### ISSUE TITLE
Make headlines permalink-able

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1004]
Let's do whatever it takes to make it performant, non-obtrusive, intuitive, and accessible to link to headings. 
In today's `master` the only way you can make a link to a heading is if you scroll up and find the TOC in the sidebar (on mobile it's much more hidden). 

Note! I think we should still keep the TOC tables in the sidebar. 

There are two potential ways to do permalink-able headings. The way npmjs.com and github.com does READMES
that there's a little "chain icon" that appears to the left (or to the right) when you hover over the link. 
<img width="594" alt="Screen Shot 2020-07-31 at 7 27 32 AM" src="https://user-images.githubusercontent.com/26739/89030908-6dde4c80-d2ff-11ea-8df0-386687596c1f.png">

Another approach is to simply turn every heading into a "self-link" like docs.github.com does. 
[Example page](https://docs.github.com/en/github/administering-a-repository/keeping-your-actions-up-to-date-with-github-dependabot)
The headings are basically like this:

```html
<h3 id="enabling-github-dependabot-version-updates-for-actions">
  <a href="#enabling-github-dependabot-version-updates-for-actions">
    Enabling GitHub Dependabot version updates for actions</a></h3>
```

The advantages of that are that it requires 0 CSS and 0 JS to make it happen, and it works without a mouse device.

**Comment by peterbe** [comment]
I definitely favor the way docs.github.com does it and I'm confident it can be done pretty easily with Yari since we control the HTML as a DOM (with `cheerio`). 

I think it's up to @schalkneethling and @malqinneh to decide and perhaps they prefer to push this out to the design system process. 

But it might be worth it for the dev team (hi @escattone and @Gregoor ) to consider throwing this in now as an HTML thing and then `mdn-minimalist` can style it. 

What do you think?

**Comment by peterbe** [comment]
Whatever we build, let's not build a thing that requires some client-side JavaScript to mutate the DOM based on some query selectors.

**Comment by peterbe** [comment]
@escattone What would it take to write a piece of `cheerio` mutation that turns `<h2 id="text_and_stuff">Text & Stuff</h2>` into `<h2 id="text_and_stuff"><a href="#text_and_stuff">Text & Stuff</a></h2>`?
I know it's possible and not hard to do with `cheerio` but I'm not familiar with the repercussions with live samples.

**Comment by escattone** [comment]
@peterbe 👍 We could definitely do that without any repercussion to the live samples.

**Comment by peterbe** [comment]
Oops. Typo in the string interpolation in https://github.com/mdn/yari/pull/1061/commits/0b47590c700b148840dbfe0d8b7c0762823e92a3
