### ISSUE TITLE
readOnly indicators hard to read in kumastyles

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1007]
On http://localhost:3000/en-US/docs/Web/API/MediaStream you'll see
<img width="904" alt="Screen Shot 2020-07-31 at 1 27 12 PM" src="https://user-images.githubusercontent.com/26739/89060818-a860dd00-d331-11ea-8f47-86e149c7e2e3.png">
If we launch Yari1 with `kumastyles`, we should fix that. 

But if `mdn-minimalist` and Fiori manages to get in first, we don't need to.

**Comment by peterbe** [comment]
@schalkneethling Would you mind being responsible for this one? CC @tobinmori 
I'm not sure how to best tag this but I'm thinking it could be tagged as `Yari1 blocker` if that was a tag.

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/pull/1776

**Comment by peterbe** [comment]
This is what it looks like now:
<img width="964" alt="Screen Shot 2020-11-20 at 11 16 52 AM" src="https://user-images.githubusercontent.com/26739/99823049-e7ee4780-2b21-11eb-8836-810c51b09dae.png">

Are sure those badges are readable enough. It looks a bit strange that the badge's whiteish background color is nearly identical to the background. Kinda looks like it's not working correctly. Reopen if you agree.

**Comment by schalkneethling** [comment]
> Are sure those badges are readable enough. It looks a bit strange that the badge's whiteish background color is nearly identical to the background. Kinda looks like it's not working correctly. Reopen if you agree.

Yip. there is an issue for that on the minimalist side. So basically, I need to give it a slightly darker background in general, and then the lighter one when displayed inside a table.
