### ISSUE TITLE
<position> Formal Syntax does not match the spec

### ISSUE THREAD

**Issue by sidewayss** [mdn/yari#10098]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/position_value

### What specific section or headline is this issue about?

#formal_syntax

### What information was incorrect, unhelpful, or incomplete?

This page:
```
<position> = 
  [ left | center | right ] || [ top | center | bottom ]  |
```
[The spec](https://drafts.csswg.org/css-values/#position):
```
 <position> = [
  [ left | center | right | top | bottom | <length-percentage> ]
|
  [ left | center | right ] && [ top | center | bottom ]
|
```
Below that they are the same text, formatted differently.

### What did you expect to see?

The same text as in the spec.

**Comment by caugner** [comment]
Thanks for reporting, I was expecting Dependabot to keep that package up to date, but it looks like [this comment](https://github.com/mdn/yari/pull/9285#issuecomment-1640371076) of mine prevented it from doing so.

https://github.com/mdn/yari/pull/10110 should fix this.
