### ISSUE TITLE
Bad BCD queries don't work when Kumascript doesn't work

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1011]
The original design of the `bad_bcd_query` flaw was when `kumascript`'s BCD macro produces something like this:
```html
<div class="bc-data" id="bcd:html.elements.canvas">
```
...and it double checks that query against the mdn-browser-compat-data here: https://github.com/mdn/yari/blob/538dd9c86013561ae48bd9e2a052f7ee4faa7d5e/build/flaws.js#L92-L110

So basically, it checks the query used by kumascript. The chances of kumascript succeeding to make a BCD table, that the Yari builder can replace with its own React-based implementation, is near nil. 

Instead, imagine you do this:
```
<p>{{Compat("html.elements.canvasOOPSTYPO")}}</p>
```
what you should get is a flaw saying that `html.elements.canvasOOPSTYPO` is not a valid BCD query. 

But you get nothing :(
I opened http://localhost:3000/en-US/docs/Web/HTML/Element/canvas and did a replacement from `<p>{{Compat("html.elements.canvas")}}</p>` to `<p>{{Compat("html.elements.canvasXXX")}}</p>` and all you get is this:

<img width="822" alt="Screen Shot 2020-07-31 at 3 18 05 PM" src="https://user-images.githubusercontent.com/26739/89069407-14970d00-d341-11ea-849d-1b36cde1b26d.png">

and noting in the ["Show flaws"](http://localhost:3000/en-US/docs/Web/HTML/Element/canvas#_flaws)

**Comment by peterbe** [comment]
@escattone What do you think, the incorrect usage of the `Compat()` macro is a flaw because it's not right and it's not a fatal disaster. But should be it a `macros` flaw or one of these `bad_bcd_query` which I prototyped but clearly misunderstood so it's never happening. 

Clearly, what you type into those `{{SomeMacro(THIS_HERE)}}` calls, we usually treat as a `macros` flaw, but what *could* be the problem is that you've typed it as perfectly as you can, but the reason it's not working is that the query hasn't made it into `mdn-browser-compat-data` yet. 

I could go either way. Either we turn this into a new macro error or we edit the Compat macro so that when the query doesn't match anything it produces a structured HTML output that the Yari flaw detection (cheerio stuff) can detect and flag.

**Comment by escattone** [comment]
@peterbe Hm, I'm not sure. Let's talk the pros and cons of each way in our 1:1 on Monday?

**Comment by peterbe** [comment]
Let's just change the error message so that Yari can deal with the "flawness".

**Comment by peterbe** [comment]
We chatted about this and concluded that it should be done in Yari content/build rather than inside the macro. The reasoning is that if you've typed `<p>{{Compat("html.elements.canvas")}}</p>` (or `<p>{{Compat("html.elements.canvasOOPSTYPO")}}</p>` for that matter)
It's actually nothing wrong from a kumascript point of view. The wrong is between you and `mdn-browser-compat-data` and having a dedicated flaw for this makes sense.
