### ISSUE TITLE
Watcher is not noticing changes

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1012]
I think this broke in the rush to wrap up Reductio

Steps to reproduce:

1. Go to http://localhost:3000/en-US/docs/Web/HTML/Element/canvas
2. Open content/files/en-us/web/html/element/canvas/index.html and make a change
3. Keep an eye on http://localhost:3000/en-US/docs/Web/HTML/Element/canvas
4. Not reloaded with the recent changes :(

Expected the page to refresh without a full browser document reload.

**Comment by peterbe** [comment]
Pretty sure the problem is that the watcher isn't sending anything to the WebSocket. I put in a `console.log` into the `WSSProvider` 's `onmessage` function and nothing's happening there when I edit a file on the file system. 

Ideas @Gregoor

**Comment by peterbe** [comment]
I looked into it a bit and I'm baffled. I put in these console.log statements:

```javascript
watcher.on("add", (filePath) => {
  console.log(filePath, "ADD");
  postDocumentInfo(filePath, "added");
});
watcher.on("change", (filePath) => {
  console.log(filePath, "CHANGED");
  postDocumentInfo(filePath, "updated");
});
```
And I get the "ADD" lines (when `nodemon` restarts) but **never** the "CHANGED" lines.

**Comment by peterbe** [comment]
I wanted to know if it was a problem with node workers so I wrote this:
```javascript
const path = require("path");
const chokidar = require("chokidar");
const { CONTENT_ROOT } = require("content");

const watcher = chokidar.watch(
  // For now, brutally hardcode it to only the 'en-us' folders
  // until we have a resolution on L10n.
  [path.join(CONTENT_ROOT, "en-us", "**", "*.html")]
);

watcher.on("ready", () => {
  console.log(
    `Watching over ${Object.keys(
      watcher.getWatched()
    ).length.toLocaleString()} files.`
  );
});

watcher.on("add", (filePath) => {
  console.log(filePath, "ADD");
});
watcher.on("change", (filePath, stat) => {
  console.log(filePath, "CHANGED", stat);
});

```

when you run that with `node` it correctly prints a bunch of files with the `ADD` suffix but nothing happens when I change any of the files it said it added.

**Comment by peterbe** [comment]
We are on the latest version but something did change in chokidar 3.4.1 which was very recently. Perhaps they broke something.
https://github.com/paulmillr/chokidar/blob/master/.github/full_changelog.md

**Comment by Gregoor** [comment]
I'm sorry to report that we might have an OS specific problem here. It works like a charme on my machine, i.e. I'm still getting the CHANGED events with the most recent version of master. Do you want to see if downgrading chokidar fixes the problem foryou?

**Comment by peterbe** [comment]
Got resolved with an upgrade. (Or, was it a computer restart?)
