### ISSUE TITLE
Error in minmax() drops the CSS declaration

### ISSUE THREAD

**Issue by pepelsbey** [mdn/yari#10137]
### Summary

[There’s a declaration](https://github.com/mdn/yari/blob/main/client/src/settings/index.scss#L23) with `minmax()` that’s not applied. That’s fair since it [requires two values](https://developer.mozilla.org/en-US/docs/Web/CSS/minmax).

```css
li {
  grid-template-columns: 1fr minmax(5em);
}
```

I noticed by looking at the console:

> Error in parsing value for ‘grid-template-columns’.  Declaration dropped.

### URL

https://developer.mozilla.org/en-US/blog/

### Reproduction steps

1. Go to [URL](https://developer.mozilla.org/en-US/blog/)
2. Check the console

### Expected behavior

This declaration is either fixed or removed.

### Actual behavior

Error on console and possible wrong behavior.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
@pepelsbey Mind opening a PR to change it to `grid-template-columns: 1fr 5em;`?
