### ISSUE TITLE
Publish built client & ssr

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#1017]
The first prototype of our NPM published yari CLI will be pretty similar to what we currently have. There are optimizations to be had here though, which will reduce the dependencies people have to install when using it (and with that the size).

The idea would be to have a pre-publish hook that builds out ssr and client, thereby moving the typescript, webpack, sass, etc. dependencies to devDependencies (which aren't installed when you `npm install` something).

**Comment by peterbe** [comment]
A not so crazy idea is that we lump scripts a bit. 

I guess the idea is that someone does this:
```
git clone url/to/mdn-content && cd mdn-content
yarn install
yarn start
```

Periodically, they're supposed to do something like this:
```
git pull upstream master
yarn install
yarn start
```

Also, it's not unrealistic that someone (working on the content, not the yari thing) does:
```
yarn start
# some time passes
yarn start
# some time passes
yarn start
# some time passes
yarn start
```

So it'd be kinda annoying if we rearrange the meaning of `start` to actually be a script that runs `yarn install` and `yari build:client` and `yarn build:ssr`. 

In general, every time people `git pull` it's likely that `yarn.lock` will have changed and that means you should run yari's build stuff. Yes, it would be nice if yari could ship a non-dev server but I don't think it's that easy. 

So, the nice middle ground would be a new script that does all the things:

```json
"scripts": {
  "boot": "yarn install && yari build:client && yari build:ssr"
}
```

That's less magical and it's less fancy tricks. Just a convenient wrapper for all the things you're supposed to remember to do between topic branch work. 

It might be worth forcing in a husky script that blabbers about what you're supposed to do every time you've done a `git pull`.

**Comment by peterbe** [comment]
This got done but I lost the PR that was the one that did it. 

For the record, the solution became to build the whole front-end with `REACT_APP_CRUD_MODE=true` and `NODE_ENV=production` and then ship that in the NPM tarball. Include the `client/build` but discard the `client/src`.
