### ISSUE TITLE
Issue with top navigation

### ISSUE THREAD

**Issue by awut-star** [mdn/yari#10178]
### Summary

There is a gap between the navigation bar and the browser toolbar.

### URL

All pages with this navigation bar.

### Reproduction steps

1.Scroll down until the navigation bar is at the top of the page, i.e., 'AI Help' is no longer visible on the page.
2.Scroll down, and you'll see that some elements will be displayed in this gap.

https://github.com/mdn/yari/assets/90757590/052e8c35-71c4-4dcc-96e5-c034d3cfb4c0

![20231](https://github.com/mdn/yari/assets/90757590/aec05ae9-dc3b-4635-91f6-7fdef7309e10)

### Expected behavior

There should be no gap between the navigation bar and the browser toolbar.

### Actual behavior

The gap between the navigation bar and the browser toolbar.

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Thank you for taking the time to report this issue @awut-star. 👍 

We're already tracking it in https://github.com/mdn/yari/issues/9159, so I'm going ahead and close this issue as a duplicate.
