### ISSUE TITLE
"Play" page does not successfully run example at enclosed link

### ISSUE THREAD

**Issue by its-all-waves** [mdn/yari#10187]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#html-only_dialog

### What information was incorrect, unhelpful, or incomplete?

In both FF and Chrome, in the "play" page, this code example does not run as stated. Hitting the "OK" button does not close the dialog. Back at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#html-only_dialog, however, under "Result," the "OK" button _does_ close the dialog. In short, it seems something is wrong with https://developer.mozilla.org/en-US/play. 

### What did you expect to see?

I expected the "OK" button to close the dialog as the example states it should.

### Do you have anything more you want to share?

Oddly, the following example runs as expected in the "play" page @ https://developer.mozilla.org/en-US/play.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/html/element/dialog`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/html/element/dialog/index.md
* Last commit: https://github.com/mdn/content/commit/bed59f268d5e299beb538e435f08c4f4ce685980
* Document last modified: 2023-11-20T15:37:12.000Z

</details>

**Comment by bsmth** [comment]
Thanks for reporting this one @its-all-waves I've moved it over to Yari which I think is the right place for this.

**Comment by mirunacurtean** [comment]
@its-all-waves Could you verify if this still occurs and if so specify on which OS/browser is it happening?
I've tried to reproduce it on Windows 11 on the latest FF and Chrome browsers and on MacOS Ventura on Safari and Firefox as well and it's working as expected, by closing the dialog box when clicking on the "Ok" button. 

https://github.com/mdn/yari/assets/53306802/a300d212-ad1a-4e3a-b940-b519049105d1



https://github.com/mdn/yari/assets/53306802/326a421b-2395-4724-aa4f-c5a600f44e08

**Comment by mirunacurtean** [comment]
> @its-all-waves Could you verify if this still occurs and if so specify on which OS/browser is it happening? I've tried to reproduce it on Windows 11 on the latest FF and Chrome browsers and on MacOS Ventura on Safari and Firefox as well and it's working as expected, by closing the dialog box when clicking on the "Ok" button.
> 
>  Wind.11.FF.Playground.example.is.working.mov 
>  Safari.playground.example.is.working.mov

Marking this as closed.

**Comment by devonbreary72-ctrl** [comment]
🎛2021 dishes haydywysyqyysy saw day Tatyana a stay saw what saw stay saw stayer dhxhchfhshsyqysydysyywyaysysx
