### ISSUE TITLE
Image without 'alt' text flaw checking

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1018]
Checking that an image has an alt text is quite tricky because it's hard to find it in the source. 
For example, `<img src="fine.png">` should be a flaw but how do you find *where in the HTML that appears*? 
It's not so easy because what if you have this:
```html
<img src="fine.png" alt="I have one"> OK
<img src="fine.png"> NOT OK
``` 
And now do you distinguish between?:
```html
<img>
<img alt>
<img alt="">
```

When analyzing a `cheerio` instance you don't get the HTML as it appears in the original source text so you can't do `$(element).html()` because that's potentially different.

**Comment by peterbe** [comment]
Perhaps a good start is to check and log a flaw without attempting to point out where in the HTML it exists. E.g.

```javascript
$("img").each((i, element) => {
  var img = $(element)
  if (img.attrs('alt')) {
    addImageAltFlaw(img.html());
  }
})
```
...without attempting to point out exactly where in the source HTML it appears.

**Comment by peterbe** [comment]
The hardest thing would be to know what to do with the `alt` texts once if you've discovered that a particular `<img src="..." alt="">` is in use. 
Suppose you wanted to work on this, in the content, you can probably get a very long way simply by git grepping for `alt=""` 
```
▶ cd content/files/en-us
▶ rg 'alt=""' | wc -l
    1101
```

**Comment by caugner** [comment]
@nschonni Once https://github.com/mdn/content/issues/21616 is resolved, how can we best ensure that new images are always added with alt text? Maybe with markdownlint?!

**Comment by nschonni** [comment]
Yes, that will happen with https://github.com/mdn/content/pull/20110

**Comment by caugner** [comment]
Perfect, thanks! Closing this issue in favor of [that solution](https://github.com/mdn/content/pull/20110). 👍
