### ISSUE TITLE
Add more to the autocomplete titles for search

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1022]
http://localhost:5000/en-US/docs/Web/HTML/Element/audio for example as a title of:
```
<audio>: The Embed Audio element
```
and it's showing up nicely when you search for `aud`
<img width="375" alt="Screen Shot 2020-08-04 at 4 34 23 PM" src="https://user-images.githubusercontent.com/26739/89342186-68229700-d670-11ea-9c10-d1690ccf1a3b.png">

But it's not working very well if you combine `audio` with other, arguably, relevant words like `html audio` which isn't an unrealistic search term.
<img width="387" alt="Screen Shot 2020-08-04 at 4 35 39 PM" src="https://user-images.githubusercontent.com/26739/89342323-a029da00-d670-11ea-8358-57f6a1d46c1a.png">

Oftentimes, there's a lot of value in referring to terms that happens to not be in the document title but could be inferred from the context.

**Comment by peterbe** [comment]
I did experiment with 
```diff
diff --git a/client/src/search.tsx b/client/src/search.tsx
index 7eec1bfed..2f4b9283f 100644
--- a/client/src/search.tsx
+++ b/client/src/search.tsx
@@ -70,6 +70,11 @@ function useSearchIndex(): [null | SearchIndex, null | Error, () => void] {
     const urls = data.map(({ url, title }, i) => {
       // XXX investigate if it's faster to add all at once
       // https://github.com/nextapps-de/flexsearch/#addupdateremove-documents-tofrom-the-index
+      const path = url
+        .split("/")
+        .map((x) => x.replace(/_/g, " "))
+        .slice(3);
+      title += " " + path.slice(path.length - 3, path.length - 1).join(" ");
       flex.add(i, title);
       return url;
     });

```
and it works pretty well. But it definitely needs more sleeping on. It'd be nice to stall on this one until we start noticing patterns and complaints from real users.

**Comment by caugner** [comment]
This seems no longer to be an issue, as the quicksearch only shows items matching all query terms:

<img width="799" alt="image" src="https://user-images.githubusercontent.com/495429/204928141-67f17e77-2ea1-4e48-af6e-7158913c6daa.png">
