### ISSUE TITLE
Order for which banner to show is unpredictable

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1024]
There are actually two problems with [this code](https://github.com/mdn/yari/blob/466da141666075500106ae1d7706478f01b3a3c2/client/src/banners/active-banner.tsx#L226-L241).

1.  If you loop like that you can never guarantee the order of the banners if, under certain circumstances, there are more than one banner waffle flag on.
2. If you have already have a subscription, (and the subscription_banner is on), it won't even attempt any of the other banners.

**Comment by peterbe** [comment]
@schalkneethling @malqinneh If I work on this, can I just take the liberty of deleting the l10nsurvey banner code?

**Comment by malqinneh** [comment]
Fine by me.

**Comment by peterbe** [comment]
What about porting the **user interviews** banner from Yari and thus assume that it'll be obsolete by the time Yari reaches any state of production?

**Comment by schalkneethling** [comment]
> What about porting the **user interviews** banner from Yari and thus assume that it'll be obsolete by the time Yari reaches any state of production?

You can safely remove that one as well. Thanks, Peter.
