### ISSUE TITLE
Is it possible to show locale title instead of the last path string in `main menu of module` for macros?

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/yari#10274]
Related to https://github.com/mdn/translated-content/issues/13881.

Our main menus of module display the last path string:

https://github.com/mdn/yari/blob/6b54c603da801cd0abbef4cbdf475084aa146960/kumascript/macros/PreviousMenuNext.ejs#L46-L51

In locale, we only can only see the English title (i.e. the last past string):
![image](https://github.com/mdn/translated-content/assets/69554233/f438d010-686c-4a50-aaa0-ed1cabed84f5)

Is it possible to show locale title instead of the last path string?

**Comment by awxiaoxian2020** [comment]
ping @yin1999 for ideas :)

**Comment by yin1999** [comment]
Displaying localized titles would be better. I'm trying to embed localized titles into the page info in the macro system (#8241). But before this could be landed, we can only implement this in the following way:

1. generate the full, localized slug with the `env.locale` variable
2. call [`getPageByURL`](https://github.com/mdn/yari/blob/6b54c603da801cd0abbef4cbdf475084aa146960/kumascript/src/info.ts#L153) method to get the page info, if the page does not exist, fallback to the en-US title, else use the title field in the returned object.
