### ISSUE TITLE
Live sample not working in '2D collision detection‘

### ISSUE THREAD

**Issue by jasonren0403** [mdn/yari#10273]
### Summary

Two live samples in this document doesn't work well. The shape needed do not display in the live sample.

### URL

https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection

### Reproduction steps

1. Open document above
2. Observe the live samples under [Axis-Aligned Bounding Box](https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection#axis-aligned_bounding_box) and [Circle Collision](https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection#circle_collision)
3.

### Expected behavior

The live sample should be loaded and worked well

### Actual behavior

Only the text shows in live sample.

Also, the console errors like this:

![image](https://github.com/mdn/yari/assets/40999116/0e0b6429-2415-4a2f-997c-254c7c29570f)

I'm using Edge, and observing similar issues on Chrome and Firefox too.

### Device

Desktop

### Browser

Edge

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by pseudopilot** [comment]
Can it be assigned to me? I found the problem and making a fix already.

**Comment by yin1999** [comment]
> Can it be assigned to me, please? I found the problem and making a fix already.

Hey @pseudopilot. I think you can have a try on this, as this issue has neither been assigned to anyone else nor marked as "on hold".
