### ISSUE TITLE
Canonical URL and robots meta tags

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#103]
As we're building up Stumptown and our tooling for deployment, we will need to set the right canonical URL meta tags so that Google doesn't pick it up and think it's a plagiarising copy. Best would be to simply tell Google bot to not pick up anything unless it's explicitly configured to do so. 

Ideally, we don't want any search engine bot traffic and this can either be done with a robots.txt or `<meta name="robots" content="...">` tags. Which is best? 

Some day, the renderer will be used for the final production site that we *want* google bot to pick up. That would be an explicit environment variable that we only set on one single site.

**Comment by peterbe** [comment]
For the moment, to break this up a bit, I think we should start with putting 
```html
<link rel="canonical" href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video">
```
for every `$document.mdn_url` on every rendered HTML page.

**Comment by peterbe** [comment]
@tobinmori This one is critical for the MVP. (assuming we have a somewhat similar picture of what the MVP is)
Basically, it's *critical* that we never put up a site (e.g. yari-mvp.developer.mozilla.org or pr1234.yari-mdn.io), with the MDN content, without the correct `canonical` head tags otherwise we run the risk of having it indexed in search engines. 

I wrote [a PR](https://github.com/mdn/yari/pull/165) a long time ago but it's dead. However, it contains some fundamentally good ideas.

**Comment by tobinmori** [comment]
thanks @peterbe. this makes sense to me. we'll add it to the heap!

**Comment by peterbe** [comment]
I have a very simple solution to this!
We simply hardcode the prefix `https://developer.mozilla.org` in the template rendering. Always. That way, it can't ever go wrong. And it's like that in production anyway. 

```
▶ curl https://developer.mozilla.org/en-US/docs/Web/JavaScript 2>&1 | rg canonical
  <link rel="canonical" href="https://developer.mozilla.org/en-US/docs/Web/JavaScript" >
```
