### ISSUE TITLE
Memoize Redirects.resolve()

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1030]
Title says it all. 

BUT, let's keep [this](https://github.com/mdn/yari/issues/1027) in mind. 

Only need to do it if it matters when doing mass-builds.

**Comment by peterbe** [comment]
Silly me. It's arguably already memoized. The `Redirects.resolve` is a curried function that uses closure to return a function that uses a simple object (`O(1)`) lookup.

**Comment by Gregoor** [comment]
Well your thinking was right given all the talk about doing things just-in-time, it's kind of surprising that I didn't follow through with it with redirects. For a second I was considering turning that file into a JSON, which might be a lot quicker to parse (and I still kind of think it should be JSON, for simplicity's sake). But then it also didn't seem worth making a fuss over. Still curious to hear your thoughts on it though.

**Comment by peterbe** [comment]
I see your point. It might not make sense as a .txt file if humans aren't really supposed to be messing with it anyway. (i.e. they should be using a CLI or a web UI thing). 
Food for thought, sure.
I think we lost our momentum on the CRUD and Toolbar right after the PVP. It's definitely important to help content authors with this kind of stuff.
