### ISSUE TITLE
DOMContentLoaded event is not fired

### ISSUE THREAD

**Issue by Namchee** [mdn/yari#10310]
### Summary

`DOMContentLoaded` event isn't fired by the playground code. This makes every code that depends on `DOMContentLoaded` breaks as they won't be executed.

### URL

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role

### Reproduction steps

1. Visit the page
2. Open the code in playground by clicking the `Play` link
3. Issue reproduced

### Expected behavior

The tabs should be navigatable with `Tab` and arrow keys.

### Actual behavior

Tab example doesn't work since `DOMContentLoaded` event is not fired at all.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Linux

### Anything else?

This issue came from https://github.com/mdn/content/pull/29889

Can be hacked by listening to `readyState` instead. [Sample PR](https://github.com/mdn/content/pull/29889).

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by Amirko22** [comment]
> ### Summary
> 
> `DOMContentLoaded` event isn't fired by the playground code. This makes every code that depends on `DOMContentLoaded` breaks as they won't be executed.
> ### URL
> 
> https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role
> ### Reproduction steps
> 
>     1. Visit the page
> 
>     2. Open the code in playground by clicking the `Play` link
> 
>     3. Issue reproduced
> 
> 
> ### Expected behavior
> 
> The tabs should be navigatable with `Tab` and arrow keys.
> ### Actual behavior
> 
> Tab example doesn't work since `DOMContentLoaded` event is not fired at all.
> ### Device
> 
> Desktop
> ### Browser
> 
> Chrome
> ### Browser version
> 
> Stable
> ### Operating system
> 
> Linux
> ### Screenshot
> 
> _No response_
> ### Anything else?
> 
> This issue came from [mdn/content#29889](https://github.com/mdn/content/pull/29889)
> 
> Can be hacked by listening to `readyState` instead. [Sample PR](https://github.com/mdn/content/pull/29889).
> ### Validations
> 
>     * [x]  I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
> 
>     * [x]  I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
> 
>     * [x]  I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by Amirko22** [comment]
https://github.com/Amirko22/Amirko22/tree/main

**Comment by Amirko22** [comment]
- [ ]

**Comment by wbamberg** [comment]
@caugner, this does not seem to be fixed by https://github.com/mdn/yari/pull/10770 .

**Comment by caugner** [comment]
@wbamberg [Works for me](https://developer.mozilla.org/en-US/play?id=6mBqNlYKU1OWSh8GvoETbq31yf6O%2BzUxpcWTpeKlkv69tx1FcTiFPaawBbdETfjtk%2Bk%2F1F0z2v1FefXx). Please open a [new issue](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml) for the problem you're experiencing..
