### ISSUE TITLE
Playground usability

### ISSUE THREAD

**Issue by shivakgurung** [mdn/yari#10326]
### What information was incorrect, unhelpful, or incomplete?

Playground

### What did you expect to see?

Increased ease of use and size and layout adjustable playground.

**Comment by bsmth** [comment]
Hi @shivakgurung do you mean the editors at https://developer.mozilla.org/en-US/play?

**Comment by caugner** [comment]
Closing as duplicate in favor of https://github.com/mdn/yari/issues/9556.
