### ISSUE TITLE
Our memoize utility function might be dangerous

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1034]
We're using `memoize()` in at least two places. 

* https://github.com/mdn/yari/blob/16ddd65643cf2521f8ee6dcf1513e3f821f1cc5e/content/document.js#L122
* https://github.com/mdn/yari/blob/16ddd65643cf2521f8ee6dcf1513e3f821f1cc5e/kumascript/index.js#L16

The first argument in the functions it wraps are dangerously similar. 
For example, when it's `Document.read` the key is `en-us/web/html/element/video` and when it's `renderFromURL` (in `kumascript` ) it's `/en-US/docs/Web/HTML/Element/video`.
They're different but are we just lucky?
If we implement https://github.com/mdn/yari/issues/1030 we might be using the same first key and if the key is identical you get very wrong cache hits. 

Perhaps we should have a prefix like:
```javascript
const read = memoize('Document.read', (folder, fields = null) => {
```
or 
```javascript
const read = memoize('Document.read')(folder, fields = null) => {
```

**Comment by Gregoor** [comment]
I'm not sure if I'm misunderstanding but if you are saying that the two memoize calls are sharing the same cache, I can lay that worry to rest, as the cache is bound to each invocation. I.e. anytime you wrap a function inside of memoize, a new cache is instantiated and only used for calls to the (returned) function.

**Comment by peterbe** [comment]
Right you are! Phew. Thanks for the sanity check.
