### ISSUE TITLE
Play - Excessive time to execute examples

### ISSUE THREAD

**Issue by nihaopaul** [mdn/yari#10351]
### What information was incorrect, unhelpful, or incomplete?

the examples do not execute, browser: chrome v120 mac sonoma

seems its stuck waiting for runner.html to execute as its always pending. 
![image](https://github.com/mdn/interactive-examples/assets/519051/2a8aa30a-5864-4dbe-bd67-7e2c7ece8bff)

### What did you expect to see?

expected to see the examples execute.. 

![image](https://github.com/mdn/interactive-examples/assets/519051/cb4ef3ae-06c5-4cfa-a99f-a0006629f04f)

### Do you have any supporting links, references, or citations?

![image](https://github.com/mdn/interactive-examples/assets/519051/a0b54098-84d3-4b7b-a916-bcf6ad7d1131)

### Do you have anything more you want to share?

seems runner.html is stuck doing something, i waited 60 seconds and then runner was no longer pending but the results didnt appear, upon clicking run again it worked.

**Comment by argl** [comment]
Unfortunately, I could not reproduce the issue. Please feel free to reopen if the problem persists.
