### ISSUE TITLE
Let's do something more about MacroExecutionErrors

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1041]
See http://localhost:3000/en-US/docs/Web/HTML/Element/input/search#attr-spellcheck
What you see is this:

<img width="700" alt="Screen Shot 2020-08-07 at 11 05 34 AM" src="https://user-images.githubusercontent.com/26739/89659688-35f67c80-d89e-11ea-8523-ea60b497d628.png">

When you're in previewing mode (`localhost:3000`), it's just a little bit too "discrete". It should probably "stand out" more to grab a human's attention to take care of it. Yes, we have the "Show flaws" UI but it's still potentially not enough. 

When in production mode (`localhost:5000`), it, today, actually looks exactly the same. I think there it should say something "less screamy" but more proactive and helpful like:

```html
<p class="macro-error">
Sorry. An error occurred right here rendering this text inclusion. <br>
To learn more or to help out go to <a href="/en-US/docs/MDN/Getting_Started">learn about how to contribute</a>.
</p>
```

(PS. we could leverage `NODE_ENV==='development'` here and load some extra CSS that makes that more red and standing out)

Some help from @schalkneethling and @malqinneh would be appreciated here. We can break this apart between some necessary `kumascript` rendering stuff and some design work. Plus a shared chat about the correct and appropriate wording/prose.

**Comment by peterbe** [comment]
@escattone @schalkneethling What do you think we should do here. 

Perhaps we can punt on it and after the launch we can be ultra strict in our flaw checking in PR builds and thus it would become very hard to make this happen at all. 

But mind you, we still get a lot of `MacroExectionError` macros.

**Comment by peterbe** [comment]
@escattone It'd be nice to not allow any MacroExecutionErrors by putting up a super strict CI so that the `main` branch never has anything that can cause any `MacroExecutionErrors`. But I still don't know if's feasible, because someone might do merry work on a page, and their CI PR build is all good, but not realize that some other document depended on it and that's something you wouldn't find out until it's too late.

**Comment by peterbe** [comment]
I definitely think it would be more useful and productive if we catch and failures and (depending on `NODE_ENV`) show a custom warning banner there instead of just showing the kumascript source input. In that banner we'd get a chance to lure the reader into helping out the project. We could for example include a link to create a new issue in mdn/content with the title and part of the description all prefilled.

**Comment by peterbe** [comment]
@escattone Do you think this should be a Yari1 blocker?

**Comment by escattone** [comment]
@peterbe @schalkneethling @chrisdavidmills @HerminaC 

I don't think we're going to be able to address any (or at least most) of the macro errors prior to the December launch, so the question is how do we display these macro errors (that occur during the build). We could:
1. Just do what we do now in Yari, and show the failed macro call on the page, like `{{page("/en-US/docs/Web/HTML/Element/input/text", "spellcheck-include")}}`. Currently on MDN, many but not all of these errors fail silently (for example, the section on the page Peter mentioned above https://developer.mozila.org/en-US/docs/Web/HTML/Element/input/search#attr-spellcheck), so even showing what we do now is often different than what MDN currently does.
1. Do what Peter is suggesting as an option, and make the failure a little more visible so we draw attention to it and perhaps suggest ways to contribute a fix.
1. Something else.

Given that we have our hands full with our current list of tasks, as well as any work that arises from the beta launch, I'm thinking we should choose the first option for now, which is to say we do nothing. After the launch we'll tackle the large list of flaws in the documents (many of which are automatically fixable with our existing flaws tools). However, if we find we have the time before the official launch, we may want to do @peterbe's suggested option.

**Comment by peterbe** [comment]
For the record if we do display some HTML of our own, instead of just `{{MacroThatFailedHard}}` we should have some styling. I asked @schalkneethling to file an issue about creating something we can use.

**Comment by mattiapontonio** [comment]
Beyond the rest of the management I believe that in CSS it needs to start from the `.error` class and eventually extend in the future. In the end it should be a simple message always without further functionality.

**Comment by schalkneethling** [comment]
@escattone Do we still these often enough to warrant addressing it? If we do, I would need to understand how to trigger a failed execution so that we can "inject" the relevant HTML or classes. Thanks

**Comment by escattone** [comment]
@schalkneethling Hm, I don't think so. I think we should close this, at least for now, and we can revisit it later if we have to.

**Comment by teoli2003** [comment]
I think we are close to 0 now, so we can easily investigate when new ones appear.

<img width="1130" alt="Screenshot 2021-11-09 at 19 13 34" src="https://user-images.githubusercontent.com/1466293/140980932-99a5eefb-c452-4701-84c1-5753bb2c091b.png">

Periodically checking the flaw dashboard and cleaning these is enough. In other terms, I think there are many things more important :-)

/me loves the flaw dashboard, although I don't have enough time to look at it more often.

I would support to close thiis issue.
