### ISSUE TITLE
Game Console Error

### ISSUE THREAD

**Issue by p4th4k** [mdn/yari#10457]
### Summary

The MDN Docs for 2D collision detection using Crafty.js game engine contain a bug in the provided sandbox environment. The code example within the sandbox triggers an error,"ReferenceError: Crafty is not defined", likely because Crafty.js is not present in the sandbox. This issue hinders users from successfully running and experimenting with the code in the documentation.

### URL

https://developer.mozilla.org/en-US/docs/Games/Techniques/2D_collision_detection

### Reproduction steps

1. Navigate to the MDN Docs page for 2D collision detection using Crafty.js.
2. Access the provided sandbox environment for the code example.
3. Run the code within the sandbox.

### Expected behavior

The code should run without errors, allowing users to understand and experiment with 2D collision detection using Crafty.js as intended.

### Actual behavior

"ReferenceError: Crafty is not defined"

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://github.com/mdn/yari/assets/157967122/f6ac9775-8db2-4676-8794-353e9d9b972a)

### Anything else?

Alternative Solution: An alternative to this can be to use canvas api directly to experiment with 2D Collision detection.

### Validations

- [x] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by dipikabh** [comment]
Thanks @p4th4k for opening the issue.

To add here for more context: the HTML/JS code does run successfully (eg, in a codepen) without any console errors.

**Comment by caugner** [comment]
Thanks for reporting @p4th4k, it looks like this is a known issue and has been reported before in https://github.com/mdn/yari/issues/9346.
