### ISSUE TITLE
U - Refactor Yari Deployer

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#1055]
# Acceptance Criteria
- [ ] Refactor existing deployer to work with Yari

**Comment by peterbe** [comment]
What is this issue and shall we break it down or close it?
I see this is attached to an Epic called "Implement online preview for PRs (Deployer)" which might, unfortunately, get pushed into a lower prioirity for an "urgent" Yari1 launch.

**Comment by peterbe** [comment]
Closed in favor of https://github.com/mdn/yari/issues/1106
