### ISSUE TITLE
U - Investigate Kuma API endpoints (what needs to be disabled/hidden)

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#1057]
- are there endpoint outside of /docs that we're exposing that we shouldn't?
- Vet Kuma API endpoints to make sure that we don't need to support any more in Yari
- Determine what/if we need to shutdown endpoints (pre-launch)

**Comment by mirunacurtean** [comment]
@escattone Could you please take another look at this and see if it's still valid?

**Comment by peterbe** [comment]
I checked the `/api/v1/*` endpoints and they're sane and don't need much cleaning up. 

I don't know what other endpoints still exists outside of that because there's no way to get to anything under `/$locale/docs/*` anymore.

**Comment by escattone** [comment]
Thanks @mirunacurtean and @peterbe. This issue was meant to cover what we might have to disable **prior** to the launch of Yari. We can close this.
