### ISSUE TITLE
`http://localhost:3000/<locale>/_flaws` locale page error

### ISSUE THREAD

**Issue by hochan222** [mdn/yari#10653]
### Summary

The http://localhost:3000/ko/_flaws page shows

"No documents have been built, so no flaws can be found At the moment, you have to use the command line tools to build documents that we can analyze."

even though the yarn build was completed.

### URL

`http://localhost:3000/<locale>/_flaws`

ex)
http://localhost:3000/ko/_flaws

### Reproduction steps

1. nvm use && yarn
2. yarn build 

The `/yari/client/build/ko/index.json` file was created normally.

> Built 41,917 pages in 28.7 minutes, at a rate of 24.3 documents per second.
> Peak heap memory usage: 1.60 GB
> ...
> ✨ Done in 1725.75s.

3. yarn dev

### Expected behavior

flaw page where flaw items are detected

### Actual behavior

"No documents have been built, so no flaws can be found At the moment, you have to use the command line tools to build documents that we can analyze."

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

<img width="816" alt="image" src="https://github.com/mdn/yari/assets/22424891/24040c8f-2373-49b2-b788-e4458a74d2a2">

### Anything else?

more details: https://github.com/mdn/yari/pull/10550#issuecomment-1952633010

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by hochan222** [comment]
cc. https://github.com/mdn/translated-content/issues/18056

**Comment by caugner** [comment]
@hochan222 Do you recall when this last worked, or has this always been broken?

**Comment by hochan222** [comment]
@caugner This always been broken. Also other contributor has confirmed that the same error happens.

**Comment by hochan222** [comment]
If it is working properly, please let me know the execution steps after cloning and I will check it.

**Comment by hochan222** [comment]
cc. @1ilsang

**Comment by hochan222** [comment]
@1ilsang Is it going to work out? I'm not working well. hmm...

---

- **case 1:** `git clone` => `nvm use` => `sudo yarn` => create `.env` file (for CONTENT_TRANSLATED_ROOT, CONTENT_ROOT) => `sudo yarn start` => `http://localhost:3000/ko/_flaws` => fail
- **case 2:** `git clone` => `nvm use` => `sudo yarn` => create `.env` file => `sudo yarn start` => `sudo yarn client:build` => `sudo yarn start` => `http://localhost:3000/ko/_flaws` => fail
- **case 3:** `git clone` => `nvm use` => `sudo yarn` => create `.env` file => `yarn client:build` => `sudo yarn start` => `http://localhost:3000/ko/_flaws` => fail
- **case 4:** `git clone` => `nvm use` => `sudo yarn` => create `.env` file => `sudo yarn dev` => `sudo yarn build` => `http://localhost:3000/ko/_flaws` => fail

**Comment by hochan222** [comment]
@caugner Anyway, since I built it after dev, it came out well! Thank you.

<img width="1313" alt="image" src="https://github.com/mdn/yari/assets/22424891/40d249c5-9653-45e3-b2be-86927101ebef">

**Comment by caugner** [comment]
> * **case 1:** `git clone` => `nvm use` => `sudo yarn` => create `.env` file (for CONTENT_TRANSLATED_ROOT, CONTENT_ROOT) => `sudo yarn start` => `http://localhost:3000/ko/_flaws` => fail
> 
> * **case 2:** `git clone` => `nvm use` => `sudo yarn` => create `.env` file => `sudo yarn start` => `sudo yarn client:build` => `sudo yarn start` => `http://localhost:3000/ko/_flaws` => fail
> 
> * **case 3:** `git clone` => `nvm use` => `sudo yarn` => create `.env` file => `yarn client:build` => `sudo yarn start` => `http://localhost:3000/ko/_flaws` => fail

Two questions:
1. Do you need to run yarn with sudo privileges? (This doesn't look right.)
2. Is the failure you refer to this error:
    ```
    error: ENOENT: no such file or directory, open '/path/to/yari/popularities.json'
    ```

**Comment by hochan222** [comment]
@caugner Currently, the flaws page is not working in case 1.

1. It used to fail when running without `sudo`, but now it works fine even without `sudo`.

I don't remember the error, but I think a permission error occurred in the cloud-function-related download (maybe..?) when executing the `yarn` command. **It's working fine now.**

2. By failure I meant the _flaws page error below. Also, I'm getting the following error in the [`fix-yarn-start-add-popularities` branch](https://github.com/mdn/yari/pull/10718).

<img width="1375" alt="image" src="https://github.com/mdn/yari/assets/22424891/8af2b337-1cc4-488d-abbe-a638e53832bc">

**Comment by caugner** [comment]
> I don't remember the error, but I think a permission error occurred in the cloud-function-related download

I have seen a permission-related error here: https://github.com/mdn/yari/issues/10717
Otherwise it could have been an error related to downloading `@vscode/ripgrep`, which regularly fails.

Please report the error message the next time you are seeing it.

> 2\. By failure I meant the _flaws page error below. Also, I'm getting the following error in the [`fix-yarn-start-add-popularities` branch](https://github.com/mdn/yari/pull/10718).

It might be nice if the error message said what command to run, e.g.: "Run `yarn build --locale ko` to build all documents for the current locale." Feel free to open a PR! 😉 

Since it is working fine for you now, I'm going ahead and close this issue as resolved. 🎉

**Comment by hochan222** [comment]
@caugner I understand! Confirmed that it works well!

Thank you very much for your help in resolving the difficulty.

> Feel free to open a PR!😉

Yes I will. Also, I will write [the ko locale guide](https://github.com/mdn/translated-content/tree/main/docs/ko) related to current issues.

Have a good one :)
