### ISSUE TITLE
good/bad example pre tags styling

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1066]
What it looks like [in prod](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
<img width="1079" alt="Screen Shot 2020-08-14 at 7 48 46 AM" src="https://user-images.githubusercontent.com/26739/90246505-ca169580-de02-11ea-8840-98c3638b42cf.png">

What it looks like [in yari](http://localhost:3000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map)
<img width="1006" alt="Screen Shot 2020-08-14 at 7 42 45 AM" src="https://user-images.githubusercontent.com/26739/90246531-d8fd4800-de02-11ea-8c9f-92792bff85f6.png">

**Comment by peterbe** [comment]
All that stuff sits in `kumastyles/components/syntax/_example.scss` which is imported by `_wiki-wysiwyg.scss` which is imported by `editor-content.scss` which is never imported by anyone or anything.

**Comment by peterbe** [comment]
So, quick remedy would be to just make sure we import that `_example.scss`.

**Comment by schalkneethling** [comment]
Addressed by https://github.com/mdn/mdn-minimalist/pull/281

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/pull/1862

**Comment by peterbe** [comment]
Are you sure this is good enough? In Kuma, it didn't do syntax highlighting. But now, with that new "stronger" red (compared to Kuma) it's really painful, to look at the code with that red background?
<img width="1027" alt="Screen Shot 2020-11-30 at 10 43 54 AM" src="https://user-images.githubusercontent.com/26739/100630767-f47c5800-32f8-11eb-8c0b-a8df114a8888.png">

The contrast with the red words (e.g. `Map`) on that red background is so low I have to squint. 
And that left-border is so dark that it's not at all the red that I'm used to mean "not" or "bad". 

Here, if I pick the colors from Kuma I think it's a lot more pleasant to look at:
<img width="1074" alt="Screen Shot 2020-11-30 at 10 47 11 AM" src="https://user-images.githubusercontent.com/26739/100631206-779dae00-32f9-11eb-8aed-891cc95d2559.png">

What do you think?

**Comment by schalkneethling** [comment]
@peterbe That is a good point. Especially with the syntax highlighting it is rough :)

**Comment by schalkneethling** [comment]
I have addressed this here: https://github.com/mdn/mdn-minimalist/pull/311

**Comment by peterbe** [comment]
I kicked off a Dev build. I suspect that in about 20min we'll be able to refresh https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map and see if it worked.
