### ISSUE TITLE
Update Yari kumascript with latest from https://github.com/mdn/kumascript

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1069]
When we started Yari we completely cloned the github.com/mdn/kumascript/macros into `./kumascript/macros/` and we thought perhaps we'd keep doing that until the day we let Yari take over. 
But we've already re-written so much of the macros ([example](https://github.com/mdn/yari/pull/1064/files)) so that's no longer an option. 

However, the GroupData.json file has been seeing frequent changes. [Latest here](https://github.com/mdn/kumascript/pull/1414/files)

Before we fully switch over to Yari we need to make sure we do one last "careful clone" of the macros from github.com/mdn/kumascript.

**Comment by peterbe** [comment]
Perhaps let's not focus solely on `GroupData.json` because there are probably other recently files updated too. 
https://github.com/mdn/kumascript/commits/master

**Comment by peterbe** [comment]
@escattone wanna wire this up to some checklist for the migration? I *think* you started working on that but I'm too lazy to search Google Docs now.

**Comment by escattone** [comment]
> @escattone wanna wire this up to some checklist for the migration? I _think_ you started working on that but I'm too lazy to search Google Docs now.

Done (actually a few days ago)!

**Comment by escattone** [comment]
It seems to me we can close this, since we've added it to our official launch plan, and it's something we do on launch day, not something we have to get done prior to launch day. @peterbe Thoughts?

**Comment by peterbe** [comment]
Yep. Now that it's on the launch plan doc there's nothing we can do with this issue itself.
