### ISSUE TITLE
pre > code HTML should be a flaw

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1072]
On http://localhost:3000/en-US/docs/Web/API/VRFrameData/timestamp
[We have this because](https://github.com/mdn/yari/blob/a910b8398635b01a80d39b0ee9882c7b844edd93/content/files/en-us/web/api/vrframedata/timestamp/index.html#L37-L67)

When working on https://github.com/mdn/yari/pull/1071 I can assert that Prism can actually cope with it. 
The more correct thing should have been that it should look like this: https://gist.github.com/peterbe/00f0542345210fc72a0f336bd11ce1b1
Which renders just fine:
<img width="1093" alt="Screen Shot 2020-08-14 at 5 19 58 PM" src="https://user-images.githubusercontent.com/26739/90293619-8186c880-de52-11ea-8ede-a396b72a1b5e.png">

**Comment by peterbe** [comment]
So basically, if there are `<pre>` blocks that contain `<code>` tags it should be considered a flaw. 
And it should be fixable. All you need to do is to extract the plain text (kinda like viewing it in a browser and copy the text with the mouse) and then inject it into the `<pre>` tag HTML escaped.

**Comment by peterbe** [comment]
Keep this in mind: https://github.com/mdn/yari/issues/1281
The source (i.e. the HTML files in mdn/content) should just have `<pre class="brush...">` and the code in it. E.g.
```html
<p>Check out this example:</p>
<pre class="brush:js">function foo() {}</pre>
```
But when Yari builds it, the final HTML should en up something like this:
```html
<p>Check out this example:</p>
<pre class="notranslate">
  <code>
     <span class="token">function</span> <span class="token">foo()</span> <span class="bracket">{}</span>
  </code>
</pre>
```

**Comment by escattone** [comment]
Closing, since I think this was fully addressed by @peterbe's two PR's:
- https://github.com/mdn/yari/pull/1413
- https://github.com/mdn/yari/pull/1457
