### ISSUE TITLE
Curriculum cards are not clickable

### ISSUE THREAD

**Issue by PolyDevil** [mdn/yari#10734]
### Summary

Only top half of the card is clickable.

![image](https://github.com/mdn/yari/assets/25101758/6f7060dc-cfa7-423d-aedc-be3c1b4ce938)

### URL

https://developer.mozilla.org/en-US/curriculum/

### Reproduction steps

1. Open page https://developer.mozilla.org/en-US/curriculum/
2. Try to click on the card (you have like 50% chance to click on it, since only half of it is actually clickable)

### Expected behavior

It is expected that after clicking on the card URL would change

### Actual behavior

Sometimes URL would change, sometimes it would not - depends on where you click.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Android

### Screenshot

![image](https://github.com/mdn/yari/assets/25101758/edfef2c9-8b74-443f-a194-d4ce7c9c27c1)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by mirunacurtean** [comment]
@PolyDevil Thank you for your contribution. The curriculum cards are now wholly clickable on landing page/ overview pages and through keyboard navigation as well. Closing this ticket as fixed. 

https://github.com/mdn/yari/assets/53306802/5e95da55-8513-4b0f-ada7-82ae3fd95e9b
