### ISSUE TITLE
yari's toolbar does not exist  "Open in your editor" , "View on MDN", "Edith on Github"

### ISSUE THREAD

**Issue by Byron2016** [mdn/yari#10744]
### Summary

I use:

- OS: windows 10 V22H2 (compilation 19045.4170)
- wsl
- Node: v20.11.1
- npm: 10.2.4
- yarn: 1.22.22

yari´s toolbar does not exist 

**"Open in your editor" ,  "View on MDN", "Edith on Github"**

![prototype](https://github.com/mdn/yari/assets/15000602/dff154a8-b806-44a6-8da0-08d0f25d2abf)

### URL

http://localhost:3000/es/docs/Web/JavaScript/Inheritance_and_the_prototype_chain
http://localhost:5042/es/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

### Reproduction steps

1. git clone https://github.com/Byron2016/translated-content.git --depth=1
2. git clone https://github.com/Byron2016/content.git --depth=1
3. cd content && yarn
4. git clone https://github.com/Byron2016/yari.git --depth=1
5. cd yari && git fetch &&  git pull
6. yarn
7. yarn dev

### Expected behavior

![image](https://github.com/mdn/yari/assets/15000602/b405864a-c0d0-4f50-8cca-40d47aa58a4d)

### Actual behavior

![prototype](https://github.com/mdn/yari/assets/15000602/7a9562a1-4fcf-40e7-a185-98559a993bc9)

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://github.com/mdn/yari/assets/15000602/b6c2176d-f4e6-455c-a9d8-efec34750623)

![image](https://github.com/mdn/yari/assets/15000602/e597fa02-04ec-4754-bd74-86fae8fb212c)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Hi @Byron2016, thanks for taking the time to open this issue. 👋 

You'll need to set `REACT_APP_WRITER_MODE=true` in your `.env` to enable the writer's tools, including the toolbar.

See: https://github.com/mdn/yari/blob/main/docs/envvars.md#react_app_writer_mode

I'm closing this issue as "won't fix", but please let us know if that setting doesn't work for you.
