### ISSUE TITLE
DOMContentLoaded does not fire in LiveSample

### ISSUE THREAD

**Issue by debiru** [mdn/yari#10766]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/API/Document/readystatechange_event

### What specific section or headline is this issue about?

The play function

### What information was incorrect, unhelpful, or incomplete?

https://developer.mozilla.org/en-US/docs/web/api/document/readystatechange_event#result says "load" only.

### What did you expect to see?

The result says:

```
DOMContentLoaded
readystate: complete
load
```

### Do you have anything more you want to share?

I think this issue should be addressed in the yari repository. Sorry if this has already been reported.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/api/document/readystatechange_event`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/readystatechange_event
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/readystatechange_event/index.md
* Last commit: https://github.com/mdn/content/commit/41a8b9c9832359d445d136b6d7a8a28737badc6b
* Document last modified: 2023-04-07T05:52:28.000Z

</details>

**Comment by bsmth** [comment]
Thanks a lot to both of you for reporting and investigating 🙏🏻 I've moved this over to Yari which I think is the right place for it!

**Comment by wbamberg** [comment]
@caugner, this does not seem to be fixed by https://github.com/mdn/yari/pull/10770 .

**Comment by Kaiido** [comment]
@caugner the initial report links [to a section](https://developer.mozilla.org/en-US/docs/web/api/document/readystatechange_event#result) that still reproduces the original issue. Your playground isn't listening for the evnet in the same way.  
To fix it and other related issues, you'd need to fire the DOMContentLoaded event from the document (and to make it bubble)  and to also fire a readystate event.

This issue has not been fixed yet.
