### ISSUE TITLE
Window load example regression

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#10771]
The page for https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event has an example showing the order in which `load` and `DOMContentLoaded` events are fired. As recently as [June 13, 2023](https://web.archive.org/web/20230613035502/https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) this example worked, but since the new live sample system launched [it has stopped working](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event#live_example).

Perhaps this is because in the new system `DOMContentLoaded` fires before the script runs.

**Comment by wbamberg** [comment]
@caugner, this does not seem to be fixed by https://github.com/mdn/yari/pull/10770 .

**Comment by caugner** [comment]
@wbamberg [Works for me](https://developer.mozilla.org/en-US/play?id=6mBqNlYKU1OWSh8GvoETbq31yf6O%2BzUxpcWTpeKlkv69tx1FcTiFPaawBbdETfjtk%2Bk%2F1F0z2v1FefXx). Please open a [new issue](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml) for the problem you're experiencing..

**Comment by wbamberg** [comment]
For this example: https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event#live_example

...in the output I see this:

<img width="796" alt="Screen Shot 2024-04-16 at 4 13 05 PM" src="https://github.com/mdn/yari/assets/432915/4202b9c7-baa9-42af-8213-9d005b78e08d">

...in the pre-Playground version (https://web.archive.org/web/20230322100016/https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event#live_example) I see this:

<img width="802" alt="Screen Shot 2024-04-16 at 4 14 31 PM" src="https://github.com/mdn/yari/assets/432915/0d1cd942-e475-493b-bf12-6c9009b60f67">
