### ISSUE TITLE
🐛 form submission invalid in playground

### ISSUE THREAD

**Issue by hanyujie2002** [mdn/yari#10788]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#handling_the_return_value_from_the_dialog

### What specific section or headline is this issue about?

#handling_the_return_value_from_the_dialog

### What information was incorrect, unhelpful, or incomplete?

When the example EmbedLiveSample("Handling the return value from the dialog") be played in playground, the cancel button is invalid. 

![image](https://github.com/mdn/content/assets/84226578/4e7ef028-d0bd-4342-addd-176e2f0d93ed)

However, the button is valid when the example is directly played in mdn

![image](https://github.com/mdn/content/assets/84226578/5b1a860e-8b0f-4e02-93aa-81d8558136d0)

### What did you expect to see?

The cancel button is valid when playing the example in playground

**Comment by bsmth** [comment]
> /cc @bsmth Could you transfer this :)

Sure thing, let's see what eng has to say
