### ISSUE TITLE
Use S3 logging to get rid of totally obsolete redirects

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1087]
There are sooo many redirects in the `_redirects.txt` files. Many of them are probably never ever used. 

Once we're in S3 we can enable logging, download all the logs and write a script that compares every lin in `_redirects.txt` and compares with 301 redirects in S3 hosting. Those that are never mentioned in a month can be deleted.

**Comment by escattone** [comment]
@schalkneethling I don't think so, let's close this one for now.
