### ISSUE TITLE
Move the content from yari into new mdn content repo

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1095]
Move the content from yari into new `mdn/mdn-content` repo and test it.

- [x] Make the new repo
- [x] [Publish `yari` as an `npm` package](https://github.com/mdn/yari/pull/1196)
- [x] Write the `package.json` that installs `yari` and starts it
- [x] Move the relevant CI workflows into the new repo
- [x] Auto-publish `yari` on master commits to npmjs.com
- [x] [Disable or fake the whoami stuff in this version of Yari that we ship.](https://github.com/mdn/yari/pull/1230)
- [x] Can't rely on `git branch --show-current` when running Yari from Content. 
- [x] [Post-process the rendered HTML to drop `a[title]` attributes](https://github.com/mdn/yari/issues/1248)
- [x] [Dumper to split archive from translated content](https://github.com/mdn/yari/issues/1250)
- [x] Document how the NPM stuff works

**Comment by peterbe** [comment]
YAY!!! 🎉
