### ISSUE TITLE
 Implement policy for reviewing/merging mdn content PR's

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1098]
Implement the policy for handling mdn/mdn-content repo's PR's decided in #1097.

**Comment by peterbe** [comment]
Here's a start:

1. If the PR has merge conflicts, it's on the *author* to resolve and merge in `main` to her branch and push that updated branch. 
2. If CI fails, it won't be merged. The editor and author will share the responsibility to find out why CI failed. 
3. Don't use `git rebase` on a branch that has an associated PR created. 
4. The editor has the right to close PRs that are deemed to span too many unrelated topics if the PR isn't phrased as a general solution that explains the breadth of the change.
5. If it's a non-trivial edit, there should exist an issue and that issue's ID (e.g. `#123`) should be mentioned in the PR description. 
6. Don't reopen a PR that an editor has closed.

**Comment by escattone** [comment]
@peterbe I'll add your items to the content contribution guide (`README.md`), and then I'm going to close this, since we've got the [`CODEOWNERS` file in place](https://github.com/mdn/content/blob/main/.github/CODEOWNERS) as well a contribution guide. We can work from there in terms of tweaking the contribution guide going forward.
