### ISSUE TITLE
Remove some view endpoints in Kuma 

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1099]
We need to make the following changes to https://github.com/mdn/kuma:

- [ ] Disable the following URL's/views:
    - [ ] `/<locale>/dashboards/` and all of its children
    - [ ] `/<locale>/docs.json`
    - [ ] `/<locale>/unsubscribe`

**Comment by peterbe** [comment]
Arguably, this can wait. A couple of hours at least. 

Perhaps we should have a label for `Yari1` milestone issues that are for post-migration. Same with that thing about running all the fixable flaws.

**Comment by schalkneethling** [comment]
@escattone done/worth doing?

**Comment by escattone** [comment]
Long gone and done! 😄 Thanks @schalkneethling!
