### ISSUE TITLE
List document pages that will need to be updated or deleted

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1102]
Create list of documents that either need to be updated or deleted, and determine who will update them. Here's what we know so far:

#### Need to be updated
- [ ] https://developer.mozilla.org/en-US/docs/MDN and others under its document tree (e.g., many docs talk about MDN as a Wiki)

#### Need to be deleted
- [x] https://developer.mozilla.org/en-US/docs/MDN/Doc_status and all of its sub-pages should be removed

#### Implementation
- [ ] Determine who will make the updates/deletions and when.
- [ ] Updates/removals completed.

**Comment by peterbe** [comment]
The list of subpages from within `MDN/` that we completely ignore (not even redirecting to archived content) are here:
https://github.com/mdn/yari/blob/4d2d943b9df83788d083affdc584145bada275d7/import/constants.js#L28

But I would argue that https://developer.mozilla.org/en-US/docs/MDN/Kuma/Server_charts should be in that list too. Bye bye.

**Comment by escattone** [comment]
This (and much more) was already done by @chrisdavidmills.
