### ISSUE TITLE
Fix few remaning old live-sample URL's

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1104]
Fix the few remaining old live-sample URL's referenced in the content (I found 5 of them). For example, https://mdn.mozillademos.org/en-US/docs/Web/API/HTMLImageElement/height$samples/Example --> https://mdn.mozillademos.org/en-US/docs/Web/API/HTMLImageElement/height/_samples_/Example

<img width="1190" alt="image" src="https://user-images.githubusercontent.com/3743693/90570913-8ce53700-e165-11ea-975b-00a6ac8dfb53.png">

**Comment by escattone** [comment]
This is actually a post-launch task.

**Comment by Ryuno-Ki** [comment]
Is this still relevant / open?

**Comment by escattone** [comment]
@Ryuno-Ki 👍 Yes, this is still relevant.

**Comment by peterbe** [comment]
@escattone Are there still any left? What about mdn/translated-content?

**Comment by escattone** [comment]
@peterbe Yes. There are 4 left in the English content. I'm going to tackle those today, and also check the translated-content.

**Comment by escattone** [comment]
There are no more references to old live-sample URL's in the English content, thanks to https://github.com/mdn/content/pull/4392. 🎉 However, it looks like we have about 60+ references remaining in the translated content. At least we made some progress today! 😄

**Comment by caugner** [comment]
If this wasn't already done, this work was finished in https://github.com/mdn/translated-content/issues/10400.
