### ISSUE TITLE
AWS Work

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1107]
**Some more AWS work remains to be done (and more in comments below):**

- [x] Create new `prod` and `stage` S3 buckets for the Yari document content, static and sitemap files (`dev` has already been created)
- [x] Create new AWS IAM user (and associated IAM policies that are restricted to the tasks of the `deployer`) with programmatic credentials for running the `deployer` within GitHub Actions 
- [x] Define changes and change plan required for primary `stage` and `prod` CDN's. Can we re-use our current primary `stage` and `prod` CDN's and simply apply our new behaviors and some associated Lambda functions at launch time, or do we need to create fresh CDN's and have AWS-Support help us switch the CNAME's from the old CDN's to the new ones? **ANSWER: After discussing this with @limed, we will create fresh CDN's and have AWS-Support help us switch the CNAME's from the old CDN's to the new ones.**
- [x] Create the new CloudFront distribution for Yari `stage` (this will replace the existing stage CDN on launch day)
    - [ ] Define new `Group` origin with the `mdn-content-stage` S3 bucket as its primary origin and the stage ELB (public access point for the stage Django services) as its secondary origin for 404 fail-overs
    - [ ] Define new behaviors
- [x] Create the new CloudFront distribution for Yari `prod` (this will replace the existing prod CDN on launch day)
    - [ ] Define new `Group` origin with the `mdn-content-prod` S3 bucket as its primary origin and the prod ELB (public access point for the prod Django services) as its secondary origin for 404 fail-overs
    - [ ] Define new behaviors

~~- [ ] Create Lambda function `mdn-content-origin-response` in the `us-east-1` region for handling "fundamental" redirects (this might not be strictly necessary since we will fail-over to Django and Django already handles the fundamental redirects)~~ **NOTE: This was not needed. We handle the fundamental redirects within our `mdn-content-origin-request` Lambda@Edge function.**

**Comment by peterbe** [comment]
Let's dig into this a bit. It's not entirely clear how we are going to update the stage bucket. We could simply have a separate GitHub Action cron job that runs on a similar periodicity but that is configured to Yari deploy to a different bucket. 
In fact, we could make this one be a lot more frequent and have it *not* send CloudFront invalidations. 

The other thing we could look at potentially is to do "incremental deploys" all the time. I.e. on every master commit, we build everything. Just like the regular 24h periodic build and upload everything (remember, the yari deployer is pretty smart to avoid uploading things that haven't changed). 

Both approaches gives us more "immediate" results on some developer.allizom.org after PRs are merged (yari and mdn-content)

I think it makes sense that stage has a *configurable* difference from prod (apart from just the S3 bucket name) and we can play this to its full advantage. But we also need to be aware that stage is suppose to be as close to prod as humanly possible so it might make sense to make stage behave exactly as prod if the $$$ allows it.

**Comment by peterbe** [comment]
Besides, when you say "stage" you mean something like developer.allizom.org, right? Not individual PR builds.

**Comment by escattone** [comment]
**So far I've created the following:**

- [ ] the `mdn-content-dev`, `mdn-content-stage` and `mdn-content-prod` S3 buckets
- [ ] the `mdn-content-dev` S3 bucket has been configured with a `lifecycle rule` that automatically expires all of its objects older than 30 days
- [ ] the `mdn-content-stage` and `mdn-content-prod` S3 buckets have been configured with a `lifecycle rule` that automatically expires all of their objects older than 1 year
- [ ] the Lambda function `mdn-content-origin-request` in the `us-east-1` region which is the region required for Lambda functions used by CloudFront (the actual code of the latest version of the Lambda function is https://github.com/mdn/yari/blob/master/deployer/aws-lambda/content-origin-request/index.js)
- [ ] the AWS Certificate Manager SSL certificate for `*.content.dev.mdn.mozit.cloud`
- [ ] the CloudFront distribution (CDN) for the `dev` environment, configured with:
    - the CNAME of `*.content.dev.mdn.mozit.cloud`
    - the `*.content.dev.mdn.mozit.cloud` SSL certificate from above
    - a single default behavior with the `mdn-content-dev` S3 bucket as its origin
    - the `mdn-content-origin-request` Lambda@Edge function to handle  `origin-request` events
- [ ] the Route53 NS record for `dev.mdn.mozit.cloud` (@limed helped me and created this)
- [ ] the Route53 wildcard DNS record for `*.content.dev.mdn.mozit.cloud` that routes to the CloudFront distribution for the `dev` environment
- [ ] the following IAM policies: `mdn-yari-deployer-update-lambda-functions`, `mdn-yari-deployer-upload-dev`, `mdn-yari-deployer-upload-stage`, `mdn-yari-deployer-upload-prod`
- [ ] the IAM user `mdn-yari-deployer` with programmatic credentials (i.e., with access and secret keys) for use with GitHub Actions

**Comment by escattone** [comment]
** I still need to create the following:**

- [ ] the new CloudFront distribution for Yari `stage` (this will replace the existing stage CDN on launch day)
    - [ ] define new `Group` origin with the `mdn-content-stage` S3 bucket as its primary origin and the stage ELB (public access point for the stage Django services) as its secondary origin for 404 fail-overs
    - [ ] define new behaviors
- [ ] the new CloudFront distribution for Yari `prod` (this will replace the existing prod CDN on launch day)
    - [ ] define new `Group` origin with the `mdn-content-prod` S3 bucket as its primary origin and the prod ELB (public access point for the prod Django services) as its secondary origin for 404 fail-overs
    - [ ] define new behaviors
- [ ] Lambda function `mdn-content-origin-response` in the `us-east-1` region for handling "fundamental" redirects (this might not be strictly necessary since we will fail-over to Django and Django already handles the fundamental redirects)

**Comment by escattone** [comment]
I've also created the following, which completes the infrastructure for Yari for the launch:
- [ ] the AWS Certificate Manager SSL certificate for the Yari stage CDN (arn:aws:acm:us-east-1:178589013767:certificate/a74ef423-755e-4e19-af2b-f779282f691a)
- [ ] the AWS Certificate Manager SSL certificate for the Yari prod CDN (arn:aws:acm:us-east-1:178589013767:certificate/0ad29b33-2002-41fd-92d4-0825560521bb)
- [ ] the IAM user `mdn-yari-deployer-prod` with programmatic credentials (i.e., with access and secret keys) for use with GitHub Actions (arn:aws:iam::178589013767:user/mdn-yari-deployer-prod)
- [ ] the IAM user `mdn-yari-deployer-dev-and-stage` with programmatic credentials (i.e., with access and secret keys) for use with GitHub Actions (arn:aws:iam::178589013767:user/mdn-yari-deployer-dev-and-stage)
- [ ] the CloudFront distribution (CDN) for the stage environment (arn:aws:cloudfront::178589013767:distribution/E2MLRMA1VTVDHX)
- [ ] the CloudFront distribution (CDN) for the prod environment (arn:aws:cloudfront::178589013767:distribution/E2ZY2DGUN70EMI)
- [ ] the Route53 DNS CNAME for `yari-demos.prod.mdn.mozit.cloud` that routes to the CloudFront distribution for the Yari prod environment
- [ ] the Route53 DNS CNAME for `yari-demos.stage.mdn.mozit.cloud` that routes to the CloudFront distribution for the Yari stage environment

**Comment by escattone** [comment]
FYI. The entire Yari stage deployment (CDN, S3 bucket, and EKS-based Django service) has been tested using our [new Yari integration tests](https://github.com/mdn/yari/tree/master/testing/integration). Here is the latest result:

```sh
rjohnson-44864:integration rjohnson$ poetry run pytest --base-url https://developer.allizom.org
The currently activated Python version 2.7.16 is not supported by the project (^3.7).
Trying to find and use a compatible version.
Using python3 (3.8.0)
============================================ test session starts =============================================
platform darwin -- Python 3.8.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
baseurl: https://developer.allizom.org
rootdir: /Users/rjohnson/repos/yari/testing/integration
plugins: rerunfailures-9.1.1, base-url-1.4.2
collected 1027 items

headless/test_cdn.py ........................................................                          [  5%]
headless/test_endpoints.py ...F...............................                                         [  8%]
headless/test_redirects.py ........................................................................... [ 16%]
...................................................................................................... [ 26%]
...................................................................................................... [ 36%]
...................................................................................................... [ 45%]
...................................................................................................... [ 55%]
...................................................................................................... [ 65%]
...................................................................................................... [ 75%]
...................................................................................................... [ 85%]
...................................................................................................... [ 95%]
............................................                                                           [ 99%]
headless/test_robots.py .                                                                              [100%]

================================================== FAILURES ==================================================
____________________________________________ test_hreflang_basic _____________________________________________

base_url = 'https://developer.allizom.org'

    def test_hreflang_basic(base_url):
        """Ensure that we're specifying the correct value for lang and hreflang."""
        url = base_url + "/en-US/docs/Web/HTTP"
        resp = request("get", url)
        assert resp.status_code == 200
        html = PyQuery(resp.text)
        assert html.attr("lang") == "en"
>       assert html.find('head > link[hreflang="en"][href="{}"]'.format(url))
E       assert []
E        +  where [] = <bound method PyQuery.find of [<html>]>('head > link[hreflang="en"][href="https://developer.allizom.org/en-US/docs/Web/HTTP"]')
E        +    where <bound method PyQuery.find of [<html>]> = [<html>].find
E        +    and   'head > link[hreflang="en"][href="https://developer.allizom.org/en-US/docs/Web/HTTP"]' = <built-in method format of str object at 0x7f9e81f7ccf0>('https://developer.allizom.org/en-US/docs/Web/HTTP')
E        +      where <built-in method format of str object at 0x7f9e81f7ccf0> = 'head > link[hreflang="en"][href="{}"]'.format

headless/test_endpoints.py:75: AssertionError
========================================== short test summary info ===========================================
FAILED headless/test_endpoints.py::test_hreflang_basic - assert []
================================= 1 failed, 1026 passed in 80.50s (0:01:20) ==================================
```

I believe that this single failure will be resolved once we build the translated content for stage as well.

**Comment by escattone** [comment]
This is done.
