### ISSUE TITLE
Sidebar icons aren't "outside the text"

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1109]
In `kumastyles`: 
<img width="369" alt="Screen Shot 2020-08-19 at 4 45 45 PM" src="https://user-images.githubusercontent.com/26739/90688593-ae652200-e23c-11ea-9fd1-baf4f10f41d8.png">

In current kuma prod:
<img width="385" alt="Screen Shot 2020-08-19 at 4 54 47 PM" src="https://user-images.githubusercontent.com/26739/90688644-be7d0180-e23c-11ea-8e38-132cdaaef92b.png">

The font styles and stuff is different but probably an entirely different problem. 
In `kumastyles` the biggest problem is that the icon isn't "outside" the text to the left.

**Comment by peterbe** [comment]
@schalkneethling We can all discuss it later but you can decide if you want to put this onto the `Yari1` Milestone (blocker for launch) as a reminder. 
It's after all possible to read the side-bar fine even the icons aren't where they used to be.

**Comment by schalkneethling** [comment]
Resolved in https://github.com/mdn/yari/pull/1321
