### ISSUE TITLE
Search bar on https://developer.mozilla.org has no scroll bar and other issues

### ISSUE THREAD

**Issue by tk9139** [mdn/yari#11120]
When I search for something  that have a lot of result I cannot see all result. The Search bar does not have a scroll bar, so I cannot scroll to the bottom of the result to choose the option of displaying more.   For instance, I was searching for "remove". I see 5 result listed but I cannot scroll beyond the 5th item.  Is there a way of changing this search bar so that at least a scroll bar is added?

**Comment by mirunacurtean** [comment]
@tk9139 Thank you for posting your first issue. This is a [known issue](https://github.com/mdn/yari/issues/5650) on smaller viewports or where the list of search results is longer and indeed the solution would be to add a scroll, as mentioned in https://github.com/mdn/yari/issues/5650#issuecomment-1315142687/ so it is good you have brought it to attention. 

Managed to reproduce it with the "remove" example. 
![image](https://github.com/mdn/yari/assets/53306802/87b64057-9c1b-4522-85cc-27fcaa209686)

**Comment by tk9139** [comment]
I forgot to mention that I was using my laptop landscape view when I did
the search. Thank you for the follow up.

Thanh Khuu
480-359-7521
***@***.***

**Comment by caugner** [comment]
Thank you for taking the time report this issue. 👍 

Indeed we already track this issue in https://github.com/mdn/yari/issues/5650, which has an open PR, so I'm closing this one as a duplicate.
