### ISSUE TITLE
Determine CMS CLI commands (if any) for content contributors

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1114]
Determine what, if any, CMS commands (e.g., for creating new documents, moving existing documents, deleting documents, etc.) we need to implement for the Yari launch, and implement them. If so, can these be implemented as CLI-only commands?

**Comment by peterbe** [comment]
We have none other than what the CRUD can do. 
I would argue we accept that we have to write the documentation for it. I know it's humanly possible to add, delete, edit, and move documents using the command line and basic `cp` and `git mv` and `rm` and stuff. 
It can simply be one paragraph per action.

**Comment by escattone** [comment]
We have decided, at least for the beta launch of Yari, to **not** implement any CLI commands to aid in creating, updating, moving, or deleting documents. Instead, we will provide detailed instructions/documentation for contributors wanting to do each of those content tasks. That effort is already captured in https://github.com/mdn/yari/issues/1108, so closing this as done.
