### ISSUE TITLE
Code of conduct for content repo

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1115]
New repos need these things.

**Comment by peterbe** [comment]
@chrisdavidmills Would you be interested in owning this one?

**Comment by chrisdavidmills** [comment]
@peterbe Well, I am not disinterested, but I really wouldn't have time to handle it.

**Comment by peterbe** [comment]
The license issue is here: https://github.com/mdn/yari/issues/408

**Comment by peterbe** [comment]
@escattone We don't have one for this repo either. 
But I think https://mana.mozilla.org/wiki/display/DATA/GitHub+practices mentions to use https://github.com/mozilla/repo-templates/blob/master/templates/CODE_OF_CONDUCT.md which we can just check-in everywhere.
