### ISSUE TITLE
Searching for `tilde` returns nothing

### ISSUE THREAD

**Issue by adrian5** [mdn/yari#11187]
I first looked over at [mdn / content](https://github.com/mdn/content/pull/30723) but then realized this probably belongs here.

I was searching for the `tilde` character, by which I meant the [subsequent-sibling selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Subsequent-sibling_combinator), and not getting any results.

![tilde-search](https://github.com/mdn/content/assets/5426924/6f5d95ba-7b25-4219-91ef-537178a1dcfd)

 A search for `~` only suggests the [Bitwise NOT](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Bitwise_NOT) page. If there were no results at all, I would have assumed this is due to dealing with a special character.

**Comment by fiji-flo** [comment]
I'm sorry for the inconvenience. This is intended as the message says:
> No document titles found.

If you hit enter of click the magnifier the site search will open as it includes the document.

Maybe we enhance our quick search to support similar use cases in a future. But for now I'm closing this.
