### ISSUE TITLE
[Suggestion] 'Locale' values would be better to be managed as a type.

### ISSUE THREAD

**Issue by C17AN** [mdn/yari#11322]
### Summary

The `locale` properties used in the project are of the `string` type, and it would be nice if they were managed more strictly with the `Locale` type.

- **AS-IS** (Code Suggestion at `on-github.tsx`)
<img width="383" alt="image" src="https://github.com/mdn/yari/assets/26535030/b679ced6-b363-42f8-b658-c7296312d9fc">

- **TO-BE**
<img width="546" alt="image" src="https://github.com/mdn/yari/assets/26535030/bb3722d5-a968-4d10-9858-00228e3c72c1">

### Anything else?

First of all, I think this could be a breaking change, so I started by fixing one small type.

If there is a reason for using the string type considering future scalability, etc., you can reject this PR. :)

Or If you think this proposal is okay, I'll fix the parts that are considered to have less impact to the `Locale` type.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Fixed via https://github.com/mdn/yari/pull/11323.
