### ISSUE TITLE
Note cards/backgrounds

### ISSUE THREAD

**Issue by malqinneh** [mdn/yari#1133]
Looking at the forEach() page; we use orange/yellow note cards within body text and sections to call out additional context and narrative. The note cards introduce new type treatments and their background elements are only as wide as the readable line-width. 

## Acceptance criteria
- [ ] Add component/style to Storybook
- [ ] Implement component/style on production

## Implementation decision and next steps

- H4 header styles changed to Arial - Bold
- Arial for note body / text
- Four types (admonition) of note cards;
   - Note
   - Experimental
   - Deprecated
   - Non-standard
- Specific icons per note type
- Note cards span full column width
- Text within note cards remains at readable width

![note types.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/75c1c72f-0a9f-45ff-980a-8c04957c44c3)

## Existing problem

- Due to the background element (orange/yellow rectangle) being constrained (width wise) to the same readable line-width we use for the rest of the page, the padding on the right side can end up being too constrained (see below example; the word "If" is nearly touching the edge of the component).

![Screen Shot 2020-07-13 at 12.05.34 PM.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/484e221a-f918-409e-a9bc-1c8be1160fa0)

- Benefits of introducing new type treatment (Zilla vs Arial) within note cards are unclear/unnecessary - adding visual clutter and disrupting readability/flow.

![Screen Shot 2020-07-13 at 12.05.17 PM.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/a943a207-d553-4eef-b53b-3b41e84dea4d)

## Proposed solution

- Make note background element span full width of the right column within platform feature page(s)
- Constrain text width to the same readable-line-width as standard page text/paragraph styles
- Format all text styles within note element(s) to be consistent with standard page text/paragraph styles
- Remove icon in the top left corner of the note card (unnecessary/lacks formatting)
- Use 3px line width for left-border (consistent px line width as dividers on the page)

![Screen Shot 2020-07-13 at 12.17.27 PM.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/699cf910-a6fb-4213-80a5-8a7a487c5909)

![Screen Shot 2020-07-13 at 12.43.39 PM.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/d4cd69ca-db19-4870-bc95-0dd2d7c08272)

**Comment by schalkneethling** [comment]
Note to self (@schalkneethling): https://github.com/mdn/yari/issues/630

**Comment by peterbe** [comment]
It is a bit weird that there's no margin between note cards. As seen on https://main.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Kitchensink
<img width="898" alt="Screen Shot 2020-11-10 at 10 16 56 AM" src="https://user-images.githubusercontent.com/26739/98693160-f4aeb680-233d-11eb-99bb-72ff35f6923e.png">

**Comment by schalkneethling** [comment]
I will double-check this but, I am pretty sure that when used in the content, that will be resolved by the content around the notecards/
