### ISSUE TITLE
Non-Scrolling Sidebars Trigger Migraines

### ISSUE THREAD

**Issue by MarjaE2** [mdn/yari#11333]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

### What specific section or headline is this issue about?

The non-scrolling sidebars on both sides of the page

### What information was incorrect, unhelpful, or incomplete?

It's not the information, it's the layout.

Having a narrow non-scrolling sidebar is bad enough, but the page has wide non-scrolling sidebars on both sides, with no visiual constrast and separation between the sidebars and the scrolling content between them.

So if users scroll or page down, it hurts, and triggers motion sickness, nausea, and migraines.

### What did you expect to see?

... I thought previous updates had fixed the sidebars.

### Do you have any supporting links, references, or citations?

Mentions scrolling, though it doesn't discuss web design:

https://pubmed.ncbi.nlm.nih.gov/36879031/

https://www.mdedge.com/clinicianreviews/article/82705/neurology/dizziness-and-vertigo-recognizing-vestibular-migraine/page/0/4

About parallax scrolling. Since these both involve how parts of the page slide past other parts of the same page, I think these are equivalent. In my experience the symptoms are similar:

https://www.theverge.com/2013/9/25/4770818/ios-7-zooming-animations-causing-reports-of-severe-motion-sickness

https://www.webaxe.org/vestibular-issues-parallax-design/

https://wearedrum.com/thinking/parallax-design

This also discusses the issues, but is massively inaccessible due to the same issues:

https://www.w3.org/WAI/GL/wiki/Animation_caused_by_user_interaction

**Comment by bsmth** [comment]
Thanks for opening this. I've moved it to Yari which is the right repository. 

Also linking to these which look similar:

- [ ] https://github.com/mdn/yari/issues/9365
- [x] https://github.com/mdn/yari/issues/6232

**Comment by caugner** [comment]
Thank you @MarjaE2 for taking the time to report this problem. It appears that you have already reported this issue in July 2023: https://github.com/mdn/yari/issues/9365

Sorry we haven't gotten to it yet, but it is on our list, so I'm going to close this issue as a duplicate.
