### ISSUE TITLE
Yari build possibly broken

### ISSUE THREAD

**Issue by estelle** [mdn/yari#11365]
### Summary

I updated my local environment.
I can get to http://localhost:5042/en-US/docs (which redirects to http://localhost:5042/en-US/docs/Web) 
but not to http://localhost:5042 or http://localhost:5042/en-US or http://localhost:5042/en-US/play/ (live examples work, but clicking "play" to open in new tab gets the error)

The error message reads:

Error: ENOENT: no such file or directory, stat 'myPath/content/node_modules/@mdn/yari/client/build/en-us/_spas/404.html'

It was working on 2.56, but the 2.57 build seems to be the issue. 

### URL

http://localhost:5042

### Reproduction steps

1. update all the repose
2. yarn install; yarn start
3. go to the local environment's MDN home page.

### Expected behavior

the home page

### Actual behavior

an error:
Error: ENOENT: no such file or directory

### Device

Desktop

### Browser

Edge

### Browser version

Stable

### Operating system

iOS

### Screenshot

![Screenshot 2024-06-25 at 11 47 19 AM](https://github.com/mdn/yari/assets/69888/cac92ab5-b573-4be9-9f24-2da774920294)
<img width="330" alt="Screenshot 2024-06-25 at 11 48 05 AM" src="https://github.com/mdn/yari/assets/69888/3cfaf2e2-d64a-4cf5-aca2-2a8b8d84ef3f">

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Technically, we're missing a `yarn render:html` when packaging yari, but originally it seems `yarn tool spas` no longer building HTML files is a breaking change we missed. We'll provide a fix in the next 24 hours.

**Comment by caugner** [comment]
@estelle The fix is now available in `@mdn/yari` 2.58.0, and I expect Dependabot to open a PR on mdn/content in the next hours.

**Comment by caugner** [comment]
With https://github.com/mdn/content/pull/34426 being merged, the fix has now landed in the content repository.

**Comment by estelle** [comment]
@caugner Thanks for the quick turn around and fix. It's working
