### ISSUE TITLE
In-page styles

### ISSUE THREAD

**Issue by malqinneh** [mdn/yari#1138]
# User story
Implement all in-page styles in Storybook to production.

## Acceptance criteria
- [ ] color palette 
- [ ] table styles

### Sprint ready checklist
- [x] Acceptance criteria defined
- [x] Team understands acceptance criteria
- [x] Team has defined solution / steps to satisfy acceptance criteria
- [x] Acceptance criteria is verifiable / testable
- [x] External / 3rd Party dependencies identified

**Comment by schalkneethling** [comment]
Closing in favor of the breakdown in https://github.com/mdn/yari/issues/1155
