### ISSUE TITLE
Implement Technology Topic Landing Pages

### ISSUE THREAD

**Issue by malqinneh** [mdn/yari#1145]
# User story
E - As product manager, designer, and engineer I want us all to have reached decisions around all components, styles, and page layouts on [technology topic landing page(s)] so that we can implement a design system on MDN

## Page list
Technologies overview 
HTML
CSS
Javascript
Graphics
HTTP
Web APIs
Extensions
MathML

### Acceptance Criteria
- [ ] Product manager and engineering sign-off on each page layout and styles
- [ ] Sketch library of all components and styles used on each page
- [ ] Abstract collection with finalized previews of each page  
- [ ] Add components and styles in Storybook
- [ ] Push changes live to production

### Sprint ready checklist
- [x] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [x] Acceptance criteria is verifiable / testable
- [x] External / 3rd Party dependencies identified

### Links
- [ ] Placeholder for any relevant links to documentation

**Comment by schalkneethling** [comment]
@chrisdavidmills @escattone Do you agree that we are not going to do anything special at the moment for pages such as the below? i.e. the current implementation is good enough for now.

- https://developer.mozilla.org/en-US/docs/Web/CSS
- https://developer.mozilla.org/en-US/docs/Web/HTML
- etc.

**Comment by chrisdavidmills** [comment]
@schalkneethling Yes, I'd agree with that. What we've got there already is functional, and we've got bigger fish to fry right now. Although maybe somewhere later on down the line we could think about at least have a nice little header graphic for each major landing page.

The one thing I have noticed that is broken is the little banner for the front-end web developer learning pathway.

The "Looking to become a front-end web developer?" heading has become detached completely from the rest of the text and the link:

"We have put together a course that includes all the essential information you need to work towards your goal.

Get started"

And the nice banner styling just isn't there any more.

Looking at some other pages that feature this banner:

* https://developer.mozilla.org/en-US/docs/Web/JavaScript
* https://developer.mozilla.org/en-US/docs/Learn
* https://developer.mozilla.org/en-US/docs/Learn/HTML
* https://developer.mozilla.org/en-US/docs/Learn/CSS
* https://developer.mozilla.org/en-US/docs/Learn/JavaScript

The banner isn't consistently this broken everywhere, but the styling is not there any more, and it is pretty broken in most places.

Can you work on fixing those?

**Comment by schalkneethling** [comment]
> @schalkneethling Yes, I'd agree with that. What we've got there already is functional, and we've got bigger fish to fry right now. Although maybe somewhere later on down the line we could think about at least have a nice little header graphic for each major landing page.
> 
> The one thing I have noticed that is broken is the little banner for the front-end web developer learning pathway.
> 
> The "Looking to become a front-end web developer?" heading has become detached completely from the rest of the text and the link:
> 
> "We have put together a course that includes all the essential information you need to work towards your goal.
> 
> Get started"
> 
> And the nice banner styling just isn't there any more.
> 
> Looking at some other pages that feature this banner:
> 
> * https://developer.mozilla.org/en-US/docs/Web/JavaScript
> * https://developer.mozilla.org/en-US/docs/Learn
> * https://developer.mozilla.org/en-US/docs/Learn/HTML
> * https://developer.mozilla.org/en-US/docs/Learn/CSS
> * https://developer.mozilla.org/en-US/docs/Learn/JavaScript
> 
> The banner isn't consistently this broken everywhere, but the styling is not there any more, and it is pretty broken in most places.
> 
> Can you work on fixing those?

Yup, we do have an issue for that one. https://github.com/mdn/yari/issues/2255

**Comment by schalkneethling** [comment]
Closing with a note on the future taken here https://github.com/mdn/yari/issues/2443
