### ISSUE TITLE
Implement Reference Page

### ISSUE THREAD

**Issue by malqinneh** [mdn/yari#1147]
# Epic 
E - As product manager, designer, and engineer I want us all to have reached decisions around all components, styles, and page layouts on [reference pages] so that we can implement a cohesive design system on MDN

### Top five reference pages
https://developer.mozilla.org/en-US/docs/web/javascript
https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/array
https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/array/map
https://developer.mozilla.org/en-US/docs/web/api/fetch_api/using_fetch
https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/array/filter
https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/array/foreach

#### [U - Main menu components and styles](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/234)
- [x] [foundational work for CSS refactor](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-minimalist/31)
- [x] [grid implemented](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-minimalist/44)
- [ ] grid implemented in Yari and Kuma 
- [ ] [main menu component implemented](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/170) 
- [ ] [header search component implemented](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/171) 
- [ ] [user menu component implemented](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/172)

#### [U - Sidebar menu components and styles](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/237)
- [ ] [side bars](https://app.zenhub.com/workspaces/mdn-design-system-5f2090ff88d81a001857b98f/issues/mdn/mdn-fiori/261) 
- [ ] [table of contents](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/163) 

#### [U - In-page components](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/235)
- [ ] [breadcrumbs implemented](https://app.zenhub.com/workspaces/mdn-design-system-5f2090ff88d81a001857b98f/issues/mdn/mdn-fiori/259)
- [ ] [note cards implemented](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/228) 
- [ ] [meta information implemented](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/242)
- [ ] [language selector implemented](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/221)
- [ ] [inline code implemented](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/249) 
- [ ] [code examples implemented](https://app.zenhub.com/workspaces/mdn-design-system-5f2090ff88d81a001857b98f/issues/mdn/mdn-fiori/260) 
- [ ] [browser compact table](https://app.zenhub.com/workspaces/mdn-design-system-5f2090ff88d81a001857b98f/issues/mdn/mdn-fiori/258) 

#### [U - In-page styles](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/236)
- [ ] [type scale](https://app.zenhub.com/workspaces/mdn-dev-5d6ea9fb3fe11605a63cea86/issues/mdn/mdn-fiori/147) 
- [ ] page title
- [ ] type styles
- [ ] color palette 
- [ ] table styles

### Sprint ready checklist
- [x] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

### Links
- [ ] Placeholder for any relevant links to documentation

Note: 
- Product manager and engineering sign-off on [platform feature] page layout and styles
- Sketch library of all components and styles used on the [platform feature] page
- Abstract collection with finalized [platform page] preview
- Add components and styles in Storybook
- Push changes live to production

**Comment by schalkneethling** [comment]
Closed in favor of: https://github.com/mdn/yari/issues/1155
