### ISSUE TITLE
Large blank space at bottom of page on certain screen widths

### ISSUE THREAD

**Issue by Elon-fast** [mdn/yari#11501]
### Summary

After shrinking the window, a large amount of blank space appeared at the bottom and the height was abnormal, but when the console was called out, the height returned to normal

### URL

https://developer.mozilla.org/en-US/docs/Glossary

### Reproduction steps

1 .Open the corresponding page
2. Reduce the window width to <1200px but >768px
3. Just swipe at the bottom of the article

### Expected behavior

There is no significant amount of blank space at the bottom of the article

### Actual behavior

significant amount of blank space at the bottom of the article

### Device

Desktop

### Browser

Edge, Stable, Windows
Chromium, Stable, Linux
Epiphany (WebKit), Stable, Linux

### Screenshot

<img width="728" alt="2024-07-19 105707" src="https://github.com/user-attachments/assets/fd4d0e3d-67fc-4516-9a4a-5c5bd35a9b45">
<img width="727" alt="2024-07-19 105757" src="https://github.com/user-attachments/assets/7556e0df-3e69-4fb6-b2dc-3102130b84fe">

### Anything else?

no

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by LeoMcA** [comment]
Seems to be in an issue in Blink + WebKit on our "hide the right sidebar" media query: if I had to guess, the left sidebar is overflowing in a weird way causing the whole page to get longer - I think we've seen this sort of behaviour before in Blink + WebKit - I don't recall the fix.

**Comment by caugner** [comment]
I believe this is what https://github.com/mdn/yari/pull/10560 is about.

**Comment by hanyujie2002** [comment]
https://github.com/mdn/yari/pull/11621 is also about this

**Comment by caugner** [comment]
Fixed via https://github.com/mdn/yari/pull/11621.
