### ISSUE TITLE
Design System: Reference pages

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1155]
# Problem

While the MDN Web Docs project is a large, high impact project, we have a small team to both maintain and grow it. Access to resources such as design and UX are also not available consistently available and so, we need to make strategic use of these resources.

The codebase of the project has gone through many iterations over the years, but not a lot of time was spent on cleanup and maintenance. Documentation of the existing codebase has lagged and testing of the frontend pieces is almost nonexistent.

Over the years through fast-moving cycles, decisions were made that have caused inconsistencies across the front end UI and codebase that make the overall experiences inconsistent from a user's perspective, and brittle from a developer perspective.

Changes in one area can often have a negative impact on areas that seem unrelated at the time of implementation. Because of the brittleness mentioned before and the lack of a formal QA process, or a set of maintained and automated UI integration tests, user interface bugs are very often found and reported by our users instead of being prevented from reaching production in the first place.

Having to cater to an array of one-off use cases, and continued support for legacy implementation causes friction for developers and negatively impact our end-users in terms of performance. In the same vein, spending all of this time playing whack-a-mole prevents us from dedicating time to the fine-grained details of the user interface components such as general usability and accessibility. This is to the detriment of our users, as well as the brand image of MDN Web Docs as a leader on the web.

All of the above also has a real monetary cost because a lot of engineering time is spent on fixing bugs that could have been avoided and reimplementing common components instead of reusing existing components. This leads to reduced productivity and a slower time to marker.

Not having clearly defined, well documented, and tested user interface components slow down overall development time and further adds to the above-mentioned problems. This is a negative cycle that we should, and cannot continue.

### Some statistics

For the following reference page:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

- 42 unique colors
- 58 Unique Background Colors
- 47 Unique font sizes
- 13 Unique Font Families
- 1,791 rules
- 132 `id` selectors (ideal? 0)
- 211KB (38KB GZipped) (Comparisson: Bootstrap 123kb -> 23kb GZipped)

![A screenshot of MDN’s current CSS specificity score](https://user-images.githubusercontent.com/10350960/90970220-4e070680-e502-11ea-9ab3-aa0440a5e924.png)

> Base 10 specificity score for each selector by source order. Generally, lower scores and flatter curves are better for maintainability.

# Solution

In short, we need to implement a [design system](https://www.invisionapp.com/inside-design/guide-to-design-systems/), rewrite most of our core SASS codebase, and optimize our HTML. This has been largely agreed on and is a current key result(KR) of the team.

This specific `pitch` is for the implementation of the design system that relates specifically to the reference pages on MDN Web Docs which is the bulk of the website. This is a `big batch` project and as such has an `appetite` of a full 6-week uninterrupted cycle.

> pitch: This document outlining the problem, solution, appetite, rabbit holes, and no-goes.

> appetite: The amount of time we want to spend on a project, as opposed to an estimate

An example page would be:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

As can be seen from the above page, while reference pages have many unique components, it also shares larger components with other page types across the MDN Web Docs website. The benefit of addressing the reference page type first is then two-fold:

1. This is the highest touch point for end-users and these improvements will thus directly impact the largest part of the MDN Web Docs audience
2. Addressing this page type will address 80% of the use cases and components across all pages

> NOTE: While having a fully-fledged design system is our goal, this cycle will focus on the pattern library portion with just enough documentation to assist in adoption. Separate `pitches` will be written and proposed in the future for other aspects of the overall design system.

### Implementation

- Components are built directly into the Yari codebase.
- Component specific SASS will be co-located with the relevant TypeScript component, for example

```
-- client
---- src
------ ui
-------- molecules
---------- main-menu.tsx
---------- main-menu.scss
```

- Core style is provided by the [`mdn-minimalist` library](https://github.com/mdn/mdn-minimalist)
- Iconography is provided by the [`mdn-dinocons` library](https://github.com/mdn/mdn-dinocons/)
- The design system will be based on [Storybook](https://storybook.js.org/), which will be part of the overall Yari codebase.

### Components that will be addressed

- [Base grid](https://github.com/mdn/yari/issues/1126)
- Main menu
  1. [Improve accessibility of main menu](https://github.com/mdn/yari/issues/1124)
  2. [Rotate arrows in main menu(mobile) on interaction](https://github.com/mdn/yari/issues/1166)
- [Search (header component)](https://github.com/mdn/yari/issues/1130)
- [User menu](https://github.com/mdn/yari/issues/1131)
- [Titlebar](https://github.com/mdn/yari/issues/1169)
- [Breadcrumbs](https://github.com/mdn/yari/issues/1128)
- [Table of contents (aka On this Page)](https://github.com/mdn/yari/issues/1142)
- [Sidebar](https://github.com/mdn/yari/issues/1137)
- [Typescale](https://github.com/mdn/yari/issues/1170)
- [Colour palette](https://github.com/mdn/yari/issues/1171)
- [Table styles](https://github.com/mdn/yari/issues/1172)
- [Links](https://github.com/mdn/yari/issues/1173)
- [Forms](https://github.com/mdn/yari/issues/1121)
- [Iconography](https://github.com/mdn/yari/issues/1174) ~ (driven from [`mdn-dinocons`](https://github.com/mdn/mdn-dinocons/))
- [Buttons](https://github.com/mdn/yari/issues/1175)
- [Meta information and badges](https://github.com/mdn/yari/issues/1132)
- [Interactive examples](https://github.com/mdn/yari/issues/1176)
- [Notecards](https://github.com/mdn/yari/issues/1133)
- [Browser compatibility data table](https://github.com/mdn/yari/issues/1143)
- [Footer](https://github.com/mdn/yari/issues/1127)
- [Newsletter signup form](https://github.com/mdn/yari/issues/1177)
- [Promotional banner](https://github.com/mdn/yari/issues/1178)
- [Sign in modal](https://github.com/mdn/yari/issues/1179)

### Breakpoints

All implementation is done mobile-first. From here we have two breakpoints where layout and content will be customized as appropriate:

1. 1024px (min-width - Tablet in landscape orientation)
2. 1366px (min-width - This is the most common laptop/desktop screen size)

## Rabbit Holes

As mentioned in the `solution` portion above, focus in this cycle should be on the component implementation details and just enough documentation to assist adoption. Further detail is best avoided at this stage to avoid possible rabbit holes that could derail the success of this cycle.

- Simple over complex
- Good enough over perfect

## No Goes

- No logic changes to any macros are allowed
- Focus on implementation in Yari no backporting to Kuma

## [Appetite](https://basecamp.com/shapeup/1.2-chapter-03#setting-the-appetite)

6 weeks

## Resources

- One full-time frontend engineer
- One UX designer (40% time which equates to 12 full days during the 6-week cycle)

**Comment by escattone** [comment]
I think this is fundamentally done. We'll be making corrections from this point forward.

**Comment by smith558** [comment]
Is the design system published anywhere?
