### ISSUE TITLE
MDN crashes brave

### ISSUE THREAD

**Issue by holic** [mdn/yari#11569]
### Summary

Opening any MDN reference page appears to crash Brave browser. Just to be certain this wasn't related to an extension, I am able to reproduce this with all my extensions disabled.

### URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl
https://developer.mozilla.org/en-US/docs/Web/CSS/::after

### Reproduction steps

1. Open any of the above MDN links in latest Brave browser
2. As soon as the page loads, Brave crashes

### Expected behavior

I expect Brave to not crash

### Actual behavior

Brave crashes

### Device

Desktop

### Browser

Other (specify below)

### Browser version

Stable

### Operating system

Mac OS

### Anything else?

<img width="712" alt="image" src="https://github.com/user-attachments/assets/634595c2-b870-4025-9e73-705e3318d732">
<img width="481" alt="image" src="https://github.com/user-attachments/assets/901fe806-67a2-490d-93b9-e1a0f560a737">

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
For the record, I couldn't reproduce with Brave 1.66.115 or 1.68.137 on macOS Sonoma 14.6, and neither with the latest Brave.

**Comment by argl** [comment]
I also cannot reproduce the issue. I am closing this now, but I want to thank you for taking the time to report an issue.
