### ISSUE TITLE
BCD table in "text-decoration-style" page is broken when notes are expanded

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#1167]
Take the BCD table at https://developer.mozilla.org/en-US/docs/Web/CSS/text-decoration-style#Browser_compatibility:

*******
<img width="1033" alt="Screen Shot 2020-04-29 at 10 51 09 AM" src="https://user-images.githubusercontent.com/432915/80629211-5ee9b480-8a07-11ea-838e-f465e9bcfe3e.png">

*******

It contains two rows, and the first row has some notes that we can see by clicking a disclosure arrow.

Click one of the note disclosure arrows in the top row:

*******
<img width="1033" alt="Screen Shot 2020-04-29 at 10 51 25 AM" src="https://user-images.githubusercontent.com/432915/80629270-7a54bf80-8a07-11ea-9703-688380953a73.png">

*******

Most of the second row is pushed out of the box and the names of the rows disappear.

I suspect this is because the name of the first row `text-decoration-style` wraps, so that row is taller than normal.

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/pull/1536
