### ISSUE TITLE
release notes would be much more usable if they omitted empty sections

### ISSUE THREAD

**Issue by ewnjtgouierg** [mdn/yari#11774]
### Summary

release notes display a lot of useless text that makes it extremely hard to read the only useful info

### URL

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/131

### Reproduction steps

open the url

### Expected behavior

the list of changes introduced by the new version

### Actual behavior

the list of all web technologies where and all possible types of changes that COULD be introduced, with the actual changes buried somewhere in-between long stretches of useless attention-wasting blank section names, easy to miss when scrolling

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
@ewnjtgouierg The developer notes you refer to are for the upcoming Firefox version and are still in the process of being written. The empty sections are there on purpose to facilitate the writing process and will be removed as soon as the Firefox version is released in about 2 weeks.

We don't have plans to change this process, so I'm going ahead and close this issue as "won't fix".

Thank you for your understanding. 🙏

**Comment by ewnjtgouierg** [comment]
@caugner  - sorry, i didn't realize that. thanks for explanation
