### ISSUE TITLE
pages from documentation get removed without  any consideration for the broken links

### ISSUE THREAD

**Issue by ewnjtgouierg** [mdn/yari#11771]
### Summary

i regularly stumble upon external links from other sites as well as internal links from the documentation itself, that lead to no longer existing MDN page

such a page simply returns 404 code and offers an option to search for the url as a keyword on the site, which is often useless

if the section of manual is removed because some technology is no longer relevant / supported / renamed - there should be explanation / redirect on the old url

example js-ctypes - details below
it is linked from mozilla wiki: https://wiki.mozilla.org/JSctypes which claims to be outdated and refers to it as a newer alternative, and there're internal links to it from different language versions of MDN itself, suggesting that the page indeed existed in the past

### URL

https://developer.mozilla.org/en-US/docs/Mozilla/js-ctypes

### Reproduction steps

1.go to the specified url
2.observe there's no any information - as if such a page never existed
3.try to use offered option of searching to find that nothing gets found on MDN site
4.try googling "site:developer.mozilla.org js-ctypes" - you'll find some non-english pages that lead to the same deleted page

### Expected behavior

if a section of the manual is removed because some technology is no longer relevant / supported  or is renamed - opening the old url should display an explanation and/or link(s) to the relevant new page(s)

### Actual behavior

the pages get simply deleted, returns 404 code and offer an option to search for the url as a keyword on the site, which is often useless

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
@ewnjtgouierg Thank you for taking the time to report this issue. 👍 

Please note that the topic that you're referring to has been entirely removed from MDN. In many cases, there are redirects in place that bring the user to the new location where the documentation can be found. However, for outdated topics where there is no alternative location, we usually don't redirect, except if we're getting a significant amount of requests. Rest assured that we're monitoring 404s, as is good practice. The mentioned URL, however, has had less than 10 users and requests in the last four weeks, so it is not eligible for a redirect.

So I'm going ahead and close this as "won't fix".

Thank you for your understanding. 🙏
