### ISSUE TITLE
Redundant hidden paragraphs in content

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1191]
See https://github.com/mdn/yari/blob/0f25d1ca46bf1300863f9dd05a5e6dbe7ae3101b/content/files/en-us/web/html/element/video/index.html#L32
That `<p>` of text is repeated 923 times across all `en-US` content. 

And https://github.com/mdn/yari/blob/0f25d1ca46bf1300863f9dd05a5e6dbe7ae3101b/content/files/en-us/web/html/element/video/index.html#L448
That `<div>` is repeated 2098 times. 

First of all, what's the point of it? Why is it even there? Why is visually hidden?

I think we should delete these lines and if it's deemed strongly useful, we should add it to the `InteractiveExample.ejs` macro etc.

**Comment by peterbe** [comment]
By the way, if we can delete it as part of the dumper we stand to save 273KB of content for all `en-US` :)

**Comment by chrisdavidmills** [comment]
These paragraphs are there to provide guidance for would-be contributors who want to update a BCD table or an interactive example, but don't know how the macro system works. I would like to keep them in some form.

By "we should add it to the `InteractiveExample.ejs` macro etc.", do you mean just add the note into the macro source? This wouldn't help people who have no idea how the macro system works.

Could we put some code into the macros to generate some kind of help line to provide this info in the rendered page?

**Comment by peterbe** [comment]
> Could we put some code into the macros to generate some kind of help line to provide this info in the rendered page?

Exactly. So, first we edit the content (e.g the `index.html` files)

```diff
{{EmbedInteractiveExample("foo")}}
-<div class="hidden">The source...</div>
```

Then we edit the `kumascript/macros/EmbedInteractiveExample.ejs`

```diff
%>
<iframe class="<%= iClass %>" width="100%" height="250" frameborder="0" src="<%= url %>" title="MDN Web Docs Interactive Example"></iframe>

+<div class="hidden">The source...</div>
```

Now, independent of agnostically of the usefulness of that hidden HTML tag, we only type that stuff once in the source code rather than ~1,000 times in the content files.

**Comment by peterbe** [comment]
I'm just going to go for it. I think that plan is sane. There's no good reason why that string should appear 923 + 2098 times when it can appear only (and exactly) 1 + 1 times.

**Comment by chrisdavidmills** [comment]
Ah yes, I get it now. And yes, totally agreed. Go for it!

**Comment by peterbe** [comment]
I don't know exactly how I measured but I noticed that there's variants like this:

* `The compatibility table on this page is...`
* `The compatibility table in this page is...`

(note the difference in "on" vs "in")
Just goes to show the importance of DRY :)
I'm "regexing" for both strings.
