### ISSUE TITLE
Upside-down rendering of CJK characters in translation

### ISSUE THREAD

**Issue by bangseongbeom** [mdn/yari#11921]
### Summary

When I try to translate any MDN page to Korean using a browser translation tool, the characters on the browser compatibility table's header are reversed.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/text-orientation

### Reproduction steps

1. Access any MDN page that has a browser compatibility table.
2. Translate to Korean with a browser translation tool.

### Expected behavior

![expected](https://github.com/user-attachments/assets/56e1d017-df1b-493b-a32e-8fc2f85b1527)

Or:

![expected-2](https://github.com/user-attachments/assets/561dc0b9-403c-4375-9b5b-996e9b9e3822)

### Actual behavior

![actual](https://github.com/user-attachments/assets/c9907037-c179-4e05-9430-57f4f8ba9301)

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by argl** [comment]
The PR for this issue is on the way to be merged, so I am clsing this issue. Thanks for taking the time!
