### ISSUE TITLE
Content localization

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1198]
- [ ] Smartling integration
- [ ] Training the MT model with our current localized content
- [ ] Changes required to the Yari builder
- [ ] Archive manually-localized content
- [ ] Document localization approach
- [ ] Implement Redirects
    - [ ] For locales that will no longer be supported (e.g., Swedish or Arabic)
    - [ ] All document slugs will be in English, so have to handle redirects from localized slugs to English slugs

**Comment by mirunacurtean** [comment]
@fiji-flo Can you please triage this?

**Comment by fiji-flo** [comment]
Even though some parts are still applicable I prefer closing this as the smartling integration is on hold I guess.
