### ISSUE TITLE
Use matchMedia or (window.client.height) to dictate some features

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#120]
[Here](https://github.com/mdn/stumptown-renderer/blob/b3d83a309a6d0350ced054183f50ee299b478c09/client/src/search.js#L34) and [here](https://github.com/mdn/stumptown-renderer/blob/b3d83a309a6d0350ced054183f50ee299b478c09/client/src/search.js#L211) and [here](https://github.com/mdn/stumptown-renderer/blob/b3d83a309a6d0350ced054183f50ee299b478c09/client/src/search.js#L230) the search widget uses `isMobileUserAgent()` to determine how the functionality should differ. For example, if you're on a mobile device you're more likely to want to see *fewer* search results because your screen is smaller. 

The whole idea of "tailoring" the rendering based on the browser is good but we shouldn't do this based on the *type* of browser but instead of features that actually relate. For example, if your browser window isn't very high, it should only display, say, 5 search results so that scrolling doesn't suck. But if you're on a big screen, it might help to show a lot more. So this logic depends on the client inner height. So probably better to use something like `window.matchMedia` to figure these things out.

**Comment by peterbe** [comment]
[Here](https://github.com/mdn/stumptown-renderer/blob/b3d83a309a6d0350ced054183f50ee299b478c09/client/src/search.js#L303-L313) as well where it makes sure the top of the search input is at the top of the screen if the screen real estate is small so that the pop-up keyboard doesn't hide the search results too much. 

By the way, it might be an attractive option to make the whole search widget, on small screens, something that takes up *100%* of the whole screen instead of tricks to scroll things into position.

**Comment by schalkneethling** [comment]
@fiji-flo Do you know whether this was addressed as part of the redesign?

**Comment by caugner** [comment]
Closing in favor of the newer https://github.com/mdn/yari/issues/5650.
