### ISSUE TITLE
Tracker - MDN Fiori - Footer

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1205]
Tracker issue for the MDN Fiori - Footer milestone

- [x] [Main promo banner](https://github.com/mdn/yari/issues/1178)
- [x] [Add footer component](https://github.com/mdn/yari/issues/1127)

**Comment by sahilempire** [comment]
I want to work on this issue, **please assign this to me**. **@schalkneethling**

**Comment by peterbe** [comment]
> I want to work on this issue, **please assign this to me**.

We don't assign work to contributors. If you want to help, come with a PR on something that isn't being actively worked on.

**Comment by sahilempire** [comment]
As **I am new** in this contributors field, **please suggest** me something, what can **I contribute**?

**Comment by schalkneethling** [comment]
> As **I am new** in this contributors field, **please suggest** me something, what can **I contribute**?

Hey @sahilempire, this is actually a tracker of a larger set of work which I think is actually done 😄  So, I should close this.
I am not 100% sure if we have any good first issues on the Yari project specifically but, please have a look at our other projects here on Github: https://github.com/mdn/

This one might be worth having a look at as well https://github.com/mdn/interactive-examples

**Comment by schalkneethling** [comment]
Resolved by:

- https://github.com/mdn/yari/issues/1178
- https://github.com/mdn/yari/issues/1127
