### ISSUE TITLE
Spelling mistake on div article-footer

### ISSUE THREAD

**Issue by Mangotic** [mdn/yari#12097]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web

### What specific section or headline is this issue about?

article-footer "Help improve MDN"

### What information was incorrect, unhelpful, or incomplete?

spelling mistake "helpfuul", tried fixing myself but its generated by typescript/static js so cant access it
![grafik](https://github.com/user-attachments/assets/97ad0717-d626-48e0-a459-7804466c60fa)

### What did you expect to see?

helpfull

**Comment by bsmth** [comment]
Thanks a lot! I think this landed in https://github.com/mdn/yari/pull/12033, tagging @caugner for a look 👀
