### ISSUE TITLE
Fix remaining MacroLiveSampleError's

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1220]
There are 16 `MacroLiveSampleError`'s that need to be fixed.

- [x] http://localhost:3000/en-US/docs/Web/CSS/::-webkit-meter-optimum-value  **[Fixed in Wiki (bad `id` value)]**
- [x] http://localhost:3000/en-US/docs/Web/CSS/initial-letter-align  **[Fixed in Wiki (bad `id` value)]**
- [x] http://localhost:3000/en-US/docs/Web/CSS/appearance **[Fixed in Wiki (bad `id` value)]**
- [x] http://localhost:3000/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout **[Fixed in Wiki (used `id` instead of `class`)]**
- [x] http://localhost:3000/en-US/docs/Web/CSS/CSS_Grid_Layout/Layout_using_Named_Grid_Lines **[Fixed in Wiki (used `id` instead of `class`)]**
- [x] http://localhost:3000/en-US/docs/Web/CSS/::-webkit-meter-suboptimum-value **[Fixed in Wiki (bad `id` value)]**
- [x] http://localhost:3000/en-US/docs/Web/CSS/@media/prefers-contrast **[Fixed in Wiki (missing `html` and `css` `class` values)]**
- [x] http://localhost:3000/en-US/docs/Web/CSS/@media/prefers-reduced-data **[Changed in Wiki (missing `html` and `css` `class` values) but still broken for another reason]**
- [x] http://localhost:3000/en-US/docs/Web/CSS/@media/prefers-reduced-transparency **[Fixed in Wiki (missing `html` and `css` `class` values)]**
- [x] http://localhost:3000/en-US/docs/Web/HTML/Element/optgroup **[Fixed in Wiki (bad `id` value)]**
- [x] http://localhost:3000/en-US/docs/Web/HTML/Element/s **[Fixed in Wiki (bad `id` value)]**
- [x] http://localhost:3000/en-US/docs/Web/HTML/Element/rtc **[Fixed in Wiki (bad `id` value)]**
- [x] http://localhost:3000/en-US/docs/Web/API/Document/queryCommandState **[Already fixed in Wiki (missing `html` and `js` `class` values)]**
- [x] http://localhost:3000/en-US/docs/Web/API/Window/pageshow_event **[Fixed in Wiki (bad `id` value)]**
- [x] http://localhost:3000/en-US/docs/Web/API/GeolocationCoordinates/longitude **[Fixed in Wiki (bad `id` value)]**
- [x] http://localhost:3000/en-US/docs/Web/API/HTMLElement/change_event **[Fixed in Wiki (used `id` instead of `class`)]**

**Comment by peterbe** [comment]
Should we take this opportunity-time to see if we can make it more robust? Or is the hope that once we fix it in the wiki it'll never be a problem ever again?

**Comment by escattone** [comment]
> Should we take this opportunity-time to see if we can make it more robust? Or is the hope that once we fix it in the wiki it'll never be a problem ever again?

I don't think it's worth making it more robust until we take greater control of the content when we move the content to GitHub (as well as until we define our new localization approach), so I think we just have to take the approach that once we fix it in the Wiki, we hope it won't be a problem again.

**Comment by escattone** [comment]
I also temporarily (until we update our content from the Wiki) updated our current content to reflect the changes made to the Wiki, simply so we don't see these live-sample errors any longer when building the non-archived content.
