### ISSUE TITLE
Count the complete number of characters of translatable text in English

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1227]
Using a recent database dump of all *active* English content, we need to compute the total character count of **all translatable text**. I.e. the words that would be translated by a machine from English to $locales. This needs to include the document titles which is currently housed in the front-matter.

**Comment by peterbe** [comment]
Note-to-self; base off of this: https://gist.github.com/peterbe/6d3e1f172770ddff8b546d8527d64722

**Comment by peterbe** [comment]
I'm presuming that if the HTML is `<h2 id="What_is_WebAssembly">What is WebAssembly?</h2>` that counts as 20 (not 54) because 
```
>> "What is WebAssembly?".length
20
```

Or is it 18 because there are 2 whitespaces in there??

**Comment by gueroJeff** [comment]
It's 20. Whitespace is counted.
