### ISSUE TITLE
RSS only shows a HTML page without content

### ISSUE THREAD

**Issue by Huy-Ngo** [mdn/yari#12324]
### Summary

The RSS linked in the footer and in `<link>`  leads to an empty page

### URL

https://developer.mozilla.org/en-US/blog/rss.xml

### Reproduction steps

1. Go to https://developer.mozilla.org/en-US/blog/rss.xml
2. See a blank page

### Expected behavior

It should show a RSS feed of the blog.

### Actual behavior

It shows an empty page

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Screenshot

![an empty page on MDN](https://github.com/user-attachments/assets/6a494ca5-4bb7-48d7-a0b6-5599dc2cdfe9)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by yin1999** [comment]
This issue has been fixed, you may be able to fetch the RSS feed again :)

**Comment by Huy-Ngo** [comment]
thanks
