### ISSUE TITLE
Images do not fall back to en-US

### ISSUE THREAD

**Issue by nyan-dot** [mdn/yari#12334]
### Summary

It seems that image files do not fall back to `en-US` across all locales and pages.

### URL

https://developer.mozilla.org/ja/docs/Learn/Getting_started_with_the_web/CSS_basics

### Reproduction steps

1. Navigate to a page in a locale where images are expected to be present.

### Expected behavior

The images from `en-US` should be displayed.

### Actual behavior

A broken image icon is displayed as if the images do not exist.

### Device

Smartphone

### Browser

Chrome

### Browser version

Stable

### Operating system

Android

### Screenshot

![Screenshot_20241219-054014](https://github.com/user-attachments/assets/6a14a18b-df5f-4c6e-82a0-3b3e928e8971)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [x] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by yin1999** [comment]
We used to copy the images from en-US to l10n folders (#7917, which can prevent the broken images in documents as well as in livesamples)

We may implement the function in [rari](https://github.com/mdn/rari) as well.

**Comment by nyan-dot** [comment]
Understood. I look forward to seeing the images restored!

**Comment by fiji-flo** [comment]
resolved via https://github.com/mdn/yari/pull/12335

We now do this in the cloud function and I missed the casing in there 🙈
