### ISSUE TITLE
Auto-merge minor Depenabot upgrades too

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1236]
We use https://github.com/marketplace/actions/dependabot-auto-merge to auto-merge Dependabot PRs that upgrade various packages. But, by default, it's conservative so it only does it if (all CI passes) and the version is a "patch" update. E.g. "1.2.3" to "1.2.4". 

For example, it helped us here: https://github.com/mdn/yari/pull/1233 (yes, it looks like it was `@peterbe` who told Dependabot to merge it but that's just how the action works). 
But it couldn't help us here: https://github.com/mdn/yari/pull/1235 because it's a "minor" upgrade. 
In https://github.com/mdn/yari/runs/1096551164 you get this output:
```
title: "Bump http-proxy from 1.17.0 to 1.18.1"
from: 1.17.0
to: 1.18.1
manual merging required
```

So, shall we allow `auto-merge` to even auto-merge the minor upgrades too? How much do we trust our CI?

**Comment by peterbe** [comment]
* We still don't have any CI for testing the whole dev environment.  
  - we probably won't until we have a nice split of the content and the code
* So many times in the last couple of weeks, there's been minor upgrades to packages that are way too boring to matter.
* Yari is not even production yet! 
 - Having to manually merge is a time-sink and distraction
* Perhaps, if a minor upgrade of a package leads to something that passes CI but breaks elsewhere (in something untested) that might just be a great opportunity to add more/better tests.

**Comment by peterbe** [comment]
Thoughts and feelings @escattone @schalkneethling 
I'm personally in favor of allowing `auto-merge` to auto-merge "minors" too and not just "patch" upgrades.

**Comment by escattone** [comment]
@peterbe I agree with you. I think we should auto-merge "minors" as well. The CI tests in Yari are pretty good, and I think we can trust them. Let's at least give it a try.
