### ISSUE TITLE
Automate the data flow of popularities

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1239]
Originally from https://github.com/mdn/yari/issues/1238#issuecomment-690490486
Having to get Yari building with up-to-date popularities should be fully automated and reasonably fresh. For example, the latest rising page on MDN is the page about Same-Site cookies because of recent changes in browsers. If we don't elevate that page through our popularity rating for search stuff, pages that like will be unnecessarily harder to find.

**Comment by peterbe** [comment]
We moved it to be based on the CloudFront logs.

**Comment by schalkneethling** [comment]
It sounds like this is done from https://github.com/mdn/yari/issues/1239#issuecomment-823692354. Perhaps there is still some automation needed though? @fiji-flo Thoughts?

**Comment by fiji-flo** [comment]
That's automated.
