### ISSUE TITLE
Bikeshedding on how and where to archive content

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1242]
This issue is an "extension" of https://github.com/mdn/yari/issues/1076 digging more specifically into naming and organization. 

The current plan ([summarized here](https://github.com/mdn/yari/issues/1094#issuecomment-690688442)) is that we treat non-en-US content like we treat regular archive content (e.g. XUL). But we have options. 

Certain is that we'll have a `github.com/mdn/content` (aka. Content) repo that is going to be the source of truth replacing MySQL in the Wiki. That will only have `en-us` and it will only have non-archive content. Now we just need to figure out what do with things like 

* `/en-US/docs/Mercurial/Using_Mercurial`
* `/fr/docs/Web/JavaScript/A_propos`
* `/fr/docs/Améliorations_CSS_dans_Firefox_3`

(not picking on French, just an example. instead of `fr` imagine it's `!en-us`)

### Option 1

Create a repo for **all** things that are *not en-us* **or** *not* active content. 
E.g. `github.com/mdn/archivecontent`
This would include things like `/fr/docs/Web/JavaScript/A_propos`

### Option 2

Create a repo for **all** *en-us archive* content. And another for **all** non-en-us independent of active or archive slug. 
E.g. `github.com/mdn/archivecontent` and `github.com/mdn/localizedcontent`

### Option 3

Create a repo for **all** *en-us archive* content. And another for **all** non-en-us active content. And another for all non-en-us *archive* content. 
E.g. `github.com/mdn/archivecontent` and `github.com/mdn/localizedcontent` and `github.com/mdn/archivelocalizedcontent`.

### Option 4 (inspired by @escattone 's comment)

Create a repo for *all archived* content, independent of language. Another repo specifically for *translated active* content. 
E.g. `github.com/mdn/archivecontent` and `github.com/mdn/translatedcontent`

## Naming

Let's agree that the active en-us content should be simply called `content`. Eg. `github.com/mdn/content`.

Now, **what do we call the other repos?**

## Option 1 (archiving)

`archivedcontent`

### Option 2 (archiving)

`archivecontent`

### Option 3 (translations)

`localizedcontent`

### Option 4 (translations)

`translatedcontent`

### Option combinations

`archivedlocalizedcontent`
`archivelocalizedcontent`
`archivedtranslatedcontent`
`archivetranslatedcontent`

### Options with hyphens

All the above could be hyphenated. E.g. `archive-content` or `translated-content` 

## Important notes

* It is very possible and quite realistic that we **treat** archive content different from non-en-us content. For example, on `/ar/docs/Web/CSS` we might wanna do things differently. For example, a different banner explain the state of the doc. This would be possible to if we lump translated content with archive English content. 

* The archive content is likely never going to be useful and will die a slow death. But a lot of the now translated content we might use to train our machine learning service. For example, the Japanese and French translations in particular. 

* We might have to update these things we archive (en-us or translated) because otherwise we might publish complete junk that is just embarrassing. So, we might have to deal with PRs on the translated content. Does it them help that it's different from the split up?

* Too many repos hurt the brain. Too few makes them into monsters since they'll contain the the rendered HTML which is often huge.

**Comment by escattone** [comment]
@peterbe Wow, this is really nicely done and summarized, and I especially liked that you added those `Important notes`, thank you!

This naming here is tricky, but as you say important! In terms of splitting, I wonder if we should consider a 4th option, where this option would mean the following:
- A repo for **all archived English content and its localizations**. I'm thinking that this content will be least useful (e.g., perhaps we don't really want to use the localized content here for training purposes, since it's probably the least scrutinized for quality?), and keeping the localizations associated might be useful to those who are still interested in this content? In terms of naming, I'd vote for `archived-content`.
- A repo for **all non-archived non-English content**. I'm thinking this grouping is going to be useful for both training purposes as well as knowing that we need to display a special banner for these documents. In terms of naming, I'd vote for `localized-content`, or maybe `frozen-localized-content` so it's not confused as being the actively-maintained localized version of the `content` repo?

In terms of splitting, if this "option 4" proves unpopular, I think I like your option 3 best, with the following names: `archived-content`, `localized-content`, and `archived-localized-content`.

**Comment by chrisdavidmills** [comment]
I think what I'd like to see here is basically the same thing as what Ryan is talking about, forgive me if I'm wrong ;-)

The content team often looked at content in terms of how much we care about it, and we often split it into two groups:

1. Stuff we care about, enough to for example write linter recipes for, and think about carrying over into structured content in Yari. Examples — HTML, CSS, JS, HTTP, WebAPIs, Learning Area.
2. Stuff we don't care about, which is either already archived, or we want to get rid of asap, such as the stuff inside the `Mozilla/` directory.

So by this token, I would also go for having a repo for the yari content, a repo for the archived `en-US` content and its localizations, and a repo for the localizations of the English content we care about.

In terms of naming I would go for hyphens, as hyphenated names are easier to read and consistent with other repos in the org, and I would go for a naming scheme that always starts with `content-`, so it becomes familiar and it easier to remember or at least infer the different repo names. I'd go for

* `content`
* `content-archived`
* `content-localized`

**Comment by ddbeck** [comment]
Seconding @chrisdavidmills, both on the structure choice and making the names group together nicely. The `content-` convention makes it much more obvious that these are related.

**Comment by peterbe** [comment]
@escattone I updated my original issue text with an "Option 4". Did I get that right?

It's actually an interesting and attractive option because this way we can write a piece of code like this:
```javascript
if (doc.isArchived) {
  return <ArchivedContentBanner/>
} else if (doc.locale !== 'en-us') {
  return <TranslatedContentFrozenBanner/>
} else {
  // No banner for active English content
  return null
}
```
Note that this way we don't say something like "This translated content is currently frozen and will be replaced by a machine in the coming months" when you're currently viewing something like `/fr/docs/Mozilla/XUL`.

**Comment by peterbe** [comment]
In terms of names (the true bike shedding), I would argue that `archived-content` is better than `content-archived` because it just reads better if you read it without a hyphen. And this way, you don't suffer from bad tab completion after you've typed `cd ~/project/mdn/cont[TAB]` :)
Yes, it's all content so as a prefix it kinda makes sense but I think this form (i.e. "archived-content") sets it apart a bit more strongly. I think it'd be different if it was grouping like `content-tier1`, `content-tier2`, `content-tier3`. 
Are you OK to buy that @chrisdavidmills @ddbeck ?

**Comment by peterbe** [comment]
Can I propose a personal preference? After much dog-walking-thinking on this, I've become **a fan of the word "translated" instead of "localized"**. 

* It's the English strings of text that has been translated by (ideally) not rewritten to be appropriate for the locale. I.e. we replace the English prose, not rewrite the examples to be about olives instead of jam for the Greek translation. 
* Localization (*"the process of making something local in character or restricting it to a particular place."*) is bigger and broader term than translated and can easily be confused for internationalization which, to me, is about making MDN feel like it's running in the locale with the appropriate date and number formatting and stuff. 
* What the contributors did was translate, in terms of the right verb. I don't think you'd ask Julien "Have you localized the new Web API X page yet?"

**Comment by ddbeck** [comment]
@peterbe the main thing to me is showing that the repos are, in fact, related. I do feel like there should be a common prefix for them, especially if stuff is expected to cross repo boundaries (e.g., moving something from `content` → `archive`). Maybe `web-docs-content`, `web-docs-archive`, `web-docs-translations`?

(If GitHub gave us literally any other way to group repos within an org, I'd probably be a bit more relaxed about it.)

**Comment by peterbe** [comment]
For the `content` repo we bike shedded that too a lot and the justification for calling it such a short and simple name was:

1. It's already prefixed by the GitHub organization `mdn`, so no point to repeat that. 
2. For contributing writers it wouldn't make a whole lot of sense to have a folder called `~/MyProjects/content` but we realize we control the quick start guide and it'll have something like this for you to copy to your terminal: `git clone https://github.com/mdn/content.git mdn/content` which means that `git clone` will create the containing directory automatically, and voila, now it's namespaced on your laptop. 
3. Hardcore writer contributors might prefer to git clone it specifically and these folks probably already has a strong feeling about where to put it. For example, I have all my MDN related stuff in `~/dev/MOZILLA/MDN/`.

**Comment by peterbe** [comment]
Also, it does occur to me that the bike-shedding importance gets diminished by the fact that we're expect that the whole people in the universe that will ever check out these archive and translated repos are:

1. Ryan and Peter - hacking on the Yari build tool when it builds archived stuff.
2. Our GitHub Action Production build workflow, which we control. 

It's different for Content and Yari because these expect to be forked and contributed to by tens or hundreds of humans. These repos will need carefully crafted and up-to-date READMEs. 

Perhaps that's fuel enough to realize that the name isn't as important as I might have made it out to be.

**Comment by chrisdavidmills** [comment]
> Are you OK to buy that @chrisdavidmills @ddbeck ?

Sure, I can buy that. I don't have a really strong preference as to the order of the words — after a few days it just becomes dealt with by muscle memory anyway.

> Can I propose a personal preference? After much dog-walking-thinking on this, I've become a fan of the word "translated" instead of "localized".

Again, I don't think either would be a deal breaker here. One concern is that historically on MDN we have always used `localization` or `l10n`, not `translation`, for this purpose. Is that an issue? Or is this a good point to make a change for the better? I do agree with you that translation is more specific and fit for purpose.

**Comment by peterbe** [comment]
@escattone and I had a lengthy discussion on this and have now decided on all the names and splitting. Here it goes. 

2 new repos (beyond the `content` one):
  - `archived-content`: Everything that's considered archived based on the slug, independent of the locale
  - `translated-content`: Everything that isn't active English or archived

Note the use of the:

* hyphen
* distinction that "content" is a suffix rather than a prefix/namespace
* "archived", not "archive"
* "translated", not "localized"

Thank you all for your help! Much appreciated.
