### ISSUE TITLE
Rethink the homepage

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1255]
As we have mentioned between us, the bulk of what currently makes up the homepage is either going away or, going be less useful to our end users. With that, we should start thinking about ideas around how to make better use of this page.

Below is one simple idea that can be implemented with little effort as a starting point. Would appreciate everyone's ideas here.

![mdn-home (1)](https://user-images.githubusercontent.com/10350960/93069362-dbf78c80-f67d-11ea-8ccd-145abd9f5c2d.png)

**Comment by schalkneethling** [comment]
Something else I saw on the TypeScript landing page is what is shown in the screenshot below. Essentially it lists a couple of the most used documentation pages. I am thinking with @peterbe's popularity score work, we could create a component such as this to add to the homepage?

![Screenshot 2020-09-13 at 12 01 42](https://user-images.githubusercontent.com/10350960/93069660-3c86c980-f67e-11ea-8f3a-54f2fb483175.png)


Perhaps later on this is something a user can edit when signed in?

**Comment by peterbe** [comment]
I like it a lot. I would argue that what you have in the first screenshot is what you'd get on https://developer.mozilla.org/en-US/docs/Web and so I would be much in favor of the homepage only being a big fat prominent search, links to the 3 main areas, and some widget about recent updates or, like you demonstrated, some of the most popular pages. 

But there are other interesting elements to consider too. For example; a list of testimonials from prominent Open Source thoughtleaders. Or, a widget that shows the number of new issues in yari, content, or browser-compat-data. 
Or pictures of human faces. Or interviews with (learning) web developers, like a blog. 

Whatever we do, let's make it so we want to go there ourselves. Rather than a space that needs to be filled.

**Comment by chrisdavidmills** [comment]
I agree with what I'm seeing so far; I like some variation of the most critical areas, plus a search.

I'd also like to see a small section entitled something like "Learn web development", with the text "New to web development? Learn all you need to know with [Learn Web Development](https://developer.mozilla.org/en-US/docs/Learn)."

Also, in the "Help improve MDN" section, what's there at the moment is good, but I am currently rethinking the contribute pages to make it much easier for community members to find things to do to help with the content. At the moment it is nigh-on impossible. This will probably involve making significant changes to https://developer.mozilla.org/en-US/docs/MDN and https://developer.mozilla.org/en-US/docs/MDN/Contribute; you might need to change one of the links on there fairly soon, but fine for now.

**Comment by peterbe** [comment]
Perhaps we need a Miro board to collect all the great ideas and inspire each other. 

I for one wouldn't mind seeing more human faces on MDN. And the homepage is a great place for that to start. Either stock photos or actual mugshots of real testimonial givers.

**Comment by peterbe** [comment]
One thing I often reach for myself is a list pages I've recently visited. Right now, all I've got is the address bar. 
But what we could do is use `localStorage` and simply do something like this:

```javascript
const visited = JSON.parse(localStorage.getItem('visited'))
visited.push([window.location.pathname, new Date().getTime(), document.title])
localStorage.setItem('visited', JSON.stringify(visited))
```
And equipped with that we can list these build a list on the home page. And if we also compare the dates we'd be able to see **if the page has been modified since you last visited**.

**Comment by chrisdavidmills** [comment]
I really like this, @peterbe. This would give users much more of a reason to visit the homepage.

**Comment by peterbe** [comment]
I'm using this issue as Miro idea board :)

But seriously, I think it's good to open your mind and say out loud as if time and resources wasn't an issue.

**Comment by schalkneethling** [comment]
> One thing I often reach for myself is a list pages I've recently visited. Right now, all I've got is the address bar.
> But what we could do is use `localStorage` and simply do something like this:
> 
> ```js
> const visited = JSON.parse(localStorage.getItem('visited'))
> visited.push([window.location.pathname, new Date().getTime(), document.title])
> localStorage.setItem('visited', JSON.stringify(visited))
> ```
> 
> And equipped with that we can list these build a list on the home page. And if we also compare the dates we'd be able to see **if the page has been modified since you last visited**.

This is again something we can easily user test using a web extension and have people vote on the usefulness. If we get the right signals back from users, we know it is worth our time to build it into the product itself.

**Comment by schalkneethling** [comment]
Depends on https://github.com/mdn/yari/issues/2438

**Comment by mattiapontonio** [comment]
As for the illustration, I don't think working on the ground is healthy from a posture point of view.
I like [Jira](https://www.atlassian.com/software/jira)/[Atlassian](https://www.atlassian.com/) who often uses the concept of constructions which I don't mind. Think of web development as a construction site 👷👷‍♀️🚧🛠️🏢🏗️.

**Comment by Ryuno-Ki** [comment]
Before starting about what goes into it, let me ask you one question:

Who's the intended audience(s)?
What they have in mind when they visit the homepage?

I think, we should design from a „jobs to be done” perspective.

**Comment by mattiapontonio** [comment]
I'm thinking of **3** colored boxes that take up just the right amount of space on mobile phones: **HTML**, **CSS** and **JavaScript**.
The rest must be removed from the homepage.

**Comment by peterbe** [comment]
@chrisdavidmills @schalkneethling So close now! The Kuma home page is almost ready. Once there we can open up the discussion about what *else* to put on the home page. 

As a matter of fact, I think we should move this to Discussions and move it back here to an issue once we decide on what to do. Also, we might be getting some external help with the home page.

**Comment by schalkneethling** [comment]
> As a matter of fact, I think we should move this to Discussions and move it back here to an issue once we decide on what to do. Also, we might be getting some external help with the home page.

Let's move the discussion over here: https://github.com/mdn/yari/discussions/2940

**Comment by schalkneethling** [comment]
Handled by the redesign and tracked elsewhere.
