### ISSUE TITLE
One popularities.json file per locale

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1262]
What we're using `popularities.json` for is to make sure the `search-index.json` file is sorted by popularity. Those are dumped to disk on a per-locale basis anyway.

**Comment by schalkneethling** [comment]
How we do this has changed: https://github.com/mdn/yari/blob/84e6ef1c6097a3e741dc362a00750e31add9832c/.github/workflows/prod-build.yml#L170

We should update the docs to reflect the changes.
