### ISSUE TITLE
Delete never-used ks macros

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1274]
Using the [`BUILD_LOG_MACROS_USED`](https://github.com/mdn/yari/pull/1249) env var you can get a log of all ks macro calls. You can combine that log output with the listing of `kumascript/macros/*.ejs` to get the difference of what never appears in the log files. I.e. macros that are not used by any active content. 

Here's a nifty Python script you can use:

```python
import sys
from pathlib import Path
from collections import defaultdict

macros_used = defaultdict(int)

with open(sys.argv[1]) as f:
    for line in f:
        macro_name = line.split('|')[0]
        macros_used[macro_name] += 1

macros_possible = {
    x.name.lower().rsplit('.', 1)[0]:x for x in
    Path('kumascript/macros').iterdir()
    if x.name.endswith('.ejs')
}

flat = sorted([
    (macros_used.get(x) or -1, x) for x in macros_possible
], reverse=True)
# from pprint import pprint
# pprint(macros_used)
# from pprint import pprint
# pprint(macros_possible)

print("MOST POPULAR...")
for used, name in flat:
    if used > 0:
        print(f'{name:<30} {used:,}')
print('\n')


deletable = len([x for x,y in flat if x <=0])
print(f"DELETE WORTHY (never used) ({deletable})")
for used, name in flat:
    if used <= 0:
        print(macros_possible[name])
```

Equipped with this, we should be able to delete about 50 `.ejs` macros that are never used.

**Comment by peterbe** [comment]
I think my python script is fine. Here's how you use it.
```
yarn prepare-build
export BUILD_MACROS_USED_LOGFILE=/tmp/macros-used.log
yarn build
```
...wait ~10min...
```
python peterbe__analyze_macros_used.py /tmp/macros-used.log
```

**Comment by peterbe** [comment]
Today, now that Uplift is complete. I ran a complete build with `BUILD_MACROS_USED_LOGFILE` and analyzed which, compared to the `kumascript/macros/*.ejs` that were never executed. 

```
kumascript/macros/jsapixref.ejs
kumascript/macros/jsapi_minversion_inline.ejs
kumascript/macros/jsapi_minversion_header.ejs
kumascript/macros/jsapi-requires-request.ejs
```
https://github.com/mdn/yari/pull/3059

```
kumascript/macros/LocalizationStatusInSection.ejs
kumascript/macros/LegacyAddonsNotice.ejs
kumascript/macros/jsctypesSidebar.ejs
```
https://github.com/mdn/yari/pull/3060

```
kumascript/macros/SpiderMonkeySidebar.ejs
kumascript/macros/SimpleBanner.ejs
kumascript/macros/SimpleBadge.ejs
kumascript/macros/Preferences_System_TOC.ejs
```
https://github.com/mdn/yari/pull/3061

```
kumascript/macros/xref2.ejs
kumascript/macros/xref.ejs
```
https://github.com/mdn/yari/pull/3062
```

**Comment by Ryuno-Ki** [comment]
Wow, that's a lot of cruft!
Another benefit of moving to GitHub, I guess?
(As in: this kind of analysis wouldn't have been possible with the wiki setup)

**Comment by peterbe** [comment]
Note-to-self; The following are used in less than 10 places:
```
userlink                       9
cssanimatedproperties          9
訳語                             6
addonsidebarmain               3
tree                           2
lxrsearch                      2
b2gonlyheader2                 1
```

Might be worth hunting those down.

**Comment by peterbe** [comment]
To worry about macros that are only ever used in translated content, let's discuss that in: https://github.com/mdn/yari/issues/3063

**Comment by Ryuno-Ki** [comment]
What's the third one meant to mean? It shows `[][]` on my system (likely missing a font with those glyphs).
If I copy-paste them into a search engine, I get results like https://ja.wikipedia.org/wiki/%E8%A8%B3%E8%AA%9E - so something Japanese.
