### ISSUE TITLE
Code examples should be wrapped in a code element

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1281]
On current production code examples are wrapped as follows:

```
<pre class="brush: html notranslate line-numbers language-html">
  <code class=" language-html">
    ...
  </code>
</pre>
```

In Yari, the nested `code` element is missing. The interesting thing is if you look at the source of the content of a wiki page, it only contains the `pre`. This means there is some post-processing that adds these nested `code` elements. This also explains why these are missing in Yari.

After having spoken to @chrisdavidmills it was agreed that for proper HTML semantics, we should keep the existing behavior of wrapping code example in both a `pre` and a nested `code` element.

[1] https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-code-element

**Comment by peterbe** [comment]
> This means there is some post-processing that adds these nested `code` elements.

Pretty sure that's the client-side PrismJS that mutates the DOM.

**Comment by peterbe** [comment]
As we call Prism in Node too, I don't know why we're not letting it output the result wrapped in a `<code>` but I can look into it.

**Comment by peterbe** [comment]
Note-to-self; there are probably times when the content already is, hardcoded, to `<pre><code>...` so we don't want that to become `<pre><code><code>...`.
