### ISSUE TITLE
CanvasRenderingContext2D.drawImage() looks bad on mobile

### ISSUE THREAD

**Issue by 532910** [mdn/yari#1309]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawImage

![image](https://user-images.githubusercontent.com/14617699/93814308-04265300-fc5d-11ea-93bb-b4f61adedebe.png)

**Comment by schalkneethling** [comment]
![Screenshot 2020-12-12 at 06 34 38](https://user-images.githubusercontent.com/10350960/101975301-1e604380-3c44-11eb-836a-a6918c43eb3f.png)

Resolved.

**Comment by 532910** [comment]
Is it released? I still see the same result.

**Comment by 532910** [comment]
I confirm this is fixed now!
