### ISSUE TITLE
Banner to explain that something is archived

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1312]
*This* issue isn't really about archived localized content. It's about the regular archived content. The URLs that we don't actively maintain in mdn/content. E.g. http://localhost:5000/en-US/docs/XUL/Attribute/onunload

People might wonder why there's no "Edit on GitHub" link in the footer. 

Actually, not even certain whether it should be displayed as a banner. 

* Perhaps it's enough to just have a note in the footer. 
* Perhaps we should link to a blog post to explain the reasoning?
* Perhaps we can link to https://github.com/mdn/archived-content#readme
* Perhaps both a banner and a note in the footer?

**Comment by peterbe** [comment]
As part of my work on https://github.com/mdn/yari/issues/1078 I threw in a quick hack. It works in terms of core functionality but clearly it doesn't answer any of the questions in this issue's description. 
<img width="803" alt="Screen Shot 2020-09-24 at 10 22 26 AM" src="https://user-images.githubusercontent.com/26739/94158325-44015c00-fe50-11ea-960e-31e07036bf14.png">

It's a greater-than-zero start. At least it's something can control from the React code now.

**Comment by peterbe** [comment]
@schalkneethling I removed myself from assignment. I think it's up to you to style it now, right?

**Comment by schalkneethling** [comment]
> @schalkneethling I removed myself from assignment. I think it's up to you to style it now, right?

Yup, sounds correct to me.

**Comment by peterbe** [comment]
Now it's worse as it appears at the bottom of the page. :)
<img width="800" alt="Screen Shot 2020-11-18 at 12 39 17 PM" src="https://user-images.githubusercontent.com/26739/99566625-29081f80-299b-11eb-850b-e295d1a15794.png">
