### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1320]
For language selection in the header area of documentation pages, we have a custom-styled dropdown. See below:

![Screenshot 2020-07-10 at 12 03 24](https://user-images.githubusercontent.com/10350960/87142833-677f2680-c2a5-11ea-8493-440a2868900e.png)

## Implementation decision and next steps
- Add standard dropdown for language select
- Add [Add translation] link next to language select dropdown (desktop only)
![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/c3f6ffc7-9da9-41a3-bdb6-78bfd924940b)
- Keep dropdown for language select on mobile
- Truncate dropdown below [table of contents]/[jump to section] component
- Dropdown spans full width on mobile
![image.png](https://images.zenhubusercontent.com/5dcb02f3b2765800014d8c01/8f2c43f6-38d3-48d7-a1f0-e8819bb36499)

## Existing problems

The first downside between the current implementation and simply using a standard browser select element is that

1. It uses additional CSS and JavaScript to mimic a select element's dropdown behavior
2. There is not functional parity between it and a standard select and so, we lose some accessibility benefit we get for free when using a standard platform element

There is also a known problem on pages where there is a lot of available languages. As can be seen below, the dropdown extends beyond the viewport and a user needs to scroll the document to see all languages:

![Screenshot 2020-07-10 at 12 02 58](https://user-images.githubusercontent.com/10350960/87143178-f55b1180-c2a5-11ea-9116-30dd9bd5dec8.png)

One of the possible reasons we decided to use a custom dropdown is to accommodate the "Add a translation" option.

![Screenshot 2020-07-10 at 12 03 19](https://user-images.githubusercontent.com/10350960/87143275-1d4a7500-c2a6-11ea-9fc9-5b930cb19a15.png)

## Proposal

Use a standard select element for the languages, and provide move "Add a translation" to a button(this might be a feature we will loose entirely once the move to Github is complete)

For example:

![Screenshot 2020-07-10 at 12 13 03](https://user-images.githubusercontent.com/10350960/87143675-c2fde400-c2a6-11ea-9eff-de1bbabace61.png)

#### Expanded

![Screenshot 2020-07-10 at 12 16 46](https://user-images.githubusercontent.com/10350960/87143956-44ee0d00-c2a7-11ea-81be-f88a9becc096.png)

### Benefits

1. Simple to implement
2. Easy to maintain
3. Less CSS
4. Smaller DOM
5. Less JavaScript
6. Greater accessibility

**Comment by peterbe** [comment]
> Note that in terms of implementation, we will currently only implement this change in Kuma as Yari does not currently support any l10n aka. we need to remember to update the relevant acceptance criteria to reflect this

That's not true. We will launch Yari with l10n. 

I haven't even bothered to actually look at the issue here above but I think this issue should be left open and something that we add to Fiori *after* launch if the new language switcher is (going to be) much better.

**Comment by peterbe** [comment]
Talked to @schalkneethling I'm going to do the implementation of this. In `master`. It'll always be a `<select>`. Even if there's only one other language and it will always have a `<option value="$locale" selected>$native</option>` at the top of the list.

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/pull/1372
