### ISSUE TITLE
Deployer update-lambda-functions command publishes a new version when no change 

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1331]
When running the `deployer update-lambda-functions` command in GitHub Actions, a new Lambda package is uploaded and published even if no changes have been made from the current version. This seems to happen only when a new `mode_modules` directory is created (i.e., a fresh `yarn install`), so I suspect we're including information in the ZIP file from `node_modules` that changes for every `yarn install`. This is not a blocker, but it would be nice to understand if we can fix this.

**Comment by schalkneethling** [comment]
@escattone still an issue?

**Comment by escattone** [comment]
@schalkneethling Yes, this is still a minor but annoying issue. I might try to explore this further within the next 3 weeks.

**Comment by caugner** [comment]
Fixed via https://github.com/mdn/yari/pull/6129 and https://github.com/mdn/yari/pull/6202.
