### ISSUE TITLE
Link to file an issue about the page you're viewing

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1342]
At the moment, in the document footer, we have an "Edit in GitHub" link which takes to the blob view of that document. We should consider something more verbose that also has an "automated link" to filing an issue. I.e. one that prefills the new-issue text based on the page you were on.

**Comment by peterbe** [comment]
whatwg (w3c) uses this for their issue filing [for example](https://github.com/whatwg/html/issues/new?title=%22The%20element%20can%20be%20used%20for%20typographical%20effec...%22&body=https%3A%2F%2Fhtml.spec.whatwg.org%2Fmultipage%2Fsections.html%23the-aside-element%0A%0A%3E%20The%20element%20can%20be%20used%20for%20typographical%20effects%20like%20pull%20quotes%20or%20sidebars%2C%20for%20advertising%2C%20for%20groups%20of%20nav%20elements%2C%20and%20for%20other%20content%20that%20is%20considered%20separate%20from%20the%20main%20content%20of%20the%20page%5C)

**Comment by peterbe** [comment]
Next action: I'm going to put something together that isn't phrased or worded perfectly. Then I'll throw it over to @chrisdavidmills to "perfect" (aka. wordsmith it).

**Comment by escattone** [comment]
This issue is related: https://github.com/mdn/yari/issues/1435
