### ISSUE TITLE
Better linking from BCD table to github.com/mdn/browser-compat-data issue filing

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1344]
Today, on the [BCD table](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap#Browser_compatibility) we have a link (outside the table) which is:

```html
<a class="bc-github-link external" href="https://github.com/mdn/browser-compat-data" rel="noopener">
  Update compatibility data on GitHub</a>
```

The problem with this is that it doesn't carry any information about which BCD table you *came from*. Let's come up with a better link to the new-issue filing page that carries information about where you came from.

**Comment by peterbe** [comment]
@ddbeck agrees to think about what the (near) perfect issue filing template should be, I can prepare the React code so that that link works.

**Comment by peterbe** [comment]
Note; this is very similar to this topic: https://github.com/mdn/yari/issues/1342

**Comment by ddbeck** [comment]
OK, here's my dream scenario (that doesn't know anything about BCD's internals):

## As a reader

I'm looking at a page and I see some questionable data. I click a link that says something like "Report an issue with this compatability data". It takes me to a pre-filled new issue form on GitHub that looks something like this:

**Title:** api.WindowOrWorkerGlobalScope.fetch - [REPLACE THIS WITH A TITLE]
**Write:**
```
<!-- Tips: where applicable, specify browser name, browser version, and mobile operating system version -->

#### What information was incorrect, unhelpful, or incomplete?

#### What did you expect to see?

#### Did you test this? If so, how?


<!-- Do not make changes below this line -->
<details>
<summary>MDN page report details</summary>

* Query: `api.WindowOrWorkerGlobalScope.fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch
* Macro call: `{{ Compat("api.WindowOrWorkerGlobalScope.fetch", 10) }}`
* Report started: 2020-09-30 13:14

</details>
```

## As a reviewer

After the reader submits the issue, I hopefully get something that looks like this:

### api.WindowOrWorkerGlobalScope.fetch - Missing Firefox support for data: URIs


#### What information was incorrect, unhelpful, or incomplete?

I wanted to know whether Firefox supported `data:` URIs with `fetch()`. Firefox's table cell for that feature is blank.

#### What did you expect to see?

Version 103.

#### Did you test this? If so, how?

I consulted my astrologer.


<details>
<summary>MDN page report details</summary>

* Query: `api.WindowOrWorkerGlobalScope.fetch`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/fetch
* Macro call: `{{ Compat("api.WindowOrWorkerGlobalScope.fetch", 10) }}`
* Report started: 2020-09-30 13:14

</details>

**Comment by ddbeck** [comment]
Oh one more thing: if the source for the issue template can be its own file that I could link to from the BCD docs, that would be helpful. Then I could do PRs against Yari to update the template (for example, I just remembered that I should ask people to link to bug trackers).

**Comment by peterbe** [comment]
> if the source for the issue template can be its own file that

That unfortunately wasn't super easy. The use of the template happens in the front-end. (Yes, technically the front-end code is used by Node too when it server-side renders the pages). 
We depend on create-react-app and how it implements Webpack. As far as I know you can only import `.json` and `.scss` and `.css` files. Not `.txt` or `.html`. 
So I hardcoded the template into the main source code file which is unlikely to move. In fact, if we mention the BCD documentation in a code comment, it'll remind future coders that this string constant is referred to by something else.

**Comment by ddbeck** [comment]
> In fact, if we mention the BCD documentation in a code comment, it'll remind future coders that this string constant is referred to by something else.

This works for me. Thank you!
