### ISSUE TITLE
Redirects should automatically follow to the final destination

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1350]
This is something we noticed when working on https://github.com/mdn/yari/pull/1349

Imagine you put this in the `mdn/content/files/en-us/_redirects.txt`:

```
/en-US/docs/Foo /en-US/docs/Bar
/en-US/docs/Bar /en-US/docs/Buzz
```

Now, if you try to use this you get:

```javascript
const { Redirect } = require("./content");
console.log(Redirect.resolve("/en-US/docs/Foo"));
```
This will output:
```
/en-US/docs/Bar
```
when, in fact, it should output `/en-US/docs/Buzz`.

**Comment by peterbe** [comment]
@escattone 
The urgency of this isn't particularly high. It would be nice if we can solve it first and foremost in the dumper where we worked hard figure out the "final destinations" for redirects. But somehow we failed to use that when we dump to disk to write the `_redirects.txt` file. 

At the moment, in the mdn/content/files/en-us/_redirects.txt I think there are 20-30 lines that redirect, from "A to B" where there already exists a "B to C". In other words, it should have had "A to C" and "B to C" only. 

Speaking of the dumper; note that we still have a couple of lines in the `_redirects.txt` where the "from" is equal to the "to".

**Comment by peterbe** [comment]
Hmm... https://github.com/mdn/content/pull/25 didn't fail in CI. 
I think the simplest start is the fact that how `get-diff-action` didn't even bother with the PR Build workflow because there were no changes to to `files/**/*.html`.

**Comment by peterbe** [comment]
Now blocked by: https://github.com/mdn/yari/pull/1358

**Comment by fiji-flo** [comment]
Resolved by `shortCuts` in redirect.js
