### ISSUE TITLE
wiki.tree walks the entire tree regardless of the depth argument

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1354]
For context see https://github.com/mdn/yari/pull/1351#issuecomment-701471033. Here's the key snippet:

> What's going on?!!
> 
> The http://localhost:5000/en-US/docs/Web/API page only has about 1,000 links. Which makes sense since there are about 1,000 immediate children of that page.
> 
> So, is there a horribly inefficient implementation in that somewhere the `wiki.tree(...)` that causes an un-hinged deep recursion but only bothers to render the first level or something?

That's a great observation and question. There are two causes to this. First, the original Kumascript code for `page.subpages` would take the depth into account and pre-build the entire tree. I modified that such that the `subpages` getter is lazy (i.e., only created on-demand) (see https://github.com/mdn/yari/blob/65ef826345c519114c36b5f5d56a4d4f3c03e3d0/kumascript/src/info.js#L143). This allows the users of the subpages data to go as deep as needed. Second, I see that `wiki.tree` doesn't take the depth into account and recurses as deep as it can go, which means all the way because of the first point above (see https://github.com/mdn/yari/blob/65ef826345c519114c36b5f5d56a4d4f3c03e3d0/kumascript/src/api/wiki.js#L232).

**Let's fix `wiki.tree` to only walk the subpages to the depth requested.**

**Comment by peterbe** [comment]
@escattone I think https://github.com/mdn/yari/issues/1434 is mainly a matter of content. One quick edit in the wiki before migration day and poof, solved. But if we do *any* display of `{{ListSubpages}}`, and it does this unbounded depth recursion, it's going to display too many links and it's not just a matter of optimization.
