### ISSUE TITLE
contributors.txt and index.html don't work in CDN

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1363]
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Thunderbird works.
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Thunderbird/index.json works.
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Thunderbird/index.html does *not* work. 
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Thunderbird/contributors.txt does *not* work. 

These files [do exist](https://s3.console.aws.amazon.com/s3/buckets/mdn-content-dev/main/en-us/docs/mozilla/thunderbird/?region=us-west-2&tab=overview).

**Comment by escattone** [comment]
@peterbe I don't think https://main.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Thunderbird/index.html  should work, since https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/index.html doesn't work either.

**Comment by peterbe** [comment]
But contributors.txt should work :)

**Comment by peterbe** [comment]
Hmm... This worries me a little. But I appreciate that it's a tricky thing. 
First of all, I see that the reason `index.json` worked was because of this line: https://github.com/mdn/yari/blob/9d6344a09e410a95111ad5056f58379fa41a7e43/deployer/aws-lambda/content-origin-request/index.js#L31
That means, how's it going to work when the request is for something like https://main.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Thunderbird/screenshot.png ?
We're pretty strict with file attachments [here](https://github.com/mdn/yari/blob/9d6344a09e410a95111ad5056f58379fa41a7e43/filecheck/checker.js#L118-L127) and [here](https://github.com/mdn/yari/blob/9d6344a09e410a95111ad5056f58379fa41a7e43/filecheck/constants.js#L6-L8) so that means we could do what [our server](https://github.com/mdn/yari/blob/9d6344a09e410a95111ad5056f58379fa41a7e43/server/index.js#L160) does. 
But we can't simply just look for a list of file extensions on the URL. Because that might clash hard with URLs like this:
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json

One thing at a time I guess.

However, there's another option. S3 keys don't actually care. 
You could technically transform the `index.html` files. So *instead* of 
```python
...
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird/index.html')
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird/index.json')
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird/contributors.txt')
...
```
we do this:
```python
...
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird')
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird/index.json')
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird/contributors.txt')
...
```
I.e. the key of the first one is the name of the folder. 
This kind of madness trickery only makes sense on S3, but it'll work anybody ever needs to see what's inside the bucket since the CloudFront will always be in front. 

That way, in origin-request you could do something like this:
```diff
  // Rewrite the URI to match the keys in S3.
  // NOTE: The incoming URI should remain URI-encoded.
+  let newURI = request.uri;
+  if (newURI.endsWith('/')) { newURL = newURL.slice(0, -1); }
+  newURI = slugToFolder(newURI);
-  let newURI = slugToFolder(request.uri);
-  if (newURI.includes("/docs/") && !newURI.endsWith("/index.json")) {
-    if (!newURI.endsWith("/")) {
-      newURI += "/";
-    }
-    newURI += "index.html";
-  }
  request.uri = newURI;
```
Now, there's no exceptions or special treatment on a per-file extension basis.
