### ISSUE TITLE
permanently redirect a URL with a trailing slash to the same URL without one

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1365]
MDN currently 301 redirects https://developer.mozilla.org/en-US/docs/Web/CSS/ to https://developer.mozilla.org/en-US/docs/Web/CSS. We should do the same or else we'll confuse Google.

Currently in Yari, both https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/ and https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS return the same result.

**Comment by peterbe** [comment]
To extend my idea [here](https://github.com/mdn/yari/issues/1363#issuecomment-702683169), all we'd need to do is something like this:
```diff
  // Rewrite the URI to match the keys in S3.
  // NOTE: The incoming URI should remain URI-encoded.
+  let newURI = request.uri;
+  if (newURI.endsWith('/')) { return redirect(301, newURI.slice(0, -1)) }

+  newURI = slugToFolder(newURI);
-  let newURI = slugToFolder(request.uri);
-  if (newURI.includes("/docs/") && !newURI.endsWith("/index.json")) {
-    if (!newURI.endsWith("/")) {
-      newURI += "/";
-    }
-    newURI += "index.html";
-  }
  request.uri = newURI;
```

**Comment by escattone** [comment]
See https://github.com/mdn/yari/pull/1373
