### ISSUE TITLE
A change to header on mobile

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1369]
After having a look around at home some other developer-related websites such as Github handle their headers on mobile and talking with @peterbe, we have decided to rework the header on mobile a little.

This brings it more in line with what people generally expect, and also makes the underlying implementation less fragile. Essentially this means that the initial state of the header on mobile will be:

![Screenshot 2020-10-02 at 08 45 57](https://user-images.githubusercontent.com/10350960/94895464-c363e080-048b-11eb-97eb-3c2763fbd59d.png)

When the menu is then expanded, it will look as below:

![Screenshot 2020-10-02 at 09 14 44](https://user-images.githubusercontent.com/10350960/94897369-c3fe7600-048f-11eb-92cf-593131408075.png)

Here is another option for when the menu is expanded

![Screenshot 2020-10-02 at 09 38 50](https://user-images.githubusercontent.com/10350960/94899208-2c028b80-0493-11eb-9cb1-0a4d9aa39f5f.png)

With one of the top-level menus expanded:

![Screenshot 2020-10-02 at 09 48 38](https://user-images.githubusercontent.com/10350960/94899990-8d772a00-0494-11eb-9d23-9acefda8b943.png)

## Figma Design Doc

https://www.figma.com/file/YYVJ8uqG8UFBBvQhdI7fxR/MDN-Web-Docs?node-id=221%3A7

**Comment by peterbe** [comment]
I love it! Yes please! 
Can we have this in Yari1 already?

But I don't like the black background because it really makes it hard to read. When it's all white, it's sufficiently clear that the first 3 things are content navigation items. That's probably because you have really good icons. Arguably, despite my extremely low confidence in seeing my own face, I think it would be nicer to see my mugshot that the little GitHub icon.

**Comment by peterbe** [comment]
> Can we have this in Yari1 already?

Oh I see. You added the `Yari1` Milestone so you probably think this is doable this month.

It's going to make the header slightly different on the home page (and sign up and site search) in the launch but I'm fine with that.

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/pull/1430
