### ISSUE TITLE
Ability to build any branch and prefix in Production Build

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1370]
In the [Production Build](https://github.com/mdn/yari/actions?query=workflow%3A%22Production+Build%22) workflow we ask a couple of questions: https://github.com/mdn/yari/blob/9d6344a09e410a95111ad5056f58379fa41a7e43/.github/workflows/production-build.yml#L9-L21
Imagine we add a new question that is something like this:

```yml
      deployment_prefix:
        description: "Deployment prefix"
        required: false
        default: "main"
```

Now, we need to change:

```diff
          cd deployer
          export DEPLOYER_BUCKET_NAME=mdn-content-dev
-         export DEPLOYER_BUCKET_PREFIX=main
+         export DEPLOYER_BUCKET_PREFIX=${{ github.event.inputs.deployment_prefix }}
```

Now, I can manually trigger a Production Build and override "main" with something like "mdn-fiori" or "peters-web-perf-experiment". 

Then, that means these root folders will exist in the S3 bucket. 
If I [read this correctly](https://github.com/mdn/yari/blob/9d6344a09e410a95111ad5056f58379fa41a7e43/deployer/aws-lambda/content-origin-request/index.js#L47) it means that I'd be able to try any domain simply by replacing "main" here:

* From: `https://main.content.dev.mdn.mozit.cloud/`
* To: `https://peters-web-perf-experiment.content.dev.mdn.mozit.cloud/`

That means that we the core team, can deploy any interesting branch (as long as it's pushed to the mdn/yari repo) all the way to a fully formed CDN. 
And this is huge!!

We can now hack on something (e.g. a web perf experiment or a redesign idea) and, push the branch to GitHub, press the "Run workflow" button and voila you now have a complete site fully deployed. So you can now test this new domain with friends-and-family, Lighthouse, SpeedCurve etc.

**Comment by peterbe** [comment]
@escattone What do you think? Awesomest idea since prefilled tax returns?

**Comment by escattone** [comment]
@peterbe I like it. Even better than prefilled tax returns! 😆

**Comment by peterbe** [comment]
Once https://github.com/mdn/yari/pull/1387 lands, let's build all of `mdn-fiori` and see if we can host the whole site on its own domain.
