### ISSUE TITLE
An interesting idea about how to deal with file lookups in origin-request

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1371]
Hmm... This worries me a little. But I appreciate that it's a tricky thing. 
First of all, I see that the reason `index.json` worked was because of this line: https://github.com/mdn/yari/blob/9d6344a09e410a95111ad5056f58379fa41a7e43/deployer/aws-lambda/content-origin-request/index.js#L31
That means, how's it going to work when the request is for something like https://main.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Thunderbird/screenshot.png ?
We're pretty strict with file attachments [here](https://github.com/mdn/yari/blob/9d6344a09e410a95111ad5056f58379fa41a7e43/filecheck/checker.js#L118-L127) and [here](https://github.com/mdn/yari/blob/9d6344a09e410a95111ad5056f58379fa41a7e43/filecheck/constants.js#L6-L8) so that means we could do what [our server](https://github.com/mdn/yari/blob/9d6344a09e410a95111ad5056f58379fa41a7e43/server/index.js#L160) does. 
But we can't simply just look for a list of file extensions on the URL. Because that might clash hard with URLs like this:
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json

One thing at a time I guess.

However, there's another option. S3 keys don't actually care. 
You could technically transform the `index.html` files. So *instead* of 
```python
...
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird/index.html')
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird/index.json')
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird/contributors.txt')
...
```
we do this:
```python
...
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird')
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird/index.json')
s3_client.pub_object(Bucket=bucket, Key='en-us/docs/web/mozilla/thunderbird/contributors.txt')
...
```
I.e. the key of the first one is the name of the folder. 
This kind of madness trickery only makes sense on S3, but it'll work anybody ever needs to see what's inside the bucket since the CloudFront will always be in front. 

That way, in origin-request you could do something like this:
```diff
  // Rewrite the URI to match the keys in S3.
  // NOTE: The incoming URI should remain URI-encoded.
+  let newURI = request.uri;
+  if (newURI.endsWith('/')) { newURL = newURL.slice(0, -1); }
+  newURI = slugToFolder(newURI);
-  let newURI = slugToFolder(request.uri);
-  if (newURI.includes("/docs/") && !newURI.endsWith("/index.json")) {
-    if (!newURI.endsWith("/")) {
-      newURI += "/";
-    }
-    newURI += "index.html";
-  }
  request.uri = newURI;
```
Now, there's no exceptions or special treatment on a per-file extension basis.

_Originally posted by @peterbe in https://github.com/mdn/yari/issues/1363#issuecomment-702683169_

**Comment by escattone** [comment]
@peterbe Love it. This is the way forward. I'm going to get this going today if I have time.

**Comment by escattone** [comment]
@peterbe One more comment. We can't do `if (newURI.endsWith('/')) { newURI = newURI.slice(0, -1); }`. We're going to have to redirect in that case so we don't introduce confusion into Google's page rank (two URL's to the same page).

**Comment by peterbe** [comment]
> so we don't introduce confusion into Google's page rank (two URL's to the same page).

Pretty sure it's not a problem. 
Suppose that we 200 OK on both
`https://developer.mozilla.org/en-US/docs/Foo` and `https://developer.mozilla.org/en-US/docs/Foo/`
If you view source on both of them, you'll find that it has:
```html
<link rel="canonical" href="https://developer.mozilla.org/en-US/docs/Foo">
```
in both of them. So Google will just see them as 1. 

However, I still think you're right in that we ought to redirect them. It's just neater. If we allow the trailing `/` someone might copy that and some other script somewhere in the world will get confused thinking they are two different URLs.
