### ISSUE TITLE
Accessibility issues should not be present on documentation.

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#1378]
@pavandixit93 commented on [Thu Jul 30 2020](https://github.com/mdn/sprints/issues/3556)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [x] Correction or update

# Details

I was referring https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Complementary_role, documentation. Documentation is great and helpful. One thing i found that there are lots of accessibility issues present in the document when i ran AXE accessibility checker, Can you guys please fix those?

**Comment by escattone** [comment]
Closing here since it has been transferred to Yari.
