### ISSUE TITLE
Redirects should map to their final destination

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1381]
https://github.com/mdn/yari/pull/1358 touches on this but the ultimate flaw lies within the importer. 

In the `_redirects.txt` we have this:

```
/en-US/docs/window.window       /en-US/docs/Web/API/window.window
```
but we also have 
```
/en-US/docs/Web/API/Window.window       /en-US/docs/Web/API/Window/window
```

Ignore case and let's express the above differently, what we have here is:
```
A -> B
B -> C
```

What happens inside Yari is that it will execute the `getPage()` Kumascript function and it will look things up in `_redirects.txt` but it won't look if what it redirects to redirects to something else. So `getPage("A")` will, through the `info.cleanURL()` become a lookup for `getPage("B")` which will fail because that page does not exist. 

We *could* improve our `Redirects.resolve()` function so that it does what Python `requests.get()` does which is it automatically "retries" on redirects until it lands on something that is `<300` or `>=400`. 
But why should we? The importer can get this perfect on day 0 and we never have to bother doing that in the builder going forward. (In https://github.com/mdn/yari/pull/1358 we introduce a new `yarn redirects validate` function that can check (in CI) that human-introduced lines don't cause bad chains)
If we solve this in the importer (and in `yarn redirects validate`) we can keep `Redirects.resolve()` simple)

Essentially, this should NOT happen after you run the importer:
```
▶ cat _redirects.txt | rg -i 'window\.window' | rg -vi state
/en-US/docs/DOM/window.window	/en-US/docs/Web/API/window.window
/en-US/docs/DOM:window.window	/en-US/docs/Web/API/window.window
/en-US/docs/Document_Object_Model_(DOM)/window.window	/en-US/docs/Web/API/window.window
/en-US/docs/Web/API/Window.window	/en-US/docs/Web/API/Window/window
/en-US/docs/window.window	/en-US/docs/Web/API/window.window
```

What it SHOULD be is this:
```diff
▶ cat _redirects.txt | rg -i 'window\.window' | rg -vi state
-/en-US/docs/DOM/window.window	/en-US/docs/Web/API/window.window
+/en-US/docs/DOM/window.window	/en-US/docs/Web/API/Window/window
-/en-US/docs/DOM:window.window	/en-US/docs/Web/API/window.window
+/en-US/docs/DOM:window.window	/en-US/docs/Web/API/Window/window
-/en-US/docs/Document_Object_Model_(DOM)/window.window	/en-US/docs/Web/API/window.window
+/en-US/docs/Document_Object_Model_(DOM)/window.window	/en-US/docs/Web/API/Window/window
/en-US/docs/Web/API/Window.window	/en-US/docs/Web/API/Window/window
-/en-US/docs/window.window	/en-US/docs/Web/API/window.window
+/en-US/docs/window.window	/en-US/docs/Web/API/Window/window
```

**Comment by fiji-flo** [comment]
resolved in #1359
