### ISSUE TITLE
Sourcemaps for the cli

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#139]
The cli does run [`sourceMapSupport.install()`](https://github.com/mdn/stumptown-renderer/blob/7a718c47ed8a6d85d21fe124896a2f556a821ee3/cli/index.js#L31) but I suspect it's not working as expected with babel etc. The cli and its webpack config was the very first thing I started when I started this project so it's most likely rough and hacky. 

The problem comes from the fact that unexpected errors produce near useless stack traces. 

Try...

1. Edit something like `client/src/document.js` and put in a `throw new Error('hello world')` somewhere in some component. 
2. Run `cd cli && CLI_BUILD_HTML=true yarn run run ../stumptown/packaged/html/reference/elements/video.json`

**Comment by peterbe** [comment]
One thing that might be unrelated to this but nevertheless important is the context. Usually the `cli` is asked to run itself for many files and it's not unrealistic that it works for 99 found .json files but fails on 1 of them. Perhaps due to "corrupt stuff" from `stumptown-content`. Usually in a SSR NodeJS Express solution if you get an error it's usually pretty good at mentioning context in the form a URL. What's really important is to know which .json file was the cause of the trouble. Perhaps the simplest solution would be to do something like this:

```
foundJsonFiles.forEach(path => {
  console.log(`About to render ${path}`)
  cliMeatFunction(path);
})
```
so you can simply look at what was the *last* console.log path.

**Comment by peterbe** [comment]
@Gregoor Is this something you'd be interested in investigating?

**Comment by Gregoor** [comment]
Yup! Will look at it tomorrow

**Comment by peterbe** [comment]
Note-to-self; I wonder if our babel strips the sourcemap registration in the built bundle. 
Perhaps https://www.npmjs.com/package/babel-plugin-stack-trace-sourcemap is something we should add to the cli.

**Comment by peterbe** [comment]
There is no CLI any more. There's still the SSR piece which is transpiled with Webpack and we still don't really have good sourcemaps for it. 
But we're being smart in that we do as little as we possibly can in the `ssr/*.js` code. Most things are happening inside `content/*.js` or `build/*.js` or `client/src/**/*.tsx` where either sourcemaps are moot or where we actually have it working quite nicely. 

The bestest solution might just be to switch to Next.js instead of create-react-app since they actually have a fully supported solution for SSR *and* client-side stuff.

**Comment by leerob** [comment]
Hey @peterbe 😄 Have been enjoying looking through this repo - out of curiosity, was there a limitation on Next.js that prevented y'all from adopting it and doing hand-rolled React SSR?

**Comment by peterbe** [comment]
> Hey @peterbe 😄 Have been enjoying looking through this repo - out of curiosity, was there a limitation on Next.js that prevented y'all from adopting it and doing hand-rolled React SSR?

Initially, it was lack of skills. In my defense, the early prototype of Yari was made when NextJS wasn't even known :)
At the time I was very comfortable around CRA and just wanted to get something up and running. 
By the time we realized what a mess CRA is when you want to do SSR and having to do your own Babel etc. so you can use it in Node, it was clear that we needed something like NextJS. From there, we just didn't get around to it. Like a recurring piece of tech debt we rolled along in front of us. 

We did attempt some NextJS at one point, led by my colleague, but in hindsight, I think that project attempted to do EVERYTHING the NextJS way including running it in Vercel. 
It would have been better to allow the regular Node code entirely worry itself with doing the Markdown and macro expansion stuff and dumping to the file system (or a database). Then, the getStaticProps (or getServerSideProps) could just read the content from disk, by taking the `req.path` and transposing it to the relevant `build/${path}.json` kinda deal. That way, we'd get NextJS to handle all SSR but become agnostic as to how the hell the HTML payload is prepared. 

I left the Yari (Mozilla) in late 2021 and I used NextJS on my personal and new work projects.
