### ISSUE TITLE
Removed feature compat table entry confusing

### ISSUE THREAD

**Issue by freaktechnik** [mdn/yari#1399]
With Firefox for Android a bunch of extension APIs are not yet supported that were previously supported. As such they have a removed version but no newer added version yet. The table ends up looking like this:
![image](https://user-images.githubusercontent.com/640949/95336226-b80c1d00-08b0-11eb-9207-882ead0c89fc.png)
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/onChanged#Browser_compatibility
If I look at that entry, I'd think it's trying to tell me that the feature isn't supported between version 48 and 79 for sure, no idea about 80, maybe it'll be supported there. But that's not at all what the compat data says:
```json
              "firefox_android": {
                "version_added": "48",
                "version_removed": "79"
              },
```
https://github.com/mdn/browser-compat-data/blob/master/webextensions/api/downloads.json#L1134-L1136

A better rendering - in my opinion - would show it as not supported starting with version 79 (either just 79 or maybe some indicator like 79 - *) and have a "previous support" entry for 48-79.

**Comment by freaktechnik** [comment]
To me the confusing thing is that it's red and has a range, if it were just green (/marked as supported) that'd work too, for me, however that potentially gives the wrong impression if you only quickly glance at the table.

**Comment by peterbe** [comment]
@ddbeck If you have some feelings on this, please share.

**Comment by freaktechnik** [comment]
I made a rough mockup of a representation that would make more sense to me. I realize that this is more complicated, since you can't just map the BCD entries 1:1 to a HTML entry.
![image](https://user-images.githubusercontent.com/640949/95460702-9163ea00-0975-11eb-8e24-fce75031df1d.png)

(it probably doesn't need the >=, but I added that because I previously had a range on the supported, too)

**Comment by peterbe** [comment]
It's such a "surprising" thing that an API disappeared that it might not really matter how you try to display it in a tiny cell. Whichever it is, an explanation is helpful. 

One idea is to do what caniuse.com does which is that hover or clicks on the cell shows a popover that contains a bit more flesh. My instinct is that that gives more room for verbose explanations. Your rough mockup and the existing "flaps" in the BCD table make it a bit hard to see that what you're reading now is specifically relevant to that initial cell you clicked on.

**Comment by kewisch** [comment]
@ddbeck Hey, wondering if there is anything we could do to move this forward? I'd love to see if we could improve the display here.

**Comment by Ryuno-Ki** [comment]
I mean, if you were to overhaul the table …
I wonder, whether there was such a case, that an API was removed - just to got reintroduced later in some other form.
(I can't recall such a case off-hand. But it would be possible, wouldn't it?).

Anyway, I'd go with a `No¹` in red with a cross. The `No` represents the current status, and the superset 1 allows for an explanation (similar to caniuse). That could then explained, that it was only available between this and that version (could be relevant for some ESR versions?).

**Comment by chrisdavidmills** [comment]
@ddbeck hi Daniel. I've bene discussing this with @kewisch , and I wondered if it would fix it to update the data to this kind of structure:

```
"firefox_android": [
  {
    "version_added": false
  },
  {
    "version_added": "48",
    "version_removed": "79"
  }
]
```

?

**Comment by ddbeck** [comment]
I'm opposed to duplicating support statements for feature removals. To do so would be a massive change and would almost certainly affect hundreds of features. It would also create a subtle and hard-to-explain distinction within BCD itself, between features that were removed (having two support statements) and features which went unimplemented (which would have one support statement), when the schema, as documented, requires only one. This would have a negative impact on contributors and other consumers of BCD.

I'd much rather expand BCD's API to produce better summaries of support statements. It'd be much better if, for example, the table had a YES/NO summary for every feature-browser pair and then the option to expand to see a history of that browser's support.

**Comment by chrisdavidmills** [comment]
@ddbeck thanks, that does make sense. We'll just have to leave that as a future enhancement then, I guess.

**Comment by peterbe** [comment]
> It'd be much better if, for example, the table had a YES/NO summary for every feature-browser pair and then the option to expand to see a history of that browser's support.

That sure is an interesting idea! A bit "out there" but definitely interesting. 

The code for the BCD table, in Yari, is not tiny but it's high quality and very predictable. Much much saner than the KS macro code in Kuma. 
So without fear of Kumascript (and only a little fear of TypeScript) we can really go above and beyond now.

**Comment by schalkneethling** [comment]
@ddbeck You have any more thoughts on this one? Has it perhaps been addressed? Should we keep this around?

**Comment by ddbeck** [comment]
I think Daryl's work is going to address this. I don't think there's any immediate work to be done, though it's not actually resolved yet.

**Comment by schalkneethling** [comment]
> I think Daryl's work is going to address this. I don't think there's any immediate work to be done, though it's not actually resolved yet.

I would rather close this instead of having issues linger around that we are bound to forge to go back to and close. Seeing that this _will_ be resolved as part of the redesign, I am going to close as that work is tracked elsewhere.
