### ISSUE TITLE
Add current release to BCD table

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1400]
A *lot* of times when looking at browser support on MDN I have to do a quick take and when looking at the version when support for a feature or property was added. Like sometimes I see 59 and I think, hmmmmm, that is long ago right? 🤔

I reckon it would be super useful to show the current release of the various browsers as the first line in the BCD table as can be seen below. I believe we already have this information?

![Screenshot 2020-10-08 at 10 18 28](https://user-images.githubusercontent.com/10350960/95433621-7af76780-0950-11eb-9a5d-5c792a3cfd74.png)

**Comment by mattiapontonio** [comment]
I like this idea. In general it is not very clear that the number in the green is the version in which the first column feature was added.

**Comment by mattiapontonio** [comment]
I did a table here
https://github.com/mdn/yari/issues/1761#issuecomment-729945716

_We could add colums to my table_...

**Comment by mattiapontonio** [comment]
FTR
https://github.com/brandon93s/html-table-to-json

**Comment by peterbe** [comment]
@ddbeck @Elchi3 I actually like this suggestion. I don't dare to think how hard it would be to implement, but if you know of something available within the BCD data, it might be significantly easier to implement. 
Also, what do you think about Schalks idea? 
Personally, it's often something I find myself wondering too. "Available since verson 89?? But how many stable relases ago was that?!"

**Comment by mattiapontonio** [comment]
Should We out these 3 tr in thead?

| Device  | Smartwatch |   |
| Name    | Opera      |   |
| Version | 1.0        |   |
|---------|------------|---|


https://www.w3.org/WAI/tutorials/tables/irregular/

**Comment by Ryuno-Ki** [comment]
Hm, actually a good point, Mattia is pointing up here.
What are the headings? I'd expect device (mobile, desktop) and browser combined for `scope="col"` (which might need an `aria-labelledby` to have been spoken out in conjunction) and the first column as `thead` for `scope="row"`.

I'd expect a screen reader to read out „Supported in Flex Layout. Desktop. Firefox. 52. Remark […]”.

**Comment by ddbeck** [comment]
I think adding more version numbers to the table would be a mistake. If we're going to go to the trouble of making big changes to the table, I'd much rather see us do something a bit more holistic. For example, I think it'd be much more fruitful  to have a top-line summary for each browser (e.g., "Unsupported", "In development", "Supported (new in the last X months)", "Supported (with non-standard name)") that makes the comparison _for_ the reader than it is to merely give them the numbers to work it out themselves.

**Comment by mattiapontonio** [comment]
> top-line summary
Could be the table footer.

But have you seen what the table looks like? have you seen that lines are different features? Do we all agree on how a table should work in terms of coordinates?

**Comment by schalkneethling** [comment]
> If we're going to go to the trouble of making big changes to the table, I'd much rather see us do something a bit more holistic.

I agree, there is a multitude of problems with the table and I doubt any real low hanging fruit. I would totally be for a rethink of how we present the data in general.

**Comment by mattiapontonio** [comment]
There are object [patterns](https://www.github.com/mdn/browser-compat-data/tree/master/schemas%2Fcompat-data-schema.md) in the readme. 
It might be useful to create classes or _Components_ that map these objects to a template.

Example:

```JavaScript
function Support(prefix = new String(), version_added = new String(), version_removed = new String()) {
 return `
<div>
<div>${prefix}</div>
<div>${version_added}</div>
<div>${version_removed}</div>
</div>
`

}
```

**Comment by schalkneethling** [comment]
@ddbeck Thoughts on this? Thanks

**Comment by ddbeck** [comment]
@schalkneethling My take in https://github.com/mdn/yari/issues/1400#issuecomment-779078811 still stands. I'd like to do a top-of-the-page panel for compat, standards track, experimental status, etc. I think that'll be a lot more fruitful before something like this; let's take that up in our content-engineering prioritization process. 👍

**Comment by caugner** [comment]
This was actually implemented in February 2023 by https://github.com/mdn/yari/pull/8041. 🎉
