### ISSUE TITLE
Exclude Kitchensink from indexing

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1403]
It's probably both useful and harmless to always build [the Kitchensink page](https://github.com/mdn/content/tree/main/files/en-us/mdn/kitchensink). But we should avoid it being indexed.

At least we should avoid it in the `sitemaps/en-us/sitemap.xml.gz` and a `<meta name="robots" cotnent="noindex">` thing. 

Should it be excluded from the search-indexes as well?

**Comment by escattone** [comment]
> Should it be excluded from the search-indexes as well?

Yes, I think so.
