### ISSUE TITLE
Tool to delete docs

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1417]
Very similar to https://github.com/mdn/yari/issues/1379, we also need a tool to delete documents. Like the tool to move documents, it would have to handle not only the deletion of single documents but entire document trees as well.

Should this tool also be able to add an optional redirect or redirects, so we don't just 404? I suppose that should be the task of our planned `yarn redirects add ...` command.

**Comment by escattone** [comment]
@fiji-flo I was looking through the issues and found this old one -- https://github.com/mdn/yari/issues/1051 -- which I thought had some information that you might find interesting.

**Comment by Ryuno-Ki** [comment]
Would that trigger a prompt for confirmation? (Especially in the case of deleting a whole tree, I'd suspect a list of files-to-be-deleted and ask for a confirmation. Optionally always-confirmed via CLI parameter).

**Comment by escattone** [comment]
Closed via #1510
