### ISSUE TITLE
{{ListSubpages}} on /en-us/docs/web

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1434]
This is probably more a matter of *content* than functionality. But I just don't want it to be forgotten. 

I think the reason it goes crazy in Yari is because of this bug: https://github.com/mdn/yari/issues/1354
And by "crazy" I mean the fact that the scrollbar goes for miles on https://main.content.dev.mdn.mozit.cloud/en-us/docs/web because it's so deep there.

**Comment by schalkneethling** [comment]
Looking at the page mentioned, it seems we are OK here now.
