### ISSUE TITLE
Reduce rounded corners for search bar

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#1436]
This was reported in https://github.com/mdn/yari/pull/1430#issuecomment-707784053

See the thread there for further discussion.

Perhaps related to #1155 and #950.

**Comment by schalkneethling** [comment]
Thanks for filing @Ryuno-Ki - I addressed it here 😸  - https://github.com/mdn/yari/pull/1430/commits/f9ed113f6bb74ecea11ac08b76528a235ae26c36
