### ISSUE TITLE
I don't like the breadcrumb above the document header. It's "just weird". I'm just so used to breadcrumbs being under the heading.

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1439]
I don't like the breadcrumb above the document header. It's "just weird". I'm just so used to breadcrumbs being under the heading. 
![IMG_3A7A38977C69-1](https://user-images.githubusercontent.com/26739/95868785-a1464a00-0d38-11eb-9283-fcc0915974e6.jpeg)

It's actually not really a breadcrumb, to be honest. It's just a link to the parent document. But it just doesn't make sense I don't think because the parent page isn't that important. And it's not entirely obvious that it's the parent. 
I understand why it's not showing all the other steps of a regular breadcrumb that you get on desktop, it's because of the lack of space. It's like cheating on desktop.
<img width="1419" alt="Screen Shot 2020-10-13 at 10 00 07 AM" src="https://user-images.githubusercontent.com/26739/95870795-ea979900-0d3a-11eb-88f3-511435a251d7.png">

I'm not sure what the solution is. Perhaps make it snug right under the (grey) header area.

_Originally posted by @peterbe in https://github.com/mdn/yari/pull/1430#issuecomment-707759483_

**Comment by peterbe** [comment]
I used to be that the breadcrumb was *under* the page title on desktop but *above* on mobile. 
Now, it's *above* on both. I'm still not a fan of that but I don't want to force any time-consuming change.
