### ISSUE TITLE
"Cannot read property 'replace' of undefined" in {{LandingPageListSubpages}}  MacroExecutionError

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1444]
Try http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/API#_flaws
It'll look something like this:
<img width="1041" alt="Screen Shot 2020-10-13 at 10 03 12 PM" src="https://user-images.githubusercontent.com/26739/95934949-139e4500-0da0-11eb-88c1-8a60617cd4dc.png">

**Comment by peterbe** [comment]
Hmm.. The reason it happens is because `aPage.summary` becomes `undefined` in `SubpagesWithSummaries.ejs`. If you `console.log` that `aPage` in the for loop you get:
```
5:30:13 PM server.1     |  {
5:30:13 PM server.1     |    url: '/en-US/docs/Mozilla/Add-ons/WebExtensions/API/alarms',
5:30:13 PM server.1     |    locale: 'en-US',
5:30:13 PM server.1     |    slug: 'Mozilla/Add-ons/WebExtensions/API/alarms',
5:30:13 PM server.1     |    title: 'alarms',
5:30:13 PM server.1     |    summary: undefined,
5:30:13 PM server.1     |    tags: [
5:30:13 PM server.1     |      'API',
5:30:13 PM server.1     |      'Extensions',
5:30:13 PM server.1     |      'Inteface',
5:30:13 PM server.1     |      'Needs Privileges',
5:30:13 PM server.1     |      'Reference',
5:30:13 PM server.1     |      'WebExtensions',
5:30:13 PM server.1     |      'alarms'
5:30:13 PM server.1     |    ],
5:30:13 PM server.1     |    translations: [],
5:30:13 PM server.1     |    subpages: [Getter]
5:30:13 PM server.1     |  }
```

**Comment by peterbe** [comment]
@escattone Ah! This is going to tricky and potentially something we need to elevate. 
If you look at https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API#JavaScript_API_listing
it builds up a listing there and it needs the document title and the document summary. 
The problem is: we don't have summaries anymore. It's always `undefined` in `getPage` (from `kumascript/src/info.js`).
We only have the summary after the page has been built. So I guess we're back to the old chicken-and-egg problem. 
Before, when we had this problem, we solved it by simply *not* relying (or using!) the summary at all. In this case, if you don't have the summary you simply can't build that KS macro. 

In fact, I think the simplest solution is brutal. Really brutal. You simply rewrite the macro to not use the summary anymore. Then it looks like this:
<img width="777" alt="Screen Shot 2020-10-15 at 5 44 56 PM" src="https://user-images.githubusercontent.com/26739/96189324-45351e80-0f0e-11eb-8a91-ec76d8d2d026.png">

Perhaps it's end-of-day tired but I can't think of a better solution at this point. 
Thing is, it's very populary macro. Grep the mdn/content and you'll see it in about 16 pages. http://localhost:3000/en-US/docs/Web/EXSLT/regexp ([in kuma](https://developer.mozilla.org/en-US/docs/Web/EXSLT/regexp)) being one for example. 

What do you think? Shall be go for the brutal solution of just listing titles instead?

Suppose we write a hack so that `page.summary` becomes a lazy getter that goes back into Yari to build the page and then it becomes available. It might work but that means we can't first render out the KS macros (infinite recursion) but attempts to cobble up a summary based on the raw (Kuma) HTML. Blargh.

**Comment by peterbe** [comment]
In hindsight, here's the ripgrep I find:
```
files/en-us/mdn/kuma/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/mdn/rfps/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/mdn/contribute/structures/macros/other/index.html: <li>{{TemplateLink("SubpagesWithSummaries")}} constructs a definition list of all the immediate children of the current page. There is no other formatting done. You can get a two-column list ready for use as a multi-column landing page using {{TemplateLink("LandingPageListSubpages")}}.</li>
files/en-us/mdn/contribute/structures/page_types/index.html:<p>The list of subpages can be generated automatically using the templates {{TemplateLink("SubpagesWithSummaries")}}, {{TemplateLink("SubpageMenuByCategories")}}, and {{TemplateLink("LandingPageListSubpages")}}. However, in more complex cases, the list may need to be created (and maintained!) by hand.</p>
files/en-us/mdn/structures/page_types/index.html:<p>The list of subpages can be generated automatically using the templates {{TemplateLink("SubpagesWithSummaries")}}, {{TemplateLink("SubpageMenuByCategories")}}, and {{TemplateLink("LandingPageListSubpages")}}. However, in more complex cases, the list may need to be created (and maintained!) by hand.</p>
files/en-us/mdn/structures/macros/other/index.html: <li>{{TemplateLink("SubpagesWithSummaries")}} constructs a definition list of all the immediate children of the current page. There is no other formatting done. You can get a two-column list ready for use as a multi-column landing page using {{TemplateLink("LandingPageListSubpages")}}.</li>
files/en-us/inbox/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/web/accessibility/aria/roles/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/web/api/installtrigger/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/web/exslt/exsl/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/web/exslt/str/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/web/exslt/set/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/web/exslt/math/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/web/exslt/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/web/exslt/regexp/index.html:<p>{{SubpagesWithSummaries}}</p>
files/en-us/web/webdriver/commands/index.html:<p>{{SubpagesWithSummaries}}</p>
```
About half of those pages are in `mdn` or other "meta" documents. Also, the page that started this issue was `Mozilla/Add-ons/WebExtensions/API` which isn't a super critical page to us.

**Comment by escattone** [comment]
@peterbe Good catch! I'd like to go with your simple, brutal solution, but let's get @chrisdavidmills' feedback before we move ahead with that. I'll talk to him first thing tomorrow morning, unless you speak with him first.

**Comment by chrisdavidmills** [comment]
@peterbe @escattone I think only showing the title/link without the summary would be troubling, especially on some pages where the summaries are really required for context. Could we use some kind of dumber solution where the subpages are cycled through, and the first paragraph of each is grabbed and used as the summary?

**Comment by Ryuno-Ki** [comment]
Hm, well, LaTeX has some areas, where you need to give the build process two passes to have updated information everywhere.
Would that be an option here?
Like in the first pass, generate the titles (show them) and the summaries.
In the second pass, include the title AND the summaries.

**Comment by peterbe** [comment]
> @peterbe @escattone I think only showing the title/link without the summary would be troubling, especially on some pages where the summaries are really required for context. Could we use some kind of dumber solution where the subpages are cycled through, and the first paragraph of each is grabbed and used as the summary?

Careful what you ask for :) 
We can build anything. I think we can attempt something where it forcibly attempts to extract the summary from the Kuma-HTML and strips HTML tags and KS macros. And if that regex fails, we fall back on an empty string.

**Comment by peterbe** [comment]
Ok. I have a hack ready to go. Here's what it looks like:
<img width="883" alt="Screen Shot 2020-10-16 at 8 27 26 AM" src="https://user-images.githubusercontent.com/26739/96258044-6edf5b80-0f89-11eb-92a2-9a0b57898038.png">
and
<img width="1247" alt="Screen Shot 2020-10-16 at 8 28 17 AM" src="https://user-images.githubusercontent.com/26739/96258198-a221ea80-0f89-11eb-84b9-cc87219023a4.png">

Obviously, it's not great because the KS macros are still present. But it's definitely a huge increase compared to the above mentioned *brutal* solution of not having anything at all.

**Comment by peterbe** [comment]
Alrite! With a bit of optimistic regex matching you can now get this:
<img width="1198" alt="Screen Shot 2020-10-16 at 8 41 03 AM" src="https://user-images.githubusercontent.com/26739/96259253-5708d700-0f8b-11eb-829e-d4e7a13d192a.png">

Looks near identical to the Kuma one https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API#JavaScript_API_listing

**Comment by chrisdavidmills** [comment]
Nice, looking good @peterbe !

**Comment by peterbe** [comment]
My hack might look promising on those pages but there are still a great number of places where it fails to find any summary. I made a complete build where I logged every page where a summary couldn't be found. Here's what I found:

http://localhost:3000/en-US/docs/Games/Index
http://localhost:3000/en-US/docs/Games/Introduction_to_HTML5_Game_Development_(summary)
http://localhost:3000/en-US/docs/Glossary/Denial_of_Service
http://localhost:3000/en-US/docs/Glossary/Immutable
http://localhost:3000/en-US/docs/Glossary/Index
http://localhost:3000/en-US/docs/Glossary/Prototype-based_programming
http://localhost:3000/en-US/docs/Glossary/Second-level_Domain
http://localhost:3000/en-US/docs/Learn/Index
http://localhost:3000/en-US/docs/MDN/Contribute/Howto/Create_an_interactive_exercise_to_help_learning_the_web/distant_example
http://localhost:3000/en-US/docs/MDN/Index
http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/Index
http://localhost:3000/en-US/docs/Tools/Debugger/Keyboard_shortcuts
http://localhost:3000/en-US/docs/Tools/Index
http://localhost:3000/en-US/docs/Tools/Page_Inspector/Keyboard_shortcuts
http://localhost:3000/en-US/docs/Tools/Web_Console/Invoke_getters_from_autocomplete
http://localhost:3000/en-US/docs/Tools/Web_Console/Keyboard_shortcuts
http://localhost:3000/en-US/docs/Web/API/AudioParamDescriptor
http://localhost:3000/en-US/docs/Web/API/Document_object_model/Using_the_W3C_DOM_Level_1_Core/Example
http://localhost:3000/en-US/docs/Web/API/EventTarget/EventTarget.attachEvent()
http://localhost:3000/en-US/docs/Web/API/FetchEvent/PreloadRequest
http://localhost:3000/en-US/docs/Web/API/HTMLTrackElement/cuechange_event
http://localhost:3000/en-US/docs/Web/API/Index
http://localhost:3000/en-US/docs/Web/API/Window/stop
http://localhost:3000/en-US/docs/Web/API/XSLTProcessor/Resources
http://localhost:3000/en-US/docs/Web/Events/Index
http://localhost:3000/en-US/docs/Web/Guide/Index
http://localhost:3000/en-US/docs/Web/HTTP/Headers/Index
http://localhost:3000/en-US/docs/Web/MathML/Index
http://localhost:3000/en-US/docs/Web/SVG/Index
http://localhost:3000/en-US/docs/Web/SVG/mimeTypes.rdf_corruption
http://localhost:3000/en-US/docs/Web/SVG/Replaced_Element
http://localhost:3000/en-US/docs/Web/SVG/Sizing
http://localhost:3000/en-US/docs/Web/SVG/Specification_Deviations
http://localhost:3000/en-US/docs/Web/XML/Index
http://localhost:3000/en-US/docs/Web/XPath/Index
http://localhost:3000/en-US/docs/Web/XSLT/Index
http://localhost:3000/en-US/docs/Web/XSLT/Transforming_XML_with_XSLT/Resources
http://localhost:3000/en-US/docs/Web/XSLT/XSLT_JS_interface_in_Gecko
http://localhost:3000/en-US/docs/Web/XSLT/XSLT_JS_interface_in_Gecko/Resources
http://localhost:3000/en-US/docs/WebAssembly/Index

I'm pretty sure these are always just the `Index.ejs` macro. It's used in these pages:

```
files/en-us/games/index/index.html:<p>{{Index("/en-US/docs/Games")}}</p>
files/en-us/tools/index/index.html:<div>{{ToolsSidebar}}</div><p>{{Index("/en-US/docs/Tools")}}</p>
files/en-us/webassembly/index/index.html:<p>{{Index("/en-US/docs/WebAssembly")}}</p>
files/en-us/glossary/index/index.html:<p>{{Index("/en-US/docs/Glossary")}}</p>
files/en-us/web/accessibility/index/index.html:<p>{{Index("/en-US/docs/Web/Accessibility")}}</p>
files/en-us/web/events/index/index.html:<p>{{Index("/en-US/docs/Web/Events")}}</p>
files/en-us/web/xslt/index/index.html:<p>{{Index("/en-US/docs/Web/XSLT")}}</p>
files/en-us/web/api/index/index.html:<p>{{Index("/en-US/docs/Web/API")}}</p>
files/en-us/web/http/index/index.html:<p>{{Index("/en-US/docs/Web/HTTP")}}</p>
files/en-us/web/html/index/index.html:<p>{{Index("/en-US/docs/Web/HTML")}} <span class="seoSummary">A comprehensive index list of all the available HTML documentation.</span></p>
files/en-us/web/http/headers/index/index.html:<p>{{Index("/en-US/docs/Web/HTTP/Headers")}}</p>
files/en-us/web/xml/index/index.html:<p>{{Index("/en-US/docs/Web/XML")}}</p>
files/en-us/web/xpath/index/index.html:<p>{{Index("/en-US/docs/Web/XPath")}}</p>
files/en-us/web/mathml/index/index.html:<p>{{Index("/en-US/docs/Web/MathML")}}</p>
files/en-us/web/svg/index/index.html:<p>{{Index("/en-US/docs/Web/SVG")}}</p>
files/en-us/web/guide/index/index.html:<p>{{Index("/en-US/docs/Web/Guide")}}</p>
files/en-us/mozilla/add-ons/webextensions/index/index.html:<div style="overflow: auto;">{{Index("/en-US/docs/Mozilla/Add-ons/WebExtensions")}}</div>
files/en-us/learn/index/index.html:<p>{{Index("/en-US/docs/Learn")}}</p>
files/en-us/mdn/index/index.html:<p>{{Index("/en-US/docs/MDN")}}</p>
```
But, for the record, pages like http://localhost:3000/en-US/docs/Web/HTTP is working just fine.

**Comment by peterbe** [comment]
Actually, this is what I see a lot on the pages where no summary could be extracted:
<img width="944" alt="Screen Shot 2020-10-16 at 9 31 19 AM" src="https://user-images.githubusercontent.com/26739/96264682-70615180-0f92-11eb-88c7-53f09d05b849.png">
I.e. the Index page is just like this:
```
<div>{{WebAssemblySidebar}}</div>

<p>{{Index("/en-US/docs/WebAssembly")}}</p>
```

And when the `Index.ejs` macro lists **itself** it fails to find a summary. 
In that case I would strongly argue that it's a mistake of that macro to include itself. If we can fix that, the number of times a summary can't be extracted would go down significantly. 

Therefore, I think my hack is good enough. It's time to move on.

**Comment by peterbe** [comment]
Migrated that last discussion to: https://github.com/mdn/yari/issues/1468
