### ISSUE TITLE
Submit PR via GitHub

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1465]
>  I need some grant or something?
> (I'm relatevly new to GitHub flows)

None. You just need to check out Yari and set it up to run locally and then you can work from there.

_Originally posted by @peterbe in https://github.com/mdn/yari/issue_comments/709612207_

Imagine if I want to submit this function:
https://github.com/mattiapontonio/tooltip/blob/main/tooltip.js

There is a way to do not install the project locally and use GitHub to go to some file, edit, paste the function, and then see the deploy in some enviroment on-the-fly?
Just asking.
In my static GitHub pages I work sometimes like that using just front-end technologies.

_Actually I'm from my father PC so I have Just Chrome, funny thing._

**Comment by schalkneethling** [comment]
At the moment, updating documentation is still done via wiki.developer.mozilla.org

In the future, content updates will happen in the `mdn/content` repo and you can see the contribution guidelines there: https://github.com/mdn/content/blob/main/CONTRIBUTING.md

To which piece of Yari or the MDN content would you want to add `tooltip.js`?

**Comment by peterbe** [comment]
First of all, "Submit PR via GitHub" is very much something you can do. GitHub has this built-in. 
You can edit stuff in a git repo entirely by pressing the Edit pen icon. And you can even do things like creating new files. And then, using the GitHub UI you can automate the creation of a fork and branch and create a PR. 

However, it's genuinely not recommended to do this for code changes. It might work for content changes as Schalk pointed out above. 

The topic of automatically building a version of Yari based on a branch is a huge topic and best saved for other ongoing discussions we already have.
