### ISSUE TITLE
Search icon size is not optimized on Chrome

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1466]
**Environment**:  https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web

**Browsers:**
Chrome 

**STR:** 
1. Reach https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web or any of the pages 
2. View search bar.

**Expected Result:**
Search icon fits the search bar, the way it does on Firefox and Safari browsers. 
![image](https://user-images.githubusercontent.com/53306802/96261659-66a71080-0fc9-11eb-84fa-9e9f74aaeb43.png)

**Actual result:**
![image](https://user-images.githubusercontent.com/53306802/96261762-876f6600-0fc9-11eb-84f0-c9c3200f1945.png)

**Comment by schalkneethling** [comment]
Thank you for reporting @mirunacurtean. This is fixed in the `mdn-fiori` branch where a *lot* of front-end changes are being made to define and implement the MDN design system. Closing this one as resolved.

**Comment by peterbe** [comment]
@schalkneethling Can you kick of a buld of `mdn-fiori` (with Deployment prefix `mdn-fior`) and give that URL to @mirunacurtean to check with in cases of style things like that?
