### ISSUE TITLE
lambda@edge origin-request-handler unsafe for CloudFront origin groups

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1474]
Since AWS CloudFront origin groups introduce multiple origins (a primary and a secondary) for the same behavior, we have to ensure we only make adjustments for custom S3 origins. For example, we use an origin group for requests for static files (CSS, JS, icons, images, etc.), where the primary is our custom S3 origin and the secondary is the Kuma Django service, because static files for documents will be served from S3, but any static files unique to the MDN home page or account profiles must be served from Kuma (Django WhiteNoise). Since our Lambda@Edge origin-request handler will also be called prior to any request for the secondary origin (on 404 fail-overs), we have to make sure we don't make our S3-specific adjustments when running prior to a request for the Kuma origin.

**Comment by peterbe** [comment]
> we have to make sure we don't make our S3-specific adjustments when running prior to a request for the Kuma origin.

What are those adjustments? I thought the old thing we did was rewrite the `request.uri` when it might end with a `/` or something like that. But what does it have to do with static files?
