### ISSUE TITLE
requests for /distimages/* files 404 on document page loads

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1476]
We're 404'ing on requests for /distimages/* files:

<img width="1408" alt="image" src="https://user-images.githubusercontent.com/3743693/96310941-36f20b80-0fbd-11eb-9421-d6857eff1a46.png">

Should we be copying these files from `ssr/dist/distimages` to the build directory on builds?

**Comment by peterbe** [comment]
That might just go away in `mdn-fiori`. It's a hangover from the `kumastyles` project I suspect.

**Comment by peterbe** [comment]
Yeah, it goes away as you can see here: https://mdn-fiori.content.dev.mdn.mozit.cloud/en-US/docs/MDN/Kitchensink
I say we just close because we're probably at a point where the `mdn-fiori` branch is already better than what we currently have in `master` (aka `kumastyles`).
