### ISSUE TITLE
Fix our Lighthouse score

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1484]
Basically...
<img width="1871" alt="Screen Shot 2020-10-16 at 5 09 30 PM" src="https://user-images.githubusercontent.com/26739/96487400-10c1ab00-120b-11eb-992c-aa061e123c25.png">

If you look carefully, it's the render-blocking that's causing it. Let's fix that.

**Comment by peterbe** [comment]
One thing I've noticed, from doing lots of testing is that the difference is small. It's probably good practice to not inject `.css` style sheets into a DOM because if you do this during the rendering, it forces the browser to block the rest of the rendering. 

It might be an option to delay that loading until *after* the XHR to `whoami` has finished and concluded that "Yes, it's time to inject a banner".

**Comment by Ryuno-Ki** [comment]
It depends.
There's this thing called „critical CSS”, which should be injected into a `<style>`. That one would take care of the absolute minimum (I think, layout, colours) to render the basic design.

The rest can be either loaded via JavaScript. Or as `<link href="stylesheet" />` inside the body (looking for the article now, where I found that trick).

**Comment by Ryuno-Ki** [comment]
https://github.com/whatwg/html/commit/179983e9eb99efe417349a40ebb664bd11668ddd for using `<link />` in `<body>` and stay WHATWG-HTML5-conform.

via https://stackoverflow.com/a/35801653

**Comment by Ryuno-Ki** [comment]
Loading CSS asynchronously: https://github.com/filamentgroup/loadCSS

**Comment by Ryuno-Ki** [comment]
Ah. Of course! Jake to the rescue: https://jakearchibald.com/2016/link-in-body/#a-simpler-better-way

**Comment by peterbe** [comment]
We still have some ways to go until we're blown away. But it's a start. 
<img width="1890" alt="Screen Shot 2020-10-28 at 9 09 03 AM" src="https://user-images.githubusercontent.com/26739/97440055-54986c80-18fd-11eb-885e-8b0ec8b3cc64.png">

**Comment by peterbe** [comment]
However, it's not all great. Look at this comparison for example:
<img width="1882" alt="Screen Shot 2020-10-28 at 9 14 53 AM" src="https://user-images.githubusercontent.com/26739/97440691-2b2c1080-18fe-11eb-901e-d6f4ba6d9be9.png">

Yari is actually performing worse that Kuma on this page :(

But for that page, https://github.com/mdn/yari/pull/1416#issuecomment-710115708 is going to turn 1.2MB document to 376KB. So there's still hope!

**Comment by peterbe** [comment]
Clearly, we still have some more things we can do but for now, this issue is a bit too vague to deal with. So, let's close it and move on with more individual specific issues.
