### ISSUE TITLE
Inject image width/height to avoid cumulative layout shift

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1498]
CLS (cumulative layout shift) is when what you're looking at sudden moves down right in front of your eyes as stuff like images finally come in, somewhere above. 

Example: on http://localhost:5000/en-us/docs/Web/CSS/CSS_Box_Alignment
![Screen-Recording-2020-10-20-at-9 56 23-AM](https://user-images.githubusercontent.com/26739/96597160-808f6e80-12bb-11eb-8a8d-e2e8c8cee931.gif)

Since we control the `<img src>` tags in Yari we can use things like [`image-size`](https://github.com/image-size/image-size) which is pure Node JavaScript and doesn't read in the whole file so it's fast. 
Now we can automatically convert the:

```html
<img src="screenshot.png" alt="Bla">
```
...into...
```html
<img src="/en-US/docs/Current/Doc/screenshot.png" alt="Bla" width="430" height="260">
```

Now you get this result:
![Screen-Recording-2020-10-20-at-10 01 13-AM](https://user-images.githubusercontent.com/26739/96597663-15926780-12bc-11eb-9ef1-af59d6e59aad.gif)

**Comment by peterbe** [comment]
Also worth a read: https://web.dev/optimize-cls/#images-without-dimensions

**Comment by Ryuno-Ki** [comment]
As far as I know, Yari is generating those images at build time (not in response of a request). Would client hints (HTTP Headers, a.k.a. Accept-CH) be helpful?

@peterbe's link is interesting, too. CSS aspect-ratio and srcset can actually help improve the situation further.

**Comment by peterbe** [comment]
Hmm... See https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Inspect_and_select_colors
What someone's done there is that they have included images that are larger than their intended display. 

I have some code that removes any `width: XXXpx` and `height: YYYpx` from any `img` 's `style` attribute. And this is what happens:
<img width="1162" alt="Screen Shot 2020-12-21 at 4 14 22 PM" src="https://user-images.githubusercontent.com/26739/102822735-9991ca00-43a7-11eb-9dc4-e8c4963a2b08.png">

Here's the original:
<img width="1129" alt="Screen Shot 2020-12-21 at 4 15 38 PM" src="https://user-images.githubusercontent.com/26739/102822826-c7770e80-43a7-11eb-8c54-9e587f53ad2a.png">

I would argue, that it's wrong in the first place to upload an image that isn't the intended size. If you want to display the image with a max width of 200 pixels, what you should do is resize the image before you include it. Otherwise, you'll make the binary image larger than it needs to be. 

As a matter of fact, https://media.prod.mdn.mozit.cloud/attachments/2019/09/24/16888/637c48f06dc75a7acfb08d7dabb6e96b/color-picker-good-contrast.png is 120KB but when I download it and resize it to 200px using macOS Preview, it becomes 37KB.

**Comment by hamishwillee** [comment]
I tend to agree with @peterbe in https://github.com/mdn/yari/issues/1498#issuecomment-749200988 - generally you should try upload an image to correct size, and this should be the minimum size that conveys the relevant information. If only because big files are heavy for recipients and unlike server-based wiki systems, static sites can't dynamically resize images on sending (not to mention when we get the source locally).

Devils advocate:
- you can't regrow an image you've shrunk. In another site I recently added the feature to allow images to  expand when clicked. This is really useful in some cases, but diligent pruning of image sizes over the years means that much of the benefit was lost.
- When using images within a table or other layout structure you don't always know the ideal layout size when you're starting. I find it useful to be able to set widths, but I almost never set heights.

**Comment by mattiapontonio** [comment]
Yes.
- A designer should creates **3** _sources_ _cropped_ and _optimized for the web_ for each media using Photoshop
- A designer should know where to push this files and how names it using the terminal
- A designer should add the `src` to the HTML in the right file in the repository via PR and see the result in the page, testing the resize of the window and see that his **3** jobs are correctly shown and the effort of _centering the kitten_ in the different canvas served.
- ...

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/source

Repeat this effort for **x** of **y** images in the repository.

**Comment by hamishwillee** [comment]
My two bits; that is too onerous for authors. The markdown format doesn't even allow you to support image size. So normally you encourage authors to generate one image that is of the minimum practical size - e.g. crop redundant whitespace, shrink to 1000pixels width (ish), convert to jpg.

**Comment by mattiapontonio** [comment]
Test

<img alt="Example showing a toolbar button (browser action)." src="https://mdn.mozillademos.org/files/15751/browser-action.png" style="height: 50px; width: 50px;">

**Comment by Ryuno-Ki** [comment]
> The markdown format doesn't even allow you to support image size.

However, some parsers allow for attributes: https://www.npmjs.com/package/markdown-it-attrs could be used with a srcset.

**Comment by mattiapontonio** [comment]
But I didn't understand if it's the parser that just strips them like we would like to or if GitHub has CSS that works. So to date what I understand if we validate the HTML (in this case the CSS properties of the inline style) and the CSS says nothing or says what is needed for example for the maximum width then problem solved. I don't think there is a need to extend markdown also because there is currently no markdown in this project.

**Comment by mattiapontonio** [comment]
FTR
https://github.com/search?q=PerformanceObserver+repo%3Amdn%2Fyari&type=code

**Comment by mattiapontonio** [comment]
> > The markdown format doesn't even allow you to support image size.
> 
> However, some parsers allow for attributes: https://www.npmjs.com/package/markdown-it-attrs could be used with a srcset.

You might as well just start providing HTML samples on content to see what happens, you don't need to act right away on creating Macro / Web Components or markdown parser plugins.

Given other issues, this CLS could be a content problem.

Monitoring separately.

**Comment by mattiapontonio** [comment]
Can We discuss this and see what happens with the CLS?

https://github.com/mdn/content/pull/734

**Comment by peterbe** [comment]
> I tend to agree with @peterbe in [#1498 (comment)](https://github.com/mdn/yari/issues/1498#issuecomment-749200988) - generally you should try upload an image to correct size, and this should be the minimum size that conveys the relevant information. If only because big files are heavy for recipients and unlike server-based wiki systems, static sites can't dynamically resize images on sending (not to mention when we get the source locally).
> 
> Devils advocate:
> 
>     * you can't regrow an image you've shrunk. In another site I recently added the feature to allow images to  expand when clicked. This is really useful in some cases, but diligent pruning of image sizes over the years means that much of the benefit was lost.
> 
>     * When using images within a table or other layout structure you don't always know the ideal layout size when you're starting. I find it useful to be able to set widths, but I almost never set heights.

Responding to your "devil's advocating"...
If we allow people to upload a 2000x2000 PNG but you explicitly set the width like `<img src="pic.png" width="200">` then it's likely that people end up downloading a LOT more data to be able to see a smaller image and it's not any crisper. Resized down to 200px it's very possible that no human eye can tell it apart from one that natively 200px wide. But the amount of data transferred might be 1MB vs 50KB which hurts every single reader indefinitely. 
And implementing complicated override'able rules and exceptions might lead to complexity that is undesirable. 

(I feel like you knew ALL of that perfectly well but I think it's fair to log the complete argument here)

**Comment by mattiapontonio** [comment]
I'm increasingly thinking that this should be handled by editors but kindly asked ...
