### ISSUE TITLE
[Mobile Search] Display issues and lack of 'close search' button

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1517]
**Environment:** https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web
**Browsers:** Firefox and Chrome
**Device:** Android 9.0.0

**Steps to reproduce:** 
1. Tap the search bar and input text. 
2. Try to close search. 
3. Erase text from search bar.
4. Switch to landscape mode.

**Actual results:**
The search results overlap the search text. 
The search bar has no close (X) button so search cannot be close unless using the browser Back button. 
After the text is erased from the search bar a line is displayed across the search bar. 
When switching to landscape mode the search icon is oversized. 
![mobile search issues](https://user-images.githubusercontent.com/53306802/96893207-234e1580-1493-11eb-8475-6cc8dc12645e.gif)

![landscape search icon](https://user-images.githubusercontent.com/53306802/96893395-5395b400-1493-11eb-8b83-ace5ffcca4f9.gif)

**Expected results:** 
The search text is visible and no overlap with other page elements occurs. 
A search close button or something with similar functionality is added. 
Display issues are fixed (the line that goes across the search bar after the keyword is erased) 
The search iscon size is the same in portrait and landscape mode.

**Comment by peterbe** [comment]
Potentially relevant: https://github.com/mdn/yari/issues/1433

**Comment by schalkneethling** [comment]
This one is no longer relevant as our implementation has changed and we no longer slide down the search input over the header. Thanks for filing @mirunacurtean
