### ISSUE TITLE
Generate error pages, e.g. 404

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1531]
In CloudFront you can specify a page for custom errors. E.g. 
<img width="847" alt="Screen Shot 2020-10-26 at 3 34 17 PM" src="https://user-images.githubusercontent.com/26739/97219694-b8595300-17a0-11eb-9d55-6ab7621cb937.png">

Now, we just need to make sure these exist on disk (generated by Yari, uploaded by deployer).

**Comment by peterbe** [comment]
Let's build something that works for all/any error but we'll start with 404 first.

**Comment by Ryuno-Ki** [comment]
From an UX point of view, it might make sense to include a search on those pages.
Helps the user not feeling lost altogether.

**Comment by peterbe** [comment]
Let's call it according to this naming scheme: `/_errorpages/404.html`

**Comment by peterbe** [comment]
> From an UX point of view, it might make sense to include a search on those pages.
> Helps the user not feeling lost altogether.

Search will always be available as part of the header. 

However, what we could potentially do is, on the client-side, trigger a fetch of ALL the possible correct URLs and compare each one to the current one. You could include suggestions based on a edit-distance of the second degree.
