### ISSUE TITLE
Unbreak the home page post-fiori

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1538]
Not really an important page but we just mustn't forget to fix it. 
<img width="1505" alt="Screen Shot 2020-10-27 at 10 33 12 AM" src="https://user-images.githubusercontent.com/26739/97316222-e2158700-183f-11eb-823f-d91ac3f1fe3f.png">

**Comment by Ryuno-Ki** [comment]
Since it's not assigned yet: where would changes be needed to fix it?

**Comment by peterbe** [comment]
@schalkneethling It's not just the home page. There's now (soon) one more page that is *not* a reference page. (By the way, can rename that to "document-page" instead of "reference-page"?)

There's going to exist:

```
<Layout pageType="reference-page"></Layout>

and 

<Layout pageType="error-page"></Layout>

and 

<Layout pageType="home-page"></Layout>
```

It would be nice if they all worked :)

Here's what happens when it's `<Layout pageType="error-page"></Layout>`:
<img width="1616" alt="Screen Shot 2020-11-04 at 5 09 47 PM" src="https://user-images.githubusercontent.com/26739/98173384-06690780-1ec1-11eb-872c-f20a52d3a44e.png">

To be honest, I don't understand why they can't all be of the same page type. Aren't they all pages that should have a header and footer and some margins?
Either way, my PR to render error pages is coming within days so you'll have to use your imagination. But beware that my PR makes pretty big changes to the app.tsx file so perhaps we can sync up on Slack.
