### ISSUE TITLE
Unbreak the Flaws dashboard

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1539]
The [Flaws dashboard](http://localhost:3000/en-US/_flaws) doesn't have to be pretty or even great. But it needs to be somewhat functional because it's the only tool we have to discover patterns of document flaws. 
Initially, I think the primary users will be editors and the core Yari dev team. 

It just needs to not look like this: :)
<img width="1261" alt="Screen Shot 2020-10-27 at 10 43 19 AM" src="https://user-images.githubusercontent.com/26739/97317490-3cfbae00-1841-11eb-8025-2ccf3520fadb.png">

**Comment by peterbe** [comment]
@schalkneethling (CC @escattone ) I don't want to prioritize this issue. It'd be nice if it wasn't so completely busted. Perhaps we can spend 1-3 hours on it just to make it a bit less horrible. But still retrain ourselves to not over-engineer the prettiness. I was hoping you had some quick tricks up your sleeve Schalk. 
Also, I think there's a `flaws/index.scss` file where we can clownshoes in whatever it takes. Anything here shouldn't, in principle, leak bloat onto the actual pages we build for documents.

**Comment by escattone** [comment]
@peterbe @schalkneethling I think this is worth spending a bit of time on before the official Yari launch, but perhaps as a lowest priority, since it can be pushed to post launch if we're pressed for time.
