### ISSUE TITLE
Unbreak the Toolbar

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1541]
The toolbar, as of the Fiori merge is now stuck rather at the bottom of the document. It also looks like it could do some work to tidy up the buttons and margins and stuff. 

<img width="1072" alt="Screen Shot 2020-10-27 at 12 16 26 PM" src="https://user-images.githubusercontent.com/26739/97330208-5525fa00-184e-11eb-900a-942eb4119bb2.png">

**Comment by peterbe** [comment]
Note, the toolbar is no longer sitting at the bottom. Great! But it's got an ugly red border around it which makes it look like there's an error. 
The "buttons" are weird looking. Especially odd that some are links and some are buttons.

**Comment by peterbe** [comment]
Here's another thing to consider too. When the Document Spy notices that a document was updated, it starts to spit out extra information and suddenly the whole right-hand side takes up for 4 lines. That makes the whole toolbar extra high and filled with quite annoying whitespace. 
<img width="1501" alt="Screen Shot 2020-11-17 at 6 57 53 AM" src="https://user-images.githubusercontent.com/26739/99387707-72287880-28a2-11eb-99ea-a285304c27d2.png">

**Comment by peterbe** [comment]
Here's what it looks like if you get an error trying to open a document in your editor:
<img width="1501" alt="Screen Shot 2020-12-01 at 4 27 18 PM" src="https://user-images.githubusercontent.com/26739/100798844-2de4be80-33f2-11eb-8fed-011411a16f51.png">

You can simulate that by starting `yarn dev` and opening up a page like this. Then kill `yarn dev` and go back to the browser and click that "Edit in your editor" button.

**Comment by schalkneethling** [comment]
I am closing this one as the toolbar is no longer broken but, I have created the following issue to discuss and propose some ideas on how we can improve it even more:

https://github.com/mdn/yari/issues/2440
