### ISSUE TITLE
BCD cells change height when expanding

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1544]
I'm sure this has been filed before either in mdn/kumascript or something but I think it would take longer to find it than to just file a new one and deal with it. 

Before pressing the second-from-the-left expand:
<img width="1055" alt="Screen Shot 2020-10-27 at 1 23 02 PM" src="https://user-images.githubusercontent.com/26739/97338375-bbfbe100-1857-11eb-892b-e8f957d0a57c.png">

Here's what it looks like when expanded
<img width="1046" alt="Screen Shot 2020-10-27 at 1 25 02 PM" src="https://user-images.githubusercontent.com/26739/97338531-ddf56380-1857-11eb-8e38-c5d454180333.png">

Also, I suspect there's something foul at play. If you look carefully you notice that in the cell to the *left* of the one that says `3.1` the thicker right-border seems to have moved over. 
<img width="424" alt="Screen Shot 2020-10-27 at 1 25 02 PM" src="https://user-images.githubusercontent.com/26739/97338731-17c66a00-1858-11eb-947a-192acf538b30.png">

**Comment by tannerdolby** [comment]
I double checked a few BC tables to see if the problem still exists and it seems to have been fixed. The thicker border persists after expanding the dropdown and there aren't any border mismatches. I reckon this is ready to be closed @peterbe !
