### ISSUE TITLE
Page element styles are changed when returning to it using breadcrumb link

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1558]
**Environment:** https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web

**Browsers:** 
Firefox Release
Chrome
Safari

**Devices:** 
Windows pro 10
macOS 10.14 

**Steps to reproduce:**
1. Go to https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web and note the page format and element styles. 
2. Select the Web Developer Reference link. 
3. Select the HTML elements  link. 
4. Return to Web technology for developers page by selecting the breadcrumb link. 

**Expected result:** 
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web  page is loaded successfully and the content format and page element styles are the same as when first reaching the page. 

**Actual result:** 
The border between the 'Documentation for Web developers' and 'Web technology references' section is missing and the content displayed linearly instead of side by side, the font size is increased, the search bar style is changed. 

![The page content format is changed when returing to it using breadcrumb links](https://user-images.githubusercontent.com/53306802/97474935-4f670c00-1955-11eb-91f8-eaae40994fb0.gif)

**Tested using links:** 
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/Reference/API

**Comment by peterbe** [comment]
I'm really curious about how that could have happened. @schalkneethling I didn't even know we can render pages without a sidebar at all. 

By the way, here's what I see when I try to reproduce:
![Screen-Recording-2020-10-28-at-4 56 41-PM](https://user-images.githubusercontent.com/26739/97496077-d2309c80-193e-11eb-869f-69e75494d353.gif)

**Comment by peterbe** [comment]
Apart from the annoying flashing, it looks like where I ended up (after clicking in the breadcrumb) is identical to the page I started on.

**Comment by mirunacurtean** [comment]
As was established when closing #1560 this is the intended look for the docs/Web page so I can close this issue and log something else for the flash behavior and a couple other small things I noticed related to breadcrumbs. @peterbe

**Comment by peterbe** [comment]
The "flash behavior" isn't a bug. It's just something we don't have an improved feature for now. But i'll make sure @schalkneethling has a better issue filed formally for it. 
So, can we close this now?

**Comment by mirunacurtean** [comment]
Yes, done.
