### ISSUE TITLE
Some pages display a different format/ style than expected

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1560]
**Affected pages examples:**
Just on https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/Reference there are:
[starting to learn our learning area](https://main.content.dev.mdn.mozit.cloud/en-US/docs/Learn/Getting_started_with_the_web) link 
 [Learn Web Development](https://main.content.dev.mdn.mozit.cloud/en-US/docs/Learn) Link
[HTML elements](https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element) page
[Introduction to HTML](https://main.content.dev.mdn.mozit.cloud/en-US/docs/Learn/HTML) page, Learn HTML page, HTML5 page, Element reference , Reference, CSS, Introduction to CSS, Learn CSS, Reference, JavaScript, Learn JavaScript, Developer guide and and the corresponding Reference links. 

**More examples:**
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/Reference/API
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Learn/Getting_started_with_the_web
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/CSS
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML
and many more …

**Actual results:**
Font size is increased in comparison with parent page.
Search bar is rectangular.
Main menu drop down menu arrows are not set to sideways and to the left of the header.
Section/ topic borders are missing. 
![image](https://user-images.githubusercontent.com/53306802/97492062-b4c5f780-196b-11eb-905e-0d8743f8b1b2.png)

**Expected result:** 
All pages should respect the default format/ styling set on https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web, as seen when first loading the page. 
![image](https://user-images.githubusercontent.com/53306802/97491688-26517600-196b-11eb-9917-1fded74c5917.png)

NOTE: This might be a case similar to https://github.com/mdn/yari/issues/1558

**Comment by peterbe** [comment]
Do you understand this one @schalkneethling ?

**Comment by mirunacurtean** [comment]
@peterbe @schalkneethling  what was happening could be better seen in this gif, although if this is due to testing on an older version, I imagine it would not be reproducible by you, same as #1558. 
![docs style difference](https://user-images.githubusercontent.com/53306802/97541336-ab6d7700-19cd-11eb-8372-ab1f0021677a.gif)

**Comment by mirunacurtean** [comment]
Closing this as this is the expected redesign result for all the pages and it has been applied uniformly after the yesterday's updates.
