### ISSUE TITLE
General Knowledge section header is cut off

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1571]
Steps to reproduce: 
1. Go to https://main.content.dev.mdn.mozit.cloud/en-US/docs/Glossary/World_Wide_Web
2. Scroll to General Knowledge section header. 

**Actual result:** 
Header text is cut off. 
![image](https://user-images.githubusercontent.com/53306802/97610572-bea83300-1a1d-11eb-8670-c1130ca1f2f1.png)

**Expected result:** 
Header text is made to fit, same as "Learn about it" header.

**Comment by peterbe** [comment]
What a curious thing! I see about 35 of these `<h3>` tags all over the `en-US` content:

<img width="1109" alt="Screen Shot 2020-10-30 at 4 17 09 PM" src="https://user-images.githubusercontent.com/26739/97753018-76dfe500-1acb-11eb-8fb4-2c761d54aa4e.png">

The simplest solution is to manually open each and every one of these 35 documents and scrub away the `style="line-height: 24px;"`.
It might make sense to have that there when the content is in the Wiki. 
We can just simple remember to do this a one-off chore with some `sed` and `grep` magic once we're over the migration.

**Comment by peterbe** [comment]
@schalkneethling Can you confirm that if you edit the `files/en-us/glossary/world_wide_web/index.html` and reload it looks good in Fiori?

**Comment by schalkneethling** [comment]
> @schalkneethling Can you confirm that if you edit the `files/en-us/glossary/world_wide_web/index.html` and reload it looks good in Fiori?

Will take a look. So, this is not a `macro` thing, it was added via the `WYSIWYG`?

**Comment by schalkneethling** [comment]
> glossary/world_wide_web/index.html

Confirmed. Thanks for filing @mirunacurtean

**Comment by peterbe** [comment]
@escattone @schalkneethling This issue is a bit confusing in that it's *both* post-launch (label) and Yari1 UI (milestone).

**Comment by schalkneethling** [comment]
@mirunacurtean Looks like this is resolved? https://developer.mozilla.org/en-US/docs/Glossary/World_Wide_Web

**Comment by mirunacurtean** [comment]
Yes, this is fixed now. Closing the issue.
