### ISSUE TITLE
HTMLRefTable.ejs depends on a hardcoded Kuma image

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1581]
See https://github.com/mdn/yari/blob/1e65d7e24668f88a77c1e53dac7d5ef7882f646a/kumascript/macros/HTMLRefTable.ejs#L205

**Comment by peterbe** [comment]
Do you have any ideas how to solve this @schalkneethling 
Haven't you use other SVGs and stuff in macros and can we learn/steal from that?

**Comment by schalkneethling** [comment]
> Do you have any ideas how to solve this @schalkneethling
> Haven't you use other SVGs and stuff in macros and can we learn/steal from that?

Yup, I can take a look at this.
