### ISSUE TITLE
Main menu drop down is still open when returning to page

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1582]
**Environment: dev**

**Browsers:** 
Firefox Release 
Safari
does not occur on Chrome

Devices: 
Windows PRO 10 64-bit
Android 9.0.0
MacOS Mojave 10.14.6

**Steps to reproduce:** 
1. Go to any page on dev MDN, for example https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web
2. Open any main menu drop down and select an internal section option, for example. https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/Tutorials
3. Select the browser "go back" button to return to previous page. 

**Actual result:** 
Main menu drop down is still open and selected option is highlighted. 
![Navigation menu drop down is still open when returning to page](https://user-images.githubusercontent.com/53306802/97711167-66c50700-1ac5-11eb-82d8-abe7b7b15c8b.gif)

**Expected result:** 
Main menu drop down is closed when previous page is loaded.

**Comment by peterbe** [comment]
Great find @mirunacurtean ! 

@schalkneethling Do you remember, by heart, how the sub-menus decide to be open or not? Is it react state or vanilla JS event handlers or some CSS magic?

**Comment by schalkneethling** [comment]
> Is it react state or vanilla JS event handlers or some CSS magic?

I believe it is React state driven.

**Comment by schalkneethling** [comment]
Will be addressed as part of the redesign and is tracked elsewhere.
