### ISSUE TITLE
Header background color opacity makes text hard to read

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1583]
**Steps to reproduce:**
1. Go to https://main.content.dev.mdn.mozit.cloud/en-US/docs/web/HTTP/Headers/Content-Type
2. jump to Examples section and view header. 

**Actual result:** 
'Content-Type' text is hard to read 
![image](https://user-images.githubusercontent.com/53306802/97712021-8446a080-1ac6-11eb-9f0f-4fdf8fa6ccb1.png)

Other examples: 
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTTP/Headers/Save-Data

**Comment by mirunacurtean** [comment]
Updating with other examples to check when this is fixed: 
https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
"Making eval and arguments simpler"

**Comment by schalkneethling** [comment]
![Screenshot of fix to low contrast headings](https://user-images.githubusercontent.com/10350960/100581567-96e40d80-32f0-11eb-8f12-f7406d471a1b.png)

This has been resolved.
