### ISSUE TITLE
Styling missing for  {{Non-standard_Header}} {{Obsolete_Header}} {{Deprecated_Header}}

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1584]
See [these macros](https://github.com/mdn/content/blob/ccfc7ac1bc07ab283941a0f25130aeb5bde6ddfb/files/en-us/mdn/kitchensink/index.html#L359-L361) in the kitchensink. 
They render to this:
<img width="873" alt="Screen Shot 2020-10-30 at 9 47 11 AM" src="https://user-images.githubusercontent.com/26739/97712630-146bf200-1a95-11eb-9dba-59309e42e99c.png">

Here are examples of these in production:

`{{Non-standard_Header}}`
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/offline_enabled

`{{Obsolete_Header}}`
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color-rendering

`{{Deprecated_Header}}`
https://developer.mozilla.org/en-US/docs/Web/CSS/image-orientation

**Comment by peterbe** [comment]
The warning one still isn't working correctly. 
<img width="1025" alt="Screen Shot 2020-11-20 at 11 19 38 AM" src="https://user-images.githubusercontent.com/26739/99823363-4adfde80-2b22-11eb-9274-d9c3f0799e91.png">
On https://developer.allizom.org/en-US/docs/Web/CSS/image-orientation

**Comment by schalkneethling** [comment]
> The warning one still isn't working correctly.

Hmm, it is still using only `warning` i.e. missing `notecard`

```
<div class="warning">
```

Should the cheerio script not have solved this?

**Comment by peterbe** [comment]
Let's "fail forward" here instead: https://github.com/mdn/yari/issues/1795
