### ISSUE TITLE
BCD table a bit busted

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1595]
On http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/API/dns
there are 2 problems:

1. There's do "desktop" and "mobile" icon on the first row. 
<img width="1337" alt="Screen Shot 2020-10-30 at 3 42 28 PM" src="https://user-images.githubusercontent.com/26739/97750073-8577cd80-1ac6-11eb-8780-495ad98df76b.png">

2. Here in Yari, there's only 1+5 columns. On [prod](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/dns) it's 1 + 6 columns. Yari doesn't have the "Safari" column.

**Comment by peterbe** [comment]
@schalkneethling Can you look into the missing icons?

I'll look into why there's no Safari column. 
Also, I noticed in KumaScript we call it "Firefox for Android" but in Yari it's called "Firefox Android". Wot?!

That "Firefox for Android" phrase seems to come from something called `L10n-CompatTable.json` which I don't know how it works. 
I haven't started debugging any of this yet but perhaps @ddbeck can drop some instant wisdom here. Or perhaps @escattone knows what's going on with these legacy BCD tables.

**Comment by ddbeck** [comment]
Sorry, I don't know anything about where the strings come from. But "Firefox for Android" is the most correct option.

Perhaps it would be a good idea if BCD itself provided browser name strings though.

**Comment by schalkneethling** [comment]
> Sorry, I don't know anything about where the strings come from. But "Firefox for Android" is the most correct option.
> 
> Perhaps it would be a good idea if BCD itself provided browser name strings though.

Something tells me the previous macro version kinda did?

**Comment by schalkneethling** [comment]
Ah yes, but it also returns "Firefox Android" - https://github.com/mdn/kumascript/blob/e6689c907d5991de5aaa5d13969930bca4823fc4/macros/Compat.ejs#L484

**Comment by peterbe** [comment]
@schalkneethling I can take care of https://github.com/mdn/yari/issues/1672 if you can fix the missing icons. 

I'll file a separate one about figuring out why the Safari column is missing in Yari but not in Kuma.

**Comment by peterbe** [comment]
Note to self, the reason the icons don't appear is because the `<th>` get a classname of `bc-platforms-webextension-desktop` instead of just `bc-platforms-desktop`.
