### ISSUE TITLE
Printing of relative paths kinda suck now

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#160]
The `cli` for example is started via the script in the `/package.json`.  
Example:
```
▶ yarn workspace cli start
...
Wrote ../client/build/en-US/docs/Web/HTML/index.json 14ms
Wrote ../client/build/en-US/docs/Web/HTML/Element/address/index.json 156ms
Wrote ../client/build/en-US/docs/HTML/Elements/index.json 10ms
...
```

Inside the `cli` there's a function that handles printing of file paths that tries to make it relative to `process.cwd()`: https://github.com/mdn/stumptown-renderer/blob/71c3221de51fefb7c50195dfda9cef110692a75c/cli/index.js#L73-L76
Its intention is good but the problem is that they don't work when using `yarn workspace cli start` because I'm running that command from `/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer` but the value of `process.cwd` inside the `cli` is `/Users/peterbe/dev/MOZILLA/MDN/stumptown-renderer/cli`.

The problem is that the printed paths aren't something you can click on or copy and paste to open. E.g. `less ../client/build/en-US/docs/Web/HTML/index.json` would fail unless if you first `cd cli`.

**Comment by peterbe** [comment]
@Gregoor Do you know a simple solution to this?

**Comment by Gregoor** [comment]
@peterbe `__dirname` instead of `process.cwd()` should do the trick
