### ISSUE TITLE
Do we need rel=alternative hreflang meta links?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1603]
Like on view-source:https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Error
<img width="1192" alt="Screen Shot 2020-11-02 at 8 47 15 AM" src="https://user-images.githubusercontent.com/26739/97875270-22658100-1ce8-11eb-986f-01c93b29d05d.png">

This is something that Kuma has that we don't have in Yari. 
I honestly don't know anything about this "standard" (I use quotes because I don't even know if it's a standard). 
But it's pretty clever because if you're a browser extension that redirects you to the locale you *prefer*, they have to find out the correct **slug** because it's not good enough to do `url.replace('fr', 'en-US')`. 

A problem we have is that we don't have the complete graph of localization connections. In our current functionality, we can know the connection to the English version. And each English version knows about the translations. But an immediate technical challenge is that we only have this *if* we bother to build with `CONTENT_TRANSLATED_ROOT` which is currently off by default in the 24 build workflow.

**Comment by peterbe** [comment]
If we, by default, always include `CONTENT_TRANSLATED_ROOT`, it'll still be able to always link up the different locales.

**Comment by peterbe** [comment]
I think we simply need to do it. 

> tell Google about these different variations. Doing so will help Google Search point users to the most appropriate version of your page by language or region.

and 

> but it is usually best for you to explicitly indicate your language- or region-specific pages.

https://developers.google.com/search/docs/advanced/crawling/localized-versions?hl=en&visit_id=637411409912568511-3980844248&rd=1

**Comment by peterbe** [comment]
If we *don't* do this, Google.de might display `developer.mozilla.org/en-US/docs/Foo` *higher* than `developer.mozilla.org/de/docs/Foo`. And it might display both. 

But what makes it tricky is; is that so bad? Do we really care that much about driving traffic to the `de` pages for the `Google.de` searchers?

Thing is; if you're selling something it might be extra important that you target and match international Google searchers with the best local URLs. E.g. Your product probably will sell better if the prices are listed in euros rather than dollars. 
But MDN is different. Do we really want to favor the German translation over the English one? It might benefit that German Google searcher to display both sites and she can chose which one she prefers. 

But counter to that argument, we have a lot of titles that are confusing enough as it is. If someone in, say, Sweden, searches for "Intersection Observer" you don't want the Russian translation to show up which it might because that page might have better SEO ranking or something.

**Comment by Ryuno-Ki** [comment]
On top of that, the non-English content might lack behind the English one (sometimes significantly).

**Comment by peterbe** [comment]
From https://developers.google.com/search/docs/advanced/crawling/localized-versions

> Each language version must list itself as well as all other language versions.

So, like Kuma, we need one tag in there for `en`.
