### ISSUE TITLE
Missing "in-page-callout" and "cta" CSS?

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1606]
### Yari
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/3743693/97893887-b20a3000-1ce6-11eb-84bf-28ea6c7133e7.png">

### Current MDN
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/3743693/97894019-d8c86680-1ce6-11eb-8804-afc5a32fe9fc.png">

**Comment by schalkneethling** [comment]
Will be addressed by https://github.com/mdn/mdn-minimalist/issues/271
