### ISSUE TITLE
≤ is ambiguous on MDN

### ISSUE THREAD

**Issue by saschanaz** [mdn/yari#1607]
![image](https://user-images.githubusercontent.com/3396686/75923260-fea22080-5e64-11ea-8d03-861659719fe2.png)

https://developer.mozilla.org/en-US/docs/Web/API/MediaSession

It makes me think that Edge supported the feature *until* version 79, not *at-least-since* 79. There is no description about what `≤` actually means. I think this is a problem.

(Transferred from https://github.com/mdn/browser-compat-data/issues/5782)

**Comment by escattone** [comment]
@ddbeck What are your thoughts on this?

**Comment by ddbeck** [comment]
Making the ≤ a superscript sounds reasonable to me. 👍

**Comment by vinyldarkscratch** [comment]
+1 for a superscript, and perhaps an added note in a dropdown/legend entry explaining exactly what the symbol means?  It seems that there is quite a bit of confusion on this, so an explanatory note should help clear things up, hopefully.
