### ISSUE TITLE
Article footer isn't distinguished from content at all

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1613]
See http://localhost:3000/en-US/docs/Web/HTML/Element/video#See_also
<img width="1008" alt="Screen Shot 2020-11-02 at 4 10 35 PM" src="https://user-images.githubusercontent.com/26739/97919584-041e7600-1d26-11eb-981a-9f050bbf5eaa.png">

That "Last modified: ..." looks like it's another (last) bullet point as part of the "See also" section. 

In Prod this is "resolved" thanks each `<h2>` having a bold blue top-border. 
E.g. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#See_also

**Comment by peterbe** [comment]
@schalkneethling Can you triage this one?

**Comment by schalkneethling** [comment]
Here is my proposal for this section:

## Isolated

![Screenshot 2020-11-29 at 09 15 29](https://user-images.githubusercontent.com/10350960/100535666-9d588380-3223-11eb-814c-7b4c2b2ab8da.png)


## In page (this one was created using devtools so, the above is the clean implementation 😄)

![Screenshot 2020-11-29 at 09 14 37](https://user-images.githubusercontent.com/10350960/100535669-a21d3780-3223-11eb-90e0-87c21b7e4a01.png)

**Comment by mattiapontonio** [comment]
- Maybe the ribbon is too much... 🙂
- The footer Is not actually a footer, is It?

![Screenshot_20201129-091707.png](https://user-images.githubusercontent.com/44380480/100536870-c0833300-3223-11eb-9e89-b3ff5bea2256.png)

**Comment by schalkneethling** [comment]
> The footer Is not actually a footer, is It?

No, but it is the footer of the article so, part of the change would involve wrapping this section as a `footer`

> Maybe the ribbon is too much... 🙂 It has some functionality or meaning?

Perhaps ;) It is a little visual flair. I am not married to it. It is more commonly used to indicate a bookmark which is not accurate here but hey, perhaps it is just what this section needs to further distinguish itself from the rest of the content.

> A list with 1 element is not a list 🙂 Maybe "last modified" can be mini table

Well, technically a list of 1 is still a list. But yes, there are a lot of instances where the HTML can, and will, be cleaned up.

**Comment by mattiapontonio** [comment]
> > The footer Is not actually a footer, is It?
> 
> No, but it is the footer of the article so, part of the change would involve wrapping this section as a `footer`
> 
> > Maybe the ribbon is too much... 🙂 It has some functionality or meaning?
> 
> Perhaps ;) It is a little visual flair. I am not married to it. It is more commonly used to indicate a bookmark which is not accurate here but hey, perhaps it is just what this section needs to further distinguish itself from the rest of the content.
> 
> > A list with 1 element is not a list 🙂 Maybe "last modified" can be mini table
> 
> Well, technically a list of 1 is still a list. But yes, there are a lot of instances where the HTML can, and will, be cleaned up.

These should become 3 issues --> PR

**Comment by peterbe** [comment]
> Here is my proposal for this section:

I don't like either. 
It's virtually impossible to know that "Last modified: ..." and the `<h3>Found a problem on this page?</h3>` are NOT part of the document but rather a function of the document. 
Here's my devtools 2min hack:
<img width="1102" alt="Screen Shot 2020-11-30 at 8 22 31 AM" src="https://user-images.githubusercontent.com/26739/100615237-503ce600-32e5-11eb-9bb5-c4dc12fd0ae2.png">

**Comment by schalkneethling** [comment]
@peterbe Well, yes and no.

"See also", is technically also not part of the document but instead, lists a number of links that is in some way related to the topic of the current document.

In the same vein, "last modified" relates information about the current document, not MDN overall. Then the Github links, except for the link to the contribution doc, again related to the current document i.e. they will take you to the source of this document, or allow you to log an issue about the current document.

It therefore felt like all of this is a type of `aside` i.e. a collection of tengentially related content and so, this is why I grouped them together but, also made it visually distinct. Again, you can largely ignore the little bookmark ribbon 😄 

I do understand where you are coming from with your suggestion and have another idea to propose.

**Comment by schalkneethling** [comment]
Here is another proposal to create a dedicated section for the Github pieces and also, to de-emphasize the last modified line.

![Screenshot 2020-11-30 at 19 51 23](https://user-images.githubusercontent.com/10350960/100645737-c113ea80-3345-11eb-8745-bc3011a09668.png)

**Comment by peterbe** [comment]
I like that but it's a big undertaking to switch to this gray background.

**Comment by mattiapontonio** [comment]
How about even change the content?

## Issues

- [Repository]()
- [Issues]()
- [Contribution guide]()

**Comment by peterbe** [comment]
Now I'm torn. I think there's value in separating what's not part of the document so that it's distinctly visually different. 
But then, the "Last modified" should be part of that metadata region too, no?

I definitely don't like the inclusion of the GitHub logo because GitHub the links are about changing the content, not about GitHub. In other words, that it's GitHub or GitLab or some other link to some other dashboard isn't important. 

But all in all, I'm liking your latest screenshot more than what we have today. I'm struggling to have a preference for this design compared to the one I suggested though. They both solve the problem in a decent way.

**Comment by escattone** [comment]
@schalkneethling Overall, I like your latest screenshot, but I agree with @peterbe about not liking the GitHub logo in the `Found a problem with this page?` heading. I'm less sure about the `Last modified` line, but I'm leaning toward including that in the "metadata" region as well.

**Comment by mattiapontonio** [comment]
I think that `footer` has to be either the `article footer` or the `body footer`. I don't see any other place to put it except for the aside. 
For me it is more related to the article than to the page, for example I believe that from GitHub you cannot change the items in the `aside nav`. 
So I would leave it as a `footer` on the right column (which in another issue could also be moved to the left) and differentiate it. 
The background is fine at the moment ... maybe a lighter tone still ...
