### ISSUE TITLE
Avoid the `mdn_url` to `uri` transformation

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#162]
In `stumptown-content` it's called `mdn_url`. It's a key on every document. It's also in the `document.related_content[].content` and it's in the `document.body[].link_list.value` keys. 

All it does is A) check that the `mdn_url` always starts with a `/` and B) "rename" the key from `mdn_url` to `uri`. 
This feels unnecessary and clunky. We could just start accepting the name `mdn_url`. I.e.
```diff
-<Link to={node.uri}>
+<Link to={node.mdn_url}>
```

It's just fancy preferences for variable names in a sense. It might still be a good idea to do the check that it's a valid relative path. 

Arguably, regarding the check, this is the kind of stuff that might be best to do somewhere in the scripting of `stumptown-content` so that `stumptown-renderer` can just assume the documents packaged are solid. 

Some day, we'll probably execute the `cli` from `stumptown-renderer` from within `stumptown-content`'s CI and that would quickly break the build if some front-matter isn't to the renderer's liking.

**Comment by peterbe** [comment]
What do you think @wbamberg ?

**Comment by wbamberg** [comment]
Is there any change being proposed here for stumptown-content, or is it just for the renderer to use the name `mdn_url` instead of `uri`? If the latter, I don't think I have an opinion on this but I feel like perhaps I am expected to :).

**Comment by peterbe** [comment]
Both. I've never been a huge fan of the mention of "mdn". But perhaps there's a good reason for it. "uri" is better because it's not a URL (because it's only just a path) but then again I'm not sure I've ever understood the difference between "URI" and "URL". 

But from the stumptown-content perspective, it doesn't really care about URLs at all since that's a worry of the consumer. But we're faced with the reality that MDN is the most important consumer and it has legacy that we have to respect.

**Comment by wbamberg** [comment]
Just on the naming issue, I think there's a difference depending on the intended usage of this property. Is it intended 

(1) to help us construct MDN-the-website out of stumptown-content,
or
(2) for third parties (like VS Code) to link to MDN-the-website?

For instance, the `mdn_url` property in BCD clearly has (2) in mind. People using BCD to power compat tools use it to link back to MDN for more information on an item.

But the `mdn_url` in stumptown_content increasingly looks like (1): it's an internal thing used to build a website out of the content. Changing it from an absolute to a relative URL was a significant step towards (1).

If it's function is (2), then `mdn_url` is right: it's saying: "here's a page about this thing *on MDN*". If it's function is (1), then `uri` is fine.

If its function is (1), should we *also* have `mdn_url` to perform function (2)? Perhaps noone cares at this point and we could worry about that when we need to.

Also paging @Elchi3 and @ddbeck for some perspective.

**Comment by ddbeck** [comment]
> If its function is (1), should we also have `mdn_url` to perform function (2)?

If transforming `uri` into `mdn_url` is possible, then providing consumers a convenience method for that transformation is probably the right way to go. If it's an independent bit of data, then yes, let's have both. But…

> Perhaps noone cares at this point and we could worry about that when we need to.

This is probably the case for now. I'm fine with `uri` for now and fixing the `mdn_url` problem when it's a live problem. Kicking cans like these down the road has served us pretty well on BCD.

**Comment by Elchi3** [comment]
> For instance, the `mdn_url` property in BCD clearly has (2) in mind. People using BCD to power compat tools use it to link back to MDN for more information on an item

Yes, this is a use case, but not exclusively so. The rendering of the MDN compat tables need `mdn_url` to link to sub features in the rows and I did wonder if there is a more elegant way for this to happen in stumptown, because in the stumptown-content packaged json there is `mdn_url` again in the `browser_compatibility` object in addition to the `mdn_url` in the "main object" (it is the same url in case of the root feature, but different for sub features). So, this makes it look like `mdn_url` doesn't really belong in BCD.

Oh, I just realized the subfeatures aren't resolved into the json? Like, I only see one `__compat` object in `package/html/reference/elements/audio.json`. But there are multiple in rows for the [audio element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio#Browser_compatibility). Are subfeatures not rendered in the tables?

Maybe it would be cool if we could re-use "queries" like `html.element.audio.autoplay` to refer to things and then only create URLs when we need them? That way, when several compat rows come into stumptown, it could see these and link them as it knows thanks to a url resolver what the urls are for "html.element.audio.whatever".

> Perhaps noone cares at this point and we could worry about that when we need to.

Yes, my above text are just thoughts on this. I'm also fine with getting more into this when we feel the need.

**Comment by peterbe** [comment]
> Just on the naming issue, I think there's a difference depending on the intended usage of this property. Is it intended
> 
> (1) to help us construct MDN-the-website out of stumptown-content,
> or
> (2) for third parties (like VS Code) to link to MDN-the-website?
> 

I definitely think it's (1) because it's already not an absolute URL. So the likes of VSCode or DevTools would now need to do `'https://developer.mozilla.org' + mdn_url`. 

Therefore I'm in favor of renaming all occurrences from `mdn_url` to `uri`.

**Comment by wbamberg** [comment]
Peter:

> I definitely think it's (1) because it's already not an absolute URL.

Yes, but it used to be :). It started out as a clone of the BCD one, although it really always had this dual existence. But it's meaning has definitely shifted more towards (1) over the last few months.

So it seems like everyone is OK with `mdn_url` -> `uri` and worry about external clients later. But that said, this is a breaking change that doesn't actually get us any new features, so it isn't a high priority for me.

> Oh, I just realized the subfeatures aren't resolved into the json? Like, I only see one __compat object in package/html/reference/elements/audio.json. But there are multiple in rows for the audio element. Are subfeatures not rendered in the tables?

I don't understand this, I do see multiple `__compat` objects in packaged, and the rendered table includes multiple rows:

<img width="941" alt="Screen Shot 2019-10-02 at 10 08 06 AM" src="https://user-images.githubusercontent.com/432915/66065601-a2755200-e4fc-11e9-8614-f962dba49999.png">

> Maybe it would be cool if we could re-use "queries" like html.element.audio.autoplay to refer to things and then only create URLs when we need them? That way, when several compat rows come into stumptown, it could see these and link them as it knows thanks to a url resolver what the urls are for "html.element.audio.whatever".

I'd need to understand this better, maybe we should talk it over in person. I definitely see value in keeping the same taxonomy for stumptown-content that you have pioneered for BCD.

>  Kicking cans like these down the road has served us pretty well on BCD.

That's reassuring!

**Comment by peterbe** [comment]
Note-to-self; When I don't have anything else interesting to do I'll take a quick stab to search-and-replace all occurances of `mdn_url` to `uri` in both content and renderer. I'll also remove any checking or massaging of this value in the renderer's `cli`.

**Comment by peterbe** [comment]
Ugh. Here we are. In Stumptown (and in BCD) it makes sense to call a URL something like `mdn_url` (or `mdnurl` or `mdn-url` or `mdn-uri`) because for those project MDN is just another (albeit important) consumer of the data. 
But we got a bit stuck with it. The word is scattered all over the Yari codebase and it's a bit unfortunate. 

Either way, I think we should consider refactoring away the term `mdn_url` and go for `url` throughout Yari. But it's probably for another day.
