### ISSUE TITLE
When making changes/reviewing PRs, need a better way to preview what's changed

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#1624]
When reviewing a PR in the content repo, loading the page in the local preview was a little bit of a pain  — it took me a couple of minutes to figure out what URL to type in to see the rendered edited page. I wonder if we could print out what URLs you need to go to the pages that have been modified?

One the URL was figured out, testing the change was OK — flip between checking out main and the test branch, and then run start again, then reload the page. Although I wonder if there is an easier way to allow a user to compare before and after?

I chatted to @peterbe on slack about this, and he offered these thoughts:

Two possible solutions I can think of:

*The CI in the pull request knows which URLs were touched because it knows which files to build. So it could post these as a pull request comment so you only needed to click.
* Another option is that the home page (which currently just shows a bunch of links to recently viewed documents) could ask git “Which files are different in the current branch compared to origin/main?” and for those each one present a link to them.
* Another idea is that there could be a form/button on the homepage (on localhost:5000) where you just paste in the URL of the GitHub PR and yari can automatically switch to that branch.

This could be worth looking into more at some point.

**Comment by Ryuno-Ki** [comment]
Hm, what if the behaviour could be [similar to Vercel](https://vercel.com/docs/git/vercel-for-github) (f.k.a. Zeit) ?

![](https://vercel.com/docs-proxy/static/docs/git/github-comment.png)

Is there a ephemeral URL the PR gets deployed to?
Or at least a way to map a file to an URL (by rewriting the path `/files/something` to `localhost:5000/something`)?

**Comment by peterbe** [comment]
> Is there a ephemeral URL the PR gets deployed to?

Some day we'll try to make it so that every PR (on the content) publishes as a deployed site. But it's quite a bit of work. 

I think a great stop-gap is to convert the list of files (that get built) into a list of URLs that at least start with `http://localhost:5000` then the editor just needs to check out the branch and click the links. 
The question is; where do we put that? On the home page or as a PR comment posted by CI?

**Comment by peterbe** [comment]
For the record, the "correct" most-basic way to review a content PR is to click the "Files" tab and for each `index.html` that's mentioned you need to expand it to see the front-matter at the top. Then you need to copy-n-paste the slug and paste it after `http://localhost:5000/en-US/docs/`. Cumbersome but something we can make easier for the reviewer.

**Comment by Ryuno-Ki** [comment]
Just a wild thought: Could there be a screenshot diff? With a highlight (= coloured border) of the areas that changed?

**Comment by mattiapontonio** [comment]
> The question is; where do we put that? On the home page or as a PR comment posted by CI?

On the PR 👍
Nice issues.

**Comment by schalkneethling** [comment]
We now have preview urls for pull requests 🎉  - https://github.com/mdn/content/pull/10097#issuecomment-951923967
