### ISSUE TITLE
parseInt() with second argument 10

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#1625]
I spotted this at
https://github.com/mdn/yari/blob/cdaecafd14d4b758046f21a7efb4dd0a6fc26ca0/server/index.js#L270
but a search yields other instances.

Background: When the first arguments happen to start with 0, it could lead to [unintended consequences](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#Description) / [on MDN/content](https://github.com/mdn/content/blob/ca5e207a79d092bd4572818112a70558d7499648/files/en-us/web/javascript/reference/global_objects/parseint/index.html#L43-L75)

So as a safety measure, it's best to always call `parseInt()` with two arguments :-)

**Comment by peterbe** [comment]
Not on the server. The chances of that not working are unrealistic.
