### ISSUE TITLE
<kbd> lost its styling

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1626]
In Yari:
<img width="399" alt="Screen Shot 2020-11-03 at 1 17 31 PM" src="https://user-images.githubusercontent.com/26739/98024933-07be0580-1dd7-11eb-921a-f6ba855032c4.png">
<img width="299" alt="Screen Shot 2020-11-03 at 1 18 26 PM" src="https://user-images.githubusercontent.com/26739/98024962-11476d80-1dd7-11eb-93fb-0f1ecf20b03f.png">

In Kuma:
<img width="375" alt="Screen Shot 2020-11-03 at 1 18 41 PM" src="https://user-images.githubusercontent.com/26739/98024981-1ad0d580-1dd7-11eb-8234-29190ae868e8.png">

Compare https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Ember_structure_componentization#Using_the_CLI_to_create_our_components_for_us with http://localhost:3000/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Ember_structure_componentization#Using_the_CLI_to_create_our_components_for_us

**Comment by Ryuno-Ki** [comment]
The respective CSS for `kbd`:

```css
    background-color: #eee;
    border-radius: 3px;
    border: 1px solid #b4b4b4;
    box-shadow: 0 1px 1px rgba(0,0,0,.2),0 2px 0 0 rgba(255,255,255,.7) inset;
    color: #333;
    display: inline-block;
    font-family: consolas,"Liberation Mono",courier,monospace;
    font-size: .85em;
    font-weight: 700;
    line-height: 1;
    padding: 2px 4px;
    white-space: nowrap;
}
```

**Comment by peterbe** [comment]
Another good page to test is:
http://localhost:3000/en-US/docs/Tools/Page_Inspector/Keyboard_shortcuts
vs https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/Keyboard_shortcuts

**Comment by schalkneethling** [comment]
Addressed in https://github.com/mdn/mdn-minimalist/pull/234
We can confirm and close once I release a new version of minimalist.

**Comment by peterbe** [comment]
https://main.content.dev.mdn.mozit.cloud/en-US/docs/Tools/Keyboard_shortcuts
