### ISSUE TITLE
The font of the document title looks much bigger in Yari

### ISSUE THREAD

**Issue by escattone** [mdn/yari#1654]
MDN:
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/3743693/98311566-8e641580-1f84-11eb-8c3b-db6eb0728ec8.png">

Yari:
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/3743693/98311667-c5d2c200-1f84-11eb-8f36-84fa068c0cd1.png">

**Comment by schalkneethling** [comment]
Thank you for bringing this up @escattone. I was bold when I chose the type scale for desktop 😄 I do agree that especially `h1` and `h2` elements are probably too large. I have switched to a different type scale that has smaller increments. This will be introduced with this release of minimalist.

https://github.com/mdn/mdn-minimalist/pull/231

Let me know what you think once the minimalist dependency has been updated with the new scale.

**Comment by schalkneethling** [comment]
@escattone This has been merged https://github.com/mdn/yari/pull/1658

**Comment by schalkneethling** [comment]
@escattone After the recent changes, do you feel that we can close this one?

**Comment by escattone** [comment]
@schalkneethling Yes, let's go with the recent changes. Thanks!
