### ISSUE TITLE
Things I don't like about the footer

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1662]
<img width="1131" alt="Screen Shot 2020-11-06 at 3 00 20 PM" src="https://user-images.githubusercontent.com/26739/98409527-08f26b00-2041-11eb-8461-0b28fd4ca417.png">

1. (in the 2-col grid) I don't like that the black rectangle around each link is clickable. It should just be the white text. It's unexpected that clicking anywhere in the black emptyness suddenly opens a link.
2. There's an odd space between the words "MDN" and "Mozilla" until their little SVG icons. Looks better on Kuma. 
3. The words "these licenses" in the sentence "© 2005-2020 Mozilla and individual contributors. Content is available under these licenses." is actually a link. You don't find that out until you hover over these two words. 
4. It's weird that some links are underlined and some are not.

**Comment by bershanskiy** [comment]
@peterbe 

> 2. There's an odd space between the words "MDN" and "Mozilla" until their little SVG icons. Looks better on Kuma.

On the image above you marked only one space between MDN and SVG icons, but not the space after "Mozilla". Did you mean to remove both of them (to maintain symmetry)? What do you think about the following image where they both are reduced from 40px to 5px? If it's OK, I'll prepare a PR.

> 3. The words "these licenses" in the sentence "© 2005-2020 Mozilla and individual contributors. Content is available under these licenses." is actually a link. You don't find that out until you hover over these two words.

Would you be interested in reviewing #1837?

> 4. It's weird that some links are underlined and some are not.

Would you prefer if all "stand-alone" links were underlined only on hover, but in-text "these licenses" link was always underlined?

Result:
![image](https://user-images.githubusercontent.com/45960703/100157081-0a35eb80-2ebb-11eb-8627-66fd1a2d7529.png)

**Comment by peterbe** [comment]
@bershanskiy Thanks! 
I'm hoping that @schalkneethling can respond this issue is in his domain.
