### ISSUE TITLE
BCD table doesn't list main feature

### ISSUE THREAD

**Issue by Elchi3** [mdn/yari#1668]
Hey! :)

Locally, I see no `concat` in this BCD table:
http://localhost:5000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat#Browser_compatibility
Compare with:
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat#Browser_compatibility

See also the missing first row here (should also list "Array"):
http://localhost:5000/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Browser_compatibility
c.f.
https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array#Browser_compatibility

**Comment by peterbe** [comment]
I guess https://github.com/mdn/yari/pull/1627 didn't seem to solve all the problems. 
I'll try to fix this.

**Comment by escattone** [comment]
@Elchi3 !!!!!!! ❤️ 🎉 Wow, it does my heart some good to "see" you again! Thanks for this!

**Comment by peterbe** [comment]
We're just waiting for @fiji-flo to review https://github.com/mdn/yari/pull/1681
