### ISSUE TITLE
It's "Firefox for Android" not "Firefox Android"

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1672]
Sorry, I don't know anything about where the strings come from. But "Firefox for Android" is the most correct option.

Perhaps it would be a good idea if BCD itself provided browser name strings though.

_Originally posted by @ddbeck in https://github.com/mdn/yari/issues/1595#issuecomment-723020851_

**Comment by peterbe** [comment]
@ddbeck The string "Firefox Android" comes from BCD itself. 
https://github.com/mdn/browser-compat-data/blob/e5cdca34b6b499dfe15c800ad76fd661f075a5cb/browsers/firefox_android.json#L4

So, if "Firefox for Android" is the correct string, does that mean we should edit it in that file ^ ?

Also, if "Firefox for Android" is correct (and "Firefox Android" is wrong), should we not also change this too: https://github.com/mdn/browser-compat-data/blob/e5cdca34b6b499dfe15c800ad76fd661f075a5cb/browsers/chrome_android.json#L4

**Comment by ddbeck** [comment]
For Firefox for Android, that's correct. We should edit that file.

For Chrome, I think we should probably ask Google what their preferred designation is, at least for developer audiences.

For BCD's part, I've opened https://github.com/mdn/browser-compat-data/issues/7328.
