### ISSUE TITLE
Thank you but that design is not going to be fixed. Instead, we're moving our attention to Project Yari.

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1674]
Thank you but that design is not going to be fixed. Instead, we're moving our attention to Project Yari. 
Use https://developer.allizom.org/en-US/docs/Web/API/Element/requestFullScreen to test (for example). 

_Originally posted by @peterbe in https://github.com/mdn/kuma/issues/7608#issuecomment-724018020_

![Screenshot_20201109-180050.png](https://user-images.githubusercontent.com/44380480/98572194-a3f37b00-22b5-11eb-86d5-222fde54ab67.png)

Hello, title here exit the viewport.

**Comment by schalkneethling** [comment]
Thank you for reporting @mattiapontonio. I will address this.

**Comment by mattiapontonio** [comment]
![Screenshot_20201110-005658.png](https://user-images.githubusercontent.com/44380480/98610379-bab6c380-22ef-11eb-8e77-0854cbe253dd.png)
Not incognito nothing changhed.
Chrome 86 on Android 10

**Comment by schalkneethling** [comment]
@mattiapontonio this has not been deployed yet. There is a time lag between things being merged to `master/main` and it landing on our development or staging environments.

**Comment by mattiapontonio** [comment]
Ok.
I like this solution
https://github.com/mdn/yari/pull/1675#issuecomment-724276853
