### ISSUE TITLE
Make the auto-complete titles no overflow so weirdly

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1680]
<img width="534" alt="Screen Shot 2020-11-09 at 4 05 39 PM" src="https://user-images.githubusercontent.com/26739/98596514-8ae2ce00-22a5-11eb-9e71-8b323e08f4cb.png">

Note, there's a big chance the auto-complete search is disabled in the Yari1 launch so this issue can not be a high priority.

**Comment by schalkneethling** [comment]
Looks like one of the other changes fixed this one o/\o

### Mobile

![Screenshot 2020-11-29 at 09 27 25](https://user-images.githubusercontent.com/10350960/100535879-6daa7b00-3225-11eb-9cd5-5acd4ac1f1d5.png)


### Tablet

![Screenshot 2020-11-29 at 09 27 11](https://user-images.githubusercontent.com/10350960/100535886-77cc7980-3225-11eb-9067-fbc5f92ce7e4.png)


### Desktop

![Screenshot 2020-11-29 at 09 27 47](https://user-images.githubusercontent.com/10350960/100535889-7d29c400-3225-11eb-8ee4-ef4cbc65cc7d.png)

**Comment by peterbe** [comment]
This is still what I see. 
<img width="531" alt="Screen Shot 2020-12-01 at 2 27 45 PM" src="https://user-images.githubusercontent.com/26739/100787282-68922b00-33e1-11eb-9a74-ae89a21a91de.png">

I don't know why so few things appear when you took your screenshot for Desktop.

**Comment by mattiapontonio** [comment]
- https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow
- https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title
