### ISSUE TITLE
Underlining of <a><code> elements in BCD table looks weird

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1694]
<img width="286" alt="Screen Shot 2020-11-10 at 8 22 59 PM" src="https://user-images.githubusercontent.com/26739/98753553-9c55d400-2392-11eb-8724-bd6ec6938103.png">

Some have, what appears to be, double-underline and some have an extra thick underline.

**Comment by peterbe** [comment]
@schalkneethling I took the liberty of calling this a Yari1 UI "blocker".

**Comment by Ryuno-Ki** [comment]
Which page would that be?
My gut feeling would be a `text-decoration: underline` combined with a `border-bottom` (or `border-block-end`).

**Comment by peterbe** [comment]
Related https://github.com/mdn/yari/issues/1610
