### ISSUE TITLE
Sidebar navigation menu is still open and link is selected after returning from page user was redirected to

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1705]
**Environment:**
Stage

**Steps to reproduce:**
1. Go to https://developer.allizom.org/en-US/docs/Web/JavaScript and open "Complete beginners" menu. 
2. Select any of the links. 
3. After being redirected to the selected page, go back to the previous page using the 'go back' browser button. 
4. View sidebar navigation menu. 

**Actual result:**
The menu is still open and the link is selected. 

**Expected result:**
On https://developer.mozilla.org/en-US/docs/Web/JavaScript the menu is closed when returning to the page. 

![Sidebar navigation menu is still open when returning to page after following a link redirect](https://user-images.githubusercontent.com/53306802/98830569-3aa17280-2443-11eb-846b-1d3a7ae19109.gif)

Note: This is very similar to #1582  with the exception that it is the sidebar menu affected instead.

**Comment by escattone** [comment]
Yari is designed to behave this way.
