### ISSUE TITLE
Redirect to 'JavaScript expressions and operators' gets a 404 page not found result

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1709]
Environment:
Stage

**Steps to reproduce:** 
1. Open in browser https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference. 
2. Jump to 'Expressions and operators' section. 
3. Select 'JavaScript expressions and operators.' link. 

**Actual result:**
Redirect results in 404 page not found and when trying to go to https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Operators the same result was received. 

**Expected result:**
Like all other links on the page, his should be functional and redirect to the expected page. 

![JavaScript expressions and operators 404 redirect](https://user-images.githubusercontent.com/53306802/98834087-79392c00-2447-11eb-9471-7be047eed727.gif)

**Comment by peterbe** [comment]
Perhaps something that might interest you @fiji-flo ?

**Comment by mirunacurtean** [comment]
Updating with other 404 redirect issues: 
https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar
