### ISSUE TITLE
Low contrast of code as headline

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#1725]
Spotted at http://localhost:5000/en-US/docs/Web/HTML/Element/input/text#Non-standard_attributes

![low-contrast](https://user-images.githubusercontent.com/3097194/98872791-76eec600-2477-11eb-9df6-b4322d178d9b.png)

The CSS applied to `<code>` yields bad contrast here.
Also, the icon in headlines need some polishing.

**Comment by peterbe** [comment]
Don't manually fix cases of `<h3><code>...</code>` there are hundreds of these, in en-US alone. It can be fixed with styling. That's why I moved it here to `yari`.

**Comment by schalkneethling** [comment]
This has been resolved by https://github.com/mdn/yari/pull/1850
