### ISSUE TITLE
Too much whitespace margin

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1729]
This is what it looks like on mobile:
![IMG_354428418743-1](https://user-images.githubusercontent.com/26739/99076921-e9e86180-2589-11eb-979c-486be6ac3e0d.jpeg)

I can't explain it, perhaps it's just habits, but it just feels like too much whitespace margin is wasted. 
Fiori uses 24px on mobile. Wikipedia uses 16px. 
![IMG_FED48E59DD8E-1](https://user-images.githubusercontent.com/26739/99077035-1f8d4a80-258a-11eb-88a3-aad8ebb37ecf.jpeg)

Other sites:

* developer.mozilla.org: 20px
* docs.github.com: 16px
* web.dev: 24px
* smashingmagazine.com: 18px
* css-tricks.com: 26px (but they have a black "container" around the article)

Like I said, perhaps it's just me. But I feel like precious space is wasted on the margins. It's actually not as big a problem when you're reading blocks of plain paragraph prose. But it's much more pronounced on reference pages that have lots of other features like code snippets and tables. 
For example:
<img width="425" alt="Screen Shot 2020-11-13 at 8 35 06 AM" src="https://user-images.githubusercontent.com/26739/99077698-249ec980-258b-11eb-9dbf-3c5f796dfa12.png">

**Comment by schalkneethling** [comment]
This has been resolved by an earlier pull request.

![Screenshot 2021-01-11 at 15 31 34](https://user-images.githubusercontent.com/10350960/104188600-2289a780-5422-11eb-82f9-2ff6b4b3a656.png)
