### ISSUE TITLE
Previous and Next buttons from Javascript guide pages should have the same styling as the ones from Javascript Complete beginner pages

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1730]
**Steps to reproduce:** 
1. Go to https://developer.allizom.org/en-US/docs/Web/JavaScript. 
2. Open the Complete Beginner menu and select to view the JavaScript basics page. Note the 'Previous' and "Next" buttons. 
3. Return to https://developer.allizom.org/en-US/docs/Web/JavaScript. 
4. Navigate to  JavaScript Guide> Introduction and view the  'Previous' and "Next" buttons. 

**Actual result:**
![image](https://user-images.githubusercontent.com/53306802/99079234-53876080-25c8-11eb-8d52-3f68b4d53a67.png)

**Expected result:**
Consistent styling of the Previous and Next buttons across MDN pages. 
![image](https://user-images.githubusercontent.com/53306802/99079156-35b9fb80-25c8-11eb-83b7-e136880a3946.png)

**Comment by peterbe** [comment]
Same styling now on:
https://developer.allizom.org/en-US/docs/Web/JavaScript/Guide/Introduction
https://developer.allizom.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics

At least in terms of the color of the buttons.
