### ISSUE TITLE
 "Prerequisites" text overlap and image display issues

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1734]
**Steps to reproduce:** 
1. Go to https://developer.allizom.org/en-US/docs/Learn/CSS/First_steps. 
2. From the CSS first steps menu select the What is CSS? page. 
3. View the "Prerequisites:" and "Objective" table and then scroll down the page "Browser Default" image. 

**Actual results:**
Text overlap on 'CSS first steps', 'CSS building blocks', 'Styling text' and 'CSS layout' pages 
![image](https://user-images.githubusercontent.com/53306802/99087023-f349ec00-25d2-11eb-8e5c-47ac04cdf1b6.png)

**Image display issues - the images are too stretched out
"Browser defaults" and "Browser support" on:**
https://developer.allizom.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS
![What is CSS table text overlap and images height](https://user-images.githubusercontent.com/53306802/99087263-3e63ff00-25d3-11eb-806c-b308f6311d09.gif)

**'Jane Doe' image example on:**
https://developer.allizom.org/en-US/docs/Learn/CSS/First_steps/Using_your_new_knowledge
"Mozilla is cool" image
https://developer.allizom.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics

Web Console image
https://developer.allizom.org/en-US/docs/Web/JavaScript/Guide/Introduction

**Expected result:**
See https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS
https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/Using_your_new_knowledge

**Comment by peterbe** [comment]
It's weird that, as part of the content, that image tag tries to set its own width and height with CSS (`style="..."`). That's something we need to tackle some other day. I think it's a hangup from the CKEditor. 

However, in Kuma, the wrapping `<p>` tag contains width but it doesn't mess with the height of the image, so the image is allowed to maintain its aspect ratio. Why isn't minimalist doing that?

**Comment by schalkneethling** [comment]
> **Image display issues - the images are too stretched out "Browser defaults" and "Browser support" on:**
> [developer.allizom.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS](https://developer.allizom.org/en-US/docs/Learn/CSS/First_steps/What_is_CSS)

That is a content problem as the styling originates from inline styles. Previous we had the following in the CSS:

```
height: auto !important;
```

Let's not do that anymore. That is a bug that should be fixed in the content. I fixed this article on the wiki so, when we import again, it will be resolved. Thanks for logging this @mirunacurtean

**Comment by schalkneethling** [comment]
The "text overlap" overlap issue has also been resolved 🥳

**Comment by peterbe** [comment]
> Let's not do that anymore. That is a bug that should be fixed in the content. I fixed this article on the wiki so, when we import again, it will be resolved.

What should it be?
I noticed that [the image](https://mdn.mozillademos.org/files/16493/html-example.png) is 1385x594 and that's what it's inline style says (or said, until yesterday).

One thing we can, and should do, is to always specify the width and height of images. I.e.
```html
<img alt="The default styles used by a browser" 
 height="594" width="1385"
 src="https://mdn.mozillademos.org/files/16493/html-example.png" style="border: 1px solid #cccccc;">
```
because that prevents annoying layout shift.

**Comment by peterbe** [comment]
I'm moving the discussion here: https://github.com/mdn/yari/issues/1798 about scales. 

Besides, in `en-US` alone there are 1,921 images that have their width and height set as inline style attributes. 
```
▶ rg '<img'  | rg width | rg height | wc -l
    1921
```
are all of these going to look "wonky" in Yari when we launch?

Either way, let's move this to a new issue too.

**Comment by schalkneethling** [comment]
> One thing we can, and should do, is to always specify the width and height of images. I.e.

Yes, indeed. But _not_ with inline CSS. Setting the attributes is definitely the way to go.
