### ISSUE TITLE
First column text overlaps with the second column

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1735]
1. Go to https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array
2. Find text "Property/Element"
3. View table. 
4. Notice that the text from the first column overlaps the text from the second column.
![image](https://user-images.githubusercontent.com/53306802/99090237-08c11500-25d7-11eb-91c8-a3fa55da0fb0.png)

Other examples:
'Comparison of class-based (Java) and prototype-based (JavaScript) object systems' table
https://developer.allizom.org/en-US/docs/Web/JavaScript/Guide/Details_of_the_Object_Model
https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
Issue: 
https://github.com/mdn/yari/issues/1734

**Comment by peterbe** [comment]
I don't know why the `.standard-table` has [a hardcoded limit](https://github.com/mdn/mdn-minimalist/blob/1be44f7c5e967834a1241268f7320aed4c681ce7/sass/atoms/_tables.scss#L91). Seems arbitrary and specific.

**Comment by schalkneethling** [comment]
see https://github.com/mdn/mdn-minimalist/issues/263

**Comment by schalkneethling** [comment]
> I don't know why the `.standard-table` has [a hardcoded limit](https://github.com/mdn/mdn-minimalist/blob/1be44f7c5e967834a1241268f7320aed4c681ce7/sass/atoms/_tables.scss#L91). Seems arbitrary and specific.

That is for mobile viewports. For one thing, I should not apply that on viewports where it is not needed. My bad 😄 but, I think there is a larger problem I need to address somehow. Tables are tricky to make responsive if you do not have complete control over the content.

**Comment by schalkneethling** [comment]
Hah, seems `max-width: inherit;` is somehow not doing the trick there.

**Comment by schalkneethling** [comment]
resolved by https://github.com/mdn/yari/pull/1776
