### ISSUE TITLE
Table borders are missing 

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1737]
**Affected pages (discovered so far):** 
https://developer.allizom.org/en-US/docs/Web/JavaScript/A_re-introduction_to_JavaScript
https://developer.allizom.org/en-US/docs/Web/JavaScript/Enumerability_and_ownership_of_properties

**Allizom rendering:** 
![image](https://user-images.githubusercontent.com/53306802/99091628-cf89a480-25d8-11eb-828e-659601fb1e7f.png)

![image](https://user-images.githubusercontent.com/53306802/99091707-e92aec00-25d8-11eb-939b-6e7092d9ae11.png)

![image](https://user-images.githubusercontent.com/53306802/99091731-f21bbd80-25d8-11eb-9217-11396d41efb8.png)

**Mozilla:**
![image](https://user-images.githubusercontent.com/53306802/99094658-c7cbff00-25dc-11eb-8bf7-e9d2fc6eb061.png)
![image](https://user-images.githubusercontent.com/53306802/99094743-e4683700-25dc-11eb-95e2-5eb6f8903b67.png)

![image](https://user-images.githubusercontent.com/53306802/99094838-0366c900-25dd-11eb-92a5-97c80801f18b.png)

**Comment by schalkneethling** [comment]
See https://github.com/mdn/mdn-minimalist/issues/264

**Comment by schalkneethling** [comment]
Thank you @mirunacurtean.

We will need to look into some of these tables post-launch and make a decision on whether we need to add support for these or, refactor them. What I _am_ going to do is add at least basic support so they have borders drawn as a bare, base style.

The tables that scroll are wrapped in a `div` element with inline style so, this is yet another thing we will need to make a decision around post-launch and clean up. For now, giving them at least some basic styling is sufficient.

![Screen Shot of tables with only basic styling support](https://user-images.githubusercontent.com/10350960/99647155-0db01980-2a5a-11eb-87ea-d864e7552732.png)


BTW, I am collecting odd pages and places where folks used inline styles here[1] so we can loop back and address these cases.

[1] https://github.com/mdn/mdn-minimalist/issues/256

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/pull/1776
