### ISSUE TITLE
'Random canvas circles' example does not display images when clicking on the "Update" button

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#1739]
Steps to reproduce:
1. Go to https://developer.allizom.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code. 
2. Under the "Why Bother" section there is an example. click the "Update" button to view it. 

**Actual result:**
No image is displayed. 

**Expected result:**
Every time the Update button is hit, an image is displayed. 

![Update image with no reaction](https://user-images.githubusercontent.com/53306802/99097342-2c3c8d80-25e0-11eb-867a-cd88fcacb850.gif)

**Comment by chrisdavidmills** [comment]
This looks like expected behavior to me — 100 random circles drawn each time the button is clicked. What do you perceive as being wrong here?

**Comment by mirunacurtean** [comment]
@chrisdavidmills Thanks for checking.  Seem like this it was just recently fixed because it was not working when I logged it, as seen from in the GIF. 
Closing it as it is not longer reproduced.
