### ISSUE TITLE
Specifications table overflow viewport in mobile

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1750]
https://developer.allizom.org/en-US/docs/Web/CSS/flex-shrink#Specifications
https://whatismybrowser.com/w/ZHRXZWB

**Comment by peterbe** [comment]
Do you think you can make a PR to make those specification tables responsive?

**Comment by mattiapontonio** [comment]
I'm focused on another project so I can't guardantee when. Open issue is more easy from mobile and so I do It.
Not excluded, let me win the "setup fear" 🙂

**Comment by mattiapontonio** [comment]
https://github.com/mdn/sprints/issues/3840

**Comment by schalkneethling** [comment]
See https://github.com/mdn/mdn-minimalist/issues/262

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/pull/1776
