### ISSUE TITLE
Sign in buttons overflow

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1751]
https://developer.mozilla.org/en-US/users/account/signup-landing

![Screenshot_20210120-013505.png](https://user-images.githubusercontent.com/44380480/105110800-be20b500-5abf-11eb-9040-54f0a4ffbe46.png)

https://whatismybrowser.com/w/HHR6YME

**Comment by peterbe** [comment]
![IMG_CF498A4146BC-1](https://user-images.githubusercontent.com/26739/99454407-5e0d6700-28f4-11eb-8f1b-5a71b4b6c258.jpeg)
It's fine on iOS. 

Can you take a screenshot?

**Comment by mattiapontonio** [comment]
I don't know why but i can't upload screenshots...
Anyway i see it's not fine, seems padding Is consinstent where there are the text and not when there are the buttons...

**Comment by mattiapontonio** [comment]
First shot: less text and inline `button` as default (buttons are inline i guess).

**Comment by mattiapontonio** [comment]
![Screenshot_20201121-100751](https://user-images.githubusercontent.com/44380480/99872384-bb9a0000-2be1-11eb-8b8c-4e2ae5aacce8.png)

Here. Should not be better to redirect ti the page so unic flow and less maintenace?

**Comment by mattiapontonio** [comment]
Still a issue
https://developer.mozilla.org/en-US/users/account/signup-landing
