### ISSUE TITLE
Dump a CSV file of all revision creations

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1753]
As discussed, it would be a database dump view that is from `wiki_revision` something like:
```
URL     DATE     USER
```
That way, if someone really wants to prove to their future employer that they made many revisions, they can point to this file which will upload into an `mdn` GitHub repo with a README.

**Comment by peterbe** [comment]
This issue is now part of [the launch-day list](https://docs.google.com/document/d/1VvaT5q1uMsoJm2TLmeQAmdXKFfJTBUru0VJTFtQjM3o/edit?ts=5faabf30#)
It is my intention to do a practice run to generate this with a MySQL backup dump and to set up the git repo with a decent README.

**Comment by peterbe** [comment]
It's unclear to me how to output this. After all...

```
mysql> select count(*) from wiki_revision;
+----------+
| count(*) |
+----------+
|  1011631 |
+----------+
1 row in set (29.31 sec)

```

But I think if you flatten it so you only list the distinct usernames for every document, it'll be a lot less.

**Comment by escattone** [comment]
@peterbe Thank you for doing this! That looks good to me, except that I would suggest that we only filter out "junk" slugs, and keep everything else, including slugs we consider "archived". It seems better to include as much as possible that isn't "junk". A good name for the repo? What do you think of one of these options (assuming all are within the MDN organization):
1. wiki-history
1. wiki-revision-history
1. wiki-content-revision-history

**Comment by peterbe** [comment]
What do you think @escattone and @chrisdavidmills ?
https://github.com/mdn/wiki-revision-history

**Comment by peterbe** [comment]
The code I used to generate the CSV file lives within https://github.com/peterbe/yari/tree/1753-dump-a-csv-file-of-all-revision-creations but I'm not going to get that merged into Yari's `master`.

**Comment by peterbe** [comment]
If you guys can please skim through the `README.md` and make edits, I think we can move on. In fact, we can archive the repo too. 
Perhaps, if you think it's a good idea, we can add to every `contributors.txt` a mention of the URL `https://github.com/mdn/wiki-revision-history`.

**Comment by peterbe** [comment]
This as been done: https://github.com/mdn/wiki-revision-history
