### ISSUE TITLE
Missing 🔽 in BCD in mobile

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1757]
There is no visual way to distinguish witch rows are clickable and witch not.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

https://whatismybrowser.com/w/844XCWE

![Screenshot_20210120-013812.png](https://user-images.githubusercontent.com/44380480/105110990-2e2f3b00-5ac0-11eb-9493-812fc7baf289.png)

**Comment by peterbe** [comment]
Use https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty#Browser_compatibility instead for this issue. 
When you're in responsive design mode the 9, 5.1, and 6 are clickable to expand, but that's impossible to know unless you click on them to find out. 
When you're *not* in responsive design, it's obvious thanks to the little down caret arrows
<img width="855" alt="Screen Shot 2020-11-18 at 10 11 00 AM" src="https://user-images.githubusercontent.com/26739/99548246-6dd58b80-2986-11eb-8790-184a3ee38289.png">
Curious why they would disappear in responsive mode.

**Comment by mattiapontonio** [comment]
Move only the details (the expandible content) in another table.
In this case 3 records.
🧨

**Comment by mattiapontonio** [comment]
RIF: https://github.com/mdn/yari/issues/1761

**Comment by mattiapontonio** [comment]
> Curious why they would disappear in responsive mode.

We should at least _re-show_ them...

**Comment by peterbe** [comment]
Still an issue.

**Comment by mattiapontonio** [comment]
Nope.
You have to remove this effort in event listeners from the table.
