### ISSUE TITLE
Remove the icon in the sidebar properties navigation

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1758]
https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty
 https://whatismybrowser.com/w/HMDY77K

note
I didnt inspect but i think using 2 `span` in 1 `div` works.

**Comment by peterbe** [comment]
What do you mean? Can you take a screenshot and explain more fully and carefully what the actual problem is. Let's not worry about solutions yet. And the screenshots need to relate to the right and relevant URL.

**Comment by mattiapontonio** [comment]
I can't upload from my app...
I don't understand why the URL is wrong every time... I'm talking about YARI

So see in the bottom of the page
Object.prototype.__defineGetter__() is too long and breacks the line.

**Comment by peterbe** [comment]
<img width="415" alt="Screen Shot 2020-11-18 at 12 36 33 PM" src="https://user-images.githubusercontent.com/26739/99566285-b39c4f00-299a-11eb-922a-3b0e33bf6f74.png">
This is what I see on that page. What's wrong? If the word is too long for its container, how else would you display it if not onto the next line.

**Comment by mattiapontonio** [comment]
![image](https://user-images.githubusercontent.com/44380480/99581722-6ee7d680-29e1-11eb-967c-534fb65d1dbb.png)
![image](https://user-images.githubusercontent.com/44380480/99581935-b2dadb80-29e1-11eb-95b6-2552dc2415b8.png)

### Rapid solution
Should need discussion. It is `code` or is an anchor that looks like code?
![image](https://user-images.githubusercontent.com/44380480/99583233-7c05c500-29e3-11eb-9093-6c73d2a267c4.png)

**Comment by peterbe** [comment]
Good work! I think that looks better already. How, putting in overrides into the devtools is one thing, making a PR against the SCSS files is another. But I think you can figure it out.

**Comment by mattiapontonio** [comment]
Yes, it's true. However if I develop I am less free to talk and in some cases if I see an "error" like this I prefer to open an issue. And if I develop with an issue not open to me, I am more focused. At the moment they think so. However, you can do as you please of course. In any case it is not in place. I don't know if by the time if I have the project installed locally I will be in this area and I will solve it. I'm not downloading yet. I think opening issues is still a contribution, I don't expect them to be resolved by force, I just try to spark discussion. Not Ok for me, one random looking design 🙂.

**Comment by mattiapontonio** [comment]
Intuitively it could be a matter of HTML only, however, unless inheriting some CSS properties. for what I said that 2 spans are in line by default, only there is SVG that must be forced as dimensions 🤔

**Comment by mattiapontonio** [comment]
Or you can put the icon after which is unusual but not illegal 🤔

**Comment by schalkneethling** [comment]
I believe the issue here is that we do not want to break to a new line immediately after the icon(s). The words themselves should break as appropriate but we should keep the icons on the same line as the text.

Thanks, @mattiapontonio

**Comment by mattiapontonio** [comment]
> I believe the issue here is that we do not want to break to a new line immediately after the icon(s). The words themselves should break as appropriate but we should keep the icons on the same line as the text.
> 
> Thanks, @mattiapontonio 

Yes 👍
But this mapping 

|[link]()|👍|
|[link]()|👎|

Could be moved somewhere.
