### ISSUE TITLE
Show support as 🟩, 🟨, or 🟥

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1761]
I also suggest to move the `supported data` from `background` ti a `green bullet` so It Is more flexible and It can be moved around and It Is as the same level of the texts (the name of the browser and the version).

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/issues/1747#issuecomment-729701307_

**Comment by peterbe** [comment]
Can you please try to rewrite the issue title to something we can all understand?

**Comment by mattiapontonio** [comment]
It's all suggestions that comes from "mantainability" experience dealing with relational databases.

**Comment by peterbe** [comment]
Can you explain with a code example?

**Comment by mattiapontonio** [comment]
It's not easy, it's complex. It also depends on how data are modelled from BE or Web Service and comes.
Anyway my notes are:

- Use another table
- Do not use hided content
- Do not use ***** because is hard to read 
- True may become a red|green bullet or some emoji, in all tables...

## Example
|Property|Browser|Version|Note|Supported
|--|--|--|--|--|
|`flex-shrink`|Firefox|20|Since Firefox 28, multi-line flexbox is supported.| ✅
|`flex-shrink`|Firefox|20|Before Firefox 32, Firefox wasn't able to animate values starting or stopping at  `0`.| 🔴
|`flex-shrink`|Firefox|49|**-X-**  prefix| ✅
|...|...|...|...|...

**Comment by peterbe** [comment]
So what you're suggesting is a, more or less, rewrite of the BCD table? Thanks for the suggestion and feedback!
If you want to try to write a pull request (it's React + TypeScript) it's really not that hard. But it might be worth doing some more research first and sketch some prototype and show them around to gather feedback.

**Comment by mattiapontonio** [comment]
I don't want to rewrite the BCD table. I want to move non-tabular data from one cell of one table to another table. This would automatically solve many layout and pagination issues. I have not seen the data as it is modeled but just looking at the front end it is evident that there is no good alignment with the backend. I don't want to focus on code, in this case I speak as a "tester". Of course mine is not a claim, I simply review problems faced in other projects. How does the data arrive? Can I have a JSON or a table? Maybe even there there may be issues I don't know. React is good but objects and arrays always remain the same, unfortunately or fortunately ...
In my opinion, one must always remember whether information or interaction comes first. In this case, I prefer information.

![image](https://user-images.githubusercontent.com/44380480/99612043-234f2000-2a15-11eb-9c67-732ca895887a.png)

**Comment by mattiapontonio** [comment]
How does the table look without custom style. Mostly unusable, especially the hidden part.
![image](https://user-images.githubusercontent.com/44380480/99864043-7655de00-2ba1-11eb-8f1a-dde86cfbc2b5.png)
![image](https://user-images.githubusercontent.com/44380480/99864067-9d141480-2ba1-11eb-9a1c-6ba144edc33d.png)

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/issues/2502

**Comment by Ryuno-Ki** [comment]
Keep in mind, that there are colour blind people (e.g. red-green colour-blindness effects one in 14 men, statistically speaking).
Thus, it's best practice to not carry meaning with colour _alone_.

**Comment by mattiapontonio** [comment]
@Ryuno-Ki i agree but there Is not this 🟩 like this 🆗 with _true_ inside.

**Comment by Ryuno-Ki** [comment]
When using Emojis, you [need to have the users have a font](https://www.smashingmagazine.com/2016/11/character-sets-encoding-emoji/) which is able to show that Unicode codepoint.

Elder Androids might show a gray [] otherwise. (talking from experience here)
Perhaps worth to take a look into Analytics, which devices are used. There are a wide range of outdated Android devices out in the wild :-(

**Comment by mattiapontonio** [comment]
@Ryuno-Ki yes We definitely Need a Component so a custom class that owns a `text` and a `color` 👍
