### ISSUE TITLE
bash: yarn: command not found

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1785]
Hello, I know it's off topic but I don't know why I can't install yarn ...
Is it possible to use npm or could there be other issues?

I just tried from readme to clone the project.
![image](https://user-images.githubusercontent.com/44380480/99711030-900ffc00-2aa1-11eb-8f92-58a12ff475a7.png)
![image](https://user-images.githubusercontent.com/44380480/99711113-ad44ca80-2aa1-11eb-89b0-0bd135ec2b34.png)

**Comment by peterbe** [comment]
The [README](https://github.com/mdn/yari#readme) has a link. 
To https://classic.yarnpkg.com/en/docs/install
Seems you have installed it but I can't help figure out how to get it to work on Windows in VS Code. Perhaps try other forums like VS Code support. Or Yarn support.
