### ISSUE TITLE
Styling stretches inline images instead of scaling them

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1798]
This comes from https://github.com/mdn/yari/issues/1734#issuecomment-731337332

If you have
```html
<p>
<img alt="The default styles used by a browser" src="https://mdn.mozillademos.org/files/16493/html-example.png" style="border: 1px solid #cccccc">
</p>
```
It looks good:
<img width="812" alt="Screen Shot 2020-11-20 at 1 29 54 PM" src="https://user-images.githubusercontent.com/26739/99836703-7c61a580-2b34-11eb-8b68-55e1a30285ca.png">
on http://localhost:3000/en-US/docs/Learn/CSS/First_steps/What_is_CSS

But if you correctly set the `image` width and `height` attributes:
```html
<p>
<img height="594" width="1385"
alt="The default styles used by a browser" src="https://mdn.mozillademos.org/files/16493/html-example.png" style="border: 1px solid #cccccc"
>
</p>
```
then this happens:

<img width="758" alt="Screen Shot 2020-11-20 at 1 31 14 PM" src="https://user-images.githubusercontent.com/26739/99836832-aca94400-2b34-11eb-9bd9-62a6954f92fe.png">

Having the `height` set is good because it means the browser doesn't need to shift all the stuff below it as the image loads. This causes CLS (Cumulative Layout Shift) which is bad for our Web Perf metrics which could affect our SEO. And just generally make people less happy consuming the content.

Is there not a way to do the CSS so that images are allowed to have their correct size set but "scale" it so it displays as well as it can?

**Comment by chrisdavidmills** [comment]
Looks like the dimensions are not being set correctly, so that the aspect ratio is incorrect.

If you only set the width, the height is usually adjusted proportionately so the aspect ratio is maintained, and I think it still gives you a box to help avoid CLS. Would that work?

**Comment by peterbe** [comment]
No, the dimensions are set correct in terms of their ratio. 
<img width="1425" alt="Screen Shot 2020-11-20 at 1 49 50 PM" src="https://user-images.githubusercontent.com/26739/99838521-4540c380-2b37-11eb-9eda-0143016ed32f.png">

It [says](https://web.dev/optimize-cls/#images-without-dimensions) you should set both `width` and `height` to optimize for CLS.

**Comment by mattiapontonio** [comment]
Hello, sorry for the intrusion but this is a problem that I happened to face. Personally after some investigation I would have come to the conclusion that the smartest way is to set the height and width on the Backend. Ideally a microservice for the image that returns an object in different dimensions and the same dimensions in node that can be bound on the template. Instead in the case of SSR and without services you could use Node to request the image (or possibly only the HEAD if this information is in the HEAD), obtain the dimensions and perform the calculation. How to get 100% width? Also fix the dimensions of the column 🤔 Does what I said have anything to do with the state of the art of the project? I do not know then the question of scalability as it is impacted .... I have mine.

**Comment by schalkneethling** [comment]
I agree with @chrisdavidmills. Set the width, let the browser maintain the aspect ratio as the viewport resizes.

**Comment by mattiapontonio** [comment]
- Something even PHP for the concept.

https://web.dev/cls/
https://www.npmjs.com/package/image-size
https://www.npmjs.com/package/image-size
https://css-tricks.com/snippets/php/get-widthheight-of-image/

## others not good solution
Wrap images in a fixed dimensioni flex container...

**Comment by schalkneethling** [comment]
Hey all,

I commented on this without really digging in. I'm ashamed 😞 

I now did. So, to fix this and make it so this is a non-issue in terms of the visual display takes one line of CSS. Currently, our reset does this:

```
img {
  display: block;
  max-width: 100%;
}
```

With only that, having for example the following in HTML will result in an image that is not proportionately scaled:

```
<img alt="The default styles used by a browser" src="https://mdn.mozillademos.org/files/16493/html-example.png" width="1385" height="594">
```

Simply adding `height: auto` to the previously mentioned rule resolves the problem. This will be added in the next release of minimalist. In terms of best practice, I would say:

1. The absolute ideal is to set both the width _and_ height
2. If for whatever reason we can only set one, set the width

Phew, no I feel better 😄

**Comment by mattiapontonio** [comment]
The thing is CLS, until the image Is loaded if `auto` the `height` is `0`.

**Comment by Ryuno-Ki** [comment]
I wonder, whether an `img` could use a `min-height`? But then again, what value should be chosen until the image is loaded …

**Comment by mattiapontonio** [comment]
Asked in content
https://github.com/mdn/sprints/issues/3925

**Comment by schalkneethling** [comment]
With https://github.com/mdn/yari/pull/1860, images that set their `width` and/or `height` attributes will be scaled appropriately. If an image uses inline-style to set these values, that is a flaw and we should allow it to look weird so it will be fixed.

If we can do this in an automated fashion, that is great. If not, this will be resolved over time and should be prevented from happening in the future. As mentioned in https://github.com/mdn/yari/issues/1799#issuecomment-734794068, inline styles will override whatever we do unless we use `!important` and we are not going to do that.

**Comment by peterbe** [comment]
I love it! Thanks to everyone involved!
Now we have the ideal solution. 
If you set `height="594" width="1385"` on the `<img` tag there, you get this:
<img width="1168" alt="Screen Shot 2020-11-30 at 10 38 26 AM" src="https://user-images.githubusercontent.com/26739/100630277-57b9ba80-32f8-11eb-9b57-baae7073394f.png">
It's hard to tell but thanks to the `height` tag on the `<img` the browser doesn't do any layout shift whilst waiting for the image. 

Now I need to write that piece of code that opens the image, gets its `width` and `height` and uses the Cheerio instance to set it based on the binary image size (there's a node lib for that).
