### ISSUE TITLE
Images with width/height set in inline style look wonky

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1799]
I'm moving the discussion here: https://github.com/mdn/yari/issues/1798 about scales. 

Besides, in `en-US` alone there are 1,921 images that have their width and height set as inline style attributes. 
```
▶ rg '<img'  | rg width | rg height | wc -l
    1921
```
are all of these going to look "wonky" in Yari when we launch?

Either way, let's move this to a new issue too.

_Originally posted by @peterbe in https://github.com/mdn/yari/issues/1734#issuecomment-731340420_

**Comment by peterbe** [comment]
Basically, any image that is large'ish might look scaled in only one dimension. 
Random first one I found: http://localhost:3000/en-us/docs/Learn/CSS/CSS_layout/Position_skills
<img width="749" alt="Screen Shot 2020-11-20 at 1 37 28 PM" src="https://user-images.githubusercontent.com/26739/99837406-8afc8c80-2b35-11eb-8ac9-81234fd8b891.png">

**Comment by peterbe** [comment]
I'm a bit disappointed that the CSS is scaling the images in only 1 dimension but if that's the best that can be done with CSS, one thing we can certainly attempt is to correct the `img` tags with Cheerio when we render them. But that's probably something we need to do with the rendered HTML too that we import. 

In fact, I think it might be a smart idea to write a Cheerio thing that turns:
```html
<img src="png" style="what:ever; width: 123px; height: 235px">
```
into
```html
<img src="png" style="what:ever" width="123" height="235">
```
but then you have to take on the risk of parsing CSS which is not trivial at scale.

**Comment by peterbe** [comment]
Can we not just learn and copy from Kuma how they did it?

**Comment by schalkneethling** [comment]
> Random first one I found: http://localhost:3000/en-us/docs/Learn/CSS/CSS_layout/Position_skills

This one actually has inline-style as opposed to setting its `width` and `height` attributes:

```
<img alt="The green box is at the top right of a container with a grey border." 
src="https://mdn.mozillademos.org/files/17077/position-task1.png" style="height: 661px; width: 1033px;" data-flaw="image1">
```

tested it with the following markup post https://github.com/mdn/yari/pull/1860, and it now displays correctly:

```
<img alt="The green box is at the top right of a container with a grey border." width="1033" height="661" src="https://mdn.mozillademos.org/files/17077/position-task1.png" data-flaw="image1" />
```

**Comment by schalkneethling** [comment]
> Can we not just learn and copy from Kuma how they did it?

Inline style is always going to override what we do in external CSS or even in-page CSS unless we use `!important` and we are not going to go down that road 😄

**Comment by schalkneethling** [comment]
I am going to close this one as well. If an image's `width` and `height` are being set with inline CSS, this is an error and needs to be resolved. If the appropriate `width` and `height` attributes are used, images will display correctly, and it will avoid cumulative layout shift.

**Comment by mattiapontonio** [comment]
> I am going to close this one as well. If an image's `width` and `height` are being set with inline CSS, this is an error and needs to be resolved. If the appropriate `width` and `height` attributes are used, images will display correctly, and it will avoid cumulative layout shift.

Well but I'm not sure about setting mannualy. Something coded should exists.
