### ISSUE TITLE
Doc_status links must be removed

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1800]
Doc_status is no more once we land Yari.
<img width="747" alt="Screen Shot 2020-11-20 at 7 01 52 PM" src="https://user-images.githubusercontent.com/26739/99861089-0d4f7580-2b63-11eb-911c-3b700313d182.png">
I suspect it just needs to be removed from the MDNSidebar macro.

**Comment by peterbe** [comment]
@tannerdolby  Is this an issue you'd like to take a stab at? You need to figure out which Kumascript macro that is used on that page and then find the relevant `.ejs` file and then delete the link things related to `Doc_status`.

**Comment by tannerdolby** [comment]
@peterbe Yeah I'll take a stab at this. Thanks for letting me know. I will have an update on removing `Doc_status` links from the sidebar within the next few days.

**Comment by tannerdolby** [comment]
Update: You were correct, the macro just needed to be removed from `MDNSidebar.ejs`. After removing the following list item the sidebar no longer has a dropdown item for "Doc status by topic".

```
<li class="toggle">
      <details>
          <summary><%=text['Doc_status_by_topic']%></summary>
          <ol>
            <li><a href="<%=baseURL%>Doc_status"><%=text['Doc_status_by_topic']%></a></li>
            <li><a href="<%=baseURL%>Doc_status/Overview"><%=text['Are_we_documented_yet']%></a></li>
          </ol>
      </details>
</li>
```

Note: I did notice `Doc_status` is located within two files inside the `kumascript/macros/` directory:
1. `CanvasSidebar.ejs`
2. `DocStatusQuickLinks.ejs`

Would you like the references to `Doc_status` removed or just leave them be for now?

**Comment by tannerdolby** [comment]
Third times the charm. Got my GPG key setup and finally provided a signed commit. This was my first time setting up GPG keys so I apologize for the two closed PRs before this one.

**Comment by peterbe** [comment]
> Would you like the references to `Doc_status` removed or just leave them be for now?

Wipe off the face of the earth.

**Comment by tannerdolby** [comment]
Updated my PR with the requested changes.
