### ISSUE TITLE
✂️ cropped logo in edit profile page

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1802]
The logo is cropped when You are logged in in the profile page from mobile.

https://developer.mozilla.org/en-US/profiles/MattiaPontonio/edit (use Your profile).

**Comment by akhil-gautam** [comment]
@mattiapontonio I am able to fix it on this link https://developer.allizom.org/en-US/profiles/MattiaPontonio/edit in the browser itself but I am not sure which repository does the above application belong to. Please let me know.

**Comment by akhil-gautam** [comment]
https://github.com/mdn/kuma/issues/7609
@mattiapontonio  I am able to grab the thread related to this but do you find it happening in `Yari` also?

**Comment by mattiapontonio** [comment]
Yes in YARI. `allizom` is YARI.
Here a screenshot from my profile.
You should register and login by Your self, It might appens even on your profile.

![Screenshot_20201202-175528.png](https://user-images.githubusercontent.com/44380480/100904914-cc8f1f00-34c7-11eb-8bc0-862bd4f7ea16.png)

**Comment by peterbe** [comment]
I know this is confusing but the way the CDN is set up, 
Any request to https://developer.allizom.org/*/profiles/* goes to Kuma actually. 
That's where the view/edit profile still exists. 
We'll port these pages to Yari too some day.

**Comment by mattiapontonio** [comment]
Still an issue in the _Kuma header_

![Screenshot_20210120-015116.png](https://user-images.githubusercontent.com/44380480/105111817-09d45e00-5ac2-11eb-9bc8-a1fbbab0623c.png)
![Screenshot_20210120-015050.png](https://user-images.githubusercontent.com/44380480/105111824-0c36b800-5ac2-11eb-8930-f6515295d7c6.png)
