### ISSUE TITLE
Page not found from home screen

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1806]
# Steps to reproduce
- https://developer.allizom.org/en-US/
- Add to home screen (I'm in Chrome Android App)
- Open from the icon in the home screen
- I see the home page in italian, like my language preference
- Visit **Tecnologie web**

Page not found

Sorry, the page /it/docs/Web could not be found.

---
From Chrome the browser It works.
Using Firefox Android App even from the home screen it works but It Is in english by default

![Screenshot_20201121-203013](https://user-images.githubusercontent.com/44380480/99885893-6d641b80-2c38-11eb-8eb3-6ae19147c27f.png)

**Comment by peterbe** [comment]
We currently don't build the other locales on stage. 
That's why https://developer.allizom.org/it/docs/Web is 404. 
Once we build the translated content too, this problem will go away. 

I don't think it has anything to do with home screen apps.
