### ISSUE TITLE
Multiline <code>

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1808]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/code

> To represent multiple lines of code, wrap the \<code\> element within a \<pre\> element. The \<code\> element by itself only represents a single phrase of code or line of code.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/span

> The HTML <span> element is a generic inline container for phrasing content

## Actually

```html
<pre class="brush: js notranslate">
 <code>
  <span class="token"></span>
  <span class="token"></span>
</code>
</pre>
```

## Example page
https://developer.allizom.org/en-US/docs/Web/API/HTMLSelectElement

![image](https://user-images.githubusercontent.com/44380480/99874507-d91e9800-2be8-11eb-839c-bd4cd3de028a.png)

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/issues/1810

**Comment by peterbe** [comment]
This is how PrismJS works and when we dug into it we learned it's like that for good reasons.
