### ISSUE TITLE
anchors

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1816]
Hello, I saw that the links to the sections of the page actually point to headers. 
If they pointed to **document fragments** on the page, the padding of the section with respect to the top of the window would be preserved. 
I think the best thing is to have the headings **siblings** with the anchors and both children of the section they reference. 
Some layout issues could be solved by placing the anchors absolutely on right top of the section or at the end of the section.

## Example

```html
<section id="section">
 <h1>Section</h1>
 <a href="#section">Section</a>
</section>
```

- [a](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a)
- [DocumentFragment](https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment)
- [hash](https://developer.mozilla.org/en-US/docs/Web/API/URL/hash)

view-source:http://developer.allizom.org/en-US/docs/Web/API/Element/requestFullScreen

![Screenshot_20201122-084631](https://user-images.githubusercontent.com/44380480/99898378-586fa280-2ca1-11eb-8c15-8cfc31b19041.png)

**Comment by peterbe** [comment]
What's the problem? If you're referring to the top of the viewpoint being positioned imperfectly, it can be solved with CSS instead of moving the `id="AnchorID"`.

**Comment by mattiapontonio** [comment]
Solving with CSS is not perfectly correct. The real beginning of a section is the border of a section, the blue rectangle that appears on the inspector.
