### ISSUE TITLE
Strangely empty looking BCD table

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#182]
<img width="1499" alt="Screen Shot 2019-10-15 at 9 31 08 AM" src="https://user-images.githubusercontent.com/26739/66836035-9c389a00-ef2e-11e9-880b-c741d48895f4.png">

That page was composed from [a project](https://docs.google.com/document/d/1yNJCNJ2iv4H7f8E0OcJlLxDDrP90Pv6os85yMAnX0mI/edit#heading=h.bndl33yzt92l) that pulls in all old Kuma content and using some reverse engineering tries to make .json files similar to how `build-json` works. 

The JSON for this page is as follows:
```json
      {
        "type": "browser_compatibility",
        "value": {
          "resolve": {
            "__compat": {
              "mdn_url": "https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/dns/resolve",
              "support": {
                "chrome": {
                  "version_added": false
                },
                "edge": {
                  "version_added": false
                },
                "firefox": {
                  "version_added": "60"
                },
                "firefox_android": {
                  "version_added": "60"
                },
                "opera": {
                  "version_added": false
                }
              }
            }
          }
        }
      }
```

https://gist.github.com/peterbe/91d6a71a7d0f2b794dcdccfcc0caac64

It seems like there's should at least be 1 extra row.

**Comment by peterbe** [comment]
@joedarc Is that something you might be able to understand. There aren't instructions yet for how to get to this JSON but you can hijack any of the `stumptown-content/packaged/**/*.json` files and just override it with this and then load it in the browser to see what the output is visually.

**Comment by joedarc** [comment]
@peterbe If i get some time later today I'll take a look at this. 👍

**Comment by joedarc** [comment]
@peterbe I got it to render, it looks like it had an extra key in the JSON that was unexpected. The other blocks don't have the `resolve` key wrapping `__compat`. If i had to wager a guess..this is something newer in stumptown-content that will wrap all of the in the actual name of the element so that we don't have to use the `mdn_url` to get the name? 

Either way to render in stumptown-renderer as-is the JSON should look like:

```
{
  "type": "browser_compatibility",
  "value": {
    "__compat": {
      "mdn_url": "https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/dns/resolve",
      "support": {
        "chrome": {
          "version_added": false
        },
        "edge": {
          "version_added": false
        },
        "firefox": {
          "version_added": "60"
        },
        "firefox_android": {
          "version_added": "60"
        },
        "opera": {
          "version_added": false
        }
      },
      "status": {
        "experimental": false,
        "standard_track": true,
        "deprecated": false
      }
    }
  }
}
```

Please note I also had to remove the `resolve` key and add a `status` key for it to render properly.

![Screen Shot 2019-10-15 at 12 12 07 PM](https://user-images.githubusercontent.com/1201062/66849815-98644200-ef45-11e9-991b-0d17ae657ee5.png)

**Comment by joedarc** [comment]
If I'm correct in my guess about stumptown-content, feel free to ping me and I can make the adjustments to the rendering of the BCD table to accept the newer format when the time comes.

**Comment by peterbe** [comment]
I should give some important context.

I'm working on a prototype where we take all the structured stuff that `stumptown-content/scripts/build-json/build-json.js` produces and puts into `packaged` AND this other script that I'm working on. What that script does is that it scrapes ALL content from Kuma. It finds the HTML for each page and looks at the use of `{{Compat(ARGS)}}` and then manually calls...
```javascript
const { packageBCD } = require("../build-json/resolve-bcd");

...

        const bcdData = packageBCD(compat);
        return {
            type: "browser_compatibility",
            value: bcdData
        };
```
So there's definitely an opportunity to do something with that `bcdData` struct. 
However, it would be nice to not have to but then we're dragging in fixes for legacy into the stumptown-renderer's BCD ingredient component (that you wrote @joedarc )

Perhaps @Elchi3 can weigh in?

**Comment by peterbe** [comment]
Too old now.
