### ISSUE TITLE
html body main article (picture)? img

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1843]
The thing is CLS: until the `img` is loaded if `auto` the `height` is `0`.

- [picture](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture)
- [object-position](https://developer.mozilla.org/en-US/docs/Web/CSS/object-position)
- [object-fit](https://developer.mozilla.org/en-US/docs/Web/CSS/object-fit)

## prevent CLS?
Maybe `picture` should have fixed `height`.

```css
picture {
 width: 100%;
 height: 128px;
}
```

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/issues/1798#issuecomment-732730087_

## Control over the object
Another thing, using `picture` in the future editors should have controls on the `object-` properties.

**Comment by mattiapontonio** [comment]
Another thing, using picture in the future editors should have controls on the `object-` properties.

**Comment by peterbe** [comment]
Can you elaborate and explain how this issue is different from https://github.com/mdn/yari/issues/1498?

**Comment by mattiapontonio** [comment]
They are two different solutions both to avoid CLS. Simply setting the attributes via Node (which I also proposed I remember) could prevent CLS but using picture Instead it could be more modern, extensible and expose more features. It would be necessary to decide on a fixed height of the frame of the images and maybe put a little effort in the style of the frame. There will no longer be a way to fit the image to the frame, but in general the layout will be consistent, responsive and will prevent overflow if images are loaded that are too large. I prefer picture.

**Comment by peterbe** [comment]
If this is about switching to the [`<picture>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) element instead of `<img>`, then update the issue title to be specific about that.

**Comment by mattiapontonio** [comment]
I tryed something like a regex but Is not real code.

**Comment by peterbe** [comment]
What does `<picture><img> ...</picture>` give us that we need?

**Comment by mattiapontonio** [comment]
_Common use cases for <picture>:

Art direction. Cropping or modifying images for different media conditions (for example, loading a simpler version of an image which has too many details, on smaller displays)._

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture

It should solve the stretching problem.
Then other Issues should be addressed in this _modern way for images_.
I even still not experienced too much but seems ok.

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/issues/1498
