### ISSUE TITLE
html body main section h2

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1859]
Another thing that I have been interested in since I started contributing is definitely a full stack issue. 
I have seen that the editors and also the snippets are split using the titles as if they were dividers. 
Now this is very handy on the editing side but in my experience it is wrong if you enter the context of mark-up languages. 
In HTML the grouping is done using the parent elements, not the children as dividers between siblings, if a parent has several groups of children it is advisable to have intermediate parents who group. Now I don't know if it's trivial or wrong or there are solutions that I don't know but having experience in JSON and XML I understand that they have different uses to represent data ... and therefore mixing them scares me. 
In my opinion, on the editing side, we should provide a feature to group and not force to use the titles, the use of titles is already a good SEO practice and can possibly be validated by other means (example warning: you have entered an untitled section).

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/section

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/pull/1811#issuecomment-734199471_

**Comment by mattiapontonio** [comment]
If we wanted to go much further ... there would also be this API that would immediately give the editor a CSS view of what it is doing, the validated content could be posted (as HTML) to the Backend without further computation if not of security. But I still haven't seen it as I imagine it, there is always a Backoffice of some kind even on WordPress ...

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Editable_content

Sorry if I go "free". 🙂

**Comment by mattiapontonio** [comment]
The thing I don't like is using titles as dividers and hooks for anchors. They should be sections. I had seen however and I have not yet seen the API response because I only have one mobile in this period (long history) that even in the snippets the algorithm that generates the pre is based on the titles. At first this thing surprised me but thinking about it I remain in the comfort zone that the container or class or component is one thing while the content or properties or attributes are others. So by imagination the API should either already give you the fact that it is an h3 or give you the raw data and you put it in the title you prefer. It is not up to the frontend to switch which titles are and above all to recreate a DOM that already exists ... So, thinking about it, perhaps we should remove the automatism of the automatic anchors ... I find it difficult to explain in 1 issue ...

**Comment by mattiapontonio** [comment]
It is certainly certain that there can be a much more academic and clear way to express my concept but at the moment it does not occur to me. If you want to close the issue it's not a problem for me.

**Comment by mattiapontonio** [comment]
All this leads to the fact that on the editing side a feature would be needed to dissect beyond the titles.

**Comment by peterbe** [comment]
It would be nice if instead of a `index.html` there's a `001-introduction.html` and `002-examples.html` and `003-seealso.html` etc. But there isn't and there's significant advantages with it all being in one simple file. 
We hope one day to switch from HTML to Markdown (or something similar) and there it's a bit easier because you're not even allowed to put in arbitrary block tags around things. 

All sides have pros and cons. But it's a huge element of complication when you have legacy. If I could start from absolute scratch tomorrow and not have to worry about any migrations it would be a very different discussion. But that's not the case. MDN is 15 years old and we'll always have to keep that in mind.

**Comment by mattiapontonio** [comment]
Ok. Maybe in the future i Will dig more into the code to be more realistic and specific 👌
