### ISSUE TITLE
Cumulative Layout Shift (CLS)

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1863]
- Is this a issue?
- Is it tested?
- How to test?

## Related issues

- https://github.com/mdn/yari/issues/1799
- https://github.com/mdn/yari/issues/1798
- https://github.com/mdn/yari/issues/1843

## Resources
- https://developer.mozilla.org/en-US/docs/Web/API/LayoutShift

**Comment by peterbe** [comment]
We know what CLS is and we'll break it down where it's actionable and appropriate.
