### ISSUE TITLE
breadcrumb's > should be out of the :active state of the breadcrumb

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1865]
The Arrow should be out of the Blue rectangle.

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/pull/1864#issuecomment-734832487_

**Comment by akhil-gautam** [comment]
@mattiapontonio Can I pick this issue?

**Comment by mattiapontonio** [comment]
@akhil-gautam 
Certainly, in my ideal world whoever opens does not take charge

**Comment by peterbe** [comment]
> Can I pick this issue?

We don't reserve assignment to outside contributors unless there's an extended previous communication or the contributor has a very long and strong history with the project. 
For now, just make a PR and, honestly, hope that your PR comes in first :)

**Comment by mattiapontonio** [comment]
I didn't understand but ok. I don't think I can assign people on this repository. I will not remember the rules that the platform does not suggest to me but I think there will be no problems.
