### ISSUE TITLE
Switch to break-word instead of break-all for titlebar

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1869]
Noticed the following issue on allizom related to how the text in the titlebar breaks when it no longer fits into the available width:

![demonstrates an awkward text break caused by break-all](https://user-images.githubusercontent.com/10350960/100536031-86676080-3226-11eb-8c2f-4453eeee1bd3.png)

Whoops, 😄 that is not good. `word-break` does a better job

![better word breaks with word-break](https://user-images.githubusercontent.com/10350960/100536051-adbe2d80-3226-11eb-9bcc-81fb6059f3d1.png)

And it still handles those really long titles such as "CanvasRenderingContext2D.globalCompositeOperation"

![Screenshot 2020-11-29 at 09 39 54](https://user-images.githubusercontent.com/10350960/100536082-dba37200-3226-11eb-966e-ca80cd1f1597.png)

**Comment by mattiapontonio** [comment]
In Italy in elementary school we are taught that words must be broken between one syllable and another. I haven't found this thing in CSS yet because knowing syllables has to be complicated.

https://en.wikipedia.org/wiki/Syllabification
