### ISSUE TITLE
in content badge needs slightly darker background color

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1883]
The inline badges displayed in the content but outisde of a table needs a slightly darker background color:

http://localhost:3000/en-US/docs/Web/API/DeviceMotionEventAcceleration#Properties

![Screenshot 2020-11-30 at 10 52 49](https://user-images.githubusercontent.com/10350960/100588305-60ab8b80-32fa-11eb-836d-f5a0ececce19.png)

**Comment by mattiapontonio** [comment]
How about transform this list in a table with 3 colums and X rows?
