### ISSUE TITLE
body's h1 vs article's h1

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1886]
https://github.com/mdn/yari/pull/1884

Should the `h1` of the `body` be the `h1` of the `article` so displayed on top of the right layout column on desktop instead of full `width` on top of the page?

**Comment by schalkneethling** [comment]
> #1884
> 
> Should the `h1` of the `body` be the `h1` of the `article` so displayed on top of the right layout column on desktop instead of full `width` on top of the page?

No. The main title/topic of the document should be marked up as the `h1` element. In the current layout, that means the text displayed in the title bar.

**Comment by mattiapontonio** [comment]
@schalkneethling think the `article` as a `Component` that if not in this type of `document` does not have an `h1` so It depends on it.
