### ISSUE TITLE
Impossible to see what's a link and what isn't in BCD table

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1887]
E.g. http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json
<img width="396" alt="Screen Shot 2020-11-30 at 8 59 54 AM" src="https://user-images.githubusercontent.com/26739/100618900-6c8f5180-32ea-11eb-9906-4d5d8dcd28a6.png">

You can't see which elements are clickable. 
You can find out if you hover the mouse over each and every one since then they light up the background:
<img width="289" alt="Screen Shot 2020-11-30 at 9 00 39 AM" src="https://user-images.githubusercontent.com/26739/100619067-9e081d00-32ea-11eb-871f-9215f73a0af7.png">

**Comment by peterbe** [comment]
I suspect it was https://github.com/mdn/yari/pull/1873 but let's not re-open any existing issues because the issues mentioned before were on more/other specifics.

**Comment by schalkneethling** [comment]
@peterbe Indeed. This is a tricky one to get right. This table is so busy. I was thinking one can add a link icon next to links, but I fear it might add a lot of clutter. This is not ideal either(at all). Still thinking about it.

**Comment by peterbe** [comment]
Underlining 
Here's what it looks like with a 
```css
text-decoration: underline;
text-decoration-skip-ink: none;
```
<img width="334" alt="Screen Shot 2020-11-30 at 9 08 06 AM" src="https://user-images.githubusercontent.com/26739/100619879-b9bff300-32eb-11eb-870f-69267ab49a3a.png">

Here's what it looks like with a 
```css
text-decoration: underline;
```
<img width="285" alt="Screen Shot 2020-11-30 at 9 09 02 AM" src="https://user-images.githubusercontent.com/26739/100620043-f0960900-32eb-11eb-890a-a37812603d81.png">

I think either of them is better. But even better is to apply the consistent blue we use for all hyperlinks:
<img width="436" alt="Screen Shot 2020-11-30 at 9 12 12 AM" src="https://user-images.githubusercontent.com/26739/100620265-36eb6800-32ec-11eb-84a5-7fa5ee0b00bc.png">

But that reminds me, why are `<code>` tags always black? I think it's unfair. Why do plain text gets to have nice blue color and `<code>` doesn't?
Compare:
<img width="470" alt="Screen Shot 2020-11-30 at 9 14 28 AM" src="https://user-images.githubusercontent.com/26739/100620464-75812280-32ec-11eb-94fd-e06e48727465.png">
*Yari*

<img width="652" alt="Screen Shot 2020-11-30 at 9 14 50 AM" src="https://user-images.githubusercontent.com/26739/100620517-82057b00-32ec-11eb-87ba-f9a4c328bf7e.png">
*Kuma*


@ddbeck @Elchi3  Do you have any strong feelings towards any of these screenshots? 


It doesn't help that the font is so large that almost all of these `<code>` tags, in the first column of all the BCD tables, are so large that it almost always has to take up 2-3 lines.

**Comment by Elchi3** [comment]
My preference is the blue color for links like it is on Kuma now.

**Comment by ddbeck** [comment]
Yeah, the blue at minimum. Though I also like the underline on mouseover in Kuma as well.

**Comment by mattiapontonio** [comment]
I like the links blue and underlined, prespaced if I code. I don't mind the gray background on the `code` but still everything on a white background so I would whiten the background of the column. Beyond the aesthetics, legibility is also important and it is a classic to underline the links.

![Screenshot_20201130-173426.png](https://user-images.githubusercontent.com/44380480/100637093-c1ef5100-3332-11eb-95c0-62afd846ba64.png)

**Comment by schalkneethling** [comment]
Sometimes the simplest solution is the best. Here is my new proposal for solving this.

![Screenshot 2020-11-30 at 18 46 41](https://user-images.githubusercontent.com/10350960/100638208-6a55e300-333c-11eb-8f83-4d6c74c55991.png)

**Comment by peterbe** [comment]
Why can't it be treated as regular links in the content? I.e. only blue when not hovered, blue + underline when hovered. 
The highlighting of the whole cell feels out of place. It's something you see sometimes as a technique, in HTML tables, to make see across the whole row. I.e. you hover over one of the cells in the row and the whole row gets a slightly highlighted background. 
But these are hyperlinks inside the cells, they're not clickable cells.

**Comment by mattiapontonio** [comment]
The "pre style" should even come from not `code` tag but specific rules via the `href` 
https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors

**Comment by schalkneethling** [comment]
Thank you for all the feedback everyone!

![Screenshot 2020-11-30 at 20 00 01](https://user-images.githubusercontent.com/10350960/100646387-a4c47d80-3346-11eb-8502-3a3bab81f04e.png)
