### ISSUE TITLE
Use a cookie instead of the Accept-Language header to pick locale

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1889]
If you, today, have a German browser and you visit a page like this: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key 
It has a hyperlink like this:
```html
<a href="/docs/Web/API/KeyboardEvent/key/Key_Values">pre-defined key values</a>.
```
If you click that, the Lambda@Edge will turn that into a 302 redirect to `/de/docs/Web/API/KeyboardEvent/key/Key_Values` (note the injected `/de` in the beginning)

This is bad because:

1. You were reading an English article and suddenly it goes to German
2. That slug might not exist you get a 404 page (which thankfully says "Good News" and shows the way to the English version)

It's not just when you click hyperlinks on our own pages. It's also all the MDN URLs that appear in VS Code tooltips, Devtools, and other links all over the internet that are "locale agnostic".

**Comment by peterbe** [comment]
If only we set a cookie whenever the user uses the language drop-down to **change** language, we can use that instead of [the `Accept-Language` header](https://github.com/mdn/yari/blob/97010cca227b6facf30c5aae9fb4660e14a9c429/deployer/aws-lambda/content-origin-request/index.js#L13-L14).

**Comment by peterbe** [comment]
Note! There are still interesting decisions to be made about potentially rewriting, in build-time, with Cheerio, all the hyperlinks like that so they are more explicit. 
@fiji-flo Made an interesting observation that if you make all internal hyperlinks absolute (e.g. `/en-US/docs/Web/Foo/Bar`) you kinda "get stuck" and there's no hope of going back to the locale you prefer. I'm personally not so sure that's an obvious problem but it definitely points out that it's a non-trivial problem to decide how to deal with these links.

**Comment by peterbe** [comment]
One interesting idea that came to mind, when discussing the concept of ["top 14 locales"](https://docs.google.com/document/d/1Q2ND8XLiOjMgBPL4-xqSeO7FOoIlA5ygTgvJrjCd_D0/edit?disco=AAAAKrIbwy0&usp_dm=true&ts=5fc5d9ef) is that perhaps we should discriminate based on WHAT the locale is when there's no cookie available. 

I.e. if you `curl -H 'accept-language: ja' https://developer.m.o/docs/web/foo` it should 302 redirect to https://developer.m.o/ja/docs/web/foo because that's likely to 200 OK. But if the locale is valid but extremely rare (e.g. sv-SE) we don't assume that we can redirect to https://developer.m.o/sv-SE/docs/web/foo because it's so likely to just 404. 

Only fr, ja, zh-CN have enough "coverage" that you can "assume" that a request for `/docs/web/CSS/thing` is going to work. 
Perhaps we should even consider that! We could the number of documents for all locales and pick which locales we *might* use (if it matches the `Accept-Language`) and instead of using `VALID_LOCALES` we have a separate list like `POPULAR_VALID_LOCALES` :)
So if your `Accept-Language` is Vietnamese (which I know is in `VALID_LOCALES`) we default to `DEFAULT_LOCALE` instead when Lambda tries to redirect from `/docs/Foo` to `/$local/docs/Foo`.

**Comment by peterbe** [comment]
Blocked by https://github.com/mdn/yari/pull/1915

**Comment by escattone** [comment]
See https://github.com/mdn/kuma/pull/7670, https://github.com/mdn/kuma/pull/7673, and https://github.com/mdn/kuma/pull/7674

Works like a charm now!
