### ISSUE TITLE
Notecards should only have an icon if there's a h4

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1908]
This is nice and this is what it should look like when there's an `<h4>` in the notecard:
<img width="772" alt="Screen Shot 2020-12-02 at 10 31 25 AM" src="https://user-images.githubusercontent.com/26739/100894165-32f54c80-348a-11eb-8e99-80f8d9c59ed8.png">

But there are thousands of pages that have note cards that don't have a heading. THen this happens:
<img width="1109" alt="Screen Shot 2020-12-02 at 10 16 50 AM" src="https://user-images.githubusercontent.com/26739/100894218-41436880-348a-11eb-9ba6-2c7471a60b9f.png">

**Comment by schalkneethling** [comment]
Will be handled in https://github.com/mdn/mdn-minimalist/issues/316

**Comment by mattiapontonio** [comment]
This icon may not belong to the title context but to the context of the entire block so it could be managed with a ribbon at the top right or other.

**Comment by schalkneethling** [comment]
Resolved in main.

![Screenshot 2020-12-05 at 21 00 33](https://user-images.githubusercontent.com/10350960/101261055-ee450c00-373c-11eb-8932-068171a78d92.png)
