### ISSUE TITLE
consinstent blue in border color

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1918]
I found this new _blue_ of the `a` very relaxing and I noticed that some `border-color`s are not consinstent.

![Screenshot_20201203-110033.png](https://user-images.githubusercontent.com/44380480/100994663-1c68f700-3557-11eb-8e15-ca69ba9d0b53.png)
![Screenshot_20201203-110106.png](https://user-images.githubusercontent.com/44380480/100994680-21c64180-3557-11eb-9944-24ee8ee86bf3.png)

**Comment by mattiapontonio** [comment]
I know that the snippets comes from another project but should be fine of even them (the _function_ color... etc) be consinstent.

**Comment by schalkneethling** [comment]
Resolved in https://github.com/mdn/mdn-minimalist/pull/369
