### ISSUE TITLE
Bump down size of TOC and Related Topics

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#1919]
With the new link color, content is generally even more readable and with that, I feel that we can safely bump down the font size(a little, from `1rem` to `0.9rem`) of the TOC and the related topics sections on desktop.

The nice thing about this is, the main content is brought a little more into focus and the sidebar overall moves a little more into your visual background. This is how it should be 😸

**Comment by mattiapontonio** [comment]
Instinct is what I don't like. I like the number 1 is more whole. Furthermore, if the dimensions are relative to something, the something should be changed and not the relationship.

**Comment by peterbe** [comment]
I disagree. With the `<h1>` and the `<h2>`s in the content are so huge as they are, It would be weird if the `<h2>` and `<h4>` in the sidebar is much smaller. 

On that note, if you ask me, the "Jump to section" and the "Related Topics" look like they're of different size. Could it be because one is `h2` and one is `h4`?

**Comment by schalkneethling** [comment]
> I disagree. With the `<h1>` and the `<h2>`s in the content are so huge as they are, It would be weird if the `<h2>` and `<h4>` in the sidebar is much smaller.
> 
> On that note, if you ask me, the "Jump to section" and the "Related Topics" look like they're of different size. Could it be because one is `h2` and one is `h4`?

The heading sizes will not change, only the links. After experimenting I decided to only change the size of the links under "Related topics"

## Before

![Screenshot 2020-12-04 at 09 51 56](https://user-images.githubusercontent.com/10350960/101136944-b8a60300-3616-11eb-8ab5-65a4ba55c3d6.png)

## After

![Screenshot 2020-12-04 at 09 55 41](https://user-images.githubusercontent.com/10350960/101137112-fb67db00-3616-11eb-9309-9f453ddcfb05.png)
