### ISSUE TITLE
this cells in mobile are "not aligned"

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1922]
The gray cells looks different by others

![Screenshot_20201204-162151.png](https://user-images.githubusercontent.com/44380480/101181161-d9894b00-364c-11eb-800b-40944f6e6538.png)

**Comment by mattiapontonio** [comment]
Yeah
Now looks bigger but better than before 👍

![Screenshot_20210111-150152.png](https://user-images.githubusercontent.com/44380480/104191613-0126bc80-541e-11eb-8d5f-d2abcb58f691.png)

**Comment by schalkneethling** [comment]
Duplicate of https://github.com/mdn/yari/issues/1940
