### ISSUE TITLE
Flash of Unstyled Text | FOUT

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1924]
It happens that i see the font flickering.

**Comment by peterbe** [comment]
We use `font-display: swap` and that's why you get FOUT. If you wanna have custom web fonts, there are always problems like this. A possible solution is to not use swap if you have cookie that indicates that you've loaded it before. Definitely something for the far future to worry about.

**Comment by mattiapontonio** [comment]
https://www.freecodecamp.org/news/web-fonts-in-2018-f191a48367e8/
? Preloading?

**Comment by peterbe** [comment]
See view-source:https://developer.allizom.org/en-US/docs/Web/HTML/Preloading_content
The woff2 fonts are already preloaded. But the browser is only human. Web fonts is a complex topic and I think the solution we have in place is pretty decent, assuming we're going to keep having a custom web font.

**Comment by Ryuno-Ki** [comment]
In case this wants to be considered post-launch: Zach described an interesting approach that is now used on CSS-Tricks:

https://www.zachleat.com/web/css-tricks-web-fonts/

**Comment by mattiapontonio** [comment]
Beyond the characteristics of custom fonts which are certainly of editorial value, I am focused on solving the problem of having what the browser needs, therefore on a problem of loading times and events. Now, if there is no native solution to communicate with the browser and instruct it to render only after it has loaded the font, I think that a global loader that hides the page until the load event could be useful. I don't like this very much because I have learned more or less how a browser works just because it gave me problems and I saw them gradually but if this were a shared solution (as I see it is implemented both in Web app and in native applications) it could be reason for discussion and effort. The link solution does not convince me too much in the sense that the article does not go to the point.

https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event

**Comment by Ryuno-Ki** [comment]
As far as I understood that article, you could use [`FontFace.load()`](https://developer.mozilla.org/en-US/docs/Web/API/FontFace/load) as an indicator when a font is completely loaded.

**Comment by peterbe** [comment]
Pardon my ignorance but we're doing pretty much what Zach recommends in that article. Except we don't go through the trouble of breaking up our woff fonts into two files (all and optimized) for the two-stage loading. 
So perhaps we could save a couple of bytes by running `pyftsubset` to make a reduced first-stage font that is slightly smaller. But I would argue this definitely elevates the complexity of the system bit. You have to draw the line somewhere.

**Comment by mattiapontonio** [comment]
I see this class but the problem despite of the methods Is what before?

- White?
- A loader?
- Ideally but not possibile a perfectly rendered page?
- A millisecond of a designer-not-friendly page

💭💭💭

**Comment by Ryuno-Ki** [comment]
@peterbe Great to hear!

@mattiapontonio Well, the „flash” happens mainly if the features of the font vary massively (which causes a reflow and thus layout shift). So if you pick a system font that has a similar x-length and line-height, the difference shouldn't be too much. You could trigger the swap via a `class` that is added on resolution of FontFace.load() that undos the changes.

But I'm more of a developer than a designer.

**Comment by mattiapontonio** [comment]
@Ryuno-Ki I semi-agree (as a developer that want to focus on tables and data structures with default font family like Arial) but here where I am that Is the GitHub Android App this nice Microsoft font Is ready when i see It and It Is a good experience 🙂🤷🏻‍♂️
