### ISSUE TITLE
Some images still get stretched

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1927]
Compare https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector/Cookies and http://localhost:3000/en-US/docs/Tools/Storage_Inspector/Cookies#Context_menu
The HTML is:
```html
<p>
<img alt="" src="https://mdn.mozillademos.org/files/16811/cookie_table_widget_context.png" 
  style="border: 1px solid black; display: block; height: 250px; margin-left: auto; margin-right: auto; width: 924px;" data-flaw="image1" loading="lazy">
</p>
```
and there's lots of these. I don't know what's up with all the other stuff in that inline things but the width and height numbers are correct. The PNG *is* 924x250. 

If we write that code that injects `width="XXX" height="YYY"` into the `<img>` tag, the image is still stretched incorrectly.

**Comment by mattiapontonio** [comment]
I think the best thing is to use picture so you stay in the Front End area

**Comment by schalkneethling** [comment]
![Screenshot 2020-12-12 at 18 55 34](https://user-images.githubusercontent.com/10350960/101989825-a0d01e00-3cab-11eb-8eaf-6cdfac6be520.png)

I don't know. If I remove the inline style and replace it with `width` and `height` attributes, it looks fine to me.

**Comment by mattiapontonio** [comment]
![Screenshot_20201212-175927.png](https://user-images.githubusercontent.com/44380480/101989913-cd803780-3ca3-11eb-8404-6b538a45d481.png)

Still stretched from Firefox mobile for Android.
