### ISSUE TITLE
Preloading content with rel="preload"

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1939]
Should be good to `preload` images present in a page in the `<head>`?

#### related
- https://github.com/mdn/yari/issues/1927
- https://github.com/mdn/yari/issues/1843
- https://github.com/mdn/yari/issues/1924
- https://github.com/mdn/yari/issues/1814

#### references
- https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content

#### why
- performance...
- tackle context management of both `head` and `body main article`?...

**Comment by peterbe** [comment]
That assumes that people will always scroll down to eventually consume the images, but that's far from a guarantee. 

By instead *not* loading images at all (e.g. `loading="lazy"`) there's less that needs to be done when you open the page which is a good web performance pattern. But you could argue that if they've stayed on the page for a certain amount of time, it's a big chance they'll scroll down and if they do it would be nice to have the images preloaded. 

I don't think there's a great use case for preloading images today. We can revisit this in the future when there's a specific problem to be solved.
