### ISSUE TITLE
BCD *️⃣ causes not aligned cells

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1940]
![Screenshot_20201204-161655.png](https://user-images.githubusercontent.com/44380480/101180815-59fb7c00-364c-11eb-8dc2-ec636762febf.png)

**Comment by peterbe** [comment]
URL?

**Comment by mattiapontonio** [comment]
I can't refind the original URL.
I found this 
https://developer.allizom.org/en-US/docs/Web/API/Element/requestFullScreen

with asteriscs + a strange string "-X"

![Screenshot_20201204-163232.png](https://user-images.githubusercontent.com/44380480/101183438-d04dad80-364f-11eb-8e9d-73f9a08d7338.png)

**Comment by mattiapontonio** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/CanvasGradient

**Comment by mattiapontonio** [comment]
Yeah,

In generale those *️⃣ caueses misalignment in some cases.
