### ISSUE TITLE
table.bc code.version

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1941]
Could version numbers be like code so preformatted because is common to see them in a package.json or something.

![Screenshot_20201204-162325.png](https://user-images.githubusercontent.com/44380480/101181461-31c04d00-364d-11eb-801a-655d875e195c.png)

**Comment by schalkneethling** [comment]
@mattiapontonio I don't believe it will make that much of a difference semantically or visually to justify adding a number of additional DOM nodes, especially on pages with a large, complex BCD table. Thoughts?

Our DOM is already pretty massive on a number of pages which is detrimental for performance.

**Comment by mattiapontonio** [comment]
Of course. 
It's often a trade-off.
🤷🏻‍♂️ I don't want to force some things too much complex, it's a ready made idea that comes some minute ago 🙂
