### ISSUE TITLE
"Read only" badges don't look great

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#1943]
Perhaps this is just personal taste, so take me with a pinch of salt. 

On http://localhost:3000/en-US/docs/Web/API/Document/
<img width="678" alt="Screen Shot 2020-12-04 at 10 49 52 AM" src="https://user-images.githubusercontent.com/26739/101184383-a5973100-361e-11eb-9260-94a8f9e04b38.png">

On https://developer.mozilla.org/en-US/docs/Web/API/Document
<img width="632" alt="Screen Shot 2020-12-04 at 10 51 45 AM" src="https://user-images.githubusercontent.com/26739/101184437-b647a700-361e-11eb-9a14-cbe7940bc1cb.png">

Compared to kuma...,

* there's lacking whitespace between the text and the badge
* the boldness makes it "stand out too much" as if it was an urgent warning.
* it's weird that the badge has rounded corners, but not a border around all of it. When it's not rounded corners it kinda makes more sense that there's just a thick border on the left. 

In general..., 

* it's so weird that sometimes there's an icon and sometimes there a text badge/tag. 
<img width="551" alt="Screen Shot 2020-12-04 at 10 57 45 AM" src="https://user-images.githubusercontent.com/26739/101185186-8c42b480-361f-11eb-91f6-2d0d0713999c.png">
Why isn't read-only an icon? Or why isn't "experimental" or "not-standardized" tax badges/tags?
* I still think they're too large. If a property on some API is read-only, that's not a problem, that's a fact. So it doesn't to alert or freak me out. :)

**Comment by mattiapontonio** [comment]
_Why isn't read-only an icon? Or why isn't "experimental" or "not-standardized" tax badges/tags?_
👍

- text is more talking for a developer that want copy and paste the string
- icons are immediate for a mental parsing but even them should be designed by a designer in SVG to be in a design system

**Comment by bershanskiy** [comment]
> it's so weird that sometimes there's an icon and sometimes there a text badge/tag.

What icon should represent "Read only"? For example, what do you think about a crossed pencil?

**Comment by mattiapontonio** [comment]
From Google
![Screenshot_20201207-002148.png](https://user-images.githubusercontent.com/44380480/101296251-ae585480-3822-11eb-9910-b12f2ba4d172.png)

It would also be interesting from the point of view of structuring the design system and the components to create a list or glossary of icons that may have different declinations such as

| Icon                                     |Badge|
|------------------------------------------|------|
| `<info name="read-only" display="icon" />` |`<info name="read-only" display="badge" />` |

- `name` is enum
- `display` is enum

💭

**Comment by schalkneethling** [comment]
Being addressed as part of the redesign and tracked elsewhere.
