### ISSUE TITLE
Stretched images / pictures

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1959]
Sorry if duplicate.
I'm from mobile as well.

![Screenshot_20201205-142358.png](https://user-images.githubusercontent.com/44380480/101244536-685a9e00-3707-11eb-8fc9-47136d5f1c9e.png)
![Screenshot_20201205-143908.png](https://user-images.githubusercontent.com/44380480/101244585-ace63980-3707-11eb-9b67-8d989f1edb8a.png)

https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics

**Comment by mattiapontonio** [comment]
Now some images are cropped.
Some are right.
Looking better 👌

![Screenshot_20201209-164642.png](https://user-images.githubusercontent.com/44380480/101652150-2fd7fe80-3a3e-11eb-8c2c-e4580f0fed40.png)

**Comment by peterbe** [comment]
Dupe of https://github.com/mdn/yari/issues/1927
