### ISSUE TITLE
A little cropped X in mobile search input

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1964]
![Screenshot_20201205-151028.png](https://user-images.githubusercontent.com/44380480/101245296-2122dc00-370c-11eb-80e3-808688935e16.png)

The icon should be the `<label>` of the `<input>` so displayed inline as a sibling.

**Comment by schalkneethling** [comment]
The icon is added in Safari when using an input of type search. In a recent update, I added `-webkit-appearance: none;` which resolves this problem. Tested on iPhone 7 with Safari

**Comment by mattiapontonio** [comment]
I don't like the CSS rules that starts with `-` but Is a personal opinion.
