### ISSUE TITLE
<datalist> for the search <form> suggestions

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1981]
I know that there Is a lack of styling but i think Is good for mobile experience ti use `<datalist>` for the search <form> suggestions.

And `<option>` with "all the attributes" even `label`

- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

![Screenshot_20201205-224748.png](https://user-images.githubusercontent.com/44380480/101266133-649d3a80-374c-11eb-8d92-c008ee3f5221.png)

![Screenshot_20201205-225909.png](https://user-images.githubusercontent.com/44380480/101266278-92cf4a00-374d-11eb-8d65-eed354baaf57.png)

![Screenshot_20201205-230200.png](https://user-images.githubusercontent.com/44380480/101266311-e9d51f00-374d-11eb-8c25-3a502730e828.png)

![Screenshot_20201205-230820.png](https://user-images.githubusercontent.com/44380480/101266417-ebebad80-374e-11eb-9d1d-7a206b130e20.png)

**Comment by peterbe** [comment]
We have an autocomplete search functionality. It's just not enabled yet. Instead of using `<datalist>`  we use `downshift`.

**Comment by mattiapontonio** [comment]
@peterbe My bipolar `developer` | `designer` brain tells me I like it better `<downshift>` but `<datalist>` is better. Anyway ok.

**Comment by peterbe** [comment]
I actually like `<datalist>` in some cases. [Especially on mobile](https://www.peterbe.com/plog/datalist-looks-great-on-mobile-devices)

**Comment by mattiapontonio** [comment]
The problem is that it is not recommended to serve different content based on the device because in fact the URI is the same. I should investigate but I remember reading about it. It is a bit of the reason why many times mobile users change plans to desktop users but nowadays they are said to use a mobile-first approach otherwise you will never be able to compete with native applications and the web is trying. It is the reason why in this specific case I am focusing on testing YARI on mobile.

**Comment by mattiapontonio** [comment]
In any case, if you wanted to create a custom solution you should at least try to reimplement the same features if possible. It is certainly a work of several issues.
