### ISSUE TITLE
input type submit in search form

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1982]
There Is not the submit `<button>|<input>` for the search `<form>`.

![Screenshot_20201205-231214.png](https://user-images.githubusercontent.com/44380480/101266460-57357f80-374f-11eb-958d-cdd10fbffc2a.png)

**Comment by peterbe** [comment]
It's a `<input type="search">` so your browser keyboard should replace the "Enter" for "Search". No?

**Comment by schalkneethling** [comment]
> It's a `<input type="search">` so your browser keyboard should replace the "Enter" for "Search". No?

No, that happens on Safari. I know how to fix that. Also, I was meaning to file a similar issue. Addressing. Thanks @mattiapontonio

**Comment by mattiapontonio** [comment]
I am always beyond the topic but if you use a normal form it does the GET automatically with the param queries already set on the search page without AJAX or strange things, it is a form that does a GET. I don't know if you know but now that I know I want to remember it.

**Comment by mattiapontonio** [comment]
On mobile phones there is a button in the shape of a magnifying glass but if we put a button we show even more that we are faithful to the law I think.

**Comment by mattiapontonio** [comment]
Adding the label is also much "more W3C". The magnifying glass or a string that says "Search" is the label. The placeholder instead is a fake search, not a guide on how to search like "JavaScript function statment"
