### ISSUE TITLE
Simplify and improve install and start for the developer experience

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1988]
Is possibile to simplify the getting started operations in order to improve the developer experience?

## Proposal TBD

```
git clone https://github.com/mdn/content.git mdn/content
git clone https://github.com/mdn/yari.git mdn/yari
cd mdn/yari
yarn
export CONTENT_ROOT=../content/files
yarn start

```

## Issues

- `content` should be a dependency? A Git repository could be a dependency https://docs.npmjs.com/cli/v6/configuring-npm/package-json#git-urls-as-dependencies
- `dev` should be `start`? Why? Is more semantic, is [documented in scripts of Node](https://docs.npmjs.com/cli/v6/using-npm/scripts), there is shortcut and Heroku for example run `start` as a default script (this is for the CI/CD thing)

## Target 🎯
```
git clone https://github.com/mdn/yari.git
cd yari
npm i
npm start
```
### then
- logs location (_http://localhost:3000_) from Node server in console
- logs in a table the `process.env`
- do not open the browser

## Notes
- (No commands Linux only IMHO)
- I don't know why Yarn but with It Is another step if You already have Node 🤷🏻‍♂️ I did not dig into Yarn yet

**Comment by peterbe** [comment]
Sorry. I disagree. We designed it this way. You should not need to clone `yari` to work on the content. Yari is two things:
* the previewing tool for the content
* the build tool that ships the built content 

There's a huge difference between `yarn dev` and `yarn start` in Yari.

**Comment by mattiapontonio** [comment]
@peterbe I speak from experience about other packages that clone them and go. The first approach is not the best and I tried. Anyway ok, I don't know at the moment how to do it myself in case.
