### ISSUE TITLE
GitHub repository deploy url

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#1996]
![Screenshot_20201207-104356.png](https://user-images.githubusercontent.com/44380480/101335218-35381c00-3879-11eb-866c-0fb7f6c6ee3d.png)
![Screenshot_20201207-104240.png](https://user-images.githubusercontent.com/44380480/101335228-379a7600-3879-11eb-91e9-42dffd5aa16c.png)

**Comment by schalkneethling** [comment]
@mattiapontonio I believe we might be waiting until the official launch.

**Comment by mattiapontonio** [comment]
@schalkneethling ok.
Should be add an **Environments** section in the readme?
Something that points to allizom and maybe other info.

**Comment by mattiapontonio** [comment]
Can We please fix this?
Why?
From the GitHub Android App there Is not a link to PROD.
