### ISSUE TITLE
Do not publish sourcemaps to npm

### ISSUE THREAD

**Issue by bershanskiy** [mdn/yari#1997]
Please consider not publishing sourcepaps of `yari` to npm because `yari`'s dependents (`mdn/content`) likely don't need it in prod.
Also, this should save some time if `mdn/content` ever switches to `@mdn/yari` published to npm (https://github.com/mdn/yari/issues/1604#issuecomment-721118634).

As of version `0.1.323`, npm release of `@mdn/yari` `.map` files occupy ~4 MB out of ~7 MB of the whole package size. 

<details>
<summary>List of source map files with their sizes</summary>
In an empty directory install yari as a dependency and run:

$ find node_modules/@mdn/yari -name "*.map" | xargs du -sch

Output:

4.0K    node_modules/@mdn/yari/client/build/static/css/10.70fd4276.chunk.css.map
4.0K    node_modules/@mdn/yari/client/build/static/css/11.24e71b07.chunk.css.map
1.0K    node_modules/@mdn/yari/client/build/static/css/12.94edd2f2.chunk.css.map
8.0K    node_modules/@mdn/yari/client/build/static/css/13.0d311b88.chunk.css.map
4.0K    node_modules/@mdn/yari/client/build/static/css/5.c452b65c.chunk.css.map
4.0K    node_modules/@mdn/yari/client/build/static/css/7.eaa564a4.chunk.css.map
4.0K    node_modules/@mdn/yari/client/build/static/css/8.79c2ef97.chunk.css.map
96K     node_modules/@mdn/yari/client/build/static/css/main.157d65bf.chunk.css.map
36K     node_modules/@mdn/yari/client/build/static/js/10.a11589f2.chunk.js.map
8.0K    node_modules/@mdn/yari/client/build/static/js/11.4932c4a5.chunk.js.map
8.0K    node_modules/@mdn/yari/client/build/static/js/12.459f6c1a.chunk.js.map
4.0K    node_modules/@mdn/yari/client/build/static/js/13.77731a98.chunk.js.map
12K     node_modules/@mdn/yari/client/build/static/js/14.1f185f91.chunk.js.map
24K     node_modules/@mdn/yari/client/build/static/js/15.ad3cab70.chunk.js.map
456K    node_modules/@mdn/yari/client/build/static/js/2.f3e567d7.chunk.js.map
80K     node_modules/@mdn/yari/client/build/static/js/3.31d03490.chunk.js.map
260K    node_modules/@mdn/yari/client/build/static/js/4.c265acfb.chunk.js.map
44K     node_modules/@mdn/yari/client/build/static/js/5.d0044c2e.chunk.js.map
48K     node_modules/@mdn/yari/client/build/static/js/6.aa47b790.chunk.js.map
20K     node_modules/@mdn/yari/client/build/static/js/7.91d45b47.chunk.js.map
24K     node_modules/@mdn/yari/client/build/static/js/8.fcc169fd.chunk.js.map
108K    node_modules/@mdn/yari/client/build/static/js/9.1302d8ed.chunk.js.map
132K    node_modules/@mdn/yari/client/build/static/js/main.d35f5045.chunk.js.map
20K     node_modules/@mdn/yari/client/build/static/js/runtime-main.7b6ffd8c.js.map
372K    node_modules/@mdn/yari/ssr/dist/1.js.map
4.0K    node_modules/@mdn/yari/ssr/dist/10.js.map
12K     node_modules/@mdn/yari/ssr/dist/11.js.map
40K     node_modules/@mdn/yari/ssr/dist/12.js.map
24K     node_modules/@mdn/yari/ssr/dist/13.js.map
48K     node_modules/@mdn/yari/ssr/dist/2.js.map
252K    node_modules/@mdn/yari/ssr/dist/3.js.map
20K     node_modules/@mdn/yari/ssr/dist/4.js.map
24K     node_modules/@mdn/yari/ssr/dist/5.js.map
40K     node_modules/@mdn/yari/ssr/dist/6.js.map
84K     node_modules/@mdn/yari/ssr/dist/7.js.map
8.0K    node_modules/@mdn/yari/ssr/dist/8.js.map
8.0K    node_modules/@mdn/yari/ssr/dist/9.js.map
1.7M    node_modules/@mdn/yari/ssr/dist/main.js.map
4.0M    total
</details>

**Comment by peterbe** [comment]
> likely don't need it in prod.

`mdn/content` doesn't use the NPM package of yari in prod. 
You use the Yari NPM package when you do local previewing of the content as you're writing it. 
If something was to crash then, it might be very helpful to have sourcemaps. E.g. a writer says "I was doing a previewing after this and that change and I got this error..." and they might be able to provider a better error description. 

And isn't this true in prod too? If you get an error, the browser will download the sourcemaps to get a richer error message in the console. That might help better describe and debug production issues in the client. No?

**Comment by Ryuno-Ki** [comment]
I think, the fear is that it might lack some secrets.
Like, in business, you don't want to let everybody know how your code was written („security by obscurity”).
That's likely different for MDN.

The only thing I'd double-check here, is whether the Sourcemaps are inlined or referred to by URL.
The latter is preferable, since it would be only loaded on-demand (instead of to everybody)

**Comment by mattiapontonio** [comment]
> I think, the fear is that it might lack some secrets.
> Like, in business, you don't want to let everybody know how your code was written („security by obscurity”).
That's likely different for MDN.

I basically commented the same way without reading here before 🔮
https://github.com/mdn/yari/issues/2299#issuecomment-778874011

Source maps are a complex way of tracing back to code you could have served from the start, not dealing with PHP debugging because if there was an error there the page wouldn't even be served with [500](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500).
