### ISSUE TITLE
Little things to make this look great

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2]
### Important

- [x] Build the Browser Compat Table component
- [x] Build the Interactive Examples component
- [x] Build the Attributes component
- [x] ~~Come up with a better name for this project~~ We decided to rename it to **stumptown-renderer**
- [x] Move this repo to the `mdn` GitHub org
- [x] Make a full deployment build and upload somewhere (e.g. GitHub pages)
- [x] Some basic unit tests
- [ ] [ESLint](https://github.com/peterbe/mdn2/issues/32)
- [x] [Prettier](https://github.com/peterbe/mdn2/pull/31)
- [ ] Refactor code so that the core React components don't exclusively sit inside the `client` app
- [x] CI for testing and linting
- [ ] A nice footer
- [x] Sidebar (imperfect)

### Nice to haves

- [ ] `docker-compose` to start all the things
- [ ] Building a sitemap.xml (or `sitemaps.xml` etc.)
- [x] [Build a JSON file for all titles for possible search](https://github.com/peterbe/mdn2/pull/25)
- [ ] Some MDN nice looking stylesheets
- [ ] Figure out how to display document metadata (contributors, tags, last modified)
- [ ] Tooling to automatically update `stumptown-experiment` git submodule
- [ ] HTML validation tooling
- [ ] Service Worker (should be disabled in PR staging builds!)
- [ ] Lazy loading non-critical features
- [x] Site search (titles)
- [ ] Netlify deployment should be easy
- [ ] Have control over our server-side rendered 404 pages. 
- [ ] CSP headers and Mozilla Observatory A+
- [ ] Google Analytics
- [ ] `humans.txt` file

**Comment by schalkneethling** [comment]
> Come up with a better name for this project

I still think mdn-freshly-ground ;)

**Comment by peterbe** [comment]
> I still think mdn-freshly-ground 

It's not wrong but can you think of something slightly more "sustainable". It *might* not be applicable but **if** this really works out it might be something more solid and not just a "temporal" name. 

I usually call a lot of my projects whimsical (short!) Swedish words (Tecken, Grymt, etc.) that has some relevance but isn't restricting its scope. 

For example, I wrote a webapp called `github-bugzilla-pr-linker` which was not only too long but it didn't work for doing other things like linking issues or merges.

**Comment by peterbe** [comment]
I deleted two previous comments here related to picking a good name. At the Whistler All-hands we made a decision to call it: `stumptown-renderer`.

**Comment by pdemko93** [comment]
> ### dôležitý
> * [x]  Zostavte komponent tabuľky Compat Table
> * [x]  Zostavte komponent interaktívne príklady
> * [x]  Zostavte komponent Atribúty
> * [x]  ~Príďte s týmto projektom lepšie meno~Rozhodli sme sa premenovať ho na **stumptown-renderer**
> * [x] Presuňte toto repo do `mdn`organu GitHub
> * [x]  Vytvorte niekde úplné rozmiestnenie a nahrávanie (napr. Stránky GitHub)
> * [x]  Niektoré základné jednotkové testy
> * [ ]  [ESLint](https://github.com/peterbe/mdn2/issues/32)
> * [x]  [krajší](https://github.com/peterbe/mdn2/pull/31)
> * [ ] Refaktorový kód, takže základné komponenty React nesedia výlučne v `client`aplikácii
> * [x]  CI na testovanie a poťahovanie
> * [ ]  Pekná päta
> * [x]  Bočný panel (nedokonalý)
> 
> ### Je pekné mať
> * [ ]  `docker-compose` začať všetky veci
> * [ ] Vytvorenie súboru sitemap.xml (alebo `sitemaps.xml`atď.)
> * [x]  [Vytvorte súbor JSON pre všetky tituly pre možné vyhľadávanie](https://github.com/peterbe/mdn2/pull/25)
> * [ ]  Niektoré pekne vyzerajúce štýly MDN
> * [ ]  Zistite, ako zobraziť metadáta dokumentu (prispievatelia, značky, naposledy upravené)
> * [ ] Nástroj na automatickú aktualizáciu `stumptown-experiment`submodulu git
> * [ ]  Nástroje na overenie HTML
> * [ ]  Service Worker (malo by byť zakázané pri zostavovaní PR PRaging!)
> * [ ]  Lenivé načítanie nepodstatných prvkov
> * [x]  Vyhľadávanie na stránkach (tituly)
> * [ ]  Nasadenie programu Netlify by malo byť jednoduché
> * [ ]  Majte kontrolu nad našimi vykreslenými 404 stranami na strane servera.
> * [ ]  Záhlavia CSP a observatórium Mozilla A +
> * [ ]  Google Analytics
> * [ ]  `humans.txt` súbor

**Comment by peterbe** [comment]
I don't know if @pdemko93 is a spam bot or a confused user but I'll block that user if it reappears. For now I'm deleting the comment.
