### ISSUE TITLE
woff2 fonts served with the wrong content-type

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2017]
```
▶ curl -I https://developer.allizom.org/static/media/ZillaSlab-Bold.subset.0beac26b.woff2 | rg content-type
...
content-type: binary/octet-stream
```
It's maybe because [`mimetypes` guesses it wrong](https://github.com/mdn/yari/blob/4066278d3cf6c3039bd414111c07a02dc86b8964/deployer/src/deployer/upload.py#L166)

Seems we're [not the only ones](https://stackoverflow.com/questions/28235550/proper-mime-type-for-woff2-fonts) who have this problem.

On macos, my Python 3.8 gets it right though:
```python
>>> import mimetypes
>>> mimetypes.guess_type('client/build/static/media/ZillaSlab-Bold.subset.0beac26b.woff2')
('font/woff2', None)
```

**Comment by peterbe** [comment]
[Sample file we've uploaded](https://s3.console.aws.amazon.com/s3/object/mdn-content-stage?region=us-west-2&prefix=main/static/media/zillaslab-bold.subset.0beac26b.woff2)
[Sample `.woff` file](https://s3.console.aws.amazon.com/s3/object/mdn-content-stage?region=us-west-2&prefix=main/static/media/zillaslab-bold.subset.72026b3c.woff)

**Comment by peterbe** [comment]
Curious that my VPS Ubuntu 20.04 with Python 3.8 gets it right:
```
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mimetypes
>>> mimetypes.guess_type('peterbecom/base/static/fonts/icons.woff2')
('font/woff2', None)
```

**Comment by peterbe** [comment]
It's still an issue. I'm just going to override it in the Deployer.

**Comment by mattiapontonio** [comment]
Could it have a correlation with the FOIT that I always seemed to see from time to time?
