### ISSUE TITLE
'View Profile' option is not available in menu dropdown on other pages than homepage

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2021]
**Preconditions:**
Create and sign in with a contributor account. 

**Steps to reproduce:**
1. Go to https://developer.allizom.org/en-US/. 
2. Select the profile icon and view dropdown menu options - View Profile, Edit Profile and Sign Out. 
3. Open any of the article pages, for example, https://developer.allizom.org/en-US/docs/Web.
4. Repeat step 2. 

**Expected result:**
On https://developer.mozilla.org/en-US/docs/Web this options is available. 

**Actual result:**
Only edit and sign out are available in Stage. 
![image](https://user-images.githubusercontent.com/53306802/101512789-13778b80-3984-11eb-94bf-b29e7059b346.png)

**Comment by peterbe** [comment]
It's a not a regression *within Yari* because it seems when the menu was initially added it simply didn't have it. 
https://github.com/mdn/yari/blob/862f12903e4389400f34474ebc0f028e0f33a600/client/src/ui/molecules/login/index.tsx#L64-L74
Any reasoning for that @schalkneethling ?
I think we missed this in review because [the PR was too big](https://github.com/mdn/yari/pull/1261).

**Comment by schalkneethling** [comment]
> Any reasoning for that @schalkneethling ?

I believe we might have thought to not actively link to it as it contains a bunch of dead content and links post the Yari launch. i.e. the contribution history, links to the various dashboards etc.

**Comment by mattiapontonio** [comment]
I did not understand if all this part of the profiles is dismissed and therefore you have to remove the entire block or save something inside your profile.

https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/

**Comment by peterbe** [comment]
> I believe we might have thought to not actively link to it as it contains a bunch of dead content and links post the Yari launch.

Very true. The page becomes extra useless. But it's not going away. We definitely need to remove the contributions listing. 
But I think it's fine that we don't link to it anymore. And I don't think it's critical that the menu options match perfectly when you're on the home page compared to a document page. 

Let's just not forget to remove the "Recent Docs Activity" portion as soon as possible after Dec 14.

**Comment by peterbe** [comment]
> I did not understand if all this part of the profiles is dismissed and therefore you have to remove the entire block or save something inside your profile will still lives.
> 
> https://hacks.mozilla.org/2020/10/mdn-web-docs-evolves-lowdown-on-the-upcoming-new-platform/

We're almost deliberately vague on the messaging here. It's partly because we don't have all the answers ourselves and partly because it's fractional in importance compared to the important change which is the documents. More will come, but it'll have to wait a bunch of days.
