### ISSUE TITLE
Language drop down lists some languages twice

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2034]
On https://developer.allizom.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics for example, when I click on the drop-down, I see French, Nederlands, and Italian twice:

![Screenshot 2020-12-09 at 15 53 23](https://user-images.githubusercontent.com/10350960/101638439-bdafeb80-3a36-11eb-8e2d-7ede82875f1a.png)

**Comment by peterbe** [comment]
It's not the languages that are repeated. But it appears like that if you strip away the slug from the relevant URLs. 
<img width="818" alt="Screen Shot 2020-12-09 at 10 04 14 AM" src="https://user-images.githubusercontent.com/26739/101646745-e9ff4400-3a05-11eb-891f-0d2857d6b0ab.png">


Why does `/ja/docs/Web/JavaScript/Getting_Started` and `/ja/docs/Learn/Getting_started_with_the_web/JavaScript_basics` both claim to be translations of this page?!

**Comment by peterbe** [comment]
Here's the "culprit": https://github.com/mdn/translated-content-rendered/blob/da0f03ffd66347a47bd8d3932edd48796f75d476/files/ja/web/javascript/getting_started/index.html#L4

I wonder what's going on in MySQL that triggered this and why it's not happening in the Wiki.

**Comment by mattiapontonio** [comment]
I know that with this...
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/getCanonicalLocales

_Duplicates will be omitted and elements will be validated as structurally valid language tags._

**Comment by peterbe** [comment]
> Here's an example "culprit": https://github.com/mdn/translated-content-rendered/blob/da0f03ffd66347a47bd8d3932edd48796f75d476/files/ja/web/javascript/getting_started/index.html#L4
> 
> I wonder what's going on in MySQL that triggered this and why it's not happening in the Wiki.

WIthout even looking at how Kuma works, the problem seems to lie with the importer. 
It totally makes sense in mysql:
```
mysql> select id, parent_id from wiki_document where locale='ja' and slug='Web/JavaScript/Getting_Started';
+-------+-----------+
| id    | parent_id |
+-------+-----------+
| 88023 |      2740 |
+-------+-----------+
1 row in set (0.00 sec)

mysql> select locale, slug, title from wiki_document where id=2740;
+--------+--------------------------------+---------------------------------------+
| locale | slug                           | title                                 |
+--------+--------------------------------+---------------------------------------+
| en-US  | Web/JavaScript/Getting_Started | Getting Started (JavaScript Tutorial) |
+--------+--------------------------------+---------------------------------------+
1 row in set (0.00 sec)

```
So what's going wrong in the importer then?!

**Comment by peterbe** [comment]
Ah! That document ID 2740 is actually a redirect!
```
mysql> select locale, slug, title, is_redirect from wiki_document where id=2740;
+--------+--------------------------------+---------------------------------------+-------------+
| locale | slug                           | title                                 | is_redirect |
+--------+--------------------------------+---------------------------------------+-------------+
| en-US  | Web/JavaScript/Getting_Started | Getting Started (JavaScript Tutorial) |           1 |
+--------+--------------------------------+---------------------------------------+-------------+
1 row in set (0.00 sec)
mysql> select html from wiki_document where id=2740;
+--------------------------------------------------------------------------------------------------------------------------------------+
| html                                                                                                                                 |
+--------------------------------------------------------------------------------------------------------------------------------------+
| <p>REDIRECT <a class="redirect" href="/en-US/Learn/Getting_started_with_the_web/JavaScript_basics">JavaScript basics [en-US]</a></p> |
+--------------------------------------------------------------------------------------------------------------------------------------+
1 row in set (0.00 sec)
```

So basically, now you have 2 different translations that both point to the same English doc. And this problem only arises because of redirects. Hmm... 
Feels like Kuma cheated here. 
```
