### ISSUE TITLE
When on a translated page, the only other language option is English

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2035]
This might be as intended but, thought I would file an issue so we have it recorded in history if that is the case 😄 

When on for example https://developer.allizom.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics

If I switch to say Nederlands, the language selector now only offer me Nederlands and English:

![Screenshot 2020-12-09 at 16 09 57](https://user-images.githubusercontent.com/10350960/101640281-ff419600-3a38-11eb-9cc4-a3705dfa2b86.png)

So, if I wanted a different non-English language, I would first have to switch back to English and then switch again. It is lightning fast 😄 but might not be the ideal user experience.

**Comment by mirunacurtean** [comment]
https://github.com/mdn/yari/pull/2839#issuecomment-777597073

**Comment by mattiapontonio** [comment]
This could be reopened...
Why be inconsistent in UI between languages?

![Screenshot_20210212-183811.png](https://user-images.githubusercontent.com/44380480/107802363-8674f800-6d61-11eb-86d2-c65fd41ed106.png)
