### ISSUE TITLE
Set the right HTML lang attribute

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2038]
Independent of uplifting or unfreezing or "dropping" locales, we're still rendering localized content. So we should get the `<html lang="en">` tag right. E.g. view-source:https://developer.allizom.org/fr/docs/Web

**Comment by peterbe** [comment]
@fiji-flo What do you think, if the chrome *and* the content is all in, say French, then I think we should have `<html lang="fr">`. No doubt. 
But what if, like during the frozen translation period, you have English chrome and French article text. What `lang` value should we have then?

**Comment by Ryuno-Ki** [comment]
You can [assign `lang` to any element](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) since it's a global one.

So, `<html lang="en">` for the chrome (= the surroundings) and `lang="fr"` for the content (`<main>` or something).

**Comment by mattiapontonio** [comment]
- `lang` and `locale` are the same string?
- `lang` and `locale` are the same thing?
- exists an attribute called `locale`?

This is for calling it `lang` if `const` in React as a good practice.

Of course You can and You should override of necessary but i'm thinking at the _one-way-data-flow_ (when You have to pass a variable 10 times in childs...)

**Comment by Ryuno-Ki** [comment]
> `lang` and `locale` are the same string?

Can be. As in, you can use a locale as value for the lang attribute. It expects a string in [BCP 47 format](https://www.ietf.org/rfc/bcp/bcp47.txt).

> `lang` and `locale` are the same thing?

No. `lang` is a language (like, `en` or `pt`), `locale` adds the region (e.g. UK / US or PR / BR).

**Comment by peterbe** [comment]
Ah. So if the header + footer is English, but the article text is French we could do:
```html
<article lang="fr">
```
Cool. But what's the value in doing this? Where and how does it matter?

**Comment by Ryuno-Ki** [comment]
A screenreader will switch pronounciation accordingly.

For example, `Berlin` is pronounced differently depending on your language:
https://en.wiktionary.org/wiki/Berlin (the speaker within that article play back some audio file)

It can have a serious effect on their UX: https://webaim.org/techniques/screenreader/#video (English text spelled with Czech pronounciation for demo purposes).

Also, it might help crawlers to categorise the content a bit better.

**Comment by mattiapontonio** [comment]
```
<html lang="en">
​<​article​ ​lang​="​fr​"​></article>
</html>
```
I believe that when the UI will be translated we will need to find a way to manage the attribute on the individual elements based on the presence or absence of the JSON file or more specifically the key, assuming a list of elements of which only a part are translated.

**Comment by peterbe** [comment]
Then, let's just do it. 
The code for figuring out the `lang` based on the `locale` is probably the same as we do for the `hreflang` meta tags. 
I'll attempt this next week.

**Comment by mattiapontonio** [comment]
I did not understand, however, even `hreflang` should be analyzed to understand if it can serve and as a value and how to do it.
