### ISSUE TITLE
input[type="search"].placeholder

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2043]
![Screenshot_20201209-232352.png](https://user-images.githubusercontent.com/44380480/101696053-ca9fff80-3a75-11eb-92f8-4e1a4ec693e5.png)

_The placeholder attribute is a string that provides a brief hint to the user as to what kind of information is expected in the field._ 

https://developer.allizom.org/en-US/docs/Web/HTML/Element/input/search#placeholder

**Comment by peterbe** [comment]
What are you suggesting?

**Comment by mattiapontonio** [comment]
I wanted to leave the choice ... I don't know the name of an unknown method, a random content class or a simple "what is the difference between const, let and var?"

**Comment by schalkneethling** [comment]
I feel that the string "Search MDN Web Docs" is simple and concise. It is clear to everyone what the input field is meant for and what the expected outcome should be. Trying to add too much there might actually be negative and cause cognitive overload for some people.

**Comment by mattiapontonio** [comment]
You can add a label for _Search_.
