### ISSUE TITLE
missing label for select#lang[name="lang"]

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2046]
![Screenshot_20201209-235750.png](https://user-images.githubusercontent.com/44380480/101698805-6af82300-3a7a-11eb-98d9-305d09118a4d.png)

**Comment by schalkneethling** [comment]
![Screenshot of DOM indicating the precense of a visually hidden for label element](https://user-images.githubusercontent.com/10350960/102050403-6e2d3f00-3deb-11eb-9629-df0600898788.png)

There is a label that is associated with the select element to ensure it is still available to users of assistive technologies. It is intentionally visually hidden as it uses additional screen real estate and the intented purpose of the component is clear.

**Comment by mattiapontonio** [comment]
You can show the label and set _Search into MDN_ as a `innerText`.
