### ISSUE TITLE
Jump to section not Intl / translated

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2048]
![Screenshot_20201210-000617.png](https://user-images.githubusercontent.com/44380480/101699547-9cbdb980-3a7b-11eb-9772-9b52fc347daa.png)

**Comment by peterbe** [comment]
Yeah, the chrome is not localized yet. We're hoping to get to that in early next year. It's a known issue. We're tracking this in a Google Doc.

**Comment by mattiapontonio** [comment]
@peterbe 

Ok. I think it's also in Firefox, I alternate a little from one browser to the other. I think it's an interesting topic how to internationalize strings in a standard way, I've seen that it can be done with dates and more but simple strings in templates I have yet to understand the best practice.
