### ISSUE TITLE
What's with all the `localStrings` variables in macros?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2051]
Here's one, for example: https://github.com/mdn/yari/blob/f257b9fbf68a03880263d1b88be3dd5b212d602b/kumascript/macros/CSP.ejs#L7
There are 12 lines similar to these throughout a bunch of .ejs files. 
I don't quite understand what they do. But if you search for string `localStrings` (or `commonLocalStrings`) where these occur, you'll only find it exactly once. 
There are a rare few places where they're used. For example in `svginfo.ejs`:
```
value: categories.join(localize(commonLocalStrings, "listSeparator"))
```

I did a little experimentation by removing it from `SVGElement.ejs` and built the `BUILD_FOLDERSEARCH=web/svg/` and the rate of building went up by 13%. 

What do they do? A relic from the past or does it prime something by being called?

**Comment by escattone** [comment]
@peterbe Interesting. It seems that a lot of these JSON objects are being created from https://github.com/mdn/yari/blob/master/kumascript/macros/L10n-Common.json, but then never used.
