### ISSUE TITLE
Remove all uses of pageExists() in macros?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2052]
There's a lot of `wiki.pageExists()` calls in the macros. See https://gist.github.com/peterbe/a8c1465c425670a81fc62bf0f3278dda
I suspect they're mostly in obsolete looking macros. But I know that `SVGElement.ejs` is called tens of thousands of times. 

Then I noticed this: https://github.com/mdn/yari/blob/f257b9fbf68a03880263d1b88be3dd5b212d602b/kumascript/src/api/wiki.js#L13-L19

Can we just delete all occurrences of this throughout the macros and delete it from that `wiki.js` too?

**Comment by peterbe** [comment]
@escattone If you can bless this issue (perhaps remove the question mark from the issue title), this might be a great beginner-issue.

**Comment by escattone** [comment]
@peterbe 👍 I totally agree. I've known about this for some time now, but thought it best to wait until after we launched Yari. Sometime after we launch, let's get rid of all calls to `wiki.pageExists()`.

**Comment by peterbe** [comment]
@tannerdolby Can you take this one?

**Comment by tannerdolby** [comment]
@peterbe Yeah. I can take this one.
