### ISSUE TITLE
Problems printing MDN document using Firefox browser

### ISSUE THREAD

**Issue by swwright** [mdn/yari#2054]
**Summary**
Content clipped, only one page of content presented, all remaining content is lost.

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Open Firefox browser
2. Go to https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Basic_Shapes
3. Select Print from the menu.  The problem shows on the preview page as well as the printed paper.

**Actual behavior**
_What actually happened?_
Let's take "Basic Shapes" as an example.
The first page contains the title and nothing else.
The second page contains (at full scale) the content of the document down to line 4 of the example XML.
The rest of the content, from line 5 of the example XML down to the final paragraph,  are invisibly printed in the air below the bottom of the 8.5x11 inch page.
The third page contains the footer, ironically advertising "Learn the best of web development".

**Expected behavior**
_What did you expect to happen?_
I expected to see all six pages of "Basic Shapes, the "learn the best" footer being at the bottom of the sixth page.

**Additional context**
_Is there anything else we should know?_

Printing was done at the "shrink to fit" scale setting.
I am using Firefox 83.0, 64-bit version.
I should note that the document is actually quite good.  That's why I was trying to print it for off-line use.
I honestly don't know if this is a problem with the document, or a problem with Firefox.
Google Chrome and Microsoft Edge (the new Chrome-wanna-be version) both print this document in full.
But I have had this same problem (clip off any text that doesn't fit on the first page) with Edge on other documents, and Firefox printed those docs fine.  Sorry, those events happened months ago and I do not remember what I was printing.

**Comment by peterbe** [comment]
Without getting too much into the details, it's clearly a terrible experience when print even from the new (Yari) system. 
https://developer.allizom.org/en-US/docs/Web/SVG/Tutorial/Basic_Shapes

I think we can make huge improvements to the printing if we just define a basic print stylesheet that hides a bunch of things that are useless in a PDF or on physical paper such as some header and footer stuff, fix the `<pre>code>` snippets, and other relatively easy fixes.

**Comment by mattiapontonio** [comment]
But isn't there already a default style sheet for printing?

**Comment by peterbe** [comment]
> But isn't there already a default style sheet for printing?

No mention of one in view-source:https://developer.allizom.org/en-US/docs/Web/SVG/Tutorial/Basic_Shapes
So no I don't think so.

**Comment by mattiapontonio** [comment]
Maybe Sass resets it. I don't mean to say but resetting is a bit of a series of safe issues.

**Comment by mattiapontonio** [comment]
_That's why I was trying to print it for off-line use._

It could be argued that for offline and at the same time eco-friendly use, a PWA could be made 😊🥁

**Comment by piotrtomiak** [comment]
A support for `raw` parameter (#2161) can help as well, one could open the version with documentation only without any menus, headers or footers. An "open printable version" button could be there.

**Comment by schalkneethling** [comment]
We have a missing print stylesheet 😱 My apologies folks. I will add this back.
