### ISSUE TITLE
Lack of icon in Chrome mobile "keep tapped on a link" modal

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2058]
Here Ok:
![Screenshot_20201210-171824.png](https://user-images.githubusercontent.com/44380480/101798742-bd355480-3b0b-11eb-88c5-de2c52a8c0a7.png)

Here missing favicon
![Screenshot_20201210-171806.png](https://user-images.githubusercontent.com/44380480/101798811-d0e0bb00-3b0b-11eb-86f4-0e9d4fb72afc.png)

Step to reproduce:
- keep tapped on a link / anchor using a mobile device and Chrome Android App

**Comment by peterbe** [comment]
Unlike developer.mozilla.org, on developer.allizom.org we actually have https://developer.allizom.org/manifest.json which should define logos like that. But what developer.mozilla.org has HTML like this:
```html
  <!-- third-generation iPad with high-resolution Retina display: -->
  <link rel="apple-touch-icon-precomposed" sizes="144x144" href="/static/img/favicon144.e7e21ca263ca.png">
  <!-- iPhone with high-resolution Retina display: -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="/static/img/favicon114.d526f38b09c5.png">
  <!-- first- and second-generation iPad: -->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="/static/img/favicon72.cc65d1d762a0.png">
  <!-- non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <link rel="apple-touch-icon-precomposed" href="/static/img/favicon57.de33179910ae.png">
  <!-- basic favicon -->
  <link rel="shortcut icon" href="/static/img/favicon32.7f3da72dcea1.png">
```

So what browser are you using there? Can you find out what or where it's looking for icons?
Perhaps `/manifest.json` is only read and downloaded by the browser in conjunction with PWA and Service Workers, which we don't currently have.

**Comment by mattiapontonio** [comment]
My browser:
https://whatismybrowser.com/w/Y28X28C

I'm not sure if you have to choose between the page `manifest` or `<head>`. The manifest represents the PWA in terms of global App (so for example the icon on the home screen), the head represents the document in terms of URL so I think that for that case we should use the `<head>`. 
Which link should I look for. 
Is it too risky to copy all of Kuma's and take the pictures into the house?

**Comment by mattiapontonio** [comment]
After some test seems:

- I didn't find how this modal Is called/documented
- Google itself don't use It 🙂
- GitHub use It
- Seems that the data comes not from the URL that You are on but the One that You are long tapping

![Screenshot_20201210-215546.png](https://user-images.githubusercontent.com/44380480/101829176-ecab8780-3b32-11eb-9b6f-96493a874a69.png)
![Screenshot_20201210-215623.png](https://user-images.githubusercontent.com/44380480/101829181-f03f0e80-3b32-11eb-841b-d4652d47e298.png)
![Screenshot_20201210-215641.png](https://user-images.githubusercontent.com/44380480/101829189-f2a16880-3b32-11eb-8d46-9abf0e44626e.png)
![Screenshot_20201210-215659.png](https://user-images.githubusercontent.com/44380480/101829194-f503c280-3b32-11eb-8111-0b68d05c5de8.png)

**Comment by mattiapontonio** [comment]
If You `curl` a Yari URL the `<head>` is rendered? 🤔
