### ISSUE TITLE
SERP overflow on mobile

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2059]
![Screenshot_20201210-175058.png](https://user-images.githubusercontent.com/44380480/101803046-64b48600-3b10-11eb-96a0-74c0575428f2.png)

**Comment by schalkneethling** [comment]
@mattiapontonio what device are you using?

**Comment by mattiapontonio** [comment]
@schalkneethling 
https://whatismybrowser.com/w/3YW8P8G

**Comment by schalkneethling** [comment]
I can no longer reproduce this on mobile at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules

**Comment by mattiapontonio** [comment]
It's a search but seems fixed 👍
https://developer.mozilla.org/en-US/search?q=PluralRules
