### ISSUE TITLE
SERP 2 messages 0 results && PluralRules

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2060]
Maybe duplicate.
I think that Just the section header should stay.

I'm not sure how but I feel this is for something here. For example 0 is plural?

https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/PluralRules/PluralRules

![Screenshot_20201210-175251.png](https://user-images.githubusercontent.com/44380480/101803308-a6ddc780-3b10-11eb-830a-4ffabda6253c.png)

![Screenshot_20201211-214330.png](https://user-images.githubusercontent.com/44380480/101953036-ed5b2100-3bf9-11eb-96c3-f311b46dd4d3.png)

**Comment by peterbe** [comment]
We're going to "rewrite" the full-text search in the weeks following the launch. This is a good issue to keep an eye on see if we can get it right from the start. Thanks @mattiapontonio !
