### ISSUE TITLE
 Warning icon color is not yellow

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2064]
**Steps to reproduce:**
1. Go to https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#Function_properties. 
2. See uneval() element icon and compare to production.

**Actual result:**
Warning icon colour is blue.
![image](https://user-images.githubusercontent.com/53306802/101825911-f505c180-3b36-11eb-8939-473b3c3aed72.png)

**Expected result:**
Warning sign colour should be yellow.
![image](https://user-images.githubusercontent.com/53306802/101826025-1b2b6180-3b37-11eb-983a-c748a7795dac.png)

 
 Hoping this is not a duplicate of something that is in planning / intended, but a quick search through logged issues did not yield such results, so I am logging it just in case.

**Comment by schalkneethling** [comment]
> Hoping this is not a duplicate of something that is in planning / intended, but a quick search through logged issues did not yield such results, so I am logging it just in case.

This instance is correct @mirunacurtean. This uses the `non-standard` macro and so, is not meant to be a warning. We do not currently have an icon to represent `non-standard` and so we reuse the warning icon but show it as blue. Not great, but it is ok for now.

**Comment by mirunacurtean** [comment]
Alright, I have seen it in other instances as well such as the Methods links under Related topics so it is good to know that it's intended. Thank you for the clarification @schalkneethling .

**Comment by mattiapontonio** [comment]
_We do not currently have an icon to represent non-standard and so we reuse the warning icon but show it as blue._

Should We create a repository for designers that only use Adobe Illustrator but can export in SVG and push via GitHub desktop for Mac 🤔

**Comment by Ryuno-Ki** [comment]
In that case, don't forget to run the output through SVGO / https://jakearchibald.github.io/svgomg/ before adding, please.
