### ISSUE TITLE
'Page not yet created' links do not reflect that

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2065]
**Steps to reproduce:** 
1. Go to https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects#Control_abstraction_objects. 
2. View all code examples. 
3. Hover over the AsyncGenerator and AsyncGeneratorFunction links and see that pages for this have not yet been created. 

**Actual results:**
Unwritten pages links are indistunguashable from written ones. 
![image](https://user-images.githubusercontent.com/53306802/101826677-000d2180-3b38-11eb-9626-bf88d0232e26.png)

**Expected result:**
Visual warning through red colour that pages have not been written yet. 
![image](https://user-images.githubusercontent.com/53306802/101826711-0f8c6a80-3b38-11eb-9004-e8743aa6e4fb.png)

**Comment by mattiapontonio** [comment]
I don't know how this is handled in Kuma but it seems like a smart way to handle it not to set href and then use an attribute selector for the style.

**Comment by peterbe** [comment]
This what I call pre-launch regression. We had it working recently but it seems to have gone away. 
As you can see, the HTML is correct. 
```html
<a class="new" 
  title="The documentation about this has not yet been written; please consider contributing!" 
 data-flaw-src="{{JSxRef(&quot;Global_Objects/AsyncGenerator&quot;, &quot;AsyncGenerator&quot;)}}">  <code>AsyncGenerator</code>
</a>
```

@schalkneethling we used to have a `a.new` style, but perhaps that was back in the "kumastyles" day. 
If we can't fix this rapidly before the launch, I think we should try to prioritize it for early next week. 
In my view, we just need some color on those links that make them look less like a clickable link.

**Comment by mattiapontonio** [comment]
I finally found a reason to use `a:link` 🧐 So it would appear to `a` -> `red` and `a: link` -> `blue`.

https://css-tricks.com/how-to-disable-links/

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) ['Page not yet created' links do not reflect that](https://trello.com/c/968YhQId/19-page-not-yet-created-links-do-not-reflect-that)

**Comment by mattiapontonio** [comment]
![Screenshot_20210115-192117.png](https://user-images.githubusercontent.com/44380480/104763896-e2e6f680-5766-11eb-8eca-d40f5b0300b8.png)

Nice orange 🍊🙂
