### ISSUE TITLE
Table properties, elements and example are not styled differently from other table content

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2067]
Possible duplicate, as I remember I've seen something like this mentioned in slack but I am not sure it is this specific case. 

**Steps to reproduce:** 
1. Go to https://developer.allizom.org/en-US/docs/web/javascript/reference/global_objects/array#Creating_an_array_using_the_result_of_a_match.
2. View 'Property/Element' and 'Example' items and hover with mouse over them.

**Actual results:**
Properties, elements and example are missing the darker gray background colour.
Also, Cursor and tooltip are missing when hovering over 'Read Only' badge and only informative text is displayed. 
![image](https://user-images.githubusercontent.com/53306802/101827243-b6710680-3b38-11eb-8eee-b1549bde2ce4.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/53306802/101828601-74e15b00-3b3a-11eb-908a-dae7f6e9fa6e.png)

Also, when hovering over 'Read Only' badge a mouse cursor and a question tooltip are displayed on developer.mozilla.org.

**Comment by mattiapontonio** [comment]
👛
I think but I'm not sure it's because the gray is the same and on my side I don't think I need to exaggerate with the grays.
