### ISSUE TITLE
[Desktop] Some Notes are set as notecard.note elements and are marked as paragraphs while some or not 

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2074]
**Steps to reproduce:**
1. Go to https://developer.allizom.org/en-us/docs/web/http/cors#What_requests_use_CORS. 
2. Seek "Note" paragraphs and compare them. 

**Actual results:**
 Some notes are not visually set apart into a different class. 
![image](https://user-images.githubusercontent.com/53306802/101899292-40ab8000-3bb6-11eb-80b1-8719b628bfa6.png)

While on the same page, some notes displayed differently. 
![image](https://user-images.githubusercontent.com/53306802/101899522-a26bea00-3bb6-11eb-96b3-446aca886369.png)

**Expected result:**
All notes are displayed in the same way. 
https://developer.mozilla.org/en-US/docs/web/http/cors#What_requests_use_CORS

**Comment by mattiapontonio** [comment]
From mobile seems ok

![Screenshot_20201211-130130.png](https://user-images.githubusercontent.com/44380480/101901264-12777180-3bb1-11eb-8c97-61183a45788b.png)

**Comment by mirunacurtean** [comment]
Also on the same topic, some notes are marked as paragraphs while some or not, which makes the text line length vary. 
This is also an inconsistency not encountered on https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS.
 
![image](https://user-images.githubusercontent.com/53306802/101901402-aa795900-3bb9-11eb-99c5-0d70503794ca.png)

**Comment by mattiapontonio** [comment]
Without looking I would expect that the notes are `div.note`s with one or more `p`aragraphs inside.

**Comment by mattiapontonio** [comment]
Arguably those `strong` could be put in the before 
![Screenshot_20201211-131347.png](https://user-images.githubusercontent.com/44380480/101902296-b9a8d880-3bb2-11eb-9ac3-003069a6744d.png)

**Comment by peterbe** [comment]
@mirunacurtean I believe this has been fixed. We just need to way max 12h for the next build. Would you mind refreshing on the next working-day and see if it's now resolved?

**Comment by mattiapontonio** [comment]
https://github.com/mdn/mdn-minimalist/issues/386

**Comment by mattiapontonio** [comment]
Is fixed visually?

![Screenshot_20210101-191841.png](https://user-images.githubusercontent.com/44380480/103444167-3dac2880-4c66-11eb-9d1d-4cf23317032d.png)

**Comment by mirunacurtean** [comment]
@peterbe @mattiapontonio  Sorry for the late reply. I was supposed to look over this before going on holiday but it skipped my notice. I have verified on the same page and several others that the Notes are consistently displayed the same, marking this issue as fixed.
