### ISSUE TITLE
Missing blockquote style

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2075]
Steps to reproduce:
1. Go to https://developer.allizom.org/en-us/docs/web/http/cors#What_requests_use_CORS
2. Search for "Preflighted requests and redirects". 
3. Compare error message styling to https://developer.mozilla.org/en-US/docs/web/http/cors#What_requests_use_CORS. 

**Actual result:**
![image](https://user-images.githubusercontent.com/53306802/101899872-2faf3e80-3bb7-11eb-87a4-c635256e9b91.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/53306802/101899908-3a69d380-3bb7-11eb-879f-fb16d883d82c.png)

**Comment by peterbe** [comment]
It's sad that we lost our styling for `blockquotes` in minimalist. Seems like a bug. @schalkneethling ?

However, what is going on with that article? If I wrote that I think I would have used `<pre>` instead since block quotes is supposed to be for, well, quotes. 
Considering that, perhaps we should throw this issue over to mdn/content to say that all use of `<blockquote>` should be replaced with `<pre>`.

**Comment by peterbe** [comment]
Or, perhaps it's more pressing. There's LOTs of use of `<blockquote>` in the active `en-US` content. 
```
MOZILLA/MDN/content  main ✔
▶ rg '<blockquote' | wc -l
      68
```

E.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt 
<img width="911" alt="Screen Shot 2020-12-11 at 2 04 22 PM" src="https://user-images.githubusercontent.com/26739/101943817-c7159100-3bb9-11eb-88a3-a0952b6e29cf.png">
That's very much a quote. 

In Yari:
<img width="887" alt="Screen Shot 2020-12-11 at 2 04 53 PM" src="https://user-images.githubusercontent.com/26739/101943881-e3193280-3bb9-11eb-9f71-07456fa7f076.png">

**Comment by mattiapontonio** [comment]
`blockquote`[•](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/blockquote) should have quotes `before` and `after`.

**Comment by mattiapontonio** [comment]
There Is a native HTML element for these `blocknote`?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element

**Comment by schalkneethling** [comment]
![Screenshot 2020-12-13 at 08 40 19](https://user-images.githubusercontent.com/10350960/102005099-d95d0f80-3d1e-11eb-8b79-1cf50a5b3915.png)

Resolved by https://github.com/mdn/mdn-minimalist/pull/369

**Comment by peterbe** [comment]
Why are block quotes allowed to be wider than the text? Seems incorrect.
<img width="1131" alt="Screen Shot 2020-12-13 at 4 38 52 PM" src="https://user-images.githubusercontent.com/26739/102024723-bb64ce80-3d61-11eb-9377-2bf0700f2981.png">

**Comment by mattiapontonio** [comment]
https://marcomm.nd.edu/blog/the-difference-between-blockquotes-and-pull-quotes/#:~:text=A%20blockquote%20is%20used%20in,from%20the%20text%20around%20it.&text=Pull%20quotes%20are%20made%20up,an%20attention-grabbing%20visual%20element.

- blockquotes
- pull-quotes

I should understand if you are talking about _pull-quotes_ or _blockquotes_.

**Comment by mattiapontonio** [comment]
https://github.com/mdn/mdn-minimalist/issues/374#issuecomment-744080310

**Comment by schalkneethling** [comment]
> Why are block quotes allowed to be wider than the text? Seems incorrect.
> <img alt="Screen Shot 2020-12-13 at 4 38 52 PM" width="1131" src="https://user-images.githubusercontent.com/26739/102024723-bb64ce80-3d61-11eb-9377-2bf0700f2981.png">

Yup, that was a bug. It is fixed now.
