### ISSUE TITLE
Table titles is not bold and some table borders are not well defined

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2076]
**Steps to reproduce:**
1. See https://developer.allizom.org/en-us/docs/web/javascript/guide/regular_expressions#Using_regular_expressions_in_JavaScript.
2. View 'Methods that use regular expressions' and 'Results of regular expression execution.' tables. 
3. Compare with tables in  https://developer.mozilla.org/en-US/docs/web/javascript/guide/regular_expressions

**Actual results:**

![image](https://user-images.githubusercontent.com/53306802/101914610-2df07580-3bcd-11eb-959d-6057dfb9919c.png)

Expected results:
The title being centered might be as intended, but table titles font could stand to be bold. 
Also it looks like some of the boarders between the 1st and 2nd column are not visible.
![image](https://user-images.githubusercontent.com/53306802/101914691-4791bd00-3bcd-11eb-973d-2996cc99543a.png)

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/issues/2100
