### ISSUE TITLE
BCD table is situated in the Examples section content instead of being set after Specification table

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2079]
**Steps to reproduce:**

1. Go to https://developer.allizom.org/en-us/docs/web/javascript/guide/regular_expressions#Using_special_characters_to_verify_input
2. Scroll through the Examples section. 
3. Compare to https://developer.mozilla.org/en-US/docs/web/javascript/guide/regular_expressions

**Actual results:** 
The BCD table is set in the Examples section. 
![image](https://user-images.githubusercontent.com/53306802/101915938-f256ab00-3bce-11eb-8fbe-9de8bed4f050.png)

**Expected result:**
BDC table is generally set after page text content and under Specification table.

**Comment by mattiapontonio** [comment]
Should the BCD have a _forced_ title via React template?

### Browser compatibility datas in a table

_Note: every word except the first is lowecase._

**Comment by schalkneethling** [comment]
This is no longer the case: https://developer.mozilla.org/en-US/docs/web/javascript/guide/regular_expressions#examples
