### ISSUE TITLE
Tools heading is missing

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2082]
1. Go to https://developer.allizom.org/en-us/docs/web/javascript/guide/regular_expressions#Examples/
2. Scroll to Result iframe and look at the links below. 
3. Compare to https://developer.mozilla.org/en-US/docs/web/javascript/guide/regular_expressions#Tools. 

**Actual result:**
![image](https://user-images.githubusercontent.com/53306802/101918168-bb35c900-3bd1-11eb-8fbe-b8631c032fa0.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/53306802/101918220-c4bf3100-3bd1-11eb-9593-3a7ccfc455ab.png)

**Comment by peterbe** [comment]
It was a content issue. The BCD table on that page wasn't situated at the root level. You can see what I had to do [here](https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions$compare?locale=en-US&to=1657724&from=1656837). The diff looks weird but I basically made it so the BCD table didn't sit within a `<div>` when it didn't need to. 
Curious that this was still happening and that I didn't notice last time I made a build.

**Comment by peterbe** [comment]
Actually, let's keep this open till it's possible to assert that it's fixed. Actually, at the time of writing, I'm running an import from the prod DB but it might not make it in the next prod dump. But by early next week we should be able verify that it has been solved in stage.

**Comment by schalkneethling** [comment]
Confirmed as resolved: https://developer.mozilla.org/en-US/docs/web/javascript/guide/regular_expressions#tools
