### ISSUE TITLE
h5 headings are not displayed as expected

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2083]
**Steps to reproduce:**
1. Open in browser https://developer.allizom.org/en-us/docs/web/html/element/input#name_and_radio_buttons and view headings. (What's in a name. name and radio buttons, HTMLFormElement.elements)
2. Compare to https://developer.mozilla.org/en-US/docs/web/html/element/input#name_and_radio_buttons

**Actual result:**
![image](https://user-images.githubusercontent.com/53306802/101920899-0d2c1e00-3bd5-11eb-976a-9e6de589f09c.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/53306802/101920956-1c12d080-3bd5-11eb-9754-726630279b6a.png)

**Comment by mattiapontonio** [comment]
I didn't mind the old titles but white on black it must be said that it is more standard.

**Comment by peterbe** [comment]
I guess @schalkneethling just needs to do whatever he did to `h4` to `h5` too.

**Comment by mattiapontonio** [comment]
> **Steps to reproduce:**
> 1. Open in browser https://developer.allizom.org/en-us/docs/web/html/element/input#name_and_radio_buttons and view headings. (What's in a name. name and radio buttons, HTMLFormElement.elements)
> 2. Compare to https://developer.mozilla.org/en-US/docs/web/html/element/input#name_and_radio_buttons
> 
> **Actual result:**
> ![image](https://user-images.githubusercontent.com/53306802/101920899-0d2c1e00-3bd5-11eb-976a-9e6de589f09c.png)
> 
> 
> **Expected result:**
> ![image](https://user-images.githubusercontent.com/53306802/101920956-1c12d080-3bd5-11eb-9754-726630279b6a.png)
> 

I was wondering if this old comparison thing can still be done after launch ...

**Comment by schalkneethling** [comment]
`h5` elements no longer use Zilla and as such are also not displayed as faux ZillaSlab headings. The current display is as intended. In terms of semantics and accessibility, those should not be `h5` headings at all but instead, be `h3` elements which would also restore the display.
