### ISSUE TITLE
Long <td> items do not fit in a single line in table column

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2085]
**Steps to reproduce:**
1. View https://developer.allizom.org/en-us/docs/web/html/element/input#Non-standard_attributes
2. Note the Attribute column items. 
3. Compare to https://developer.mozilla.org/en-US/docs/web/html/element/input#Non-standard_attributes

**Actual result:**
![image](https://user-images.githubusercontent.com/53306802/101921544-cd196b00-3bd5-11eb-8604-e0ea4bd3db19.png)

**Expected result**

![image](https://user-images.githubusercontent.com/53306802/101921646-e6221c00-3bd5-11eb-9fb1-46e227320eb5.png)

Not sure what the solution is here, or if there is a that does not compromise on consistency, 
A similar situation can be seen when comparing longer Method links. 
https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce#
![image](https://user-images.githubusercontent.com/53306802/101921981-3f8a4b00-3bd6-11eb-8583-5ac72769d203.png)

Another example:
https://developer.allizom.org/en-us/docs/web/html/element#Text_content

**Comment by mattiapontonio** [comment]
https://github.com/mdn/mdn-minimalist/issues/348

**Comment by peterbe** [comment]
@schalkneethling Why did you close this? Is there nothing we can do about these tables' first column looking so cramped. How did Kuma manage to get it right? Can we steal that?
<img width="1044" alt="Screen Shot 2021-01-12 at 6 40 07 AM" src="https://user-images.githubusercontent.com/26739/104310001-0547ee00-54a1-11eb-8f8a-6e0bd5191c14.png">

**Comment by peterbe** [comment]
I think we should re-open this and fix it.

**Comment by Ryuno-Ki** [comment]
@schalkneethling Ping

**Comment by Ryuno-Ki** [comment]
Thanks for reopening.

**Comment by schalkneethling** [comment]
This is being addressed in https://github.com/mdn/yari/pull/3527
