### ISSUE TITLE
Previous, Next and Overview buttons are misaligned one over the other and with no space in-between on non-English pages

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2089]
**Steps to reproduce:** 
1. Go to https://developer.allizom.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics and view buttons positioning. 
2. Change language to non-English, for example https://developer.allizom.org/fr/docs/Apprendre/Commencer_avec_le_web/Les_bases_JavaScript
3. Compare the buttons position. 

**Actual result:**
![image](https://user-images.githubusercontent.com/53306802/101934756-b2032700-3be6-11eb-80fb-e3573cb0a73a.png)

**Expected result:**
![image](https://user-images.githubusercontent.com/53306802/101934691-9c8dfd00-3be6-11eb-9f71-2de41d57c59b.png)

This also occurs on mobile, but there the default position for the buttons on english articles is one under the other so the only issue is the lack of space/ padding between them

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/issues/1957

**Comment by mirunacurtean** [comment]
Re-opening this issues as it occurs again on non-English locales. The 
https://developer.mozilla.org/de/docs/Web/JavaScript/Guide/Einf%C3%BChrung
https://developer.mozilla.org/ar/docs/Web/JavaScript/Guide/Introduction
https://developer.mozilla.org/fr/docs/Web/JavaScript/Guide/Introduction
https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Introduction

![image](https://user-images.githubusercontent.com/53306802/106499939-e8b03c00-64c9-11eb-8a73-584215d5b3ad.png)

**Comment by Ryuno-Ki** [comment]
I _think_ translated sites are currently on the back burner (if I get https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ correctly).

But perhaps worth to fill against mdn/mdn-minimalist ?
