### ISSUE TITLE
Main menu items are not translated when changing the language to non- English options 

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#2090]
Compare main menu from https://developer.allizom.org/zh-CN/docs/web/javascript 
with main menu from https://developer.mozilla.org/zh-CN/docs/web/javascript and notice that nothing in the Main menus has been translated in stage. 

Another set of steps is to load an English article page and change the language https://developer.allizom.org/en-US/docs/Web/HTML. 
Compared to the same page on developer.mozilla.org, notice that the the translated of the page content might be updated but not the main menus.

**Comment by Ryuno-Ki** [comment]
Related to #2038

**Comment by mattiapontonio** [comment]
https://github.com/mdn/content/issues/176

**Comment by escattone** [comment]
In Yari, we don't  translate the UI text strings based on locale. We may add this feature to Yar in the future.

**Comment by mattiapontonio** [comment]
@escattone of You Will open a repository for this translations please use kind of Array or numeric id so don't go to something like `STRING_FOR_THE_LABEL_INSIDE_THE_SECOND_FORM_FR` 🙂🙏
