### ISSUE TITLE
Figure out what to do with the Toolbar CRUD tools

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2092]
In https://github.com/mdn/yari/issues/1614 we decided to comment it out. 
That's a hurried solution. We should either delete it entirely or fix it properly. But the circumstances are weird. First, as of right now, we're pressed for time. Secondly, it's really early days to judge the usefulness of these things. Perhaps people are perfectly 100% happen and content to use the CLI tools inside mdn/content. Perhaps, there's some other more importnat CRUD tool they actually want/need. Perhaps the CRUD tools we have are fine, they just need to styled and fixed (e.g. no more `alert()` and `confirm()`)

Let's leave it for now and keep an eye on it. Eventually, it needs to either be completely removed (and the relevant parts in the server!) or fixed up. That's what this issue is about.

**Comment by caugner** [comment]
The CRUD tools have been removed in https://github.com/mdn/yari/pull/6065.
