### ISSUE TITLE
change logo to "MDN Web Docs"

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2094]
On https://developer.mozilla.org/en-US/
In the document title:
<img width="231" alt="Screen Shot 2020-12-11 at 3 27 27 PM" src="https://user-images.githubusercontent.com/26739/101951680-62f8ca00-3bc5-11eb-9a25-38f723e076da.png">

In the logo:
<img width="234" alt="Screen Shot 2020-12-11 at 3 28 08 PM" src="https://user-images.githubusercontent.com/26739/101951741-7f950200-3bc5-11eb-8a8f-e52d2a5386b2.png">

On https://developer.mozilla.org/en-US/docs/MDN
<img width="587" alt="Screen Shot 2020-12-11 at 3 28 39 PM" src="https://user-images.githubusercontent.com/26739/101951796-920f3b80-3bc5-11eb-935e-d3800a5e183a.png">

**Comment by peterbe** [comment]
Can we please be consistent? That's what I meant about this issue being about :)

**Comment by mattiapontonio** [comment]
I don't like too much _camel-spaced-case_ so I vote **MDN web docs** like the logo 🎨👨‍🎨

**Comment by schalkneethling** [comment]
It is meant to be `MDN Web Docs`

**Comment by vkWeb** [comment]
+1 for @schalkneethling's `MDN Web Docs`.

**Comment by Ryuno-Ki** [comment]
[Announcement](https://blog.mozilla.org/opendesign/future-mdn-focus-web-docs/) back then used `MDN Web Docs`.

**Comment by chrisdavidmills** [comment]
I would also say MDN Web Docs. It's not a normal sentence-cased title — the whole thing is a product name/"proper" noun.

**Comment by mattiapontonio** [comment]
It makes me think: let's say this string is a variable, can we get it right inside the logo? It would be nice to try entering "A list of repositories of web documentations" or something else and see what happens everywhere. However, maybe even just talking about it is fine.

**Comment by Ryuno-Ki** [comment]
The subdomain is `developer`, because it started of as „Mozilla Developer Network” (or MDN, for short).
So the main audience were developers. See also the press announcement I've linked before.

**Comment by mattiapontonio** [comment]
I know that changing the domain or URLs in general triggers SEO issues.

**Comment by peterbe** [comment]
So the issue here is indisputably that the logo needs to change. Cool. Let's do it.

**Comment by schalkneethling** [comment]
<img width="500" alt="logo@2x" src="https://user-images.githubusercontent.com/10350960/102049611-e266e300-3de9-11eb-82e4-af75e14b9f45.png">

@chrisdavidmills @HerminaC @escattone Thoughts? r+/-

**Comment by chrisdavidmills** [comment]
@schalkneethling lgtm

**Comment by HerminaC** [comment]
same - i like it, @schalkneethling

**Comment by mattiapontonio** [comment]
The distances between the letters, the edges, the dinosaur and the rectangles and squares could be evened out a little better.

**Comment by mattiapontonio** [comment]
> <img width="500" alt="logo@2x" src="https://user-images.githubusercontent.com/10350960/102049611-e266e300-3de9-11eb-82e4-af75e14b9f45.png">
> 
> @chrisdavidmills @HerminaC @escattone Thoughts? r+/-

The distances between the letters, the edges, the dinosaur and the rectangles and squares could be evened out a little better.
Especially the dinosaur was better before.
First of all, only the text should be changed, leaving the rest unchanged w obviously adjusting the width of the rectangle of the disputed name.

**Comment by schalkneethling** [comment]
![Screenshot 2020-12-14 at 13 46 40](https://user-images.githubusercontent.com/10350960/102077975-ce83a700-3e12-11eb-94f4-9b1c43c69603.png)

Those have been measured out to the millimeter in Illustrator.

**Comment by mattiapontonio** [comment]
> ![Screenshot 2020-12-14 at 13 46 40](https://user-images.githubusercontent.com/10350960/102077975-ce83a700-3e12-11eb-94f4-9b1c43c69603.png)
> 
> Those have been measured out to the millimeter in Illustrator.

Outside but not inside

**Comment by ddbeck** [comment]
Just a note here that this version doesn't actually contain the Mozilla logo (for starters it has the regular `i` and `/` glyphs instead of the fancy `Mozilla` ligature, with `://`). Might be a good idea to review https://mozilla.design/mozilla/logo-usage/ before changing from what we've got. It has a bunch of fussy details about proportions and such, which also look off to me in this new version.

**Comment by schalkneethling** [comment]
> Just a note here that this version doesn't actually contain the Mozilla logo (for starters it has the regular `i` and `/` glyphs instead of the fancy `Mozilla` ligature, with `://`). Might be a good idea to review [mozilla.design/mozilla/logo-usage](https://mozilla.design/mozilla/logo-usage/) before changing from what we've got. It has a bunch of fussy details about proportions and such, which also look off to me in this new version.

This actually uses ZillaSlab Highlight with the ligatures. This is not handmade.

**Comment by schalkneethling** [comment]
I see the `://` missing but this is what Illustrator produces. I wonder if there was an update to the font.

**Comment by schalkneethling** [comment]
Yup, there was an update

**Comment by mattiapontonio** [comment]
But handle that in Sass and leave the dinosaur alone in SVG? However, I really like the idea of the protocol-friendly logo.

**Comment by mattiapontonio** [comment]
Can't you deploy only the _logo + title + logo_ component on some location?

**Comment by escattone** [comment]
@schalkneethling I like it!
