### ISSUE TITLE
Flag missing syntax entries as flaw

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#2096]
Originally reported in https://github.com/mdn/content/issues/182, when an CSSSyntax macro shall be evaluated, but no property is defined, that page should be flagged as having a flaw.

**Comment by escattone** [comment]
Good idea, thanks @Ryuno-Ki!

**Comment by peterbe** [comment]
I think if you add some code to `CSSSyntax.ejs` to do something like:
```
if (someCondition) {
  throw new Error("write something descriptive here")
}
```
it will automatically become a `MacroExecutionError` flaw and should show up appropriately. 
Wanna try a PR to test this @Ryuno-Ki ?
We can help if you get stuck writing the end-to-end tests.

**Comment by Ryuno-Ki** [comment]
I'm currently in catch-up mode. I expect to have a bit more slack time in January.
A quick search didn't yield a `CSSSyntax` to be found in this repo. I'd need to familiarise myself with the codebase before I can tell, whether I can PR it.

So if someone else is picking up it before end of year, go on!
Otherwise I'll look into this in January 2021, if it's okay.

**Comment by mattiapontonio** [comment]
This is the file
https://www.github.com/mdn/yari/tree/master/kumascript%2Fmacros%2FCSSSyntax.ejs

But it's in `kumascript` folder.
Is that supported?
