### ISSUE TITLE
Setting note label via CSS

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2098]
Arguably those `strong` could be put in the before via CSS
![Screenshot_20201211-131347.png](https://user-images.githubusercontent.com/44380480/101902296-b9a8d880-3bb2-11eb-9ac3-003069a6744d.png)

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/issues/2074#issuecomment-743159338_

**Comment by mattiapontonio** [comment]
Are there any human languages ​​that use to quote with ()? 
For example: 

(It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.)
– **Albus Silente**

I do not know. 
In any case, a CSS in a tag in a template could perhaps be translated. 
You have to understand but it is a correct question. 👍

**Comment by mattiapontonio** [comment]
If you only want to use the quotes and not the notes, it may be reasonable. I only remember how many times a yellow note saved me but it can also be a good excuse to give a better sentence.

**Comment by Ryuno-Ki** [comment]
Perhaps I misread you, but my understanding would be, that you want to have something like this:

```css
.note::before {
    content: "Note: ";
    font-weight: bold;
}
```

Then, the `Note: ` of the `content` is not translatable. Sure, there are hacks (like putting the value into a `data-*` attribute and read it in CSS via `attr()`. But what good is it to have the `<strong>Note:</strong>` then?

**Comment by mattiapontonio** [comment]
When I see in publishing that something is repeated many times, I think we need to think of a solution to standardize it. I can't count how many strong there are, I think I've seen many. It is certainly a discussion. But if it were a shared rule it could be a value. I don't know for sure. The translation approach seems correct to me 👍

**Comment by mattiapontonio** [comment]
The old strong should be left double or removed with a regex, which on entire content I have never tried to search, let alone replace but it would be interesting (when I get my PC back and not a smartphone).

**Comment by mattiapontonio** [comment]
However it would take a PR so this maybe automatically adds a post launch to this thread

**Comment by mattiapontonio** [comment]
But this infamous Regex should be done on which repository? `mdn/content`?

**Comment by mattiapontonio** [comment]
And if I perform it then is it possible that something reconstructs me over HTML? 🤔

**Comment by mattiapontonio** [comment]
https://github.com/mdn/mdn-minimalist/issues/386

**Comment by peterbe** [comment]
Please rewrite the issue title to something that we can understand. Bug report or feature request. And why. Or else, let's close this.

**Comment by mattiapontonio** [comment]
@peterbe done
@schalkneethling can We implement this / move to minimalist.
So if a editor use the note class automatically get the label via CSS.

**Comment by mattiapontonio** [comment]
Ok i close and take this
https://github.com/mdn/mdn-minimalist/issues/386
