### ISSUE TITLE
no-inline-comments

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2099]
- https://www.github.com/mdn/yari/tree/master/.eslintrc.js
- https://eslint.org/docs/rules/no-inline-comments

Can We set some rules on comments?
I think there Is a way to ingore eventually.

i know that sometimes people use comments for Todo or something but i think that Se should use Issues and GitHub for comments.

JsDoc and other use of comments should be eventually preserved, i only "hate" something like:

```
// I do this because bla bla bla
// Todo fix me 👎
```

With respect of discussuons, but "not in the code" instead code review is hard.

**Comment by Ryuno-Ki** [comment]
Personally, I'm one of those developers, who put „TODO:” as comments into code.
Reasoning is, that I highlight „known issue” for those reading this particular piece of code. The comment often points to an issue with more details.

**Comment by mattiapontonio** [comment]
Ideally you should open an issue, edit, PR, CR, merge and automatic issue closing so ideally there should always be no code for open issues. All this naturally leads to a good opening of the issues so it would take issues to discuss without PR how to open good issues. However, the thing of the comments is not very important but I like it.

**Comment by mattiapontonio** [comment]
Another thing a bit like that. The search for known issues at least on the app is not in the flow of opening an issue. On Yari there are not even templates (and I would like it to remain so because an account is a form and an account is to delete 3 strings and then paste 1 from the cliboard and therefore forget the point 🙂). So in fact in my opinion the opening should be free as the closing is free. In short, it seems to me that there are permissions and roles to manage, this is also because I like how this system is made but it does not necessarily have to be the system of course.
