### ISSUE TITLE
nav.pagination

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2106]
Remove the center button between previous and after

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/issues/1957#issuecomment-743772555_

Maybe Is a React issue but Maybe there Is some Sass organism or atom in this area.

**Comment by mattiapontonio** [comment]
@schalkneethling ok.
I'm starting from the idea of pagination widthout pages but Just the `<<` and `>>`

https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook/Pagination

**Comment by mattiapontonio** [comment]
Added a issue for the recipe 👨‍🍳.
I like a clean 2 tags solution with 0 to N anchors.

https://github.com/mdn/sprints/issues/3963

**Comment by mattiapontonio** [comment]
_This is generated by a KumaScript macro but is "easy" to remove for active content that is regularly rebuilt using the latest Kumascript macros._

Actually i didn't dig into Kuma so i think "only new". Of course with time i Will dig more into the "data flow".

**Comment by peterbe** [comment]
This is labelled as "needs triage". **What is the question to discuss?** Can someone please summarize that down to one sentence. Or close this issue.
