### ISSUE TITLE
Production building without translated-content is a foot gun

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2130]
[These lines](https://github.com/mdn/yari/blob/cf05884701c8280abb99443f43fceb4c84ab4cc7/.github/workflows/prod-build.yml#L34-L37) allows you to make a production (or stage) build without building the translated-content. 
The problem is that the Sitemap XML index file (e.g. `/sitemap.xml`) that lists all actual sitemap XML URLs needs to be aware of all locales. 

If you were to press the manual "Run Workflow" button and type in `false` on the "Build translated content?" input, you'd end up with a `/sitemap.xml` files that fails to mention the other locales which would be bad for our SEO.

**Comment by peterbe** [comment]
Perhaps, for now, remove the foot gun. (note-to-self; team has been informed on Slack)
...until we figure out a way to merge partial builds. 
Or, we can make the code that generates the XML files become aware of `CONTENT_TRANSLATED_ROOT` and if it's falsy it just opts out of making the xml files because the way we upload to S3 is append-only.

**Comment by Ryuno-Ki** [comment]
You could split up the Sitemap by language and use `<loc>` tags:
https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps

Then, partial builds would only replace the sitemap for that locale (assuming, the global sitemap is already aware of that locale).

**Comment by mattiapontonio** [comment]
FTR https://developer.allizom.org/sitemap.xml
https://developer.mozilla.org/sitemap.xml

**Comment by Ryuno-Ki** [comment]
You could [tweak it some more](https://www.sitemaps.org/protocol.html) by using `<lastmod>` and `<changefreq>` (in case you can determine / estimate those).

**Comment by Ryuno-Ki** [comment]
Ah, wait. `changefreq` is for `<url>`s. But `<lastmod>` is specified for `<loc>`s, too.

**Comment by peterbe** [comment]
`sitemap.xml` is an index of other sitemap URLs. It's generated based on what was built.

**Comment by Ryuno-Ki** [comment]
Got that.
My thought was, that it could remain more or less static, and only the referenced sitemaps gets regenerated on build.

**Comment by peterbe** [comment]
That'd be one of the possible solutions. It's not complicated. Just adds to the complexity and it's important to remember that right now it's a foot gun.
