### ISSUE TITLE
Add GitHub labels for main HTML tags so page sections

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2132]
## Example
- `article` 🟡
- `header` 🔵
- `footer` ⚫
- `main` 🔴
- `nav` ⚪
- `aside` 🟠
- `section#github` 🟢 

Free choice of colors.

**Comment by schalkneethling** [comment]
@mattiapontonio Do you mean Github issue labels? Is this so that issues can be categorized by section?

**Comment by mattiapontonio** [comment]
Yes. It might be an idea. Obviously, the issues and the project are connected and complex, but for example, I think about the SERP and I get involved with issues, thinking about the article, others and so on. The labels can also be 2+

**Comment by mattiapontonio** [comment]
This issue cannot be closed with a PR so if you want we can close it. I only had this place to offer it.
