### ISSUE TITLE
Use deprecation flag from BCD

### ISSUE THREAD

**Issue by saschanaz** [mdn/yari#2138]
Currently [MDN has a separate deprecation tag and the header](https://github.com/mdn/content/blob/cbe151a06d6e5b4d1fbb46081bd16e69ef4c1630/files/en-us/web/api/htmlmarqueeelement/index.html). Could it use the `deprecated` flag from BCD and autogenerate such header, so that there won't be two separate source of truth?

(BTW, is the Deprecated tag still a thing in Yari? I don't see it rendered anywhere, except the header.)

**Comment by mattiapontonio** [comment]
I did not understand if you intend to pass the data in query string from the links of the BCD to the next page or fetchare 2 times the data of the BCD, 1 time for the page and 1 time for the table.

**Comment by saschanaz** [comment]
> Where does the data come from?

It's from:

https://github.com/mdn/yari/blob/dc823a0db5f2f321592d7b20cc109232120ee2b0/package.json#L33

**Comment by mattiapontonio** [comment]
Intresting issue for do matching things.
So... Should be intresting a little table on top of the page for `status` key.

https://github.com/mdn/browser-compat-data/blob/4c50bfdf43261a67d00b830fb0cd3a316a286400/api/HTMLMarqueeElement.json#L46

**Comment by saschanaz** [comment]
I'd rather keep the current design.

* Deprecated header example: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMarqueeElement
   ![image](https://user-images.githubusercontent.com/3396686/102727022-6574c580-4323-11eb-84d8-8c93a8d048b3.png)
* Experimental: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/resetTransform
   ![image](https://user-images.githubusercontent.com/3396686/102727103-f51a7400-4323-11eb-820c-aff45d6ea8b5.png)
* Nonstandard: https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawWidgetAsOnScreen
   ![image](https://user-images.githubusercontent.com/3396686/102727091-e59b2b00-4323-11eb-9b32-9e19a4f36f7f.png)

**Comment by mattiapontonio** [comment]
Ok. 
Is possibile and everytimes defined that You can access these 3 booleans knowing only the page URI and the main import of the dependency in the package.json?

**Comment by saschanaz** [comment]
Yes, it's fairly straightforward. Say the URI is `/API/Foo/Bar`, the corresponding BCD item is in `api.Foo.Bar`.

Maybe https://github.com/mdn/kumascript/blob/master/macros/Compat.ejs should be partially copied to something like `Status.ejs`.

**Comment by mattiapontonio** [comment]
I like to rename things. However, I think that by referring to the page some function should return the JSON file and then from there export either the initial table with the status or the BCD in order not to replicate the logic of the mapping between repositories. 

I also think about additional services on the feature URL that return fractions of JSON. 

[Api/Foo/Bar/status]() > returns an object

In any case I can't put comments on the Kumascript macro but only on the PR.

**Comment by mattiapontonio** [comment]
I also think that instead of being imported the BCD data could be deployed and retrieved on top of the page.

**Comment by saschanaz** [comment]
You mean something like this? 👀 https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/drawWidgetAsOnScreen/bcd.json

**Comment by mattiapontonio** [comment]
Questionable because we see that it was born for compatibility and hanin more status and there is also something that speaks of HTML titles 🤔 I imagine something similar but slightly revised to represent the page and therefore also the table.

**Comment by mattiapontonio** [comment]
Could this data pass via some `meta` before going to the `article`?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

**Comment by saschanaz** [comment]
I think fetching twice is okay as the response will be cached.

**Comment by mattiapontonio** [comment]
### Draft of a PR
```
const url = new URL ();
Object.assign(url, {
// Something known in the global scope
};
fetch(url)
.then(response=>response.json())
.then(body=>{
 // Todo update the state of the component with the status Key and some if statments
})

```

**Comment by schalkneethling** [comment]
@ddbeck Thoughts? Close?

**Comment by ddbeck** [comment]
@schalkneethling There's a bit to unpack here. This discussion captures some of the issues involved: https://github.com/mdn/content/discussions/5549. That said, the underlying idea: drive this stuff from BCD is a good idea. But there's two distinct tasks that would come from this:

- Generate usage ("traffic light") banners based on support and statuses (standard track, experimental, and deprecated). This would be a bit of a content/design/engineering effort.
- Remove existing macros and tags. A content effort, after the previous step.

Not sure if we should open separate issues, hijack this one, or what. Also related: https://github.com/mdn/yari/issues/1400#issuecomment-961880928

**Comment by schalkneethling** [comment]
@ddbeck Almost sounds like creating 2 separate issues with a clear definition of work makes more sense. We can the prioritise them along with all of the other items we have.

**Comment by caugner** [comment]
Closing in favor of duplicate https://github.com/mdn/yari/issues/3929.
