### ISSUE TITLE
Remove hidden Deprecated span from BCD tables

### ISSUE THREAD

**Issue by saschanaz** [mdn/yari#2139]
Finding a word "Deprecated" in the [HTMLMarqueeElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMarqueeElement) document reports 19 matches but only 2 matches are visible, and remaining 17 matches are hidden in BCD. Could they be completely hidden by `display: none` or `visibility: hidden` for example?

**Comment by mattiapontonio** [comment]
I love design and icons but in this case I have to associate with other strings that I have in my memory I prefer to read, so I would like 19/19 visible strings.

**Comment by peterbe** [comment]
I don't think BCD tables include that visually hidden `<span>` anymore.
