### ISSUE TITLE
Move the `.scss` to minimalist

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2140]
I know you need to have the flexibility to use `.scss` without waiting for a release but maybe you should move Sass to minimalist every now and then. Even just moving without analysis in a good minimalist spot to fix the room a bit. I've circled 2.

![Screenshot_20201214-224703.png](https://user-images.githubusercontent.com/44380480/102142923-72953e80-3e63-11eb-8161-bf0c6a12e8dc.png)

Personally I don't know how to preserve history I asked myself but we must also ask ourselves if it is important to preserve it since it seems to me to understand that everything can be managed there so via issue 🤷🏻‍♂️

https://github.com/mdn/mdn-minimalist

**Comment by schalkneethling** [comment]
minimalist is meant to serve as the basis for many things MDN flavoured but, is only meant to provide the basics, the atoms if you will. The SCSS that is added in Yari are those pieces that is needed specifically for the components and is why it lives right next to the relevant component. There should be no syncing between the two in the way suggested here.

**Comment by mattiapontonio** [comment]
I don't want to insist but I can't see a technical reason not to and the atoms aren't actually defined in any documentation that I know of, they seem like a conceptual facilitation to me. I believe that when Yari components are needed in other places, they will be forgotten and reimplemented causing duplication of code. I don't know if Yari can expose them to the maximum to be imported more. But it's not serious. Thanks.

**Comment by mattiapontonio** [comment]
In the end, minimalist is just a folder somewhere else if you like.
