### ISSUE TITLE
HTML in <h3> tags is lost

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2153]
![Screenshot_20201214-214721.png](https://user-images.githubusercontent.com/44380480/102133920-25f73680-3e56-11eb-858b-59a6791758af.png)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

**Comment by schalkneethling** [comment]
> Interesting. What's happening here is that these headings are supposed to have a "non standard" icon inside them, but instead the icon hasn't shown up and the icon's `title`has been included as text instead.
> 
> @schalkneethling can you look into this at some point?

Sure, I guess these are rendered with a macro so, the problem most likely originates there.

**Comment by schalkneethling** [comment]
@mattiapontonio when you say "In the mode without CSS" do you mean if you disable CSS?

**Comment by mattiapontonio** [comment]
@schalkneethling should be Reader View

**Comment by peterbe** [comment]
What's going on is not that it's not just an icon, but the raw KS HTML is turned into HTML, which looks like this:
```html
 <h3 id="incremental_This_API_has_not_been_standardized">
   <strong id="attr-incremental"><code>incremental</code></strong> 
  <svg class="icon non-standard" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" role="img">
  <title>This API has not been standardized.</title>
<path d="M50 92.5H6.09a4.47 4.47 0 01-3.87-6.71l22-38 22-38a4.46 4.46 0 017.74 0l22 38 22 38a4.47 4.47 0 01-3.87 6.71z"/>

     <path d="M57.41 78.1A7.41 7.41 0 1150 70.7a7.39 7.39 0 017.41 7.4zm-2.14-14.89H44.81l-1.72-36h13.82z" fill="#fff"/>
  </svg></h3>
```

But then, when Yari post-processes the KS rendered HTML, it transforms this HTML by essentially extracting the **text** from the `<h3>...` to the `...</h3>` as a human would have read it. And then it logs this as a structure `h3` thing and finally renders it, in React, back to a plain text. 

I think the simple solution is to support HTML inside the text of `<h2>` and `<h3>` tags. At least `<h3>` tags.

**Comment by peterbe** [comment]
There's still a LOT of HTML inside the `<h3>` (and `<h2>` tags too, but less) that is currently not displayed. 

Before proceeding too much here, let's wait for these to land:

1. https://github.com/mdn/content/pull/375
2. https://github.com/mdn/content/pull/376
3. https://github.com/mdn/content/pull/377

**Comment by mattiapontonio** [comment]
Another solution could be the opposite, that is to not support HTML within the headers and study new sections for this information since in fact they are not part of the header but of the section of which the header is part. They could be brothers and not children of the header.

**Comment by mattiapontonio** [comment]
As i said in another issue even `incremental_This_API_has_not_been_standardized` should be moved one level up.

**Comment by mattiapontonio** [comment]
Note that the fact that they are links in this mode also causes these titles to be shown with a small font size and not a larger one.

**Comment by peterbe** [comment]
> o not support HTML within the `h`eaders

But there are so many already. History is not our friend in this case.

**Comment by mattiapontonio** [comment]
> > o not support HTML within the `h`eaders
> 
> But there are so many already. History is not our friend in this case. 

However, I understand the developers who are emerging now could thank us. And the editors + regex would have issues ... To think about, perhaps to be referenced in content.

**Comment by mattiapontonio** [comment]
We should wait deploy to close issues...

![Screenshot_20210122-141312.png](https://user-images.githubusercontent.com/44380480/105495084-03a9d180-5cbc-11eb-8ac2-e78a456f8075.png)

Nothing changed here.
Is a content issue?

**Comment by peterbe** [comment]
It works!
<img width="902" alt="Screen Shot 2021-01-22 at 9 36 33 AM" src="https://user-images.githubusercontent.com/26739/105504088-5a4fe500-5c95-11eb-8769-fffc8b1020e3.png">

**Comment by mattiapontonio** [comment]
@peterbe _my cache bad_.
Yes It works! 👍
Thanks

![Screenshot_20210122-154218.png](https://user-images.githubusercontent.com/44380480/105504883-92bce680-5cc8-11eb-9046-a62f5db9ab05.png)
