### ISSUE TITLE
Mobile View On Larger Viewport

### ISSUE THREAD

**Issue by zcdunn** [mdn/yari#2155]
I'm using Firefox with a viewport of 1090px and I'm getting what looks like a mobile view. There's no sidebar, making it hard to jump to other sections or see the _Related Topics_ list.

**Comment by mattiapontonio** [comment]
@zcdunn can You screenshot?

**Comment by zcdunn** [comment]
Here you go
![image](https://user-images.githubusercontent.com/7121969/102269138-378a1e00-3eea-11eb-9f4c-064e8ef57cb7.png)

**Comment by mattiapontonio** [comment]
Strange white space

![Screenshot_20201215-214708.png](https://user-images.githubusercontent.com/44380480/102271078-24457580-3f1f-11eb-9e6e-2c73cb30113b.png)

**Comment by zcdunn** [comment]
Yes that entire section is mostly unused, except where code blocks, asides, and tables stretch into it.

![image](https://user-images.githubusercontent.com/7121969/102271608-9d2bd980-3eed-11eb-9178-d4cb4afec38f.png)

![image](https://user-images.githubusercontent.com/7121969/102271446-6e156800-3eed-11eb-8ed4-b5dc7ec234f2.png)

**Comment by mattiapontonio** [comment]
In my opinion some elements need to have an `overflow-x: scroll` and others need to have a wrapper with the same overflow. 
A maximum `width` of `100%` is intended but many elements have `auto`matic `width`.
This fixes the problem "permanently". Then that on mobile the tables are too long horizontally is another discussion that is part of discussing the tables.
This argument is valid as you show by the problem even if the viewport `width` remains large and the columns get smaller. 
So the problem is not to be found in the _media queries_ but in the `display` of the elements (possibly `flex`).

**Comment by peterbe** [comment]
Isn't that a good thing? It's known that it's hard to read text when the lines are too long. It gets harder to track and find the next line if you basically have to twist your next to get from all-the-way right to all-the-way left + one line down. 

Am I missing something? Are you saying you would have preferred even longer lines for the paragraphs?

**Comment by zcdunn** [comment]
I don't think the length of text lines is an issue here. You can see in the screenshots that the lines wrap at a decent width. The issue is that it's a single column view instead of two columns. The sidebar with methods, related topics, etc should be in a column on the left.

**Comment by mattiapontonio** [comment]
First that column you see should be a column. And then secondly you could squeeze it to make room on the right to `aside`.

**Comment by mattiapontonio** [comment]
https://github.com/mdn/sprints/issues/3969

**Comment by schalkneethling** [comment]
@zcdunn Ah yes. So essentially the sidebar you have open is limiting the available space MDN has in terms of the overall browser viewport, as such, it is using the layout used for tablets in portrait mode.

We need to juggle a number of things when deciding how to handle breakpoints, and maintainability is one of them. Having to many breakpoints has bit us in the past and so, we have limited those. With regards to the sidebar specifically. It is a pain point for us, and something we do want to improve upon.

For right now, I am going to close this one but, to know that we are keeping track of these issues and will keep this in mind when we make future improvements to the MDN Web Docs UI. Thank you for taking the time to log this issue.

**Comment by zcdunn** [comment]
> Ah yes. So essentially the sidebar you have open is limiting the available space MDN has in terms of the overall browser viewport, as such, it is using the layout used for tablets in portrait mode.

I understand why it's happening, but this size is large enough to have multiple columns. The previous version of MDN well within this size. I'm not sure I understand your last statement. If this issue is closed, where is this being tracked?

**Comment by mattiapontonio** [comment]
We should experiment but it is possible that using flexbox you can create the responsive effect without having to change the rules on breackpoints.

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox

**Comment by schalkneethling** [comment]
@zcdunn We launched a bit of a refresh for the docs pages. The below is what I now see on a screen with a width of 1024px. Has this improved the experience for you? I remember you mentioned you often browser at 1090px

![Screenshot 2021-03-04 at 11 20 55](https://user-images.githubusercontent.com/10350960/109941318-b3228c80-7cdb-11eb-8b31-b9007ee0f9c6.png)

**Comment by glacambre** [comment]
@schalkneethling I'm not @zcdunn, so if you specifically care about their input feel free to disregard what I have to say ;)

I use a tiling window manager on a 1920x1080px screen. When I open two windows, they each get half of a screen (960px, minus 2px borders on each side, so my viewport is actually 956px wide). MDN still hides the "related topics" column for me, which is a shame because I use it a lot. It' be really nice if MDN could keep showing the sidebar as long as there's more than 800 or 900 pixels available.

But at the same time, tiling window manager users probably are a minority among MDN users so feel free to ignore me if it doesn't seem doable :).

**Comment by zcdunn** [comment]
@schalkneethling I don't see any change. I still get a mobile view with a large empty column on the right.

**Comment by Ryuno-Ki** [comment]
> But at the same time, tiling window manager users probably are a minority among MDN users so feel free to ignore me if it doesn't seem doable :).

o/

Using AwesomeWM on one machine. Or side-by-side feature of Desktop Environments (like Mate, here).

**Comment by schalkneethling** [comment]
> @schalkneethling I don't see any change. I still get a mobile view with a large empty column on the right.

I just tested at 1024px and I get the desktop layout. Can you please test again on your side?

@glacambre To answer your question. Keeping the desktop layout below 1024 is going to be a tight squeeze 😃 

With that said, I do have an idea of how we can surface the related topics better on tablet-sized devices which I will raise in a separate issue. Thank you for your feedback.

**Comment by zcdunn** [comment]
@schalkneethling Sorry for the delay. I tried again and now I get the table of contents on the left and the main content on the right. Thank you!

**Comment by schalkneethling** [comment]
> @schalkneethling Sorry for the delay. I tried again and now I get the table of contents on the left and the main content on the right. Thank you!

Thank you so much for checking again @zcdunn
