### ISSUE TITLE
The callout-box class is missing styling

### ISSUE THREAD

**Issue by akozdev** [mdn/yari#2158]
The callout-box class is missing styling. Link and a screenshot attached below
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode
![calloutbox](https://user-images.githubusercontent.com/51536161/102330977-84253600-3f8a-11eb-8922-abbaff2e7721.png)

**Comment by schalkneethling** [comment]
I did not even know we had these:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode

![Screenshot of callout-box styling](https://user-images.githubusercontent.com/10350960/104204256-bca71b00-5435-11eb-896f-eac1126a18a8.png)

**Comment by mattiapontonio** [comment]
![Screenshot_20210111-172930.png](https://user-images.githubusercontent.com/44380480/104209948-96cc4700-5432-11eb-99d2-974614cc8b5c.png)

I see that.
But this should be something standard or a info note.

**Comment by schalkneethling** [comment]
Being addressed here: https://github.com/mdn/content/issues/1660

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/content/pull/1661
