### ISSUE TITLE
Raw and summary parameters no longer supported

### ISSUE THREAD

**Issue by piotrtomiak** [mdn/yari#2161]
JetBrains IDEs (WebStorm, IntelliJ IDEA, PhpStorm, etc.) heavily depend on the `raw&summary` parameters (e.g. [https://developer.mozilla.org/pl/docs/Web/HTML/Element/div?raw&summary](https://developer.mozilla.org/pl/docs/Web/HTML/Element/div?raw&summary)) to fetch HTML or JavaScript documentation for millions of developers. With the release of the new Yari platform, the parameters seem to be no longer supported, and our code stopped working. Previously we would fetch following content for the above link:
```
The <strong>HTML Content Division element</strong> (<strong><code>&lt;div&gt;</code></strong>) is the generic container for flow content. It has no effect on the content or layout until styled using <a class="glossaryLink" href="/en-US/docs/Glossary/CSS" title="CSS: CSS (Cascading Style Sheets) is a declarative language that controls how webpages look in the browser.">CSS</a>.
```
which then was cached forever on the drive (limits the exposure of the issue to some level) and rendered in quick documentation popup. Is it possible to provide support for these parameters again?

**Comment by piotrtomiak** [comment]
On a side note, the `README.MD` looks to be outdated, as I am unable to successfully configure server locally so the documentation is rendered. I keep getting 404s.

**Comment by peterbe** [comment]
`/en-US/docs/Web/HTML/Element/div/index.json` only works when you use `localhost:5000`. 

Besides, you can get the summary from `.doc.summary` in https://developer.mozilla.org/pl/docs/Web/HTML/Element/div/index.json or you can scrape it from the view-source:https://developer.mozilla.org/pl/docs/Web/HTML/Element/div by looking for the `meta[name=description]`. tag.

**Comment by piotrtomiak** [comment]
@peterbe I've finally managed to run the content on localhost. I am not really sure why it didn't work before.

Anyway, the problem is that the functionality has been in our IDEs for several years already and there is no way for us to update all of these older versions. It turns out that it not only affects our HTML documentation, but also JavaScript one. And I don't think we are the only ones, who depend on these parameters. 

Summary from `.doc.summary` is without any tags, so it's not feasible to use and scraping HTML is pretty bad idea, as users would experience problems when anything changes in the HTML format.

I am willing to contribute support for these parameters, would such a PR be accepted?

**Comment by piotrtomiak** [comment]
I've created a PR, which solves the problem. I would appreciate a timely review to reduce documentation provision downtime.

**Comment by escattone** [comment]
Hi @piotrtomiak,

I'm sorry that the lack of support for these query parameters has affected JetBrains IDEs. When we launched this new platform for MDN Web Docs, we dropped support for all query parameters on document pages, and for multiple reasons. First, we've always considered these query parameters for internal use only, and if used publicly, for use "at your own risk". Second, with our new approach, we pre-build our document pages, upload them to S3 and serve them via a CDN (the JAMStack approach), so supporting the same query parameters complicated that approach enough that we decided it wasn't worth the effort.

So in short, this is not something we plan to support or work on, and your [pull request](https://github.com/mdn/yari/pull/2162) doesn't resolve the problem. It's much more complicated than that. For example, your pull request only addresses the local preview service (and even then has some problems that would have to be addressed), and doesn't address the more serious issue of having to pre-build multiple versions of the same document (based on the combinations of query parameters).

However, with all of that said, perhaps we can discuss possible ways forward once our team returns from our holiday break in early January. Unfortunately, we don't have time before then.

**Comment by piotrtomiak** [comment]
Hi @escattone, 

Thank you for your response! I understand and it indeed looks like we have to fix this on our side. Is `index.json` content going to be stable, or is it again something considered internal? 

Is it possible for you to return 404 for URLs ending with `?raw&summary`? That would help to minimize severity of the issue among our users - instead of rendering the full page in the quick doc popup, which causes performance issues, it would be just empty.

**Comment by escattone** [comment]
Hi @piotrtomiak,
Thanks for your understanding. Let me look into both of your questions and get back to you soon.

**Comment by escattone** [comment]
Hi @piotrtomiak,

> Is index.json content going to be stable, or is it again something considered internal?

This is something that is considered internal, so please don't rely on it.

> Is it possible for you to return 404 for URLs ending with ?raw&summary?

We looked into doing this for you today, but we didn't feel comfortable changing several pieces of our infrastructure  right before most of the team leaves for the holiday break for the next two weeks. Let's connect again when we return the week of Jan. 4th, and we can either do something like you're suggesting (return a 404 for URL's ending with `?raw&summary`) or consider something else.

Thanks again for your understanding.

**Comment by peterbe** [comment]
@piotrtomiak Do you have a public bug tracker URL for the change to switch away from the old URL?

Ryan is right in that the `index.json` is an internal feature. There are no guarantees with any of the content actually. The only thing we guarantee is the ability to view it in your browser on the modern browsers. 

Having said that, the `/index.json` URL is going to be stable. Similarly to the `/contributors.txt` URL. 
What would probably be better is if you can proxy all requests for fetching the summary. Or that you run the Yari builder, as part of your build process and check in a (huge) JSON file of all the summaries. But attribution still needs to exist back to MDN and the https://developer.mozilla.org domain.

**Comment by piotrtomiak** [comment]
@peterbe The issue is handled here: https://youtrack.jetbrains.com/issue/WEB-48715. I have implemented a hotfix to use  `index.json` for now, but to avoid any further issues we plan to bundle the documentation with the IDE: https://youtrack.jetbrains.com/issue/WEB-48771. 

@escattone Thanks for looking into this! I understand that if you don't have something similar in place, changing stuff before holidays it's not the best thing to do :) Let's sync after New Year.

**Comment by peterbe** [comment]
For now, I'm going to close it. The depth of this issue discussion was important and interesting, but matching the issue-title with what we're doing and going to do means this issue should resolve since, yes, `raw` and `summary` parameters are no longer supported.

**Comment by mattiapontonio** [comment]
It occurs to me that requesting a `Content-Type: json` on the URL could return the _representation_ of the document in JSON.
