### ISSUE TITLE
Some content's folders and slugs contain zero width space unicode character

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2171]
In particular https://github.com/mdn/content/blob/main/files/en-us/web/api/paintworklet/paint%E2%80%8Bworklet%E2%80%8B.device%E2%80%8Bpixel%E2%80%8Bratio/index.html

Here's what it looks like when I open it with `less` in my macbook:

<img width="685" alt="Screen Shot 2020-12-16 at 4 21 14 PM" src="https://user-images.githubusercontent.com/26739/102407832-ba7aa980-3fba-11eb-8dd7-6e640e3441ed.png">

I know we have some code somewhere that crashes the build if the folder or slug contains spaces. That clearly isn't enough. 

[About the zero width unicode character](https://www.fileformat.info/info/unicode/char/200b/index.htm).

**Comment by peterbe** [comment]
I initially filed this in `mdn/content` but realize this is Yari's problem. Once we have a solution in place, it would immediately bust the next build because, hopefully, running a complete build would/should crash so once that's in place, let's go back to the `mdn/content` (and `translated-content` and maybe `archived-content`) to manually clean up any that are still stuck with these characters.

**Comment by mattiapontonio** [comment]
Sometimes this class remove/changhe things in a good way of used and the members are well named.

https://developer.mozilla.org/en-US/docs/Web/API/URL/URL
