### ISSUE TITLE
The Russian translations have broken links

### ISSUE THREAD

**Issue by MeFoDy** [mdn/yari#2173]
I can't open the page https://developer.mozilla.org/ru/docs/Web/SVG/Tutorial/Основные_Фигуры (Russian version of https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Basic_Shapes). The error message is `Sorry, the page /ru/docs/Web/SVG/Tutorial/%D0%9E%D1%81%D0%BD%D0%BE%D0%B2%D0%BD%D1%8B%D0%B5_%D0%A4%D0%B8%D0%B3%D1%83%D1%80%D1%8B could not be found.`.

I see the source of the page here: https://github.com/mdn/translated-content/blob/main/files/ru/web/svg/tutorial/основные_фигуры/index.html

**Comment by peterbe** [comment]
Not sure if it's related but https://developer.mozilla.org/en-US/docs/Glossary/B%C3%A9zier_curve is working fine. 

https://developer.mozilla.org/en-US/docs/Glossary/Bézier_curve

Doesn't seem to matter if you URL-encode the link or not, it works.

**Comment by peterbe** [comment]
I don't think we should put too much time into this. The bestest solution would be to rewrite ALL translated slugs to their `translation_of` equivalent (Hi @fiji-flo @escattone ) and put all the existing `slug` values (where `slug != translation_of`) in their respective `_redirects.txt`. 
This is something we should be able to do soon. Ideally the minute switch from `translated-content-rendered` to `translated-content`.

**Comment by peterbe** [comment]
@escattone Here's another one https://developer.mozilla.org/ru/docs/Learn/HTML/Введение_в_HTML
Do these work in local dev when you enable CONTENT_TRANSLATED_ROOT?

**Comment by escattone** [comment]
FYI, this is due to https://github.com/mdn/yari/issues/2522.

**Comment by escattone** [comment]
This is resolved. Thanks again for reporting this @MeFoDy!

**Comment by escattone** [comment]
Just FYI. I updated the `dev`, `stage`, and `prod` CloudFront instances to use the new Lambda@Edge function from https://github.com/mdn/yari/pull/2545.
