### ISSUE TITLE
Compat table: adjust wording for issue reporter link?

### ISSUE THREAD

**Issue by vinyldarkscratch** [mdn/yari#2183]
First off, congrats to the Yari team for all of your hard work over the year!  I saw the new system live, and I believe all the hard work really paid off.  😄 

I noticed that there is now a link to report an issue with the compat table data right away, which creates an issue pre-filled with data regarding the page.  However, there's been a few issues opened in BCD that are referring to the page examples or content.  I believe users may be getting confused with the wording, and are thinking that "this data" means the entire page.  Perhaps something more like "Report problems with browser compatibility data on GitHub" would be better?

**Comment by peterbe** [comment]
"...with this browser compatibility data..." ?

CC @ddbeck 

I'm happy to make a fix if you and Daniel pick one. Or, just make a PR and we can look at it there.

**Comment by ddbeck** [comment]
I'm skeptical that this will actually prevent the problem, but I opened #2205. I suspect the real solution to this is going to be getting in the habit of transferring issues from mdn/browser-compat-data to mdn/content, or coming up with a canned response for closing such issues.
