### ISSUE TITLE
WebExtAPISidebar uses part after first dot in title page instead of last part

### ISSUE THREAD

**Issue by ariasuni** [mdn/yari#2189]
I started working on mdn/content#336 but I noticed that when tagging properly e.g. [`devtools.panels.create()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.panels/create), the sidebar thinks `panels` is the name to use for the sublist instead of `create()`.

You can reproduce with my PR mdn/content#372 by going to e.g. [`devtools.network` page](http://localhost:5000/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.network).

I believe the issue is in this code:

https://github.com/mdn/yari/blob/058ed1836ab5968fb4fb48f3599e52525415b793/kumascript/macros/WebExtAPISidebar.ejs#L44

which should be:

```js
apiComponentName = titlePieces[titlePieces.length - 1];
```

I tried to make a PR but changing the `WebExtAPISidebar.ejs` didn’t seem to affect the rendered page. I noticed that `nodemon` didn’t listen for ejs files but even after relaunching `yarn dev` it still gave me the wrong results.

**Comment by chrisdavidmills** [comment]
Can we get a little help here @escattone ?

**Comment by peterbe** [comment]
That's confusing as hell. We start `nodemon` like this:
```
nodemon server --watch server --watch build --watch content --watch kumascript
```
That's what `yarn start:dev-server` does. 
But I think `nodemon` doesn't know that it should trigger if you edit a `.ejs` file. 
I see that `nodemon` has the `-e` flag:
```
▶ nodemon --help
  Usage: nodemon [options] [script.js] [args]

  Options:

  --config file ............ alternate nodemon.json config file to use
  -e, --ext ................ extensions to look for, ie. js,pug,hbs.
...
```
Need to figure out how to get that right because there might be other things other than just `.ejs` we need to add. 

Besides, I would recommend you use http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools.network instead of `:5000` since that'll re-render the React code too and that enables things like the Toolbar which is useful for displaying flaws.

**Comment by peterbe** [comment]
@ariasuni Can you take a look at https://github.com/mdn/yari/pull/2211 ?
It certainly fixes the problem from before. I now see it reloading when I make an edit in a `.ejs` file. 
Confusing, it appears to say that it restarts twice. 
```
10:48:49 AM server.1    |  [nodemon] restarting due to changes...
10:48:49 AM server.1    |  [nodemon] starting `node server`
10:48:49 AM server.1    |  [nodemon] restarting due to changes...
10:48:49 AM server.1    |  [nodemon] starting `node server`
```
but I don't think it matters. 

Anyway, to tie you over you can also just open any other `.js` file and Ctrl-S to trigger a nodemon to get yourself unstuck on fixing this `WebExtAPISidebar.ejs` macro.

**Comment by escattone** [comment]
> I believe the issue is in this code:
> 
> https://github.com/mdn/yari/blob/058ed1836ab5968fb4fb48f3599e52525415b793/kumascript/macros/WebExtAPISidebar.ejs#L44
> 
> which should be:
> 
> ```js
> apiComponentName = titlePieces[titlePieces.length - 1];
> ```

@ariasuni Nice work! You're absolutely right here, that is the fix. Would you like to submit a PR for that? We can do it if you'd prefer, but you should get the credit! 😃 

> I tried to make a PR but changing the WebExtAPISidebar.ejs didn’t seem to affect the rendered page. I noticed that nodemon didn’t listen for ejs files but even after relaunching yarn dev it still gave me the wrong results.

I found the I had to stop and restart the development server in order for my changes to the `WebExtAPISidebar.ejs` macro to be recognized. The fundamental problem is that EJS itself caches the source code of the macros as they are run:

https://github.com/mdn/yari/blob/7ab0699c19af06de4ae88bbc0fb4fa3e08092fb7/kumascript/src/templates.js#L121

so once a macro is run once, even reloading the macros won't make any difference. For now, you have to stop and restart the development server. I created an issue (https://github.com/mdn/yari/issues/2223) that will remind us to turn off EJS's `renderFile()` caching when we run the development server. When I did that (to test my theory), my macro changes were recognized without having to restart the development server.

**Comment by Ryuno-Ki** [comment]
> Would you like to submit a PR for that? We can do it if you'd prefer, but you should get the credit! smiley

FWIW You can add another person with „Co-authored-by” lines as part of the commit message body to make GitHub aware of a collaborated commit.
