### ISSUE TITLE
Reader View icons very big

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2191]
![Screenshot_20201217-194430.png](https://user-images.githubusercontent.com/44380480/102529570-5df1ba00-40a0-11eb-989b-7c755ec4cb6e.png)
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input

**Comment by peterbe** [comment]
Happens in Safari's and Firefox's reader mode too. 

<img width="964" alt="Screen Shot 2020-12-17 at 3 48 25 PM" src="https://user-images.githubusercontent.com/26739/102542116-4fdf7180-407f-11eb-8307-dfda2e7c5c18.png">

<img width="1335" alt="Screen Shot 2020-12-17 at 3 47 39 PM" src="https://user-images.githubusercontent.com/26739/102542040-34746680-407f-11eb-920b-bf5da98c0eea.png">


What does this mean? That it's wrong to rely on CSS to style the size of SVG icons? Certainly seems so. 
Fortunately, we have pretty decent control of the inclusion of these SVGs in KS macros. @schalkneethling Is there a good known "trick" to set a size that still leaves the page accessible?

**Comment by peterbe** [comment]
I don't dare to see what it would look like on Pocket but it would be nice if it's somewhat decent.

**Comment by schalkneethling** [comment]
I guess as the aim of reader mode is to remove anything that is merely decorative browsers might be ignoring styling added via `::before` or `::after` as this is often used to add just that, decorative elements.

One option is to use an `icon` class that set a base `width` and `height`. 

```
.icon {
  height: 16px;
  width: 16px;
}
```

We just need to be careful with this. If there are existing content that for example does something like this:

```
<div class="icon">
  some copy about the content
  <i class="warning"></i>
</div>
```

The above `div` will be "cropped" to 16x16px which is not the intent. I almost think I had said `icon` class and then ran into this exact problem and had to revert. Worth looking into though.

**Comment by schalkneethling** [comment]
Hmm well, now I am not so sure about my whole idea above 😄 If it is ignoring styling set via those psuedo elements then why is the icons still shown. Why would it just ignore `width`, `height` and/or `background-size`? I will need to dig into this.

**Comment by mattiapontonio** [comment]
If you used an icon font, the icons would follow the font size but I don't know if it is convenient to create it on purpose.

https://www.google.com/search?q=icon+font&oq=icon+font&aqs=chrome..69i57j69i65l2j69i60l2.2257j0j4&client=ms-android-motorola-gfw&sourceid=chrome-mobile&ie=UTF-8

**Comment by schalkneethling** [comment]
This will be addressed as part of https://github.com/mdn/yari/issues/2445 - Thank you for bringing this to our attention @mattiapontonio

**Comment by peterbe** [comment]
Why was this closed? It's still a bug. Just tested it in Safari.
<img width="924" alt="Screen Shot 2021-01-12 at 6 53 40 AM" src="https://user-images.githubusercontent.com/26739/104311258-e8acb580-54a2-11eb-8c79-3d68b4405f6c.png">

**Comment by peterbe** [comment]
Oh. I see. You created a [new issue](https://github.com/mdn/yari/issues/2445) that talks about Reader view in general. 
I still think this is a valid issue and should be closed once a PR comes in to fix it.

**Comment by Ryuno-Ki** [comment]
This could also be flagged for the SVG team.

You can define a height and width attribute in the SVG to determine an „intrinsic size” of an SVG.
(Needs a check whether CSS overwrites it on render).

Keep in mind, that the icons screenshotted here carry _meaning_.
So CSS might not be the correct approach (because that would be for _decoration_).
Instead, I'd suggest an `<img />` with the SVG as `src`.
