### ISSUE TITLE
Issue with "Framework main features": …

### ISSUE THREAD

**Issue by JKROUGE** [mdn/yari#2196]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Main_features

#### What information was incorrect, unhelpful, or incomplete?
Partial subheadings display while switching to 'desktop site' in mobile browser.

#### Specific section or headline?
Subheadings.

#### What did you expect to see?
After MDN servers have been updated last week, the subheadings on pages have a display issue when I open pages in mobile browser in desktop mode , some subheadings are only partially displaying (i.e. instead of 'TypeScript' only 'Type' is visible)  in 'desktop mode' on mobile browser.
![2020_12_16_21 20 54](https://user-images.githubusercontent.com/64306336/102372131-e7dc4d00-3fe4-11eb-9400-0f9695fbaa27.jpg)

#### Did you test this? If so, how?
I checked it on mobile devices.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/tools_and_testing/client-side_javascript_frameworks/main_features`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Main_features
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/tools_and_testing/client-side_javascript_frameworks/main_features/index.html
* Report started: 2020-12-16T15:29:17.716Z

</details>

**Comment by peterbe** [comment]
![IMG_06AC181780DF-1](https://user-images.githubusercontent.com/26739/102551604-c5ead500-408d-11eb-9b81-cdac0f698ad4.jpeg)

Tested with Firefox for iOS. 
I don't think anything really changed when I pressed the "Request desktop site".

**Comment by JKROUGE** [comment]
> ![IMG_06AC181780DF-1](https://user-images.githubusercontent.com/26739/102551604-c5ead500-408d-11eb-9b81-cdac0f698ad4.jpeg)
> 
> Tested with Firefox for iOS.
> I don't think anything really changed when I pressed the "Request desktop site".

I opened the page in android chrome browser on three mobiles (Vivo Y91i, Realme 7, Nokia 2.2), the result is same, its a responsive design/css issue. Attached is photo taken of nokia 2.2 page opened in android chrome browser :

![Uploading IMG_20201218_214307.jpg…]()

**Comment by JKROUGE** [comment]
Looks like it is a CROSS BROWSER issue and issue is happening for android chrome browser, and not only one page but many MDN webpages (probably whole website) having this cross browser issue for android chrome browser, Have a look at screenshots of various different pages (with links) :

Screenshot 1
Link of page:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figure

![Screenshot_2020_1218_233558](https://user-images.githubusercontent.com/64306336/102646394-f44dda80-4189-11eb-9e1c-2769fc2db4c8.jpg)

Screenshot 2
Link of page:
https://developer.mozilla.org/en-US/docs/Web/JavaScript

![Screenshot_2020_1218_233820](https://user-images.githubusercontent.com/64306336/102646650-6f16f580-418a-11eb-8a22-59e313629d7a.jpg)

Screenshot 3
Link of page:
https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Cascade_and_inheritance

![Screenshot_2020_1218_234708](https://user-images.githubusercontent.com/64306336/102647395-afc33e80-418b-11eb-854c-8d4d0fec305b.jpg)

**Comment by mattiapontonio** [comment]
![Screenshot_20210102-204355](https://user-images.githubusercontent.com/44380480/103465413-75d16b00-4d3b-11eb-977b-b1c7e78f60a5.png)
Works in my `desktop && mobile Firefox Android`.

**Comment by peterbe** [comment]
@JKROUGE Thank you for your wonderful screenshots! I'm not sure what to do with this. But it seems like a tricky browser bug which is always what I hope it is. 

A lot has happened to Yari since Dec 18 2020. Can you test if it's still and issue?

**Comment by mattiapontonio** [comment]
```
<h3 id="quotations"><a href="#quotations" title="Permalink to Quotations">Quotations</a></h3>
```

It should be noted that the background of `h3` is less than a because for some reason the child a does not expand the father `h3`. So only graphically as I see it from the screenshots _if it were a single element_ the `background` should adapt to `innerText`. 
After that you should understand the computed `width`s in the reference browser.

**Comment by schalkneethling** [comment]
Tested with Chrome on Galaxy S10

![Screenshot 2021-02-15 at 18 05 46](https://user-images.githubusercontent.com/10350960/107970105-59bb1d80-6fb9-11eb-8aba-a524af2b4b63.png)

![Screenshot 2021-02-15 at 18 06 35](https://user-images.githubusercontent.com/10350960/107970119-5fb0fe80-6fb9-11eb-8383-9c7720f757d3.png)

Firefox on Xiaomi Redmi Note 8

![Screenshot 2021-02-15 at 18 10 38](https://user-images.githubusercontent.com/10350960/107970178-735c6500-6fb9-11eb-9082-d87123d01388.png)

Safari on iPhone 8

![Screenshot 2021-02-15 at 18 11 31](https://user-images.githubusercontent.com/10350960/107970210-7fe0bd80-6fb9-11eb-9171-13a6d8ec4a42.png)

Looks to no longer be a problem. Please feel free to reopen if this problem surfaces again. Thanks!

**Comment by JKROUGE** [comment]
> @JKROUGE Thank you for your wonderful screenshots! I'm not sure what to do with this. But it seems like a tricky browser bug which is always what I hope it is.
> 
> A lot has happened to Yari since Dec 18 2020. Can you test if it's still and issue?

Unfortunately the bug is still the same, as Mr. @peterbe has suggested it might be a tricky browser bug (specifically Chrome browser), while in desktop-mode the issue happens on portrait view of site on my mobile screen of 2-3 inches width. Anyways no issues in landscape view (6-7 inches width) of desktop-mode. Ok let it be, may be vendor will update their browser and the bug will go away in near future. Thanks all for sincere efforts. Issues happens on some pages on some headings (not all pages), following is screenshot of this webpage : https://developer.mozilla.org/en-US/docs/Web/JavaScript

![Screenshot_2021_0305_175702](https://user-images.githubusercontent.com/64306336/110115787-9a4dd000-7ddc-11eb-97c2-9c06e278f032.jpg)
