### ISSUE TITLE
Reader View: some links are styled diferrently

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2204]
![Screenshot_20201218-105017.png](https://user-images.githubusercontent.com/44380480/102600361-00508280-411f-11eb-908f-b20099d16446.png)

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

**Comment by schalkneethling** [comment]
@mattiapontonio In the above instance, `pattern` is a `code` element and the string in the screenshot is a simple anchor link. You can also see that the `h3` element above is styled completely different. I don't believe we have much, if any, control over the styling here.

I will look into this some though just to get a better understanding

**Comment by mattiapontonio** [comment]
Is there a way to inspect property computation in this mode? 
I would try to figure out if it is appropriate to change HTML or add specificity to the CSS rules. 
However they should be the same I think. 
I instinctively think that there is a correct way between putting a parent `code` of `a` or vice versa. 
And ditto for o titles that you shouldn't put `a` inside `h` o as father of `h`. 
Because probably the browser's default stylesheet is more specific in some cases than custom CSS. 

In this mode, as far as I understand, there is only control over the HTML to impact the style.

**Comment by schalkneethling** [comment]
This will be addressed as part of https://github.com/mdn/yari/issues/2445 - Thank you for bringing this to our attention @mattiapontonio
