### ISSUE TITLE
https://developer.mozilla.org/safari-pinned-tab.svg is 404

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/yari#2210]
https://github.com/mdn/yari/blob/ee113c2da64b0761c6c3b3c7c0cde7b8a0fbae53/client/public/index.html#L24-L28
… resolves to https://developer.mozilla.org/safari-pinned-tab.svg in MDN content, but that URL is 404.

**Comment by peterbe** [comment]
@schalkneethling Do you think you can generate a good mask icon SVG that we can use. It might make some bookmarking prettier. If it's hard to do, then we can remove the meta tag. The whole reason we got it was because `create-react-app` has it on by default in their boilerplate.

**Comment by myakura** [comment]
the mask icon link tag is gone in https://github.com/mdn/yari/pull/2095 .
