### ISSUE TITLE
Invalid "frameborder" attribute in kumascript/macros/EmbedLiveSample.ejs etc.

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/yari#2213]
Per https://html.spec.whatwg.org/multipage/obsolete.html#non-conforming-features `frameborder` is invalid.

So the following in `kumascript/macros/EmbedLiveSample.ejs` is causing all articles with live samples to be invalid —
https://github.com/mdn/yari/blob/0747bcd4454e70c912afcbe99be5136113e25514/kumascript/macros/EmbedLiveSample.ejs#L54

…and same for any documents that use any of the following macros:

* `kumascript/macros/EmbedInteractiveExample.ejs`
* `kumascript/macros/EmbedGHLiveSample.ejs`
* `kumascript/macros/EmbedNewRelicChart.ejs`
* `kumascript/macros/JSFiddleEmbed.ejs`

…because those all have `frameborder`.

So I guess the styling for `iframe` borders should be moved into the CSS stylesheet, and removed from the macro sources — and if so, then it looks like the tests at `kumascript/tests/macros/EmbedInteractiveExample.test.js` and at `kumascript/tests/macros/EmbedLiveSample.test.js` will need to be updated also.

**Comment by escattone** [comment]
Thanks @sideshowbarker! 🎉

**Comment by peterbe** [comment]
https://github.com/mdn/yari/pull/2912 will solve this.
