### ISSUE TITLE
Invalid width="100%" in EmbedInteractiveExample.ejs etc.

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/yari#2217]
At https://html.spec.whatwg.org/multipage/embedded-content-other.html#attr-dim-width the HTML says the value of the `width` attribute for the `iframe` element must be a non-negative integer.

So the following in `kumascript/macros/EmbedInteractiveExample.ejs` causes all articles with interactive live samples to be invalid —

https://github.com/mdn/yari/blob/0747bcd4454e70c912afcbe99be5136113e25514/kumascript/macros/EmbedInteractiveExample.ejs#L23

…and same for any documents that use any of the following macros:

* `kumascript/macros/EmbedNewRelicChart.ejs`
* `kumascript/macros/EmbedTest262ReportResultsTable.ejs`
* `kumascript/macros/InheritanceDiagram.ejs`
* `kumascript/macros/JSFiddleEmbed.ejs`

So I guess that width styling for iframe element should be moved into the CSS stylesheet, and removed from the macro sources — and if so, then the associated tests will need to be updated also.

**Comment by mattiapontonio** [comment]
> width
The width of the frame in CSS pixels. Default is 300.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe

**Comment by Spirit-ofJoy** [comment]
Just to confirm if I am understanding this right....
The iframe element in the specified "kumascript/macros/EmbedInteractiveExample.ejs" is causing unintended frontend design in various other articles?

**Comment by Blakelist7** [comment]
Hey, I'd like to help on this one. Can you assign this to me?
@schalkneethling

**Comment by Blakelist7** [comment]
@schalkneethling just confirming 😅 
1) We are removing `inline ` `width` styling from the `iframe` element, right?

If the above mentioned is true, then

1) Could you please elaborate on why are we doing this?
2) Is @sideshowbarker referring to <a href="https://github.com/mdn/interactive-examples/blob/master/live-examples/html-examples/embedded-content/css/iframe.css">this</a> CSS file? But as I can check it already has a `width` attribute.

**Comment by schalkneethling** [comment]
> 1. We are removing `inline ` `width` styling from the `iframe` element, right?

Yes, and moving it to CSS here https://github.com/mdn/yari/blob/ee08a20192d8ff07f277574b6b49e7e13b87163f/client/src/document/index.scss#L266

> 1. Could you please elaborate on why are we doing this?

Setting the `width` attribute to `100%` results in invalid HTML. The value of width needs to be a non-negative integer i.e. a number equal or greater than 0. Percentage units are not allowed.
