### ISSUE TITLE
Sidebar and content not top aligned

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2219]
We still have a the top alignment "feeling off". It looks a bit misaligned when the sidebar doesnt line up with the content. 
<img width="839" alt="Screen Shot 2020-12-18 at 3 49 53 PM" src="https://user-images.githubusercontent.com/26739/102660261-c005fa00-4148-11eb-82af-09d4ad4ca9d8.png">

Also visible here:
<img width="745" alt="Screen Shot 2020-12-18 at 3 48 25 PM" src="https://user-images.githubusercontent.com/26739/102660153-9220b580-4148-11eb-97ab-8bd02964544f.png">

**Comment by peterbe** [comment]
If I set `padding-top:0` on the `nav.sidebar` and the `article.article`, it aligns nicely. 
<img width="1042" alt="Screen Shot 2020-12-18 at 3 52 28 PM" src="https://user-images.githubusercontent.com/26739/102660514-2428be00-4149-11eb-9c00-7113be8832dc.png">

**Comment by peterbe** [comment]
For what it's worth, if you visit a page that has a `aside.document-toc-container` it's actually working
<img width="975" alt="Screen Shot 2020-12-18 at 3 54 27 PM" src="https://user-images.githubusercontent.com/26739/102660614-520e0280-4149-11eb-8d46-e04dde097f83.png">

**Comment by schalkneethling** [comment]
Looks like this is resolved? @peterbe 

![Screenshot 2021-03-31 at 19 11 33](https://user-images.githubusercontent.com/10350960/113183944-eb72a780-9254-11eb-849c-e466de6e51fb.png)

**Comment by peterbe** [comment]
I don't know. It still looks a bit odd. But it's not at all obvious to me what it should align on. 

I did temporarily set the `margin-top` to `41px` on the `<section class="document-toc">` 
and if you do that the *bottom* of the `h2` in the sidebar matches the *bottom* of the `h1` in the main content. 🙃
I think I'm out of my depth about what it should be. 
<img width="1395" alt="Screen Shot 2021-04-01 at 11 31 45 AM" src="https://user-images.githubusercontent.com/26739/113317878-da21ad80-92dd-11eb-8acb-617dff735673.png">

It certainly looks much better than it did (see the first screenshot above). 
Perhaps now it's too hard to get it right if it's not even obvious what right means. 
Perhaps Daryl might have feels that are much better.

**Comment by schalkneethling** [comment]
Yeah, we are still going to tweak it and I am sure line heights is playing into this.

**Comment by schalkneethling** [comment]
Being addressed as part of the redesign and tracked elsewhere.
