### ISSUE TITLE
translated hrefs hashtags differs from internal links hrefs

### ISSUE THREAD

**Issue by behrouze** [mdn/yari#2220]
In [this page](https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension):
developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension

the 1st link of the content is:
developer.mozilla.org/**fr**/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#**Background_scripts**

but in the content we have:
a href="**#Scripts_darrière-plan**" title="Permalink...

**Comment by schalkneethling** [comment]
this one looks to be resolved: https://developer.mozilla.org/fr/docs/Mozilla/Add-ons/WebExtensions/Anatomy_of_a_WebExtension#scripts_darri%C3%A8re-plan
