### ISSUE TITLE
Page title (visually) and maybe the all body not full width

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2233]
![Screenshot_20201220-200023.png](https://user-images.githubusercontent.com/44380480/102721922-0c466b00-42fe-11eb-88c2-570a09ea84d0.png)

**Comment by peterbe** [comment]
What did you expect? That the characters `een()` would be in that empty area in the middle of your purple circle?
The title has to wrap. 

Close? CC @schalkneethling

**Comment by mattiapontonio** [comment]
It seems to me that the whole large container does not reach 100% but from my mobile I cannot inspect.

**Comment by mattiapontonio** [comment]
![ezgif-7-9c16f2aa79a2.gif](https://user-images.githubusercontent.com/44380480/102813076-7a576480-43c8-11eb-8d13-2e4918f3270a.gif)

**Comment by mattiapontonio** [comment]
https://developer.allizom.org/en-US/docs/Web/API/Element/requestFullScreen

**Comment by mattiapontonio** [comment]
https://whatismybrowser.com/w/76CS376

**Comment by mattiapontonio** [comment]
> What did you expect? That the characters `een()` would be in that empty area in the middle of your purple circle?
> The title has to wrap. 
> 
> Close? CC @schalkneethling 

No, there is a _white_ space between the _gray_ and the _screen border_.

**Comment by mattiapontonio** [comment]
> What did you expect? That the characters `een()` would be in that empty area in the middle of your purple circle?
> The title has to wrap. 
> 
> Close? CC @schalkneethling 

What about do not break the title but giving an overflow scroll like tables?
