### ISSUE TITLE
<a class=new> is not standing out

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2237]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLDetailsElement

 ![Screenshot_20201220-221207.png](https://user-images.githubusercontent.com/44380480/102724525-6b14e000-4310-11eb-9655-e9876200f1e2.png)

**Comment by peterbe** [comment]
I know I filed this before. Recently in fact. Can you please try to find the duplicate (i.e. the original)?

**Comment by peterbe** [comment]
> I know I filed this before. Recently in fact. Can you please try to find the duplicate (i.e. the original)?

Perhaps it got closed but it wasn't actually working. I can't find it. So let's assume it's a fresh new design system bug. 

@schalkneethling The problem is that `<a class="new">` tags should stand out so it doesn't look like you can click on it.

**Comment by mattiapontonio** [comment]
I can't inspect but I suppose that `new` class is avoidable.

**Comment by mattiapontonio** [comment]
Even I can't find the duplicate. Something related to `:link` I guess.

**Comment by peterbe** [comment]
> I can't inspect but I suppose that `new` class is avoidable.

No, it's not avoidable. It's something the Yari builder produces. Now, the design system needs to deal with it appropriately.

**Comment by mattiapontonio** [comment]
> > I can't inspect but I suppose that `new` class is avoidable.
> 
> No, it's not avoidable. It's something the Yari builder produces. Now, the design system needs to deal with it appropriately. 
> 

This "`new`" logic is in all `<a>` in all `App`?

**Comment by schalkneethling** [comment]
Duplicate of https://github.com/mdn/yari/issues/2065
