### ISSUE TITLE
In the Google SERP result some words are CamelCased [SEO]

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2242]
https://www.google.com/search?q=meta+tag&oq=meta&aqs=chrome.0.69i59j69i57j69i60l2j69i61.2260j0j7&client=ms-android-motorola-gfw&sourceid=chrome-mobile&ie=UTF-8
![Screenshot_20201221-113032.png](https://user-images.githubusercontent.com/44380480/102767598-23c63800-4380-11eb-9bcd-1a1d52a186bb.png)

**Comment by escattone** [comment]
@mattiapontonio I don't know what this means. Please re-open if you can clearly identify a problem.

**Comment by mattiapontonio** [comment]
I guess It should be something like 

_Chrome full support_

and not 

_ChromeFull.._

Is a space issue in some code unknown that Google read like a single sring.

See the screenshot.
