### ISSUE TITLE
Issue with "Work with animations": …

### ISSUE THREAD

**Issue by nschonni** [mdn/yari#2243]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Work_with_animations

#### What information was incorrect, unhelpful, or incomplete?

The code embbed is a frame to a 404 page

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/work_with_animations`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Work_with_animations
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/tools/page_inspector/how_to/work_with_animations/index.html
* Report started: 2020-12-20T19:37:30.860Z

</details>

**Comment by peterbe** [comment]
Yeah, what Yari does is that it looks through the code snippets of the page and dumps them, in a combined HTML string, into `./_samples_/index.html`. But it seems, clearly, that it's buggy :) 
Let's see if we can fix it.

**Comment by mattiapontonio** [comment]
I was thinking that header and footer really shouldn't be there so maybe the call goes through the wrong place. 🤔

![Screenshot_20201221-140603.png](https://user-images.githubusercontent.com/44380480/102780293-f3899400-4395-11eb-8d86-27fdca41073e.png)

**Comment by peterbe** [comment]
What's most annoying is that the KS macro (`EmbedLiveSample`) fails you but it's not logged as a flaw. So it's impossible to know this is happening without plainly looking at the page.

**Comment by peterbe** [comment]
The solution is to open the file `files/en-us/tools/page_inspector/how_to/work_with_animations/animation_inspector_example_colon__web_animations_api/index.html` and add, to the bottom, something like:
```
{{EmbedLiveSample("firefox-logo-animation", 500, 200)}}
```

Then it works on the page that depends on it:
<img width="862" alt="Screen Shot 2020-12-21 at 9 26 38 AM" src="https://user-images.githubusercontent.com/26739/102787169-a34b0b80-436e-11eb-94dc-aee2313447f6.png">

I didn't even realize this is how it works with "foreign live samples" but I looked at how `files/en-us/learn/forms/how_to_structure_a_web_form/index.html` does it and that's where I got the idea. 

Now, is this sane @escattone ? 
And how can we possibly guard against this? 
In this case, the /en-US/docs/Tools/Page_Inspector/How_to/Work_with_animations was "foolish" for assuming that `Tools/Page_Inspector/How_to/Work_with_animations/Animation_inspector_example:_Web_Animations_API` does indeed produce a live sample? But how do you possible elevate that as a flaw or something? 
Perhaps it's rare. Perhaps the true solution is something much more lo-fi in that we stop doing these complicated transclusions. 

@escattone

**Comment by sideshowbarker** [comment]
> What's most annoying is that the KS macro (`EmbedLiveSample`) fails you but it's not logged as a flaw. So it's impossible to know this is happening without plainly looking at the page.

Yeah — regardless of what other changes we might make with regard to this, it would be help to get some logging added, if possible. But I assume that might be hard to do for this case, otherwise it’d already be getting logged?

**Comment by sideshowbarker** [comment]
> Perhaps the true solution is something much more lo-fi in that we stop doing these complicated transclusion.

I imagine the reason transclusion was used this way in this case is: Because the article is about showing how to use devtools to inspect an animation — and not at all about how to write the actual code for the animation — then adding the code directly into the article itself would be a distraction from the actual topic for the article; that is, we don’t want to make the reader need to scroll through ~100 lines to get to the part that shows the live sample we’re asking them to click on and inspect.

I guess an alternative to using a transclusion for this case would be to put the code directly into the article, but at the *end* of the article — with a title like **Code for the animation example used in this article** or something.

**Comment by sideshowbarker** [comment]
> Perhaps the true solution is something much more lo-fi in that we stop doing these complicated transclusion.

I raised https://github.com/mdn/content/pull/534 for adding some language to the related documentation.

The use case for the transclusion in this article seems valid. So while it’s definitely complicated, it seems pretty useful in general to be able to transclude code and/or live samples across multiple articles that might want to say different things about the code or live sample, in different contexts.

So maybe we just need to try to document things better? (Well, along with adding better logging for transclusion failures.)

**Comment by nschonni** [comment]
Looks like the particular page is fixed. Did you want to keep this open as a general issue for these types of embeds or should I close it?

**Comment by sideshowbarker** [comment]
> Looks like the particular page is fixed. Did you want to keep this open as a general issue for these types of embeds or should I close it?

No need to keep it open for my sake at least.
