### ISSUE TITLE
Use the "privacy-enhanced" YouTube embed technique

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2246]
I suspect the [`EmbedYouTube` macro](https://github.com/mdn/yari/blob/master/kumascript/macros/EmbedYouTube.ejs) was probably created before YouTube had the "privacy-enhanced mode". It simply uses `www.youtube-nocookie.com` instead of the regular `www.youtube.com` domain which means that what YouTube embeds you watch don't suddenly appear in your YouTube feed. I personally think that's quite nice because my YouTube life is quite "personal" in that I like relaxing and watching cooking and swimming and science videos. Not CSS and Web APIs videos which is for when I'm working. 

But there's a potentially a missed opportunity. I can only speculate, but common sense tells me that if you're the creator of the embedded video, you might actually want to get as many eyeballs as possible to your videos. So if you can get people to watch them, embedded in a site, you might want them to reappear when people are watching their YouTube content on other devices at other times. 
Having said that, MDN isn't pushing its own YouTube content and if, for some video(s), we *don't* want the privacy-enhanced embed technique, you can simply opt to not use the `EmbedYouTube` KS macro.

**Comment by mattiapontonio** [comment]
I was thinking I don't know if it makes sense to only allow videos from this channel so the only parameter is the ID.

https://youtu.be/4-d_SoCHeWE

**Comment by chrisdavidmills** [comment]
I don't really have a strong opinion here. I quite like the idea of respecting people's privacy, but I don't think it will upset people that much. Let's try it.
