### ISSUE TITLE
Jump to section over the archived fixed Yellow div

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2250]
![Screenshot_20201221-223859.png](https://user-images.githubusercontent.com/44380480/102824563-64a06a00-43dd-11eb-882e-641e096ac578.png)

**Comment by schalkneethling** [comment]
We need to bump the `z-index` to use `z-index: $bring-to-front;`

**Comment by mattiapontonio** [comment]
Is there a way to count the elements using z-index and sort them with 1,2,3 ...?
