### ISSUE TITLE
I should see the image in a new Tab so I can zoom if the image is small in the article [feature]

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2253]
### Example of this feature in GitHub

![ezgif-3-6255afb5beb2.gif](https://user-images.githubusercontent.com/44380480/102830972-ec40a580-43ea-11eb-96f8-ffb30d4f33d7.gif)

GitHub opens images in new tabs.

**Comment by peterbe** [comment]
I don't understand.

**Comment by mattiapontonio** [comment]
It's a feature.
All `<img>` wrapped by a `<a>` that points to the `src`.

**Comment by mattiapontonio** [comment]
I even thinked about request fullscreen but I should investigate better.
