### ISSUE TITLE
These light blue boxes has not padding top

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2255]
- https://developer.mozilla.org/en-US/docs/Web/CSS
- https://developer.mozilla.org/en-US/docs/Learn

![Screenshot_20201222-011944.png](https://user-images.githubusercontent.com/44380480/102834290-ec916e80-43f3-11eb-825d-5d23da001b01.png)
![Screenshot_20201222-012406.png](https://user-images.githubusercontent.com/44380480/102834488-7a6d5980-43f4-11eb-8c90-5c1659716e9c.png)

**Comment by tannerdolby** [comment]
@mattiapontonio Maybe they were intended to not having any top padding. What exactly makes this an issue? In my opinion, the space between the neighboring elements above each of the "light blue boxes" seems appropriate.

I think this could probably be closed, but it's best to see what a MDN team member says first.

**Comment by mattiapontonio** [comment]
@tannerdolby yeah It should be as You Say. I like equals padding for a design something. 🙂

**Comment by mattiapontonio** [comment]
But that box would be the equivalent of the yellow one and the red one but for information?

**Comment by chrisdavidmills** [comment]
We did have better styling for these boxes, but it didn't make it through to Yari.

@schalkneethling do you already have this recorded somewhere in the pile?

**Comment by mattiapontonio** [comment]
I can't find the issue but there was a similar problem where we talked about the article and the padding / margin of the first child to align with the sidebar.

**Comment by escattone** [comment]
@schalkneethling I added the `design-system` label and assigned it to you in order to get your thoughts on any next steps if any.

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/mdn/yari/issues/2255](https://trello.com/c/sOHcGRBf/15-https-githubcom-mdn-yari-issues-2255)

**Comment by mattiapontonio** [comment]
My 2 cents 🙂

![Screenshot_20210113-173115.png](https://user-images.githubusercontent.com/44380480/104480734-2ace1800-55c5-11eb-8ffe-a82ee642167c.png)

**Comment by schalkneethling** [comment]
Here is the first piece https://github.com/mdn/content/pull/1295 that addresses this issue

**Comment by schalkneethling** [comment]
Second portion: https://github.com/mdn/mdn-minimalist/pull/416

**Comment by schalkneethling** [comment]
final piece: https://github.com/mdn/yari/pull/2523

**Comment by mattiapontonio** [comment]
I like it a lot this is what dendabot closes issues but at the moment the problem is still present. Maybe you have to wait for the usual release time.

👍

![Screenshot_20210114-145429.png](https://user-images.githubusercontent.com/44380480/104599846-8f967a80-5678-11eb-9c62-3f46c94341f6.png)

**Comment by tannerdolby** [comment]
@mattiapontonio Is there anyway you could include smaller screenshots in the future? It's very hard to view such large images on mobile devices when I'm not browsing on my laptop. Thank you!

**Comment by mattiapontonio** [comment]
![Screenshot_20210115-132034.png](https://user-images.githubusercontent.com/44380480/104726787-836ff300-5734-11eb-9a76-44888843f3ae.png)

That's atomic! ⚛️
