### ISSUE TITLE
Chevron up icon for ::before psuedo element being cutoff at small viewports

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#2260]
When I was fixing some alignment stuff in the `main-nav` menu, I noticed the psuedo ::before element (a chevron up icon) is being cutoff from the top half at smaller viewports. The issue starts at < 610px and becomes increasingly more noticeable as the viewport width gets smaller.

_610px_

<img width="127" alt="Screen Shot 2020-12-22 at 12 21 49 AM" src="https://user-images.githubusercontent.com/48612525/102866209-bcde6880-43eb-11eb-81c3-5a474e39991f.png">

_600px_

<img width="157" alt="Screen Shot 2020-12-22 at 12 21 38 AM" src="https://user-images.githubusercontent.com/48612525/102866224-bfd95900-43eb-11eb-8fb7-c52ca894acad.png">

_550px_

<img width="120" alt="Screen Shot 2020-12-22 at 12 23 17 AM" src="https://user-images.githubusercontent.com/48612525/102866323-eac3ad00-43eb-11eb-8a0f-f821cbe59ed7.png">

_500px_

<img width="117" alt="Screen Shot 2020-12-22 at 12 23 46 AM" src="https://user-images.githubusercontent.com/48612525/102866374-016a0400-43ec-11eb-947e-30fba7332669.png">

_430px_

<img width="116" alt="Screen Shot 2020-12-22 at 12 25 14 AM" src="https://user-images.githubusercontent.com/48612525/102866497-34ac9300-43ec-11eb-9e13-c760df9f84bb.png">

_350px_

<img width="116" alt="Screen Shot 2020-12-22 at 12 25 58 AM" src="https://user-images.githubusercontent.com/48612525/102866559-4e4dda80-43ec-11eb-9848-5099f37973fd.png">

After further inspection, it seems `background-size: 12px` is the culprit, along with the `width` and `height` properties, which are necessary for the psuedo element to appear.

```
.breadcrumbs li .breadcrumb-penultimate:before {
    background: transparent url(/static/media/chevron.f472b7ac.svg) 0 0 no-repeat;
    background-size: 12px;
    content: "";
    display: inline-block;
    height: 12px;
    margin-right: 6px;
    transform: rotate(-90deg);
    width: 12px;
}
```

Proposed fix:
Change background-size to `background-size: 100% 12px` where `100%` is the width of the background image and `12px` is the height of the image, so the height doesn't change from above. And modify the width property to a more appropriate size on smaller viewports. 

Where `1rem` is just a test value which allows the icon to be more visible on 320px viewports and above. This could be tweaked or maybe add a media query to bring it back to `width: 12px` at larger viewports so the space in between the chevron and text isn't noticeable.

```
.breadcrumbs li .breadcrumb-penultimate:before {
    background: transparent url(/static/media/chevron.f472b7ac.svg) 0 0 no-repeat;
    background-size: 100% 12px;
    content: "";
    display: inline-block;
    height: 12px;
    margin-right: 6px;
    transform: rotate(-90deg);
    width: 1rem;
}
```

**Comment by mattiapontonio** [comment]
Or moving `SVG` in the `content` so should be computed like a `div`.

https://stackoverflow.com/q/19255296/3579536
