### ISSUE TITLE
All id and hashes should be like multiple-words-id

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2267]
All `id` and `hash`es should be like: 

```html
<div id="multiple-words-id"></div>
``` 

And not like:

```html
<div id="Multiple_Words_Id"></div>
``` 

Even in JavaScript not:

```JavaScript
console.log(Multiple_Words_Id);
``` 

But:

```JavaScript
console.log(window["multiple-words-id"]);
``` 

And in URL s

Good
```
https://d.org/path-with-more-than-one-word#multiple-words-id
```

Bad
```
https://d.org/path-with-more-than-one-word#Multiple-Words-Id
```

- https://github.com/mdn/yari/pull/2266
- #2265

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/id

### Why?
Cosmetics.

**Comment by peterbe** [comment]
Why?

**Comment by mattiapontonio** [comment]
Cosmetics...
O don't know, It seem to me more ordered.
If i find the real Why i Will comment.

**Comment by mattiapontonio** [comment]
The next tyranny will be to force one word to use. Seriously, for example, I wouldn't mind if Yari's paths and BCD's paths were aligned for example.

**Comment by peterbe** [comment]
Ok. Since this isn't a bug we necessarily agree on, but it's still an interesting topic, please start a new Discussion and please try to explain the pros and cons of using hyphens instead of underscores.

**Comment by mattiapontonio** [comment]
Ok.

Why not a discussion?
Because in the Android App only issues are implemented. 
For discussions I have to login to the web app. 🤷🏻‍♂️

No problems. 👍
