### ISSUE TITLE
[improve doc] documenting CLI's synopsis

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2275]
### Example

```
git diff [<options>] [<commit>] [--] [<path>…​]
git diff [<options>] --cached [<commit>] [--] [<path>…​]
git diff [<options>] <commit> [<commit>…​] <commit> [--] [<path>…​]
git diff [<options>] <commit>…​<commit> [--] [<path>…​]
git diff [<options>] <blob> <blob>
git diff [<options>] --no-index [--] <path> <path>
```
From: https://git-scm.com/docs/git-diff

Is in readme?
Can We add a section for the CLI?

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/pull/2273#issuecomment-750029729_

### yarn command-1
....

### yarn command-2
...

## Actual markdown
Need to be linked by the main readme in root.
- https://www.github.com/mdn/yari/tree/master/docs%2Fcli-tool.md

**Comment by peterbe** [comment]
No explanation of what the problem is.
