### ISSUE TITLE
contributors.txt incorrectly refers to master branch

### ISSUE THREAD

**Issue by saschanaz** [mdn/yari#2277]
https://developer.mozilla.org/en-US/docs/Learn/CSS/First_steps/How_CSS_works/contributors.txt

```
# Contributors by commit history
https://github.com/mdn/content/commits/master/files/en-us/learn/css/first_steps/how_css_works/index.html

# Original Wiki contributors
warleyfdias
choudh70
jlbuckner
rachelandrew
chrisdavidmills
ExE-Boss
```

But there is no master branch, it should use `main`.

**Comment by HolgerJeromin** [comment]
Same with all links "Source on GitHub"
![image](https://user-images.githubusercontent.com/2410353/105874215-a2a43580-5ffc-11eb-9cf0-544013819373.png)

**Comment by peterbe** [comment]
[`master` is gone](https://github.com/mdn/yari/discussions/2951)

**Comment by escattone** [comment]
@peterbe This is still an issue. We're still referring to the content repo's `master` branch in any doc's contributor.txt file (e.g., https://developer.mozilla.org/en-US/docs/Web/contributors.txt), but we should change that to use the `main` branch instead.

**Comment by peterbe** [comment]
Here's what I see. 
<img width="767" alt="Screen Shot 2021-02-17 at 9 22 00 AM" src="https://user-images.githubusercontent.com/26739/108217452-98f48600-7101-11eb-8494-d680bd450458.png">

**Comment by HolgerJeromin** [comment]
The links to github are still wrong. ref: https://github.com/mdn/yari/issues/2277#issuecomment-767665956

**Comment by saschanaz** [comment]
Could you refresh and check again? I see them properly changed to `main`.

**Comment by peterbe** [comment]
Could be that the CDN cache is still warm. Try messing with the casing of the URL to bypass that.

**Comment by escattone** [comment]
Yep, it's a caching issue. This is resolved.
