### ISSUE TITLE
Consider supporting <del> and <ins> in <pre> <code> as a way to show .bad and .good

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2278]
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/del
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ins

Actually there are 2 snippets: 1 _good and green_ and 1 _bad and red_.
It could be 1 snippet corrected from the bad to the good like in a PR. 

🤔
Maybe it's a discussion and not a issue.

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/issues/2198

**Comment by peterbe** [comment]
Why? Where?
