### ISSUE TITLE
https://mdn-samples.mozilla.org CSP policy frame-ancestors doesn’t allow https://yari-demos.prod.mdn.mozit.cloud

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/yari#2281]
Problem: The iframe at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#Result displays:
> mdn-samples.mozilla.org will not allow Nightly to display the page if another site has embedded it

Cause: That iframe is a live sample, the source for which looks like this:
```html
<h4 id="Result">Result</h4>
<p><iframe class="live-sample-frame sample-code-frame" id="frame_Example1"
frameborder="0" width="640" height="400"
src="https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/iframe/_samples_/Example1"
loading="lazy"></iframe></p>
```
…and the https://yari-demos.prod.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/iframe/_samples_/Example1 source has:
```html
<body>
<iframe src="https://mdn-samples.mozilla.org/snippets/html/iframe-simple-contents.html"
title="iframe Example 1" width="400" height="300"></iframe>
</body>
```
So https://mdn-samples.mozilla.org/snippets/html/iframe-simple-contents.html isn’t directly framed from that `https://developer.mozilla.org` article but instead is inside a nested `https://yari-demos.prod.mdn.mozit.cloud` iframe.

Checking the HTTP headers for https://mdn-samples.mozilla.org/snippets/html/iframe-simple-contents.html shows:
```
$ curl -I https://mdn-samples.mozilla.org/snippets/html/iframe-simple-contents.html
…
Content-Security-Policy: frame-ancestors 'self' https://developer.mozilla.org https://developer.allizom.org 
    https://mdn.mozillademos.org;
```
…and so because `https://yari-demos.prod.mdn.mozit.cloud` isn’t listed in that CSP policy as an allowed host source for the `frame-ancestors` directive, the browser refuses to display the `https://yari-demos.prod.mdn.mozit.cloud`-nested `https://mdn-samples.mozilla.org` iframe.

Related: https://github.com/mdn/content/issues/635

**Comment by escattone** [comment]
@sideshowbarker Thanks for digging into this and your excellent description of the problem! 🎉 

[I updated the `frame-ancestors` CSP within the mdn/samples-server repo](https://github.com/mdn/samples-server/commit/f380d560afcb1b09fc3ace6e5e05f71aead4316f), and @limed (from Mozilla IT) helped me push the new code to the server. This is resolved.
