### ISSUE TITLE
Allow for custom host

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#2298]
Allow to define a host (according to [Express.js documentation](http://expressjs.com/en/api.html#app.listen) this would be the second argument to

https://github.com/mdn/yari/blob/ae2020b71cc928b4cb31efee794f355b865fb120/server/index.js#L240

) so a local instance could be checked from other devices on the same network, by passing in `0.0.0.0`.
Useful when testing with a mobile (resp. the screenreader there, in my case).

**Comment by peterbe** [comment]
Doesn't Expression already listen to some default environment variables? Can you find out?

**Comment by Ryuno-Ki** [comment]
It does. `NODE_ENV` for [production environments](http://expressjs.com/en/advanced/best-practice-performance.html#set-node_env-to-production) and `DEBUG` for [trouble shooting](http://expressjs.com/en/advanced/best-practice-performance.html#do-logging-correctly).

Searching through the codebase, I can't spot further environment variables (except in testing or benchmarking scenarios).
