### ISSUE TITLE
Serving static images

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2306]
Please see this about serving static files in Express instead of testing everiting from the Node request...
https://expressjs.com/en/starter/static-files.html

It's ok...

In general, there is one thing to say: that navigating to the URL of an image means that the image is served via http, therefore with the headers and body of an image and not HTML containing a img (that Is of course the default browser behaviour), therefore text that contains an image, therefore in general the approach is _wrong_.

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/pull/2297#issuecomment-753415868_

I would like to say that it would also make sense to manage all requests individually to have more control but at this point you should perhaps use the node class directly and not go through Express (which forces you to use a folder). In any case, the http answer in my opinion should be correct ie 404 with empty body and correct content types and so on.
https://github.com/mdn/yari/pull/2297

**Comment by mattiapontonio** [comment]
I would like to say that it would also make sense to manage all requests individually to have more control but at this point you should perhaps use the node class directly and not go through Express (which forces you to use a folder). In any case, the http answer in my opinion should be correct ie 404 with empty body and correct content types and so on.

**Comment by peterbe** [comment]
What are you proposing? What's the problem? What's not working as it should?

**Comment by mattiapontonio** [comment]
I suppose http.
https://developer.mozilla.org/en-US/docs/Web/HTTP

But to be super collaborative I suppose I should write an end to end test on 1 of the 2 ends which is the one that fetches.
