### ISSUE TITLE
Set `Access-Control-Allow-Origin: *` header

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/yari#2307]
It’d be great if the 302 responses from https://media.prod.mdn.mozit.cloud/ had the Access-Control-Allow-Origin header.

See https://github.com/mdn/content/pull/726 for some context; I had considered using https://mdn.mozillademos.org/files/16553/DgsZYJNXcAIPwzy.jpg as a request URL in a live sample within the https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/progress_event article — but found that it wouldn’t work, due the fact that the 302 redirect from https://mdn.mozillademos.org/files/16553/DgsZYJNXcAIPwzy.jpg to https://media.prod.mdn.mozit.cloud/attachments/2019/03/05/16553/ddebeaad0fab32c8aee3119600aba18a/DgsZYJNXcAIPwzy.jpg has no Access-Control-Allow-Origin header.

(Yeah I considered just using https://media.prod.mdn.mozit.cloud/attachments/2019/03/05/16553/ddebeaad0fab32c8aee3119600aba18a/DgsZYJNXcAIPwzy.jpg as the request URL instead — because that does have the Access-Control-Allow-Origin header — but… at 116 characters, that’s a pretty log URL to be dropping into a code sample.

**Comment by schalkneethling** [comment]
@escattone is this still a to-do?

**Comment by mdn-infra** [comment]
@schalkneethling Yes, this is still a TODO.

**Comment by schalkneethling** [comment]
> @schalkneethling Yes, this is still a TODO.

Who should we speak to? Is this something you can configure @escattone?

**Comment by sideshowbarker** [comment]
Beautiful — thanks much 🎉
