### ISSUE TITLE
Browser release dates not being shown

### ISSUE THREAD

**Issue by gsnedders** [mdn/yari#2308]
#944 meant to add release dates when the BCD data includes them, but I can't see it working e.g. on https://developer.mozilla.org/en-US/docs/Web/CSS/writing-mode where none of the browsers have a release date despite BCD including them

(this also in a way touches on #1400)

**Comment by mattiapontonio** [comment]
Can You add a comment in code that references that issue?

**Comment by peterbe** [comment]
Oh no! Regression it seems. I'll take a look.

**Comment by peterbe** [comment]
What's going on?! It's working in http://localhost:3000/en-US/docs/Web/CSS/writing-mode
<img width="512" alt="Screen Shot 2021-01-05 at 10 03 00 AM" src="https://user-images.githubusercontent.com/26739/103661860-34101280-4f3d-11eb-98d9-15bcfbd2ed28.png">

**Comment by peterbe** [comment]
Note-to-self; there's probably nothing wrong with the React code. The `bcd.json` file is simply containing different data. So something must be going on with the building/dumping of that. 
<img width="1529" alt="Screen Shot 2021-01-05 at 10 10 02 AM" src="https://user-images.githubusercontent.com/26739/103662648-30c95680-4f3e-11eb-9977-25f4be1f4f41.png">

**Comment by peterbe** [comment]
What might be the explanation is that https://s3.console.aws.amazon.com/s3/object/mdn-content-prod?region=us-west-2&prefix=main/en-us/docs/web/css/writing-mode/bcd.json hasn't been modified since December 10 2020 which is ages ago.

**Comment by peterbe** [comment]
To test something, I deleted the file from the [stage S3 bucket](https://s3.console.aws.amazon.com/s3/buckets/mdn-content-stage/object/delete?region=us-west-2&prefix=main/en-us/docs/web/css/writing-mode/&showversions=false) and kicked off a fresh Stage build. In a while, we'll see what happens. If it does upload a fresh new one, it means that uploading works. But it then probably also means that *updating* doesn't work.

**Comment by peterbe** [comment]
@gsnedders The codefix has landed. It should be in production by some time tomorrow or Sunday. Perhaps you can help us check that it worked on Monday.

**Comment by gsnedders** [comment]
works for me, yay! thanks!
