### ISSUE TITLE
[warn] Code style issues found in the above file(s). Forgot to run Prettier?

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2310]
This warning prompt me to run prettier but I can't since I've done the PR using GitHub web version from a smartphone.

![Screenshot_20210102-144153.png](https://user-images.githubusercontent.com/44380480/103458455-ba8fde80-4d08-11eb-83c9-5593d06d0bf8.png)

https://github.com/mdn/yari/pull/2309

**Comment by mattiapontonio** [comment]
I would not completely disagree if it was CI maybe doing me a commit that beautifies the code. The important thing is that you see the diff and that the logic doesn't change.

**Comment by peterbe** [comment]
Prettier can't run in CI because that would require making a commit.
