### ISSUE TITLE
Consider highlight.js

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2312]
https://highlightjs.org/

### why?
Can You see this?
https://github.com/mattiapontonio/asteroids/security/dependabot/package-lock.json/highlight.js/open

Dependabot suggest me to update for a Regex security problem and Say highlights fixed that 🤷🏻‍♂️

> Version 10.4.1 resolves these vulnerabilities. Please upgrade.

https://github.com/advisories/GHSA-7wwv-vh3v-89cq

**Comment by peterbe** [comment]
Use Discussions. 
Also, we already considered highlight.js and it wasn't good enough.
