### ISSUE TITLE
Problem with "previous" and "next" button in learning pages

### ISSUE THREAD

**Issue by iZanfir** [mdn/yari#2313]
Hi I'm from Brazil. 
 I've been learning from your page, and in Portuguese. However, when using the "next" button, it takes me to another page in English, claiming that there is no other one in Portuguese. Apparently this happens because the page in Portuguese has a slight difference in the url.

 Look:
![image](https://user-images.githubusercontent.com/75179881/103479749-82db7200-4dae-11eb-9b21-69624a2276c3.png)
The same page, in portuguese: https://developer.mozilla.org/pt-BR/docs/Aprender/Getting_started_with_the_web/JavaScript_basico

 This occurs with a lot of pages in portuguese. But still is possible access them with the other links in the website.
 This is just an example, it ends up happening with others urls too, I just noticed in the learn/aprendizado category

Thanks for your time.

**Comment by chrisdavidmills** [comment]
Apologies, but we're not currently accepting changes to translations at the moment. Read https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ for an explanation.
