### ISSUE TITLE
static analysis on HTML

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2316]
> I'm not saying some static analysis isn't valuable. But if you wanted to test the raw source HTML, you can write a script that uses Yari's sub-routines to that already knows how to separate the front-matter from the "HTML" and then you can test that.

I don't know how to do It but o open a issue for thinking about that.

_Originally posted by @mattiapontonio in https://github.com/mdn/content/issues/648#issuecomment-753952482_

**Comment by peterbe** [comment]
What is the **issue** here? Is it a bug report or a feature request? If not, please close.

**Comment by peterbe** [comment]
I see. It's a followup from https://github.com/mdn/content/issues/648#issuecomment-753952482 which I closed. 

Please don't open any issues for random discussions that are not actionable or understandable.

**Comment by mattiapontonio** [comment]
It is not that I do it because I like to see open issues, it is that otherwise it passes my mind.

**Comment by mattiapontonio** [comment]
In my head there is still the issue of HTML validation otherwise I can't think of parsing all the cases that an editor could propose.
