### ISSUE TITLE
Mantion this API in the readme

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2321]
Mantion this API in the readme

https://developer.mozilla.org/en-US/docs/MDN/Tools/Search#Search_query_format

https://developer.mozilla.org/api/v1/search/en-US?q=History%20Api

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/issues/2320#issuecomment-754009542_

**Comment by peterbe** [comment]
Don't want to.
