### ISSUE TITLE
kumascript unit test suite is busted

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2325]
Happens on `master` every time. Not sure when it started. 

<details>
<summary>Output</summary>
 FAIL  kumascript/tests/index.test.js
  ● testing the main render() function › non-fatal errors in macros are returned by render()

    expect(received).toEqual(expected) // deep equality

    Expected: StringContaining "{{nonExistentMacro(&quot;yada&quot;)}}"
    Received: "<html><head></head><body><a class=\"new\" title=\"The documentation about this has not yet been written; please consider contributing!\" data-flaw-src=\"{{cssxref(&quot;bigfoot&quot;)}}\"><code>bigfoot</code></a>
          {{nonExistentMacro(\"yada\")}}
          <a href=\"/en-US/docs/Web/CSS/number\" data-flaw-src=\"{{cssxref(&quot;dumber&quot;)}}\"><code>&lt;dumber&gt;</code></a>
          <a href=\"/en-US/docs/Web/CSS/number\"><code>&lt;number&gt;</code></a>
          <p id=\"fx-header\"></p>
          <p id=\"fx-inline\"></p>
          <p id=\"gecko-header\"></p>
          <p id=\"gecko-inline\"></p>
          {{page(\"bogus\")}}
          <p><a class=\"new\" title=\"The documentation about this has not yet been written; please consider contributing!\" data-flaw-src=\"{{cssxref(&quot;bigfoot&quot;)}}\"><code>bigfoot</code></a></p>
          {{page(\"/en-US/docs/Web/B\", \"bogus-section\")}}
          <p><a class=\"new\" title=\"The documentation about this has not yet been written; please consider contributing!\" data-flaw-src=\"{{cssxref(&quot;bigfoot&quot;)}}\"><code>bigfoot</code></a></p></body></html>"

       99 |     let [result, errors] = await render("/en-us/docs/web/a");
      100 |     // First, let's check the result.
    > 101 |     expect(result).toEqual(
          |                    ^
      102 |       expect.stringContaining("{{nonExistentMacro(&quot;yada&quot;)}}")
      103 |     );
      104 |     expect(result).toEqual(

      at Object.<anonymous> (kumascript/tests/index.test.js:101:20)

A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks.
Summary of all failing tests
 FAIL  kumascript/tests/index.test.js
  ● testing the main render() function › non-fatal errors in macros are returned by render()

    expect(received).toEqual(expected) // deep equality

    Expected: StringContaining "{{nonExistentMacro(&quot;yada&quot;)}}"
    Received: "<html><head></head><body><a class=\"new\" title=\"The documentation about this has not yet been written; please consider contributing!\" data-flaw-src=\"{{cssxref(&quot;bigfoot&quot;)}}\"><code>bigfoot</code></a>
          {{nonExistentMacro(\"yada\")}}
          <a href=\"/en-US/docs/Web/CSS/number\" data-flaw-src=\"{{cssxref(&quot;dumber&quot;)}}\"><code>&lt;dumber&gt;</code></a>
          <a href=\"/en-US/docs/Web/CSS/number\"><code>&lt;number&gt;</code></a>
          <p id=\"fx-header\"></p>
          <p id=\"fx-inline\"></p>
          <p id=\"gecko-header\"></p>
          <p id=\"gecko-inline\"></p>
          {{page(\"bogus\")}}
          <p><a class=\"new\" title=\"The documentation about this has not yet been written; please consider contributing!\" data-flaw-src=\"{{cssxref(&quot;bigfoot&quot;)}}\"><code>bigfoot</code></a></p>
          {{page(\"/en-US/docs/Web/B\", \"bogus-section\")}}
          <p><a class=\"new\" title=\"The documentation about this has not yet been written; please consider contributing!\" data-flaw-src=\"{{cssxref(&quot;bigfoot&quot;)}}\"><code>bigfoot</code></a></p></body></html>"

       99 |     let [result, errors] = await render("/en-us/docs/web/a");
      100 |     // First, let's check the result.
    > 101 |     expect(result).toEqual(
          |                    ^
      102 |       expect.stringContaining("{{nonExistentMacro(&quot;yada&quot;)}}")
      103 |     );
      104 |     expect(result).toEqual(

      at Object.<anonymous> (kumascript/tests/index.test.js:101:20)

Test Suites: 1 failed, 1 of 37 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        2.364 s
Test run was interrupted.
</details>

**Comment by escattone** [comment]
Not sure when it started either, but I already have a PR for this (https://github.com/mdn/yari/pull/2324).

**Comment by peterbe** [comment]
It was [this commit](https://github.com/mdn/yari/commit/18d97a31f9a2cfbc0a2b3ba229f72722a03bf9f0)
I think I know what the problem is. It's related to fragments.

**Comment by peterbe** [comment]
Gosh I miss Slack and Pull Panda :)
I only now noticed https://github.com/mdn/yari/pull/2324
