### ISSUE TITLE
Content overflowing to the right

### ISSUE THREAD

**Issue by DoviMaj** [mdn/yari#2327]
How to reproduce the error: 
* Go to the page https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Relationship_of_Grid_Layout#Grid_and_flexbox on screen from width: 1360 pixels to 1670px. (linux OS, both on Firefox and Chrome)

# Screenshoot:

![chrome-capture (12)](https://user-images.githubusercontent.com/36450233/103567742-08554400-4ecd-11eb-8025-fe70d8d9946e.jpg)

```
@media (min-width: 74.9375em){
.page-header {
     grid-column: 1/3; 
}
```
Im not sure whats causing this error but removing this media query seems to fix it.

**Comment by peterbe** [comment]
@schalkneethling Can you fix this?

**Comment by peterbe** [comment]
@schalkneethling If you need help faking it so that you get a language drop-down in local dev, I can help.

**Comment by schalkneethling** [comment]
@DoviMaj can you confirm that this has been fixed? Thank you.

**Comment by DoviMaj** [comment]
@schalkneethling confirmed, thanks!
