### ISSUE TITLE
Report a problem with this content on GitHub: make it clearer you should add a summary

### ISSUE THREAD

**Issue by danburzo** [mdn/yari#2328]
The current prepopulated title on the _Report a problem with this content on GitHub_ link on each MDN content page, which includes an ellipsis where the summary should go, seems to be [frequently missed](https://github.com/mdn/content/issues) (as I initially did). Maybe something more explicit like _[INSERT SUMMARY]_ would work better?

**Comment by mattiapontonio** [comment]
It must also be said that perhaps it could also be removed since then in the list of issues (in which it is clear that these are issues) we find a series of

 - [Issues with ...]()
 - [Issues with ...]()
 - [Issues with ...]()

**Comment by peterbe** [comment]
Yeah, that summary is often not used and often admittedly feeling like an annoying thing to have to add. 
I'd be happy to remove the ellipsis. 
Or, replace it with ` (short summary here please)`

What @chrisdavidmills decides/prefers I'd be happy to implement.

**Comment by chrisdavidmills** [comment]
Could we make it default to "issue with [relative URL of page]" ?

And then in the comments in the body, add one at the top saying `<!-- please change above summary to something more descriptive  -->`?

Would that work for the folks on this issue?

**Comment by mattiapontonio** [comment]
I suggest an empty summury and if possibile in body a `table` of **N** usefull data.

**Comment by danburzo** [comment]
As a potential contributor to MDN content, I find it useful for issues to have self-contained summaries so you can get at least a rough idea of the content of the issue when skimming the list. Any change that nudges people towards that is welcome. I  prefer something that has fewer chances of being missed, eg. @peterbe's suggestion to replace the ellipsis with `(short summary here please)`.

**Comment by mattiapontonio** [comment]
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/about-automation-for-issues-and-pull-requests-with-query-parameters#supported-query-parameters

**Comment by peterbe** [comment]
@chrisdavidmills If you prefer the suggestion of replacing the ellipses with `(short summary here please)` then I can take care of this.

**Comment by chrisdavidmills** [comment]
@peterbe yup, I approve of this. Let's try it.
