### ISSUE TITLE
Live sample images not loading via iframe

### ISSUE THREAD

**Issue by davidfkimball** [mdn/yari#2331]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/filter

#### What information was incorrect, unhelpful, or incomplete?
**Most of the sample images are broken links** - see attached screenshot.

![Screen Shot 2021-01-04 at 11 41 29 AM](https://user-images.githubusercontent.com/69653437/103558023-09ad4f00-4e82-11eb-83d8-a0cacbc88436.png)

(It is possible that you intentionally chose broken image link images as the sample images...but if so, that's very confusing.)

#### Specific section or headline?
**Functions** (#Functions)
and
**Combining Functions** (#Combining_functions)

#### What did you expect to see?
Normal sample images.

#### Did you test this? If so, how?
Refreshed and hard-refreshed the page a few times.
Turned off AdBlockPlus.
Tried it in Chrome and Safari (MacOS). (The broken link image is slightly different in Safari)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/filter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/filter
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/filter/index.html
* Report started: 2021-01-04T16:32:58.279Z

</details>

**Comment by peterbe** [comment]
The problem is that https://yari-demos.prod.mdn.mozit.cloud/files/3708/Test_Form.jpg doesn't load. 
I think the problem could be solved if we used https://mdn.mozillademos.org instead for the iframes.

**Comment by peterbe** [comment]
@escattone How come https://mdn.mozillademos.org/files/3708/Test_Form.jpg but https://yari-demos.prod.mdn.mozit.cloud/files/3708/Test_Form.jpg doesn't?

Ideally, we shouldn't be relying on any images via Kuma but here we are. One problem at a time. 
Besides that fancy code we have that can download external images, which is a flaw, to a local image (fixable flaw), only works for images in the HTML like `<img src="https://mdn.mozillademos.org/files/12345/foo.jpg">`.

**Comment by peterbe** [comment]
Here's another one: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Using_the_srcset_and_sizes_attributes

It fails because it's trying to download https://yari-demos.prod.mdn.mozit.cloud/files/16797/clock-demo-400px.png which won't work.

**Comment by escattone** [comment]
@peterbe We should prioritize this tomorrow. We can discuss more tomorrow, but I think we have two choices here:
1. Run our fixable flaws on these images (so they're downloaded to the repo and served the new way).
2. Modify kuma to accept `yari-demos.prod.mdn.mozit.cloud` and `yari-demos.stage.mdn.mozit.cloud` as safe attachment domains.

**Comment by escattone** [comment]
@peterbe Another option, a bit more radical, would be to point `mdn.mozillademos.org` to the same CDN as `developer.mozilla.org`. This would also be more involved as well. We'd have to have AWS transfer the CNAME from the one CDN to the other, change the DNS, and also add `mdn.mozillademos.org` to the SSL cert for the primary Yari CDN.

**Comment by escattone** [comment]
@peterbe I think I've settled on a nice solution until we fix all of these image flaws. I was able to go with option `#2` above but with only changes to some Kubernetes environment variables. It's working on stage. See https://developer.allizom.org/en-US/docs/Web/CSS/filter. I'll deploy to prod tomorrow morning.

**Comment by escattone** [comment]
This is resolved (see https://developer.mozilla.org/en-US/docs/Web/CSS/filter).

**Comment by davidfkimball** [comment]
?Awesome!



|||||||   David Kimball, GIS Specialist
|||||||   Massachusetts Department of Conservation and Recreation
|||||||   251 Causeway Street, Suite 600-700, Boston, MA 02114
|||||||   david.kimball@mass.gov  617-626-1447

________________________________

**Comment by escattone** [comment]
Thanks again for reporting this @davidfkimball!
