### ISSUE TITLE
Images not loading

### ISSUE THREAD

**Issue by tradri** [mdn/yari#2346]
The images aren't loading in the Learn Web Development section of MDN.
The alt text is showing instead.

**Comment by escattone** [comment]
@tradri Which pages are you seeing this problem on?

**Comment by escattone** [comment]
I found one: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Document_and_website_structure

**Comment by tradri** [comment]
@escattone Almost all of the pages in the Learn Web Development section. Here the page I was originally trying to access: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

**Comment by escattone** [comment]
Thanks for reporting this @tradri! I'm looking into this as we speak.

**Comment by tradri** [comment]
@escattone thanks

**Comment by escattone** [comment]
@tradri This is resolved. Thank you again for reporting it, cheers!

**Comment by tradri** [comment]
@escattone thanks to you for keeping such an awesome free learning resource running ;-)

**Comment by mattiapontonio** [comment]
![Screenshot_20210105-234559.png](https://user-images.githubusercontent.com/44380480/103708110-365f8480-4fb0-11eb-9b35-f08557cef208.png)

Yeah It works.
Please Copy this layout for YARI, even colors (TBD).
