### ISSUE TITLE
Strange 404

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2348]
Visting this page:
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mesh

I have 2 issues:
- The style is strange
- The menu is made by buttons and anchors so i think should be `<details>`

![Screenshot_20210106-022633.png](https://user-images.githubusercontent.com/44380480/103718812-ec829880-4fc7-11eb-8e84-9463e96bca92.png)

Note: if You see the page as the same way and scroll You should probably spot some HTML issue to be discussed.

**Comment by peterbe** [comment]
Strange. Must have been an unfortunate glitch in the serving of one of the `.css` files from the CDN. It's irreproducible.
