### ISSUE TITLE
Unslug all locales (unify slugs across locales)

### ISSUE THREAD

**Issue by fiji-flo** [mdn/yari#2359]
This will be broken down to smaller tasks but this what should happen:

- [x] replace slug with `translation_of` for all translated documents
- [x] fix `translation_of` with `#`'s
- [x] update the file locations
- [x] adjust redirects
- [x] deal with conflicting `translation_of` and `translation_of_original`
- [x] automatic PR to translation repos when moving original content in [mdn/content](https://github.com/mdn/translated-contentmdn/content)
- [x] apply ad-hoc changes from original content when deploying 
- [x] migrate [mdn/translated-content](https://github.com/mdn/translated-content) 
- [ ] migrate [mdn/translated-content-rendered](https://github.com/mdn/translated-content-rendered)

**Comment by peterbe** [comment]
Close?
