### ISSUE TITLE
Offline docs dump broken

### ISSUE THREAD

**Issue by Kapeli** [mdn/yari#2362]
Hi. I'm the maintainer of https://kapeli.com/mdn_offline, an offline dump of the docs found on MDN.

I'm not able to get the docs to work offline anymore. All pages show this error:

<img width="1268" alt="Screenshot 2021-01-06 at 18 13 50" src="https://user-images.githubusercontent.com/1445635/103791299-f7324180-504a-11eb-80f2-aadf14d564e0.png">

This might be related to/caused by https://github.com/mdn/yari/pull/2010, but I'm not sure.

You can replicate the error by downloading [CSS.zip](https://www.dropbox.com/s/5tc0akfclbas89t/CSS.zip?dl=0) and loading `Documents/developer.mozilla.org/en-US/docs/Web/CSS/display.html`.

I tried removing the JS completely from the pages and that causes the pages to display just fine, except that the compatibility tables don't show up anymore.

Any idea how I should proceed or what would be the best place to disable the display of that error page? Any help is greatly appreciated.

Thank you!

**Comment by escattone** [comment]
@Kapeli I'm sorry but we don't have time to help you debug your issue.

**Comment by kaveinthran** [comment]
I am not sure if this is a correct reply for an individual who works and democratise mdn to those who do not have good bandwith, it sounds like people know less manners than coding

**Comment by kennyneedsmilky** [comment]
That's sad to hear. I hope for the best.

**Comment by mattiapontonio** [comment]
What I know here is that exists
https://github.com/mdn/content
But i don't know how to use that _not-in-yari_

**Comment by Ryuno-Ki** [comment]
In #2299 it sounds like a service-worker approach was thought about.

The „problem” you're having next @Kapeli, is that the page gets rendered with React.
Perhaps you can wait until the content was migrated over to Markdown?
It should be possible to pipe that through a static site generator to recreate an offline version, I think.
