### ISSUE TITLE
iframe#result height

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2364]
![Screenshot_20201209-233442.png](https://user-images.githubusercontent.com/44380480/101697037-60885a00-3a77-11eb-9056-aa6d7d531131.png)

**Comment by schalkneethling** [comment]
![Screenshot of iframe height problem resolved](https://user-images.githubusercontent.com/10350960/104190354-a8a6ed80-5424-11eb-9cd5-a2c9df34cbc0.png)

This is what we need it to look like. Example URL:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

**Comment by mattiapontonio** [comment]
![Screenshot_20210111-150405.png](https://user-images.githubusercontent.com/44380480/104191843-54007400-541e-11eb-83c9-7567ed8b44e0.png)

How It looks now.
There Is no way to compute the height from the `src`? (Possibile stupid idea ⚠️).

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Sample code frame](https://trello.com/c/CtUCPtOH/18-sample-code-frame)

**Comment by schalkneethling** [comment]
This will be resolved in minimalist: https://github.com/mdn/mdn-minimalist/issues/422
