### ISSUE TITLE
Make sure live example source is always available from the compiled and rendered HTML of developer.mozilla.org and not only from the CDN as well

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2386]
When there is an `<iframe>` for code provide a link to the source so i can click from the smartphone and see how it is displayed in a new window.

## What I'm expecting?
An anchor
https://developer.mozilla.org/en-US/docs/web/HTML/element/a

## Where?
Near the context of the `<iframe>`.

---
- https://github.com/mdn/yari/issues/1428
- #2683
- https://github.com/mdn/content/issues/1653

**Comment by chrisdavidmills** [comment]
This is a pretty good idea. To make this issue work better, I'd suggest updating the title to something shorter and less verbose like "Make sure live example source is always available", then include the current title text in the description.

I'd then suggest expanding the description to maybe describe what you think it could look like, and if there are any guidelines we could write to make this more consistently done.

For example, in the live examples that pull the code from code blocks on the page, the source code is usually visible.

But in iframe examples taken from GitHub, the code is generally not. when I use a GitHub live example, I usually provide a link to the live example in case you want to run it in a separate tab, and a link to the source code so you can see it.

If we wrote a guideline that all live examples should be like this and then tried to enforce it, then that might solve your issue to a large degree. Or you could argue that we might need a new bit of site functionality to serve this purpose.

Either way, this is a useful discussion.

**Comment by mattiapontonio** [comment]
We should move to discussions?

**Comment by chrisdavidmills** [comment]
This is probably OK here, as it is a discussion about a potential change that is pretty actionable. Not just theoretical, or "maybe we could do something like this".

**Comment by mattiapontonio** [comment]
Note to self
I map _Make sure_ to _testing_.
This Is not a testing issue Is a implementation issue because i don't know where to open issue for asserting that this link Is present.

**Comment by escattone** [comment]
@chrisdavidmills Thanks for the clarification of what this issue is about. Is the following a fair summary of what this issue is suggesting as a change?

1. For each `EmbedLiveSample` macro, in addition to the `iframe` also add a link to the example page so it can be opened in its own browser tab.
2. For each `EmbedGHLiveSample` macro, in addition to the `iframe` also:
    - add a link to the example page so it can be opened in its own browser tab
    - add a link to the example's source code in GitHub

**Comment by escattone** [comment]
@chrisdavidmills Unless you suggest otherwise, this would not be a high priority for the dev team. For now, I'm going to give it a `p3` (meaning it's a valid request, but given everything we have to do, not something we plan on doing at least into the foreseeable future).
