### ISSUE TITLE
Add IT 🇮🇹 in Canvas Macro ejs

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2396]
https://www.github.com/mdn/yari/tree/master/kumascript%2Fmacros%2FCanvasSidebar.ejs

Question:
Can I just copy the _en_, keep the keys and translate the values?

**Comment by chrisdavidmills** [comment]
> https://www.github.com/mdn/yari/tree/master/kumascript%2Fmacros%2FCanvasSidebar.ejs
> 
> Question:
> Can I just copy the _en_, keep the keys and translate the values?

Yes, you can. In exactly the same way as there's a `zh-CN`, `ru` language strings object, you just need to create an equivalent for `it`

**Comment by mattiapontonio** [comment]
I'll see if I find any Italians so let's try the issue opening, PR and review flow in 3.
