### ISSUE TITLE
chevron in content + another svg

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2404]
Regarding the "area" of this PR i have 2 issues:

- the SVG should be in `content`
- the arrow should be a _new SVG_ and not a _different SVG rotated_

Why?
- [SoC](https://en.m.wikipedia.org/wiki/Separation_of_concerns#:~:text=In%20computer%20science%2C%20separation%20of,code%20of%20a%20computer%20program.)
- maintainability

https://github.com/mdn/yari/issues/2260

**Comment by escattone** [comment]
@mattiapontonio I suspect this should be a comment on #2260?  Either move this comment to #2260 (and close this issue), or more clearly define what you're talking about here.
