### ISSUE TITLE
Publish to Elasticsearch in deployer

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2410]
After we've uploaded to S3 and Lambda, we should bulk publish all the content to Elasticsearch. 
Let's close this issue once we have:

- [x] A deployer script that works and has been tested against our (new) staging/dev ES server(s)
- [x] Create a Dev, Stage, and Prod Elastico URLs and enter their URLs into Secrets on the Yari repo.
- [x] Invocation of this at the bottom of the `prod-build.yml`, `stage-build.yml` and `dev-build.yml`.

**Comment by peterbe** [comment]
@escattone Next up is to create the URLs and put them into Secrets. One for each environment.

**Comment by escattone** [comment]
@peterbe 👍 Thanks for reminding me. I'll take care of that, and let you know when they're ready.

**Comment by escattone** [comment]
> @escattone Next up is to create the URLs and put them into Secrets. One for each environment.

@peterbe This is done. We now have the following ES secrets in this repo:
- `DEPLOYER_DEV_ELASTICSEARCH_URL` (this one we actually added on November 13, 2020)
- `DEPLOYER_STAGE_ELASTICSEARCH_URL`
- `DEPLOYER_PROD_ELASTICSEARCH_URL`

**Comment by peterbe** [comment]
I guess this means we can start adding what was added to the bottom to stage-build.yml to the prod-build.yml and then this issue is complete.
