### ISSUE TITLE
https://media.prod.mdn.mozit.cloud/samples/html/currentScript.html — How to edit the source?

### ISSUE THREAD

**Issue by sideshowbarker** [mdn/yari#2414]
https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript is a link to https://media.prod.mdn.mozit.cloud/samples/html/currentScript.html, and the code of that currentScript.html sample doesn’t appear to be working as expected, so I wanted to update it.

But I can’t find anywhere in github where the source for the resource is stored.

**Comment by mattiapontonio** [comment]
Try to read _More mdn projects_ here in readme
https://github.com/mdn/sprints

Is in _interactive-examples_?

**Comment by Elchi3** [comment]
I've tried to migrate these into an editable space, but never finished that. See https://bugzilla.mozilla.org/show_bug.cgi?id=1076893 for background and a list of stuff under /samples.

**Comment by sideshowbarker** [comment]
> I've tried to migrate these into an editable space, but never finished that. See [bugzilla.mozilla.org/show_bug.cgi?id=1076893](https://bugzilla.mozilla.org/show_bug.cgi?id=1076893) for background and a list of stuff under /samples.

ah OK thanks

so given that, for the specific case of that https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript article — and given that the sample doesn’t work as expected anyway (which is I why I wanted to try to edit it) — I guess the best thing do is for me to is to wrie a good working example in the article itself, and then do an EmbedLiveSample for that, and completely remove the link to that https://media.prod.mdn.mozit.cloud/samples/html/currentScript.html sample.

**Comment by escattone** [comment]
> so given that, for the specific case of that https://developer.mozilla.org/en-US/docs/Web/API/Document/currentScript article — and given that the sample doesn’t work as expected anyway (which is I why I wanted to try to edit it) — I guess the best thing do is for me to is to wrie a good working example in the article itself, and then do an EmbedLiveSample for that, and completely remove the link to that https://media.prod.mdn.mozit.cloud/samples/html/currentScript.html sample.

That would be great if you have time. Thanks @sideshowbarker!
