### ISSUE TITLE
Mention sprints readme in Yari readme

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2419]
Can We mention this readme

https://www.github.com/mdn/sprints/tree/master/README.md

For a better overview for people that land on Yari first?

**Comment by chrisdavidmills** [comment]
It would be good to update the Yari readme to talk a little about what MDN is, say briefly what content work is going on, and then link to the content repo. I'm planning on moving all the sprint work (the project boards and other information) over to the content repo and then closing down the sprints repo. What's on the sprints readme right now is somewhat out of date too.

But thanks for bringing this up. I'll keep this issue to hand as a reminder to get that sorted.

**Comment by mattiapontonio** [comment]
Actually i don't really care about the sprint repo but the readme is good and well formatted 👍
