### ISSUE TITLE
Provide a "global 🚥 indicator of support" in the feature page

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2420]
Feature proposal:

Asumming a feature is supported by **0** to **x** browsers.
The page of the feature should present an indicator that is:

- 🟩 if the feature is supported by **x** browsers
- 🟨 if the feature is supported by a number of browsers between **0** and **x**
- 🔴 if the feature is supported by **0** browsers

**Comment by peterbe** [comment]
This is vague and low priority. It would need to describe more clearly what and where it should show this.

**Comment by mattiapontonio** [comment]
Ok.
Looking forward to new _specs_.
I see the _need design_ label somewhere.

**Comment by mattiapontonio** [comment]
<span style="background:yellow;border-radius:4px;">Need design</span>

**Comment by mattiapontonio** [comment]
Does It make sense? 🤔🔢

| Feature | Browser | Browser | Total |
|---------|---------|---------|-------|
| A       | 1       | 0       | 0     |
| B       | 1       | 1       | 1     |
| Total   | 1       | 0       | 0     |
