### ISSUE TITLE
These L10N json are "hidden" in macros

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2429]
Can We please move?
I didn't expert to find there.
And as I see somewhere this macro folder is kind of deprecated...

![Screenshot_20210110-031656.png](https://user-images.githubusercontent.com/44380480/104112688-641b3500-52f2-11eb-9cc5-b6cd98067c65.png)

Something like

`L10N/file.json`

**Comment by escattone** [comment]
@mattiapontonio This is not worth the effort. We have so many more important things to focus on.
