### ISSUE TITLE
Implement Home Page

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2438]
As the first step to https://github.com/mdn/yari/issues/1255 we need to implement the current homepage that is still being served from Kuma in Yari

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Implement Homepage](https://trello.com/c/RvQ4yGTD/21-implement-homepage)

**Comment by peterbe** [comment]
https://github.com/mdn/yari/pull/2689 has been merged. Now we need to add the SSR rendering and the Hacks blog feed thing.

**Comment by mattiapontonio** [comment]
These are the [high level folders which are less than the French](https://hacks.mozilla.org/2021/02/mdn-localization-update-february-2021/) ones which is good.
Shouldn't they be listed on the homepage to give the menu and the blog a separate structure?

- games
- glossary
- learn
- mdn
- mozilla
- plugins
- related
- tools
- web
- webassembly

**Comment by peterbe** [comment]
The new home page is live and in prod. 
We have some [more work to do with the Lambda function](https://github.com/mdn/yari/pull/2922) but that's run separately.
