### ISSUE TITLE
Propose design for Yari content authoring toolbar

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2440]
The is the current implementation of the Yari content authoring toolbar:

## Initial state

![Screenshot 2021-01-11 at 12 41 08](https://user-images.githubusercontent.com/10350960/104170903-856f4480-540a-11eb-8600-214678ff95db.png)

## Expanded state

![Screenshot 2021-01-11 at 12 41 18](https://user-images.githubusercontent.com/10350960/104170939-90c27000-540a-11eb-94b3-f340206a9c7c.png)

While this is good enough, we should explore some options on how we can make this even better for end-users. We might even consider thinking of this in terms of three pieces:

- The main toolbar
- The Flaws section
- The document spy

@chrisdavidmills Do you have any requests or ideas on how we can improve this feature to improve the authoring experience? Have you heard any complaints or requests from current contributors?

**Comment by schalkneethling** [comment]
This discussion might also be relevant https://github.com/mdn/yari/discussions/2422

**Comment by mattiapontonio** [comment]
Can I have the mobile URL?

**Comment by schalkneethling** [comment]
> Can I have the mobile URL?

This is only available on desktop.

**Comment by peterbe** [comment]
> This discussion might also be relevant #2422

It's just another flaw. Should haven't an impact on the design of the toolbar.

**Comment by schalkneethling** [comment]
The toolbar was improved as part of the redesign so, closing this one.
