### ISSUE TITLE
[Feature] Referenced in

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2441]
GitHub automatically marks a issue as referenced in another issue.
Could be fine to have the same feature in the doc, so a section that lists documents that reference the current one.

🤔🔃

![Screenshot_20210111-123453.png](https://user-images.githubusercontent.com/44380480/104177820-ad11dd00-5409-11eb-944d-dd7d7c5bdb34.png)

**Comment by peterbe** [comment]
What does "section that lists documents that reference the current one" mean??

**Comment by mattiapontonio** [comment]
Something like the following.

## Class.method() document title

The `method` method is a method but even a property and a function.

### Referced in
- [OPP tutorial]()
- [Class]()
- [Learning something]()
