### ISSUE TITLE
Header graphics for topic landing pages

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2443]
As mentioned by @chrisdavidmills here https://github.com/mdn/yari/issues/1145#issuecomment-757838687

> What we've got there already is functional, and we've got bigger fish to fry right now. Although 
> maybe somewhere later on down the line we could think about at least have a nice little header 
> graphic for each major landing page.

I agree that this would be nice to explore.

**Comment by mattiapontonio** [comment]
Use data attributes for enum!

```html
data-topic="CSS"
```

**Comment by Ryuno-Ki** [comment]
Could https://docs.htmlcsstoimage.com/ (like used by The Practical Dev's forem software) be an option?

**Comment by Ryuno-Ki** [comment]
https://github.com/forem/forem/blob/d822d8d7d99ce1b9a1c65e50bf8e5a9be3185bda/app/lib/html_css_to_image.rb#L8-L10

shows their implementation in Ruby

**Comment by mattiapontonio** [comment]
But what does it have to do with the issue?
However, I have always found [tamarro](https://it.m.wikipedia.org/wiki/Tamarro) that the same HTML of the animated product is reimplemented in the commercial pages.
