### ISSUE TITLE
Legends section not shown, sometimes, in BCD tables

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2444]
See http://localhost:3000/en-US/docs/Web/API/Notification/Notification#browser_compatibility for example. 
Renders like this:
 
<img width="1059" alt="Screen Shot 2021-01-11 at 10 09 44 AM" src="https://user-images.githubusercontent.com/26739/104199294-44206a00-53f5-11eb-8603-8e91482a4c80.png">

In the Wiki, it would always show the legends section. 
<img width="1112" alt="Screen Shot 2021-01-11 at 10 11 11 AM" src="https://user-images.githubusercontent.com/26739/104199359-57333a00-53f5-11eb-8d49-af4b1cd2c6d2.png">

**Comment by mattiapontonio** [comment]
Maybe I go too far but that legend should be removed in my opinion in favor of `th`.

**Comment by peterbe** [comment]
> Maybe I go too far but that legend should be removed in my opinion in favor of `th`.

Let's worry about that later. Right now, this issue describes a regression from how BCD tables were designed to work in MDN. Similar to https://github.com/mdn/yari/issues/2163
Once this is settled, the likes of @ddbeck can push for modernized changes.

**Comment by mattiapontonio** [comment]
Yes.
_Don't call that legend since legend Is for forms._
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/legend
