### ISSUE TITLE
Transfer account sign-in/sign-up landing page

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2449]
When a user is on mobile, right-clicks the "Sign in" link to open the URL in a new tab, or JavaScript failed for whatever reason, the user is taken to https://developer.mozilla.org/en-US/users/account/signup-landing?next=/en-US/

![Screenshot of account sign-in/sign-up landing page](https://user-images.githubusercontent.com/10350960/104215282-398bc200-5441-11eb-8ee0-182f89e39f29.png)

This is currently served by the old codebase and needs to be transferred to Yari.

## Open Question

As we have a moment to reconsider this flow I am wondering whether we should just remove the modal completely. For one thing, most of our users never log in, and those that do, stay signed in pretty much forever 😄 

This means it is something that is not used a lot and so, it probably does not make sense to keep all of this complexity. We used to have modals for the subscription flow, but that is now gone as well. That means the sign-in modal is now the only modal we have.

If we do away with the modal we can remove quite a bit of JS and SCSS and, we can remove the dependency on React Modal. The downside is that when a user clicks on sign-in, they are taken to a different page instead of being presented with a modal on the same page.

Thoughts?

**Comment by mattiapontonio** [comment]
I think We need 3 paths:

`account/sign/in`
`account/sign/up`
`account/benefits`

No modals.

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Transfer account sign-in/sign-up landing page](https://trello.com/c/bVgrduJR/22-transfer-account-sign-in-sign-up-landing-page)

**Comment by peterbe** [comment]
I'm going to make a PR that partially close this issue and then "hand it over" to you @schalkneethling when it's in `main`.

**Comment by peterbe** [comment]
Note-to-us: We can implement the new sign in and sign up under a new endpoint in the App, but we mustn't change the "Sign in" link otherwise we need to nail this perfectly when we merge to `main`. So it'll be an optional env var that just exists quite temporarily.

**Comment by schalkneethling** [comment]
Here are the layout comps for the first iteration of the sign-in/sign-up page:

## Desktop

![Screenshot of sign-in page on desktop](https://user-images.githubusercontent.com/10350960/108189700-b6354e80-7119-11eb-8249-3effcb1fff24.png)

## Tablet

![Screenshot of sign-in page on tablet](https://user-images.githubusercontent.com/10350960/108189866-e7158380-7119-11eb-86cf-13e310f5d52d.png)

## Mobile

![Screenshot of sign-in page on mobile](https://user-images.githubusercontent.com/10350960/108189904-f0065500-7119-11eb-81dd-9f6e9e19a8ef.png)

https://www.figma.com/file/YYVJ8uqG8UFBBvQhdI7fxR/MDN-Web-Docs?node-id=2242%3A0

**Comment by escattone** [comment]
@schalkneethling I like your latest mock-ups!

**Comment by peterbe** [comment]
We still need to enable it.
