### ISSUE TITLE
Yari doesn't completely respect CONTENT_ROOT changes

### ISSUE THREAD

**Issue by ddbeck** [mdn/yari#2452]
Presently, Yari punishes you for getting `CONTENT_ROOT` wrong and fixing it.

For example, suppose I set `CONTENT_ROOT` to `/path/to/mdn/content/` instead of `/path/to/mdn/content/files/`, then run `yarn dev`. Then I check the site and find that all the content 404s. So, I go back and change `CONTENT_ROOT` to point to the correct directory and re-run `yarn dev`. At this point, Yari helpfully reuses data from the previous run:

```
Reusing existing history from /var/folders/5v/mzyz10hs433586qr7xtrqth00000gn/T/yari-git-history.json
```

And it _continues_ to return 404s for all the content. It did so until I deleted `yari-git-history.json`.

Since Yari writes a bunch of data outside the project directory, at any given moment, it's not obvious that I'm _not_ working with a clean Yari run. I had to carefully read the extensive console output to find that Yari was reusing data from a previous run.

Some ideas to make this less painful:

- Provide some authoritative `clean` command (e.g., running `yarn clean` nukes anything that Yari might've built for a run and guarantees that the next run is from a pristine state)
- Invalidate `yari-git-history.json` when the path to `CONTENT_ROOT` changes

**Comment by peterbe** [comment]
Weird that something in the `yari-git-history.json` file gives you 404s! That in itself might be a good place to start.

**Comment by peterbe** [comment]
We should see if https://github.com/mdn/yari/pull/2365 solves this issue.

**Comment by mattiapontonio** [comment]
Is **content** a dependency?
https://docs.npmjs.com/cli/v6/configuring-npm/package-json#dependencies
...

**Comment by peterbe** [comment]
@ddbeck Any chance you can see if https://github.com/mdn/yari/pull/2661 solves this issue now?

**Comment by ddbeck** [comment]
@peterbe I can confirm that this is resolved now. Thank you!
