### ISSUE TITLE
Contributions 400 bad request

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2454]
![Screenshot_20210111-200322.png](https://user-images.githubusercontent.com/44380480/104226471-26302500-5448-11eb-97eb-4f0bce1907cc.png)

https://developer.mozilla.org/en-US/dashboards/revisions?user=MattiaPontonio

**Comment by peterbe** [comment]
Dashboards are dead.

**Comment by mattiapontonio** [comment]
Came from
![Screenshot_20210111-220948.png](https://user-images.githubusercontent.com/44380480/104238761-bf1b6c00-5459-11eb-81cf-ae1c9b3300b3.png)

**Comment by escattone** [comment]
@mattiapontonio Thanks for reporting this. This issue will be resolved as soon as I deploy (in about an hour or less) 
the latest Kuma changes (which killed dashboards and got rid of the `Contributions` link).
