### ISSUE TITLE
Newsletter checkbox not aligned

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2455]
https://developer.mozilla.org/en-US/profiles/MattiaPontonio/edit

![Screenshot_20210111-200623.png](https://user-images.githubusercontent.com/44380480/104226718-8c1cac80-5448-11eb-9e59-36b26fc7413f.png)

**Comment by tannerdolby** [comment]
It is indeed very slightly raised above the neighboring text. One thing to note, the Profile page styling is handled in `mdn/kuma` so this issue may need to be transferred there if an MDN team member sees that the issue needs to be fixed.

<img width="784" alt="Screen Shot 2021-01-12 at 10 09 09 PM" src="https://user-images.githubusercontent.com/48612525/104413304-f6098480-5522-11eb-8557-75223bc2060a.png">

The `input` element of `type="checkbox"` within the `#newsletterPrivacy` container is the one that is slightly mis-aligned.

```html
<div id="newsletterPrivacy" class="form-group form-group-agree newsletter-group-privacy">
  <input type="checkbox" id="newsletterPrivacyInput" name="privacy" required="">
  <label for="newsletterPrivacyInput">
  I'm okay with Mozilla handling my info as explained in this <a href="https://www.mozilla.org/privacy/">Privacy Policy</a>. 
  </label>
</div>
```

Adding `vertical-align: middle` does fix the alignment issue, but introduces some bad alignment on the bottom. Bumping the bottom margin from `3px` to `5px` makes things look nice and evenly aligned.

<img width="914" alt="Screen Shot 2021-01-12 at 10 06 13 PM" src="https://user-images.githubusercontent.com/48612525/104413057-6ebc1100-5522-11eb-99d9-9544bd31699b.png">

_Screenshot with red alignment lines for annotation_
<img width="914" alt="Screen Shot 2021-01-12 at 10 06 13 PM" src="https://user-images.githubusercontent.com/48612525/104413152-a460fa00-5522-11eb-918c-2b2dd8daa7cc.png">

I'm happy to submit a PR for this over in `mdn/kuma`. Just let me know.

**Comment by schalkneethling** [comment]
For right now I would not worry about this. Profiles/accounts are soon going to be moved to Yari. As part of the process, it will also get a facelift and we will address these items then.

**Comment by mattiapontonio** [comment]
Yes.
I think is something related to `font-size` and `line-height`.

**Comment by schalkneethling** [comment]
Those checkboxes will be removed for the time being so, I am going to close this issue.
