### ISSUE TITLE
Unespected 403

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2462]
If i curl in this order i got a 403 where I'm expecting a 200:

```
curl https://developer.mozilla.org/en-US/profiles/MattiaPontonio
200 🆗
curl https://developer.mozilla.org/en-US/profiles/MattiaPontonio/edit
403 🆗
curl https://developer.mozilla.org/en-US/profiles/MattiaPontonio
403 🔴 expected: 200
curl https://developer.mozilla.org/en-US/profiles/MattiaPontonio
200 🆗
```

https://reqbin.com/curl

**Comment by escattone** [comment]
@mattiapontonio I can't reproduce this using `curl` from a shell command line. I suspect this is an issue with https://reqbin.com/curl or something unrelated to MDN.
