### ISSUE TITLE
[Feature request] Allow for browsing by return type

### ISSUE THREAD

**Issue by tomayac** [mdn/yari#2472]
I was [wondering](https://twitter.com/tomayac/status/1348734935650201602) what methods or properties return a [`ReadableStream`](https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream). Examples are [`Body.body`](https://developer.mozilla.org/en-US/docs/Web/API/Body/body) or [`Blob.stream()`](https://developer.mozilla.org/en-US/docs/Web/API/Blob/stream), but there is currently no way to obtain a complete list. This is a feature request to add such functionality to the docs. Possible solutions:

- @samthor [suggested](https://twitter.com/samthor/status/1348935724909748224) parsing TypeScript `.d.ts` files.
- @chrisdavidmills [meant](https://twitter.com/chrisdavidmills/status/1348948067408621571?s=20) it would be easy to *"write a script that crawls the repo and returns all instances of features with a certain return value"*.
- Another idea might be to look at Web IDL.

**Comment by mattiapontonio** [comment]
Does count `new ReadableStream()` works?

**Comment by tomayac** [comment]
> Does count `new ReadableStream()` works?

I don't think this would catch cases like `fetch('./foo').then(response => response.body)`.

**Comment by mattiapontonio** [comment]
I don't know Typescript well but there is some difference between what is _exposed and documented so it can be tested_ and what is the statment at run te of each line.
IMHO

**Comment by peterbe** [comment]
@chrisdavidmills Can you help me. 
The content isn't structured. Documents have `tags` but Yari has no great way to navigate by tags. At the moment, tags are only ever used by the KumaScript sidebar macros. 

Is this a Yari issue or a Content issue?

**Comment by mattiapontonio** [comment]
I am thinking of a `returns` key in `YAML` that accepts a `URL`.

**Comment by tomayac** [comment]
The W3C repo https://github.com/w3c/webref/ looks pretty close to something that could be promising for this purpose. A simple [search](https://github.com/w3c/webref/search?p=1&q=readablestream+extension%3Aidl&type=) already turns up usable results. All that's missing now would be a tool on top to filter by return types.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills Can you help me.
> The content isn't structured. Documents have `tags` but Yari has no great way to navigate by tags. At the moment, tags are only ever used by the KumaScript sidebar macros.
> 
> Is this a Yari issue or a Content issue?

Maybe I am underestimating how difficult this would be to do. I had it in mind that we could create functionality that could crawl webapi pages and find all the ones that contain say `<code>ReadableStream</code>` underneath the `<h2>Return value</h2>` heading. This is what all such pages should feature.

Of course, there is currently no linting that goes on for MDN pages to enforce this, so we can't guarantee this structure in all cases.

This kind of use case shows why the linting/recipe project we did for the CSS/JS references is potentially so useful. Maybe it would be an idea to postpone thinking about this until we have got further with linting? 

another thought — would it be feasible at all to add things like "return value" to the YAML frontmatter?

**Comment by mattiapontonio** [comment]
> The W3C repo https://github.com/w3c/webref/ looks pretty close to something that could be promising for this purpose. A simple [search](https://github.com/w3c/webref/search?p=1&q=readablestream+extension%3Aidl&type=) already turns up usable results. All that's missing now would be a tool on top to filter by return types. 

It will be trivial but I like this idea because it is _W3C_ and it is _already done_. I just don't know how to make [idl](https://en.m.wikipedia.org/wiki/Interface_description_language) _talk_ to Node.

**Comment by peterbe** [comment]
> another thought — would it be feasible at all to add things like "return value" to the YAML frontmatter?

Yes! That would be a very nice a structured place. Not perfect, but much better than parsing the content.

**Comment by mattiapontonio** [comment]
If you put it there it can be smart to accept the full URL so in case there is more metadata to take you can make a number of promises in retrieving these URLs including the title. So does the 1 time build right? In general the whole URL is better than a string which we then have to keep consistent around.

**Comment by schalkneethling** [comment]
> > @chrisdavidmills Can you help me.
> > The content isn't structured. Documents have `tags` but Yari has no great way to navigate by tags. At the moment, tags are only ever used by the KumaScript sidebar macros.
> > Is this a Yari issue or a Content issue?
> 
> Maybe I am underestimating how difficult this would be to do. I had it in mind that we could create functionality that could crawl webapi pages and find all the ones that contain say `<code>ReadableStream</code>` underneath the `<h2>Return value</h2>` heading. This is what all such pages should feature.
> 
> Of course, there is currently no linting that goes on for MDN pages to enforce this, so we can't guarantee this structure in all cases.
> 
> This kind of use case shows why the linting/recipe project we did for the CSS/JS references is potentially so useful. Maybe it would be an idea to postpone thinking about this until we have got further with linting?
> 
> another thought — would it be feasible at all to add things like "return value" to the YAML frontmatter?

@ddbeck @Rumyra What do you think about this? Adding something to the Frontmatter is one thing but then we also need a way to surface that via search or the UI somehow. I guess the question is, should we invest the time to make this happen, will it benefit enough readers to warrant the time investment?

**Comment by ddbeck** [comment]
I think we should not do this, at least not in this form. Reading this thread, I think Chris's comment is still the thing:

> Maybe it would be an idea to postpone thinking about this until we have got further with linting?

I think this sort of thing should emerge as a consequence of content modeling work. It's _possible_ to sprinkle structure on existing content, but that's also sort of how you end up in a situation like mdn/data. If we're going to start introducing new frontmatter fields, we need to start with page type and do the work to structure the content accordingly.

**Comment by tomayac** [comment]
Thanks for the transparency regarding the decision to _not_ proceed. Appreciated you taking the time to consider this nevertheless.

**Comment by schalkneethling** [comment]
> Thanks for the transparency regarding the decision to _not_ proceed. Appreciated you taking the time to consider this nevertheless.

And thank _you_ for the suggestion Please keep them coming. It helps us so much if we know what our readers would actually find useful as opposed to us guessing 😄
