### ISSUE TITLE
Don't syntax highlight hidden <pre> tags

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2474]
Look at https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool for example. 
[Its raw HTML](https://github.com/mdn/content/blob/main/files/en-us/web/css/css_colors/color_picker_tool/index.html) looks something like this:

```html
<div style="display: none;">
<h2 id="ColorPicker_Tool">ColorPicker tool</h2>

<h3 id="HTML">HTML</h3>

<pre class="brush: html">    &lt;div id="container"&gt;
        &lt;div id="palette" class="block"&gt;
            &lt;div id="color-palette"&gt;&lt;/div&gt;
...

```

But when Yari gets its hands on it, that `<pre>` tag is extracted and sent into Node Prism to be syntax highlighted. 
What happens is that the HTML bloats unnecessarily for `<pre>` tags that are never meant to be consumed by the human eye. See view-source:https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool whose HTML is serialized for in the HTML itself and then in the JSON serialized React state (towards the end). This slows down Prism syntax highlighting unnecessarily and most importantly, it makes the HTML bigger than it needs to be.

**Comment by peterbe** [comment]
One thing to note is that mdn/content (en-US) there are 1,709 `<pre>` tags that are inside a `<div class="hidden">` or a `<div style="display:none">`. That basically means 1,709 `pre` tags that we can omit.

**Comment by peterbe** [comment]
Useful pages to test with:

* http://localhost:3000/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool
* http://localhost:3000/en-US/docs/Learn/CSS/Styling_text/Fundamentals

You can see the result if you switch to `:5000` and use view source. E.g. view-source:http://localhost:5000/en-US/docs/Learn/CSS/Styling_text/Fundamentals

**Comment by mattiapontonio** [comment]
Why not a simple flaw?
