### ISSUE TITLE
Page overflow in the x direction for `/en-US/docs/Web/CSS/Grid`

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#2478]
I encountered some overflow in the x direction on my laptop screen (1024px) for [CSS Grid](https://developer.mozilla.org/en-US/docs/Web/CSS/grid) documentation. The overflowed content is scrollable, so I could imagine `overflow-x: scroll` exists somewhere. 

_Screenshot of overflow-x content_
<img width="1275" alt="Screen Shot 2021-01-12 at 10 37 02 AM" src="https://user-images.githubusercontent.com/48612525/104357513-27059d00-54c2-11eb-9872-c87e4d549e5e.png">

I'm not sure if this is reproduced on any other pages, but for now the CSS Grid docs page is the only one I can say for certain has this overflow issue.

**Comment by tannerdolby** [comment]
After investigating this a bit more, the problem is being caused from the `<main>` element width. In particular, since there aren't any styles applied to `.main-content`. I added a`max-width` property to the first child element in `.main-content` which is an `<article>` tag and this fixed things.

```html
<main id="content" class="main-content" role="main"><article class="article">
  <article class="article">...</article>
</main>
```

Adding `max-width: 1100px` to the `.article` class makes the overflow issue goes away. It seems for some reason the width on the `<main>` content is whats causing the overflow-x situation.

<img width="283" alt="Screen Shot 2021-01-13 at 8 26 11 PM" src="https://user-images.githubusercontent.com/48612525/104544830-9de38880-55dd-11eb-97e8-6410449bea8b.png">

<img width="1272" alt="Screen Shot 2021-01-13 at 8 23 56 PM" src="https://user-images.githubusercontent.com/48612525/104544728-4fce8500-55dd-11eb-8b9f-d5f2794350f6.png">

The [CSS - MDN](https://developer.mozilla.org/en-US/docs/Glossary/CSS) page amongst others don't have this overflow problem and doesn't require an explicit `max-width` to `.article` or `<main>` like the [CSS Grid - MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/grid) page does. I'm not sure adding `max-width: 1100px` is a fix but more of a band-aid, yes it fixes the overflow issue but just masks the underlying root issue causing the overflow. I have a suspicion that something within `.article`, potentially the `<iframe>` or maybe the browser compatibility table, its tough to pinpoint exactly what the cause is.

**Comment by peterbe** [comment]
@schalkneethling Can you please triage this?

**Comment by tannerdolby** [comment]
I just noticed this on the [:nth-child() - CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) page as of today too.

**Comment by schalkneethling** [comment]
> I just noticed this same overflow issue on the [:nth-child() - CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) page as of today too.

Thanks! This is the very next item on my todo list

**Comment by tannerdolby** [comment]
Your welcome @schalkneethling ! 

Let me know if there is anything I can do to help.

**Comment by tannerdolby** [comment]
@schalkneethling I know your working on this already (and may have committed fixes) but I wanted to share that the [position - CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/position) page is also experiencing the overflow issue.

**Comment by tannerdolby** [comment]
Pinging you again Schalk, [Array.prototype.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) page has the `overflow-x` issue. Not sure if this is just happening on MacOS when viewing in chrome but that's what I'm currently using.

**Comment by schalkneethling** [comment]
> Pinging again, [Array.prototype.filter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) page has the `overflow-x` issue. Not sure if this is just happening on MacOS when viewing in chrome but that's what I'm currently using.

Thanks, @tannerdolby. This will be addressed by something I snuck into https://github.com/mdn/yari/pull/2839

**Comment by tannerdolby** [comment]
Your welcome, @schalkneethling. Ok sounds good, thanks for the heads up.

**Comment by schalkneethling** [comment]
@tannerdolby So https://github.com/mdn/yari/pull/2839 as landed in `main`. In ~24 hours or so it should on production. I will of course test, but if you could also have a look and see whether the overflow issues have been resolved I would very much appreciate that.

**Comment by tannerdolby** [comment]
@schalkneethling Sure thing. I'll have a look tonight and see if I can find any pages where the overflow issues still exist.

**Comment by tannerdolby** [comment]
@schalkneethling I checked all the pages that I had taken note of having the overflow issue, and everything seems to be fixed. I will continue looking around to see if any issues still exist, but I think you've fixed the problem. Nice work!

**Comment by schalkneethling** [comment]
> @schalkneethling I checked all the pages that I had taken note of having the overflow issue, and everything seems to be fixed. I will continue looking around to see if any issues still exist, but I think you've fixed the problem. Nice work!

Thanks so much for double-checking!
