### ISSUE TITLE
EmbedLiveSample fails if the ID gets changed from the text

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2488]
E.g. http://localhost:3000/en-US/docs/Web/CSS/CSS_Colors/Color_picker_tool/#_flaws

The reason it's failing is because it has this HTML:
```html
<div style="display: none;">
<h2 id="ColorPicker_Tool">ColorPicker tool</h2>

<h3 id="HTML">HTML</h3>

<pre class="brush: html">    &lt;div id="container"&gt;
...
</pre>
</div>

<div>{{ EmbedLiveSample('ColorPicker_Tool', '100%', '900') }}</div>
```

Internally, the `<h2 id="ColorPicker_Tool">ColorPicker tool</h2>` get actually gets changed to `<h2 id="ColorPicker_tool">ColorPicker tool</h2>` (not the lowercased `t` in the ID). It overrides whatever the ID is to what of the `<h2>`'s text (spaced replaced with underscores). 
So there is `#ColorPicker_Tool` (there's only a `#ColorPicker_tool`) and hence it fails. 

That `<h2>` used to have a `name` attribute which made it less fragile to changes in the text.

**Comment by peterbe** [comment]
Also, imagine the HTML was first this:
```html
<h2 id="ColorPicker_Tool">ColorPicker tool</h2>
```
and note that there's no `name` attribute again. It's highly likely that a translator might be tempted to change that to.
```html
<h2 id="ColorPicker_Tool">FärgPlocknings verkyg</h2>
```
...which would get an "intermediate" HTML of:
```html
<h2 id="FärgPlocknings verkyg">FärgPlocknings verkyg</h2>
```
but that translator probably didn't recognized that they also had to change the KS macro call to 
```html
<div>{{ EmbedLiveSample('FärgPlocknings verkyg, '100%', '900') }}</div>
```
which is counter-intuitive to start with.

**Comment by peterbe** [comment]
Let's try this. If the element has a `name` tag, use and respect that. If it already has an ID, use and respect that. If it doesn't have either `name` or `id`, then and only then, take the text and transform with underscores instead of spaces.

**Comment by peterbe** [comment]
FYI, [here](https://github.com/mdn/content/commit/9427de4a1db1415b73ccc537eb067b850db7cd33) is where the `name` was removed and from that day onwards we didn't notice that the `_samples_/index.html` ceased to be created in production.

**Comment by escattone** [comment]
This is something @peterbe and I discussed at length in a video meeting. The fragility of the `EmbedLiveSample` approach should at least be reduced by moving forward with the proposed fix:

> Let's try this. If the element has a name tag, use and respect that. If it already has an ID, use and respect that. If it doesn't have either name or id, then and only then, take the text and transform with underscores instead of spaces.
