### ISSUE TITLE
Support EmbedLiveSample without headings

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2491]
See this comment
https://github.com/mdn/yari/pull/2490#discussion_r556186903

**Comment by escattone** [comment]
@mattiapontonio Please don't open issues without clearly defining their substance. The title `Support EmbedLiveSample without headings` doesn't make any sense to me. I'm closing this, but if you can clearly define what you're proposing here, you can re-open it.

**Comment by mattiapontonio** [comment]
@escattone

**Comment by mattiapontonio** [comment]
Why these classes with columns `:`?

**Comment by Ryuno-Ki** [comment]
Those closes help Prism.js add the syntax highlighting.

**Comment by mattiapontonio** [comment]
We should mention
https://github.com/PrismJS/prism
for Who wants to understand features of this.
