### ISSUE TITLE
Reconsider/Rethink tables

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2502]
There are a number of issues related to various styling and display issues with regards to tables on MDN Web Docs:

- https://github.com/mdn/yari/issues/1797
- https://github.com/mdn/yari/issues/2101
- https://github.com/mdn/yari/issues/2100
- https://github.com/mdn/yari/issues/2102
- https://github.com/mdn/yari/issues/2103
- https://github.com/mdn/yari/issues/1941
- https://github.com/mdn/yari/issues/1757
- https://github.com/mdn/yari/issues/1761
- https://github.com/mdn/yari/issues/1762
- https://github.com/mdn/yari/issues/1960
- https://github.com/mdn/yari/issues/1818
- https://github.com/mdn/yari/issues/2085

There may well be others. This means tables are problematic and I agree.
Time to step back and rethink how we can improve the UX and general UI of tables on MDN Web Docs across platforms and devices.

**Comment by mattiapontonio** [comment]
There is one thing that I care about is over flow on mobile.

**Comment by Ryuno-Ki** [comment]
As far as I can tell, those issues deal mainly with BCD.
Do we have other tables we need to take into account?

The main problem seem to be the handling of overlong content within those tables.

**Comment by schalkneethling** [comment]
@Ryuno-Ki this is about rethinking tables in general on MDN Web Docs from a design and UX perspective.

BCD is definitely something to address separately. It is a pretty complex UX problem.

**Comment by mattiapontonio** [comment]
> It is a pretty complex UX problem

It's also a data structures but not-algorithm problem

**Comment by Ryuno-Ki** [comment]
> @Ryuno-Ki this is about rethinking tables in general on MDN Web Docs from a design and UX perspective.

I recall that @LeaVerou blogged about it a few years ago:
https://lea.verou.me/2018/05/responsive-tables-revisited/

**Comment by mattiapontonio** [comment]
> > @Ryuno-Ki this is about rethinking tables in general on MDN Web Docs from a design and UX perspective.
> 
> I recall that @LeaVerou blogged about it a few years ago:
> https://lea.verou.me/2018/05/responsive-tables-revisited/

Headings on tables can be placed both horizontally and vertically but that's a mix. I don't like it, too much repetition of the headers and it's a hack at the end, it's not a solution it's a workaround.

**Comment by Ryuno-Ki** [comment]
Another use case: https://github.com/mdn/content/issues/1834
