### ISSUE TITLE
Transfer "Create Account" page to Yari

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2504]
The "Create your MDN Web Docs Account" page needs to be implemented in Yari:

The current endpoint is http://localhost.org:8000/en-US/users/account/signup

![Screenshot 2021-01-13 at 15 23 37](https://user-images.githubusercontent.com/10350960/104458800-817f2600-55b4-11eb-9bd8-6040cf61a90f.png)

For this iteration we do not need the include the following option:
"Get exclusive content, offers and invitations to your inbox"

**Comment by mattiapontonio** [comment]
A random quesiton.
There is an endpoint without UI to do and test this POST?

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Transfer "Create Account" page to Yari](https://trello.com/c/yZLVLIk5/23-transfer-create-account-page-to-yari)

**Comment by schalkneethling** [comment]
Here are the comps for the first iteration of this page:

## Desktop

![Screenshot 2021-02-17 at 12 33 45](https://user-images.githubusercontent.com/10350960/108192326-cb5fac80-711c-11eb-89a2-646293193ac6.png)

## Tablet

![Screenshot 2021-02-17 at 12 33 57](https://user-images.githubusercontent.com/10350960/108192355-d31f5100-711c-11eb-8a53-7d3d37d1ec99.png)

## Mobile

![Screenshot 2021-02-17 at 12 34 06](https://user-images.githubusercontent.com/10350960/108192377-dadef580-711c-11eb-85bb-1e7b4a14c68f.png)

**Comment by peterbe** [comment]
I quite like the idea of displaying your full name and mugshot as part of the sign-up process. It might be very doable at little effort and I think it would make sense to display that to you when you're signing up because it feels like the computer "has at least understood you" so far.

**Comment by schalkneethling** [comment]
> I quite like the idea of displaying your full name and mugshot as part of the sign-up process.

I agree, a good suggestion @peterbe. I will update the layout comps.

**Comment by peterbe** [comment]
Actually, don't rely on the email. In fact, the email will never be present. But the full name and/or avatar (image url) might be. Also, neither might be.

**Comment by escattone** [comment]
@schalkneethling @peterbe's I like the suggestion to add the avatar and full name (but **not** the user's email) to the mock-ups as well. I would say we could even get by with just the avatar if that's easier or works better.

**Comment by schalkneethling** [comment]
Updated design to take into account the avatar

![Screenshot 2021-03-04 at 17 40 19](https://user-images.githubusercontent.com/10350960/109988946-b421e100-7d10-11eb-8367-6cefde58f317.png)

**Comment by escattone** [comment]
@schalkneethling Looks great!

**Comment by schalkneethling** [comment]
This is taken care of by #2449
