### ISSUE TITLE
Transfer Account Settings page

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2505]
Implement the new account settings page in Yari

http://localhost.org:8000/en-US/account/

![Screen Shot 2021-01-13 at 15 24 06-fullpage](https://user-images.githubusercontent.com/10350960/104459141-05391280-55b5-11eb-9fba-503a4d5afbea.png)

In this iteration we do not need:

- Subscriptions
- The "Get exclusive content...." checkbox

**Comment by mattiapontonio** [comment]
Same question here, what is the endpoints to use in PostMan?

**Comment by schalkneethling** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Transfer Account Settings page](https://trello.com/c/kIMkpelt/24-transfer-account-settings-page)
