### ISSUE TITLE
Issue with styles and icon in "Looking to become a front-end web developer?" block

### ISSUE THREAD

**Issue by Torhuo** [mdn/yari#2517]
Page with the problem: https://developer.mozilla.org/en-US/docs/Learn and all other pages with this block.

Looks like there are missing some styles and icon, because it was better before migration to Yari.

**Comment by tannerdolby** [comment]
I don't see what you mean. Could you include screenshots for the specific areas of the page that have "problems"?

**Comment by Torhuo** [comment]
Found same issue, my bad. #2255
