### ISSUE TITLE
Yari flaw fixes causing xref macro arguments to be incorrect?

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#2520]
In https://github.com/mdn/content/pull/1236, @nschonni did a bunch of automated flaw fixes, mainly on the links in the affected articles.

I noted that in a couple of cases, xref macro arguments had been changed so they still worked, but the resulting link text was incorrect. For example `{{domxref("RandomSource")}}` got changed to `{{domxref("Crypto/getRandomValues")}}`, whereas it should be `{{domxref("Crypto.getRandomValues")}}`.

This occurred in `files/en-us/glossary/rng/index.html`.

Can you have a look into this? Thanks!

**Comment by peterbe** [comment]
The macros work with both. I'm not sure why we use a `.` in xref macros. But consistency is a powerful force. 
I can look into making the flaw fixing re-format it.

**Comment by rachelandrew** [comment]
I just came to log this as I ran into the same problem with https://github.com/mdn/content/pull/1185 and after spending some time wondering if I was having some kind of senior moment realised I hadn't changed them, fixable flaws had.

**Comment by peterbe** [comment]
Actually, @chrisdavidmills can you please take a look and report why we use . instead of /
After all, what if the slug actually depends on a dot. Like 'pwa/manifest.json'. 

If we can move to using / as the delimiter, we might save ourselves some coding work.

**Comment by mattiapontonio** [comment]
Crypto.getRandomValues()

- `Crypto` is the name of the interface?
- `.` is an accessor
- `getRandomValues` is the name of a function

Why do not We support the full URL as a argument?

**Comment by chrisdavidmills** [comment]
@peterbe sure thing. When you use the one-argument version of an xref macro, the slug and the link text are derived from the argument value. The link text is exactly the same as the argument value, whereas the slug fragment is modified if necessary, to the form it needs to be in.

So if you put `{{domxref("Document.body")}}`, the link text will be "Document.body", but the slug fragment is updated to "Document/body" so the URL is well-formed.

But if you put `{{domxref("Document/body")}}` the link text will be"Document/body", which is not what we want (the slug fragment is still correct).

There is also a two-argument version, which allows you to specify the link text and slug fragment separately, e.g. `{{domxref("Document/body", "Document.body")}}`. It would be a pain to write this explicitly each time you want to write such a call.

**Comment by peterbe** [comment]
@chrisdavidmills I didn't appreciate that the text becomes `/` too. I don't know what I was thinking, but I thought it would become `<a href=".../Document/body"><code>body</code></a>` but your point is that it becomes `<a href=".../Document/body"><code>Document/body</code></a>` which isn't how APIs are described or used.

**Comment by chrisdavidmills** [comment]
> @chrisdavidmills I didn't appreciate that the text becomes `/` too. I don't know what I was thinking, but I thought it would become `<a href=".../Document/body"><code>body</code></a>` but your point is that it becomes `<a href=".../Document/body"><code>Document/body</code></a>` which isn't how APIs are described or used.

Yup, got it in one.
