### ISSUE TITLE
lowercase for percent-encoded URLs breaks

### ISSUE THREAD

**Issue by fiji-flo** [mdn/yari#2522]
https://developer.mozilla.org/ru/docs/Learn/HTML/Введение_в_HTML becomes https://developer.mozilla.org/ru/docs/Learn/HTML/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_HTML

Which is found for example on https://developer.mozilla.org/ru/docs/Learn/HTML

The page exists an is accessible via:
https://developer.mozilla.org/ru/docs/Learn/HTML/введение_в_html becomes https://developer.mozilla.org/ru/docs/Learn/HTML/%D0%B2%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_html

We'll have to `decodeURI` then `.toLowerCase()` then `encodeURI` in the right place, which potentially breaks other things.

**Comment by escattone** [comment]
Good catch @fiji-flo! I tested it and this explains https://github.com/mdn/yari/issues/2173.

**Comment by escattone** [comment]
I updated the `dev`, `stage`, and `prod` CloudFront instances to use the new Lambda@Edge function from https://github.com/mdn/yari/pull/2545. This is now resolved! Thanks @fiji-flo!
