### ISSUE TITLE
Change the "Join the MDN Community" link in the global nav

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#2525]
The Feedback > Join the MDN Commmunity global nav link currently points to https://developer.mozilla.org/en-US/docs/MDN/Community, which was deleted from the source so should soon start to 404.

I'd like to propose we change the link text to "Contribute to MDN" and have it linking to https://developer.mozilla.org/en-US/docs/MDN/Contribute.

Maybe also put it down the bottom of the list of links.

I'm more than happy to fix this myself, BTW; I'm just not sure where the source for this lives.

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/search?q=Join+the+MDN+Community&type=

**Comment by peterbe** [comment]
I've made the two necessary PRs. 
This is one of those examples where it still hurts to have to have Kuma doing some front-end stuff (home page, site-search, sign-up, etc)
