### ISSUE TITLE
these licences in footer link is not styled

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2529]
![Screenshot_20210114-154921.png](https://user-images.githubusercontent.com/44380480/104606560-2b77b480-5680-11eb-9ee4-61c3dcc6bf1e.png)
![Screenshot_20210114-154913.png](https://user-images.githubusercontent.com/44380480/104606567-2dda0e80-5680-11eb-9926-8b3f8ac812d8.png)

**Comment by schalkneethling** [comment]
This is as intended. Thank you for reporting @mattiapontonio
