### ISSUE TITLE
Link content in footer

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2530]
_Content_ word in footer could be linked to the repository.

> © 2005-2021 [Mozilla]() and individual contributors. [Content]() is available under these [licenses]().

**Comment by tannerdolby** [comment]
It kinda "pollutes" the footer with permalinks but not a bad idea. To potentially provide a link to `mdn/content`

**Comment by mattiapontonio** [comment]
Yes, what i want is to be clear on what Is content, what is Yari, what is interactive example and so on. So links works well ti define what is what in what doman.

**Comment by peterbe** [comment]
Nope. The link is correct and fine.
