### ISSUE TITLE
404 => homepage [i18n and L10n]

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2532]
[Go back to homepage]() is not in `fr` both in `innerText` than `href`.

## Example
https://developer.mozilla.org/fr/both

## Actually
Go back to the home page  
https://developer.mozilla.org/

## Expected
Retournez à la page d'accueil
https://developer.mozilla.org/fr

**Comment by schalkneethling** [comment]
Do you mean that it links to `en-US` or that the text is not localized?

**Comment by mattiapontonio** [comment]
Both. Potential 2 issues.

**Comment by mattiapontonio** [comment]
Serve browsers language

# Side issue
- My browser is in _Français_ 
- but visting the root URL https://developer.mozilla.org 
- redirects me to https://developer.mozilla.org/en-US/
- instead of https://developer.mozilla.org/fr

![Screenshot_20210119-010749.png](https://user-images.githubusercontent.com/44380480/104972873-4e44f880-59f3-11eb-994f-5c81f5cc81ce.png)
