### ISSUE TITLE
Link to github.com/mdn/content/edit 📝

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2537]
Currently pages links to the source on GitHub.
We can add a link to the **edit** page.

Example URL:
https://github.com/mdn/content/edit/main/files/en-us/web/css/border/index.html

Example list with 2 items:

- ⛲ [Source]()
- ✏️ [Edit]()

**Comment by tannerdolby** [comment]
Upon clicking the "Example URL" I'm met with the following message on GitHub:

> You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork tannerdolby/content, so you can send a pull request.

Is this what you intended?

**Comment by mattiapontonio** [comment]
If You propose changhes It creates a fork.
Lets try.

**Comment by schalkneethling** [comment]
It's an interesting idea but seeing that we do not control the entire flow, I doubt we can make this work. If we knew your Github username on the frontend in Yari it would be plausible, but we currently do not.

With that said, if you do not have a fork of the content repo, it will return a 404 even if we knew your Github username. For example https://github.com/mdnwebdocs-tester/content/edit/main/files/en-us/web/css/border/index.html

**Comment by mattiapontonio** [comment]
> It's an interesting idea but seeing that we do not control the entire flow, I doubt we can make this work. If we knew your Github username on the frontend in Yari it would be plausible, but we currently do not.
> 
> With that said, if you do not have a fork of the content repo, it will return a 404 even if we knew your Github username. For example https://github.com/mdnwebdocs-tester/content/edit/main/files/en-us/web/css/border/index.html

What I have to say? It is a wrong idea. The first idea is better. Even for those using Linux it should work as it is web.

**Comment by peterbe** [comment]
Let's not do this. Not everyone wants to edit it via the GitHub UI. We can't have too many links there. It's limited real estate.

**Comment by mattiapontonio** [comment]
I particularly like this feature and it's both because it's my idea and because it's a good idea.
