### ISSUE TITLE
Remove the watcher functionality

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2546]
Sadly, the watcher is more fancy than it's useful. Having it means we need to do all the `chokidar` stuff which can cause problems on Linux with too many file descriptors. And it requires a WebSocket and it requires the Document Spy. 
If you don't use the watcher (`REACT_APP_NO_WATCHER=true`) you actually get a very good experience. Since the `useSWR` hook uses the PageVisilbility Web API, it actually refreshes the page the second you switch from your IDE back to your browser. 

One of the original design goals was when the in-browser editor was better. It used to *overlay* next to the content and it was neat that as soon as you typed, it would immediately update the page because the WebSocket pushed the diff so fast. But with the `useSWR` hook, you get a `mutate` callable which is identical in end-functionality actually.
And the in-browser editor morphed to "Quick-edit" which is now not an overlay anymore. So you can't see your edits until you close the editor anyway. 

Being able to remove all the functionality means a leaner Yari.

**Comment by Ryuno-Ki** [comment]
@peterbe Would the README need an update here as well?

**Comment by peterbe** [comment]
> @peterbe Would the README need an update here as well?

What did I miss?

**Comment by Ryuno-Ki** [comment]
In https://github.com/mdn/yari#error-enospc-system-limit-for-number-of-file-watchers-reached
it currently says

> Error: ENOSPC: System limit for number of file watchers reached

> There are two options to resolve this.
>
> 1. Disable the watcher via REACT_APP_NO_WATCHER
> ```
> echo REACT_APP_NO_WATCHER=true >> .env
> ```
> 2. Increase max_user_watches:
>     See https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

I'd assume, these information are obsolete by now?

**Comment by peterbe** [comment]
> In https://github.com/mdn/yari#error-enospc-system-limit-for-number-of-file-watchers-reached
> it currently says
> 
> > Error: ENOSPC: System limit for number of file watchers reached
> 
> > There are two options to resolve this.
> > 
> > 1. Disable the watcher via REACT_APP_NO_WATCHER
> > 
> > ```
> > echo REACT_APP_NO_WATCHER=true >> .env
> > ```
> > 
> > 
> > 
> > 1. Increase max_user_watches:
> >    See https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers
> 
> I'd assume, these information are obsolete by now?

They're not. `create-react-app` has this thing were it's monitoring all the source code files for potential saves so it knows to automatically reload. Because there are so many source code files, and bound to just increase, you can run into this warning still.
