### ISSUE TITLE
Unespected scroll snap

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2564]
See the GIF.
The page does a little snap vertically.

![ezgif-3-8ba592d32d26.gif](https://user-images.githubusercontent.com/44380480/104788050-7cc39900-5791-11eb-8946-86972b30290c.gif)

**Comment by schalkneethling** [comment]
That is interesting. We definitely do not use scroll snap or do anything different for mobile with regards to scrolling. It is unlikely that there is anything we can do about this. I can confirm that this happens in Chrome on Android though.
