### ISSUE TITLE
there's a distance between the scroll bar and the table

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2568]
Now the tables are responsive and that's real good 👍👌
Thanks all!

This issue is because now there is a probably padding between the table and the scroll bar that "pushes" the scroll bar near the title.

## Expected
No padding

![Screenshot_20210116-215751.png](https://user-images.githubusercontent.com/44380480/104822858-eef5b580-5845-11eb-90e4-93d47678f8db.png)
![Screenshot_20210116-215735.png](https://user-images.githubusercontent.com/44380480/104822861-f1580f80-5845-11eb-8845-9d2fc856e003.png)

The page (a real good Page 👍🙏)
https://developer.mozilla.org/en-US/docs/Web/Events

**Comment by Harshita-Kanal** [comment]
Can I take this up?

**Comment by mattiapontonio** [comment]
@Harshita-Kanal ok for me but I can't assign.

**Comment by peterbe** [comment]
> Can I take this up?

We don't assign outside the core dev team. Have a go and make a PR if the issue isn't already assigned. Your PR doesn't have to be perfect as long as it tries and works. You'll get help in the PR.
