### ISSUE TITLE
Weight and color of the text in code area

### ISSUE THREAD

**Issue by patelkaransingh** [mdn/yari#2571]
Text in code area, Please consider:
- increase font weight a bit so that its visible properly
- use darker color

Thank You.

**Comment by schalkneethling** [comment]
@patelkaransingh We have made some updates to the code example styling and color. Could you have a look and let me know if you are happy with the changes or whether there are still areas we can improve? Thank you.

**Comment by schalkneethling** [comment]
Being addressed as part of the redesign and tracked elsewhere. Thank you for reporting @patelkaransingh
