### ISSUE TITLE
Document.cookie examples don't work

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#2579]
@1202software commented on [Fri Dec 04 2020](https://github.com/mdn/sprints/issues/3942)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [ ] New documentation
- [x] Correction or update

# Details
The examples on this page no longer work: https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie

It seems you cannot access `document.cookie` anymore from JavaScript, it always returns an empty string. I'm on Google Chrome/Linux.

Perhaps the examples should be removed and/or notice added.

---

@vkWeb commented on [Sat Dec 05 2020](https://github.com/mdn/sprints/issues/3942#issuecomment-739334909)

@1202software @chrisdavidmills umm, I can try looking into what's going on. 

---

@vkWeb commented on [Sat Dec 05 2020](https://github.com/mdn/sprints/issues/3942#issuecomment-739359933)

After looking a bit on this I got to know that Google Chrome doesn't allow cookie reads / writes from file:// protocol. Other browsers allow that. Chrome allows cookie reads/writes from http protocol only: https://bugs.chromium.org/p/chromium/issues/detail?id=535. 

---

@hamishwillee commented on [Mon Dec 07 2020](https://github.com/mdn/sprints/issues/3942#issuecomment-739584565)

No, this is an issue due to expected security behaviour, as reported in https://support.google.com/chrome/thread/33543699?hl=en (i.e. related to SameSite and iframes). You can see these working if you load the source pages directly in chrome. https://mdn.mozillademos.org/en-US/docs/Web/API/Document/cookie$samples/Example_2_Get_a_sample_cookie_named_test2?revision=1591237

There are a couple of potential problems outlined there. The example is in an embedded iframe with a different domain.
```
<iframe class="live-sample-frame sample-code-frame" frameborder="0" height="36" id="frame_Example_1_Simple_usage" src="https://mdn.mozillademos.org/en-US/docs/Web/API/Document/cookie$samples/Example_1_Simple_usage?revision=1652690" width="200"></iframe>
```
From a SameSite cookie perspective on chrome this means that cookies will not be sent by default (it will be set to Lax).

To fix this, first I'd try modifying the examples to add the SameSite as shown - e.g. 
```
document.cookie = "name=oeschger; SameSite=None; Secure;";
```

That will probably work, but it is possible that the iframe itself will put further restrictions on calling this API (doesn't appear to on quick scan of docs).

@chrisdavidmills Where are the examples on https://mdn.mozillademos.org actually stored/specified? making the change above to add SameSite=None; Secure; would do "no harm" IMO, though there will need to be a note added in docs.

PS. If that doesn't work then we'll have to look closer at the iframe itself. It may be that this has to be a link to example rather than embed. I'd kind of prefer that - only suggesting the samesite change because it gives us an opportunity to make some comments about how important SameSite is now.

---

@chrisdavidmills commented on [Mon Dec 07 2020](https://github.com/mdn/sprints/issues/3942#issuecomment-739769238)

@hamishwillee that's a good question — I'm not really sure how to access those demos.

@escattone , do you how the answer to this?

I'd be in favor of moving those demos across to a repo somewhere under https://github.com/mdn/ at some point.

---

@escattone commented on [Tue Dec 08 2020](https://github.com/mdn/sprints/issues/3942#issuecomment-740404909)

@chrisdavidmills I think @hamishwillee is right on here (thank you), but I probably won't be able to look into this in more detail until next week due to everything else going on for the launch of Yari a week from today.

---

@hamishwillee commented on [Fri Jan 15 2021](https://github.com/mdn/sprints/issues/3942#issuecomment-760599680)

@escattone Just a reminder, that this one is still a problem.

**Comment by neillindberg** [comment]
I see this is closed, but not resolved. I think less experienced devs should be notified that the examples won't work. Or, just add a button to initially set the cookie before trying to read it. Anyway, w/o looking at the dev console there's no feedback to the user so I would say this is not resolved or handled in any way.

**Comment by schalkneethling** [comment]
@chrisdavidmills @neillindberg I just ran the little example in the page to show cookies and it output the following:

```
> name=oeschger; favorite_food=tripe; test1=Hello; test2=World; reader=1
```

I guess that means the example works fine now?

**Comment by caugner** [comment]
> @chrisdavidmills @neillindberg I just ran the little example in the page to show cookies and it output the following:
> 
> ```
> > name=oeschger; favorite_food=tripe; test1=Hello; test2=World; reader=1
> ```
> 
> I guess that means the example works fine now?

The examples work since https://github.com/mdn/content/pull/5031 applied the workaround of setting `SameSite=None`. 🎉
