### ISSUE TITLE
Autocompression of images not working on Windows

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#2582]
When I try to compress images on Windows I get an error. The test case is this branch https://github.com/hamishwillee/content/tree/backup_devtools_badcomp and the file: files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png

Note, this same branch compresses fine on Ubuntu 20.04. 

Error as shown below. 

```
D:\github\mozilla\mdn_content\content>yarn filecheck "files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png" --save-compression
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png --save-compression
files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png was unexpected at this time.

D:\github\mozilla\mdn_content\content>  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\node.exe"  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\..\env-cmd\bin\env-cmd.js" --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png --save-compression
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

More information on what was tried in https://github.com/mdn/content/pull/1338#issuecomment-761906015

**Comment by peterbe** [comment]
What happens if you do:
```
D:\github\mozilla\mdn_content\content>yarn filecheck "files\en-us\tools\page_inspector\how_to\examine_and_edit_css\show_pseudo_classes_hover.png" --save-compression
```
i.e. instead of `/` use `\`. For Windows. 

I have no idea that the "was unexpected at this time" string comes from even. It's not a string found in Yari or in any of the `node_modules` files as far as I can see. 
One thing that could be a clue is that the `filecheck` tool creates a temporary directory and dumps the result in there and then it compares the results with the source. And if you do `--save-compression` it doesn't really compare, it just copies the compressed file from said temporary directory and overwrites the source file. 

The package we use for creating a temporary directory is https://www.npmjs.com/package/tempy
In turn, it uses https://www.npmjs.com/package/temp-dir which is just a thin wrapper for `os.tmpdir()` in Node. 

I googled `was unexpected at this time` and skimmed the search results and see stuff related to DOS and Batch scripts. So that might actually explain why it's not originating from our source code, in a sense.

**Comment by peterbe** [comment]
Another thing to check, to rule things out, is if you can manually type `yarn filecheck "THE ABSOLUTE FULL WINDOWS PATH TO THE IMAGE" --save-compression` 
That would tell is it's something busted with out it combines the relative path to the file with the value of the `CONTENT_ROOT` setting.

**Comment by hamishwillee** [comment]
@peterbe Thank you for the advice. I tried using back and forward slashes, and also the full path the the file - same error in each case. I have put the debug below FYI.

---
```
D:\github\mozilla\mdn_content\content>git checkout backup_devtools_badcomp
Switched to branch 'backup_devtools_badcomp'

D:\github\mozilla\mdn_content\content>yarn filecheck "files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png" --save-compression
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png --save-compression
files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png was unexpected at this time.

D:\github\mozilla\mdn_content\content>  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\node.exe"  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\..\env-cmd\bin\env-cmd.js" --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png --save-compression
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\github\mozilla\mdn_content\content>yarn filecheck "D:/github/mozilla/mdn_content/content/files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png" --save-compression
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) D:/github/mozilla/mdn_content/content/files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png --save-compression
D:/github/mozilla/mdn_content/content/files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png was unexpected at this time.

D:\github\mozilla\mdn_content\content>  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\node.exe"  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\..\env-cmd\bin\env-cmd.js" --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) D:/github/mozilla/mdn_content/content/files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png --save-compression
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\github\mozilla\mdn_content\content>yarn filecheck "/github/mozilla/mdn_content/content/files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png" --save-compression
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) /github/mozilla/mdn_content/content/files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png --save-compression
/github/mozilla/mdn_content/content/files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png was unexpected at this time.

D:\github\mozilla\mdn_content\content>  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\node.exe"  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\..\env-cmd\bin\env-cmd.js" --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) /github/mozilla/mdn_content/content/files/en-us/tools/page_inspector/how_to/examine_and_edit_css/show_pseudo_classes_hover.png --save-compression
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\github\mozilla\mdn_content\content>yarn filecheck "D:\github\mozilla\mdn_content\content\files\en-us\tools\page_inspector\how_to\examine_and_edit_css\show_pseudo_classes_hover.png" --save-compression
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) D:\github\mozilla\mdn_content\content\files\en-us\tools\page_inspector\how_to\examine_and_edit_css\show_pseudo_classes_hover.png --save-compression
D:\github\mozilla\mdn_content\content\files\en-us\tools\page_inspector\how_to\examine_and_edit_css\show_pseudo_classes_hover.png was unexpected at this time.

D:\github\mozilla\mdn_content\content>  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\node.exe"  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\..\env-cmd\bin\env-cmd.js" --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) D:\github\mozilla\mdn_content\content\files\en-us\tools\page_inspector\how_to\examine_and_edit_css\show_pseudo_classes_hover.png --save-compression
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

D:\github\mozilla\mdn_content\content>yarn filecheck "files\en-us\tools\page_inspector\how_to\examine_and_edit_css\show_pseudo_classes_hover.png" --save-compression
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) files\en-us\tools\page_inspector\how_to\examine_and_edit_css\show_pseudo_classes_hover.png --save-compression
files\en-us\tools\page_inspector\how_to\examine_and_edit_css\show_pseudo_classes_hover.png was unexpected at this time.

D:\github\mozilla\mdn_content\content>  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\node.exe"  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\..\env-cmd\bin\env-cmd.js" --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) files\en-us\tools\page_inspector\how_to\examine_and_edit_css\show_pseudo_classes_hover.png --save-compression
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nschonni** [comment]
I ran into this now too, but just found that if you drop the `--cwd=$(pwd)` it seems happy again. Probably safe to remove since the default then falls back to `process.cwd()` in the `cli.js`

**Comment by peterbe** [comment]
So the `--cwd=$(pwd)` could be causing problems on Windows?? What OS are you on @nschonni ?
I'll take a look to see if the `--cwd=$(pwd)` is potentially obsolete now.

**Comment by nschonni** [comment]
Mainly Windows and using GitBash, but also macOS and Ubuntu through WSL when needed

**Comment by hamishwillee** [comment]
@nschonni How do you go about dropping `--cwd=$(pwd)` if you run this locally? It is a bit of a pain to have to switch to ubuntu to fix up my PRs.

Further, if this is going to fail submission, shouldn't a flaw or other notification be provided to tell me? e.g. `yarn test` or whatever?

**Comment by nschonni** [comment]
You can edit the package.config locally in the content repo
https://github.com/mdn/content/blob/6e21cfdfbac220b6d601ff92a274aaab3957a652/package.json#L12
to 
```json
`"filecheck": "env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js",
```

**Comment by hamishwillee** [comment]
Awesome, though still something going on
```
D:\github\mozilla\mdn_content\content>yarn filecheck files/en-us/tools/web_console/ui_tour/web_console.png
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js files/en-us/tools/web_console/ui_tour/web_console.png
[Error: ENOENT: no such file or directory, stat 'D:\github\mozilla\mdn_content\files\en-us\tools\web_console\ui_tour\web_console.png'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'D:\\github\\mozilla\\mdn_content\\files\\en-us\\tools\\web_console\\ui_tour\\web_console.png'
}
```
The file exists.

**Comment by nschonni** [comment]
Maybe try running it through Git Bash

**Comment by hamishwillee** [comment]
No dice (but thanks for the advice):
```bash
hamis@DESKTOP-G5JQBQG MINGW64 /d/github/mozilla/mdn_content/content (ff86_relnote_devtool)
$ yarn filecheck files/en-us/learn/server-side/express_nodejs/skeleton_website/expressgeneratorskeletonwebsite.png
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js files/en-us/learn/server-side/express_nodejs/skeleton_website/expressgeneratorskeletonwebsite.png
[Error: ENOENT: no such file or directory, stat 'D:\github\mozilla\mdn_content\files\en-us\learn\server-side\express_nodejs\skeleton_website\expressgeneratorskeletonwebsite.png'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'D:\\github\\mozilla\\mdn_content\\files\\en-us\\learn\\server-side\\express_nodejs\\skeleton_website\\expressgeneratorskeletonwebsite.png'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by mattiapontonio** [comment]
Sometimes i see:
`mdn_content\content\files`
Sometimes
`mdn_content\files`

Is that related?

**Comment by peterbe** [comment]
Weirdness. So the file `D:\github\mozilla\mdn_content\files\en-us\learn\server-side\express_nodejs\skeleton_website\expressgeneratorskeletonwebsite.png` genuinely exists? Can you copy-n-paste the full path of the image, from the error message, and run `ls` or something to assert that the full path is accurate?

**Comment by Ryuno-Ki** [comment]
I believe, the Windows pendant to `ls` is called `dir`.

**Comment by hamishwillee** [comment]
Yes, it genuinely exists :-) 

- Run failing command (git bash)
```
hamis@DESKTOP-G5JQBQG MINGW64 /d/github/mozilla/mdn_content/content (expr_oldlink)
$ yarn filecheck files/en-us/learn/server-side/express_nodejs/skeleton_website/expressgeneratorskeletonwebsite.png
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) files/en-us/le
arn/server-side/express_nodejs/skeleton_website/expressgeneratorskeletonwebsite.png
files/en-us/learn/server-side/express_nodejs/skeleton_website/expressgeneratorskeletonwebsite.png was unexpected at this
 time.

D:\github\mozilla\mdn_content\content>  "D:\github\mozilla\mdn_content\content\node_modules\.bin\\node.exe"  "D:\github\
mozilla\mdn_content\content\node_modules\.bin\\..\env-cmd\bin\env-cmd.js" --silent cross-env CONTENT_ROOT=files node nod
e_modules/@mdn/yari/filecheck/cli.js --cwd=$(pwd) files/en-us/learn/server-side/express_nodejs/skeleton_website/expressg
eneratorskeletonwebsite.png
error Command failed with exit code 255.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
- Navigate to location of file
```
hamis@DESKTOP-G5JQBQG MINGW64 /d/github/mozilla/mdn_content/content (expr_oldlink)
$ cd files/en-us/learn/server-side/express_nodejs/skeleton_website/

hamis@DESKTOP-G5JQBQG MINGW64 /d/github/mozilla/mdn_content/content/files/en-us/learn/server-side/express_nodejs/skeleton_website (expr_oldlink)
```
Run dir - note that file is present!
```
$ dir
expressgeneratorskeletonwebsite.png  index.html
```

**Comment by nschonni** [comment]
yeah, I actually hit this today again and none of my (maybe) workarounds were able to run, so I gave up and used my old Mac for it. Tried on WSL, but it crashed in a different manner

**Comment by hamishwillee** [comment]
Don't give up! If this is going to be something that blocks merge it needs to be reported as a flaw and fixable on all platforms.

**Comment by peterbe** [comment]
> fixable on all platforms.

Indeed! Until we figure out a way to support Windows, perhaps hold off a little on fixing fixable flaws on Windows. We'll figure it out. Just slower than I had hoped. Nobody on the dev team even has access to a Windows computer. Right @fiji-flo ?

**Comment by nschonni** [comment]
The `flaws` part actually works fine on Windows, only issue is when manually pulling down images and then trying to compress using `filecheck`

**Comment by hamishwillee** [comment]
@nschonni Really? When I add a new image to a page it never shows a flaw on the uncompressed file. It only shows flaws if the page has "remote" images.

**Comment by nschonni** [comment]
I've been pulling remote images from the commandline with flaws without any issues, but when I hit it again recently, it was from pulling down remote images from Wayback Machine. That's what I meant by manually adding

**Comment by nschonni** [comment]
No solution, but I figured out it's this line that's crashing `const stat = await promisify(fs.stat)(filePath);`

**Comment by nschonni** [comment]
OK, looks like it was the `cwd` thing after all, but I'm not sure enough of the solution to PR it.
1. Remove the " --cwd=$(pwd)` from the `filecheck/cli.js` call
2. Monkey patch the `const cwd = options.cwd || process.cwd();` line in `filecheck/cli.js` to `const cwd = process.cwd();`

**Comment by nschonni** [comment]
Looks like just changing the `--cwd=.` works without the monkey patch

**Comment by hamishwillee** [comment]
@nschonni Nice one. I can confirm that on windows command prompt the `--cwd=.` works for me:
```
D:\github\mozilla\mdn_content\content>yarn filecheck files/en-us/learn/server-side/express_nodejs/skeleton_website/expressgeneratorskeletonwebsite.png
yarn run v1.22.5
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/filecheck/cli.js --cwd=. files/en-us/learn/server-side/express_nodejs/skeleton_website/expressgeneratorskeletonwebsite.png
Done in 4.58s.
```
To be very clear on the "flaw" issue, if I modify that file so it is bigger then view the file locally, no flaw is displayed on the website. I see this as a problem because I look at this and think "great" but the PR will fail due to the filecheck.
![image](https://user-images.githubusercontent.com/5368500/106813978-d13da280-66c5-11eb-9a47-f7ee3997e34d.png)

**Comment by peterbe** [comment]
Sorry that I've lost track of this issue a bit. Is the solution to simply replace `--cwd=$(pwd)` for `--cwd=.` and then it suddenly works on Windows too?

**Comment by hamishwillee** [comment]
@peterbe Yes, if you replace as you indicate it works on Windows. BUT I have not tried to confirm that also works on Linux (after changing)

**Comment by mattiapontonio** [comment]
> Node.js is an open-source, **cross-platform**, back-end JavaScript runtime environment that runs on the Chrome V8 engine and executes JavaScript code outside a web browser.

https://en.m.wikipedia.org/wiki/Node.js

Is that still true? Where Is the problem in Node? In NPM?

**Comment by peterbe** [comment]
> > Node.js is an open-source, **cross-platform**, back-end JavaScript runtime environment that runs on the Chrome V8 engine and executes JavaScript code outside a web browser.
> 
> https://en.m.wikipedia.org/wiki/Node.js
> 
> Is that still true? Where Is the problem in [Node](https://nodejs.org/en/)? In [NPM](https://docs.npmjs.com/)?

Does that comment have ANYTHING to do with the problem that this issue is discussing. Are you sure this comment is helping us in ANY way or is it just noise and distraction? Did you think this through before posting?

**Comment by mattiapontonio** [comment]
I was just thinking: do we have to deal with maintaining cross platform commands then weird programs or processes or do we already have everything we need with this stack? My comment doesn't help but making 3 attempts on different systems doesn't help either, what helps is to choose supported technologies and use them literally. I don't know I go to feeling like when the friend comes to the bar and says "guys, don't fight ... it's just an operating system".

**Comment by Ryuno-Ki** [comment]
@peterbe I understand your frustration. Could you keep polite here? (Or take this dicussion off-thread by using e-mail).
It feels toxic to readers of these issues.

**Comment by peterbe** [comment]
> @peterbe I understand your frustration. Could you keep polite here? (Or take this dicussion off-thread by using e-mail).
> It feels toxic to readers of these issues.

Sure. Thanks for reminding me. If you can, when you see comments that are distracting and off-tangent, help out to remind to keep the discussion focussed.

**Comment by Ryuno-Ki** [comment]
Will do (and did in the past).

Sometimes, I feel like there are some parts, that feel so common for engineers, though, that I take the time to explain them.
If you feel it would be distracting, I could go ahead and mark them as off-topic. That would make GitHub collapse them, but still keep them in an issue / PR.

Bear in mind, that we are attracting newcomers here. I want to cater for them if I can.

**Comment by mattiapontonio** [comment]
Please forgive me for this non-engineering comment. 
Delete It.

> We don't deal with outsiders very well
They say **newcomers** have a certain smell
You have trust **issues**, not to mention
They say they can smell your intentions

https://www.google.com/amp/s/genius.com/amp/Twenty-one-pilots-heathens-lyrics

**Comment by hamishwillee** [comment]
Thanks for sorting this one out. Much appreciated.
