### ISSUE TITLE
redirection from previous URL format

### ISSUE THREAD

**Issue by kajman-cz** [mdn/yari#2585]
Hello, please add redirections from previously used URL schema.

Eq. from https://developer.mozilla.org/en/DOM/window.alert
to https://developer.mozilla.org/en-US/docs/Web/API/Window/alert

Perhaps this intermediate step could be used.
https://developer.mozilla.org/en-US/docs/DOM/window.alert

Thanks.

**Comment by peterbe** [comment]
Would you mind attempting to add a redirect to the [`_redirects.txt`](https://github.com/mdn/content/blob/main/files/en-us/_redirects.txt) file? I.e. make a pull request on the mdn/content repo.

**Comment by kajman-cz** [comment]
Sorry for the wrong repo.
