### ISSUE TITLE
Serve browsers language

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2586]
Serve browsers language

# Side issue
- My browser is in _Français_ 
- I'm in Italy
- but visting the root URL https://developer.mozilla.org 
- redirects me to https://developer.mozilla.org/en-US/
- instead of https://developer.mozilla.org/fr

![Screenshot_20210119-010749.png](https://user-images.githubusercontent.com/44380480/104972873-4e44f880-59f3-11eb-994f-5c81f5cc81ce.png)

_Originally posted by @mattiapontonio in https://github.com/mdn/yari/issues/2532#issuecomment-762715102_

**Comment by peterbe** [comment]
We use `Accept-language` header which the browser sends. But it's second to cookies, if present.

**Comment by mattiapontonio** [comment]
@peterbe 
Would it be problematic not to use this cookie so I can test when I want ...? I don't know what consequences it can have at the moment.

**Comment by mattiapontonio** [comment]
It works 👍
After
https://support.mozilla.org/fr/kb/supprimer-historique-navigation-et-autres-donnees-personnelles-firefox-android

And visiting
https://developer.mozilla.org
