### ISSUE TITLE
BCD note overflow

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2588]
I don't want this note here in the table but i open this issue because actually It (the note when there is a flag) overflows.

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize

![Screenshot_20210119-142227.png](https://user-images.githubusercontent.com/44380480/105040157-cba75200-5a61-11eb-8d26-a97714d23ef5.png)

**Comment by Ryuno-Ki** [comment]
Only appears for viewports smaller than 420px.
It's caused by the `<code>` within `.bc-history dd`.

I can see different approaches to it:
**`word-break: break-word`**:
![word-break](https://user-images.githubusercontent.com/3097194/105614396-794f9380-5dc9-11eb-8b80-3fe76499947e.png)

**`overflow-x: auto`**:
![overflow-x](https://user-images.githubusercontent.com/3097194/105614415-a603ab00-5dc9-11eb-8ef5-9e8f78af67db.png)

**`hyphens: auto`**:
![hyphens](https://user-images.githubusercontent.com/3097194/105614428-bfa4f280-5dc9-11eb-8f94-cd140f99f630.png)

All of them introduce some ambiguity regarding the `<code>` part.

**Comment by mattiapontonio** [comment]
Keep in mind that the Sass CI don't want too much indentation.
![Screenshot_20210124-011316.png](https://user-images.githubusercontent.com/44380480/105617810-909a7b00-5de1-11eb-97e6-91b86f15287f.png)

**Comment by Ryuno-Ki** [comment]
The markup for this piece of code is

```html
<dl class="bc-history bc-history-mobile">
  <div class="bc-notes-wrapper">
    <dt class="bc-supports-yes bc-supports">
      <abbr class="bc-level-yes only-icon" title="Full support">
        <span>Full support</span>
      </abbr>
      83
      <div class="bc-icons">
        <abbr class="only-icon" title="disabled">
          <span>disabled</span><i class="ic-disabled"></i>
        </abbr>
      </div>
    </dt>
    <dd>
      <abbr class="only-icon" title="disabled">
        <span>disabled</span><i class="ic-disabled"></i>
      </abbr>
       From version 83: this feature is behind the<code>dom.forms.autocapitalize</code> preferences (needs to be set to <code>true</code>). To change preferences in Firefox Android, visit about:config.
    </dd>
  </div>
</dl>
```

**Comment by mattiapontonio** [comment]
Missing space here 
```
behind the​<​code​
```

**Comment by Ryuno-Ki** [comment]
> Missing space here

Mea culpa. Must have missed it when manually formatting the HTML.

As far as I can tell, the markup is generated here:

https://github.com/mdn/yari/blob/077f70925048b8319beee78c0e601ce4be5d17ed/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx#L259-L327

What other structure would you recommend?
@peterbe and @Gregoor worked on that part of the codebase.

**Comment by mattiapontonio** [comment]
Side issue
How about tracking build so We can share the HTML not in prod but as a text on GitHub?

**Comment by Ryuno-Ki** [comment]
Sounds like #2453 to me (as in: builds associated with PRs having a dedicated URL).

BCD for autocapitalize can be found at

https://github.com/mdn/browser-compat-data/blob/26dd8f364aafbf822ca5f4bb46bce71c16df0998/html/global_attributes.json#L53-L115

```json
      "autocapitalize": {
        "__compat": {
          "mdn_url": "https://developer.mozilla.org/docs/Web/HTML/Global_attributes/autocapitalize",
          "spec_url": "https://html.spec.whatwg.org/multipage/interaction.html#attr-autocapitalize",
          "support": {
            "chrome": {
              "version_added": "43"
            },
            "chrome_android": {
              "version_added": "43"
            },
            "edge": {
              "version_added": "79"
            },
            "firefox": {
              "version_added": "83",
              "flags": [
                {
                  "type": "preference",
                  "name": "dom.forms.autocapitalize",
                  "value_to_set": "true"
                }
              ]
            },
            "firefox_android": {
              "version_added": "83",
              "flags": [
                {
                  "type": "preference",
                  "name": "dom.forms.autocapitalize",
                  "value_to_set": "true"
                }
              ]
            },
            "ie": {
              "version_added": null
            },
            "opera": {
              "version_added": null
            },
            "opera_android": {
              "version_added": null
            },
            "safari": {
              "version_added": false
            },
            "safari_ios": {
              "version_added": "5"
            },
            "samsunginternet_android": {
              "version_added": null
            },
            "webview_android": {
              "version_added": "43"
            }
          },
          "status": {
            "experimental": false,
            "standard_track": true,
            "deprecated": false
          }
        }
      }
```

**Comment by mattiapontonio** [comment]
- https://github.com/mdn/yari/blob/master/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
- https://github.com/mdn/browser-compat-data/blob/master/html/global_attributes.json

Where are the paragraphs?

**Comment by Ryuno-Ki** [comment]
> On top on a _served not-prod site_ having HTML on GitHub should be usefull for _reading without visiting_.

That's not how it works with MDN / Yari. The wiki moved away from Kumascript to React. So you have JSX (extended JavaScript) markup with TypeScript support (which turns it into TSX, i.e. extended TypeScript). It's a syntax defined by Facebook which allows you to write HTML-like markup in JavaScript but include so-called components within it.
It's not plain HTML anymore.

Then, at build time (if you render server-side) or run-time (otherwise) that markup is turned into HTML.

I linked the above TSX file which renders a row in the BCD table as well as the source powering it.

**Comment by mattiapontonio** [comment]
AFAIC
- React builds a static build that is served  as static HTML ever X hours.
- I'm talking about a folder or a repository that contains that static build
