### ISSUE TITLE
Deployer search-index should respect redirects

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2590]
If you use the `--update` option when you run the `search-index` (bulk uploading to Elasticsearch), we need to respect redirects too. 

If we don't re-create the Elasticsearch index every 24h, we might end up with 2 documents that contain almost the same content but spread across its old URL and its new URL.

**Comment by peterbe** [comment]
The priority of this diminishes almost entirely if we can avoid doing incremental indexing. If we're OK with a little "downtime" in the search, we don't need to worry about getting rid of old stuff in there.

**Comment by stof** [comment]
an option to avoid downtime while doing a full recreation of the index would be to use an [index alias](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-add-alias.html) for the *reading* usage of elasticsearch in the search endpoint.
The script would create a new index (probably with the date of the build in the index name), index all new content in it. Then it would recreate the alias to point to the new index. And then it can delete the old index which is not used anymore.

This way, there is no downtime. While the new index is populated, the search endpoint are still working, as they are still seeing the old data (as the alias still points to the old index at that point).

**Comment by peterbe** [comment]
@stof Your comment is great. I'd love to expand on it. But you posted it as a reply comment on something unrelated. Sorry. I can create a new issue based on your comment but then it would appear under my name. Would you prefer to start a fresh new comment or do you prefer that I create a new issue myself?

**Comment by stof** [comment]
I'll create it

**Comment by schalkneethling** [comment]
@escattone Seeing that https://github.com/mdn/yari/pull/3409 was merged, is this still something we need to keep open?

**Comment by escattone** [comment]
Right on @schalkneethling, thanks!
