### ISSUE TITLE
<a> inside a <h3> or <h2> should be a flaw

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2593]
In the olden days (Kuma wiki), we used to allow `<a>` tags in the `<h2>` and `<h3>` tags because we would render it something like this:

```html
<!-- DOM updated in render-tyime -->
<a href="id" class="permalink">🔗</a>

<!-- part of the Wiki content -->
<h2 id="id">Bla bla <a href="/other">ble</a></h2>
```

But in Yari, we're turning all `<h2>` and `<h3>` and extract their `id` attribute to make it a permlink. I.e.
```html
<h2 id="id">Bla bla</h2>
```
...becomes...
```html
<h2 id="id"><a href="#id" title="Permalink to 'Bla bla'">Bla bla</a></h2>
```

Because of that, if the original text of the `<h2>` and `<h3>` contains HTML that is `<a>` you end up with:

```html
<h2 id="id"><a href="#id" title="Permalink to 'Bla bla'">Bla bla <a href="/other">ble</a></a></h2>
```
So, the `<a>` tag part of the heading should not be allowed. It should be a flaw.

**Comment by peterbe** [comment]
Example page: http://localhost:5000/en-us/docs/web/css/@supports/#testing_for_the_support_of_a_selector
This is interesting because the source actually doesn't contain a `<a>` tag. 
See https://github.com/mdn/content/blob/274d5690c6167c42cef1da741910f18f7e579f37/files/en-us/web/css/%40supports/index.html#L133

So it'll be hard to make this flaw a fixable flaw.

**Comment by mattiapontonio** [comment]
```html
<a href="id" class="permalink">🔗</a>
<h2 id="id">Bla bla</h2>
```
I prefer this.

**Comment by Ryuno-Ki** [comment]
> I prefer this.

I was inclined to agree with you here … but then I was wondering, how would a screenreader pronounce this?
I'm afraid of a „read more” effect, which would not help differentiate the different links.

**Comment by mattiapontonio** [comment]
> how would a screenreader pronounce this?

Actually I don't know.
I will try to find a way do to even this test on mobile.

**Comment by peterbe** [comment]
I don't know why GitHub didn't link it, but the PR that'll close this is: https://github.com/mdn/yari/pull/2878

**Comment by mattiapontonio** [comment]
> I don't know why GitHub didn't link it, but the PR that'll close this is: https://github.com/mdn/yari/pull/2878

Is because case? _Fixes_ vs _fixes_.
https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue
