### ISSUE TITLE
Some files should be prettier ignored

### ISSUE THREAD

**Issue by kenrick95** [mdn/yari#260]
Running `prettier-check` command causes some failures:

(note: Windows path separator is shown below)

```
yarn run v1.17.3
$ prettier --check **/*.{js,json,scss,html}
Checking formatting...
ssr\dist\main.js
stumptown\content\fr\html\reference\elements\abbr\examples\définir-une-abréviation\example.html
Code style issues found in the above file(s). Forgot to run Prettier?
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

1. Should add `ssr/dist/` to .prettierignore
2. What should we do with that example.html one? as it should be the responsibility of [another repository](https://github.com/mdn/stumptown-content)

**Comment by peterbe** [comment]
1. [change 'cli' to 'ssr'](https://github.com/mdn/stumptown-renderer/blob/97043b11d60b846b41cd8361f535a451c8d23e57/.prettierignore#L10)
2. [why is it checking anything inside the `stumptown` directory???](https://github.com/mdn/stumptown-renderer/blob/97043b11d60b846b41cd8361f535a451c8d23e57/.prettierignore#L8)

**Comment by peterbe** [comment]
Confusingly, 
```
▶ yarn prettier-check
yarn run v1.19.2
$ prettier --check **/*.{js,json,scss,html}
Checking formatting...
All matched files use Prettier code style!
✨  Done in 1.07s.
```

For me. Despite the fact the we have a known bug that [`ssr` isn't listed](https://github.com/mdn/stumptown-renderer/blob/97043b11d60b846b41cd8361f535a451c8d23e57/.prettierignore#L10). 
Why does it not complain when I use `yarn run prettier-check`. As expected, if I run it myself, manually, I get this:

```
▶ prettier --check "**/*.{js,json,scss,html}"
Checking formatting...
ssr/dist/main.js
Code style issues found in the above file(s). Forgot to run Prettier?
```
...which is expected. 

So what's so different about how `yarn run prettier-check` does it?
Does `yarn` somehow magically know about expanding `"**/*.{js,json,scss,html}"` with the `.gitignore` in mind?

**Comment by peterbe** [comment]
https://github.com/mdn/stumptown-renderer/pull/279 will take care of that `ssr/dist` thing but I still can't reproduce the problem with the `stumptown` files. 
I know windows uses back-slashes but the `.prettierignore` file should be glob patterns and they're always implemented with forward slashes. Even on Windows. 

Any idea @Gregoor ?

**Comment by peterbe** [comment]
I think our `prettier` scripts and CI are working fine now.
