### ISSUE TITLE
[Feature] Show the flaws in the public page

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2608]
- Actually flaws are I don't know where personally.
- Could be good to see the flaws of a page into the page itself.
- The section should be not more important then content

**Comment by peterbe** [comment]
Don't know what "public page" is but we already have a Flaws Dashboard.

**Comment by mattiapontonio** [comment]
@peterbe 
Do You have a URL that i can visit from mobile?
This is because i see a lot of issues and PR about this dashboard but i never see It.
