### ISSUE TITLE
Small alignment issue for star icon in browser compatibility tables

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#2630]
In between 1199px and 1288px viewport width, the star icon that is stored in the pseudo element `::before` is slightly off center in the browser compatibility table. I'm viewing it on this page [dragenter event](https://developer.mozilla.org/en-US/docs/Web/API/Document/dragenter_event) but it should be the same for each BC table.

<img width="177" alt="Screen Shot 2021-01-20 at 9 07 27 PM" src="https://user-images.githubusercontent.com/48612525/105282671-b9add800-5b63-11eb-9135-6b042ee657a0.png">   <img width="292" alt="Screen Shot 2021-01-20 at 9 15 17 PM" src="https://user-images.githubusercontent.com/48612525/105283105-a18a8880-5b64-11eb-98ff-0ec55b1b4402.png">

This is due to the `margin-left: 6px` property on `.bc-icons i:before` which plays nice for every other responsive layout but between 1199px-1288px it has this small off center appearance.

Updating that property to `margin-left: 2px` provides a much more centered alignment of the star icon. 

<img width="240" alt="Screen Shot 2021-01-20 at 9 19 48 PM" src="https://user-images.githubusercontent.com/48612525/105283510-78b6c300-5b65-11eb-86f3-2cd83ce39c12.png">  <img width="297" alt="Screen Shot 2021-01-20 at 9 52 09 PM" src="https://user-images.githubusercontent.com/48612525/105285736-dbaa5900-5b69-11eb-9fcc-2f596a16a1e6.png">

The above seems to be much more centered. This makes the area that the media query would cover be from 1199px-1223px. Then the `margin-left: 6px` would be applied again as the media condition wouldn't be used outside that range. 

I remember seeing how media queries worked on the `.scss` end and the "mobile-first" approach, so I'm not sure if you think its "worth it" to add such a small media query to better center the star icon but let me know your thoughts.

```css
@media (min-width: 1199px) and (max-width: 1223px) {
  .bc-icons i:before {
     background-size: 18px;
     ...
     margin-left: 2px;
  }
}
```
Lastly, the `.bc-history` affects two other places where the star icon is styled by `.bc-icons i:before`, in the see implementation notes, and in the footnotes dropdown which does reduce the space in between the text and icon a bit since the container is larger and doesn't wrap to the next line like it does in the BC table. This looks squished with 2px so the footnotes box from the dropdown should retain the 6px margin left to not look like below.

_Screenshot with `margin-left: 2px` added_
<img width="346" alt="Screen Shot 2021-01-20 at 9 48 12 PM" src="https://user-images.githubusercontent.com/48612525/105285432-3e4f2500-5b69-11eb-951e-e9749a18b3ed.png">

<img width="250" alt="Screen Shot 2021-01-20 at 9 45 33 PM" src="https://user-images.githubusercontent.com/48612525/105285377-224b8380-5b69-11eb-989d-491a908b168f.png">

This is a lot of tinkering just to provide a little better centering for a small range of viewport widths so I understand if its not feasible, just wanted to bring it up.

**Comment by peterbe** [comment]
If you can correct that, I think it would make a big improvements. I've noticed little imperfections like that too and it looks kinda "sloppy" which leaves a bad taste. It shouldn't matter, but it does. We're just fancy monkeys.

**Comment by peterbe** [comment]
If you think you can fix it, we can assign this issue to you. You've proven yourself in the past.

**Comment by tannerdolby** [comment]
@peterbe Yeah I think I can fix it.

**Comment by tannerdolby** [comment]
I did some tinkering, it seems the media query route to change the `margin-left: 6px` to `margin-left: 2px` won't suffice because pages like [:nth-child() - CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) have "many" star icons in the bc tables which make defining a viewport min/max width for the media condition nearly impossible without creating a bunch of media queries. Changing `margin-left` to 2px without any media query makes things too squished.

It seems one fix for maintaining the space between the text/value and the star-icon while fixing the vertical alignment when the icon wraps to the next line is by adding a bit of `margin-right` to `.bc-icons i:before` and taking the `margin-left` down 1px to 5px.

<img width="83" alt="Screen Shot 2021-01-25 at 10 10 31 PM" src="https://user-images.githubusercontent.com/48612525/105807372-b303d400-5f5a-11eb-9085-9948875bd538.png"> <img width="75" alt="Screen Shot 2021-01-25 at 10 10 12 PM" src="https://user-images.githubusercontent.com/48612525/105807384-bbf4a580-5f5a-11eb-911e-5ed9ad490435.png"> <img width="62" alt="Screen Shot 2021-01-25 at 10 15 51 PM" src="https://user-images.githubusercontent.com/48612525/105807474-ed6d7100-5f5a-11eb-8381-3afed1b0964a.png"> <img width="163" alt="Screen Shot 2021-01-25 at 10 05 50 PM" src="https://user-images.githubusercontent.com/48612525/105807421-cf077580-5f5a-11eb-9654-c53eb99265f0.png">

We can discuss things more after review but this seems to make the vertical alignment much more centered without compromising the space between text and icon when they are side-by-side.

**Comment by peterbe** [comment]
Oh no. The screenshots are busted. But I've asked Schalk to review your PR.

**Comment by tannerdolby** [comment]
@peterbe uh oh. As in the result looks bad, or the screenshots aren't displaying correctly and aren't viewable?

**Comment by peterbe** [comment]
Now it's all working. Earlier today, all I saw was the `alt` text for the images. Couldn't tell if it was GitHub bug, network problem or something gone wrong in the comment itself. 
<img width="921" alt="Screen Shot 2021-01-26 at 12 26 26 PM" src="https://user-images.githubusercontent.com/26739/105880746-b71f0880-5fd1-11eb-91b1-41b3d4e61600.png">

**Comment by tannerdolby** [comment]
Got it. Well I'm glad its working now. Thanks for the heads up.

**Comment by Ryuno-Ki** [comment]
> Couldn't tell if it was GitHub bug, network problem or something gone wrong in the comment itself.

Your network. I could always see the images.

**Comment by tannerdolby** [comment]
@Ryuno-Ki Sounds good. Thank you for the second pair of eyes.
