### ISSUE TITLE
Inconsistent logo

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2644]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy
_MDN Web Docs_

![Screenshot_20210122-005607.png](https://user-images.githubusercontent.com/44380480/105427114-b7737880-5c4c-11eb-989d-c0f504dd1916.png)

https://developer.mozilla.org/en-US/
_MDN web docs_

![Screenshot_20210122-005549.png](https://user-images.githubusercontent.com/44380480/105427171-dc67eb80-5c4c-11eb-8969-6d9a8f6dec52.png)

**Comment by peterbe** [comment]
Will get closed as soon as we move the home page.
