### ISSUE TITLE
Issue with "Looking to become a front-end web developer?" block

### ISSUE THREAD

**Issue by Torhuo** [mdn/yari#2645]
Page with the problem - https://developer.mozilla.org/en-US/docs/Web/HTML

Looks like the problem with this block only on this page. On other pages it looks fine.

![Untitled](https://user-images.githubusercontent.com/77203405/105447578-8499a680-5c85-11eb-9528-226fc94328be.png)

**Comment by chrisdavidmills** [comment]
This was already fixed in the source (see https://github.com/mdn/content/blob/main/files/en-us/web/html/index.html#L34), and should disappear form the production page soon.
