### ISSUE TITLE
The mark on the URL has different font sizes in different devices

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2650]
## Venue

In this page
https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#deeper_dive

## Reality

The _marks_ on the URL are bigger in desktop then mobile compared to the paragraph above and below.

![Screenshot_20210122-101313.png](https://user-images.githubusercontent.com/44380480/105471371-f29c9880-5c9a-11eb-91b5-8af7ca7a88c5.png)
![Screenshot_20210122-101333.png](https://user-images.githubusercontent.com/44380480/105471386-f7f9e300-5c9a-11eb-8dda-7375c4a15e06.png)

## Expectation

Consistency for font size between the URL/marks and the article font size.

---

https://github.com/mdn/content/issues/1322

**Comment by Ryuno-Ki** [comment]
Is this a `mdn-minimalist` issue?

**Comment by mattiapontonio** [comment]
> Is this a `mdn-minimalist` issue?

Nope. 
1. Probably content actually.
2. Then minimalist.
