### ISSUE TITLE
Icon used in `h3` headings needs improved contrast

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2654]
I need to think about how best to approach this and also determine how common this use is currently.

<img width="902" alt="Screen Shot 2021-01-22 at 9 36 33 AM" src="https://user-images.githubusercontent.com/26739/105504088-5a4fe500-5c95-11eb-8769-fffc8b1020e3.png">

_Originally posted by @peterbe in https://github.com/mdn/yari/issues/2153#issuecomment-765444939_

**Comment by mattiapontonio** [comment]
Personally...

```HTML
<div>
<h2>text</h2>
<svg />
</div>
```

**Comment by Ryuno-Ki** [comment]
For the record:
Currently

```html
<h3>
  <a>
    <strong>
      <code>text</code>
    </strong>
    <svg />
  </a>
</h3>
```

**Comment by schalkneethling** [comment]
> For the record:
> Currently

That needs some spring cleaning for sure 🧹

**Comment by sohamsshah** [comment]
Hey! I would like to work on this issue. 
So shall we use some other color in SVG instead of blue for better accessibility?
Also, I suspect that even though we are providing `vertical-align:middle` due to some reason it still doesn't vertically align perfectly. Shall we consider using a flex to `align-items: center`?

Thanks!

**Comment by schalkneethling** [comment]
> Hey! I would like to work on this issue.
> So shall we use some other color in SVG instead of blue for better accessibility?
> Also, I suspect that even though we are providing `vertical-align:middle` due to some reason it still doesn't vertically align perfectly. Shall we consider using a flex to `align-items: center`?
> 
> Thanks!

Hey! Thank you for your interest. I am actually proposing a change to our document layout that would automatically resolve this problem. Let me first see where that goes and then we can revisit this one if it is still a problem.

**Comment by sohamsshah** [comment]
Sure! No problem :)

**Comment by Ryuno-Ki** [comment]
Friendly ping @schalkneethling

**Comment by schalkneethling** [comment]
> Friendly ping @schalkneethling

Still discussing. Will make a call this week.

**Comment by schalkneethling** [comment]
Yup, we are going to change the style. Will update this issue once the change lands.

**Comment by schalkneethling** [comment]
A fix for this landed as part of https://github.com/mdn/yari/pull/3795 - Will have a look as soon as the latest build has been deployed.

**Comment by schalkneethling** [comment]
The immediate issue has been resolved as can been seen below so, I am going to go ahead and close this one.

![Screenshot 2021-05-14 at 19 33 12](https://user-images.githubusercontent.com/10350960/118307624-3b4abc80-b4eb-11eb-8ec1-091d7bd255a2.png)
