### ISSUE TITLE
I have to clear the cache if Yari and not content deploys something?

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2655]
## Steps to reproduce

1. Sometimes I see an issue closed by a merged PR. 🔴
2. I'm going to visit the description when I provided a production URL to see what changed 👁️
3. Nothing changed 🤨
4. I comment in the closed issue to Say "nothing changed" 🙋‍♂️
5. A maintener says: "Yes It changed" 🤠
6. I clear the cache and navigation data 🧹
7. Yes the page is changed 👍

Can We _reduce_ those points in some way?

**Comment by peterbe** [comment]
I don't think this is related to "clearing the cache". I think you're referring to the time it takes for something from a merge-to-master until it shows up on developer.mozilla.org, right?
Yeah, that time is pretty lengthy. It's 48hours if you're really unlucky. 

The two things that are holding us back is that the prod build only runs every 24h. And the CDN caches things for 24h. 
What could solve this is to [build more frequently](https://github.com/mdn/yari/issues/2642). We could also look into triggering some cache invalidations in the CDN based on what's recently changed. But caching invalidations in the CDN is no light matter.

**Comment by mattiapontonio** [comment]
Nope.
I don't know the deploy process but sometimes I had to clear the cache after another person says that is ok.
So my question Is: the browser can know if there is something modified and then do not use cache?

I'm thinking on
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304

Without any relevant experience.

**Comment by peterbe** [comment]
Well, what could happen is that the browser over aggressively caches. We set the same 24h cache-control for the CDN to do its internal storage as well as to the browsers. You can see if if you keep the Network panel in dev tools open (caching not disabled) and click around and end up clicking the same link. No HTTP network. So yes, it's possible that between visits, the CDN **might** have a new copy but you will miss if unless you hit the browsers Refresh button. 

I don't think we want to change this. Yes, it might be a nuisance for some writers whose browser cache holds on. But they are not the norm. They can press their Refresh button. Most readers (99.9% of traffic) will benefit from a more aggressive caching.

**Comment by mattiapontonio** [comment]
There must be a solution that lets you deposit for 24 but that after a new build forces the recovery on all existing browsers. If not, I don't know.

**Comment by Ryuno-Ki** [comment]
> merge-to-~master~main

:heart:

**Comment by mattiapontonio** [comment]
@Ryuno-Ki Thoughts? It seemed to me that you know about http ...

**Comment by Ryuno-Ki** [comment]
As @peterbe hinted, two things are hard in tech:

Naming things and invalidate tech.

What I could imagine, though, is that the respective build SHA is written down somewhere (perhaps a `<meta />` tag or something.
This way, you could compare the hash codes to check, whether you're looking at the „correct” version.

Invalidating caches could be tricky. I mean, you can tell your browser to ignore cache by force-refreshing (Ctrl-Shift-R). But you should not have a say to force the CDN to invalidate the cache as a visitor on MDN in my opinion (otherwise, this could be easily leveraged into a DoS).

**Comment by mattiapontonio** [comment]
- I don't want to force to fetch to all every time because cache is ok
- I'm looking to a header-only solution to comunicate to the default browser behaviour that he have to fetch. Something related to the Age of the resource or something but i don't know so Maybe We Simply can't. I'm not looking to some custom solution _not-in-mdn_ doc

**Comment by Ryuno-Ki** [comment]
The two common approaches I'm aware of are ETag and Last-Modified.
Both appear in the response headers you shared.
