### ISSUE TITLE
Download external images with the extension that it really is

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2659]
In https://github.com/mdn/content/pull/1587 @nschonni and I discovered that some images might be called `foo.jpg` but on closer inspection, it's actually a `image/png` so the name is wrong. 
Who knows how many of these there are? The `filecheck` command will eventually catch you if you run the fixable flaws on external images that get downloaded to disk. Inconvenient when you have to manually correct it.

**Comment by Ryuno-Ki** [comment]
How do you check them?
As far as I know there are „magic bytes” at the beginning of the image binary which can help deciding on the image.

I know, we decided to add images to the repo going forward, but an alternative might be to use an image CDN, which then would convert images on-the-fly.
Could be used in the future, if the repo gets too large.

**Comment by mattiapontonio** [comment]
- https://nodejs.org/dist/latest-v6.x/docs/api/fs.html#fs_fs_readfile_file_options_callback
- https://stackoverflow.com/q/26091836/3579536

- File metadata are _safe_?
- Curious that they are not modelled in node.

**Comment by mattiapontonio** [comment]
> „magic bytes”

This is a reminder to style blockquote?

**Comment by Ryuno-Ki** [comment]
I was hinting on https://en.wikipedia.org/wiki/List_of_file_signatures or https://en.wikipedia.org/wiki/Magic_number_(programming)#Magic_numbers_in_files

On *NIX systems, you have the `file` CLI for this.
Perhaps @peterbe found another way to do it (e.g. with Node tools).
Thus my question.

**Comment by peterbe** [comment]
> How do you check them?
> As far as I know there are „magic bytes” at the beginning of the image binary which can help deciding on the image.
> 
> I know, we decided to add images to the repo going forward, but an alternative might be to use an image CDN, which then would convert images on-the-fly.
> Could be used in the future, if the repo gets too large.

We use https://www.npmjs.com/package/file-type
