### ISSUE TITLE
Move locale strings in HTML files [i18n|L10n]

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2666]
kumascript/macros/DeprecatedGeneric.ejs

- Files are HTML but not strictly documents, are HTML strings

**Comment by peterbe** [comment]
This isn't a description of a problem. 
The topic of localizing macros is much too complicated and spread into more important issues.

**Comment by mattiapontonio** [comment]
> This isn't a description of a problem. 
> The topic of localizing macros is much too complicated and spread into more important issues. 

I don't want to open a question on this but I dream in object where I don't have to write the locales but only the translations.
