### ISSUE TITLE
[a11y] Mozilla's logo is not accesible

### ISSUE THREAD

**Issue by mattiapontonio** [mdn/yari#2671]
![Screenshot_20210124-170815.png](https://user-images.githubusercontent.com/44380480/105636115-fb41ca00-5e66-11eb-8569-2c82b29717e2.png)

With TalkBack a part of the logo is not focused.
https://developer.mozilla.org/en-US/docs/MDN/Structures/Live_samples

**Comment by peterbe** [comment]
@schalkneethling Should this be resurrected?

**Comment by Ryuno-Ki** [comment]
I'd extend this question to most of the issues Mattia closed today (in Yari and Content).
I wonder, what was the cause …
There were some really gems in it.

**Comment by schalkneethling** [comment]
Tested in Safari with VoiceOver. All is good. The fact that the focus ring does not cover the entire SVG is not a problem. It is clear that the focus is on the logo.

**Comment by Ryuno-Ki** [comment]
That was my gut feeling also. I can double-check with TalkBack if it would help.

**Comment by schalkneethling** [comment]
> That was my gut feeling also. I can double-check with TalkBack if it would help.

That would be great, thank youl.

**Comment by mattiapontonio** [comment]
This Is closed.
It's a question of design passed off as accessibility

**Comment by Ryuno-Ki** [comment]
> That would be great, thank youl.

It gets detected as link on TalkBack. The alt attribute is read out as link text.

**Comment by mattiapontonio** [comment]
We put the Mozilla logo in the footer as an accessible link and leave only dinosaur and MDN.
