### ISSUE TITLE
Issue with broken links

### ISSUE THREAD

**Issue by DevRadhy** [mdn/yari#2688]
In `/kumascript/macros/B2GOnlyHeader2.ejs` for links related to Firefox OS that redirect to `/en-US/docs/Mozilla/Firefox_OS` and `/en-US/docs/Mozilla/Firefox_OS/Security/Application_security#App_Types`, but these links are not do exist, referring to `MDN/content`, only `/en-US/docs/Mozilla/Firefox`, and something related to Firefox OS is only found in `/en-US/docs/glossary/Firefox_OS`

**Comment by Ryuno-Ki** [comment]
For what it's worth: Many Firefox OS (:crying_cat_face:) related articles were moved into the Archive part of MDN, which is not part of this repo.

**Comment by peterbe** [comment]
The B2GOnlyHeader2 macro is not used anymore. But thanks for the careful noticing!
