### ISSUE TITLE
Dropdown content box in bc tables not filling entire table width

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#2692]
While I was working on some alignment with the star icons in bc tables, I noticed the dropdown content box doesn't occupy the entire width of the table which seemed a bit odd. This might not be an issue, but I wanted to bring it up just in case. 

It's reproduced for other pages but in the bc table on [:nth-child() - CSS](https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child) is where the screenshot from below comes from.

<img width="938" alt="Screen Shot 2021-01-25 at 10 25 42 PM" src="https://user-images.githubusercontent.com/48612525/105808365-72a55580-5f5c-11eb-830a-62a1c0c31894.png">

From what I can see, this is intended for the text to have `max-width: 75ch`

<img width="238" alt="Screen Shot 2021-01-25 at 10 28 09 PM" src="https://user-images.githubusercontent.com/48612525/105808500-abddc580-5f5c-11eb-998d-13f810c7570f.png">

What are your thoughts on keeping `max-width` for the text but have the background color still occupy 100% width of the table cell like the "Matches element with no parent" box does shown in the picture.

**Comment by peterbe** [comment]
@schalkneethling Can you triage this one?

**Comment by tannerdolby** [comment]
@schalkneethling After having a look at potential fixes for this, I noticed the underlying `max-width` styling is coming from `@import "~@mdn/minimalist/sass/mixins/utils";` within the `/browser-compatibility-table` folder. I tried tweaking other selectors to allow the content to occupy the entire `<td>` content-box but was unsuccessful since the `.article dl` style from `index.scss` (ie _utils.scss) has higher precendence.

<img width="430" alt="Screen Shot 2021-03-08 at 10 37 09 PM" src="https://user-images.githubusercontent.com/48612525/110428864-ddb77100-805e-11eb-9634-696171b115f2.png">

If we remove the `max-width` declaration or set it to be `max-width: 100%` then the content fills the row (aside from the bit of space on all sides from other parent paddings or margin.

<img width="772" alt="Screen Shot 2021-03-08 at 10 38 11 PM" src="https://user-images.githubusercontent.com/48612525/110428994-1bb49500-805f-11eb-919f-e74552ab005f.png">

I'm happy to work on a fix for this, but for now I think the underlying style is coming from `_utils.scss` which is imported from `mdn/minimalist`. Let me know your thoughts.

**Comment by schalkneethling** [comment]
@tannerdolby indeed that is unfortunate. It is because there are a number of elements that are set to a `max-width` that is actually defined by our `readable-line-length` class and mixin. Removing it from the underlying implementation might be an option but, moving it into `.article` will also not solve the problem.

Let me think about it a little more.

**Comment by schalkneethling** [comment]
@tannerdolby I checked a couple of pages and it looks to be fixed? Can you confirm? Thanks!

**Comment by tannerdolby** [comment]
@schalkneethling Yeah I will have a look at some pages and get back to you. No problem!

**Comment by tannerdolby** [comment]
@schalkneethling I've navigated about 50 pages with BCD tables and here are a few of the ones that I noticed still had the issue.

- https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenElement
- https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
- https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen
- https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenElement

I can provide the full list of pages that need fixes if you need me too. For the most part, many of the pages have been fixed. It seems there are only a handful that still have the issue.

This page has the issue fixed. For the pages that did have the fix applied, everything looked great.

- https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event#browser_compatibility

**Comment by schalkneethling** [comment]
> @schalkneethling I've navigated about 50 pages with BCD tables and I noticed quite a few still had the issue.
> 
> * https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenElement
> * https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API
> * https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullScreen
> * https://developer.mozilla.org/en-US/docs/Web/API/Document/fullscreenElement
> * https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event#browser_compatibility
> 
> I can provide the full list of pages that need fixes if you need me too.

Thanks so much for looking into this. It is so weird that some are fine and some are not, especially seeing that I did nothing to "fix" those that are 🙃  Anyhow, I will look into what is different between these. Thanks again.

**Comment by tannerdolby** [comment]
@schalkneethling Your welcome. It is definitely weird that its fixed in some pages and still occurring in others. Let me know if I can be of any assistance in finding a permanent fix.

**Comment by tannerdolby** [comment]
I keep coming back to this and trying to think of a way to fix things, since the `max-width` value for `.main-page-content dl` is being calculated by the readable line length mixin, it seems like that `max-width: 85ch` is sticking around for good. At 1023px, some media conditions kick in and the BC tables shift layout, this is when the extra space from `max-width: 85ch` is very visible. Between 815px and 1023px is the specific range for the problem.

Not sure if this would be a solution, but if we gave the `max-width: 85ch` to `.bc-notes-wrapper` instead of the `<dl>` and have the readable line length mixin produce a value for `.bc-notes-wrapper` instead, then the `<dl>` container can easily fill the remaining space since its the background on `<dl>` that were really after (while of course keeping the text content constrained to 85ch). The styling on `<dl>` elements might be immutable so to speak from the design system so I understand if this route isn't feasible.

```css
.bc-history .bc-notes-wrapper {
    align-items: center;
    display: flex;
    max-width: 85ch;
}

/* problem still lies here, have to remove the max-widths for `.main-page-content dl` 
   if applied to .bc-notes-wrapper instead */
.main-page-content dl, .main-page-content ol, .main-page-content p, .main-page-content ul {
    /* max-width: 45rem; */
    /* max-width: 85ch; */
}
```

<img width="761" alt="Screen Shot 2021-04-21 at 11 21 28 PM" src="https://user-images.githubusercontent.com/48612525/115665591-5a916800-a2f8-11eb-81b4-022a4dbb3337.png">

**Comment by schalkneethling** [comment]
I am going to implement a fix that will resolve both this one as well as https://github.com/mdn/yari/issues/3076
Thanks so much for all the info @tannerdolby - I will ping you for review once ready seeing that you have played such a big role here and also understand the entire context.

**Comment by tannerdolby** [comment]
Ok perfect. Your welcome! @schalkneethling - Sounds good, yeah tinkering with the styling in Dev Tools for this issue and locally in my Yari has definitely provided me a strong understanding of the context. I'm looking forward to review. Chat again soon!

**Comment by schalkneethling** [comment]
@tannerdolby https://github.com/mdn/yari/pull/3650

**Comment by tannerdolby** [comment]
@schalkneethling thanks for the ping, I will start reviewing today.
