### ISSUE TITLE
BCD cell expanders don't work in mobile view

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2696]
Desktop view
<img width="1089" alt="Screen Shot 2021-01-26 at 8 05 20 AM" src="https://user-images.githubusercontent.com/26739/105848618-3e0dba00-5fad-11eb-9f79-4d91e13e814e.png">

Mobile view
<img width="494" alt="Screen Shot 2021-01-26 at 8 05 44 AM" src="https://user-images.githubusercontent.com/26739/105848648-4cf46c80-5fad-11eb-9cdf-11bb304b3bd1.png">

**Comment by Ryuno-Ki** [comment]
Fun fact:
If you expand (on desktop) and then shrink the width, it „works”.

**Comment by schalkneethling** [comment]
This has been fixed in the redesign.
