### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Bayurzx** [mdn/yari#2725]
It is more of a suggestion, I wonder if you could add a dark mode feature to the site. My eyes would be very grateful!

**Comment by mattiapontonio** [comment]
https://github.com/mdn/yari/discussions/2539

**Comment by Ryuno-Ki** [comment]
Can we discuss this in https://github.com/mdn/yari/discussions/2539 and use an issue once we agreed upon actionable next steps.

**Comment by Bayurzx** [comment]
Okay

> Can we discuss this in #2539 and use an issue once we agreed upon actionable next steps.

Yes, closing issue...
