### ISSUE TITLE
Search does not work on Windows local build

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#2732]
This occurs on Windows for all local builds, and has done for some weeks (previously was excellent).

The error is "Error initializing search index" - see below.
![image](https://user-images.githubusercontent.com/5368500/106212245-47ea2400-621e-11eb-92f8-8e4246f427c8.png)

**Comment by Ryuno-Ki** [comment]
Ping @peterbe

**Comment by peterbe** [comment]
Oh no! When you run `yarn start` (in mdn/content) it should print out something like this:
```
Populate search-index with glob: 4.421s
Populated search-index with 11,557 found files.
```

<img width="965" alt="Screen Shot 2021-01-29 at 12 21 20 PM" src="https://user-images.githubusercontent.com/26739/106306774-7ff86380-622c-11eb-9b6f-ab1fbb2a0b38.png">

Do you not get that?

Another thing that could explain it is that you're too fast in reaching the search widget before your computer has had a chance to index all the search index URLs. 
What do you get in the Web Console when this happens? 

PS. I just test it myself in the latest `main` of `mdn/content` and I can search fine here on my macOS.

**Comment by peterbe** [comment]
It must be because of https://github.com/mdn/yari/issues/2733
Lets focus over there instead.

**Comment by hamishwillee** [comment]
Just in case it is of interest, no i don't get the search stuff. I get the following. Then a bit later a bunch of "slug doesn't match folder" warnings
![image](https://user-images.githubusercontent.com/5368500/106398911-b1aa3e00-6469-11eb-9948-9674bf0b5e9a.png)

**Comment by peterbe** [comment]
Actually, as a formality, let's let make https://github.com/mdn/yari/pull/2748 close this issue when it lands.

**Comment by peterbe** [comment]
@hamishwillee After you've upgraded your `@mdn/yari` in your mdn/content, please verify and re-open this if it still isn't solved.

**Comment by hamishwillee** [comment]
@peterbe Works perfectly. Also appears to have removed all the "stub mismatch" warnings. Thanks to you and @nschonni for getting this sorted.
