### ISSUE TITLE
What do we do about all the slug warnings

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#2733]
On current main, when I start yari I get a huge number of messages like:
```
The slug of files/en-us/games/anatomy/index.html doesn't match the folder is located in.
```
Is this an error I should do something about? If so, what?
If not, should this be logged somewhere else?

**Comment by Ryuno-Ki** [comment]
Perhaps related to #973 going forward.

**Comment by mattiapontonio** [comment]
You _need to_ move the files to the correct folder.
Does the CLI help in this case?

**Comment by chrisdavidmills** [comment]
Hrm, I don't get such warnings. Possible worth pinging @peterbe on this one.
