### ISSUE TITLE
Fix language selector skip link

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2756]
Currently, we have a skip link that points to the language selector, however,

1. We only have this on the homepage and here there is in fact no language selector at the moment
2. We do not have this on other pages on MDN Web Docs even though a language selector does exist and would be useful as a skip to target

We should address both the above issues and also, ensure that the skip link, links to the `select` input as it is a natively focusable element.

See https://github.com/mdn/yari/issues/2755 for additional context.

**Comment by peterbe** [comment]
Is this still relevant?

**Comment by schalkneethling** [comment]
> Is this still relevant?

Yup still relevant.
