### ISSUE TITLE
Markdown plugin for code including line highlighting

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#2757]
When yari supports markdown parsing we will need a simple mechanism indicating code markup. 

Minimally this should support the github-compatible 3-backtick fences followed by a language indicator. For example, to indicate ruby code you would do:
<pre>```ruby
require 'redcarpet'
markdown = Redcarpet.new("Hello World!")
puts markdown.to_html
```</pre>

Other highly desirable features (not "github compatible")
1. Line marking/highlighting. The ability to highlight one or more lines. One way to do this is to use a syntax like <code>```ruby {1,4,6-7}</code> to indicate the lines and ranges that are highlighted. Note that the space after the language code is required for github compatibility.
1. Copy-to-clipboard function


This follows on from discussion at https://github.com/mdn/yari/issues/2198

**Comment by mattiapontonio** [comment]
Just to be picky, it is not convenient to open issues to extend features that do not yet exist, you should open issues referring to the master.

**Comment by hamishwillee** [comment]
Nope. I opened this as requested by dev team: https://github.com/mdn/yari/issues/2198#issuecomment-769576452

**Comment by mattiapontonio** [comment]
@hamishwillee as You prefer 🎩

**Comment by peterbe** [comment]
I'm very much interested in something like 

    ```ruby {1,4,6-7}

which would be a nice feature. It's also quite expected based on the popularity of GitHub.

**Comment by schalkneethling** [comment]
@wbamberg so, from reading https://github.com/mdn/content/issues/3512 it sounds like we decided to not add support for line numbers and line highlighting? If that is the case, we can close this one.
