### ISSUE TITLE
page not be found

### ISSUE THREAD

**Issue by cr1571an** [mdn/yari#2762]
Hello, I was reading the Javascript guide and when I got to the loops chapter, the following error message appears.

https://developer.mozilla.org/es/docs/Web/JavaScript/Guide/Bucles_e_iteracion
Sorry, the page /es/docs/Web/JavaScript/Guide/Bucles_e_iteracion could not be found.

**Comment by mirunacurtean** [comment]
Thank you for the contribution.  The issue could be reproduced on FF and Chrome browsers. Out of the all the languages, it is only on ES and [pt-PT ](https://developer.mozilla.org/pt-PT/docs/Web/JavaScript/Guia/Guia_express%C3%B5es_e_operadores
) that the 'Page not Found' does not have a redirect message to the English language document, as in the Hungarian page example. 
![image](https://user-images.githubusercontent.com/53306802/106489770-c9131680-64bd-11eb-9399-4035b8d27322.png)

The issue has been labeled accordingly and the development team will provide their own input in due course.

**Comment by Ryuno-Ki** [comment]
First of all: Apologies, but translations are frozen at the moment. https://hacks.mozilla.org/2020/12/an-update-on-mdn-web-docs-localization-strategy/ has more information.

Then, I'd like to ping @peterbe. My gut feeling would be a broken redirect on CloudFront.

**Comment by peterbe** [comment]
There's not a lot wrong here. Just unfortunate. @fiji-flo is working on making ALL translated document's slugs match the `en-US` equivalent perfectly. Once that's in place (hopefully before the end of the month), the problem will be improved in that there's a bigger chance that it'll be able to help you move to the English equivalent URL, as displayed in Hungarian in @mirunacurtean 's screenshot.

**Comment by peterbe** [comment]
We will take care of all of these. Soon enough `/es/docs/Web/JavaScript/Guide/Bucles_e_iteracion` will automatically become a redirect to `/es/docs/Web/JavaScript/Guide/Loops_and_iterations` and if that Spanish translation page doesn't exist you get what @mirunacurtean is demonstrating in her screenshot. 
More about the work to move translated slugs here: https://hacks.mozilla.org/2021/02/mdn-localization-update-february-2021/

**Comment by mattiapontonio** [comment]
I did not understand if the first _folder_ of the _path_ must be a canonical _locale_ or a canonical _language_ because they change due to the fact that they have an underscore that separates _language_ and _geographical area_.
