### ISSUE TITLE
End-to-end test development environment?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#277]
An important thing to be able to do is start a local dev server and do things like viewing a working page on `http://localhost:3000/en-US/docs/Web/HTML/Element/video`. Also, it's important, that feature where you edit the .md file and it refresh the browser to reflect the changes. 

A test like this is bound to be fragile but it might really help us keep an eye on the development environment working.

It could work something like this:

```
yarn start & 
urlwait localhost:3000
puppeteer-wrapper http://localhost:3000/en-US/docs/Web/HTML/Element/video 
sed ...(some command that edits stumptown/content/fr/html/reference/elements/video/video.md)...
puppeteer-wrapper http://localhost:3000/en-US/docs/Web/HTML/Element/video  ...
```

**Comment by peterbe** [comment]
What do you think @Gregoor ?

**Comment by Gregoor** [comment]
I think that's a great idea, given that this is the main way people (writers) interact with the app right now.

**Comment by peterbe** [comment]
We can start with the absolute minimum basic of just trying to start it and making sure it doesn't crash.

**Comment by peterbe** [comment]
We have this now. And it's awesome!
