### ISSUE TITLE
Validating the to-URL 

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2790]
In [this PR](https://github.com/mdn/content/pull/2046) a row was added to the `_redirects.txt` that looks like this:
```
/en-US/docs/Firefox     11
```
If you run the `yarn tool validate-redirects` it does not complain. 

That to-URL doesn't look like a valid URL.

**Comment by peterbe** [comment]
@fiji-flo Hi. Moved it to here instead.

**Comment by peterbe** [comment]
Other examples that didn't get caught:
```
/en-US/docs/Mozilla_event_reference/DOMContentLoading	(event)

/en-US/docs/URI/www	and

/en-US/docs/Web/Reference/Functions_and	classes_available_to_workers
```

**Comment by fiji-flo** [comment]
More work than expected. Lovely lower-case issues and stuff. Tomorrow :/

**Comment by peterbe** [comment]
I noticed that Florian S used the `move` CLI command and that's what go these lines into the `_redirects.txt` in the first place. That's unrelated and related at the same time. 

Either way, I could make a PR through the GitHub UI and manually type some junk into the `_redirects.txt` file with the textarea and I should get caught for doing it.

**Comment by mattiapontonio** [comment]
I'm not sure but it occurred to me to search if you can lock files with Git or with GitHub. 
The `_` would be _private_ right? As some do with variables in JavaScript
https://github.com/git-lfs/git-lfs/wiki/File-Locking

**Comment by schalkneethling** [comment]
@fiji-flo is this still an issue to address?

**Comment by fiji-flo** [comment]
I think that's fixed:
```
yarn content validate-redirects

Checking /Users/fiji/github/content/files/en-us/_redirects.txt
info: Unable to load redirects: Error: To-URL has to be external or start with / (11)

error: 🔥 Errors loading redirects 🔥
```
