### ISSUE TITLE
'@include highlighted-link-state()' is probably not working

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2791]
I don't know what but this line looks suspicious: https://github.com/mdn/yari/blob/3e9680e63ecc3945df26e7fbe4026c383c52859b/client/src/ui/molecules/breadcrumbs/index.scss#L22

I ran `prettier` on the [generated main CSS bundle](https://developer.mozilla.org/static/css/main.3839cacb.chunk.css) and this is what I got:

```css
.highlighted-link-state {
  @highlighted-link-state();
}
```

I suspect it's because it doesn't exist anywhere at all in minimalist. 

```
MOZILLA/MDN/mdn-minimalist  master ✔
▶ rg highlighted-link-state

```

Thus, this can be deleted.

**Comment by peterbe** [comment]
1. We need to figure out why linting didn't spot this sooner. 
2. We need to just delete it.

**Comment by peterbe** [comment]
Perhaps `stylelint` simply can't cope with things like this, but this is unexpected:

```
▶ stylelint client/src/ui/molecules/breadcrumbs/index.scss

client/src/ui/molecules/breadcrumbs/index.scss
 18:5  ✖  Expected align-items to come before display   order/properties-alphabetical-order

```

It's not unexpected about the alphabetical order there on line 18, but the fact that it didn't complain about the broken `@include highlighted-link-state();` on line 22. 

@schalkneethling Any idea??

**Comment by schalkneethling** [comment]
That is odd indeed. Let me take a look. Thank you for bringing this to my attention @peterbe

**Comment by peterbe** [comment]
That aside, let's not forget to run `stylelint` as part of the CI in Yari. It can be a separate issue.

**Comment by peterbe** [comment]
@schalkneethling Do you want me to file an issue about adding `stylelint` to the CI in yari. I think a lot of stuff should/could be moved from minimalist into Yari and when we do that it'll be nice to have this in CI.

**Comment by mattiapontonio** [comment]
> from minimalist into Yari

I expected the opposite
