### ISSUE TITLE
We're not sending 'x-frame-options' in doc responses

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2795]
See https://github.com/mdn/yari/issues/2794

We're doing it in Kuma but not on URLs served straight from the S3. 
[Example report here](https://snyk.io/test/website-scanner/?test=210203_Di1T_7f6f1d1be1e781026e549d74efe7d722&utm_medium=referral&utm_source=webpagetest&utm_campaign=website-scanner)

Once we move the home page to Yari, we'll be able to test with Mozilla Observatory.

**Comment by peterbe** [comment]
@escattone Considering that the work you did in https://github.com/mdn/yari/pull/2799 means it's going to be done on ALL responses, couldn't we close this issue now? I.e. it's going automatically apply to static SPAs like the home page and the site-search.

**Comment by escattone** [comment]
@peterbe Yes, we can close this now. I've updated the proper Cloudfront behaviors such that **all** responses from S3 will get the security headers we've added to https://github.com/mdn/yari/blob/master/deployer/aws-lambda/content-origin-response/index.js.
