### ISSUE TITLE
Moznss 3.36 version is not supporting EC keys

### ISSUE THREAD

**Issue by kalyank23** [mdn/yari#2802]
Moznss 3.36 version is not supporting EC keys and is causing PKCS unknown error in RHEL6, could you please let us know if EC keys are supported by NSS or not?

EC keys will have starting string "-----BEGIN EC PRIVATE KEY-----"

**Comment by peterbe** [comment]
This has nothing to do with Yari. Wrong repo I'm afraid.

**Comment by kalyank23** [comment]
I came from this link https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS

![image](https://user-images.githubusercontent.com/34736945/107067680-a35f7780-6805-11eb-8e67-70bc60b72ef8.png)
