### ISSUE TITLE
React scripts 4.0.2 breaks dev build but not CI

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2805]
`react-scripts` was updated earlier today https://github.com/mdn/yari/pull/2803

I pulled the latest from `master` and merged into my current working branch. After running `yarn` to install the latest updates I ran `yarn dev` and got the following error:

```
❯ yarn dev  
yarn run v1.22.10
$ yarn prepare-build && nf -j Procfile.dev start
$ yarn build:client && yarn build:ssr && yarn build --spas-only && yarn tool gather-git-history --verbose
$ cd client && cross-env INLINE_RUNTIME_CHUNK=false react-scripts build
Creating an optimized production build...
Failed to compile.

./src/assets/dino.svg (../node_modules/@svgr/webpack/lib?-svgo,+titleProp,+ref!./src/assets/dino.svg)
Error: Cannot find module 'levenary'
```

Looking at the release notes there is this under the underlying tools section:

```
#10213 Upgrade @svgr/webpack to fix build error (@jabranr)
```

I have however also found the following issue that mentions this problem even before this update:
https://github.com/gsoft-inc/craco/issues/205#issuecomment-716514987

If I manually change the version of `react-scripts` to `4.0.1` and then run `yarn` followed by `yarn dev` all is well. I guess we need to either log this as an issue with `react-scripts` or simply manually install `levenary` as a dependency. Thoughts? @peterbe @fiji-flo

**Comment by peterbe** [comment]
First of all, I'm reverting it now. https://github.com/mdn/yari/pull/2806 
The true bug is that CI allowed this to happen. I need figure out why it passed CI.

**Comment by peterbe** [comment]
Once that's figured out, we'll probably just need to add this new peer dependency `levenary`.

**Comment by peterbe** [comment]
After much sad debugging I can conclude that the error makes no sense. The reason it's only failing on our machines is that there's some bug somewhere related to `yarn` in that some old gunk is stuck in the `node_modules` when it shouldn't. Doing `rm -fr node_modules && yarn install` always seems to work. Annoying. But perhaps more reason to move to `yarn` 2.

**Comment by peterbe** [comment]
Not much we can do here. CI always starts afresh.

**Comment by mattiapontonio** [comment]
> rm -fr node_modules && yarn instal

How about do this in `preintall`?
