### ISSUE TITLE
Push Google Analytics to run later

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2809]
The documentation for adding the Google Analytics script snippet is here: https://developers.google.com/analytics/devguides/collection/analyticsjs

How we're currently doing it is not ideal. 

- We always trigger an (`async`) request to `https://www.google-analytics.com/analytics.js` even for clients that have DoNotTrack enabled.
- We do the Google Analytics stuff before we do our React hydration stuff (which is more valuable to users than analytics to us)
- We rely on sending the pageview from the React code anyway so there's point loading it until the React code has loaded
- Loading as an inline script in the head takes away potentially precious CPU-time when the browser should just focus on rendering the HTML + CSSOM. 
- As a deferred external script tag, loaded last of all, we stand to make every HTML page 1,291 bytes smaller. 

Also, we're currently triggering the `ga('send', 'pageview')` very late. It happens after the `<Document>` component has mounted. That means we might be missing pageviews anyway if someone's on a really slow network connection or really slow JS. So to do the Google Analytics very late is no risk of losing pageviews.

**Comment by peterbe** [comment]
I suggest we package up all the JS code that does the DoNotTrack stuff and the `ga('create', 'UA-36116321-5', 'mozilla.org');` in a deferred loaded script which we make sure is *last* of all the other external .js. 
And, in that JS code we also conditionally add `https://www.google-analytics.com/analytics.js` script tag only if the DoNotTrack means we're going to bother.

**Comment by mattiapontonio** [comment]
I don't know if it helps but what I can say here is that I would expect Google Analitics to not really catch on HTML.
So intuitively we should check the request headers (is that where you see the flag?) And insert or not 2 `script` tags in the html, 1 for the library and 1 for our implementation.

**Comment by Ryuno-Ki** [comment]
Please, respect DNT (I mean, I'm blocking Google Analytics anyway, but …)

Mozilla used to be known for privacy respecting behaviour. There is some actions that made Mozilla shed a bad light on it, so respecting DNT could be a small step to regain the trust.

> Note: DNT seems actually obsolete.

No, but completely ignored by the ad industry, because it would mean loosing :money_mouth_face:

**Comment by mattiapontonio** [comment]
![Screenshot_20210209-203502.png](https://user-images.githubusercontent.com/44380480/107417878-4ff76d00-6b16-11eb-9ac7-d10002f2cb10.png)

> No
I see Obsolete. Is BCD wrong?
Anyway Yes I agree. I'm for old school HTML text and graphic without too much psicology 🧠🧐 etc
