### ISSUE TITLE
Broken link on XPath page

### ISSUE THREAD

**Issue by ekr** [mdn/yari#2819]
https://developer.mozilla.org/en-US/docs/Web/XPath has a link under XSLT/XPath Reference to https://developer.mozilla.org/en-US/docs/Transforming_XML_with_XSLT/The_Netscape_XSLT%2f%2fXPath_Reference

But this does not exist.

**Comment by escattone** [comment]
The fix for this has been merged. It may take up to 48 hours for the changes to be visible on MDN. Thanks for reporting this @ekr.
