### ISSUE TITLE
Proposal for better page footer

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#2830]
The page footer looks like this: 

![image](https://user-images.githubusercontent.com/5368500/106996694-8743e200-67d5-11eb-99c3-867594808d8c.png)

What I personally would find more useful would be:
- **Edit on github** (replace link to source on github). Essentially just open the page rather than go to it. This shortens process by one step for most users. Ideally the name of the PR should seeded with the name of the page being edited.
- **Create a bug report** - Open a bug report using standard template that includes a link to the actual page in which the bug is present, and ideally also a link to the github page for editing. 
- The link to contributing guide is good
- 
@chrisdavidmills FYI

**Comment by chrisdavidmills** [comment]
@hamishwillee For the first link, I think "Edit on GitHub" is better text, per se — it is more of a call to action, it is more obvious  what you are doing if you click it. I think we didn't go for that text originally because we were unsure about whether it would be a good idea to try and take them straight to the URL for editing the page — they would need a GitHub account and be logged in before clicking it, what happens if they don't have a GitHub account, etc...? If we can resolve these questions, then I'd be more than happy to change it.

For the second link, your text is shorter and more succinct, but do we need to be more specific about which page you are creating a bug report for? Our existing text is more specific as to what clicking the link actually does. I know it is heavily implied that if you click this link on a page, it'll be a bug report for that page...but...hrm.

**Comment by mattiapontonio** [comment]
https://github.com/login?return_to=https%3A%2F%2Fgithub.com%2Fmdn%2Fcontent%2Fedit%2Fmain%2Ffiles%2Fen-us%2Fmdn%2Fstructures%2Flive_samples%2Findex.html

If you are logged out it sends you to a login with I suppose the next redirect.
It is true we are obliged to create an account but patience.
In my opinion we should put both links, in my opinion we should put a number of links greater than 3, for example 6 (blame, raw, source, edit, something related to Yari too).

**Comment by sarkariresulta** [comment]
<a href="https://sarkariresulta.com/">Check the footer of this website for better footer</a>

**Comment by hamishwillee** [comment]
@chrisdavidmills 

1. Re [Source on Github](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases) vs [Edit on Github](https://github.com/mdn/content/edit/main/files/en-us/mozilla/firefox/releases/index.html)

Let me put it to you another way - what's the user experience now, and which is better? Try it out - both links above are "good".

Consider the current case. You go to the source. If you don't know what you're doing you're looking at some source with no clue why you have been directed to this page. You don't know that you can edit the page here, and you don't know you have to login first. If you do know what is going on you have to select the edit button (and extra step) and possibly also log in.

With  [Edit on Github](https://github.com/mdn/content/edit/main/files/en-us/mozilla/firefox/releases/index.html) you know that the purpose is editing. If you're logged in you get taken straight to the page and you can see what you're supposed to do. If you're not you get taken to the login page and from there to the page to edit once you login. I believe if you don't know what a login page is for then you aren't capable of helping on MDN.

Upshot, to me this is a "no brainer". I think if you try this out yourself you will come to the same conclusion.

2. Good point. Arguably implied, and you don't necessarily need to list where the bugs live- i.e. "On github". So other options are "Report a problem with this content", "Report a bug on this page". I quite like the last one.

PS. The comment above from sarkar... looks like spam. I can't delete it.

**Comment by chrisdavidmills** [comment]
1. I think we agree here.
2. Yeah, I like "Report a bug on this page" too.
3. Spam comment deleted.

**Comment by hamishwillee** [comment]
@peterbe I think we've converged here - first link opens current page to edit on github and second link just changes text - ie. 

![image](https://user-images.githubusercontent.com/5368500/107287949-ce242700-6ab6-11eb-8809-cbffb18a198a.png)

Could someone in the dev team be assigned to this (not in a hurry, just want to make sure that it is owned by someone to either progress or close).

**Comment by peterbe** [comment]
Curveball here; I often click "Source on GitHub" to see it and it links me to things like the git history and the git blame and stuff. For actually editing I always used my local git version and VSCode for the actual editing. 

Another curveball; are we sure that "bug" is the right word for things that aren't completely broken but could do with an improvement. I.e. "This paragraph isn't wrong but it should also mention so and so"

**Comment by peterbe** [comment]
What do you think @schalkneethling @escattone @fiji-flo ?

**Comment by hamishwillee** [comment]
> I often click "Source on GitHub" to see it and it links me to things like the git history and the git blame and stuff. For actually editing I always used my local git version and VSCode for the actual editing.

I do too, but neither of us are/should be the main audience for this link. We're going to be able to find this page anyway, and if we wanted to we could click an edit link and then cancel to see the file. 

The main audience we want for a link like this is fly-by-helpers who don't want to understand our toolchain and we want to encourage to do quick fixes through the github interface. 

If you saw this as vital to your work we could keep it "as well" (maybe at bottom of the list). 

> are we sure that "bug" is the right word for things that aren't completely broken but could do with an improvement. I.e. "This paragraph isn't wrong but it should also mention so and so"

Fair enough. You could argue the existing text "problem" doesn't meet this requirement either. Personally I think that people will understand "Report a bug" to mean make improvements as well, and I like the fact that it is succinct. That said, here are some more options, all better than the existing text:
- Report a bug/improvement on this page
- Suggest an improvement to this page
- Raise an issue against this page

**Comment by mattiapontonio** [comment]
GitHub uses _Create Issue_.

![Screenshot_20210208-234242.png](https://user-images.githubusercontent.com/44380480/107290769-6692bb00-6a67-11eb-875c-b37b321764f2.png)

**Comment by Ryuno-Ki** [comment]
„Make this page better”?

„Improve this page”?

Bug and issue sounds pretty much like technical jargon to me.

**Comment by mattiapontonio** [comment]
One should always try to tell the truth. And this cliché serves as a general opinion on this whole issue.

**Comment by Ryuno-Ki** [comment]
I can see your reference to CRUD (Create, Read, Update, Delete) here. But bear in mind, that naming the tool isn't helping much.

If you would … let … don't know, aliens write the content, the visitors couldn't care less. Yari is out of question.
Deleting is destructive. You often don't come to GitHub to delete pages.

In fact, glancing over the reported issues at mdn/content, those drive-by editors are mainly reporting (or fixing) typos and bad links for now. That should be our focus.

**Comment by mattiapontonio** [comment]
I see your points but for convenience I don't focus on objectives like those (let's say strategic) but I prefer consistent code, clear and as universal as possible (Wikipedia and co for words). 👍

**Comment by mattiapontonio** [comment]
> Deleting is destructive

Yes, but some might want shortcuts. In the end I think there is always a PR involved.

**Comment by hamishwillee** [comment]
The audience for these kinds of links is beginners who don't know how MDN works. If you want them use these instructions they need to be unambiguous, succinct and easy to find. 

These suggestions both imply a call to edit a page, not to report a problem or improvement (i.e. you might use them on the Edit on Github link, but not the report an issue link).
- Make this page better”?
- Improve this page”?

> Bug and issue sounds pretty much like technical jargon to me.

I think we have an audience that understand these terms, but assuming that others agree with you, a few more options are:

- Suggest an improvement to this page
- Tell us how we can improve this page
- Let us know how we can make the page better
- How can we make this page better?

**Comment by mattiapontonio** [comment]
Keep going on the tangent of your ideal world divided into ideal groups of people and ideal issues. The reality is that those links actually create objects on a GitHub database or view or modify them through a web interface that requires code authentication of files on a filesystem hosted by GitHub according to a technology called Git. Now this is long to explain and therefore we could make guides that already exist but the best thing is to copy the terms of the technologies we have chosen to use together with the terminologies of the methodologies that we have not chosen to use but which are convenient.

**Comment by hamishwillee** [comment]
@mattiapontonio I certainly will, though I prefer to think of them as "real people". My favourite design principle is KISS. Look it up :-)

Anyway, I am now more interested in what the people who haven't commented have to offer.

**Comment by fiji-flo** [comment]
I think send them sending a beginner directly to [Edit on GitHub](https://github.com/mdn/content/edit/main/files/en-us/web/html/index.html) (open this link in a private window!) which prompts them directly with a login/signup page is not a great user experience. Signing up, editing and figuring everything out is a lot to ask. I would link the the file on GitHub but also have a link to a contribution guide in the footer.

**Comment by mattiapontonio** [comment]
The real problem is that you can't know if a server will reply [200](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) or [401](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401) to a client without it fetching so you shouldn't worry about it when giving a URL.
It's a bit like asking an editor to test links before using them in articles, if they did we wouldn't need flaw check on broken links.
It's not so much a user experience issue but an http issue.

**Comment by hamishwillee** [comment]
@fiji-flo **Edit on github** is so popular in the SSG world that is almost defacto standard - perhaps to some extent supported by the fact that the default Read the docs theme has this in the header - see https://docs.scrapy.org/en/latest/

It is certainly a better experience that going to the source and trying to read the wall of text that is our contribution guide to work out the next step. Logging in is something people understand.

I invite you to try both options: [Source on Github](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases) vs [Edit on Github](https://github.com/mdn/content/edit/main/files/en-us/mozilla/firefox/releases/index.html)

**Comment by Ryuno-Ki** [comment]
> **Edit on github** is so popular in the SSG world that is almost defacto standard

This could be also your personal echo chamber (*shouts 'Hey there' into a shared bubble).

> the default Read the docs theme has this in the header

I agree. I can see it in several technical documentations.

> It is certainly a better experience that going to the source

Seeing the source would allow me to orient myself (and perhaps denote the line number I'm about to change). But vertical scrolling makes the experience less appealing - another issue about max column length once we are on Markdown-base.

But then, getting thrown into the editor might be more a resembling of the WYSIWYG-Editor we had in the wiki days.

>  trying to read the wall of text that is our contribution guide to work out the next step

That is a separate issue to make the text more appealing. If only we had a technical writer *hint
I think, there's already an issue on that over in the mdn/content repo.

> And if you still disagree

Oh, I don't. I want to look at it from different angles to make a balanced decision. Don't feel discouraged, please! :heart:

**Comment by fiji-flo** [comment]
> @fiji-flo **Edit on github** is so popular in the SSG world that is almost defacto standard - perhaps to some extent supported by the fact that the default Read the docs theme has this in the header - see https://docs.scrapy.org/en/latest/

Am I looking at the wrong link? That one does not open the edit page:
[Edit on GitHub](https://github.com/mdn/content/blob/main/files/en-us/web/html/index.html) vs [Edit on GitHub](https://github.com/mdn/content/edit/main/files/en-us/web/html/index.html)

I was just voting to use the first one, sorry if I didn't make myself clear. And that's just about changing the link text in the footer.

**Comment by peterbe** [comment]
> @fiji-flo **Edit on github** is so popular in the SSG world that is almost defacto standard - perhaps to some extent supported by the fact that the default Read the docs theme has this in the header - see https://docs.scrapy.org/en/latest/
> 
> It is certainly a better experience that going to the source and trying to read the wall of text that is our contribution guide to work out the next step. Logging in is something people understand.
> 
> I invite you to try both options: [Source on Github](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases) vs [Edit on Github](https://github.com/mdn/content/edit/main/files/en-us/mozilla/firefox/releases/index.html) - both with Github login and without.
> 
> And if you still disagree, I can live with it - not broken, just subobtimal.

Interesting twist there; Readthedocs uses the phrase "Edit on GitHub" but it doesn't link to "edit mode", it links to "view mode" which seems to be a mix of what you, @fiji-flo, and I prefer. I.e. keep the URL as is but change the label for the link.
```html
<a href="https://github.com/mdn/content/blob/main/files/en-us/web/index.html">Edit on GitHub</a>
```
I can get behind that. Readthedocs is prevalent and it's a phrase that a lot of people are used to. 

However, not to be weird, but a part of me doesn't want people to edit on GitHub. I'd rather they get more engaged and take the time to set up the toolchain. Yes, it's a higher threshold but it'll empower them more and hopefully inspire them to stick around and do more edits and that way they become more aware of things like the `move` CLI or the ability to tidy up flaws. So attaching the word "Edit" to that link might be a bad thing.

**Comment by Ryuno-Ki** [comment]
I side with @mattiapontonio here. Let's make it easy for contributors to submit small patches and welcome them so stay for the CLI.

**Comment by hamishwillee** [comment]
@fiji-flo So yes I really did mean "Edit", but you're right, that ReadTheDocs really does just view. If we're not opening to edit then I'm ambivalent about the text.

It is not at all weird to want people to use the CLI. But in practice, my experience indicates that no matter how simple your tooling setup or how great the experience, people will still jump through crazy complicated hoops to use Github directly. That's another reason to move to markdown, where you get a really good editing experience within a single page using the github preview.

Given that as a team you're unconvinced, I'm closing this (but further discussion is unlikely to be good use of limited engineering and documentation resources).

**Comment by mattiapontonio** [comment]
> where you get a really good editing experience within a single page using the github preview.

It would be nice if GitHub did the preview of the html too, always highlighting the differences
