### ISSUE TITLE
Remove all appropriate KS macro calls from our JavaScript documentation

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#2844]
**Depends on https://github.com/mdn/sprints/issues/2520 and https://github.com/mdn/sprints/issues/2523**

In https://github.com/mdn/sprints/issues/2520 we triage all the KS macro calls made from our JavaScript documentation. In https://github.com/mdn/sprints/issues/2523 we develop a tool that can selectively remove KumaScript macro calls.

In this story we run the tool over the KumaScript documentation, asking it to remove the macro calls that we triaged as "remove". We then have to review the documentation, to ensure nothing broke.

## Acceptance criteria
Our JavaScript documentation no longer contains calls to any macros triaged as "remove".

**Comment by wbamberg** [comment]
Yeah, we still have several hundred calls to {{Draft}}, although I think we have consensus for removing them.

**Comment by schalkneethling** [comment]
> Yeah, we still have several hundred calls to {{Draft}}, although I think we have consensus for removing them.

Shall we close this one and spin up a new issue specifically for phasing out `Draft`?

**Comment by wbamberg** [comment]
Sounds good to me. I started https://github.com/mdn/content/discussions/10273 in case anyone wants to keep it but so far it's looking uncontroversial :).

**Comment by schalkneethling** [comment]
https://github.com/mdn/yari/issues/4876
