### ISSUE TITLE
Render all appropriate KS macro calls made in our JavaScript documentation

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#2845]
**Depends on https://github.com/mdn/sprints/issues/2520 and https://github.com/mdn/sprints/issues/2521**

In https://github.com/mdn/sprints/issues/2520 we triage all the KS macro calls made from our JavaScript documentation. In https://github.com/mdn/sprints/issues/2521 we develop a tool that can selectively render KumaScript macro calls.

In this story we run the tool over the KumaScript documentation, asking it to render the macros that we triaged as "render". We then have to review the documentation, to ensure nothing broke.

## Acceptance criteria
Our JavaScript documentation no longer contains calls to any macros triaged as "render". Instead, they contain the static HTML that these macros generate.

**Comment by schalkneethling** [comment]
@escattone Is this part of the work that was discussed some time ago regarding rendering our certain macros?

**Comment by escattone** [comment]
@schalkneethling I think we can close this, but let's confirm with @wbamberg.

**Comment by wbamberg** [comment]
Yes, let's close this. Maybe some day we will want to revisit KS macros, but it will probably be in a different project.
