### ISSUE TITLE
AvailableInWorkers macro - some workers might not be supported

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#2849]
`{{AvailableInWorkers}}` can be applied to a page to add a note like this: 
![image](https://user-images.githubusercontent.com/5368500/107305652-7d70f600-6ad7-11eb-91b9-c8293751bb4d.png)

Thing is, there are three (maybe 4) types of web workers, and depending on the thing you're talking about it might not be supported in all workers. For example, XMLHttpRequest does not work in service workers. To fix this I have to add a separate note or similar below this tag, and it's a bit ugly.

So minimally, might be worth modify this from:

>  Note: This feature is available in Web Workers.

TO 

> Note: This feature is available in Web Workers (check [link]compatibility table[/link] for details).

An even more flexible approach would be to allow me to add a string that replaces "This feature is available in Web Workers.". E.g.,  `{{AvailableInWorkers, "This feature is available in Web Workers except for service workers}}`

**Comment by mattiapontonio** [comment]
Comment to stay updated on this. 🎲🎟️

**Comment by Ryuno-Ki** [comment]
@mattiapontonio In cases like this, there's a „Subscribe” button in the Desktop view (which you can enforce even on mobile) on the right sidebar under „Notifications”. This allows you to get informed without sending a comment.

**Comment by hamishwillee** [comment]
Also, this template is not to current style for a note box, and lacks a space between the : and the text

**Comment by schalkneethling** [comment]
So, this is made up of 4 macros:

```
kumascript/macros/AvailableInWorkers.ejs
kumascript/macros/Note.ejs
kumascript/macros/NoteStart.ejs
kumascript/macros/NoteEnd.ejs
```

@escattone Could we just collapse this to a single macro that outputs a note card? We could then also do something like `var text = $0 || defaultText;` so, if someone passed a string, display that, else use the current defaults.

**Comment by peterbe** [comment]
I don't know if this helps but did you know what you can now reach anything from a document's front-matter in the kumascript rendering. E.g.
```
var text = $0 || env['some-front-matter-key'] || defaultText;
```

**Comment by peterbe** [comment]
@schalkneethling Yes you can collapse them into one single macro. You just need to make sure it doesn't break any translated-content page that might be using them individually. 

I think you just need to replace the line `<%- await template("Note", [text]) %>` in `AvailableWorkers.ejs` to just do all things they used to do. 
It might even make the rendering a bit faster! There are 287 + 644 mentions of this macro.

Do you want a hand?

**Comment by schalkneethling** [comment]
> Do you want a hand?

Nope, I think I got this. I will ping you for reivew.

**Comment by escattone** [comment]
@schalkneethling Thank you! Sorry for my delay in responding. Thanks @peterbe as well!

**Comment by hamishwillee** [comment]
Thanks very much guys.

@peterbe FYI only, just as we are discussing for deprecation, it might be good at some point to auto-add worker support information from BCD rather than using this macro at all. The problem is slightly harder for the same reason we needed this fix - BCD does not differentiate support for particular web workers except using a note.

**Comment by peterbe** [comment]
> Thanks very much guys.
> 
> @peterbe FYI only, just as we are discussing for deprecation, it might be good at some point to auto-add worker support information from BCD rather than using this macro at all. The problem is slightly harder for the same reason we needed this fix - BCD does not differentiate support for particular web workers except using a note.

If you had access to the BCD data, how would you deduce if the macro's text should appear?

It's not just the `AvailableInWorkers` but lots of things on the page might want to be dependent on getting into the meat of the BCD data. For example, one of the reason @wbamberg wanted the `browser-compat` available from the front-matter was so he could conditionally put up a deprecation/warning note at the top of the page.

Despite years of getting close to BCD I still don't really understand it. (Or, sometimes I do but then it leaks out of my brain by the following Monday). It could potentially be useful to extract the `browser-compat` from the front-matter and fetch its data from browser-compat so its meat is available to all sorts of KS macros.

**Comment by hamishwillee** [comment]
> If you had access to the BCD data, how would you deduce if the macro's text should appear?

@peterbe That's precisely my point; you don't. For AvailableInWorkers this could really only work "properly" if we were to add markup to indicate each type of worker. 

IMO it is STILL worth automatically adding the worker note from BCD, even with loss of information in the note. You'd want to include something like "Available in workers. Check compatibility table for specific omissions". Alternatively, you add it automatically from BCD if there is no note, and use an in-source note for the relatively small set of exceptions.

Why? I think managing this in one place is better, and BCD appears to have the good quality gates for information addition.

As an aside, I find BCD hard to grasp too. Mostly because my mind just wants it to be a 1:1 mapping to the code (and other) structures it describes, while the mapping is more "pragmatic".

**Comment by hamishwillee** [comment]
> As an aside, I find BCD hard to grasp too. Mostly because my mind just wants it to be a 1:1 mapping to the code (and other) structures it describes, while the mapping is more "pragmatic".

@peterbe A couple of BCD assumptions that will affect how yari does this for workers and deprecateion:
- BCD "mostly" assumes cascading properties. So if a parent is deprecated or is available in workers then all its children are too. 
- If a property of some kind is not documented then it is assumed to be supported at the same level of the parent. So you would have to assume that if property `x` is in bcd as deprecated, then `x.y` would be deprecated even if `y` is not in the BCD.

I'm sure you know that :-)
