### ISSUE TITLE
Compatibility table background for disabled-by-default features is too positive

### ISSUE THREAD

**Issue by evilpie** [mdn/yari#2856]
Currently for features that are implemented, but require a setting a flag, the background is green. In reality such a feature can not be used in production in that browser, because the the majority of people will not have this flag set.

I think MDN should use a different color. For example "Partial" uses orange/yellow from what I remember.

**Comment by Elchi3** [comment]
Transferred to yari since this about how we render compat data. I think the relevant file is https://github.com/mdn/yari/blob/master/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx

**Comment by mattiapontonio** [comment]
I was just thinking about it the other day. In fact I believe supported means 100% supported as per specification and any other case could fall into unsupported.

**Comment by Ryuno-Ki** [comment]
@Elchi3 Browsing a GitHub file and then hitting <kbd>y</kbd> will give you a permalink (in case we break up the file or rename it or something the link will remain being navigateable).

So … in my understanding, we have two issues worth talking about here:

1) How to deal with features, that are implemented, but hidden behind a flag (with respect to tooltips, iconography etc)
2) Do we need more colours for BCD tables?

Can we look into how others implemented it?
I mean, VS Code consumes BCD. DevTools can utilise them, too (I recall having seen it somewhere).

What I'm missing on the web is a somewhat striped background colour (you can do that with linear gradients, I guess).
Like … „this can be used, but …”

**Comment by mattiapontonio** [comment]
> How to deal with features, that are implemented, but hidden behind a flag (with respect to tooltips, iconography etc)

Move them as is outside the table. 🚜

> Do we need more colours for BCD tables?

✖️ Nope

**Comment by peterbe** [comment]
> I agree. See previous discussions on this:
> 
>     * [mdn/kumascript#1346](https://github.com/mdn/kumascript/issues/1346)
> 
>     * [mdn/kumascript#701](https://github.com/mdn/kumascript/pull/701)
> 
>     * https://bugzilla.mozilla.org/show_bug.cgi?id=1449340

If you and/or @ddbeck can reduce all those old discussions, plus @evilpie 's fresh one, then I think I can easily execute the change. Happy to but it'll take me a while if I have to forensically figure out what the nuisance and details are of discussions past.

**Comment by Elchi3** [comment]
> If you and/or @ddbeck can reduce all those old discussions, plus @evilpie 's fresh one, then I think I can easily execute the change. Happy to but it'll take me a while if I have to forensically figure out what the nuisance and details are of discussions past.

Sure, the idea is that everything here should be red: https://developer.mozilla.org/en-US/docs/Web/API/Bluetooth/getDevices

The compat data is here https://github.com/mdn/browser-compat-data/blob/master/api/Bluetooth.json#L206.
You can see a `flags` property for chrome and friends and that's the indicator in the data that should make things red in rendering.

**Comment by mattiapontonio** [comment]
It would take a
https://json-schema.org/
so you could refer to that

**Comment by Ryuno-Ki** [comment]
https://github.com/mdn/content/issues/2289 would be another instance for this „enabled-behind-a-flag” if I understood it correctly.

**Comment by mattiapontonio** [comment]
> https://github.com/mdn/content/issues/2289 would be another instance for this „enabled-behind-a-flag” if I understood it correctly.

Yes It Is
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
![Screenshot_20210211-193531.png](https://user-images.githubusercontent.com/44380480/107682297-71846000-6ca0-11eb-83a7-2779743d9f02.png)
![Screenshot_20210211-193558.png](https://user-images.githubusercontent.com/44380480/107682284-6d584280-6ca0-11eb-9094-0fc6f890d075.png)

(Too bad because the dialog seemed like a good feature to me)
