### ISSUE TITLE
Salvage 404s that are 404s because of lack of /docs/

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2863]
Take https://developer.mozilla.org/en-US/DOM/element.addEventListener for example. 
It came up in https://github.com/mdn/content/issues/2073

What ought to happen is that the fundamental redirects should have...
```
/en-US/DOM/(*) --> /en-US/docs/DOM/$1
```
but that list is very long. As of today, it's basically anything where the word after the locale isn't `search` or `settings` or `sign-up` or whatever we come up with next. 

A simple fix would at least be to make the 404 page a bit more useful. A piece of async XHR could do something like:

```javascript
// pseudo-code

if (VALID_LOCALES.has(currentLocale) && location.pathname.split('/')[1] !== 'docs') {
  const tryURL = location.pathname.split('/').splice(1, 0, 'docs').join('/') + '/index.json'
  const r = await fetch(tryURL)
  if (r.ok) {
    showGoodNews(r.url)
  }
}
```

**Comment by escattone** [comment]
@peterbe I like this idea! In addition to this, I'm going to think about something we can do either in the origin-response Lambda@Edge function on 404's, or perhaps even better, in the S3 redirect rules.

**Comment by peterbe** [comment]
Once https://github.com/mdn/yari/pull/2891 lands, we'll be able to use Google Analytics to see what URLs people ended up on when they got a 404. 
We can download a report of that and see if there are any major patterns. For example, I did see some 404s fly by on URLs like `/en-US/JavaScript/...` and that seems like something we could treat similarly to https://github.com/mdn/yari/pull/2872
Otherwise, if it's just too many different patterns that could be salved with attempting to inject a `/docs/` after the locale, then we can work on this issue. 

Also, I made sure that the fallback testing XHR stuff inside the `<PageNotFound>` component is lazy-loaded so we don't need to worry about "bloating" the man JS bundle just because we add more code there.

**Comment by peterbe** [comment]
I [downloaded](https://analytics.google.com/analytics/web/#/report/content-pages/a36116321w64965862p66726481/_u.date00=20210219&_u.date01=20210221&explorer-table.secSegmentId=analytics.pageTitle&explorer-table.plotKeys=%5B%5D&explorer-table.advFilter=%5B%5B0,%22analytics.pageTitle%22,%22PT%22,%22Page%20not%20found%22,0%5D%5D&explorer-table.rowCount=1000&explorer-table.rowStart=0) the top 1,000 most frequest URLs where people get a 404. 

When I analyze only the `en-US` URLs that lack the `/docs/` I find that 95% would be 200 (instead of 404) if you just squeeze in the `/docs/` to the URL. 
Of those, the 9 most frequent ones are:

```
JavaScript           46 30.7%
DOM                  41 27.3%
CSS                  14 9.3%
Tools                4  2.7%
HTML                 4  2.7%
SVG                  3  2.0%
XMLHttpRequest       3  2.0%
DragDrop             2  1.3%
IndexedDB            2  1.3%
```

So if we can add an entry to the fundamental redirects for `JavaScript`, `DOM`, and `CSS` we'd avoid 67%  of 404s that can easily be fixed by "injecting" a `/docs/` after the locale.

**Comment by peterbe** [comment]
@escattone Can you tie your PR to this issue that adds it to the fundamental redirects?
