### ISSUE TITLE
Make site-search results score-debugging optional

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2866]
This stuff is only really useful if you're actively debugging the Kuma algorithm for combining "matchness" with the popularity. 

<img width="1317" alt="Screen Shot 2021-02-09 at 4 33 17 PM" src="https://user-images.githubusercontent.com/26739/107435565-511aa100-6afa-11eb-9f52-803e83b2f98a.png">

**Comment by mattiapontonio** [comment]
I would leave them
