### ISSUE TITLE
The main JS bundle is too large

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2877]
The `client/build/static/js/main.HASH.chunk.js` bundle is too large. At the time of writing, it's 67KB. 
Its source map analysis looks like this:

<img width="1493" alt="Screen Shot 2021-02-10 at 9 59 24 AM" src="https://user-images.githubusercontent.com/26739/107527264-aac8ad00-6b86-11eb-83e9-e272276ce9ee.png">

And here's the breakdown as a list:

```
Source	Size
[no source]	10019
assets/logo.svg	7145
document/index.tsx	4891
assets/avatar.png	4401
ui/organisms/footer/index.tsx	3402
ui/molecules/main-menu/index.tsx	3318
document/on-github.tsx	2704
page-not-found/index.tsx	2567
app.tsx	2335
homepage/index.tsx	2053
document/ingredients/examples.tsx	1877
assets/dino.svg	1610
document/lazy-bcd-table.tsx	1595
document/ingredients/attributes.tsx	1398
constants.ts	1307
ui/molecules/language-menu/index.tsx	1210
document/organisms/sidebar/index.tsx	1200
ga-context.tsx	1158
site-search/index.tsx	1135
ui/molecules/login/index.tsx	1039
user-context.tsx	1020
ui/molecules/search/index.tsx	950
document/organisms/toc/index.tsx	945
ui/molecules/dropdown/index.tsx	892
document/organisms/metadata/index.tsx	771
ui/organisms/header/index.tsx	737
document/ingredients/specifications.tsx	731
ui/molecules/breadcrumbs/index.tsx	685
banners/index.tsx	617
document/preloading.tsx	580
document/ingredients/link-lists.tsx	576
ui/molecules/a11y-nav/index.tsx	543
document/ingredients/utils.tsx	490
index.tsx	436
document/ingredients/prose.tsx	351
[unmapped]	273
ui/atoms/page-content/index.tsx	259
document/ingredients/interactive-example.tsx	229
utils/auth-link.ts	225
ui/atoms/signin-link/index.tsx	221
ui/atoms/logo/index.tsx	197
ui/molecules/titlebar/index.tsx	196
document/hooks.ts	186
hooks.ts	97
banners/ids.ts	64
[sourceMappingURL]	47
[EOLs]	1
```

Things to maybe dig in to:

* [The `page-not-found` thing is taking up 2567 bytes but a lot of it can be made lazy-loaded](https://github.com/mdn/yari/pull/2883)
* Can the `logo.svg`, `dino.svg` be removed from the bundle? I know they're part of the React rendering but if we don't need to style them with CSS, can they be loaded as images, like we're doing with the magnifying glass?
* [Why is the `avatar.png` part of the bundle? It's only supposed to be used if someone logged in and doesn't have an `avatarUrl` in their profile.](https://github.com/mdn/yari/pull/2882)
* [Starting with `document/ingredients/examples.tsx` these ingredients are left-overs from when Yari was the renderer for the Stumptown-content project. We never execute most of the ingredient components.](https://github.com/mdn/yari/pull/2881)
* The `language-menu/index.tsx` becomes so big because it loads in the `languages.json`, but if we can just put the native spelling of languages as part of the JSON data about the translations we won't need the complete list of all languages. 
* The `ui/organisms/footer/index.tsx` is probably so big because it loads in all the SVGs. But why aren't 
* [The dino.svg is rarely needed and can be an image](https://github.com/mdn/yari/issues/2990)

**Comment by peterbe** [comment]
Here's a spreadsheet and a cryptic pie chart of that same table as above: https://docs.google.com/spreadsheets/d/1doQcM7uLLEGvfN2EW8Ztxa3mMH08JpRZoZ9HW_nqMEc/edit#gid=1266556508

**Comment by peterbe** [comment]
Note-to-self how I generated the source-map treemap:
```
yarn prepare-build
npx source-map-explorer client/build/static/js/main.f2b69ef0.chunk.js
npx source-map-explorer client/build/static/js/main.f2b69ef0.chunk.js --tsv
```

**Comment by peterbe** [comment]
https://evanw.github.io/source-map-visualization/ is a great resource too. You click to upload and select `main.*.map` file.

**Comment by mattiapontonio** [comment]
> if we don't need to style them with CSS

Why not.

**Comment by schalkneethling** [comment]
In https://github.com/mdn/yari/pull/2882 @peterbe moved the default fallback avatar image to assets 👍  - we can shave a few more bytes of if we convert the `png` to an `svg`.

**Comment by mattiapontonio** [comment]
> Note-to-self how I generated the source-map treemap:
> ```
> yarn prepare-build
> npx source-map-explorer client/build/static/js/main.f2b69ef0.chunk.js
> npx source-map-explorer client/build/static/js/main.f2b69ef0.chunk.js --tsv
> ```
> 

Readme?

**Comment by mattiapontonio** [comment]
The logo takes a giant slice of cake (**12,2%**), nothing can be done?

**Comment by peterbe** [comment]
>     * The `ui/organisms/footer/index.tsx` is probably so big because it loads in all the SVGs. But why aren't

@schalkneethling 
Would it be feasible to move the SVG from the JS code into external images? I know it becomes hard to control styling then but it would be a win since, as images, they're technically lazy loaded and the footer is way below the fold.

**Comment by mattiapontonio** [comment]
> I know it becomes hard to control styling then

Great point. So we have to do a PR on Yari every time we decide whether or not to style an SVG with CSS?

https://developer.mozilla.org/en-US/search?q=style+external+svg

**Comment by schalkneethling** [comment]
> > ```
> > * The `ui/organisms/footer/index.tsx` is probably so big because it loads in all the SVGs. But why aren't
> > ```
> 
> @schalkneethling
> Would it be feasible to move the SVG from the JS code into external images? I know it becomes hard to control styling then but it would be a win since, as images, they're technically lazy loaded and the footer is way below the fold.

I reckon it is fine. At the moment we do not style them at all, or if we do we simply invert the color. I have a way to do that without the SVG being in the DOM. I will create an issue for it.

**Comment by mattiapontonio** [comment]
> I have a way to do that without the SVG being in the DOM.

I'm interested. Please let's mention this in MDN if Is not.

**Comment by caugner** [comment]
✅ Chunk sizes are much smaller now (max. 169.83 kB):

```console
% yarn build:prepare                                                                                                                                                                                                                                                1 ↵ ✭
yarn run v1.22.19
$ yarn build:client && yarn build:ssr && yarn tool optimize-client-build && yarn tool google-analytics-code && yarn tool popularities && yarn tool spas && yarn tool gather-git-history && yarn tool build-robots-txt
$ cd client && cross-env INLINE_RUNTIME_CHUNK=false node scripts/build.js
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  169.83 kB        build/static/js/main.6541ca6f.js
  26.2 kB          build/static/js/966.5446b9cc.chunk.js
  22.64 kB (-2 B)  build/static/css/main.7fcd0907.css
  13 kB            build/static/js/334.05c8cba0.chunk.js
  6.78 kB          build/static/js/768.fb37e8af.chunk.js
  6.31 kB          build/static/js/68.7673ce03.chunk.js
  5.8 kB           build/static/js/browser-compatibility-table.bcbb093f.chunk.js
  5.5 kB           build/static/js/693.a3fc6bc0.chunk.js
  5.27 kB          build/static/js/996.bb7354e2.chunk.js
  4.33 kB          build/static/js/69.3ab23b5c.chunk.js
  4.31 kB          build/static/js/863.c1fb3f32.chunk.js
  4.07 kB          build/static/js/211.fef84fd9.chunk.js
  3.49 kB          build/static/js/717.a71b17a0.chunk.js
  3.48 kB          build/static/js/57.935bd084.chunk.js
  3.45 kB          build/static/js/491.aef40bf7.chunk.js
  3.11 kB          build/static/js/662.36ed4235.chunk.js
  2.2 kB           build/static/css/491.a00de7cf.chunk.css
  1.92 kB          build/static/js/791.427afbae.chunk.js
  1.67 kB          build/static/js/709.6a80be22.chunk.js
  1.6 kB           build/static/css/57.e60c22af.chunk.css
  1.29 kB          build/static/js/837.865ab4b4.chunk.js
  1.1 kB           build/static/css/518.e719f142.chunk.css
  902 B            build/static/js/472.f56c823c.chunk.js
  844 B            build/static/js/979.e277a725.chunk.js
  713 B            build/static/css/693.5a91c31c.chunk.css
  654 B            build/static/css/996.feade3fe.chunk.css
  625 B            build/static/css/837.3372dfc1.chunk.css
  625 B            build/static/css/863.76ff1021.chunk.css
  621 B            build/static/css/768.32df508f.chunk.css
  552 B            build/static/js/940.49930087.chunk.js
  444 B            build/static/css/211.c4413dff.chunk.css
  296 B            build/static/css/662.631950ad.chunk.css
  186 B            build/static/js/518.a5b6aabb.chunk.js
  145 B            build/static/css/979.7bf6dfc6.chunk.css
  132 B            build/static/css/472.066d518c.chunk.css
```
