### ISSUE TITLE
Change avatar.png to an SVG if it saves us some bytes

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2888]
In https://github.com/mdn/yari/pull/2882 @peterbe moved the default fallback avatar image to assets 👍  - we can shave a few more bytes of if we convert the `png` to an `svg`.

_Originally posted by @schalkneethling in https://github.com/mdn/yari/issues/2877#issuecomment-777246551_

**Comment by Ryuno-Ki** [comment]
@mattiapontonio Is this something you'd like to do?

**Comment by schalkneethling** [comment]
> @mattiapontonio Is this something you'd like to do?

I am happy for him to do it but, I already have the relevant asset in our design system.

**Comment by mattiapontonio** [comment]
Happy build-day 🎂😏
However I would convert them in any case because it is also good that I can zoom 🔍 in on the default avatar to see something more closely I don't know why but I do.

**Comment by peterbe** [comment]
Actually don't. I looked at 10,000 user accounts and tallied how many have an avatar picture in their details, the numbers are:

```
google          1460 14.6%
persona         682 6.8%
github          7858 78.6%

google          100.0% has a picture
persona         0.0% has a picture
github          100.0% has a picture
```

So if you can figure out a way to sign in to Persona, and you haven't uploaded a picture manually in your Edit Profile, the chances of a user NOT having a picture are extremely slim. 

Close?

**Comment by mattiapontonio** [comment]
> extremely slim

How much? **6.8%**?

**Comment by mattiapontonio** [comment]
We missed an opportunity here
