### ISSUE TITLE
Style the new site-search

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2889]
With https://github.com/mdn/yari/issues/1058 closed it is time to adding needed style, evaluate the HTML and accessibility of search.

**Comment by schalkneethling** [comment]
A note:

```
working on the site-search, if you want to simulate a slow lazy-load of the code splitting you can temporarily rewrite the import() to look something like this:
20:12
const SearchResults = React.lazy(() =>
  import("./search-results").then((module) => {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve(module as any);
      }, 5000);
    });
  })
);
```

**Comment by peterbe** [comment]
Remember to search for things that yield suggestions. Then a "Did you mean..." thing pops up.

**Comment by mattiapontonio** [comment]
> Remember to search for things that yield suggestions. Then a "Did you mean..." thing pops up. 
> 
> 

Why not draw up both the case in which there are suggestions and the one in which there are not?

**Comment by peterbe** [comment]
@schalkneethling What's left now?

**Comment by schalkneethling** [comment]
> @schalkneethling What's left now?

Good question :) I will take a look

**Comment by peterbe** [comment]
Ping?

**Comment by schalkneethling** [comment]
> Ping?

Let's close it. We can open small issues for the little things we want to improve.
