### ISSUE TITLE
Move icons in footer to CSS background images

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#2900]
>     * The `ui/organisms/footer/index.tsx` is probably so big because it loads in all the SVGs. But why aren't

@schalkneethling 
Would it be feasible to move the SVG from the JS code into external images? I know it becomes hard to control styling then but it would be a win since, as images, they're technically lazy loaded and the footer is way below the fold.

_Originally posted by @peterbe in https://github.com/mdn/yari/issues/2877#issuecomment-777788131_

**Comment by mattiapontonio** [comment]
IMHO
We should challenge ourselves not to use the Sprites because they are non-standard and are an over-engineering

**Comment by sohamsshah** [comment]
Hi, I would like to work on this issue. Can you guide me how shall i proceed? Thrilled to contribute to MDN (though I am very neophyte to this)

**Comment by Ryuno-Ki** [comment]
Hey @sohamsshah,

so, technically, right now the elements are part of the bundle:

https://github.com/mdn/yari/blob/5f398b3c0f2615bb6aa1a77f9f8fddc6df126697/client/src/ui/organisms/footer/index.tsx#L73-L123

The SCSS is defined in

https://github.com/mdn/yari/blob/5f398b3c0f2615bb6aa1a77f9f8fddc6df126697/client/src/ui/organisms/footer/index.scss#L51-L59

Here, you'd need a way to use `background` accordingly and define the respective image (see Dinocon import) via a `class` on the `<a>`. You can control the space via `padding` (for example).

That's how I'd try it first. Please report if you run into problems. (I hope, the outline is understandable enough to get started).

**Comment by schalkneethling** [comment]
> Hi, I would like to work on this issue. Can you guide me how shall i proceed? Thrilled to contribute to MDN (though I am very neophyte to this)

❤️  - Are you all setup with Yari locally? That would be the first step.

**Comment by sohamsshah** [comment]
@Ryuno-Ki So currently we have components for each icon and have `hrefs` on it. Essentially we want to take SVGs of those icons instead of extrernal `hrefs` for those. As you told, we can use a simple CSS class with ```css background: url("path-to-SVG")``` attribute to do this. Am I right or terribly mistaken?

**Comment by sohamsshah** [comment]
> > Hi, I would like to work on this issue. Can you guide me how shall i proceed? Thrilled to contribute to MDN (though I am very neophyte to this)
> 
> ❤️ - Are you all setup with Yari locally? That would be the first step.

Yes, I am trying to set up locally first. Apologies for a decade day delay. Would try to make a PR as soon as possible. Just need clarity upon my understanding of the problem.

**Comment by schalkneethling** [comment]
> > > Hi, I would like to work on this issue. Can you guide me how shall i proceed? Thrilled to contribute to MDN (though I am very neophyte to this)
> > 
> > 
> > ❤️ - Are you all setup with Yari locally? That would be the first step.
> 
> Yes, I am trying to set up locally first. Apologies for a decade day delay. Would try to make a PR as soon as possible. Just need clarity upon my understanding of the problem.

Were you able to get set up successfully?

**Comment by sohamsshah** [comment]
Yes I am setup with the local. Can you please help me clarify what I have understood (in above thread)?
So, essentially I have to get a link of dinocon for React, Twitter etc.  Can you assist on how can I get the background SVG link?

**Comment by schalkneethling** [comment]
Hey @sohamsshah, thank you for your interest. I will get back to you with the details on this as soon as possible.

**Comment by sohamsshah** [comment]
Thank you 😁

**Comment by sohamsshah** [comment]
@schalkneethling Hey, want to start working on this. Can you please provide required details? I badly wanna make my first contrib to THE MDN haha ;)

**Comment by sohamsshah** [comment]
Thank you! Consider it done ;)

**Comment by sohamsshah** [comment]
Hey, apologies for the delay in the PR, was a bit not well since last week. Please review it :)

Again thank you so much!

**Comment by schalkneethling** [comment]
> Hey, apologies for the delay in the PR, was a bit not well since last week. Please review it :)
> 
> Again thank you so much!

Glad you are feeling better. Will take a look. Thank you 🎉
