### ISSUE TITLE
Tag deprecated content

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#2903]
It is much more scalable and reliable to dynamically generate these kinds of lists from "tagged" content than to try to manually keep them up to date.

_Originally posted by @hamishwillee in https://github.com/mdn/content/issues/2086#issuecomment-777892990_

I was wondering, whether this tagging could go into frontmatter (think of markdown times in the future).

**Comment by Ryuno-Ki** [comment]
Note, the discussion in https://github.com/mdn/yari/discussions/2905

**Comment by mattiapontonio** [comment]
It makes perfect sense that articles are modeled as objects and have properties.

**Comment by peterbe** [comment]
Let's focus on the discussion first and if the team reaches a consensus there, we'll turn it into an actionable issue.

**Comment by mattiapontonio** [comment]
> consensus

On what? Please comment there with your thoughts.
A big point is _Where to tag_.
