### ISSUE TITLE
Handling invisible unicode

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#2906]
> Just our of curiosity: are there any issues with this other than _optics_? Should we come up with a extensive disallow list for characters in a slug, there's more malicious unicode?

Honestly, don't know. The zero-width ones are bad because they can cause problems and be very hard to debug. But your point is good.

_Originally posted by @peterbe in https://github.com/mdn/yari/issues/2172#issuecomment-747601180_

There's the Big List of Naughty Strings on GitHub which holds „known to be bad” strings.
On top of my head, I could imagine of Zero-Width-Joiners and Unicode confusables causing problems as well.

A conservative approach might be to restrict to ASCII charset (for en-US), see, what breaks (thinking of accents) and allowing a wider character set on an on-demand basis.

**Comment by peterbe** [comment]
We don't limit the folder names to ASCII even for the regular en-US content. E.g. https://github.com/mdn/content/tree/main/files/en-us/glossary/b%C3%A9zier_curve
But once all the translated content has gotten "Englishified" I think it would be sensible to extend our treatment of slugs and folder names a bit. 

@fiji-flo and I were talking about the fact that we probably should force slugs in a way that the `sanitize-filename` would never be needed other than for CI. 
Today the slug-to-folder is a matter of doing some odd but deterministic transforms (e.g. `:` becomes `_colon_`) but also whatever the outcome of `sanitize-filename` gets you. We should probably disallow that to be useful. E.g. 
```javascript
for (const {slug} of documents) {
  const folderName = replaceSlugCharacters(sanitizeFilename(slug));
  ...
}
``` 
instead, we do:
```javascript
for (const {slug} of documents) {
  if (sanitizeFilename(slug) !== slug) {
    throw new Error(`'${slug}' is so weird that it changes from sanitizeFilename. Rename the slug and put up a redirect!`);
  }
  const folderName = replaceSlugCharacters(slug);
  ...
}
``` 

Once we've done this, you can, apart from casing, figure out what the slug is based on the folder name. With that in place, only the time you'd need to include `slug` in the front-matter is if you want special casing.

**Comment by peterbe** [comment]
Note, my comment "assumes" that `sanitizeFilename` is the same as filtering out weird (in particular invisible) unicode. But it's only an assumption and an estimate.

**Comment by mattiapontonio** [comment]
I have to think more about this but being in the file system I think it must be a GitHub action. If these strings came from a web App it would be different but the point should be to clean content and not allow them to be inserted there. You have to think about it to understand in which languages it is useful to use these characters.

**Comment by schalkneethling** [comment]
@escattone I wonder if this is still something we should be concerned about.

**Comment by escattone** [comment]
@schalkneethling No, I don't think so. If it becomes a problem in the future, we can address it then.
