### ISSUE TITLE
.live-sample-frame is never used for anything

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2911]
Every `<iframe>` live sample gets this class name. But it's never used for anything. Not in SCSS or in any JS code. (as far as I can see).

**Comment by peterbe** [comment]
We should remove that wherever we see it. 

Do you know of any reason *not* to @schalkneethling ?

**Comment by schalkneethling** [comment]
This is one place we would need to update and remove it:
https://github.com/mdn/yari/blob/f3200f1abbd027119ce665cdcda98a949d74b33f/testing/tests/headless.test.js

**Comment by schalkneethling** [comment]
These are the places to remove it:

- /yari/client/src/document/ingredients/examples.tsx
- /yari/kumascript/macros/EmbedGHLiveSample.ejs
- /yari/kumascript/macros/EmbedLiveSample.ejs
- /yari/kumascript/tests/macros/EmbedLiveSample.test.js
- /yari/testing/tests/headless.test.js
