### ISSUE TITLE
Deployer should treat the home page `index.html` exceptionally

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2920]
We usually create S3 keys based on the `index.html` file's parent. E.g. `en-us/docs/web/foo/index.html` becomes, as an S3 key, `en-us/docs/web/foo`
That way we immediately get final URLs that *don't* end in a trailing slash. (We can question whether this is right or good another time; it's how MDN works and has worked for many years)

But the home page is different. A request to `/en-US` should actually be a `301` to `/en-US/`.

**Comment by escattone** [comment]
@peterbe and I discussed this over Slack and Zoom.
- We need to 301 redirect `/en-US` to `/en-US/` in Yari like Django currently does.
- We're **not** going to do this in the deployer. I already have a solution that's implemented in our origin-request Lambda@Edge function.

**Comment by mattiapontonio** [comment]
If a browser in French visits `en-us/` is redirected to `/` in `fr` or in `en`?

**Comment by escattone** [comment]
@mattiapontonio No, the locale in the request is always respected. Only requests for `/` (home page with no locale specified.

**Comment by escattone** [comment]
I'm closing this since I fixed it via the Lambda@Edge function (see #2922).

**Comment by mattiapontonio** [comment]
> I'm closing this since I fixed it via the Lambda@Edge function (see #2922).

Nit
You could [link](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#:~:text=On%20GitHub%2C%20navigate%20to%20the,right%20sidebar%2C%20click%20Linked%20issues.) the issue from the PR so it closes on merge.
