### ISSUE TITLE
Deleted pages and redirects with HTMLHyperlinkElementUtils

### ISSUE THREAD

**Issue by Elchi3** [mdn/yari#2935]
Maybe I'm hitting https://github.com/mdn/yari/issues/2224 but filing a new issue to track this specific issue. (Maybe I screwed up redirects and it has nothing to do with the issue, let me know)

First, https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils is not deleted but it should be.

Second, the following pages act weird (I guess because of strange redirects):

https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/hash
https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/host
https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/href
https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/password
https://developer.mozilla.org/en-US/docs/Web/API/HTMLAnchorElement/pathname

https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/hash
https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/host
https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/href
https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/password
https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/pathname

Desired outcome: All HTMLHyperlinkElementUtils pages redirect to HTMLAnchorElement.

**Comment by Elchi3** [comment]
I tried to move more pages, but the move command did some changes related to this issue then. I put that in https://github.com/mdn/content/pull/2368 and I'd appreciate a look.

**Comment by peterbe** [comment]
@fiji-flo you're the uber-redirect-guru. Can you help with this one?

**Comment by Elchi3** [comment]
I think https://github.com/mdn/content/pull/2368 fixed the cycle redirects already. 

I wonder if the cycle checking could be added to CI? It was a bit of a shame I only noticed that things got wrong after trying to move more pages. So, if the cycle checking the `yarn content move` command does could be added to some validation step that might make sense to avoid more bad redirects?

**Comment by fiji-flo** [comment]
This should be fixed. However this might still happen if a 301 is cached and we reuse a slug. `yarn content move` will put out a warning, but there's nothing preventing it.

**Comment by Elchi3** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils is not yet deleted, but I guess that's https://github.com/mdn/yari/issues/2224 ?

**Comment by fiji-flo** [comment]
Indeed.

**Comment by Elchi3** [comment]
okay cool, closing here then.
