### ISSUE TITLE
Can we drop the className=article on all <article> tags?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2957]
We currently render it out as:
```html
<article class="article">
```
And we have some (S)CSS (e.g. `document/index.scss` and the `client/public/index.html` for prints) that uses `.article`. 
Can we drop the className and just use the tag `<article>`?

**Comment by peterbe** [comment]
@schalkneethling Can you weigh in on this? 

I can imagine we added the `className="article"` (and the CSS) because of the "Kuma transition". But I could be missing something.

**Comment by schalkneethling** [comment]
@peterbe No, it is generally bad practice to attach style directly to an element type such as `article` unless you set very general base styles such as in a reset.

As you can potentially have multiple `article` elements on a page, it is best to target using a class. With that said, I am not confident that `article` is the best of all possible class names 😄

**Comment by mattiapontonio** [comment]
I would like to see the article drawn up a little bit perhaps with a double border and I don't know a gradient that makes it look like newspaper and review the exact same style when listing the articles on the home page or category page.

**Comment by peterbe** [comment]
But why would you ever have more than 1 `<article>`? 
I can totally understand the point if the chosen tagname was something "generic" like `<div>` or `<section>`. 
But `<article>`, `<header>`, and `<footer>` feels like tags you only use once.

**Comment by chrisdavidmills** [comment]
`<article>` refers more to multiple standalone items (like articles of clothing) than blog or newpaper articles, although you can use them for those purposes. You'd use multiple `<article>`s in a situation like a blog summary where the summary for each blog article can go inside an `<article>`.

And `<header>` and `<footer>` are not just for page headers and footers — the meaning is more generic than that. You could define a `<header>` and `<footer>` for each `<article>`...

**Comment by mattiapontonio** [comment]
Let us remember that in CSS you can make selectors of things within things

**Comment by Ryuno-Ki** [comment]
If I recall correctly, an `<article>` could be thought of as the part of a website, that could be shown in an Atom feed.

**Comment by peterbe** [comment]
So if there's a slight chance that we might have `document.querySelectorAll('article').length > 1` it makes sense to have a `class="..."` so we can distinguish which one is the "document/article meat area". But even then, can't you do something like `main article` or `.document-page article` to get the CSS "targetting" right?

It's not critical that we fix this but I think it's worth pausing to question things sometimes. 
It does feel like we're doing things:

```
|<------------ 30cm ---------->|
|<-- 10cm -->|<---- 20cm ---->|
```
where one of them (the 10cm or the 20cm) is redundant.

**Comment by mattiapontonio** [comment]
In my opinion, a good rule of thumb is that if you can't define something with one word, it's not a class.

**Comment by schalkneethling** [comment]
The other thing is, using a class as opposed to a element as a selector avoids the problem off unintended bugs when the element used is changed.

Why would we ever not use `article` 🤷‍♂️ but we might. Perhaps we decide to instead use a `section` element or a `div`, who knows. Thing is, if you use a class as your selector, the underlying element does not matter.

Feels like we can close this one. What do you think @peterbe?

**Comment by peterbe** [comment]
Yep. I think we've justified it. The potential saving of not needing it isn't worth it in comparison to all the other advantages of keeping it.
