### ISSUE TITLE
Support scrolling sidebars

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#2972]
It's common for sidebars to scroll independently of the main document:
* [Stripe](https://stripe.com/docs/keys)
* [GitHub](https://docs.github.com/en/graphql/reference/enums)
* [Microsoft](https://docs.microsoft.com/en-us/cli/azure/cdn/custom-domain?view=azure-cli-latest)

This means users can scroll the main doc without losing the sidebar, and scroll the sidebar without losing where they are in the main document.

MDN doesn't support this, but it would be great if it could.

**Comment by peterbe** [comment]
@schalkneethling Got a feeling for this?

**Comment by schalkneethling** [comment]
@wbamberg Funny you should mention this 😃  I have something in mind that related mostly to BCD tables but, it kinda hinges on the fact that the sidebar has some aspect of what you are suggesting. I will expand on the idea a bit more in Figma and then propose the idea here for further discussion. Thank you for bringing my attention to this @peterbe

**Comment by wbamberg** [comment]
-> https://github.com/mdn/yari/discussions/3330#discussioncomment-530762 \o/

**Comment by schalkneethling** [comment]
This is part of the redesign and tracked elsewhere, closing this one.
