### ISSUE TITLE
Issue with "CSS reference": multiple dead links in {{CSS_Ref}} template

### ISSUE THREAD

**Issue by Alien426** [mdn/yari#2984]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference

#### What information was incorrect, unhelpful, or incomplete?

"&lt;an-plus-b&gt;" https://developer.mozilla.org/en-US/docs/Web/CSS/an-plus-b
"block-overflow" https://developer.mozilla.org/en-US/docs/Web/CSS/block-overflow
"font-feature-settings (@font-face)" https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-feature-settings
"@historical-forms" https://developer.mozilla.org/en-US/docs/Web/CSS/@historical-forms
"inherits (@property)" https://developer.mozilla.org/en-US/docs/Web/CSS/@property/inherits
"initial-value (@property)" https://developer.mozilla.org/en-US/docs/Web/CSS/@property/initial-value
"leader()" https://developer.mozilla.org/en-US/docs/Web/CSS/leader
"line-clamp" https://developer.mozilla.org/en-US/docs/Web/CSS/line-clamp
"max-lines" https://developer.mozilla.org/en-US/docs/Web/CSS/max-lines
"ruby-merge" https://developer.mozilla.org/en-US/docs/Web/CSS/ruby-merge
"selector()" https://developer.mozilla.org/en-US/docs/Web/CSS/selector
"target-counter()" https://developer.mozilla.org/en-US/docs/Web/CSS/target-counter
"target-counters()" https://developer.mozilla.org/en-US/docs/Web/CSS/target-counters
"target-text()" https://developer.mozilla.org/en-US/docs/Web/CSS/target-text

#### Specific section or headline?

Headline "Index".
(I would fix this myself, but I don't know how to find/edit templates.)

#### What did you expect to see?

Content.

#### Did you test this? If so, how?

I clicked the links.
♫ The links are dead.
Affirmative. I poked one it was dead. ♬

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/reference`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/web/css/reference/index.html
* Last commit: https://github.com/mdn/content/commit/2ef7bb784bf1036ad7886b64e6451a68e573a44b
* Document last modified: 2021-01-15T08:25:52.000Z

</details>

**Comment by schalkneethling** [comment]
Had a look at the page referenced in the report. Looks like those are now marked up appropriately. See the screenshot below.

![Screenshot of 404 links showing that a page does not yet exist](https://user-images.githubusercontent.com/10350960/140064459-448796d8-281d-4722-87fc-49c16d9afd90.png)
