### ISSUE TITLE
The dino.svg does not need to be part of React

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2990]
In the document we have this:
```
import { ReactComponent as Dino } from "../assets/dino.svg";
```
See https://github.com/mdn/yari/blob/d1f339096937cd3a8764b4c9d0b03dfee3e6414f/client/src/document/index.tsx#L23

It's used like this:
```
<Dino className="page-content-container loading-document-placeholder" />
```
But the only time that gets used is in the loading screen when the client-side navigation has to XHR load in a new doc. This is rare and definitely not "urgent". I.e. it's never used in the initial render (because it's SSR it doesn't need an XHR effect). 

Can we turn it into a regular image asset instead of being part of the JS bundle?

**Comment by peterbe** [comment]
here's how big it was:
<img width="759" alt="Screen Shot 2021-02-19 at 9 46 32 AM" src="https://user-images.githubusercontent.com/26739/108519321-84e28d00-7297-11eb-8db4-69290824a147.png">

**Comment by schalkneethling** [comment]
We no longer use this one so, this is resolved.
