### ISSUE TITLE
The BCD CSS adds 9.1KB worth of CSS to the main bundle

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#2991]
Making the main CSS bundler smaller and lighter is gold for web performance. Getting rid of 9KB would be a great boost for those clicks from a Google search where the CSS might *not* be hot in the browser cache. 
Also, the BCD table triggers the download of possible 12 extra `.svg` images. That adds a strain on the initial load too. 

Almost always the BCD table is below the fold. It might not be, in a sense, if you link directly to one. [For example](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#browser_compatibility)

But it makes it ripe for genuine lazy loading. 
We're already lazy loading the JS and the XHR (JSON) request. But that lazy loading is triggered on the initial React mount. So basically, it fires immediately after the DOM is loaded. No pause in between.
And because of how it currently works, it's not feasible to lazy load the CSS because the delayed injection of an external CSS URL will cause the rendering to block! 

If we can delay the BCD table till some time after the initial render, we can safely lazy load the external CSS too.

**Comment by peterbe** [comment]
Interesting page to test: http://localhost:3000/en-US/docs/Web/API/IntersectionObserver/disconnect
If you have a sufficiently large screen the BCD table should be above the fold. So in a page like that, which is quite rare, it makes sense to load it asap. 

Another interesting page to test is: http://localhost:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs which has lots of tables. Alls you should see is the JS and the CSS chunk followed by lots of XHR requests for the  `bcd-XX.json` files.

**Comment by caugner** [comment]
Here are the file sizes from the [latest test run](https://github.com/mdn/yari/actions/runs/3586377612/jobs/6035496190#step:6:29):

```
File sizes after gzip:

  169.85 kB  build/static/js/main.c0b70aa0.js
  26.2 kB    build/static/js/966.5446b9cc.chunk.js
  22.64 kB   build/static/css/main.bf941c7f.css
  13 kB      build/static/js/334.05c8cba0.chunk.js
  6.78 kB    build/static/js/768.fb37e8af.chunk.js
  6.31 kB    build/static/js/68.7673ce03.chunk.js
  5.8 kB     build/static/js/browser-compatibility-table.bcbb093f.chunk.js
  5.5 kB     build/static/js/693.a3fc6bc0.chunk.js
  5.27 kB    build/static/js/996.bb7354e2.chunk.js
  4.33 kB    build/static/js/69.3ab23b5c.chunk.js
  4.31 kB    build/static/js/863.c1fb3f32.chunk.js
  4.07 kB    build/static/js/211.fef84fd9.chunk.js
  3.49 kB    build/static/js/717.a71b17a0.chunk.js
  3.48 kB    build/static/js/57.935bd084.chunk.js
  3.45 kB    build/static/js/491.aef40bf7.chunk.js
  3.11 kB    build/static/js/662.36ed4235.chunk.js
  2.2 kB     build/static/css/491.a00de7cf.chunk.css
  1.92 kB    build/static/js/791.427afbae.chunk.js
  1.67 kB    build/static/js/709.6a80be22.chunk.js
  1.6 kB     build/static/css/57.e60c22af.chunk.css
  1.29 kB    build/static/js/837.865ab4b4.chunk.js
  1.15 kB    build/static/css/518.614dbbf1.chunk.css
  902 B      build/static/js/472.f56c823c.chunk.js
  844 B      build/static/js/979.e277a725.chunk.js
  713 B      build/static/css/693.5a91c31c.chunk.css
  654 B      build/static/css/996.feade3fe.chunk.css
  625 B      build/static/css/837.3372dfc1.chunk.css
  625 B      build/static/css/863.76ff1021.chunk.css
  621 B      build/static/css/768.32df508f.chunk.css
  560 B      build/static/js/419.d4e71832.chunk.js
  444 B      build/static/css/211.c4413dff.chunk.css
  296 B      build/static/css/662.631950ad.chunk.css
  196 B      build/static/css/419.d1b5f3c6.chunk.css
  186 B      build/static/js/518.a5b6aabb.chunk.js
  145 B      build/static/css/979.7bf6dfc6.chunk.css
  132 B      build/static/css/472.066d518c.chunk.css
```

The biggest CSS chunks are:

- 22.64 kB   build/static/css/main.bf941c7f.css
- 2.2 kB     build/static/css/491.a00de7cf.chunk.css

And the BCD CSS is part of the `main.css` chunk.

To test the impact of the BCD CSS, I have emptied `client/src/document/ingredients/browser-compatibility-table/*.scss` and here's the result:

```
File sizes after gzip:

  169.85 kB            build/static/js/main.c0b70aa0.js
  26.2 kB              build/static/js/966.5446b9cc.chunk.js
  21.21 kB (-3.18 kB)  build/static/css/main.d3182ee1.css
  13 kB                build/static/js/334.05c8cba0.chunk.js
  6.78 kB              build/static/js/768.fb37e8af.chunk.js
  6.31 kB              build/static/js/68.7673ce03.chunk.js
  5.8 kB               build/static/js/browser-compatibility-table.bcbb093f.chunk.js
  5.5 kB               build/static/js/693.a3fc6bc0.chunk.js
  5.27 kB              build/static/js/996.bb7354e2.chunk.js
  4.33 kB              build/static/js/69.3ab23b5c.chunk.js
  4.31 kB              build/static/js/863.c1fb3f32.chunk.js
  4.07 kB              build/static/js/211.fef84fd9.chunk.js
  3.49 kB              build/static/js/717.a71b17a0.chunk.js
  3.48 kB              build/static/js/57.935bd084.chunk.js
  3.45 kB              build/static/js/491.aef40bf7.chunk.js
  3.11 kB              build/static/js/662.36ed4235.chunk.js
  2.2 kB               build/static/css/491.a00de7cf.chunk.css
  1.92 kB              build/static/js/791.427afbae.chunk.js
  1.67 kB              build/static/js/709.6a80be22.chunk.js
  1.6 kB               build/static/css/57.e60c22af.chunk.css
  1.29 kB              build/static/js/837.865ab4b4.chunk.js
  1.15 kB              build/static/css/518.614dbbf1.chunk.css
  902 B                build/static/js/472.f56c823c.chunk.js
  844 B                build/static/js/979.e277a725.chunk.js
  713 B                build/static/css/693.5a91c31c.chunk.css
  654 B                build/static/css/996.feade3fe.chunk.css
  625 B                build/static/css/837.3372dfc1.chunk.css
  625 B                build/static/css/863.76ff1021.chunk.css
  621 B                build/static/css/768.32df508f.chunk.css
  560 B                build/static/js/419.d4e71832.chunk.js
  444 B                build/static/css/211.c4413dff.chunk.css
  296 B                build/static/css/662.631950ad.chunk.css
  196 B                build/static/css/419.d1b5f3c6.chunk.css
  186 B                build/static/js/518.a5b6aabb.chunk.js
  145 B                build/static/css/979.7bf6dfc6.chunk.css
  132 B                build/static/css/472.066d518c.chunk.css
```

This means the BCD CSS is responsible for 3.18 kB (compressed).

Given that [the smallest `bcd.json`](https://developer.mozilla.org/zh-CN/docs/mozilla/add-ons/webextensions/api/search/search/bcd.json) is 2 kB (compressed) and most pages (25 have a BCD table, I find this negligible, so I'll go ahead and close this issue as "won't fix".
