### ISSUE TITLE
Consolidate redirect target validation

### ISSUE THREAD

**Issue by fiji-flo** [mdn/yari#2993]
Currently we don't take into account:

1. a redirect might point to another redirect in the translated content repo
2. a redirect might point to an archived page

We should put assertions in place that:

- we check for 1. in the `validate-redirects --strict`
- have / enforce that redirects to an archived page belong into the archived content repo

**Comment by schalkneethling** [comment]
@fiji-flo This still on your to-do, or is it done?

**Comment by fiji-flo** [comment]
`validate-redirects --strict` takes care of these cases. We're still lacking the functionality to shortcut redirects from translated content back into `/en-US/`. So let's keep this open.

`Skipping: non ja locale: /ja/docs/Web/API/GlobalFetch	/en-US/docs/Web/API/WindowOrWorkerGlobalScope`

That's the scenario we should still address.

**Comment by caugner** [comment]
Here's the current output:

```console
% yarn tool validate-redirects --strict                                                                                          1 ↵
yarn run v1.22.19
$ ts-node tool/cli.ts validate-redirects --strict
Skipping: non en-us locale: /en-US/docs/Secciones_y_contornos_de_un_documento_HTML5	/es/docs/Sections_and_Outlines_of_an_HTML5_document
Skipping: non en-us locale: /en-US/docs/Web/API/WebGL_API/Getting_started_with_WebGL/Commencer_avec_le_WebGL	/fr/docs/Web/API/WebGL_API/Tutorial/Commencer_avec_WebGL
Skipping: non en-us locale: /en-US/docs/Web/API/WebGL_API/Tutorial/Getting_started_with_WebGL/Commencer_avec_le_WebGL	/fr/docs/Web/API/WebGL_API/Tutorial/Commencer_avec_WebGL
Skipping: non en-us locale: /en-US/docs/Web/WebGL/Getting_started_with_WebGL/Commencer_avec_le_WebGL	/fr/docs/Web/API/WebGL_API/Tutorial/Commencer_avec_WebGL
Skipping: non en-us locale: /en-US/docs/WebGL/Getting_started_with_WebGL/Commencer_avec_le_WebGL	/fr/docs/Web/API/WebGL_API/Tutorial/Commencer_avec_WebGL
Skipping: non en-us locale: /en-US/docs/video	/es/docs/Web/HTML/Elemento/video
Skipping: non en-us locale: /en-US/docs/zh-n/JavaScript/Reference/Global_Objects/String/quote	/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/String/quote
info: ✓ redirects for en-us looking good!
Skipping: non es locale: /es/docs/Web/JavaScript/Guide/Obsolete_Pages/The_Employee_Example	/en-US/docs/Web/JavaScript/Guide/Details_of_the_Object_Model
info: ✓ redirects for es looking good!
info: ✓ redirects for fr looking good!
info: ✓ redirects for ja looking good!
info: ✓ redirects for ko looking good!
info: ✓ redirects for pt-br looking good!
info: ✓ redirects for ru looking good!
info: ✓ redirects for zh-cn looking good!
Skipping: non zh-tw locale: /zh-TW/docs/Web/API/Detecting_device_orientation	/en-US/docs/Web/Events/Detecting_device_orientation
Skipping: non zh-tw locale: /zh-TW/docs/WebAPI/Detecting_device_orientation	/en-US/docs/Web/Events/Detecting_device_orientation
info: ✓ redirects for zh-tw looking good!
info: 🍾 All is well in the world of redirects 🥂
✨  Done in 7.74s.
```

> Skipping: non zh-tw locale: /zh-TW/docs/Web/API/Detecting_device_orientation	/en-US/docs/Web/Events/Detecting_device_orientation

In this case, we can remove the redirect, because now we check if the English page exists (following redirects):

https://developer.mozilla.org/fr/docs/Web/API/Detecting_device_orientation

And if we resolve https://github.com/mdn/yari/issues/2528#issuecomment-1331452498, we would even suggest the target page in the current locale, if it exists.

**Comment by caugner** [comment]
> 2\. a redirect might point to an archived page

Since `archived.txt` was removed in https://github.com/mdn/yari/pull/4232, I guess this is no longer relevant.
