### ISSUE TITLE
Search returns nothing for known topic  ("?.")

### ISSUE THREAD

**Issue by chrisdavidmills** [mdn/yari#3074]
@tshinnic commented on [Fri Aug 07 2020](https://github.com/mdn/sprints/issues/3583)

# Request type

- [ ] Please close this issue, I accidentally submitted it without adding any details
- [x] New documentation
- [ ] Correction or update

# Details

So couldn't remember the magic keyword for new Javascript operator/syntax, though using it. So entered "?." into MDN search. Nothing. Wandered around web and saw 'chaining'. Enter that and see link to topic "Optional chaining (?.)". 

Is it not possible to have search aliases for topics? As search is consistently the weakest feature of MDN documentation, I wouldn't exclude that.

**Comment by Ryuno-Ki** [comment]
Similar to #3070 and https://github.com/mdn/yari/issues/3004#issuecomment-783454139 I think.

Meaning, it gets likely reduced to `""` (which then obviously cannot find anything).
