### ISSUE TITLE
Some links in 'Related topics' leads to 404

### ISSUE THREAD

**Issue by simonmysun** [mdn/yari#3078]
Hi, I found a bug and couldn't find the cause:

e.g. in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp in the related posts there is a link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects//RegExp which should be itself with single slash instead of double slash. It leads to a 301 to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects_RegExp and then turn out to be a 404 page. Other similar pages have the same issue. 

![Screenshot_2021-02-28_00-26-40](https://user-images.githubusercontent.com/3358854/109403216-f4bddb00-795b-11eb-8eac-09e9c4f97d67.png)

![image](https://user-images.githubusercontent.com/3358854/109403293-9c3b0d80-795c-11eb-8f30-0c7efe84775e.png)

I tried run yari locally the double slash URL also appears but does not get 301 and can render the correct content. 

![image](https://user-images.githubusercontent.com/3358854/109403303-abba5680-795c-11eb-87c9-448a25f8c4c1.png)

Though the contented is shown correctly, I believe there are some problems regarding the url and the redirect. Please have a look.

**Comment by peterbe** [comment]
Thanks @simonmysun 
That page uses the [`JSRef` macro to produce the sidebar](https://github.com/mdn/content/blob/1f101eec408839d38a3878d6913b4f37e4b58596/files/en-us/web/javascript/reference/global_objects/regexp/index.html#L11).
The file `kumascript/macros/JSRef.ejs` does something wrong with the slashes. 
It produces:
```html
<a href="/en-US/docs/Web/JavaScript/Reference/Global_Objects//RegExp"><code>RegExp</code></a>
```
which has a double `//` when it shouldn't. Do you think you can start Yari locally to and edit JSRef.ejs to see if you can fix it?

**Comment by chrisdavidmills** [comment]
We had a duplicate over on the content repo, and I opened a PR that I think fixes this earlier today: https://github.com/mdn/yari/pull/3085.

So we could close this, but I'm happy to wait until the PR is merged ;-)

**Comment by tshinnic** [comment]
Please see comment https://github.com/mdn/content/issues/2755#issuecomment-787901462

**Comment by peterbe** [comment]
Fixed in `main` now. We'll push out a prod build in a matter of hours.
