### ISSUE TITLE
Watch or subscribe to a page or set of pages?

### ISSUE THREAD

**Issue by Schweinepriester** [mdn/yari#3095]
Apologies if this has been asked before/is already known/available/in development, but I've tried searching for it using e.g. watch, subscribe, follow, etc. and didnt find it. Feel free to close if thats the case.

Is it still possible to watch a page (and all sub-articles) like <https://developer.mozilla.org/en-US/docs/MDN/Tools/Page_watching> describes?
If not, is that planned to come back?
Email was convenient for me, but if sending mails is to cumbersome, RSS-feeds would be great as well.
I'd really like some form of notifications.

My use case was to watch <https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases> and all sub-articles to be always informed about new changes for all releases (including those where the pages were still to be created).

**Comment by Ryuno-Ki** [comment]
The closest I can recall is https://github.com/mdn/content/issues/1877#issuecomment-769947104 - but that would make you watch all changes (which is likely not what you want).

Instead, you'd be interested in changes on a certain file :thinking:

**Comment by Schweinepriester** [comment]
> Instead, you'd be interested in changes on a certain file 🤔

And sub-files even - I've only ever watched <https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases>, implying a hierarchy to the individual changelogs. ~~Not sure if that is still given, because of ...~~ Looks like there's still a hierarchy:

https://github.com/mdn/content/blob/8da9351322bca5d3d41488cd1b8b3f2f4aaf078e/files/en-us/mozilla/firefox/releases/index.html#L14

**Comment by peterbe** [comment]
> If not, is that planned to come back?

No. It most likely will not. The content is a git repo now. 

I don't know if it's feasible but when we build, we do have access to the complete git history of every file. So you could, at every level, create a `rss.xml` file based on...:
```
rss_feed = []
for doc in git_history(filter_startswith=this_doc.url).order_by('modified'):
    rss_feed.add(doc)
dump_to_disk(rss_feed, './rss.xml')
```
Then, you'd be able to RSS subscribe to any tree. Just type in a URL, chop off the last part of the URL and add `/rss.xml` :)

**Comment by Schweinepriester** [comment]
I've found one solution which is probably good enough:
- https://stackoverflow.com/questions/9732779/how-to-watch-only-a-directory-in-a-github-repository/25315476#25315476

  > GitHub provides RSS feeds for both directories and files
- https://stackoverflow.com/questions/7353538/setting-up-a-github-commit-rss-feed

Therefore subscribing to

https://github.com/mdn/content/commits/main/files/en-us/mozilla/firefox/releases
=> https://github.com/mdn/content/commits/main/files/en-us/mozilla/firefox/releases.atom

should cover what I want.

**Comment by peterbe** [comment]
I still think there might be value in MDN having a newsletter that you can customize. One where you can go into your account and pick specific pages or pages + sub-tree. Perhaps even something specific like "Only notify me new pages"

**Comment by Schweinepriester** [comment]
Uhhh not so sure about

> github-actions bot closed this as completed

🤔

**Comment by caugner** [comment]
With [MDN Plus](https://hacks.mozilla.org/2022/03/introducing-mdn-plus-make-mdn-your-own/), it is now (since March 2022) possible to watch pages and be notified about (significant) changes as well as BCD updates. 🎉
