### ISSUE TITLE
Sidebar is broken for the API/Element page

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#3119]
Reported in Matrix.

See https://developer.mozilla.org/en-US/docs/Web/API/Element: in the sidebar, pages are often (not always) listed twice:

********

<img width="271" alt="Screen Shot 2021-03-03 at 5 03 55 PM" src="https://user-images.githubusercontent.com/432915/109894510-79517780-7c42-11eb-9876-497b092736c9.png">

********

The sidebar here is built using the APIRef macro, which fetches the list of pages to show using the `subpagesExpand` API: https://github.com/mdn/yari/blob/main/kumascript/macros/APIRef.ejs#L52. The macro hasn't changed in any suspicious way recently, so perhaps Yari is double-counting some pages here for some reason?

**Comment by Elchi3** [comment]
Sigh. Sorry about this. See https://github.com/mdn/yari/pull/3131
