### ISSUE TITLE
Translated broken links might be saved by linking to en-US instead

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3134]
I think we should do the same with regular `<a href>` links too. E.g. 

```html
<p>Kolla in denna länken här <a href="/sv-SE/docs/Web/CSS">CSS</a>.</p>
```
should automatically become:
```html
<p>Kolla in denna länken här <a 
  title="Page only currently available in English"
  href="/en-US/docs/Web/CSS">CSS (en-US)</a>.</p>
```

But that can be done as a separate thing.

_Originally posted by @peterbe in https://github.com/mdn/yari/issues/3053#issuecomment-789878223_

**Comment by peterbe** [comment]
This is blocked by https://github.com/mdn/yari/pull/3133

**Comment by schalkneethling** [comment]
Looking at https://developer.mozilla.org/de/docs/Web/CSS/Reference and https://github.com/mdn/yari/pull/3133 it looks like we got this covered.
