### ISSUE TITLE
< Dark Theme > Pls provide dark theme option

### ISSUE THREAD

**Issue by himanshu-web** [mdn/yari#3143]
I love documentation but it is so hard to read the document for an hour and two because of the light theme it affects on eyes so pls provide a dark theme option on the website. thanks and love to all

**Comment by Ryuno-Ki** [comment]
Issues are meant for actionable items.
See https://github.com/mdn/yari/discussions/2539 for the discussion.

**Comment by chrisdavidmills** [comment]
Closing this in favor of the existing discussion. Please add your thoughts there @himanshu-web ; your contribution is very welcome.
