### ISSUE TITLE
[Feature Request] Generate clickable anchor tags for HTML attributes

### ISSUE THREAD

**Issue by KartikSoneji** [mdn/yari#3148]
Anchor tags allow reference links to target a particular section of a document easily.  
The `htmlattrdef` already generates `id`s, so wrapping in them an `<a>` tag will make them clickable, increasing ease of use.

https://github.com/mdn/yari/blob/c878b4c6adae1972d424ba5dec2611fff5796bad/kumascript/macros/htmlattrdef.ejs#L1-L2

For example:
```ejs
<a href="#<%=$0%>"><strong id="attr-<%=$0%>"><code><%=$0%></code></strong></a>
```

**Comment by peterbe** [comment]
I think I can see how that could be useful. For example, to link a friend to the `dns-prefetch` section I first have to use http://localhost:3000/en-US/docs/Web/HTML/Attributes/rel#values and then say "Scroll down to `dns-prefetch`".
