### ISSUE TITLE
Add HTTP header to opt out of "interest cohort" training 

### ISSUE THREAD

**Issue by dmarti** [mdn/yari#3159]
At least one commonly used web browser is planning to deploy a system in which users are classified into "interest cohorts" based on web history. (Federated Learning of Cohorts, or FLoC). This is widely considered a risk to user privacy. Background information is available from

 * [EFF](https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea)
 
 * [Gizmodo](https://gizmodo.com/google-continues-to-promise-its-bid-to-end-cookies-isnt-1846124668)

If MDN visits are used to classify users into a "web developer" cohort, then unpredictable and possibly adverse effects will ensue. Some MDN users might be classified as web developers, and therefore good possible tenants, by landlords. Others might be classified by their current employers as people seeking new jobs as web developers, and suffer consequences at work. Still other users might be classified as web people and placed at risk for "spear phishing" attacks against web sites.

Because the training of cohorts has not been independently evaluated for privacy or security, and because cohort training is currently opt-out rather than opt-in, please add the opt-out HTTP header to MDN.

```
Permissions-Policy: interest-cohort=()
```

More info on opting out: https://github.com/WICG/floc#opting-out-of-computation

**Comment by peterbe** [comment]
Hi Don! Thanks for filing. 

@escattone @chrisdavidmills @fiji-flo This one's non-trivial. I haven't had a chance to read those lengthy articles yet. 
Technically it would be as simple as add the `Cache-Control` header to the Deployer, but it would be nice to get some buy-in from other privacy experts within Mozilla to back up Don's claims (i.e. that MDN *should* opt-out). Know anybody good to call in for advice?

**Comment by dmarti** [comment]
@arthuredelstein is also knowledgeable about browser privacy and may be able to help advise.

**Comment by englehardt** [comment]
Since FLoC is only going through origin trials in Chrome, I think it's premature to add a header that interacts with the feature to our web properties. We should definitely revisit this if Chrome decides to move FLoC beyond an experiment.

**Comment by dmarti** [comment]
The FLoC origin trial in Google Chrome is scheduled to begin some time in March 2021 (in Chrome 89). Only sites that are enrolled in the origin trial will be able to call the FLoC API.

 All sites that are detected to have "ad-related resources" (items that would be blocked by EasyList) will be included in the training, unless explicitly opted out.

If MDN does not have any third-party resource that would be blocked by EasyList, it should not be included in training during the origin trial. However, if it turns out that an ad injected into a page by a (malicious) Chrome extension can result in the page being detected as an "ad-related" page, those ads might also expose users to FLoC training on MDN.

**Comment by schalkneethling** [comment]
@englehardt @dmarti Has this gone beyond origin trials? Should we revisit this issue and possibly implement the permission policy header? Thank you

**Comment by dmarti** [comment]
@schalkneethling The first origin trial in Google Chrome has come to an end. There may be a second trial coming soon, but so far we don't know much about how FLoC will be changed. It is likely that FLoC training will only happen on pages on which the FLoC API is called, which might make the opt-out header unnecessary, but I still don't know how a script injected into a page by a browser extension might affect this. ( https://github.com/WICG/floc/issues/33#issuecomment-802248998 )

More info: https://digiday.com/marketing/google-switch-floc-cookie-replacement-fingerprinting-potential/

**Comment by schalkneethling** [comment]
Thank you for the feedback @dmarti, much appreciated.

**Comment by caugner** [comment]
[FLoC](https://github.com/WICG/floc) seems to have been replaced by the [Topics API](https://github.com/patcg-individual-drafts/topics), but I don't think it makes sense to keep tracking this here in an open yari issue.

Once this becomes significantly more prominent and therefore relevant again, we should [discuss](https://github.com/orgs/mdn/discussions) this.
