### ISSUE TITLE
Deal with "No BCD data" more gracefully?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3168]
Look at http://localhost:3000/en-US/docs/Web/API/DeprecationReportBody#_flaws for example:
<img width="707" alt="Screen Shot 2021-03-09 at 8 55 41 AM" src="https://user-images.githubusercontent.com/26739/110481136-3c0f3e80-80b5-11eb-83b9-8abf7803814b.png">

[In the raw content you'll find this](https://github.com/mdn/content/blob/39a29a5c88db77f82bb2b68273e3bf5f653df622/files/en-us/web/api/deprecationreportbody/index.html#L99-L101):
```
<h2 id="Browser_compatibility">Browser compatibility</h2>

<p>{{Compat("api.DeprecationReportBody")}}</p>
```

But because `api.DeprecationReportBody` is not recognized by the BCD data, it all kinda fails. 
Because of the way Yari builder works, it also just ditches the whole "Browser compatibility" section. It might not have been the best design but it *kinda* makes sense. 

The question is; should we deal with this better? More proactively? 
For example, we could so some graceful error message that at least tells the reader that we *tried*. E.g. 

```html
<h2>Browser compatibility</h2>

<p class="bcd-warning">
  Sorry. The BCD data is currently not available for <code>foo.bar</code>.<br/>
  Perhaps you want to contribute. Click here to file an issue on the browser-compat repo.
</p>
```
(extremely rough example but hopefully demonstrates the intent)

**Comment by peterbe** [comment]
What do you think @ddbeck @Elchi3 @chrisdavidmills ?

**Comment by Elchi3** [comment]
We previously had a call for contribution in the content itself (but hidden). See https://github.com/mdn/content/issues/2228

I think it would be better to do what you describe here.

**Comment by chrisdavidmills** [comment]
I also think that @peterbe 's suggestion for handling this is a good one. Question — should we make the CTA ask them to submit a PR to add the data, or submit an issue if they just want to report it? Or is that too complicated?

**Comment by ddbeck** [comment]
A failure like this doesn't necessarily mean that there's no data. Possible failure modes:

- The author used the wrong identifier in the macro (e.g., a typo)
- BCD hasn't caught up to the content (e.g., a page author opens PRs on mdn/content and mdn/browser-content-repo and the content PR gets merged while the compat changes are still waiting for review)
- Yari hasn't caught up to BCD (e.g., the data exists in the latest release of BCD, but that release hasn't made it into Yari yet)
- BCD doesn't have data (e.g., `api.SomeAPI` is the right data, but there's no data)

Maybe we need a flow chart to diagnose problems with the compat macro. 😬

**Comment by ddbeck** [comment]
Yeah, I suppose the second and third cases I mention would be transient and self-resolving. If we ignore those, there's at least a couple of ways we might approach this. One would be a two-pronged CTA:

> No data found for `api.SomeIdentifier`.
> Check the feature name. If the name is incorrect, open an issue or PR to change it on mdn/content. If name is incorrect, open an issue or PR to update the data on mdn/browser-compat-data.

Alternatively, we could make it one side's problem exclusively:

> No data found for `api.SomeIdentifier`.
> Submit an issue to mdn/content

And then the content repo can relocate data issues to the correct repo.

**Comment by peterbe** [comment]
I think we already had a "solution" for when this happens. At some point we starting skipping the section rather than "letting it be broken". It looks like this:

<img width="1035" alt="Screen Shot 2021-03-15 at 10 56 46 AM" src="https://user-images.githubusercontent.com/26739/111173565-24d0c500-857d-11eb-8122-de6977262440.png">

It's incorrectly still doing an XHR lookup query which I'll deal with but on the surface, I think it's a good start. 

@ddbeck Can you think up a good second sentence to put into that message about it potentially being a bug in the content rather than mdn/browser-compat-data?
Or can you perhaps wordsmith me a complete paragraph to put for the whole thing? Then I can make sure your whole sentence appears and stuff.
