### ISSUE TITLE
WebAssemblySidebar.ejs should use smartLink()

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3206]
E.g. https://developer.mozilla.org/es/docs/WebAssembly
Many of the links in the sidebar, under "Tutorials", will 404 but could easily be replaced at build-time with the `en-US` equivalent. 
We just need to change these lines: https://github.com/mdn/yari/blob/6d3e84d67172959dea95650a815fc58f7ed4d818/kumascript/macros/WebAssemblySidebar.ejs#L31-L39
to do something like:
```diff
-<a href="<%=baseURL%>/Concepts"><%=text['WebAssembly_concepts']%></a>
+smartLink(baseURL + '/Concepts', null, text['WebAssembly_concepts'], baseURL)
```
...plus the relevant changes for EJS.

**Comment by mirunacurtean** [comment]
@wbamberg Perhaps due to the translation changes, this no longer occurs. Can you confirm or is there another methods you would like to be used in this case? 

https://github.com/user-attachments/assets/d29baf81-1bcc-45e9-be6d-7db2258fd5bd

**Comment by caugner** [comment]
This issue has become obsolete with our new [rari](https://github.com/mdn/rari) build system.
