### ISSUE TITLE
Don't run scheduled workflows on forks

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/yari#3229]
I've forked this repo and received daily updates about failed actions on my repository (namely, pushing to production failed :))
A quick solution for this is to disable the actions on the fork.
I think it would be useful to add a quick note about this in the Readme.

I'll suggest a PR later.

**Comment by peterbe** [comment]
Good point! I also think it's a waste of electricity that every individual's fork would be running CI. 

I'm not entirely sure how to get to *your* Action runs. (Or mine, or Ryan's, etc.)
I think what we should do is make sure the cronjobs only run if the repository owner is `mdn`.

**Comment by peterbe** [comment]
What I don't yet understand is; how do you even see what Actions are running in a fork? On forks, you don't even have the "Actions" tab. If I take [the `mdn` on's URL](https://github.com/mdn/yari/actions) and just replace the `mdn` with `SphinxKnight` I get a 404: https://github.com/SphinxKnight/yari/actions

From what I can gather, people will have to manually click into their "Settings" (on their fork) and disable Actions. Gross. https://github.community/t/stop-github-actions-running-on-a-fork/17965 Who's going to read that?
Let's see about disabling all scheduled workflows unless their the main repo.

**Comment by peterbe** [comment]
@SphinxKnight I'm actually very confused now. 
What Actions do you have in https://github.com/SphinxKnight/yari ?
What are your "Actions" setting set to? I.e. on your https://github.com/SphinxKnight/yari/settings/actions

Does anybody else get notifications about failed production builds from Yari that isn't from running inside `mdn/yari`?
@escattone @fiji-flo

**Comment by SphinxKnight** [comment]
A screenshot might be worth a 1000words so here goes: 
![image](https://user-images.githubusercontent.com/2413436/111177946-fd90ec80-85aa-11eb-95e3-a99a80f1441e.png)

(I disabled them via the settings this morning (UTC+1))

**Comment by escattone** [comment]
@peterbe I just went through my forks and saw that I had not yet disabled Actions on all of them (so I did that).

**Comment by SphinxKnight** [comment]
Closed as per #3245 if I understand correctly.
