### ISSUE TITLE
Live samples should have a border

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#3260]
Looking at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#examples, it's hard to see where the page content ends and the example output starts:

********

<img width="856" alt="Screen Shot 2021-03-16 at 4 12 46 PM" src="https://user-images.githubusercontent.com/432915/111391762-8030af00-8672-11eb-8ee3-9cade2069d8e.png">

********

I think it would help if live sample iframes got a border, like (IDK I am not a designer):

********

<img width="813" alt="Screen Shot 2021-03-16 at 4 14 02 PM" src="https://user-images.githubusercontent.com/432915/111391846-a48c8b80-8672-11eb-8fce-8ed4bd47f9ac.png">

********

**Comment by escattone** [comment]
cc @schalkneethling @peterbe

**Comment by peterbe** [comment]
@schalkneethling I think this is an excellent example of using `style="..."` attributes directly in the KS macro. Wanna take this one?
