### ISSUE TITLE
Issue with "From object to iframe — other embedding technologi…": …

### ISSUE THREAD

**Issue by andrewjlawson30** [mdn/yari#3278]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies

#### What information was incorrect, unhelpful, or incomplete?

I am raising the under-noted issue for information in case it requires resolution. Apologies if I have done so mistakingly or if I have misunderstood the intended output from the example I refer to.

When trying the quick example under the security concerns section to demonstrate that the MDN Glossary page would not show in an <iframe>, I expected no content to show in the iframe of the browser but instead, I could view all of the content of the MDN Glossary page in the iframe section. I tried this on both Chrome and Firefox browsers with the same result in both.

#### Specific section or headline?

As stated this was under the Security concerns section of the page entitled "From object to iframe - other embedding technologies"

#### What did you expect to see?

I expected to see no content in the iframe section of the browser due to server restrictions/coding and that these restrictions would be reflected in the console section of the browser's developer tools.

#### Did you test this? If so, how?

Tried exercise several times in different browsers with the same results each time.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/html/multimedia_and_embedding/other_embedding_technologies`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies
* GitHub URL: https://github.com/mdn/content/blob/master/files/en-us/learn/html/multimedia_and_embedding/other_embedding_technologies/index.html
* Document last modified: 2021-01-22T11:51:09.000Z

</details>

**Comment by peterbe** [comment]
Can some please summarize what the problem is here?

**Comment by chrisdavidmills** [comment]
I'm sorry, I misread this, and it turns out it is about content after all ;-)

The behavior of the iframe example is different now to how it was when the article was first written, but the effect is still the same. I've updated the wording, and I think this can be closed now; see https://github.com/mdn/content/commit/9e18a29da5ea7868959189d327309c4ad1e581bb
