### ISSUE TITLE
Get rid of 'pre.language-*`

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3279]
We have a lot of CSS in the main bundle just for `pre.language-*`. 
In fact, look at the first 46 lines of https://gist.github.com/peterbe/735c93ff7b16eaefd463d36fb2a5147a which is a Prettier formatting of today's main CSS bundle. 

We don't use `class=language-*` anywhere in the core Yari product. If you should be using `class="brush: *` instead. 

The `language-*` is something you get from Markdown I think. Fenched code snippets with a block becomes `<pre class="language-javascript">` or something like that. 

However, we have a lot of cases where the `language-*` still comes up in our HTML. On https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML for example, [source](https://github.com/mdn/content/blob/9e18a29da5ea7868959189d327309c4ad1e581bb/files/en-us/learn/accessibility/html/index.html#L82) has this:
```html
<pre class="brush: html example-good line-numbers language-html">&lt;h1&gt;My heading&lt;/h1&gt;
&lt;p&gt;This is the first section of my document.&lt;/p&gt;
...
```

In this case, the `language-html` is actually preventing the `example-good` to work. 

I think we should remove all the CSS that precludes to `language-*` from the SCSS. And any HTML that's still in the raw HTML sources should get cleaned up.

**Comment by peterbe** [comment]
@schalkneethling Is this something we have in minimalist or in yari?

**Comment by peterbe** [comment]
By the way, compare http://localhost:3000/en-US/docs/Learn/Accessibility/HTML with https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML
This is what happens when you remove the `language-*` stuff:
<img width="1235" alt="Screen Shot 2021-03-18 at 11 25 13 AM" src="https://user-images.githubusercontent.com/26739/111651692-d588cf80-87dc-11eb-8b98-0b2899a485d9.png">

**Comment by schalkneethling** [comment]
> @schalkneethling Is this something we have in minimalist or in yari?

Let me double-check.

**Comment by peterbe** [comment]
I just don't understand where it could come from:
```
MOZILLA/MDN/mdn-minimalist  main ✔
▶ rg 'language-' | rg scss
sass/atoms/_primsjs.scss:.language-css .token.string,
```

```
▶ rg 'language-' | rg scss
client/src/document/molecules/_breadcrumb-locale-container.scss:  .language-toggle {
client/src/document/molecules/_breadcrumb-locale-container.scss:  .language-toggle:only-child {
client/src/site-search/search-results.scss:.language-options,
client/src/site-search/search-results.scss:  .language-option-list,
client/src/ui/molecules/language-menu/index.scss:.language-menu {
client/src/ui/molecules/language-toggle/index.scss:ul.language-toggle {
client/src/ui/molecules/language-toggle/index.scss:  .language-icon {
client/src/ui/molecules/language-toggle/index.scss:    .language-icon {
```

**Comment by schalkneethling** [comment]
@peterbe there is this one minimalist https://github.com/mdn/mdn-minimalist/blob/2198bb250990b847c5eccd81b505117b56a295f3/sass/atoms/_primsjs.scss

That is to override some colors in Prismjs to improve the a11y of the colors used. I doubt that is what you are referring to her so, perhaps all the CSS you are seeing comes directly from Prismjs' stylesheet?

**Comment by peterbe** [comment]
Yeah, I see it now. It's in `/node_modules/prismjs/themes/prism.css`
I'll investigate what if any new actually need from `prism/themes/*.css` and how it coincides with our own overrides.
