### ISSUE TITLE
Archived banner is busted in the new design

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3286]
Archived pages don't have the new design. I.e. they have the breadcrumb *below* the document header. 
<img width="1504" alt="Screen Shot 2021-03-19 at 1 12 20 PM" src="https://user-images.githubusercontent.com/26739/111817733-bf4e4280-88b4-11eb-9a78-a1b466691158.png">

In the new design, where the breadcrumb is *above* the document header it looks like this:
<img width="1502" alt="Screen Shot 2021-03-19 at 1 13 48 PM" src="https://user-images.githubusercontent.com/26739/111817905-f45a9500-88b4-11eb-90b8-152427fe2028.png">

**Comment by peterbe** [comment]
I see this is triaged as a p2. We might want to reconsider that. @chrisdavidmills and @escattone are talking about entirely deleting the archived pages. I.e. no more `isArchived` in Yari and these pages would disappear from S3.

**Comment by escattone** [comment]
@peterbe Yes, good point! I don't think we should work on this. We're going to stop displaying ALL archived pages by June 30th.
