### ISSUE TITLE
KS & CSS - Replacing titles of notes/warning/etc.. with correct semantic html/css

### ISSUE THREAD

**Issue by tristantheb** [mdn/yari#3290]
**Observed:**
In many blocks whether in Kumascript or in CSS, it is written the use of title `<h3>` and `<h4>` thus creating the titles with the appropriate icons.

But this does not so much respect the structuring of an HTML page by creating a level 4 title directly under the page title (example using `{{SeeCompatTable}}`).

![Push API Exemple](https://i.imgur.com/TW8k2zY.png)

![Push API Exemple Code](https://i.imgur.com/CVtW6dj.png)

**Expected:**
Replace this use of headings with a CSS class that would be applied to a `<p>` (e.g. p.cardTitle?) which would allow the creation of clean HTML notes with the use of icons that Kuma (and _notecards.scss) gave, while gradually abandoning the Kuma scripts (I'm trying to replace the scripts with HTML in new translations for everything that uses the Inline / Header / Ref / Glossary scripts to prepare for Kuma deprecations)

And at the same time, apply this new class to the existing Kuma scripts in order to get the basic structure of the page back to the level of the headers arrangement.

```diff
# Exemple of change for _notecards.scss:

@@ Line: 20 @@
-  h3,
-  h4 {
+ .cardTitle {

@@ Line: 42 @@
-  h3,
-  h4,
+  .cardTitle,
  &.inline {
    &::before {
```

***My question :*** Is this kind of thing possible?

**Comment by peterbe** [comment]
@schalkneethling Can you triage this one?
I for one would welcome something as simple as:
```html
<div class="notecard ...">
  <p class="title">Note!</p>
  <p>Bla bla</p>
</div>
```

which can easily be turned into something as visually attention-grabbing as a `h4` there.

Besides, why can't it just be:

```html
<div class="notecard ...">
  <p><b>Note!</b></p>
  <p>Bla bla</p>
</div>
```
which'll become, hopefully, easier to transition to Markdown with since you can use `**` instead of having to rely on setting a `class=`.

**Comment by tristantheb** [comment]
I really like the idea! :D At least it also prepares the conversion to MarkDown

I also notice in another time that it is difficult to replace inline tags like "ReadyOnlyInline", "Deprecated_Inline", "Experimental_Inline" etc. due to the use in the HTML code of raw SVG when converting KS to HTML.

For example:
```HTML
<svg class="icon experimental" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg" role="img">
    <title>This is an experimental API that should not be used in production code.</title>
    <path d="M90.72 82.34c4.4 7 1.29 12.66-7 12.66H16.25C8 95 4.88 89.31 9.28 82.34l29.47-46.46V12.5H35A3.75 3.75 0 0135 5h30a3.75 3.75 0 010 7.5h-3.75v23.38zM45.08 39.86L29.14 65h41.72L54.92 39.86l-1.17-1.81V12.5h-7.5v25.55z"></path>
</svg>
```

As well as changing the old titles to bold text, which seems to be a better solution, maybe move the SVG icons to .svg files? And then call them up in the html?

For example:
```HTML
<img src="/icons/experimental.svg" alt="An icon of a blue Erlenmeyer flask indicating that the item is experimental" title="This is an experimental API that should not be used in production code.">
```

```MD
![An icon of a blue Erlenmeyer flask indicating that the item is experimental]("/icons/experimental.svg", "This is an experimental API that should not be used in production code.")
```

**Comment by schalkneethling** [comment]
We have simplified this as part of the redesign and so, this will no longer be an issue. The actual implementation of the change is tracked elsewhere so, I will close this one.
