### ISSUE TITLE
Is anybody interested in the 'Wiki' GA event?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3299]
In the last month, we've recorded roughly 1M events when people open and hover over links in the top navbar

Its category is called `Wiki` which in itself drives the point a bit about this issue
https://analytics.google.com/analytics/web/#/report/content-event-overview/a36116321w64965862p66726481/

Is anybody interested in this statistic? 
Any plans to analyze it? 
Can we delete the code if nobody's going to bother analyzing it?

**Comment by schalkneethling** [comment]
Yeah, my vote would be to remove the code that send those pings.

**Comment by escattone** [comment]
I agree. My vote would be to delete the code that sends those pings as well.
