### ISSUE TITLE
Is anybody interesting in the 'MozMenu' GA event?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3300]
In the last month, we've collected roughly 250k events when people click links in the Table of Contents sidebar. 

Its category is called `MozMenu`
https://analytics.google.com/analytics/web/#/report/content-event-events/a36116321w64965862p66726481/explorer-segmentExplorer.segmentId=analytics.eventCategory&_r.drilldown=analytics.eventCategory:MozMenu

Is anybody interested in this statistic?
Any plans to analyze it?
Can we delete the code if nobody's going to bother analyzing it?

**Comment by schalkneethling** [comment]
I doubt this is useful anymore. Perhaps it was a way to try and see how people navigate around MDN? I doubt anyone ever references it.

**Comment by peterbe** [comment]
@escattone ping?

**Comment by escattone** [comment]
@peterbe Let's get rid of it, thanks @peterbe.
