### ISSUE TITLE
Orphaned translations "by birth" should break in CI

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3301]
We have code that checks that the folder matches in the slug (in the front-matter). 
But what if you create a brand new page, inside a translation, that doesn't exist in English (aka. github.com/mdn/content)
Then, it should break in CI. 
E.g. `cd translated-content && mkdir files/fr/web/nouveau && emacs files/fr/web/nouveau/index.html`

It's possible that we're already checking this but it's worth checking this again.

**Comment by caugner** [comment]
Still an issue:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/495429/204668229-4dfa215e-fec1-44bc-ab0f-d18b2f05af6f.png">

**Comment by caugner** [comment]
As of March 2025, this is still an issue: https://github.com/mdn/translated-content/pull/10328
