### ISSUE TITLE
Deployer needs to upload static assets first

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3315]
What happened to me was this:
<img width="1500" alt="Screen Shot 2021-03-23 at 11 42 59 AM" src="https://user-images.githubusercontent.com/26739/112174614-ed8d9400-8bcc-11eb-93d8-1f7595153896.png">

If you look carefully, what happened was that the HTML says it depends on `main.46b66fe7.chunk.css` but it's 404'ing. 
I cache-busted the URL to make sure the HTML wasn't stale. But it wasn't. The problem was that the HTML had just been uploaded, but the static assets had not yet been uploaded. 

In the time it took me to go to the S3 console, to browse, I think the file uploaded. 
<img width="1177" alt="Screen Shot 2021-03-23 at 12 09 16 PM" src="https://user-images.githubusercontent.com/26739/112178963-9984ae80-8bd0-11eb-833c-aa835e6b4a69.png">
I believe what happened, in hindsight, was that the new HTML was uploaded to S3 and I requested it via the CDN, **all whilst still waiting for the new static assets to upload.**

**Comment by peterbe** [comment]
I think we can easily solve this by sorting the keys that the Deployer needs to upload. 
We need to upload things in this order:

1. all static assets
2. document Images 
3. the `index.json` file
4. the `index.html` file (which becomes the directory name kinda thing)
5. sitemap XML and search-index.json files

**Comment by peterbe** [comment]
This whole problem is just more likely to happen on Stage because the CDN is very rarely warm there. It would rarely happen on prod because the CDN is much more likely to hold on to the HTML (which references old/existing static assets). 

But a simple solution to avoid the problem altogether is probably to just make sure the static assets are uploaded first.

**Comment by escattone** [comment]
@peterbe Great catch! You're right, we need to upload in that order.
