### ISSUE TITLE
Language selector - Alignment of select with button

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#3318]
> > I'm just leaving this comment here, I hope that's okay.
> 
> Very OK.
> 
> Besides, I think @schalkneethling is planning to move the language dropdown form thingy to the bottom of the page. Perhaps you can come back and check that it's properly aligned there when it gets there.

I just remembered this issue and lo and behold, the alignment doesn't seem to be fixed (Arch Linux / Firefox 86.0.1).

![Screenshot from 2021-03-22 16-50-06](https://user-images.githubusercontent.com/2905118/112018436-d5673780-8b2e-11eb-9417-48d85751e0bd.png)

_Originally posted by @mnme in https://github.com/mdn/yari/issues/1486#issuecomment-804181435_

**Comment by mnme** [comment]
Thanks for creating this issue. Today I noticed another design flaw in the selector with Firefox on macOS (Big Sur). Arial is installed on my machine so it picks that as the font and it is slightly too big for the box—the parentheses overlap with the border. I can create a separate issue if you want.

<img width="360" alt="Screenshot 2021-03-24 at 15 08 41" src="https://user-images.githubusercontent.com/2905118/112324329-f6589580-8cb2-11eb-9a59-df4983bd2236.png">

**Comment by schalkneethling** [comment]
> Thanks for creating this issue. Today I noticed another design flaw in the selector with Firefox on macOS (Big Sur). Arial is installed on my machine so it picks that as the font and it is slightly too big for the box—the parentheses overlap with the border. I can create a separate issue if you want.
> 
> <img alt="Screenshot 2021-03-24 at 15 08 41" width="360" src="https://user-images.githubusercontent.com/2905118/112324329-f6589580-8cb2-11eb-9a59-df4983bd2236.png">

Yeah, these elements are ticky for sure but, they provide such an accessible experience that is very hard to achieve if you implement your own. There are some things we can do to make it better though. Cannot wait to be able to have more CSS hooks to style these.

**Comment by schalkneethling** [comment]
This has completely changed with the redesign. I am therefore closing this issue.
