### ISSUE TITLE
Compat tables don't indicate subfeatures

### ISSUE THREAD

**Issue by ddbeck** [mdn/yari#3321]
Tables that represent many levels of BCD don't clearly indicate when features are nested. This is a something of a regression from the former Kuma-generated tables.

Readers are confused when seemingly-duplicate features appear, when in fact they're similarly-named subfeatures. See https://github.com/mdn/browser-compat-data/issues/9417 or https://github.com/mdn/browser-compat-data/issues/9597 for an example.

Here's an example. The long table for [expressions and operators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators) contains this:
   
<img width="1043" alt="Screen Shot 2021-03-24 at 20 43 53" src="https://user-images.githubusercontent.com/64103/112380820-c1176c00-8ce1-11eb-9a90-7da3698cd6b4.png">

If you're not aware of the underlying structure, it's impossible to know that the "trailing" features are descendants of the `function` and `function*` features, and not siblings, as is the case for the majority of the entries in the table.

Under Kuma, the tables prefixed these descendants below the top-most feature's first descendants. For example, given `{{Compat('some.feature')}}` you might have a table like this:

- Some feature
- Sub A
- Sub B
- Sub B: sub-quirk 1
- Sub B: sub-quirk 2
- Sub C

**Comment by peterbe** [comment]
I'm somewhat familiar with that area of the code and all I can remember is that it was weird and scary. Clearly, that's demonstrated by the fact that *did* (as this issue describes) become different in the Yari (React) port.

**Comment by schalkneethling** [comment]
@ddbeck We should discuss this in our upcoming meeting and decide what to do about this.

**Comment by ddbeck** [comment]
This is still an issue with the redesigned tables. See https://github.com/mdn/yari/issues/5475 for a screenshot.
