### ISSUE TITLE
Deployer pruning does not take archived redirects into account

### ISSUE THREAD

**Issue by escattone** [mdn/yari#3323]
Currently, the deployer respects the archived paths in https://github.com/mdn/yari/blob/main/content/archived.txt when pruning, but doesn't take into account the archived redirects, so they're incorrectly removed from S3.

**Comment by escattone** [comment]
In order to quickly resolve this, @peterbe and I decided to turn "pruning" off when deploying to `dev`, `stage`, and `prod`. That will resolve the problem until we can determine the most appropriate long-term fix.

**Comment by peterbe** [comment]
@escattone How do you want to divvy up the work here. 

* Generating the `archived-redirects.txt`
* Writing a (Node) script that generates `archived.txt` and `archived-redirects.txt` (instead of relying on `find` and `sed`)
* Consider merging all the "active" archived content with the redirects all in *one* `.txt` file
* Write an improvement to the deployer so it can take all of this into account (i.e. not just "active" URLs but redirects as well)

**Comment by peterbe** [comment]
My gut tells me it'll be easiest to just have 1 file for active URLs *and* redirect URLs all in one file. 
Our current `archived.txt` is file paths. But we can pivot towards URLs.

**Comment by peterbe** [comment]
For the record, let's maybe not do this. At all. 
If we can, in 2 months, entirely stop serving archived content, we won't need to do anything. So based on that, I'll boldly go ahead and remove the "p1" priority label.

**Comment by peterbe** [comment]
We're going to entirely do away with archived-content as of June 30 so that'll make this issue moot. Let's not work on it but lets also not close it until we've finished getting rid of archived-content for realz.

**Comment by p-bakker** [comment]
Hi,

We at the [Rhino](https://github.com/mozilla/rhino) project just noticed that all our documentation (archived contented on MDN) has gone missing.

Coincidentally we were already [in the process](https://github.com/mozilla/rhino/issues/954) of moving it to our own GitHub pages and we can fetch the old content directly from the [mdn/archived-content repo](https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/projects/rhino), but there is a ton of external content that links to the old pages on MDN.

Is there any way to get those old url's (see https://github.com/mdn/content/issues/2181#issuecomment-776901600) to redirect to our new documentation location (when ready)?

If yes: how do we go about that? 

TIA

**Comment by peterbe** [comment]
@p-bakker When you have a bunch of URLs you want to redirect to, we can do that. 
You can today already make a PR against https://github.com/mdn/content/blob/main/files/en-us/_redirects.txt if not something that can be large patterns (i.e. regex/wildcard redirects). 
If you do decide to make a PR against the `_redirects.txt` file, there's a CLI in mdn/yari for that. I think it's `yarn tool add-redirects --help`.

**Comment by p-bakker** [comment]
Tnx for the quick response!

Will probably be individual redirects, to properly map old urls to our new documentation structure, so when we've settled on our structure and have our content in place, I'll create a PR
