### ISSUE TITLE
/en-US/ isn't a broken link

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3326]
See screenshot:
<img width="1156" alt="Screen Shot 2021-03-24 at 9 41 28 PM" src="https://user-images.githubusercontent.com/26739/112406057-d42e3a00-8ce9-11eb-9c19-3dc6510ffa5e.png">

**Comment by nschonni** [comment]
I think it might have been flagged before because some links had it as a placeholder URL. Searching in `content`, there are only 2 hits left, and they both look like they mean to point to the root
