### ISSUE TITLE
Create generic loading placeholder

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#3341]
We currently have a placeholder dino we use on document pages when content is still loading. There are many other places we can reuse this so it makes sense to create a generic component. This is also an opportunity to move the SVG to a background image which shrinks our main bundle.

Now that I have a "hack" for the little bit of styling and animation, there is no reason to have it directly in the HTML.

**Comment by schalkneethling** [comment]
This will also take care of https://github.com/mdn/yari/issues/2990

**Comment by peterbe** [comment]
If you do make a PR, please please break it up into multiple PRs. One for the SVG to image alone. 
We do have a couple of these `<React.Suspense fallback={<p>Loading...</p>}>` which we could refactor into something uniform and generic. However, not all those places gets to use up the whole page. E.g the document XHR loading probably should take up the whole page. But the BCD table. Or the account settings operate when there's already some stuff in the page.

**Comment by peterbe** [comment]
I'd rather we tackle https://github.com/mdn/yari/issues/2990 first and foremost.

**Comment by caugner** [comment]
In the mean-time, we do have a generic loading component:

https://github.com/mdn/yari/blob/13890752c2de8998357ff6fbe0dcde748d06f89e/client/src/ui/atoms/loading/index.tsx#L12-L29
