### ISSUE TITLE
I think what's confusing about redirects is...

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3342]
I think what's confusing about redirects is... 

1. you might think you're supposed to manually edit the `_redirects.txt` file when in fact you should be using the `yarn content add-redirect ...` CLI tool. 
2. I suspect that the same validation that runs in GitHub CI isn't running on your local server when you type `yarn start`. So you might be unnecessarily disappointed when CI breaks after all the hard work. 

We can solve both. For example, perhaps it's better to call it `_redirect.json` since that'd make it impossible to have to distinguish between a tab and spaces. Heck, I don't even know how to type a tab character because my IDE automatically transforms it to 4 spaces (or 2 depending on the file).

The other thing we could do to make things a whole lot easier is to do what Python poetry does. They have a lock file just like `yarn.lock` and `package-lock.json`. But they have a hash within the file itself. How the hash is computed isn't important but if the CLI is the only tool in the world that knows how to make the hash, you can easily and quickly check that only the CLI was allowed to edit the file. 

It was @fiji-flo who built most of the redirects tooling and it would be great to have some of your thoughts on this. 

PS. I love that this is being tracked in the [content-team-dev-papercuts Trello board](https://trello.com/b/3YgVTxvh/mdn-content-team-dev-papercuts) because then we can find out that multiple people are suffering from the same confusions.

_Originally posted by @peterbe in https://github.com/mdn/content/issues/3393#issuecomment-808139716_

**Comment by caugner** [comment]
Essentially fixed by https://github.com/mdn/yari/pull/3343, and we don't need to improve it right now.
