### ISSUE TITLE
The locale of the search API gets 0 count

### ISSUE THREAD

**Issue by harapeko** [mdn/yari#3357]
I think the locale being maintained should get the results.
Have there been any changes that have affected the search API?

I have confirmed the following.
- https://developer.mozilla.org/api/v1/search?q=flex // GOOD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=en-US // GOOD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=ru // BAD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=fr // BAD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=es // BAD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=zh-CN // BAD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=ja // BAD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=pt-BR // BAD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=ko // BAD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=de // BAD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=pl // BAD
- https://developer.mozilla.org/api/v1/search?q=flex&locale=zh-TW // BAD

**Comment by peterbe** [comment]
Yep. It's busted. Actively working on it. It broke on Friday evening and took us by surprise. 

Same issue here: https://github.com/mdn/yari/issues/3359

**Comment by peterbe** [comment]
We figured out a solution but it's only a temporary solution. We're awaiting response from Elastic's customer support. We can't yet know for sure if it's our networking or simply the Elastic servers themselves. 

Right now, we're operating in a "forgiving update mode" meaning; after every build we try to publish all and everything to Elastic search without first clearing the index. If there are errors, we ignore and keep on going.

**Comment by harapeko** [comment]
Thanks for the trial and error.
It may be a temporary fix, but it is helping.

I wish you a true solution.

thanks😀
