### ISSUE TITLE
Alternate lang link tags are broken

### ISSUE THREAD

**Issue by burtek** [mdn/yari#3358]
There is `undefined` `href` in `<link rel="alternate" />`

![image](https://user-images.githubusercontent.com/2940958/112748480-1c847b00-8fbc-11eb-8b58-5bc031bc0065.png)

i.e. on https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/has

**Comment by peterbe** [comment]
I can reproduce it locally and I think I know what went wrong.

**Comment by peterbe** [comment]
Fixed now. 
It might take a little while for the CDN cache to clear but one can do a verification check by messing with the case of the URL. 
view-source:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/MAp/has
