### ISSUE TITLE
search doesnt work

### ISSUE THREAD

**Issue by heavnzor** [mdn/yari#3359]
as the title said ... the search function doesnt work for me and for friends of mine 
example : https://developer.mozilla.org/fr/search?q=css // 0 result

**Comment by heavnzor** [comment]
https://developer.mozilla.org/fr/search?q=css doesnt work

**Comment by peterbe** [comment]
Oh no. Something must have broken. Will look into it.

**Comment by nreid260** [comment]
I'm not sure if this is the same issue, but the results I am getting from search are very low quality.

Example:
   -  search for "number", the top result is "EventTarget"
   -  search for "boolean", the top result is "EventTarget"

**Comment by gondwanasoft** [comment]
I'm getting search results — but not for Javascript entries (no matter how specific my search term is).

**Comment by andronocean** [comment]
I'm seeing very odd results, too. From a few quick tests, it looks like the only things being returned are DOM API results (or other browser APIs). Any pages about straight HTML, CSS, or JS aren't showing up.

- Search for "button", top result is Document.getElementById()
- Search for "border-radius", top result is ResizeObserverEntry.target
- Search for "Promise", top result is SerialPort.close()

**Comment by Zhao-Bocheng** [comment]
the search doesn't work when the lang is Chinese!!!!  
![image](https://user-images.githubusercontent.com/63044289/112812314-8f225300-90af-11eb-9538-71966018774f.png "zh-CN")  
![image](https://user-images.githubusercontent.com/63044289/112812436-ba0ca700-90af-11eb-849a-46606d1abc27.png "en-US")

**Comment by escattone** [comment]
Thanks everyone for reporting the issue (and for your patience while we resolve it). We know the root cause of the issue (we're having connectivity issues to our Elasticsearch instance), and are working on a resolution. Sorry for the incovenience!

**Comment by escattone** [comment]
This should be resolved now. We're still experiencing (and working on) issues when bulk-indexing on our Elasticsearch instance, but search should work as expected now. Thanks again to everyone for their patience!

**Comment by peterbe** [comment]
We figured out a solution but it's only a temporary solution. We're awaiting response from Elastic's customer support. We can't yet know for sure if it's our networking or simply the Elastic servers themselves. 

Right now, we're operating in a "forgiving update mode" meaning; after every build we try to publish all and everything to Elastic search without first clearing the index. If there are errors, we ignore and keep on going.
