### ISSUE TITLE
Test various loading states for signin, up and account settings

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#3360]
@peterbe has mentioned some odd behavior with the main heading on the auth pages. Would be good to go over the various pages and states and ensure everything behaves as expected.

**Comment by peterbe** [comment]
In particular, what I find is that the first heading usually moves once the lazy-loaded chunk comes in. You can see it by refreshing the page, maybe many times, over and over.

**Comment by Eileenioi** [comment]
> 
0L2DlkCJLBrQXE/CvTfOiw==

**Comment by peterbe** [comment]
Got fixed with https://github.com/mdn/yari/pull/4391
