### ISSUE TITLE
Issue with "Promise": missing space in note

### ISSUE THREAD

**Issue by foolip** [mdn/yari#3371]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

#### What information was incorrect, unhelpful, or incomplete?

The page says:

> Note:This feature is available in Web Workers.

There's no space between "Note:" and the note.

#### What did you expect to see?

A space.

#### Did you test this? If so, how?

I found that it boils down to https://github.com/mdn/yari/blob/main/kumascript/macros/Note.ejs and thus probably affects all pages using notes, but I'm not sure about unintended consequences of adding a space there. Maybe an extra space for certain languages in https://github.com/mdn/yari/blob/main/kumascript/macros/NoteStart.ejs would be correct?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/promise`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/promise/index.html
* Last commit: https://github.com/mdn/content/commit/1712a1f29ae167ddfbf7ffeabc8573c41088566d
* Document last modified: 2021-03-16T05:30:25.000Z

</details>

**Comment by peterbe** [comment]
I disagree that this is front-end. We should just render it out with a space between the`</h4>` and the proceeding text. 
I don't know why we can't just inject a space in https://github.com/mdn/yari/blob/ce1af504e7a30ddee7457adb802d70dd79564d77/kumascript/macros/Note.ejs#L3 between the `>` and `<` there.

**Comment by foolip** [comment]
I think the issue is that not all languages should have a space in there. In particular, in Chinese it should presumable read "注意：怎么怎么样" with no ASCII space, since the full-width "：" already has space in it.

**Comment by peterbe** [comment]
[So, we could do what the French do :)](https://github.com/mdn/yari/blob/ce1af504e7a30ddee7457adb802d70dd79564d77/kumascript/macros/NoteStart.ejs#L15)

**Comment by foolip** [comment]
Yes, simply adding spaces for some languages in `NoteStart.ejs` seems like a pretty good fix. Afraid I can't fix the French language though ;)

**Comment by caugner** [comment]
Already fixed via https://github.com/mdn/yari/pull/3530.
