### ISSUE TITLE
Firefox platform hacked again for iMac 10.15.7.

### ISSUE THREAD

**Issue by wst470** [mdn/yari#3379]
I couldn't open gmail and when i uninstalled firefox and tried to reinstall, it wouldn't open, because it said firefox was already open. So, it requires uninstall and shut down, then reboot, and download fire fox. It will only work for a few days, then wash, rinse, and repeat.

**Comment by chrisdavidmills** [comment]
I am sorry to hear about your troubles, but this site has nothing to do with Firefox itself. This is related to the platform that runs the site https://developer.mozilla.org/

You'd be better off filing a bug at https://bugzilla.mozilla.org/
