### ISSUE TITLE
Compat tables should show show Node.js data for Web APIs (where present)

### ISSUE THREAD

**Issue by ddbeck** [mdn/yari#3410]
(This is something we ought to do, but I don't know if it's a high priority. It's been a known issue for at least a year. I thought it deserved to be written down somewhere, though.)

Presently, the compat table only includes Node.js data for JavaScript pages (see [`browser-compatibility-table/index.tsx`](https://github.com/mdn/yari/blob/5f398b3c0f2615bb6aa1a77f9f8fddc6df126697/client/src/document/ingredients/browser-compatibility-table/index.tsx#L41)).

In reality, we have some Node.js data for some Web APIs that Node.js supports (see https://github.com/mdn/browser-compat-data/pull/3160), but we never show it on MDN. We ought to show Node.js data for all JavaScript pages and the subset of Web API pages that have Node.js data.

The tricky thing here is that we only want to show Node.js for Web APIs that we have data for. Otherwise, we'd show a pointless column for Node.js on, for example, a zillion irrelevant DOM API pages. Right now, the compat table chooses which browsers/engines to include based on the page type, without knowing anything about the data.

**Comment by peterbe** [comment]
Yeah. This would be cool! E.g. https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams doesn't show which Node version added this. 
[Apparently it was version 10.0.0](https://github.com/mdn/browser-compat-data/blob/44f3b7e5d1bb4e1c971f4858ae34baf21d78f4c0/api/URLSearchParams.json#L27)
So can we simply look for `nodejs` in the `support` key? Would a simply truthy test suffice? I.e. it'd be Yes for `URLSearchParams.json` and No for `CSSKeyframesRule.json`.

**Comment by ddbeck** [comment]
> So can we simply look for `nodejs` in the `support` key? Would a simply truthy test suffice? I.e. it'd be Yes for `URLSearchParams.json` and No for `CSSKeyframesRule.json`.

@peterbe That is correct. If the `nodejs` key exists in `support`, then there is data there we meant for consumers to be able to make use of.

I checked and there are 230 compat features with Node.js data in the `api` tree (though they are concentrated in heavily-used APIs). There is no Node.js data in trees beside `api` and `javascript`.
