### ISSUE TITLE
Signed-in drop-down menu glitches

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3415]
See https://github.com/mdn/yari/issues/3399#issuecomment-811992286_ for a screencast that demonstrates an odd square dark-blue border behind your mugshot when you click it. 
And, the "Sign out" option has an underline text decoration.

**Comment by escattone** [comment]
@schalkneethling Can you prioritize this for next week?

**Comment by peterbe** [comment]
How's this going? Are we sure this is a p1 issue? 
Perhaps @Gregoor can help out if your plate is full @schalkneethling

**Comment by schalkneethling** [comment]
> How's this going? Are we sure this is a p1 issue?
> Perhaps @Gregoor can help out if your plate is full @schalkneethling

On it at the moment 😄
