### ISSUE TITLE
Optimize the bulk insert performance to Elasticsearch

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3417]
Once https://github.com/mdn/yari/pull/3409 is in place we can benchmark the best possible configuration for bulk indexing. 
In particular, since the new strategy is to create and populate an index before using it at all, we can play with the refresh interval. 
It's not unusual to disable the refresh interval when you're done and set it back to its default setting when you're done. We actually might be doing inserts that are not "entirely in bulk". 
When we build the complete index (with omitting the `--update` flag) we bulk insert all 48k documents. But if we do a partial build of say 100 documents (that's a big PR!) that's actually done as bulk inserts too. 
One thing to consider is to never set the refresh interval because we always bulk insert. So perhaps it's best to always set `index.refresh_interval=60s` because even if it's a smaller partial bulk indexing, even then. 

Lots of good tips here!
https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-indexing-speed.html#_use_bulk_requests

One of the tips in there is to experiment with the `bulk_size`. Currently, we have it set to 200. But we could write a script that loops over options like 100, 200, 300, 500, 1000 and see which one finishes fastest.

**Comment by peterbe** [comment]
Thing is, `bulk_size` doesn't appear to have a lot to do with indexing performance. It makes sense that a larger number is more performant because there's less network overheads. In fact, I tried a bunch of different chunk size numbers and ran it over and over and recorded the rate (documents per second). The results are as follows:

```
Dev.us-west-2.aws.found.io:9243 BEST MEDIAN RATE...
1 500   219.69 docs/sec (6 samples)
2 1000  219.50 docs/sec (6 samples)
3 300   215.66 docs/sec (6 samples)
4 200   215.39 docs/sec (6 samples)
5 100   208.54 docs/sec (6 samples)

Dev.us-west-2.aws.found.io:9243 BEST MEAN RATE...
1 500   220.02 docs/sec (6 samples)
2 1000  219.12 docs/sec (6 samples)
3 300   217.62 docs/sec (6 samples)
4 200   215.97 docs/sec (6 samples)
5 100   211.71 docs/sec (6 samples)
```

This confirms my suspicion. The larger the chunk size the higher the rate. But it's a very slim margin! Doing 1,000 docs at a time means a higher probability that it could go wrong and/or timeout because the chunk will take longer to insert. 
But a sending *fewer* chunks reduces the probability that some network might be failing. 

Conclusion; **it ain't easy. No obvious correct result.**
The default number is 500. We changed it to 100 when we changed the strategy to continue-on-error (rather than bail-on-any-error). Perhaps we should just change it back to 500.

**Comment by peterbe** [comment]
Ignore the results above. They were flawed due to a bug! When I discovered my bug in measurement I had already moved on to experimenting with setting the `max_chunk_bytes`. Now, the latest and greatest result is:

```
Dev.us-west-2.aws.found.io:9243 BEST MEDIAN RATE...
1   chunk_size=1000 max_chunk_bytes=10M   errors=0 331.71 docs/sec (4 samples)
2   chunk_size=1000 max_chunk_bytes=50M   errors=0 318.03 docs/sec (2 samples)
3   chunk_size=1000 max_chunk_bytes=5M    errors=0 314.05 docs/sec (4 samples)
4   chunk_size=1000 max_chunk_bytes=100M  errors=0 308.56 docs/sec (2 samples)
5   chunk_size=500  max_chunk_bytes=5M    errors=0 286.01 docs/sec (4 samples)
6   chunk_size=500  max_chunk_bytes=10M   errors=0 284.51 docs/sec (4 samples)
7   chunk_size=300  max_chunk_bytes=10M   errors=0 282.08 docs/sec (4 samples)
8   chunk_size=300  max_chunk_bytes=50M   errors=0 276.66 docs/sec (4 samples)
9   chunk_size=200  max_chunk_bytes=50M   errors=0 264.33 docs/sec (4 samples)
10  chunk_size=200  max_chunk_bytes=5M    errors=0 258.02 docs/sec (4 samples)
11  chunk_size=200  max_chunk_bytes=10M   errors=0 256.05 docs/sec (4 samples)
12  chunk_size=300  max_chunk_bytes=5M    errors=0 255.57 docs/sec (4 samples)
13  chunk_size=100  max_chunk_bytes=50M   errors=0 248.49 docs/sec (4 samples)
14  chunk_size=100  max_chunk_bytes=10M   errors=0 231.38 docs/sec (4 samples)
15  chunk_size=100  max_chunk_bytes=5M    errors=0 229.95 docs/sec (4 samples)
16  chunk_size=500  max_chunk_bytes=50M   errors=0 211.90 docs/sec (4 samples)
17  chunk_size=500  max_chunk_bytes=100M  errors=0 196.06 docs/sec (4 samples)
18  chunk_size=300  max_chunk_bytes=100M  errors=0 191.64 docs/sec (4 samples)
19  chunk_size=100  max_chunk_bytes=100M  errors=0 173.46 docs/sec (4 samples)
20  chunk_size=200  max_chunk_bytes=100M  errors=0 172.81 docs/sec (4 samples)
21  chunk_size=1000 max_chunk_bytes=100M  errors=2000 59.23 docs/sec (1 samples)
22  chunk_size=1000 max_chunk_bytes=100M  errors=3000 58.91 docs/sec (1 samples)
23  chunk_size=1000 max_chunk_bytes=50M   errors=2000 53.90 docs/sec (2 samples)
```

Only when you use `chunk_size=1000` were there errors. But the sample size is small so it could still just be bad luck. 
There appears to be no sensible pattern between the `max_chunk_bytes` and that's probably because each document, as a JSON string is 1.9KB on median. So 1,000 * 1.9 ~= 2MB.

**Comment by peterbe** [comment]
@escattone Last night: 
```
Took 1m 30s to index 48,395 documents. Approximately 536.3 docs/second
Count shards - successful: 96,790 failed: 0
Counts - worked: 48,395 errors: 0
```
That's a new record. It's better than what we had before we got problems with Elasticsearch indexing.

**Comment by escattone** [comment]
Nice work @peterbe!
