### ISSUE TITLE
No point in keeping the `brush: xxx` after cheerio + Prism is done

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3418]
We currently convert:

```html
<pre class="brush: js">CODE HERE</pre>
```
into
```html
<pre class="brush: js notranslate"><code><span class="token">CODE</span> <span class="token">HERE</span></code></pre>
```
(The `notranslate` isn't related to Prism but it's important for the benefit of using Google Translate in the browser.)

But once the `brush: js` has been consumed by the code that figures out which Prism lexer to use, we no longer need it. 
It's not many bytes of waste but it serves no purpose to keep the `brush: js` anymore after the Yari builder has done its Prism thing. 

However, and this relates to possible futures with Markdown, we might want to keep other things in there that might be useful. For example: `<pre class="brush: css example-good">` is used to give the `<pre>` tag a green background. This should ultimately become `<pre class="example-good notranslate">`.

**Comment by escattone** [comment]
Adding a reminder to look into whether this would affect https://github.com/mdn/yari/blob/9daaec32eddd5005b5e628c3481f94637b1dd0b3/kumascript/src/api/util.js#L184. Probably not, just didn't want to forget.
