### ISSUE TITLE
Intention to measure: Find out the x-cache values in site-searches

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3420]
We recently added `Cache-Control` to our `/api/v1/search` endpoint. That's nice if the CDN is warm but pointless(*) if it's always cold. A remedy to the coldness could be to increase the cache-control number of seconds. If you have to make it very high you have to deal with invalidation. At the moment we have it [set to 12h](https://github.com/mdn/kuma/blob/59de2572423a0e354690ee9483e77a02bf8e8a3c/kuma/api/v1/search/__init__.py#L16). 

Suppose that 12h is just too short. The longest possible number we can switch to is 24h because that's when we could trigger an invalidation request at most. 

The intention is to use Google Analytics Events to record what values of `X-Cache` clients get when they make searches. 

(*) It's not entirely pointless because the `Cache-Control` is used by the user too. If you make a search (cold browser cache), click one of the search results, realize it was the wrong one, click the Back button, and revisit the search result. That will mean the browser cache can supply the search result.

**Comment by peterbe** [comment]
In the last week; this is what we see: 
<img width="1235" alt="Screen Shot 2021-04-23 at 3 48 39 PM" src="https://user-images.githubusercontent.com/26739/115923190-dd770780-a44b-11eb-9ed9-a38900de2228.png">

- 70% of site-search API JSON is cache misses
- 30% of site-search API JSON is cache hits

**Comment by caugner** [comment]
FWIW `Cache-Control` is still at 12h in rumba (see [here](https://github.com/mdn/rumba/search?q=cache_max_age)).

In the last week, this is what we see:

<img width="1306" alt="image" src="https://user-images.githubusercontent.com/495429/204638116-21e8c98a-517b-442f-8af7-2c3ac923dcb5.png">

92% of site-search API JSON is cache misses
8% of site-search API JSON is cache hits

Compared to April 2021, the number of site-search API JSON requests has reduced significantly, as the redesign came with quicksearch.

**Comment by caugner** [comment]
This is no longer applicable since our move from AWS to GCP, so I'm closing this as done, because the measurement was implemented.
