### ISSUE TITLE
 DuckDuckGo bang search broken

### ISSUE THREAD

**Issue by diminutivesloop** [mdn/yari#3425]
When I search MDN via the DuckDuckGo “!mdn” bang shortcut certain special characters such as ‘-‘ remain url encoded resulting in irrelevant search results. For example the search “!mdn text-shadow” redirects to https://developer.mozilla.org/en-US/search?q=text%252Dshadow which has the following results

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/667716/113450197-6a8aeb80-93cd-11eb-9232-97541a37553e.png">

I believe this is DuckDuckGo’s fault since they’re unnecessarily encoding url-safe characters but since their support site doesn’t provide a good way to report issues like this and since other sites such as caniuse.com handle similar queries without issue I think it’s worth trying to fix this on MDN’s side.

**Comment by peterbe** [comment]
@schalkneethling Can you reproduce?

But I wonder what *we* could do. What is `%2D`? Why and how is a regular ASCII `-` character URL encoded??

**Comment by diminutivesloop** [comment]
Doing a little more digging myself I see that DuckDuckGo performs the redirect via JavaScript
```javascript
window.parent.location.replace("https://developer.mozilla.org/search?q=text%2Dshadow”)
```
and then for some reason MDN respond to that request with a 302 redirect to `/en-US/search?q=text%252Dshadow` even though Firefox appears to have fully decoded the url before issuing the request.
<img width="776" alt="image" src="https://user-images.githubusercontent.com/667716/113490630-65936e00-9499-11eb-8d18-9e38f0d9bff1.png">

**Comment by escattone** [comment]
@diminutivesloop Regarding the MDN redirect of `/search`  --> `/en-US/search`, that is done to localize the search, and the locale is selected as follows:  the locale specified by  the user's `preferredlocale` cookie, if present, is given top prioritty, next the user's `Accept-Language` header, and finally we default to `en-US`.

**Comment by peterbe** [comment]
I see now. This is definitely a bug on our end that we can solve. If the incoming URL is `https://developer.mozilla.org/search?q=text%2Dshadow` it should (302) redirect to `https://developer.mozilla.org/en-US/search?q=text%2Dshadow` but instead it redirects to `https://developer.mozilla.org/en-US/search?q=text%252Dshadow`. I.e. injecting the `/en-US` prefix to the pathname part of the URL is correct but it shouldn't "double-encode" the query string.

**Comment by escattone** [comment]
I updated our Cloudfront (CDN) instances to use the new Lambda function from #3502, and made sure this is resolved now. Thank you @diminutivesloop for reporting and helping us understand this. Cheers!

**Comment by peterbe** [comment]
`curl -I https://developer.mozilla.org/search\?q\=text%2Dshadow` looks right now.
