### ISSUE TITLE
<h4 id> are inconsistent, not lowercased as other headings

### ISSUE THREAD

**Issue by Remu-rin** [mdn/yari#3429]
I encountered a broken link to `id` on the same page, but when investigating further I thought that it's more appropriate to be fixed here than in `mdn/content` (which would require mass edit like https://github.com/mdn/content/pull/2312 and probably will result in inconsistent writing rules for `id` of different elements in `content` repo).

It seems that some backend code is changing `id` of `h2` and `h3` elements to lowercase (I couldn't find it, except related comment [there](https://github.com/mdn/yari/blob/984c8a3c1499f26e5b790a5a6170bd9346f33406/client/src/document/index.tsx#L105)), while most of `id` in `content` repo are not in lowercase. But that doesn't happen with `h4` elements, they stay as is, and this can lead to broken links, because `anch` macros (or it's successor?) also results in lowercase `id`.

Example of broken link: https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing/HTML_and_CSS#ie_conditional_comments (linked in `anch` [here](https://github.com/mdn/content/blob/35e5dcbdba4edb4a6d8d3577f33ad0d0e2e51f8a/files/en-us/learn/tools_and_testing/cross_browser_testing/html_and_css/index.html#L122)).
Or related recent fix of broken link without `anch`: https://github.com/mdn/content/pull/3799 (which should be reverted later if `h4 id` will be lowercased as others, also it seems to contradict with https://github.com/mdn/yari/pull/2604).

**Comment by escattone** [comment]
@peterbe We should discuss this when you return. For future reference:

- https://github.com/mdn/yari/blob/ed4290303a837f2974d86f7c6c98e89a8134e895/kumascript/index.js#L92
- https://github.com/mdn/yari/blob/ed4290303a837f2974d86f7c6c98e89a8134e895/kumascript/src/api/util.js#L101
- https://github.com/mdn/yari/pull/2266
- https://github.com/mdn/yari/pull/2604

**Comment by peterbe** [comment]
@escattone If we just change the `injectSectionIDs` function to stuff like this for example:
```diff
-id = slugify(text);
+id = slugify(text).toLowerCase();
```
then I think nothing needs to be done for anchor links. 
Worth a shot if it's that simple.
