### ISSUE TITLE
RegExp.prototype.hasIndices code sandbox is down

### ISSUE THREAD

**Issue by programmurr** [mdn/yari#3431]
The code sandbox here is down: [RegExp.prototype.hasIndices](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/hasIndices)

Instead of seeing the sandbox I see this:
![image](https://user-images.githubusercontent.com/64764695/113526043-d1fc9300-95a7-11eb-8b7e-b7b21f828d7d.png)

**Comment by tristantheb** [comment]
Hi :)

I found this information for you! mdn/interactive-examples#1782
The example is currently awaiting validation by the relevant repository of the MDN interactive examples ;)

**Comment by programmurr** [comment]
Hi! Cool I didn't realize this was a new property! I guess this is resolved given that the new example has been merged. Thank you!
