### ISSUE TITLE
Improving Readability through Dark mode

### ISSUE THREAD

**Issue by 103562** [mdn/yari#3462]
Hi Mozilla team, 

I have a feature request. Please create an option for Dark mode on the MDN Web Docs. 

This would be much appreciated.

**Comment by escattone** [comment]
@103562 Over the past few years, this has been one of the most requested features. We've already started a discussion about this (see https://github.com/mdn/yari/discussions/2539), so I'm going to close this issue. Please feel free to join that discussion if you'd like. Cheers.
