### ISSUE TITLE
add note indicating expiration date of preview URL's

### ISSUE THREAD

**Issue by escattone** [mdn/yari#3466]
I was speaking to @wbamberg about the pull-request preview URL's provided by the new [PR Review Companion](https://github.com/mdn/content/blob/main/.github/workflows/pr-review-companion.yml) GHA workflow in https://github.com/mdn/content, and he mentioned that it would be good to indicate the expiration date of the preview URL's, which is currently 30 days from their date of birth (which we can easily adjust as needed).

**Comment by caugner** [comment]
The Content and Engineering team have discussed this, and decided to close this as "won't fix", as it is encouraged to update PRs that haven't been updated for more than 30 days by merging `main` (using the "Update branch" action in the GitHub UI), and this will trigger a new deployment.
