### ISSUE TITLE
Better distinguish References and Guides

### ISSUE THREAD

**Issue by dvranga** [mdn/yari#3486]
I was confused about where I am landing after clicking the javascript tutorials because there is no proper routing and clear description the tutorials please make to navigate the links and context is very bad to understand and I am not getting a clear idea about the context of javascript tutorials my idea is any new user if landed on this page it should be easy to understand the context of tutorials but getting the confusion. every time it is showing the link about web development or front end development it is diverting the user's interest i,e if I clink on javascript tutorials why it is showing web development docs or some other docs instead of javascript.

**Comment by peterbe** [comment]
@schalkneethling @chrisdavidmills It's a never-ending and near-impossible problem for MDN to ever solve perfectly. The content is just too big and potentially broad. But I think the point is that you're easily confused as you surf between "tutorial-like pages" and "reference pages". Us who know the content so well can spot it almost immediately, but for a novice it's much harder to see where you are. 

One not-good solution is that all tutorial-like pages have pink background and all reference-like pages have brown background. Then it might be more obvious that you've landing in a very different "area" of the site. 
Another solution would to (ab)use the top navbar to highlight which one you're on. For example, if you're on [a tutorial page like this](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/JavaScript_basics) the "Reference & Guides" navbar is "highlighted" in some strong way. And when you click into [a reference page like this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures) the "Technologies" navbar is highlighted. 

Another solution would be some sort of dynamic widget that suddenly appears if you change from a reference page to a learning/guide page and vice versa. We can record what page you're on with a `sessionStorage` and then a thing can appear near the top that says "Click to go back to _Getting started with CSS_". 

Solving this would be a huge improvement for a large number of MDN users who hop between reference lookups to reading long-form articles.

**Comment by chrisdavidmills** [comment]
This is a really tough problem to solve. I think a combination of approaches would work, including using your wayfinder link type idea (the "click to go back to..."), and some kind of subtle styling to give you an idea of what part of MDN you're in (even just some kind of a nice badge at the top of the page saying "Reference", or "Learn Web Development"...)

**Comment by peterbe** [comment]
@schalkneethling What do you think about highlighting the "References & Guides" if you're on a page whose slug prefix is one of those within that "tab"?

**Comment by caugner** [comment]
This has been implemented in https://github.com/mdn/yari/pull/9940, and there is https://github.com/mdn/yari/pull/11061 to further improve the design, so I'm closing this as done.
