### ISSUE TITLE
Edit/Update comment for PR review

### ISSUE THREAD

**Issue by nschonni** [mdn/yari#3487]
Since I think the logic is in the Python deployer code, I'm not going to send anything 😄 
You can see an example of a plain GitHub API/Action here https://github.com/w3c/aria-practices/blob/0553bb51588ffa517506e2a1b2ca1422ed438c5f/.github/workflows/coverage-report.yml#L30 were it looks for an existing bot comment and updates the comment instead of multiple comments as the PR gets updated

**Comment by peterbe** [comment]
But it's not that obvious. What if the first comment pointed out the fact that PR first had some nasty flaws, a reviewer might want to keep that record so they can see that something was once pointed out but later "retracted" or something. 
It's like when you post a comment on a PR at a specific line, and then that line disappears in following commits. They're like "orphan comments" which can be a useful audit trail.

But certainly, things like the "Deployment URLs" are pointless to keep re-posting every time a new commit comes in to the PR. 

Perhaps we can edit all existing comments to become:

```
This Review Companion comment has now become obsolete. (DATE/TIME HERE)

<details><summary>See original comments</summary>
COMPLETE PAYLOAD OF PREVIOUS COMMENT
</details>
```

**Comment by peterbe** [comment]
Perhaps the need for an audit trail is exaggerated. What about this:
You seek all/any comments previously posted by the bot. Delete them. Then post the new comment. 
Then the latest comment is always last (bottom).

**Comment by peterbe** [comment]
@chrisdavidmills @wbamberg @rachelandrew If you have more feelings and opinions about the UX of the PR Review Companion bot's PR comments, here's a chance to discuss too.

**Comment by nschonni** [comment]
You can see "Edits" on comments in the GitHub UI, but fair point that sometimes an audit trail might be good. Would those not come from the actual CI run logs though as well?

**Comment by peterbe** [comment]
<img width="479" alt="Screen Shot 2021-04-13 at 10 40 33 AM" src="https://user-images.githubusercontent.com/26739/114571518-ba2aac00-9c44-11eb-8f95-b718bd156e4b.png">

Oh I see. That's neat as heck! I didn't realize this thing. 
I think we should just go for it. We could also include, the Markdown we post, that "(This comment has been updated)" to make it clear that does update when new commits come in.
