### ISSUE TITLE
Intention to measure: How many people are changing language despite having a cookie

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3519]
We're currently already recording GA events whenever someone uses that language toggle to override the language of the document. But we don't know how many of them already had a `preferredlocale` cookie. It would be interesting to know how many of these people change language even if they already have the cookie. It might lead us to understand how many people keep stumbling into the wrong locale and having to constantly switch the locale.

**Comment by peterbe** [comment]
This is in `main` but it's not hit production yet.

**Comment by caugner** [comment]
We're already measuring this, both in GA and Glean, so I'm closing as done.
