### ISSUE TITLE
poetry venv caching is "unsafe"

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3539]
It's not unsafe in terms of security but unsafe in that the cached `venv` might have been built with an old version of `poetry`. 
See https://github.com/mdn/content/pull/4179 which kinda explains it.

**Comment by caugner** [comment]
It looks like https://github.com/marketplace/actions/poetry-cache-action would do the trick, but at least we already use the `runner.os` in the cache key:

https://github.com/mdn/yari/blob/1e60717c710a06de16cc624a8beabf29f30d5b0e/.github/workflows/pr-deployer.yml#L21-L26

**Comment by caugner** [comment]
Closing, as I don't recall this being an issue in the last couple of months.
