### ISSUE TITLE
add banner to localized pages

### ISSUE THREAD

**Issue by escattone** [mdn/yari#3588]
### Intro
Let's add a banner to all localized pages for the 10 supported non-English locales. The banner has to account for two cases:
1. pages within the 6 active locales: `ru`, `ko`, `fr`, `ja`, `zh-CN`, and `zh-TW`
2. pages within the 4 inactive locales: `de`, `es`, `pl`, and `pt-BR`

### Location and look

![Screenshot 2021-04-07 at 17 28 23](https://user-images.githubusercontent.com/10350960/113892953-d5ba3080-97c6-11eb-9c84-b5270aa628e1.png)

Let's go with @dalexsy's second mockup:
- Located just below the breadcrumb bar and much thinner than that bar
- Left justified text
- Highlighted background
    - **active** locales: light pastel yellow or whatever color @schalkneethling and @dalexsy feel is best
    - **inactive** locales: a color that provides more emphasis, that indicates more of a warning since these locales have no community maintaining them, perhaps a brighter yellow or very light red or whatever color @schalkneethling and @dalexsy feel is best

### Text
Let's hard code the translations of the English text into the banner for each locale.

#### Active locales
Let's go with translations of @ddbeck's text for the 6 active locales (text below shown for French as an example):
>This page was translated from English by the community. Learn more by joining the [French community on MDN](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#french_fr).

Where the language community links for each language would be as follows:
- "Chinese" (`zh-CN` and `zh-TW`): https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#chinese_zh-cn_zh-tw
- "French" (`fr`): https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#french_fr
- "Japanese" (`ja`): https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#japanese_ja
- "Russian" (`ru`): https://developer.mozilla.org/en-US/docs/MDN/Contribute/Localize#russian_ru
- "Korean" (`ko`): TBD (@chrisdavidmills can provide this when it's ready)

#### Inactive locales
Let's go with translations of @chrisdavidmills' text for the 4 inactive locales:
> This page was translated from English by the community, but it is not actively maintained therefore it may be out-of-date. If you'd like to help maintain it, [find out how to activate inactive locales](https://github.com/mdn/translated-content#promoting-an-inactive-locale-to-tier-1).

**Comment by escattone** [comment]
@schalkneethling Could you take this one?

**Comment by escattone** [comment]
I think we could ask each of the respective localization communities within the active locales to provide translations of the text we've selected for the active locales, and I'm thinking we can find others to help us with translations for the text for the inactive locales (e.g., @Gregoor for `de`, and my wife could provide one for `es` 😄).

**Comment by SphinxKnight** [comment]
If I may be of any help :)  (I was just wandering across the repos) 

> This page was translated from English by the community. Learn more by joining the French community on MDN.

could be translated in French by

> Cette page a été traduite à partir de l'anglais par la communauté. Vous pouvez également contribuer en rejoignant la communauté francophone sur MDN.

**Comment by schalkneethling** [comment]
Progress!

![Screenshot 2021-04-29 at 15 37 48](https://user-images.githubusercontent.com/10350960/116559629-ef9bee80-a900-11eb-9d2f-e247e7796c47.png)

**Comment by schalkneethling** [comment]
And some more progress 🙃

![Screenshot of MDN Web Docs page showing a warning message for inactive locales](https://user-images.githubusercontent.com/10350960/116561456-9e8cfa00-a902-11eb-826a-e420dda5f992.png)

**Comment by schalkneethling** [comment]
![Screenshot of active translation message on desktop](https://user-images.githubusercontent.com/10350960/116562923-e2ccca00-a903-11eb-84f4-a6febd0c1da9.png)

**Comment by escattone** [comment]
@schalkneethling Exciting! Looks good so far! 🎉

**Comment by Gregoor** [comment]
Hey @schalkneethling, in case you still need deutsch, here's my attempt at speaking die Sprache:

> This page was translated from English by the community, but it is not actively maintained therefore it may be out-of-date. If you'd like to help maintain it, find out how to activate inactive locales.

could be translated to

> Der Inhalt dieser Seite wurde von der Community übersetzt, jedoch wird er nicht mehr aktiv gepflegt und kann daher veraltet sein. Wenn du mithelfen möchtest, kannst du [hier herausfinden wie deaktivierte Übersetzung reaktiviert werden](/somelink).

Tastes may vary (it feels a little wordy, but that's german for ya)

**Comment by schalkneethling** [comment]
> Hey @schalkneethling, in case you still need deutsch, here's my attempt at speaking die Sprache:
> 
> > This page was translated from English by the community, but it is not actively maintained therefore it may be out-of-date. If you'd like to help maintain it, find out how to activate inactive locales.
> 
> could be translated to
> 
> > Der Inhalt dieser Seite wurde von der Community übersetzt, jedoch wird er nicht mehr aktiv gepflegt und kann daher veraltet sein. Wenn du mithelfen möchtest, kannst du [hier herausfinden wie deaktivierte Übersetzung reaktiviert werden](/somelink).
> 
> Tastes may vary (it feels a little wordy, but that's german for ya)

Vielen Dank, Gregor! I shall use it.

**Comment by hochan222** [comment]
I was just wandering across the repos too :) 

> This page was translated from English by the community. Learn more by joining the Korean community on MDN.

could be translated in Korean by

> 이 페이지는 커뮤니티에서 영어로 번역되었습니다. MDN에서 한국 커뮤니티에 가입하여 자세히 알아보세요.

I hope it helped a little. :)

**Comment by schalkneethling** [comment]
> I was just wandering across the repos too.
> 
> > This page was translated from English by the community. Learn more by joining the Korean community on MDN.
> 
> could be translated in Korean by
> 
> > 이 페이지는 커뮤니티에서 영어로 번역되었습니다. MDN에서 한국 커뮤니티에 가입하여 자세히 알아보세요.
> 
> > "Korean" (ko): TBD (@chrisdavidmills can provide this when it's ready)
> 
> @chrisdavidmills I hope it helped a little. :)

Nice, thank you so much @hochan222.

**Comment by gidongkwon** [comment]
> 
> 
> I was just wandering across the repos too.
> 
> > This page was translated from English by the community. Learn more by joining the Korean community on MDN.
> 
> could be translated in Korean by
> 
> > 이 페이지는 커뮤니티에서 영어로 번역되었습니다. MDN에서 한국 커뮤니티에 가입하여 자세히 알아보세요.
> 
> > "Korean" (ko): TBD (@chrisdavidmills can provide this when it's ready)
> 
> @chrisdavidmills I hope it helped a little. :)

I think the "커뮤니티에서 영어로 번역되었습니다" part seems bit awkward, because it means "translated **to** English" isn't it?
Correct full translation would be something like:

> 이 페이지는 커뮤니티에 의해 영어로부터 번역되었습니다. MDN의 한국 커뮤니티에 가입하여 자세히 알아보세요.

With some more explanation in it, would be:

> 이 페이지는 커뮤니티가 영어를 한국어로 번역했습니다. MDN의 한국 커뮤니티에 가입하여 자세히 알아보세요.

What do you think? @hochan222

**Comment by hochan222** [comment]
Since then, I have corrected it in another PR. https://github.com/mdn/yari/pull/3733/files

> "이 페이지는 영어로부터 커뮤니티에 의하여 번역되었습니다. MDN Web Docs에서 한국 커뮤니티에 가입하여 자세히 알아보세요.",

**Comment by gidongkwon** [comment]
Looks good. Thanks
