### ISSUE TITLE
Twitter and OpenGraph cards not rendering for root URL and most pages

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#3590]
I was certain that the Twitter card was rendering correctly for pages on [MDN](https://developer.mozilla.org/en-US/), but it looks like the required `<meta>` tags for the Twitter summary and OpenGraph cards don't exist.

<img width="1095" alt="Screen Shot 2021-04-21 at 9 27 27 PM" src="https://user-images.githubusercontent.com/48612525/115655596-71c85980-a2e8-11eb-8313-ae00604c143f.png">

The following `<meta>` tags should be added for the Twitter social share card to render correctly. 

```html
<meta name="twitter:card" content="summary_large_image"> <!-- or content="summary" -->
<meta name="twitter:site" content="@MozDevNet">
<meta name="twitter:title" content="MDN Web Docs">
<meta name="twitter:description" content="Some description text for the page">
<meta name="twitter:image" content="https://foobar.com/some-image.jpg">
<meta name="twitter:image:alt" content="Some alt text">
```

I couldn't track down where exactly the document metadata inside the `<head>` was being generated or manually typed, but if the `<meta>` tags are being written in a template, we could define the metadata in YAML format or another data source to populate the `content` of the required Twitter card meta tags. E.g. below is an example of defining the metadata as template variables and passing them into the required `<meta>` tags.
```html
---
twitter_card_type: summary_large_image
twitter_handle: MozDevNet
twitter_card_title: MDN Web Docs
twitter_card_desc: Some description text for the page
twitter_card_image: https://foobar.com/buzz.jpg
twitter_card_image_alt: Some alt text

or maybe from an object

data:
  card_type: summary
  twitter_handle: FooBar

and access in the template {{ data.card_type }} 
---
<head>
  <meta name="twitter:card" content="{{ twitter_card_type }}">
  <meta name="twitter:site" content="@{{ twitter_handle }}">
  <meta name="twitter:title" content="{{ twitter_card_title }} ">
  <meta name="twitter:description" content="{{ twitter_card_desc }}">
  <meta name="twitter:image" content="{{ twitter_card_image }}">
  <meta name="twitter:image:alt" content="{{ twitter_card_image_alt }}">
</head>
```

This seems like a solid way to add support for the social share Twitter summary card. We could also add `<meta>` tags for the OpenGraph protocol (Facebook card) which look like:

```html
<meta name="og:title" content="MDN Web Docs">
<meta name="og:type"  content="website">
<meta name="og:url" content="https://developer.mozilla.org/en-US/">
<meta name="og:description" content="Some description text for the page">
<meta name="og:image" content="https://foobar.com/some-image.jpg">
<meta name="og:image:alt" content="Some alt text">
```
These `<meta>` tags could also have their `content` populated through template variables or from another data source like mentioned for the Twitter card tags.

### Thoughts
If the document metadata in the `<head>` is being rendered elsewhere and injected into the page, maybe writing a function to generate the `<meta>` tags needed for the Twitter summary code would be a start in that direction. Going further down this route, (my eleventy knowledge thinks "shortcode") but creating a KS macro that accepts the 6 string arguments or a single object argument with all the nested key/value pairs to generate the `<meta>` tags could be a good idea. That's if the metadata is being generated server side.

**Comment by tannerdolby** [comment]
The twitter summary card comes in two flavors: summary and summary_large_image. The generic summary card is a small photo in the left with title and desc on right, and the summary_large_image card is a larger image placed on top with title and description underneath.

### Summary card:  `<meta name="twitter:card" content="summary">`
<img width="1045" alt="Screen Shot 2021-04-21 at 10 24 05 PM" src="https://user-images.githubusercontent.com/48612525/115660332-b48e2f80-a2f0-11eb-9925-36acc30572bc.png">


### Large summary card: `<meta name="twitter:card" content="summary_large_image">`
<img width="1008" alt="Screen Shot 2021-04-21 at 10 23 36 PM" src="https://user-images.githubusercontent.com/48612525/115660327-b22bd580-a2f0-11eb-92a0-9bd79f53d2b6.png">

**Comment by tannerdolby** [comment]
@peterbe I could have sworn that the Twitter social share card worked when I shared a page on twitter to someone referencing a documentation page about 2-3 weeks ago. Let me know your thoughts on this.

**Comment by peterbe** [comment]
> @peterbe I could have sworn that the social share Twitter card worked when I shared a page on twitter to someone referencing a documentation page about 2-3 weeks ago. Let me know your thoughts on this.

Could it be that, unlike that Card Validator app, the real Twitter will fall back to the regular HTML meta tags that we have.

**Comment by peterbe** [comment]
If someone knows of a tweet of an MDN URL it would be nice to look at.

**Comment by tannerdolby** [comment]
@peterbe I did a few test tweets on Twitter and the summary card isn't rendering. 

Since the `<meta name="twitter:*">` tags aren't in the `<head>`, the real Twitter won't be able to render the card just like validator since the regular HTML tags the page currently has doesn't include `<meta name="twitter:*"> tags.

#### Test tweet 1
<img width="601" alt="Screen Shot 2021-04-22 at 1 02 26 PM" src="https://user-images.githubusercontent.com/48612525/115778130-083d5f00-a36b-11eb-9e2e-f0254ca40815.png">

#### Test tweet 2
<img width="603" alt="Screen Shot 2021-04-22 at 1 10 07 PM" src="https://user-images.githubusercontent.com/48612525/115778838-150e8280-a36c-11eb-9dd5-466ab9cfa199.png">


Unless those `<meta name="twitter:*">` tags are added, it looks like every MDN URL won't have a Twitter summary card rendered.

When I paste the URL into a tweet, there isn't a summary card generated.  Twitter is most likely using the validator behind the scenes to verify the URL when pasted (or manually entered) into tweet has a valid summary card rendered and then pop it into the tweet. Nothing is generated when I paste an MDN URL into the tweet box shown below.

<img width="682" alt="Screen Shot 2021-04-22 at 1 06 42 PM" src="https://user-images.githubusercontent.com/48612525/115778561-b47f4580-a36b-11eb-9d26-fcf34de73aa5.png">

**Comment by Ryuno-Ki** [comment]
Looking at view-source:https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox (that is, Ctrl-U on https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout/Flexbox ) I can confirm, that the `<meta />` tags are not part of the initial HTML.

**Comment by tannerdolby** [comment]
@peterbe I noticed all of the Mozilla hacks article pages **do** have the appropriate `<meta>` tags for a Twitter summary card and Facebook (OpenGraph) card, this is where I originally saw the summary card on Twitter, I tweeted one of Chris Mills blog posts from mozilla hacks and the summary card rendered nicely. 

If there is a way to use the same logic in Yari as used in the mozilla hacks [pages](https://hacks.mozilla.org/2021/03/mdn-localization-in-march-tier-1-locales-unfrozen-and-future-plans/) for generating the meta tags then that would fix this issue. They might be manually typed but both the OpenGraph `<meta name="og:*">` and Twitter `<meta name="twitter:*">` meta tags exist on the mozilla hacks article HTML pages so using the same tags (with different `content` of course) would be nice to bring into Yari. If we don't have a social share image generator (eg an image with text specific to that pages content), then using the same [mdn-web-docs-vector-logo](https://hacks.mozilla.org/files/2020/10/mdn-web-docs-vector-logo.png) as the mozilla hacks article page summary cards would do the trick.

<img width="1027" alt="Screen Shot 2021-04-22 at 8 18 12 PM" src="https://user-images.githubusercontent.com/48612525/115813372-e57d6b80-a3a7-11eb-86ab-a20b226c81c4.png">

**Comment by peterbe** [comment]
I don't think it would be hard to inject. But is it worth it? It probably is because people do use Twitter no matter what you might think about proprietary bloat that fills up your HTML. 
I do wonder, if we instead go for the OpenGraph HTML meta tags, will Twitter be able to build a pretty card out of that?

**Comment by tannerdolby** [comment]
Yeah, it doesn't seem hard to inject. I think it is worth it. There are so many people using MDN (and potentially sharing links on social media) that having a summary card appear rather than just a plain link would be better. 

If we instead go for only the OpenGraph meta tags, ie 

```html
<head>
  <meta name="og:title" content="{{ title }} - Learn web dev | MDN">
  <meta name="og:type"  content="website">
  ...
</head>
```

Then browsers will only have a social share card for Facebook and Twitter won't be able to render one. Unless we use the information from each of the OpenGraph tags to populate the Twitter card meta tags eg:

```js
const $head = $('head');

$('meta').each((i, elem) => {
    let $meta = $(elem);
    let name = $meta.attr('name');
    let content = $meta.attr('content');
  
    switch (name) {
      case "og:title":
        $head.append(`<meta name='twitter:title' content='${content}'>`);
      	break;
      case "og:url":
        $head.append(`<meta name='twitter:site' content='@MozDevNet'>`);
      	break;
      case "og:type":
        $head.append(`<meta name='twitter:card' content='summary_large_image'>`);
      	break;
      case "og:description":
        $head.append(`<meta name='twitter:description' content='${content}'>`);
     	break;
      case "og:image":
        $head.append(`<meta name='twitter:image' content='${content}'>`);
      	break;
      case "og:image:alt":
        $head.append(`<meta name='twitter:image:alt' content='${content}'>`);
      	break;
      default:
       // maybe append some default Twitter meta tags if the OpenGraph tags don't exist
    }
});
``` 

which would evaluate these OpenGraph cards

```html
<meta name="og:title" content="MDN Web Docs">
<meta name="og:type"  content="website">
<meta name="og:url" content="https://developer.mozilla.org/en-US/">
<meta name="og:description" content="Some description text for the page">
<meta name="og:image" content="https://foobar.com/some-image.jpg">
<meta name="og:image:alt" content="Some alt text">
```
and spit out 

```html
<meta name="twitter:title" content="MDN Web Docs">
<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@MozDevNet">
<meta name="twitter:description" content="Some description text for the page">
<meta name="twitter:image" content="https://foobar.com/some-image.jpg">
<meta name="twitter:image:alt" content="Some alt text">
```

**Comment by peterbe** [comment]
First of all, we don't have images, which is a shame. I sometimes wish we could take a screenshot of the page (without the header and sidebar) and make that the image. 
But I think my point is that 362 worth of bytes to add to the HTML. On top of the OpenGraph ones. 
I'm not super worried about that but the summary string could be a lot larger and then you'll end up including that 4 times.
1. The `<meta name="description">`
2. The Twitter one
3. the OpenGraph one
4. The summary within the HTML page itself

So which websites can use and benefit from the OpenGraph tags?

By the way, I don't mind adding these so much. But the proprietary bloat of bending to Twitters will is a bit annoying so I'm also not rushing to it :)

**Comment by Ryuno-Ki** [comment]
Although Facebook is the most known consumer of [Open Graph protocol](https://ogp.me/), the circumstance that it is based on RDFa protocol allows for other crawlers to also understand it. Google is listed towards the end of that page.

Twitter is entirely proprietary here …

**Comment by peterbe** [comment]
On https://developer.twitter.com/en/docs/twitter-for-websites/cards/guides/getting-started under the heading "Twitter Cards and Open Graph" it says

> "When the Twitter card processor looks for tags on a page, it first checks for the Twitter-specific property, and if not present, falls back to the supported Open Graph property. This allows for both to be defined on the page independently, and minimizes the amount of duplicate markup required to describe content and experience."

So, let's reinstate the Open Graph meta tags and see how Twitter handles that.

**Comment by tannerdolby** [comment]
> First of all, we don't have images, which is a shame. I sometimes wish we could take a screenshot of the page (without the header and sidebar) and make that the image.

@peterbe We could but it's a bit of setup. If we had a sort of social share image generator that happens at build time, maybe using puppeteer to load the page and take a screenshot of the document with certain dimensions (to not include header and sidebar)

```
page.screenshot({
  path: '/someDir/splat',
  type: 'jpeg',
  clip: { x: 0, y: 0, width: 800, height:  
});

```
and have the background be an image or some color that would handle generating the social share image and then the image output to some dir can be accessed via URL `assets/generated-social.jpg`

**Comment by tannerdolby** [comment]
> So, let's reinstate the Open Graph meta tags and see how Twitter handles that.

Completely agree. Thanks for posting that bit from Twitter card reference, I wasn't aware that the processor would fallback to the supported OpenGraph property. Seems like the last bit of the puzzle would just be generating images for the OpenGraph tag.

**Comment by peterbe** [comment]
> > First of all, we don't have images, which is a shame. I sometimes wish we could take a screenshot of the page (without the header and sidebar) and make that the image.
> 
> @peterbe We could but it's a bit of setup. If we had a sort of social share image generator that happens at build time, maybe using puppeteer to load the page and take a screenshot of the document with certain dimensions (to not include header and sidebar)
> 
> ```
> page.screenshot({
>   path: '/someDir/splat',
>   type: 'jpeg',
>   clip: { x: 0, y: 0, width: 800, height:  
> });
> ```
> 
> and have the background be an image or some color that would handle generating the social share image and then the image output to some dir can be accessed via URL `assets/generated-social.jpg`

In the past, I've used a service where you just point to a URL and it generates (and caches!) the screenshots based on something like puppeteer. Perhaps if you can combine it with a CSS selector or something to make it without the header and sidebar it could be neat. But it's bound to get very expensive at our scale. 

Let's park that discussion for another day. Let's focus on Open Graph :)

**Comment by tannerdolby** [comment]
@peterbe That sounds like a neat service! Yeah combining with some sort of selector or bit to make the dimensions not include the header or sidebar that'd be nice, but if it's very expensive with scale probably best to park for later.

Open Graph it is :)

**Comment by Ryuno-Ki** [comment]
Dropping https://docs.htmlcsstoimage.com/ which is used by forem (dev.to) => new issue?

**Comment by tannerdolby** [comment]
@Ryuno-Ki That's a really neat tool. Could definitely be useful down the line to generate the social share image for each SPA page. The current setup in #3623 renders a social card from the Open Graph meta tags for each social site besides Twitter, which should work as the twitter validator falls back to the Open Graph tags as Peter mentioned above from the docs. But it doesn't seem to be working as the docs say.

**Comment by peterbe** [comment]
> Dropping https://docs.htmlcsstoimage.com/ which is used by forem (dev.to) => new issue?

Discussion first. Then if we decide to act on it, discussions can be turned into issues. 
(Bugs don't need to go that route. Nor feature topics that have been discussed offline)

**Comment by Ryuno-Ki** [comment]
Alright. https://github.com/mdn/yari/discussions/3638
