### ISSUE TITLE
EmbedLiveSample breaks if ID has umlauts

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3598]
```html
<h3 id="Positionnement_adhérent">Positionnement adhérent (<em>sticky</em>)</h3>
...
<p>{{EmbedLiveSample('Positionnement_adhérent', '500px', '300px')}}</p>
```
fails with: `Error: No live-sample "positionnement_adh%c3%a9rent" found within /fr/docs/web/css/position`

But changing it to 
```html
<h3 id="Positionnement_adherent">Positionnement adhérent (<em>sticky</em>)</h3>
...
<p>{{EmbedLiveSample('Positionnement_adherent', '500px', '300px')}}</p>
```
works. (the only change I did was change `é` to `e`)

**Comment by peterbe** [comment]
I first discovered this on http://localhost:3000/fr/docs/Web/CSS/position#_flaws and thought it was related to the `_(sticky)` part of the ID. But deleting it didn't resolve the problem. Perhaps that's a problem too but first of all we should recover better for Unicode characters.

**Comment by peterbe** [comment]
Working on https://github.com/mdn/yari/issues/3640 might be better.

**Comment by caugner** [comment]
This seems to be working now, see: https://developer.mozilla.org/fr/docs/Learn/Forms/How_to_build_custom_form_controls/Example_5

https://github.com/mdn/translated-content/blob/08853fc1585ec7c62e0ad3e938e97c520930eb13/files/fr/learn/forms/how_to_build_custom_form_controls/example_5/index.md?plain=1#L297
