### ISSUE TITLE
limit display of non-English content to the top 10 locales

### ISSUE THREAD

**Issue by escattone** [mdn/yari#3642]
### Reference
https://hacks.mozilla.org/2021/03/mdn-localization-in-march-tier-1-locales-unfrozen-and-future-plans/

### Summary
On April 29/30, we will stop displaying all except the top 10 non-English locales, which are `fr`, `ru`, `ja`, `ko`, `zh-CN`, `zh-TW`, `es`, `de`, `pl`, and `pt-BR`.

- [x] Move the other 22 non-English locales out of https://github.com/mdn/translated-content and into the https://github.com/mdn/retired-content repository.
- [x] Update `VALID_LOCALES` to reflect this change:

    https://github.com/mdn/yari/blob/d4fd6673ad5bdae1647938b427e65e8ea0d1961f/libs/constants/index.js#L1

- [x] Retire the selected 22 non-English locales in Kuma 
- [x] Deploy updated versions of the lambda@edge functions that use `VALID_LOCALES`
- [x] Add redirects for all requests for documents in the 22 dropped locales to their English equivalents.
- [ ] Add note/banner to at least the doc pages that explains the reason for the redirect.

**Comment by peterbe** [comment]
Let's do it!

**Comment by peterbe** [comment]
>     4\. Add redirects for all requests for documents in the 22 dropped locales to their English equivalents.

Is this the case? We could just send them to the 404 page, which should almost always have that "Good news! Here's the document in English" link.
I'm not even sure what I prefer 🙃

What do you think @Gregoor @chrisdavidmills @schalkneethling ?

The question is; when someone types in <https://developer.mozilla.org/sv-SE/docs/Web> should they get immediately redirected to <https://developer.mozilla.org/en-US/docs/Web> or should they get the "Page not found" page with a 404 HTTP error code?

**Comment by chrisdavidmills** [comment]
> What do you think @Gregoor @chrisdavidmills @schalkneethling ?

This is potentially a large number of wasted clicks from people coming to the 404 and then clicking through to the English page. I'd prefer to redirect them straight to the English page but then show a banner saying something like "The page you requested no longer exists, so we've sent you to the English equivalent." so they have the context of what happened.

**Comment by peterbe** [comment]
> > What do you think @Gregoor @chrisdavidmills @schalkneethling ?
> 
> This is potentially a large number of wasted clicks from people coming to the 404 and then clicking through to the English page. I'd prefer to redirect them straight to the English page but then show a banner saying something like "The page you requested no longer exists, so we've sent you to the English equivalent." so they have the context of what happened.

Yeah, I guess it's possible to write something like this in the Lambda code:

```javascript
// Somewhere deep in the fundamental redirects code
const locale = getLocale(url)
if (['sv-se', 'uk', 'bn', ...].includes(locale)) {
  return redirect(302, url.replace(locale, 'en-US') + `?retiredlocale=${locale}`)
}
```

Then the Lambda code will take of giving us a hint on the client-side. And then we can write some React code that throws up a banner if you have `?retiredlocale=...` in the URL. 

We probably need to act quite fast if we're going to implement this before April 29 :)

PS. I'm out on Friday this week.

**Comment by escattone** [comment]
@peterbe Let's work together on this tomorrow.

**Comment by chrisdavidmills** [comment]
OK, update text suggestion:

The page you requested has [been retired](https://hacks.mozilla.org/2021/03/mdn-localization-in-march-tier-1-locales-unfrozen-and-future-plans/), so we've sent you to the English equivalent.

Optionally, we could also include a link to the source of the original, something like

The page you requested has [been retired](https://hacks.mozilla.org/2021/03/mdn-localization-in-march-tier-1-locales-unfrozen-and-future-plans/), so we've sent you to the English equivalent (see also the [retired page source code](LINK TO GH SOURCE PAGE)).

**Comment by schalkneethling** [comment]
100% Agree with @chrisdavidmills suggestion. When we do this, we can reuse the localized notes feature to display the message.

**Comment by escattone** [comment]
@schalkneethling @chrisdavidmills @peterbe @Gregoor If we decide to go with showing some kind of note to those that get redirected from a retired locale, would we need to show that on all of the SPA's (home page, search page, doc page, settings page, etc.) or just the doc pages?

**Comment by schalkneethling** [comment]
> @schalkneethling @chrisdavidmills @peterbe @Gregoor If we decide to go with showing some kind of note to those that get redirected from a retired locale, would we need to show that on all of the SPA's (home page, search page, doc page, settings page, etc.) or just the doc pages?

I reckon just the docs pages would be fine.

**Comment by escattone** [comment]
@schalkneethling Would you take on the work for this [last step of displaying the reason for the redirect](https://github.com/mdn/yari/issues/3642#issuecomment-829366459) when we're redirecting document pages in retired locales? The redirects are already in place, so you'll get a `retiredLocale=XX` parameter in the query string for those cases. I think we should continue to use this issue (I added a checklist item in the introduction for that step).

**Comment by schalkneethling** [comment]
> @schalkneethling Would you take on the work for this [last step of displaying the reason for the redirect](https://github.com/mdn/yari/issues/3642#issuecomment-829366459) when we're redirecting document pages in retired locales? The redirects are already in place, so you'll get a `retiredLocale=XX` parameter in the query string for those cases (e.g., https://developer.mozilla.org/en-US/docs/Web/CSS?retiredLocale=ar). I think we should continue to use this issue (I added a checklist item in the introduction for that step).

Consider it done 😸

**Comment by escattone** [comment]
Thanks @schalkneethling!
