### ISSUE TITLE
Improvements for web scraping

### ISSUE THREAD

**Issue by MasterEnoc** [mdn/yari#3644]
I have been working adding support for the compatibility tables in [Devdocs](https://www.devdocs.io), Devdocs uses ruby to scrap the mdn pages, now that the compatibility tables are added dinamically while generating the page, a new way to add the tables is needed. I wanted to use the files directly but it can be a burden to use this files because there is no indication, in the scraped pages, about where to find its json file.

I decided to use the URL of each page as a base path to search for its respective json file, this sometimes works and sometimes the URL has a completely different path in regards to its json file.

For example:
[SVG/Attribute/yChannelSelector](https://developer.cdn.mozilla.net/en-US/docs/Web/SVG/Attribute/yChannelSelector) is the base path I would use to find the json file of the compatibility data of this page, but the json file can be found in [svg/elements/feDisplacementMap](https://github.com/mdn/browser-compat-data/blob/main/svg/elements/feDisplacementMap.json), the URL is different of the location of the json file.

Maybe a different message could be added to the content files, i.e,  a message telling where to find the json files rather than this:
![image](https://user-images.githubusercontent.com/52229226/116174725-36ed6980-a6cc-11eb-9ad2-d918f3352c48.png)

**Comment by peterbe** [comment]
When you scrape, perhaps open https://developer.cdn.mozilla.net/en-US/docs/Web/SVG/Attribute/yChannelSelector/index.json and look through the `body[]` thing and if it looks like this:
<img width="634" alt="Screen Shot 2021-04-27 at 5 41 43 PM" src="https://user-images.githubusercontent.com/26739/116316372-d7509600-a77f-11eb-9b6b-ec3c5562a872.png">

you know which URL you need to get the BCD data.

**Comment by MasterEnoc** [comment]
This worked for me, thank you. Just one question, do you know why this page https://developer.mozilla.org/en-US/docs/Web/XSLT/Element/stylesheet does not have an index.json file? I

**Comment by peterbe** [comment]
<https://developer.mozilla.org/en-US/docs/Web/XSLT/Element/stylesheet/index.json> is 200 OK for me.
