### ISSUE TITLE
PDF printing looks weird now

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3647]
Somewhere along the timeline when we changed the DOM and its CSS (I'm thinking; when we rearrange so the breadcrumb appears above the title) it probably broke our print CSS. 

In Firefox when I load https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video and click to download to PDF I get this:
<img width="1111" alt="Screen Shot 2021-04-27 at 3 33 14 PM" src="https://user-images.githubusercontent.com/26739/116301361-f2b2a580-a76d-11eb-86d9-e01e741d52fd.png">
<img width="1087" alt="Screen Shot 2021-04-27 at 3 33 24 PM" src="https://user-images.githubusercontent.com/26739/116301366-f3e3d280-a76d-11eb-96a2-b636eecd6275.png">
<img width="1092" alt="Screen Shot 2021-04-27 at 3 33 31 PM" src="https://user-images.githubusercontent.com/26739/116301369-f5ad9600-a76d-11eb-8ed4-eda28f4d9c9f.png">

**Comment by peterbe** [comment]
I also wonder if we can safely drop all horizontal margin/padding to 0. Because the printing will add its own margin.

**Comment by peterbe** [comment]
Curiously, it looks a LOT better in Chrome. Not sure what to think/make of that. 
<img width="1404" alt="Screen Shot 2021-04-27 at 3 35 23 PM" src="https://user-images.githubusercontent.com/26739/116301568-31e0f680-a76e-11eb-833b-a05e1696d85d.png">

**Comment by peterbe** [comment]
Lots of inspiring ideas here: https://www.matuzo.at/blog/i-totally-forgot-about-print-style-sheets/

**Comment by Ryuno-Ki** [comment]
Related to https://github.com/mdn/yari/issues/2299 ?

Where do you „click to download”? Native print dialog via Ctrl-P? Or do we have a button (like Wikipedia's export) somewhere?

**Comment by peterbe** [comment]
> Related to #2299 ?
> 
> Where do you „click to download”? Native print dialog via Ctrl-P? Or do we have a button (like Wikipedia's export) somewhere?

No. Not related.

**Comment by caugner** [comment]
No longer reproducible.
