### ISSUE TITLE
Yarn command stuck in loop between install and postinstall

### ISSUE THREAD

**Issue by jpmedley** [mdn/yari#365]
`package.json` defines:

```"scripts": {
    "postinstall": "cd stumptown && npm install && git checkout package-lock.json",
    ...
  }
```

Because install is launched again, `postinstall` is reinvoked, and `install` is reinvoked, and...turtles all the way down. Screen output looks something like this:

![image](https://user-images.githubusercontent.com/8204171/75482807-608cf280-595a-11ea-92a7-2c77f772f1b4.png)

**Comment by jpmedley** [comment]
By the way, this is triggered when entering the `yarn` command at [Development section](https://github.com/mdn/stumptown-renderer#development) of the instructions.

**Comment by peterbe** [comment]
Remove the `postinstall` piece in the `package.json` file and try again. 
A fix is coming.

**Comment by peterbe** [comment]
Problem long-gone now.
