### ISSUE TITLE
https://learning.mozilla.org/web-literacy  link not working

### ISSUE THREAD

**Issue by MathivannanChandran** [mdn/yari#3656]
following link is not working 

https://learning.mozilla.org/web-literacy

**Comment by peterbe** [comment]
Where are you seeing this?

**Comment by peterbe** [comment]
Go to the page on MDN where this link appears. Then scroll to the bottom of the page and use the "Report a problem with this content on GitHub" link. Thanks in advance!

**Comment by Ryuno-Ki** [comment]
Grepped the source code and find the reference in https://developer.mozilla.org/en-US/docs/Glossary/World_Wide_Web#learn_about_it („Web literacy map”).

This line needs an update:

https://github.com/mdn/content/blob/e36a7213f866fd96f3da87312232d2dbcb668cdb/files/en-us/glossary/world_wide_web/index.html#L32

(Can you reopen and move to mdn/content, @peterbe ?)
