### ISSUE TITLE
Server start error due to _githistory.json [retired languages]

### ISSUE THREAD

**Issue by tristantheb** [mdn/yari#3665]
Following the deletion of the locales that were moved to a new repository, the Yari server throws an error for these locales when trying to launch it because it cannot find the `_githistory.json`.

To fix the server on my side, I reset my main branch before the deletion and restarted the server to at least have the `_githistory.json` once and not have any more problems, but users who will create the server with `yari`, `content` and `translated-content` might get an error to tell them that `/ar/_githistory.json` doesn't exist and the same for the other locales deleted from `translated-content`.

And on the Window side, nothing worked: `yarn build` returns an error, `yarn dev` returns an error. For the moment I have to keep the `_githistory.json` to be able to launch the server.

Maybe something needs to change on the Yari side so that withdrawn locals are not caught looking for them?

**Comment by escattone** [comment]
@tristantheb This was my fault, sorry! I have a fix for this already in https://github.com/mdn/yari/pull/3661 which I'll pull out of that pull request and get merged today. Thanks for reporting!

**Comment by escattone** [comment]
@tristantheb I realized that my idea of a quick fix wouldn't work without pulling in more of #3661, so I decided to wait until Monday for the review/merge of #3661 to fix this issue. Sorry again for the inconvenience.

**Comment by tristantheb** [comment]
Hello :)

Thanks for the information ^^ It's more for the people who will want to set this up than for the people who already have it that it will be problematic, because those who have already done the setup before the retirement of the languages, we automatically kept the `_githistory.json`, the latter not being tracked by Git ^^

**Comment by peterbe** [comment]
I'm confused. Ryan's changes haven't landed yet.
