### ISSUE TITLE
BCD no longer updating?

### ISSUE THREAD

**Issue by ddbeck** [mdn/yari#3669]
As best as I can tell, the last time BCD was updated was [17 days ago](https://github.com/mdn/yari/pull/3532) and there have been no further updates, based on [this PR search](https://github.com/mdn/yari/pulls?q=is%3Apr+%22%40mdn%2Fbrowser-compat-data%22). Yari is running `@mdn/browser-compat-data` v3.3.0 and hasn't picked up v3.3.1 or v3.3.2:

https://github.com/mdn/yari/blob/2962fab35ce96a2d7071b031a702ef131ebc8860/package.json#L48

I can't figure out why this has happened, however.

Is there a reason BCD updates have stopped? What needs to happen for BCD updates to resume?

**Comment by Gregoor** [comment]
<img width="914" alt="Screenshot 2021-05-03 at 13 01 01" src="https://user-images.githubusercontent.com/4051932/116868773-ae148780-ac0f-11eb-80f1-0de5c2603eef.png">
looks like triaging dependabot should be a high priority item for us. I will start working through the ones I know how to work on now.

**Comment by Gregoor** [comment]
https://github.com/mdn/yari/pull/3679
there it is, we are unclogged (for now)

**Comment by peterbe** [comment]
We also increased the number of open PRs allowed. 
@Gregoor cleared the pipes a bunch so hopefully, it'll be a lot less likely to happen again.
