### ISSUE TITLE
yarn build cannot find module 'gray-matter'

### ISSUE THREAD

**Issue by jpmedley** [mdn/yari#367]
I'm getting this message when I run `yarn build`:

```
Error: Cannot find module 'gray-matter'
```

I cannot proceed because I don't know which workspace this belongs in.

**Comment by jpmedley** [comment]
@peterbe

**Comment by peterbe** [comment]
Thanks. I'll need a couple of days and then I can land a massive refactor to all that stuff. That'll hopefully make this individual detail resolved. But let's wait and see.

**Comment by jpmedley** [comment]
How is the refactor coming?

**Comment by peterbe** [comment]
> How is the refactor coming?

One caveat is that even when this lands it'll be hard to play with because it's going to require that you have a database dump from production which isn't easy. But if you can figure out a way to dump your Kuma mysql database into your host mysql, it should work.

**Comment by peterbe** [comment]
Now moot.
