### ISSUE TITLE
Support ESM module loading

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#3673]
We have a number of packages we can't update yet, because they can only be run from an ESM context. Afaik we'd either have to change all our file endings to `.mjs` or change the root `package.json`'s `type` to `module`, which I assume has some other implications (more later). The PR for the affected packages reference this issue, and thus can be seen below. Note that all but one are related to our unified Markdown<->HTML pipeline

**Comment by peterbe** [comment]
How about we just try to change package.json and see what happens. If you do that, can you keep using `require(...)` or do you have to also change them to ESM imports in the same sweep?
I'd rather not have to call some files `.mjs` if there are better options. 

PS. Yes, we should entirely get away from CommonJS and we can orchestrate a coordinated mass edit but we have to be sure it's not breaking old stuff too.

**Comment by Gregoor** [comment]
I gave it a try but am getting an internal webpack error now a la
```
2:20:20 PM ssr.1        |  Error: Cannot find module '/Users/gregor/code/mozilla/yari/node_modules/terser-webpack-plugin/dist/worker.js'
2:20:20 PM ssr.1        |  Require stack:
2:20:20 PM ssr.1        |  - /Users/gregor/code/mozilla/yari/node_modules/worker-farm/lib/child/index.js
2:20:20 PM ssr.1        |      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
2:20:20 PM ssr.1        |      at Function.Module._load (node:internal/modules/cjs/loader:769:27)
2:20:20 PM ssr.1        |      at Module.require (node:internal/modules/cjs/loader:996:19)
2:20:20 PM ssr.1        |      at require (node:internal/modules/cjs/helpers:92:18)
2:20:20 PM ssr.1        |      at process.<anonymous> (/Users/gregor/code/mozilla/yari/node_modules/worker-farm/lib/child/index.js:53:34)
2:20:20 PM ssr.1        |      at process.emit (node:events:369:20)
2:20:20 PM ssr.1        |      at emit (node:internal/child_process:920:12)
2:20:20 PM ssr.1        |      at processTicksAndRejections (node:internal/process/task_queues:82:21) {
2:20:20 PM ssr.1        |    code: 'MODULE_NOT_FOUND',
2:20:20 PM ssr.1        |    requireStack: [
2:20:20 PM ssr.1        |      '/Users/gregor/code/mozilla/yari/node_modules/worker-farm/lib/child/index.js'
2:20:20 PM ssr.1        |    ]
2:20:20 PM ssr.1        |  }
```

Will do some more thinking about what it means

**Comment by caugner** [comment]
Resolved via https://github.com/mdn/yari/pull/7623.
