### ISSUE TITLE
Add an og:image HTML meta tags

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3693]
If we add a 
`<meta property="og:image" content="...URL...">` the preview of an MDN URL will look better in places like Twitter. 

The question is;
1) Which image should we use?
2) What should the `og:image:alt` be?
3) How can we include it in the build so it gets a nicely hashed name?

_Originally posted by @peterbe in https://github.com/mdn/yari/issues/3623#issuecomment-831508111_

**Comment by peterbe** [comment]
@schalkneethling (CC @tannerdolby ) do you have a suggestion for a good image to use for the Open Graph `og:image` HTML meta tag?

**Comment by peterbe** [comment]
@tannerdolby Do you know what size it ought to be? Does Open Graph or Twitter have any strong recommendations for a minimum?

**Comment by schalkneethling** [comment]
> @schalkneethling (CC @tannerdolby ) do you have a suggestion for a good image to use for the Open Graph `og:image` HTML meta tag?

https://github.com/mdn/yari/pull/3623#issuecomment-831152587 - this one? It is sized correctly and optimized. Well, not the one embedded there, but I can send you the original PNG, optimized etc.

**Comment by schalkneethling** [comment]
How about this one?

![mdn-social-share](https://user-images.githubusercontent.com/10350960/117035193-5146c900-ad04-11eb-9f6f-e703192aafe3.png)

**Comment by tannerdolby** [comment]
@peterbe 600 x 315 (px) is the minimum "best practices" dimension from the Twitter docs.

**Comment by schalkneethling** [comment]
> @peterbe 600 x 315 (px) is the minimum "best practices" dimension from the Twitter docs.

I find that doing double that 1200 x 630 ensures it works across all sites and sites like Twitter will simply scale it down if need be.

**Comment by tannerdolby** [comment]
@schalkneethling I agree.

**Comment by peterbe** [comment]
Let's do it! Can you send me that PNG @schalkneethling and I'll get it in.

**Comment by schalkneethling** [comment]
> Let's do it! Can you send me that PNG @schalkneethling and I'll get it in.

sent via email.

**Comment by peterbe** [comment]
@tannerdolby Do you know if the URL always has to be absolute? I.e. starting with `https://developer...`

**Comment by tannerdolby** [comment]
@peterbe Yeah I think the URL for the `og:image` needs to be absolute just like the canonical URL tag. 

I've never tried using a relative path, but it might be ok. I can't find anywhere specifically in Open Graph or Twitter card docs that says a relative path "isn't allowed", I have yet to try using anything other than an absolute URL.

**Comment by tannerdolby** [comment]
@peterbe Is there a `process.env.URL` or something similar that you could grab the absolute URL from? Or is the image asset not available currently from the absolute URL?

**Comment by peterbe** [comment]
> Is there a `process.env.URL` or something similar that you could grab the absolute URL from? Or is the image asset not available currently from the absolute URL?

The build is done independently of where it will be served. It's Jamstack, man :)
But what we could do is hardcode it because once it gets uploaded once to developer.mozilla.org it'll more or less always be there. And that's the only URL where it matters. But if we can use a relative URL, it would be nice to be able to test stuff like this on the stage domain.

**Comment by tannerdolby** [comment]
> The build is done independently of where it will be served. It's Jamstack, man :)

Ah, yes that makes sense :) I think I'm just use to Netlify providing `process.env.URL` along with some other environment variables, it was the first thing I reached for.

Yeah, hardcoding the URL would probably be the least fuss. I will pull into this branch and check things out locally, how did you kickoff a complete build to the dev server for a feature branch like you [did here](https://github.com/mdn/yari/pull/3623#issuecomment-825924010)? We could then test stuff like you mentioned using a relative URL with the card validators.

**Comment by schalkneethling** [comment]
I have also never used it any other way than with an absolute URL. Twitter is not as specific as the OpenGraph docs and just says URL: https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup

But I guess they mean the same thing.

**Comment by peterbe** [comment]
I'd rather first try it this way. It ought to work. Twitter has many engineers so it shouldn't be hard for them to write some code that combines the `og:image` URL with the base of the site where it comes from.

**Comment by tannerdolby** [comment]
> I'd rather first try it this way. It ought to work.

@peterbe Yeah, agreed.

**Comment by tannerdolby** [comment]
I tried using a relative path for the `og:image` in my 11ty site hosted with Netlify and it doesn't work for rendering the image. The summary card itself loads successfully just without the image. Maybe there is a way of using relative paths but from what I tested it doesn't seem likely.

<img width="654" alt="Screen Shot 2021-05-05 at 9 05 37 AM" src="https://user-images.githubusercontent.com/48612525/117173568-bee50a80-ad81-11eb-8f6f-132485b38d7e.png">

<img width="606" alt="Screen Shot 2021-05-05 at 9 10 51 AM" src="https://user-images.githubusercontent.com/48612525/117173760-f358c680-ad81-11eb-9da8-379d8bb19d5a.png">

**Comment by peterbe** [comment]
What if you test with that page on the real Twitter?

**Comment by tannerdolby** [comment]
I didn't try that, let me see

**Comment by tannerdolby** [comment]
Card renders but is missing the image on Twitter.

<img width="616" alt="Screen Shot 2021-05-05 at 9 26 42 AM" src="https://user-images.githubusercontent.com/48612525/117175758-08cef000-ad84-11eb-8a1d-3c8c96871c29.png">

**Comment by peterbe** [comment]
Alright. I'll force it to be `https://developer.mozilla.org`

**Comment by tannerdolby** [comment]
Ok sounds good.

**Comment by peterbe** [comment]
So, in the next 24h, roughly, we'll be able to test prod on Twitter to see if it works now that we have all the Open Graph tags, including `og:image`. 
If Twitter cards look nice, great, but I suspect the next action is to add the `<meta name="twitter:card" content="summary_large_image">` for it to really look good.

**Comment by peterbe** [comment]
Not that I read it but I skimmed https://flayyer.com/blog/posts/github-cards and it looks cute. 
If we really wanted to, I think https://flayyer.com/pricing is very reasonable.

**Comment by peterbe** [comment]
@tannerdolby It's clearly still not "working" on https://cards-dev.twitter.com/validator but I don't even know how to test this on Twitter. I don't know how to preview a tweet with a URL in it. Or to preview a tweet with or without a URL. 
Do you literally have to post the tweet and then delete it?

Either way, I don't think it'll be hard to inject the `twitter:card` meta tag next.

**Comment by tannerdolby** [comment]
> Do you literally have to post the tweet and then delete it?

@peterbe That is one way to test if the Twitter validator is rendering the card and displaying it in the tweet, like mentioned in number 1 below.

Yeah I just had a look and its clearly still not rendering a summary card on https://cards-dev.twitter.com/validator. To my understanding there are three ways to test if a summary card is rendering for Twitter or Open Graph:

1. Paste the URL into a tweet and see if it populates a summary card in the tweet preview, or use https://cards-dev.twitter.com/validator and make sure the card is being rendered and displays correctly.

<img width="996" alt="Screen Shot 2021-05-12 at 9 56 14 AM" src="https://user-images.githubusercontent.com/48612525/118014907-907aa880-b308-11eb-901d-9a95949e36ef.png">
<img width="616" alt="Screen Shot 2021-05-12 at 9 55 58 AM" src="https://user-images.githubusercontent.com/48612525/118014913-92446c00-b308-11eb-9c47-30fe8b74bbd7.png">

2. Use the Facebook open graph validator or https://www.opengraph.xyz/

**Comment by tannerdolby** [comment]
> Either way, I don't think it'll be hard to inject the twitter:card meta tag next.

@peterbe Agreed. Once a `<meta name="twitter:card" content="summary_large_image">` is added, everything should render as expected.

**Comment by peterbe** [comment]
>     1. Paste the URL into a tweet and see if it populates a summary card

But you press the "Tweet" button to actually send it out? 
I thought it would start to display the preview as you're in the middle of typing it. Not sure if that's a valid test.

**Comment by tannerdolby** [comment]
Before pressing the "Tweet" button to actually send it out, if the URL has a valid Twitter summary card it will display in the tweet preview area (before) you click the "Tweet" button and sent it.

**Comment by tannerdolby** [comment]
The way I look at it is, the https://cards-dev.twitter.com/validator is running in the background when a URL is pasted into a tweet (before sending it) and will render the card preview in the tweet as a nice reminder of what it will look like before you actually do "Tweet" it out.

**Comment by tannerdolby** [comment]
The image meta tag is on the page from your PR which is good news,

```
<meta property="og:image" content="https://developer.mozilla.org/mdn-social-share.2f09512a.png">
```

so once the `twitter:site` tag is injected everything will look nicely.

**Comment by peterbe** [comment]
> so once the `twitter:site` tag is injected everything will look nicely.

Uh? 
Do we add that or `<meta name="twitter:card" content="summary_large_image" />` or both?

**Comment by tannerdolby** [comment]
@peterbe That was a typo on my end, meant to say `twitter:card`. All we need to add is the `<meta name="twitter:card" content="summary_large_image">` for Twitter to fallback to the Open Graph tags and render a card.

**Comment by peterbe** [comment]
WOHOO!!
<img width="1084" alt="Screen Shot 2021-05-13 at 7 05 26 AM" src="https://user-images.githubusercontent.com/26739/118117548-c3c94000-b3b9-11eb-8295-5e00d8551c2f.png">

**Comment by Ryuno-Ki** [comment]
> I don't even know how to test this

FWIW I'm using https://addons.mozilla.org/en-GB/firefox/addon/openlink-structured-data-sniff/ to check whether parsing works at least.

**Comment by tannerdolby** [comment]
YIPPIE! 🎉 🎉  It looks great @peterbe
