### ISSUE TITLE
AvailableInWorkers.ejs should take take a smart optional argument

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#3708]
This follows on from discussion here: https://github.com/mdn/content/pull/4145#issuecomment-831950259

We have one macro for adding supported by workers, but there are [four worker types](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API#worker_types) and a method may not be supported by all of them. We recently added a free text argument to allow this to be specified, but it would be better if this was an option/enum to ensure the text is always consistent.

The four types of workers are: dedicated, shared, service and chrome. We want a default that is the same as currently that just says supported in workers, and implies in all workers. Otherwise I'm not sure about how we should enter the options because I don't know what combinations are realistic - i.e. we probably have "all workers except service workers" and "only service workers" and "dedicated workers only" etc

**Comment by hamishwillee** [comment]
PS As an aside, I don't think we can generate the macro reliably from the BCD at the moment because that stores this level of detail in the notes.

**Comment by peterbe** [comment]
> PS As an aside, I don't think we can generate the macro reliably from the BCD at the moment because that stores this level of detail in the notes.

Can we progressively solve that? Can we ask the browser-compat project to move that from notes into an "official field" in the JSON objects?

**Comment by hamishwillee** [comment]
>> PS As an aside, I don't think we can generate the macro reliably from the BCD at the moment because that stores this level of detail in the notes.

> Can we progressively solve that? Can we ask the browser-compat project to move that from notes into an "official field" in the JSON objects?

@ddbeck As you know, we're "generally" trying to fetch more compatibility data from BCD rather than duplicate it in MDN source (e.g. like specs, deprecation info, etc).

On case that is problematic is web workers. We have a feature to indicate that they are supported, and use notes to document the exceptions - e.g. "not supported in shared workers", "only supported in service workers". What that means is that the best we can do is pull in any note text associated with a parent web_worker feature (which is likely to not be so great in an MDN context).

Any thoughts on whether we might have finer granularity, and if so, how it would be done/alternatives?
