### ISSUE TITLE
Is there a way to run translated-content in yari?

### ISSUE THREAD

**Issue by hochan222** [mdn/yari#3730]
Hello!
I want to check the PR fixes of translated-content with yari. Is there any way to check? I asked a question because the execution method for translated-content is not specified.

First of all, the content repo was successfully executed. It comes out well.

- .env
```
CONTENT_ROOT=/Users/tonybyeon/Desktop/content/files
EDITOR=code
```
<img src="https://user-images.githubusercontent.com/22424891/117282705-019d0480-aea0-11eb-8894-f661357c86fd.png" height="300px" />

---

However, it fails when running on translated-content. 

- .env
```
CONTENT_ROOT=/Users/tonybyeon/Desktop/translated-content/files
EDITOR=code
```
<img src="https://user-images.githubusercontent.com/22424891/117283421-bb947080-aea0-11eb-8db8-49de6929025a.png" height="300px" />

If this is not possible, how do I check for changes to the translated-content?

---

I'll make it. => See comments below.

**Comment by hochan222** [comment]
Ah! There was more CONTENT_TRANSLATED_ROOT...

https://github.com/mdn/translated-content

**Comment by peterbe** [comment]
Perhaps the best solution is to enable the PR Review Companion for translated-content. 
We only recently launched that for the mdn/content repo but we're not yet doing it for translated-content. Would you be interested in helping out with that?

**Comment by hochan222** [comment]
Of course. I am lacking in experience, but if you understand, I would like to contribute if there is a chance.
What does PR Review Companion specifically mean? Where can I start?

**Comment by peterbe** [comment]
The "PR Review Companion" is a GitHub Action workflow. It's a workflow that runs after the "PR Test" workflow has succeeded. 
https://github.com/mdn/content/blob/main/.github/workflows/pr-review-companion.yml
https://github.com/mdn/content/blob/main/.github/workflows/pr-test.yml

Compare that `pr-test.yml` with the one in translated-content: https://github.com/mdn/translated-content/blob/main/.github/workflows/pr-test.yml
For example, note that in translated-content it doesn't upload the build files. 
Your first task is to try to port the stuff from `pr-test.yml` into the one in translated-content. Once that's done you can more or less copy the `pr-review-companion.yml` over too with some changes.

**Comment by hochan222** [comment]
Thank you. I'll try it.

### Progress
- [x] try Git Actions
- [x] try @caporal/core
- [ ] try to port the stuff from pr-test.yml into the one in translated-content.
- [ ] more or less copy the pr-review-companion.yml over too with some changes.

**Comment by hochan222** [comment]
I would like to see if what I am doing is correct. 

1. yari has a dependency on CONTENT_ROOT. 
    - I.E. CONTENT_ROOT is required for translated-content to be built.
2. @mdn/yari/build/cli.js handles CONTENT_ROOT and CONTENT_TRANSLATED_ROOT separately
    - I.E. CONTENT_ROOT for only content repo, CONTENT_TRANSLATED_ROOT for only translated-content repo
3. To upload the build files and run yari self in translated-content, translated-content repo need `package.json`

Is it correct that what I need to do is allow the translated-content repo to run yari alone without the content repo? Or is it only PR check within github actions?

**Comment by hochan222** [comment]
@peterbe  I would like to see if what I am doing is correct. 

1. yari has a dependency on `CONTENT_ROOT`. 
    - I.E. `CONTENT_ROOT` is required for translated-content to be built.
2. @mdn/yari/build/cli.js handles `CONTENT_ROOT` and `CONTENT_TRANSLATED_ROOT` separately
    - I.E. `CONTENT_ROOT` for only content repo, `CONTENT_TRANSLATED_ROOT` for only translated-content repo
3. To upload the build files and run yari self in translated-content, translated-content repo need `package.json`

The reason these matters is because `CONTENT_ROOT` is used in @mdn/yari/build/cli.js, `yarn build` and `yarn start`. So we inevitably need a content repo. 

There are many ways to solve this problem, but is there a way you can recommend? Also, I asked the question below because the method seems to be different depending on the answer to the question below.

Is it correct that what I need to do is allow the translated-content repo to run yari alone without the content repo? Or is it only PR check within github actions?

**Comment by peterbe** [comment]
> Run yari alone with **translated-content repo** independent of **content repo**

Not an option. The translated content is so very much dependent on the content. 
It's not an option to *only* set `CONTENT_TRANSLATED_ROOT` and ignore `CONTENT_ROOT`. Or to pretend that `CONTENT_ROOT` is actually `/path/to/the/translated-content/files`. 
For viewing any translated content, you'll need to have both set.

**Comment by schalkneethling** [comment]
@hochan222 is this still a problem that needs to be addressed? Also see the README here: https://github.com/mdn/translated-content/

**Comment by hochan222** [comment]
Hello @schalkneethling. There was also a change in yari after the issue was created, so it is a lot different from the current situation, but as a result, it works well now. So I'll close the issue. Thanks for the reminder.

**Comment by schalkneethling** [comment]
> Hello @schalkneethling. There was also a change after the issue was created, so it is a lot different from the current situation, but as a result, it works well now. So I'll close the issue. Thanks for the reminder.

Thank you, @hochan222! Glad to hear that things are working better now. 🎉
