### ISSUE TITLE
Attributes for external <a>'s linking to external sites

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#3731]
There's a bit of a UX & product decision to be made with the markdown conversion. Since markdown links can't have attributes such as `target="_blank"` or `rel="noopener nofolow"`, how external links function won't be a content writer decision no more (which might be good because consistency). So would be curious to hear your opinions, here is mine:

- `target="_blank"`
  - aka open in new tab
  - 43 uses in content
  - **Opinion:** Personally not a fan, I think tab management is a user-choice thing, i.e. if they want it in a new tab, they'd use cmd+click / rightclick+open-in-new-tab
- `rel=`
  - `"noopener"`
    - aka disallow linked sites to manipulate our site 
    - 286 uses in content
    - **Opinion:** yes please, though might be unnecessary because modern browsers add that automatically?
  - `"nofollow"`
    - aka tell search engines we don't endorse what's linked (aka don't up their search ranking?)
    - 216 uses in content
    - **Opinion:** Useful content should benefit from us linking to it, seems like the decent thing to do? Or do we really have content we link but don't endorse?

Curious to hear your takes

**Comment by schalkneethling** [comment]
I know we had a conversation around this not too long ago. I cannot remember the exact consensus but, I am thinking that we might want to just not use `_blank` and let the user decide if they want to just follow the link or open in a new tab/window.

I guess one thing would be to look for `href` attributes the do not start with `/` and use that as a hook to add the icon we add for external links. That way a user at least has an indication that the link, links to an external site.

With modern browsers `rel="noopener"` is now also implicitly set so, that protects some of our audience if we do decide to keep somehow using `_blank` (maybe via a cheerio build phase), but it does not protect them all. Just something to keep in mind.

**Comment by escattone** [comment]
> I know we had a conversation around this not too long ago. I cannot remember the exact consensus but, I am thinking that we might want to just not use _blank and let the user decide if they want to just follow the link or open in a new tab/window.

We last discussed this in #2861. I would vote for **not** using `target="_blank"`.

**Comment by Gregoor** [comment]
Thanks Ryan, missed that, next time I'll do more searching. Great, then Markdown links can and will just come an in as-is, nothing to do here.
