### ISSUE TITLE
`<html>` element has a fixed `lang="en-US"` value even in translations

### ISSUE THREAD

**Issue by myakura** [mdn/yari#3737]
steps to reproduce:

1. open https://developer.mozilla.org/ja/docs/Web/HTML/Element/link
2. open DevTools or view source
3. check out the value of the `<html lang>` attribute

expected result:

it should reflect the language of the translation ('ja' or 'de')

current result:

the value looks fixed to `en-US`

**Comment by peterbe** [comment]
It's because the "chrome" (aka. header and footer) is always in en-US. We don't have that localized. (yet)

Thankfully, we have this in the HTML:
```html
<main id="content" class="main-content" role="main">
  <article class="main-page-content" lang="ja">
```

I think that's a good solution which reflects the reality of the content being `ja` but the header & footer being `en-US`.

**Comment by myakura** [comment]
> Thankfully, we have this in the HTML:
> 
> ```
> <main id="content" class="main-content" role="main">
>   <article class="main-page-content" lang="ja">
> ```

oops! I missed that one. thanks!
