### ISSUE TITLE
Feature - Fuzzy Search Bar

### ISSUE THREAD

**Issue by cihanisma** [mdn/yari#3766]
Current:
- There is no fuzzy search feature on MDN Web Docs search bar
- Checked on Firefox 88.0.1 (64-bit) and Chrome 90.0.4430.93 (Official Build) (x86_64)
<img width="444" alt="no_fuzzy" src="https://user-images.githubusercontent.com/59100702/117690186-dde8ff80-b1ba-11eb-8b75-963d2cb3a5ba.png">

Update:
- With this feature on the page, the visitor can directly visit the related docs
- No need to switch to search engine every time

**Comment by peterbe** [comment]
It's coming! In a matter of weeks, I hope :)

You can test it locally when you run Yari on your laptop.

**Comment by AnilSeervi** [comment]
> It's coming! In a matter of weeks, I hope :)
> 
> You can test it locally when you run Yari on your laptop. 

This issue can be closed now as feature has been implemented into search.
