### ISSUE TITLE
Don't redirect https://developer.mozilla.org/docs/Introduction to https://developer.mozilla.org/<lang>/docs/Introduction

### ISSUE THREAD

**Issue by makotokato** [mdn/yari#3771]
Please let me know if this issue isn't in Yari and point me correct component.

Firefox's first run page (https://www.mozilla.org/en-US/firefox/nightly/firstrun/) has a link of https://developer.mozilla.org/docs/Introduction. When browser language is en, it will be redirected to https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/developer_guide/introduction.

But If using JA locale browser, https://developer.mozilla.org/docs/Introduction is redirected to https://developer.mozilla.org/ja/docs/Introduction, not https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/developer_guide/introduction, so it means that MDN shows 404 error.

So please redirect it to same page even if lang isn't en-us.

**Comment by peterbe** [comment]
@escattone @chrisdavidmills Independent of localization, and independent of June 30th, `/en-US/docs/Introduction` now redirects to  https://github.com/mdn/archived-content/tree/main/files/en-us/mozilla/developer_guide/introduction :(
Is that something we should change in https://www.mozilla.org/en-US/firefox/nightly/firstrun/ or something we need to manually fix in Yari?

**Comment by caugner** [comment]
I opened https://github.com/mozilla/bedrock/issues/11555 to replace the links on https://www.mozilla.org/ that link to MDN archived content.

FWIW https://developer.mozilla.org/docs/Introduction still redirects to https://developer.mozilla.org/en-US/docs/Introduction, but this just gives a 404, so this issue has become obsolete.
