### ISSUE TITLE
Make pr-lint and validate-redirects npx-runnable?

### ISSUE THREAD

**Issue by alattalatta** [mdn/yari#3772]
Context: https://github.com/mdn/translated-content/pull/782

I'd like to run `validate-redirects` on translated contents locally, which doesn't look easy.

It would be best if I can use npx here:

```
translated-content/files/[locale] $ npx @mdn/tools {validate-redirets|pr-lint}
(or)
translated-content $ npx @mdn/tools {validate-redirets|pr-lint} [locale]
```

...where `@mdn/tools` being a name of the new runnable package.

**Comment by caugner** [comment]
We don't have any plans to implement this anytime soon, and there hasn't been any demand either, so I'm closing this as "won't fix".
