### ISSUE TITLE
Make some KS "wrong macro" calls fixable

### ISSUE THREAD

**Issue by escattone** [mdn/yari#3779]
@hamishwillee @peterbe Sorry for the delay! For the case of `{{domxref("EventHandler")}}`, all calls to `{{domxref("EventHandler")}}` should be replaced with `{{event("Event_handlers")}}`. I think we can add some more intelligence to the "wrong macro" flaws, and suggest the proper macro to call such that they'd become automatically fixable flaws. I think the way we'd do that is via some kind of mapping between macro and basepath. I'll discuss that with @peterbe some more.

_Originally posted by @escattone in https://github.com/mdn/content/pull/4226#discussion_r628333708_

**Comment by teoli2003** [comment]
Given that "WrongMacroError" flaws are under control these days (near 0). I don't think we should invest time in this.
