### ISSUE TITLE
Issue with "Using CSS transforms": broken images

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#3796]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transforms/Using_CSS_transforms

#### What information was incorrect, unhelpful, or incomplete?

The images are shown as broken (browser placeholder).

#### Specific section or headline?

Rotating + Skewing and Translating

#### What did you expect to see?

The transformed image.

#### Did you test this? If so, how?

Firefox for Android.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/css_transforms/using_css_transforms`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Transforms/Using_CSS_transforms
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/css_transforms/using_css_transforms/index.html
* Last commit: https://github.com/mdn/content/commit/58530445b704e463be001d48aa82549d39d69127
* Document last modified: 2021-04-23T06:56:05.000Z

</details>

**Comment by peterbe** [comment]
For the record, a really quick fix is to change the content of the `<pre>` tags. 

```diff
<pre class="brush: html">&lt;img style="transform: rotate(90deg);
            transform-origin: bottom left;"
-    src="screen_shot_2016-02-16_at_15.53.54.png"&gt;
+    src="/en-US/docs/Web/CSS/CSS_Transforms/Using_CSS_transforms/screen_shot_2016-02-16_at_15.53.54.png"&gt;
</pre>
```
that will make the problem go away.

**Comment by wbamberg** [comment]
Oh thanks @peterbe . Then let's do that!
