### ISSUE TITLE
Fixable flaws from a sidebar macro are non-fixable

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#3800]
Flaws from a sidebar macro are not fixable in the current doc. For example there are 70 ish fixable flaws in https://developer.mozilla.org/en-US/docs/Web/CSS/Reference that are not actually fixable

![image](https://user-images.githubusercontent.com/5368500/118215556-091e6800-b4b5-11eb-8298-fbc50abec8a3.png)

**Comment by hamishwillee** [comment]
Though it would be great if some way could be found to make them so!

**Comment by peterbe** [comment]
@escattone We've debated this many times and it sure is tricky. But a stepping-stone solution is to take advantage of the fact that if it says "In prerequisite macro" it means it's not `fixable`. 
Then, the flaw doesn't entirely go away but it's not fixable. Because, as Hamish points out, it isn't.

**Comment by peterbe** [comment]
Why doesn't it say `In prerequisite macro` for me?!
<img width="1004" alt="Screen Shot 2021-05-17 at 11 50 37 AM" src="https://user-images.githubusercontent.com/26739/118518420-1b431500-b706-11eb-8ab9-8e0076e83f54.png">

**Comment by peterbe** [comment]
> Why doesn't it say `In prerequisite macro` for me?!
> <img alt="Screen Shot 2021-05-17 at 11 50 37 AM" width="1004" src="https://user-images.githubusercontent.com/26739/118518420-1b431500-b706-11eb-8ab9-8e0076e83f54.png">

Figured it out. 
It's because of this: https://github.com/mdn/yari/issues/3814
So basically, a bug in Yari for Windows.

**Comment by peterbe** [comment]
@escattone Any ideas how we can know that the flaw lies with the `CSS_Ref.ejs` code and not the `index.html` that uses `{{CSS_Ref}}`?
