### ISSUE TITLE
Add steps to quickstart guide for setting CONTENT_TRANSLATED_ROOT

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#3810]
In the [Yari quickstart](https://github.com/mdn/yari/blob/main/README.md#quickstart) guide, an example along with explanation for creating the environment variable `CONTENT_ROOT` is clear. But, I don't see anywhere that mentions we *must* define a `CONTENT_TRANSLATED_ROOT` env var. It would be nice to have a small explanation (eg its `mdn/content` but the translated files in `mdn/translated-content`) along with an example. 

> Do you have CONTENT_TRANSLATED_ROOT set? Is that repo up to date? 

As I was recently informed of this myself from @peterbe and [.env.dist](https://github.com/mdn/yari/blob/main/.env-dist) , we must define `CONTENT_TRANSLATED_ROOT=path/to/translated-content/files`. If this env variable is not defined, the following error is thrown for some pages when serving locally with `yarn dev`. It expects the `CONTENT_TRANSLATED_ROOT` env variable to be defined.

```
Loading Error
Error: 500 on /en-US/docs/Web/CSS/flex/index.json: Error: 'ar' not in de,en-US,es,fr,ja,ko,pl,pt-BR,ru,zh-CN,zh-TW
```

**Comment by tannerdolby** [comment]
For some pages its not required to have `CONTENT_TRANSLATED_ROOT` set when building with `yarn` and serving with `yarn dev`. 

```js
Starting the development server...
9:36:24 AM server.1     |  [nodemon] restarting due to changes...
9:36:24 AM server.1     |  [nodemon] starting `node server`
9:36:27 AM server.1     |  [HPM] Proxy created: /  -> https://developer.mozilla.org
9:36:27 AM server.1     |  CONTENT_ROOT: /Users/TannerDolby/content/files 
9:36:27 AM server.1     |  Listening on port 5000
```

http://localhost:3000/en-US/docs/Web/CSS/CSS_Flexible_Box_Layout/Basic_Concepts_of_Flexbox renders fine

but 

http://localhost:3000/en-US/docs/Web/CSS/flex without `CONTENT_TRANSLATED_ROOT` set doesn't render and returns error

<img width="335" alt="Screen Shot 2021-05-17 at 9 42 02 AM" src="https://user-images.githubusercontent.com/48612525/118525548-2a20cc00-b6f4-11eb-9cfa-32efe09ef7d2.png">

Since some pages do indeed need the `mdn/translated-content` directory of files, then I reckon having `CONTENT_TRANSLATED_ROOT` be required to set would make sense.

**Comment by escattone** [comment]
Thanks for creating this @tannerdolby!

**Comment by tannerdolby** [comment]
No problem @escattone !

**Comment by peterbe** [comment]
> Since some pages do indeed need the `mdn/translated-content` directory of files, then I reckon having `CONTENT_TRANSLATED_ROOT` be required to set would make sense.

This here seems like the bug to focus on :)
Thanks for finding that!

**Comment by tannerdolby** [comment]
@peterbe Of course! I could round up the pages that are affected by `CONTENT_TRANSLATED_ROOT` not being set when running `yarn dev` if we need a few more examples. Let me know!

**Comment by peterbe** [comment]
For the record, I can load http://localhost:3000/en-US/docs/Web/CSS/flex without having first set `CONTENT_TRANSLATED_ROOT`. 

The error looks like it could be a matter of outdated dependencies. Hmm... Are you sure you ran `yarn install` recently? And is your `content` repo fully up to date with `main`?

**Comment by tannerdolby** [comment]
@peterbe I deleted my old fork for `mdn/yari` and cloned a fresh copy of both Yari and `content` before testing this to make sure I had up to date repos. When creating this issue, Yari/content/translated-content were all even with main. I'm positive I `yarn installed` recently in Yari but that could be something I haven't done in awhile for `content`.

I'm going to make sure each repo is completed updated real quick, will let you know

**Comment by tannerdolby** [comment]
> The error looks like it could be a matter of outdated dependencies. Hmm... Are you sure you ran yarn install recently?

@peterbe You nailed it, after running `yarn install` in `content` and not setting the `CONTENT_TRANSLATED_ROOT` var in Yari, doesn't throw any errors on `yarn dev` and http://localhost:3000/en-US/docs/Web/CSS/flex loads perfectly fine. It must've been the outdated dependencies in content that were needing the env var for translated root set, who knows.

I think this is prime for closing now, I apologize for such a drawn out issue for a simple dependency update.
