### ISSUE TITLE
Auto-add deprecation marker for API item if known

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#3818]
As part of https://github.com/mdn/content/pull/5075 I added the tag "Deprecated" to [GlobalEventHandlers.onkeypress](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onkeypress), which automatically added the deprecated icon to the sidebar:
![image](https://user-images.githubusercontent.com/5368500/118575164-2ca12580-b7c9-11eb-9a13-7f1fa2207013.png)
Nice :-)

Would be good if this was also added to links in the text like this:
![image](https://user-images.githubusercontent.com/5368500/118575228-50fd0200-b7c9-11eb-9baf-9c8dd1aeaa15.png)

Obviously this would be great for any kind of link, but in particular for macro generated links. Bonus points to also add experimental icons etc. 

Note, this would probably require some fixes to the cases where the tagging has been added explicitly via `{{deprecated_inline}}. I realise this might be controversial, but to me the information about status really should be documented in the thing that is being referred to, and propagate everywhere. I'd also argue this should be separate from tags, but that's another story.

Further, it is a problem for me that we mark deprecation, non-standard, etc in three places: deprecation header, tags, BCD. This should all come from the BCD if present, and otherwise be over-ridden by a tag. The tag should auto-generate the deprecation header (or BCD should if that was what was used).

**Comment by peterbe** [comment]
Drive-by comment; when we check for broken links we always look it up. We don't just check if the file exists (in the predictable folder name). So it wouldn't be inconceivable to read in the `tags` and based on that mutate the link. E.g.
```js
const identifier = '/en-US/docs/API/Web/Window/onkeypress'
const doc = getPage(identifier);
if (doc) {
  // Not broken, but should we annotate the link???
  if (doc.tags.includes("Deprecated")) {
    text += " (deprecated!)"
  }
  ...
} else {
  logBrokenLinkFlaw(identifier)
}
```

Where and what KS macro is that?

**Comment by hamishwillee** [comment]
@peterbe That ^^^^ sounds like a good idea. 

- We'd probably want to also check for experimental and standard track in BCD (and whatever the equivalent tags are on MDN)
- These things also get a bit messy if you decide you want to auto-add a deprecation header to a page based on BCD or tags - because say you have a page tagged with both experimental and deprecated you probably only want the deprecated header (it kind of supersedes the others). 

> Where and what KS macro is that?

Now I look at the source the link I was talking about was a plain link and not a macro at all. Doesn't change my answer - any xref macro or link to a topic (note, I did not say "reference topic" here. If the page is marked as deprecated then it probably makes sense to mark it as deprecated when linked even if it is not a reference topic).

**Comment by caugner** [comment]
Closing in favor of duplicate https://github.com/mdn/yari/issues/3929.
