### ISSUE TITLE
HMTLMediaElement.onencrypted page link is broken on Encrypted_Media_Extensions_API page

### ISSUE THREAD

**Issue by spyros-uk** [mdn/yari#3824]
**Description**
The documentation for EME onencrypted is missing, and as a result when clicking the link below, it leads to a page not found.

When clicking on the link [HMTLMediaElement.onencrypted](https://developer.mozilla.org/en-US/docs/Web/API/HMTLMediaElement/onencrypted) link via https://developer.mozilla.org/en-US/docs/Web/API/Encrypted_Media_Extensions_API page, it leads to a "Page not found".

<img width="1347" alt="onenc link" src="https://user-images.githubusercontent.com/15960526/118674004-5ff7aa80-b7f1-11eb-89be-fe5f9e5a50e0.png">

<img width="978" alt="onencrypted 404" src="https://user-images.githubusercontent.com/15960526/118671710-9df3cf00-b7ef-11eb-9433-862c63bbc03c.png">

Note that the `onencrypted` documentation page exists and it is accessible by:

- Navigating to the page directly from the Browser's navigation bar
- Navigation to the page via the [HTMLMediaElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement) page (link under the Event Handlers section)

**Possible Issue:**
It seems like a router issue, not being able to resolve a relative path.

**Comment by escattone** [comment]
Thanks for reporting this @spyros-uk! I see that it's due to a typo in the URL (`...HMTL...` but should be `...HTML...`) (somewhere in our macro code I suspect). It's https://developer.mozilla.org/en-US/docs/Web/API/HMTLMediaElement but should be https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement.
