### ISSUE TITLE
Bigger warning when deleting files

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#3832]
Before you delete a file you should go through and delete all links to it from our content. In some cases it may be better to create a redirect to some other location.

@peterbe suggested ...

> Perhaps make the delete CLI louder with a suggestion like "Are you sure there are no links to... " (and it could even suggest the relevant git grep command you're supposed to use on the command line).

I think that is a good idea. Perhaps also suggest the redirect.

**Comment by caugner** [comment]
@hamishwillee Is this still an issue that comes up (i.e. pages being deleted with links still referencing them), or do dead links show up as flaws in the PR deleting the target?

**Comment by hamishwillee** [comment]
@caugner I'll have to do some testing (Friday or Monday). I do the right thing now by default - so this was mostly for new users.

**Comment by hamishwillee** [comment]
@caugner I'm going to close this. The suggestion was to improve the delete CLI to suggest adding a redirect. This is done now:

![image](https://user-images.githubusercontent.com/5368500/202596298-376f395b-f091-40e3-925a-5ae18b9ff25b.png)

To answer your specific question above, I am pretty sure that flaws only show the pages that you touched - so the dead link you create in a PR by deleting a fiele will only be visible if that page is also linked in the PR.
It would be good perhaps if tooling could detect this in the current PR, but that's not the issue that was raised here.report.

Thanks for following up.

**Comment by caugner** [comment]
> The suggestion was to improve the delete CLI to suggest adding a redirect. This is done now:

FWIW This was implemented in https://github.com/mdn/yari/pull/4812.
