### ISSUE TITLE
Missing support statement when order of statements in BCD is inverted

### ISSUE THREAD

**Issue by foolip** [mdn/yari#3839]
https://developer.mozilla.org/en-US/docs/Web/CSS/gap#support_in_grid_layout when expanding the data for Safari currently looks like this:
![image](https://user-images.githubusercontent.com/498917/119103229-328e4500-ba1b-11eb-8a4c-76023ff02c1b.png)

It looks like Safari only supports `grid-gap`, not `gap`. This is the data being rendered here:
https://github.com/mdn/browser-compat-data/blob/2c1ab9977825bac860d0152c95f4483f98cf19be/css/properties/gap.json#L127-L144

The difference to the other browsers is that the `alternative_name` entry comes first for Safari. That should be fixed, but even so this seems like a bug in the BCD table rendering.

cc @Elchi3 @apple-web-evangelist @jensimmons

**Comment by Elchi3** [comment]
Right, this could be fixed on the consumer side (yari), or we guarantee order it in BCD (see https://github.com/mdn/browser-compat-data/pull/5352)

**Comment by foolip** [comment]
This seems like a rather mysterious bug though. What is the safe order to avoid this happening? Without knowing the root cause, I'd worry that multiple statements with `prefix` or `alternative_name` could also run into this.

**Comment by foolip** [comment]
I've found another case not involving `alternative_name` at all:
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/stop-opacity#browser_compatibility

There, the data being rendered is:
```
              "safari_ios": [
                {
                  "version_added": "3",
                  "version_removed": "11"
                },
                {
                  "version_added": "14"
                }
              ],
```

cc @ddbeck who I bugged about it in https://github.com/mdn/browser-compat-data/pull/9468/files#r636796045.

**Comment by Elchi3** [comment]
Ah, thanks!  The old renderer did take into account multiple ranges but now it looks like the yari renderer just always takes the first one.

**Comment by foolip** [comment]
I wonder if the bug is here?
https://github.com/mdn/yari/blob/ce67d66ecd57752801745e9e4d77944925a85c5e/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx#L310
https://github.com/mdn/yari/blob/ce67d66ecd57752801745e9e4d77944925a85c5e/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx#L388-L395

It looks like if there there are just simple entries, `supportNotes` will be empty. That explains the case in https://github.com/mdn/yari/issues/3839#issuecomment-845838090. But the original issue I don't get, there is an `alternative_name` there.

**Comment by Elchi3** [comment]
I wrote https://github.com/mdn/yari/pull/3864 which should fix the rendering bug. 
BCD still needs to make sure the order makes sense, though.

**Comment by foolip** [comment]
Thanks for the fix, @Elchi3, and @peterbe for the review!
