### ISSUE TITLE
File checker won't look inside a possible `index.md` file

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3847]
[This code](https://github.com/mdn/yari/blob/8cbb9fb9784dc9f9798f6c73cfb393b75b76bd13/filecheck/checker.js#L106-L112) is hardcoded to only cope with `index.html`. Not `index.md`. 

So if you put in a `screenshot.png` next to the `index.md`, it won't succeed in checking that.

**Comment by peterbe** [comment]
@Gregoor You might wanna take this one before you start porting `index.html => index.md` in case those documents have file attachments.

**Comment by Gregoor** [comment]
Good catch, thanks Peter! Any reason why we would not want it to use `Document.read().rawContent` instead?

**Comment by peterbe** [comment]
> Good catch, thanks Peter! Any reason why we would not want it to use `Document.read().rawContent` instead?

Yeah, I prefer that. The `filePath` in that area is something like `/Users/peterbe/MDN/content/files/en-us/foo/screenshot.png` so you can't easily figure out what the document URL should be from that. But what we maybe can do is:
```js
const fileParentPath = path.dirname(filePath)
const doc = Document.read(path.join(fileParentPath, 'index.html')) || Document.read(path.join(fileParentPath, 'index.md'))

if (!doc) {
  throw new Error(`${filePath} is not located in a folder with an 'index.html' or 'index.md' file.`)     
}
if (!doc.rawCOntent.includes(path.basename(filePath))) {
  throw new Error(`${filePath} is not mentioned in ${doc.fileInfo.path}`);
}
```
