### ISSUE TITLE
Make sidebar links to current page bold and unclickable

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#3868]
This pulls out just one specific part of #3812 that should be relatively easy to fix and that will improve sidebars "somewhat".

The requirement is that if a page is open any link(s) to it in the sidebar should be:
-  visibly highlighted (I suggest in bold and black). We want it visibly different to other links mainly to make the current context clear (otherwise it is just one link in the "forest of links" in the sidebar). 
- Non-clickable.  If it was a clickable link the user will be taken to the top of the page. This is a problem with the current sidebar because clicking the link may scroll the sidebar off screen - losing context. In a sidebar that worked properly this would IMO still be good design, but it would become "arguable".

This should apply to all links to current page in all sidebars. You might start with the Learn sidebar macro as a test case :-)

**Comment by caugner** [comment]
Resolved via https://github.com/mdn/yari/pull/7085 and https://github.com/mdn/yari/pull/7444.
