### ISSUE TITLE
Dead link from the XUL namespace URL

### ISSUE THREAD

**Issue by lf-** [mdn/yari#3870]
Going to https://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul and then clicking on the documentation link going here: https://developer.mozilla.org/en/XUL leads to a 404.

**Comment by peterbe** [comment]
I don't know what https://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul is but it feels like that's where the issue is. They're linking to a 404'ing page.

**Comment by lf-** [comment]
That's the namespace URL for userChrome.css and probably other xul stuff, it has to go in the header, supposedly.

**Comment by caugner** [comment]
Problem solved, https://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul no longer links to us.
