### ISSUE TITLE
Content bug: <browser compatibility link invalid in Non-English page>

### ISSUE THREAD

**Issue by wssdll** [mdn/yari#3882]
### It is a widespread problem over many pages.

There is an example: 
[https://developer.mozilla.org/zh-CN/docs/Web/API/ResizeObserver#browser_compatibility](https://developer.mozilla.org/zh-CN/docs/Web/API/ResizeObserver#browser_compatibility)

## Specific page section or heading?

The experimental label, **#browser_compatibility** link.

## What is the problem?

The experimental label, **#browser_compatibility** archor link cannot be positioned correctly.

> ![image](https://user-images.githubusercontent.com/12515588/119430721-d9d4ea00-bd43-11eb-9ffd-a8d3064f0c30.png)

I think it’s because of the incorrect  ID translated.

> ![image](https://user-images.githubusercontent.com/12515588/119429515-92e5f500-bd41-11eb-9fea-0897752b5eb5.png)

## What did you expect to see?

There is a correct example: 
[https://developer.mozilla.org/ja/docs/Web/API/WritableStream#browser_compatibility](https://developer.mozilla.org/ja/docs/Web/API/WritableStream#browser_compatibility)

## Did you test this? If so, how?

Manual test.

**Comment by liyuhang1997** [comment]
I think we should translate SeeCompatTable.ejs and keep existing page id corresponding to language.
