### ISSUE TITLE
Update HTTP 404 page

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#3931]
Please update the HTTP 404 page as show:

> You've followed a link to a page that doesn't exist.
> 
> The page might not have been written yet or may have been deleted. It is also possible that the link URL is incorrect.
> We recommend searching for similar topics on MDN.
>
> To create this page, or just fix the link, please follow our instructions on [content repo README.md](https://github.com/mdn/content#contributing-to-the-content-of-mdn-web-docs)

This follows discussion here: https://github.com/mdn/yari/discussions/3890

**Comment by peterbe** [comment]
What should that link there be if the URL was something like /fr/docs/Web/Pagenotfound?

**Comment by peterbe** [comment]
@wbamberg @Rumyra Can you sign off on Hamish's suggestion here?

**Comment by wbamberg** [comment]
I'm happy with this, yes :). The only thing might be whether instead of directing them to https://github.com/mdn/content#contributing-to-the-content-of-mdn-web-docs (effectively asking them to fix it themselves) we direct them to https://github.com/mdn/content/issues (asking them to ask for it to be fixed). But I can see arguments on both sides, and this is a big improvement on what we have now.

**Comment by hamishwillee** [comment]
Great!

I don't want to derail this being implemented, so as an aside, @wbamberg perhaps the first thing in https://github.com/mdn/content#contributing-to-the-content-of-mdn-web-docs could be a call to create issues, and recognise that as a contribution.

**Comment by peterbe** [comment]
How about this then:


> You've followed a link to a page that doesn't exist.
> 
> The page might not have been written yet or may have been deleted. It is also possible that the link URL is incorrect.
> We recommend searching for similar topics on MDN.
>
> To create this page, or just fix the link, please follow our instructions on [content repo README.md](https://github.com/mdn/content#contributing-to-the-content-of-mdn-web-docs)
> 
> Or, if you prefer, [file an issue about this first](https://github.com/mdn/content/issues ).

??

**Comment by wbamberg** [comment]
I like having 2 separate links, an easy path to just file an issue as well as the link to the README. I think this is better than just sending people to the README, which is a forbidding document even if it links to the issue tracker early on.

I think "first" is odd in the second link as it implies that you have to fix the issue still after filing it. Is that what we want to imply?

If it were me I'd swap the order of "file an issue" and "fix it yourself":

> You can file an issue about this on [MDN's issue tracker].
>
> Or if you'd like to fix it yourself, please follow the contribution instructions on the [MDN content repo's README].

**Comment by hamishwillee** [comment]
> How about this then:
> 
> > You've followed a link to a page that doesn't exist.
> > The page might not have been written yet or may have been deleted. It is also possible that the link URL is incorrect.
> > We recommend searching for similar topics on MDN.
> > To create this page, or just fix the link, please follow our instructions on [content repo README.md](https://github.com/mdn/content#contributing-to-the-content-of-mdn-web-docs)
> > Or, if you prefer, [file an issue about this first](https://github.com/mdn/content/issues).
> 
> ??

**Comment by wbamberg** [comment]
sold!

**Comment by Rumyra** [comment]
Soz just catching up on this...

I'm concluding yes this is good - after writing a whole paragraph on thoughts and that's the tldr 😄

**Comment by caugner** [comment]
@hamishwillee In https://github.com/mdn/yari/pull/7070, it would have been useful to mention this issue. 😉

**Comment by hamishwillee** [comment]
Yes it would - sorry, my memory of silent year old issues perhaps not what it should be :-0
