### ISSUE TITLE
Broken-link check non-absolute URLs

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3940]
In the broken links flaw checker (which is also used in production builds), we only test absolute URLs. E.g. `/en-US/docs/Web/CSS` but never links like `padding-left`. 
Technically we also check things like `#Anchor` or `https://developer.mozilla.org/...` too. 

But what if there's a document that tries to link to a sibling document. E.g. 
https://github.com/mdn/content/blob/89924634d5234f334e29a338383710aa3a1b71c1/files/en-us/tools/debugger-api/debugger.frame/index.html#L19

There are actually quite a lot of other potential typos, like 
```html
<li><a href="en-US/docs/Web/Accessibility/Understanding_WCAG">WCAG</a>
```

**Comment by peterbe** [comment]
Another interesting example is things like:
```html
<a href="screenshot.png">
```
https://github.com/mdn/yari/pull/3887 takes care of correcting the full URL for that but it won't work if the image lookup is a failure. E.g. `screnshoot.png`. 
So when doing these broken link checks, make sure to check both `Document.findByURL()` and `Image.findByURL()`.

**Comment by caugner** [comment]
FWIW We now prevent non-absolute links via markdownlint:

https://github.com/mdn/content/blob/3c7952277be68c0dafa53b18f535adb33a435181/.markdownlint-cli2.jsonc#L154-L160

And as for the images, we do already check for existence here:

https://github.com/mdn/yari/blob/9b885aad6cf481e4d64892a1b5d8c5976e7944ba/build/check-images.ts#L168-L173
