### ISSUE TITLE
Why is the Change Language Button placed at the bottom of the document

### ISSUE THREAD

**Issue by popring** [mdn/yari#3949]
I'm curious. Why is the Change Language button at the bottom, where each action changes from one step in the previous version to two steps。

**Comment by popring** [comment]
If you know Chinese, then this paragraph will make you understand my meaning better.
change language 按钮为什么不直接放在文档顶部，这样会减少操作步骤？现在这样感觉挺麻烦的，需要跳转到底部才能更换语言。

**Comment by peterbe** [comment]
> I'm curious. Why is the Change Language button at the bottom, where each action changes from one step in the previous version to two steps。

We did it that way because we hoped it's not something people have to reach for very often. But I suspect you do. You land on a `/en-US/docs/...` URL and have to click to scroll down to the bottom and change language, right? Again and again. 

I have a fix in mind that automates that for you.

**Comment by popring** [comment]
> > I'm curious. Why is the Change Language button at the bottom, where each action changes from one step in the previous version to two steps。
> 
> We did it that way because we hoped it's not something people have to reach for very often. But I suspect you do. You land on a `/en-US/docs/...` URL and have to click to scroll down to the bottom and change language, right? Again and again.
> 
> I have a fix in mind that automates that for you.

Thank you very much. You understand me.
I would like the details very much about automates .

**Comment by schalkneethling** [comment]
This is changing as part of the redesign but, will keep it open until that landed.

**Comment by caugner** [comment]
Resolved as part of the redesign, the locale switcher is now prominently visible in the action menu at the top:

<img width="1007" alt="image" src="https://user-images.githubusercontent.com/495429/202031415-9723514d-3674-46fc-b6ba-f3123f56677f.png">
