### ISSUE TITLE
Markdown Model Pages as Integration Tests

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#3956]
Identify perfectly converted pages with Will and add them as tests, to make sure future changes don't regress the converter

**Comment by peterbe** [comment]
This was kinda what the [MDN/KItchensink page](https://github.com/mdn/content/blob/main/files/en-us/mdn/kitchensink/index.html) was meant to be. A page you can rely on to always be there and be flawless. It also doubled as a chance to make sure every KS macro got used. How do you feel about running the converter on that page? It's not any bigger or smaller commitment than converting all the JS docs. 
Perhaps if we have to, if there are certain KS macros that completely cease to make sense in a `kitchensink/index.md` file we can just delete those.

**Comment by schalkneethling** [comment]
We do have this now: https://github.com/mdn/yari/blob/9d0669d148d5fdc0feec74f605ff8ed9def6233c/.github/workflows/testing.yml#L73
