### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by MrMoon** [mdn/yari#3959]
It would really feel more comfortable to read the docs in a darker theme, especially at night,

I Hope this is already being worked on, and I hope that I can help 😄 😃

**Comment by escattone** [comment]
@MrMoon This is probably our most requested feature. We already have a discussion opened for this (see https://github.com/mdn/yari/discussions/2539). I'm going to close this issue and refer you to that discussion, where we'd welcome your comments. Thanks for your feedback!
