### ISSUE TITLE
Can't include non-image file attachments

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#3984]
The problem is described here: https://github.com/mdn/content/issues/5606 
You can put a `screenshot.png`, for example, next to the `index.(html|md)` file and it will be picked up even though there might not be a single `<img src="screenshot.png">` in the rendered and parsed HTML. 
However, we only check for images. We need to support other somewhat arbitrary files too.

**Comment by peterbe** [comment]
One temporary and possible solution for https://github.com/mdn/content/issues/5606 is to correct the CORS headers on that S3 serving. But we want to get away from using Kuma for the content. 

The advantage of being able to check in the images into the content is self-containment. Now all the content is available offline. No need to depend on a centralized internet server.

**Comment by caugner** [comment]
Closing in favor of duplicate https://github.com/mdn/yari/issues/5727.
