### ISSUE TITLE
Create CODEOWNERS files for data files

### ISSUE THREAD

**Issue by escattone** [mdn/yari#3986]
Let's use a `CODEOWNERS` file for assigning reviewers to the various data files like:

- `kumascript/macros/GroupData.json`
- `kumascript/macros/InterfaceData.json`
- `kumascript/macros/SVGData.json`
- `kumascript/macros/SpecData.json`

**Comment by caugner** [comment]
Those files live [in mdn/content](https://github.com/mdn/content/tree/main/files/jsondata) now.
