### ISSUE TITLE
MDN Web Docs no longer prompts to install as a custom search engine

### ISSUE THREAD

**Issue by jamestthompson3** [mdn/yari#3991]
It was previously possible to get the prompt to add the MDN Web Docs site as a custom search engine in Firefox. The cause of this seems to be that the [Open Search](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) link is no longer present in the `<head>` elements of the MDN Web Docs pages.

**Comment by schalkneethling** [comment]
@escattone @peterbe  I see in Kuma we used to have this:

```
<link rel="search" type="application/opensearchdescription+xml" href="{{ settings.SITE_URL }}/{{ request.LANGUAGE_CODE }}/search/xml" title="{{ _('MDN Web Docs') }}">
```

Does the URL the above reference still exist in Yari?

**Comment by peterbe** [comment]
Before we jump in and actually work on this, I think we need to discuss if Firefox (wants to) support this.

**Comment by schalkneethling** [comment]
> Before we jump in and actually work on this, I think we need to discuss if Firefox (wants to) support this.

Well according to the docs: "OpenSearch is supported by (at least) Firefox, Edge, Internet Explorer, Safari, and Chrome." so, it is not only for Firefox? or did you mean MDN?

**Comment by peterbe** [comment]
> > Before we jump in and actually work on this, I think we need to discuss if Firefox (wants to) support this.
> 
> Well according to the docs: "OpenSearch is supported by (at least) Firefox, Edge, Internet Explorer, Safari, and Chrome." so, it is not only for Firefox? or did you mean MDN?

I actually meant Firefox. Firefox used to have separate bars for address and one for search. Now it's all in one bar. Same as Chrome (and Safari too?). 
So does any browser support Open Search anybody. Can I go to a website that has it and do something to my Firefox (or Chrome) so it stops doing Google (or DDG or Bing) and uses the sites site-search instead.

**Comment by teoli2003** [comment]
If I'm not mistaken, Firefox still supports Open Search Engines and propose to add them (see the github icon, near the bottom right of the screenshots) to the list of search engines (and yes I've plenty of them ;-), including MDN) 
<img width="1120" alt="Screenshot 2021-06-15 at 16 33 53" src="https://user-images.githubusercontent.com/1466293/122072205-a7c12000-cdf7-11eb-8953-233d86d18e94.png">
Of course, the proposal is pretty subtle nowadays.

**Comment by schalkneethling** [comment]
Indeed as @teoli2003 stated:

![Screenshot 2021-06-15 at 16 41 41](https://user-images.githubusercontent.com/10350960/122073327-9fb5b000-cdf8-11eb-8c6a-b1d10945db3c.png)

**Comment by mklein994** [comment]
Users can change the default search engine on most browsers, so it follows that if MDN presents itself as a search engine, users could add it to their browser, which would provide this functionality (adding keywords for the search, jumping directly to MDN from the address bar, etc.).

Below is a table showing a few browsers with instructions for how to change their default search engine:

| Browser | Instructions |
| :--- | :--- |
| Chrome | <https://support.google.com/chrome/answer/95426> |
| Edge | <https://support.microsoft.com/en-us/microsoft-edge/change-your-default-search-engine-f863c519-5994-a8ed-6859-00fbc123b782> |
| Firefox | <https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox><sup>1</sup> |
| Opera | <https://help.opera.com/en/latest/search/#defaultSearchEngine> |
| Safari | <https://support.apple.com/en-ca/guide/safari/sfria1042d31> |

So far, it seems (in my experience) that browsers either support Open Search, or allow users to add a search engine where `%s` acts as a placeholder for the query, or some combination of both. I haven't been able to find anything conclusive for what approach search engines should take to support all browsers, but at least Open Search is [documented](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md).

---

1. On Firefox desktop, it's possible to add keyword for a search engine by right-clicking on the search input field and selecting "Add a keyword for this Search…", but this doesn't actually _add_ a search engine, it just acts like one (e.g. it can't be set as the default).

   <https://support.mozilla.org/en-US/kb/how-search-from-address-bar>

**Comment by mklein994** [comment]
If people are just wanting to add MDN search back, you can still find it in the [Mycroft Project](https://mycroftproject.com/) here:

<https://mycroftproject.com/install.html?id=70236&basename=mdc_en&icontype=png&name=Mozilla+Developer+Network>

Just go to the page, then right-click and add as normal. It should show up in Firefox preferences (about:preferences#search).

**Comment by peterbe** [comment]
If someone can build an equivalent of view-source:https://github.com/opensearch.xml we can see about uploading it as a static asset. We just need to add it to `client/public/opensearch.xml` and once it becomes available we just need to edit `client/public/index.html` to contain `<link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="MDN">` and it should be good to go.

**Comment by schalkneethling** [comment]
As mentioned before, we are pretty confident that we can get this going again, we are just double checking to make sure the config on the server side is in place to serve the file with the appropriate headers. @binyamin, feel free to change the PR from draft to ready for review in the mean time. Thank you.
