### ISSUE TITLE
BCD: render pre-stable (beta, nightly, planned) releases as blue (not green)

### ISSUE THREAD

**Issue by foolip** [mdn/yari#4005]
In https://github.com/mdn/yari/pull/3997, @Elchi3 is adding support for the special version "preview" in BCD, rendering it in blue (`$primary-500`) instead of the usual green. Beta is also pre-stable and can't be depended on yet, and I think it would make sense to render that as blue as well.

I'm raising this now because https://github.com/mdn/browser-compat-data/pull/10898 adds a large amount of data for Safari 15 beta, 147 entries it looks like. There's also a fair bit of Firefox beta data (23 entries right now: `npm run traverse firefox all 89`) and occasionally some for Chrome (1 right now).

Discussed briefly with @Elchi3 on the Matrix chat.

cc @apple-web-evangelist @jensimmons

**Comment by Elchi3** [comment]
For the record, this had consensus in the BCD call on Wednesday.

**Comment by foolip** [comment]
This was already implemented at some point. https://developer.mozilla.org/en-US/docs/Web/API/Sanitizer#browser_compatibility is a current example showing that it works.

**Comment by caugner** [comment]
Fixed via https://github.com/mdn/yari/pull/5532.
