### ISSUE TITLE
Archived pages don't render

### ISSUE THREAD

**Issue by Elchi3** [mdn/yari#4010]
Only renders for like a second and then the page goes blank for me.

https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScript
https://developer.mozilla.org/en-US/docs/Archive/Web/JavaScript
https://developer.mozilla.org/en-US/docs/Archive/Web/JavaScript/Object.noSuchMethod

Console output

[Error] [Report Only] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (JavaScript, line 1)
[Error] [Report Only] Refused to execute a script because its hash, its nonce, or 'unsafe-inline' does not appear in the script-src directive of the Content Security Policy. (JavaScript, line 66)
[Error] TypeError: undefined is not an object (evaluating 'e.waffle.flags')

**Comment by peterbe** [comment]
Ah. We changed the `/api/v1/whoami` so it no longer includes the `flags` key in the JSON. 
The JS bundles in the archived pages cleared wasn't equipped to see that disappear. Very fragile.
I've kicked off a Stage build which *includes* the archived content. 
In about 1h we'll see if https://developer.allizom.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScript starts to work again.

**Comment by peterbe** [comment]
Tricky. It errored https://github.com/mdn/yari/runs/2802368844?check_suite_focus=true
It errored because the archived content repo contains documents from locales we no longer consider "valid".

**Comment by peterbe** [comment]
Stage works now: https://developer.allizom.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScriPt

**Comment by peterbe** [comment]
Prod works too now! https://developer.mozilla.org/en-US/docs/Mozilla/Debugging/Debugging_JavaScriPt

We have to clear the CDN cache on these things.

**Comment by peterbe** [comment]
I've kicked off a CDN cache invalidation for `/en-US/docs/Archive/*` and `/en-US/docs/Mozilla/*`.

**Comment by ZeddYu** [comment]
@peterbe I don't think this site works https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache.

Still down for me. And chrome console shows the same error as before.
```
react-dom.production.min.js:216 TypeError: Cannot read property 'flags' of undefined
    at Q (index.tsx:69)
    at al (react-dom.production.min.js:157)
    at Vl (react-dom.production.min.js:180)
    at Hi (react-dom.production.min.js:269)
    at _u (react-dom.production.min.js:250)
    at Ou (react-dom.production.min.js:250)
    at xu (react-dom.production.min.js:250)
    at yu (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```
