### ISSUE TITLE
Web/HTML/Using_the_application_cache stopped working since whoami changed

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#4011]
@peterbe I don't think this site works https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache.

Still down for me. And chrome console shows the same error as before.
```
react-dom.production.min.js:216 TypeError: Cannot read property 'flags' of undefined
    at Q (index.tsx:69)
    at al (react-dom.production.min.js:157)
    at Vl (react-dom.production.min.js:180)
    at Hi (react-dom.production.min.js:269)
    at _u (react-dom.production.min.js:250)
    at Ou (react-dom.production.min.js:250)
    at xu (react-dom.production.min.js:250)
    at yu (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```

_Originally posted by @ZeddYu in https://github.com/mdn/yari/issues/4010#issuecomment-859677451_

**Comment by peterbe** [comment]
The problem with https://developer.mozilla.org/en-US/docs/Web/HTML/Using_the_application_cache is that it should have been pruned long ago. It's a stale page that's stuck in S3. It's not part of archived content. 
We're currently not pruning the existing built and published pages because we're still waiting to delete all the archived content URLs (June 30, 2021). 

So once that goes into effect, this page will become 404 instead of a 200 with a broken JS. 

CC @escattone @ZeddYu

**Comment by peterbe** [comment]
@escattone This is another page/issue that should automatically resolve once we turn the pruning back on. Let's remember to check.

**Comment by peterbe** [comment]
Got fixed when we enabled pruning again after deleting the archived content.

**Comment by ZeddYu** [comment]
@peterbe It seems the issue has been fixed. But Is there any other way to read this document online now?

**Comment by peterbe** [comment]
> @peterbe It seems the issue has been fixed. But Is there any other way to read this document online now?

I filed https://github.com/mdn/content/issues/7158
