### ISSUE TITLE
{{Specifications}} displays `Unknown Specification` for Control Lists spec

### ISSUE THREAD

**Issue by teoli2003** [mdn/yari#4015]
In the page https://pr5945.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/HTMLMediaElement/controlsList#specifications , I get "Unknown specification" as the name of the specificatiion:
<img width="544" alt="Screen Shot 2021-06-13 at 12 47 50" src="https://user-images.githubusercontent.com/1466293/121804230-9df7bb00-cc45-11eb-85fc-50ad46e19fd4.png">

The bcd in front-runner is `browser-compat: api.HTMLMediaElement.controlsList` that leads to `"spec_url": "https://wicg.github.io/controls-list/#solution-outline"`.

This spec is _not_ defined in w3c/browser-specs, but is in our exception list in https://github.com/mdn/browser-compat-data/blob/main/test/spec-urls.test.js . 

This may be the root cause of the problem.

Expectation: I would like to have the name of the spec in MDN (Controls-list).

**Comment by Elchi3** [comment]
https://wicg.github.io/controls-list/ is not a real spec, so it doesn't have a name. 

This feature will be merged into the HTML standard (hopefully soon) and then this can have a spec_url to https://html.spec.whatwg.org/multipage/. BCD allowing it is a bit of a gray area here.

I would say "Unknown spec" is correct for now.

**Comment by teoli2003** [comment]
Makes sense.

Just to try to anticipate problems (as they will appear, we are about to use bcd info on MDN for every document that has table). Is this the case for every specs in the bcd's exception list?

**Comment by Elchi3** [comment]
> Is this the case for every specs in the bcd's exception list?

Yes and the idea is to either fix bcd not use these spec_urls anymore or to fix browser-specs to include them.
For all the IETF specs, browser-specs is working on adding them. For the others, they are real edge cases and I hope BCD can remove them or better specs will be available soon (like for control lists).

**Comment by Elchi3** [comment]
I would wait use {{Specifications}} for HTTP docs (and generally for docs that hit on the BCD exception list.). It will be sorted out soon but isn't just yet.

**Comment by teoli2003** [comment]
Thank you. I will roll back the few cases that already happen.
