### ISSUE TITLE
Twitter Card preview image looks bad on dark theme

### ISSUE THREAD

**Issue by saschanaz** [mdn/yari#4023]
https://twitter.com/jensimmons/status/1402028742772408327

![image](https://user-images.githubusercontent.com/3396686/121911440-0fac3380-cd30-11eb-83e7-6100c0204c0c.png)

I think it's Twitter that broke the image since [the image itself](https://developer.mozilla.org/mdn-social-share.2f09512a.png) looks good with any dark background color. 🤔

**Comment by peterbe** [comment]
Thanks!! It got fixed by https://github.com/mdn/yari/pull/4013 today. 
So we should see this rolling out sometime tomorrow.
