### ISSUE TITLE
网页

### ISSUE THREAD

**Issue by 18157615674** [mdn/yari#4057]
网页为什么不能自动翻译我不习惯用翻译插件

**Comment by Ryuno-Ki** [comment]
Google Translator turns this into:

> Why can't the webpage be automatically translated? I am not used to using translation plugins

**Comment by 18157615674** [comment]
> 
> 
> Google Translator turns this into:
> 
> 谷歌翻译器把它变成:
> 
> > Why can't the webpage be automatically translated? I am not used to using translation plugins为什么网页不能自动翻译? 我不习惯使用翻译插件

怎么操作啊

**Comment by Ryuno-Ki** [comment]
@irvin Could you help here? I'm not speaking Chinese.

**Comment by 18157615674** [comment]
没关系我可以用手机翻译

**Comment by 18157615674** [comment]
？

**Comment by peterbe** [comment]
> ？

We need to keep the issue to English. Sorry.

**Comment by 18157615674** [comment]
什么意思没有懂closed this 关了这个31 minutes ago 31分钟前

**Comment by irvin** [comment]
@18157615674 你是要詢問 MDN 文件的問題，或者 Firefox 的問題？
MDN 文件目前均仰賴志願者人工翻譯。

如你要尋找 Firefox 的翻譯插件，請到 addons.mozilla.org
如果你要尋求 Firefox 的使用協助，請到火狐社區 http://mozilla.com.cn/moz-forum.html

**Comment by irvin** [comment]
@Ryuno-Ki @peterbe 
the issue is “why the page cannot auto-translate, i’m not used to translation add-on”
however, i’m not sure if they are looking for support on firefox or mdn. i think it’s ok to keep it closed.

**Comment by 18157615674** [comment]
谢谢
