### ISSUE TITLE
Lighthouse audit report for documentation pages

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#4060]
## Addressing Lighthouse Audit  results for MDN pages 🚧 

- [ ] Performance
- [x] Accessibility (100) 🏆 
- [ ] Best Practices
- [x] SEO 

Using the automated tool [Lighthouse]() for improving the quality of webpages (performance, SEO, accessibility, best practices), it uncovers some really "quick" fixes for accessibility & SEO, and potentially performance improvements. The audit lists some potential solutions for reducing DOM size etc, but that is where the fixes will become more complex. 

I hope this thread will be helpful first step in beginning to improve overall page quality and chip away at potential fixes to get 100s across the board on Lighthouse audits. Achieving 100 performance might be unreasonable as the size of pages are quite big with many main-thread JS tasks happening (maybe a 10-15 point increase would be super) but the other categories we will be able to get perfect scores in.

<img width="1277" alt="Screen Shot 2021-06-19 at 4 06 44 PM" src="https://user-images.githubusercontent.com/48612525/122657430-5fb43d00-d118-11eb-8674-30e6132a7f38.png">

## Performance results

<img width="675" alt="Screen Shot 2021-06-19 at 4 12 53 PM" src="https://user-images.githubusercontent.com/48612525/122657544-3c3dc200-d119-11eb-827b-f85936c172c3.png">

1. Avoid excessive DOM size - This would probably be the first priority, or atleast the start of a discussion regarding "windowing" some the elements with many repeated children like `<ol>` elements `Maximum Child Elements | ol | 363`. Lighthouse recommends using a "windowing" library like [react-window](https://react-window.now.sh/#/examples/list/fixed-size) to minimize the number of DOM nodes created if rendering many repeated elements on a page. Like what is happening with the child `<li>` elements within the ordered lists on some pages. Here is a post they lighthouse recommends on [virtualizing large lists with react-window](https://web.dev/virtualize-long-lists-react-window/?utm_source=lighthouse&utm_medium=devtools) 

Potentially using a "windowing" library like `react-window` to minimize the number of DOM nodes created if you are rendering many repeated elements on the page. Learn more. Also, minimize unnecessary re-renders using `shouldComponentUpdate`, `PureComponent`, or `React.memo` and skip effects only until certain dependencies have changed if you are using the `Effect` hook to improve runtime performance. 

2. Minimize main-thread work - I'm not entirely sure how much can be reduced here, but the breakdown for the main-thread looks like this:

<img width="675" alt="Screen Shot 2021-06-19 at 4 33 54 PM" src="https://user-images.githubusercontent.com/48612525/122657887-2c73ad00-d11c-11eb-90d4-ac63dbee88e8.png">

## Accessibility 

1. `<frame>` or `<iframe>` elements do not have a title attribute 

(Fix pending in #4061) - "Provide unique and descriptive title attributes for all frame and iframe elements."  [web.dev/frame-title/](https://web.dev/frame-title/?utm_source=lighthouse&utm_medium=devtools)

<img width="678" alt="Screen Shot 2021-06-19 at 4 41 21 PM" src="https://user-images.githubusercontent.com/48612525/122657999-36e27680-d11d-11eb-9785-b7bc81db529b.png">

Indeed the `EmbedLiveSample()` KS macro output doesn't give the `<iframe>`'s a `title` attribute. Since the `$0` arg in `EmbedLiveSample.ejs` represents the `sampleId`, I just used that value for the `title` and deslugified it along with adding "sample" to the end like `<iframe class="example-outcome-frame" title="Comparison of HTML and SVG sample" ..> `.

2. Heading elements are not in a sequentially-descending order 

(Fix pending in #4107) - This is another relatively "quick" fix. The audit screenshot is a bit off, the `<h4>` shown below tag fails the heading levels audit. It fails because we skip from an `<h2>` to an `<h4>` in the aside element. I'm just spitballin here, but since it would be a pain to search through all pages and make sure the headings are properly ordered/structured, could we do something with internal utility for selecting all the heading elements on the page (or a more specific group for performance) and then check too see if the last two headings are mismatched, then perform a "fix" to make sure the last two heading elements are in sequentially descending order. Or we could see if changing the markup directly would resolve things, but I think it might be to unpredictable on what the 2nd to last heading before the last on each page will be to provide a blanket fix. Link [heading-order](https://web.dev/heading-order/?utm_source=lighthouse&utm_medium=devtools)

<img width="677" alt="Screen Shot 2021-06-19 at 4 41 43 PM" src="https://user-images.githubusercontent.com/48612525/122658004-41047500-d11d-11eb-91e4-6c1fa7b315d4.png">

For example this is whats happening on https://developer.mozilla.org/en-US/docs/Web/CSS/flex to cause the headings level audit to fail ie `["h1", "h2", "h3", "h2", "h3", "h2", "h4"]` and its clear as day the `<h3>` is skipped at the end of the list and the `<h4>` ends up being the next heading (also the last) in the "outline" of the page in terms of someone navigating the sections of a page with a screen reader.

<img width="656" alt="Screen Shot 2021-06-21 at 2 07 28 AM" src="https://user-images.githubusercontent.com/48612525/122737447-e3178080-d235-11eb-85f6-09136f3fd481.png">

## Best practices
1. Registers a `unload` listener
<img width="678" alt="Screen Shot 2021-06-19 at 4 42 52 PM" src="https://user-images.githubusercontent.com/48612525/122658028-7a3ce500-d11d-11eb-9b50-0bff6bac7fcd.png">

## SEO
1. Tap targets are not sized appropriately 87% appropriately sized tap targets - Targets that are smaller than 48 px by 48 px or closer than 8 px apart fail the audit. [tap targets](https://web.dev/tap-targets/?utm_source=lighthouse&utm_medium=devtools). This one will be an easy fix too!

<img width="679" alt="Screen Shot 2021-06-19 at 4 44 04 PM" src="https://user-images.githubusercontent.com/48612525/122658052-a2c4df00-d11d-11eb-9305-e2f7f5a600ec.png">

With all of the above said/shown, I think there are some improvements we can quickly capitalize on to improve overall page quality. I've fixed almost all of these failed audits (besides the excessive DOM size perf audit) on my own site/projects so getting 100s in everything except performance should be obtainable relatively soon once we remedy these failed audits. And also this discussion brings to light potential areas of improvement for page performance. Hopefully this acts as a good starting point. Let the journey begin!

cc @peterbe @schalkneethling

**Comment by schalkneethling** [comment]
Thanks so much @tannerdolby

**Comment by tannerdolby** [comment]
Your welcome @schalkneethling ! If there is anything that needs more clarification or an audit detail I've missed, let me know. Otherwise, I think we are prime to start chugging away at fixing these audit warnings to get 100 in Accessibility/SEO/Best Practices. The performance fixes will require more "work" and creating a separate dedicated issue for the performance audit warnings might not be a bad idea to reduce the clutter here.

**Comment by peterbe** [comment]
If it wasn't the amazing @tannerdolby I would have suggested we turn this into a discussion. Or close it and break it up into multiple little issues. But you've laid it out so nicely and we can pepper this with many "little" PRs that are flagged as `Part of #4060`. Great work as always!

**Comment by tannerdolby** [comment]
Update: July 14, 2021

### Accessibility: 97 ➡️ 100 
- `<iframe>` elements now have `title` attributes 
- headings are all in sequentially-descending order

### SEO: 98 ➡️ tbd (not including .social-icons in footer which are apart of redesign)
- add appropriate 8px spacing between elements so they don't overlap
- ensure that tap targets are atleast 48px by 48px

**Comment by tannerdolby** [comment]
After my latest update to comment above, here is the latest Lighthouse audit report:

<img width="572" alt="Screen Shot 2021-07-18 at 2 33 54 AM" src="https://user-images.githubusercontent.com/48612525/126062413-3927a212-4daf-4576-b1f8-7f968e3cba0e.png">

Plan:
- I'm going to dive into the performance improvements next week. 
- Regarding SEO: It's giving a 92% size tap target failure (which is really good and easily fixable) for the `<select>` element to change language within `.on-github` container, it doesn't seem to be overlapping so it must need to its tap target increased as `173x21` is not adhering to the 48px by 48px minimum tap size. After this is fixed, the only SEO audit failures are those related to `.social-icon`'s in the footer which are part of redesign and might be changing (which could resolve the tap target sizing and spacing in itself)

**Comment by caugner** [comment]
Closing in favor of https://github.com/mdn/yari/issues/7692.
