### ISSUE TITLE
Figure out the license of the content repo

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#408]
When this repo becomes Yari, we'll have all the content here. The stuff that's currently in a centralized MySQL database. 
[`stumptown-content` is similar](https://github.com/mdn/stumptown-content/pull/363) in that stuff that used to be in MySQL is now in Markdown files inside the repo. 

We need to figure out the right LICENSE and stuff for this repo too.

**Comment by peterbe** [comment]
What the work now involves is to:

1. Pick the right license for the content
2. Edit this file: https://github.com/mdn/content/blob/main/LICENSE
3. Edit this file: https://github.com/mdn/content/blob/main/package.json#L5

**Comment by peterbe** [comment]
The https://spdx.org/licenses/ lists variant of "CC-BY-SA" but nothing's called exactly that. They're all with a suffix of a version number.

**Comment by escattone** [comment]
From my reading of https://developer.mozilla.org/en-US/docs/MDN/About#Copyrights_and_licenses, I suspect we're going to need to specify three licenses for the https://github.com/mdn/content repo:
- a license for the documentation content (excluding the code-samples and snippets): `CC-BY-SA` (perhaps the latest version: https://creativecommons.org/licenses/by-sa/4.0/legalcode)
- two licenses to cover the code-samples and snippets:
    - CC0 license for everything added on or after August 20, 2010
    - MIT license for everything added before August 20, 2010

We've started an email conversation with the Mozilla legal department to answer these questions.

**Comment by peterbe** [comment]
This has been done. When we create the archived-content and translated-content we'll apply the same there.
