### ISSUE TITLE
Flaws Dashboard doesn't work in mdn/content

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#4082]
Steps to reproduce:

1. Clean checkout of `mdn/content` and `yarn && yarn start` in one terminal.
2. Open <http://localhost:5000/en-US/_flaws>
3. In a *new terminal* type `yarn build`
4. Return to <http://localhost:5000/en-US/_flaws> and it won't find anything built

**Comment by peterbe** [comment]
Pretty sure it's this: https://github.com/mdn/yari/blob/8b3a24a15b3aaec500c97df20fbd7fc521b2f295/server/flaws.js#L9 It's "too naive". Needs to read from an env var instead.

**Comment by peterbe** [comment]
To fully resolve this we need to merge two PRs:

- https://github.com/mdn/yari/pull/4093
- https://github.com/mdn/content/pull/6349

Together, you can now use `yarn build` and view the Flaws Dashboard entirely from the `mdn/content` repo.

**Comment by peterbe** [comment]
Actually, it depends on https://github.com/mdn/content/pull/6349 too.

**Comment by teoli2003** [comment]
This is done, I think. I'm using this all the time.
