### ISSUE TITLE
Adjust vertical alignment for "-x-" prefix atom

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#4087]
Related to #4045

<img width="432" alt="Screen Shot 2021-06-17 at 11 39 18 AM" src="https://user-images.githubusercontent.com/48612525/122454905-af500880-cf60-11eb-8050-8781e07a642c.png">

The above PR makes sure the atoms dont ever have a line break to stop text wrapping using `white-space: nowrap` but the alignment for "-x-" prefix atoms is a bit "low" towards the bottom with current `vertical-align: middle` declaration on the `<dt>` parent element that holds the nested `<abbr>` prefix.

**Comment by tannerdolby** [comment]
If we adjust `vertical-align` to be `bottom` or `top` the alignment is more centered and appears a bit cleaner.

*With `vertical-align: bottom`*
<img width="769" alt="Screen Shot 2021-06-17 at 11 53 03 AM" src="https://user-images.githubusercontent.com/48612525/122456621-a102ec00-cf62-11eb-8433-249bdd9b35d3.png">

*With `vertical-align: top`*
<img width="768" alt="Screen Shot 2021-06-17 at 11 54 18 AM" src="https://user-images.githubusercontent.com/48612525/122456789-cb54a980-cf62-11eb-9992-b0351c7f442e.png">

**Comment by tannerdolby** [comment]
CC @schalkneethling

**Comment by schalkneethling** [comment]
@tannerdolby Your suggestion would totally work but, I always wonder whether we can step back and see if perhaps we can clean up some of the CSS and just avoid this issue altogether. I say that because the CSS for the BCD tables has not had much love devoted to it in some time.

I am happy to accept a PR that does exactly what you suggest though so, feel free to ask me for review should you decide to open a PR. Thanks!

**Comment by tannerdolby** [comment]
Yeah I wonder the same thing, instead of providing a band-aid (which this PR does), we should probably give the BCD tables some love and fix the the root issue that causes the "low" alignment for the "-x-" prefix.

> I am happy to accept a PR that does exactly what you suggest though so, feel free to ask me for review should you decide to open a PR.

I think having this PR live to adjust the alignment until we take the time to redesign and update CSS for the BCD tables would be ideal. I opened one linked to this issue, will ping you for review in the PR thread. Thank you!
