### ISSUE TITLE
Audio Worklet example does not work

### ISSUE THREAD

**Issue by rowild** [mdn/yari#4094]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API/Using_AudioWorklet

As the title says, this does not work.

**Comment by wbamberg** [comment]
Thanks for filing! This was also reported at https://github.com/mdn/content/issues/6426.

**Comment by schalkneethling** [comment]
> Thanks for filing! This was also reported at [mdn/content#6426](https://github.com/mdn/content/issues/6426).

@wbamberg shall we close this one or first transfer to the content repo?

**Comment by wbamberg** [comment]
@schalkneethling , I think we can just close this one.
