### ISSUE TITLE
Horizontal Scroll on Search

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#4104]
https://developer.mozilla.org/en-US/search?q=reader gives a horizontal scroll on mobile for `ReadableStreamDefaultReader.ReadableStreamDefaultReader()`.

Mitigation could be applying `overflow-wrap: anywhere` (as `break-word: word-break` is marked as deprecated on MDN).
Other values show no effect for me.
`hyphens: auto` changes nothing here.

Selector seems to be `.search-results-list .title a`:
https://github.com/mdn/yari/blob/38a49ade973f8bcf465fc62167a8e69c6aaaa45d/client/src/site-search/search-results.scss#L50

**Comment by peterbe** [comment]
<img width="1016" alt="Screen Shot 2021-06-30 at 3 30 55 PM" src="https://user-images.githubusercontent.com/26739/124020348-2c936880-d9b8-11eb-83b2-c5cc3fcf9148.png">
You still get a horizontal scroll even with `hyphens:auto` on the `.title a` selector. 
Perhaps @schalkneethling knows how to fix.
