### ISSUE TITLE
`content add-redirect --help` is misleading

### ISSUE THREAD

**Issue by ddbeck** [mdn/yari#4106]
The help for `add-redirect` says to use URLs, but URLs don't work.

```
   ▸ yarn tool add-redirect <from> <to>


  ARGUMENTS

    <from>                               From-URL                                               
    <to>                                 To-URL       
```

## What I expected

Running `yarn content add-redirect https://developer.mozilla.org/en-US/docs/Web/API/BluetoothAdvertisingData  https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API` should create a redirect.

## What happened

```
yarn run v1.22.10
warning ../../../../package.json: No license field
$ env-cmd --silent cross-env CONTENT_ROOT=files node node_modules/@mdn/yari/tool/cli.js add-redirect https://developer.mozilla.org/en-US/docs/Web/API/BluetoothAdvertisingData https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API

error: From-URL must start with a / was https://developer.mozilla.org/en-US/docs/Web/API/BluetoothAdvertisingData

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This was quite confusing. A URL should start with a scheme, not a slash. This led me to try providing two paths and two slugs, neither of which worked.

To resolve this, I asked in Matrix chat, at which point I got some help in chat from Sphinx; he explained that it's the URL _path_, after `developer.mozilla.org`.

## Expected resolution

To fix this, I'd expect the tool to either do what the help says it ought to (if it's a bug with the tool) or for the help to actually describe the tool's behavior (if it's a bug with the help text).

Either way, it would help if the `add-redirect` help included an example or two.

**Comment by teoli2003** [comment]
Note that `yarn content move --help` use the (correct) terminology of _slug_. I think `add-redirect` should use it too.

<img width="918" alt="Screenshot 2021-06-29 at 18 49 35" src="https://user-images.githubusercontent.com/1466293/123837166-cf8da900-d90a-11eb-8cf8-eef834ea6e9e.png">

**Comment by ddbeck** [comment]
@teoli2003 except it doesn't work with a slug. You have to have the `/en-US/docs/`, in addition to the slug.

My real preference is that the tools would let you use file paths, for tab completion. The slug is in the file and so Yari must know how to construct complete URLs for them. It's a bit annoying that I have to do the work for the CLI.

**Comment by teoli2003** [comment]
@ddbeck. Oh good point. I would have been confused, too :-)

**Comment by peterbe** [comment]
> This was quite confusing. A URL should start with a scheme, not a slash. This led me to try providing two paths and two slugs, neither of which worked.

I agree. 

And is it fair to assume that we can do something like this:
```js
if (isAbsoluteURL(fromURL)) {
  fromURL = absoluteURL2RelativeURL(fromURL)
}
```

**Comment by caugner** [comment]
Let's pass `fromURL` and `toURL` into a `new URL()` and use the `pathname`. That should do the trick.
