### ISSUE TITLE
Is deploying translated-content halted?

### ISSUE THREAD

**Issue by mfuji09** [mdn/yari#4109]
According to https://whatsdeployed.io/s/16d/mdn/translated-content , deploying translated-content seems  halted since Jun 23.

**Comment by peterbe** [comment]
Yep, It's been busted for 6 days. https://github.com/mdn/yari/actions/workflows/prod-build.yml
I know what broke it. Working on a fix.

**Comment by peterbe** [comment]
The bug was that it tries to run `decodeURI` on `https://www.ecma-international.org/ecma-262/6.0/#sec-get-%typedarray%.prototype.buffer`. 

```
▶ node
Welcome to Node.js v16.3.0.
Type ".help" for more information.
> href = 'https://www.ecma-international.org/ecma-262/6.0/#sec-get-%typedarray%.prototype.buffer'
'https://www.ecma-international.org/ecma-262/6.0/#sec-get-%typedarray%.prototype.buffer'
> decodeURI(href)
Uncaught URIError: URI malformed
    at decodeURI (<anonymous>)
>

```

**Comment by peterbe** [comment]
This was the PR that caused it: https://github.com/mdn/yari/pull/4076

**Comment by peterbe** [comment]
@mfuji09 @SphinxKnight Thank you soooo much for highlighting this. The whole team is on vacation all of this week. That's why we've been so slow to notice. 
It reminds me, I really wish to set up SMS notification for breaking prod builds. :)

**Comment by mfuji09** [comment]
@peterbe @SphinxKnight 
Thank you very much!
