### ISSUE TITLE
Change `document.title` to "Loading..." when changing document

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#413]
We current use the router props in the `Document` component to know whether to trigger a call to `fetchDocument()`. When doing that it would be nice if the `document.title` could reflect it. 
A modern-day problem with any client-side navigation is that you don't get browser native loading animation on the tab when it's fully loading a new page. 
This can be simulated pretty well by editing the `document.title` in the DOM and/or editing the favicon.

**Comment by Gregoor** [comment]
Imo the perfect transition looks more like this:
https://codesandbox.io/s/nice-rain-765w3

To put it in words: Give the user an indicator where they clicked that the action they asked for is being performed, but don't change the current page yet until you have something meaningful to display, which imo holds for for both the main content and the document title.

**Comment by peterbe** [comment]
But that means that every `<Link to={docUrl}>{docTItle}</Link>` needs to be coded with this. I guess we could write a custom `Link` component that wraps `Link` but something that adds `className="clicked-loading"` and then CSS can add some text or animate the link. 

I not sure I love this more than attempting to do something with the `document.title`. It might be worth exploring further as a separate issue. Perhaps, if that works better, we close *this* issue in favor of that.

**Comment by KartikSoneji** [comment]
Hi, is this issue still open?

**Comment by KartikSoneji** [comment]
I think that the Material UI style progress bars are more visual than adding text, and has the added benefit of being more visible.

This is what I have right now:

![7opzzeDbwm](https://user-images.githubusercontent.com/25801283/134777572-a482e052-0731-43db-b6ff-90260c3e20d5.gif)

Or, we can just have the  (like https://developer.android.com):

![XLAZ7h20iy](https://user-images.githubusercontent.com/25801283/134777755-55035a9c-4888-4009-affc-5541713be2bf.gif)

**Comment by KartikSoneji** [comment]
@peterbe friendly ping.

**Comment by escattone** [comment]
> @peterbe friendly ping.

@KartikSoneji Just FYI, our friend and former colleague @peterbe has left Mozilla and joined a different organization, so he's no longer working with us on the MDN team. I wish I could say that we'll get to this soon, but I think it's going to be a while.

**Comment by KartikSoneji** [comment]
Oh, thanks for letting me know.
Wishing him the best at his new position.

**Comment by schalkneethling** [comment]
@fiji-flo I believe we already show "Loading" in the tab when transitioning to a new document. I do not know if we changed or added anything else as part of the redesign?

Any thoughts on https://github.com/mdn/yari/issues/413#issuecomment-927141418? Thanks!

**Comment by fiji-flo** [comment]
We do and will keep doing that.
