### ISSUE TITLE
Create vertical card component

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#4130]
For use on the bookmarks dashboard, and potentially other pages, we should create a vertical card component as part of the design system.

See https://www.figma.com/file/XWkzXs93Oo5uoMPmbr0rR6/MDN-Plus-User-Stories?node-id=36%3A33 for reference.

**Comment by mirunacurtean** [comment]
@schalkneethling  Hey, I'm trying to do some cleanup in regards to Bookmarks and gather some test data as well and I figure we can close this one as it's not up to date anymore.
