### ISSUE TITLE
MDN Web Docs sidebar

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#4144]
Discuss new proposed MDN Web Docs sidebar UX
https://www.figma.com/file/4gfgDODlSKbSpkkRGGGQbe/MDN-Desktop?node-id=1%3A178

- What is the current status of the proposed design?
- What are the technical challenges in implementing the proposed UX?
- As the updates are not only frontend, who are all the stakeholders?
- Once we have landed on a final design, have identified the technical and information architecture needs, we would need a breakdown of the tasks and the people responsible for each piece

**Comment by caugner** [comment]
@schalkneethling Can we close this as "not planned" (knowing that we will address the sidebar in 2023, but probably track elsewhere)?
