### ISSUE TITLE
Content doesnt display on kiwi browser

### ISSUE THREAD

**Issue by cardcraft** [mdn/yari#4153]
When using kiwi browser on my android device. latest version from playstore. when opening a link like https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div all content will turn white and become irresponsive. it does work on chrome and edge. i attached a video recording

https://user-images.githubusercontent.com/61369184/124394896-b4071180-dd01-11eb-8af8-736dd80d7ca0.mp4

**Comment by peterbe** [comment]
@cardcraft What appears to happen is that a JavaScript error is happening during hydration. Can you see about viewing it with a Web Console or something so we can see what the error might be?

**Comment by cardcraft** [comment]
@peterbe I currently dont have access to a computer. once i do i will try to debug this and send more information.
