### ISSUE TITLE
Create deep dive pages(s) for Twitter research experiment

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#4162]
To gain more insight into people's thoughts around the deep dives, we want to set up a page that we can point readers to via Twitter.

The page will be based on the design linked too below. There is no need for a reader to navigate to or from the page.

https://www.figma.com/file/XWkzXs93Oo5uoMPmbr0rR6/MDN-Plus-User-Stories?node-id=92%3A194

The quickest way to get this done, without having to be concerned with doing double work, or breaking any styles in production is to repurpose the landing page that was used for the initial experiment.

**Comment by schalkneethling** [comment]
From @dalexsy:

> I've put all the experiment stuff in its own file now: https://www.figma.com/file/y5mZ5Nt7AMSEppuGOfLvnB/MDN-Plus-Experiments?node-id=2%3A1214

> Since we are going to be showing more than one article, we're going to link directly to the article page from Twitter. The card at the top will be sticky like it did on the experiment page and the titles will link to the other articles in the series. We still have to decide if we're showing all three or not, but the design right now is if the third one isn't going to be available.

> The deep dive feature section is the same from the experiment page. Same with the survey, just with a different color scheme and different questions on the first page.
The icons I used are from the Carbon Design System and are open source.

**Comment by schalkneethling** [comment]
from @escattone:

> fyi, in my meeting with hermina this morning we talked about the deep-dive experiment and just wanted to pass on some comments/questions that arose from that discussion -- you all may already know about all of this (or i may be off), but just trying to make sure we all have a common understanding:

> 1. schalk will adjust (with input from daryl) the https://developer.mozilla.org/en-US/plus page to replace the Customize compat tables stuff with an image and text about dark mode, and remove the reference to annotate under the Build a permanent library box
> 2. schalk (and peter?) will create the deep-dive article pages that make-up rachel's deep-dive on "modern css in the real world", with the article content just baked into the react pages for simplicity -- what url structure do we want to use for those? daryl, do you already have a url structure in mind?
> 3. each of the deep-dive article pages will also contain a survey for rating the page -- will each page show the same survey allowing each of the article pages to be rated, or just a single question that allows only the current page to be rated?
> 4. peter will work on the backend changes needed to support the new survey/surveys

**Comment by schalkneethling** [comment]
from @peterbe:

> Regarding point 2. I think you take the first start @schalkneethling and make the new page. Once that’s up, I’ll do the Yari survey portion on top of that. Then I’ll also do the necessary changes to Kuma.

**Comment by dalexsy** [comment]
The updated copy for the landing page is here: https://www.figma.com/file/y5mZ5Nt7AMSEppuGOfLvnB/MDN-Plus-Experiments?node-id=13%3A104
