### ISSUE TITLE
Handle version numbers that overflow table cell in BC tables

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#4176]
Most version numbers only seem to be a single/double digit numeric value where others have more of the SemVer `MAJOR.MINOR.PATCH` format. For version numbers that are longer like `10.3.1`, the content will overflow and be hidden since `overflow: hidden` is on `.bc-table tbody td`. 

MDN Page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/concat

https://user-images.githubusercontent.com/48612525/124872983-c0e26a00-df7a-11eb-937d-9b02dbe75945.mov

**Comment by tannerdolby** [comment]
Changing `overflow: hidden` to `overflow: auto` isn't really an option because the green background won't cover all of the scrollable background within the cell when scrolled, therefore revealing the gray background behind it which isn't ideal. There isn't a way that reads nicely using `overflow-wrap` or `whites-space` to make the version number wrap when it does overflow. 

Changing the `writing-mode` to `tb-lr` would make it completely visible and "works" but is not really all that great, (it looks bit funky and is quite hard to read)

<img width="828" alt="Screen Shot 2021-07-08 at 12 02 26 AM" src="https://user-images.githubusercontent.com/48612525/124877318-d1491380-df7f-11eb-8c26-18ecee35fba3.png">

I can't think of a great way to prevent this overflow for long version numbers in the BC table at the moment. cc @schalkneethling

**Comment by peterbe** [comment]
cc @ddbeck too

**Comment by schalkneethling** [comment]
> I can't think of a great way to prevent this overflow for long version numbers in the BC table at the moment.

There is definitely not a simple way to address this unless we make rather large changes to the overall table. There is the option of setting overlap to ellipsis, but I am not sure how screen reader and keyboard accessible that would be. @ddbeck if you think that might be worth exploring, let me know.
