### ISSUE TITLE
Populate search input with query string

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#4185]
Today, I noticed, that when visiting MDN Web Docs via direct URL https://developer.mozilla.org/en-US/search?q=something (resp. „add bookmark for this search”, which replaces a placeholder before visiting the URL in Firefox) the following:

The headline informs me about the search term. The URL holds it. The filter highlights the term in the results.
But the search input itself remains blank. Which feels a bit odd, because I have to enter the term again if I made a typo.

Are there reasons to blank it?

**Comment by bershanskiy** [comment]
As of right now, I can not reproduce this bug. Perhaps, it was fixed in the meantime and we could close this issue?

**Comment by schalkneethling** [comment]
> As of right now, I can not reproduce this bug. Perhaps, it was fixed in the meantime and we could close this issue?

Thank you for letting us know! Will close it out. 🎉
