### ISSUE TITLE
Cramped figcaption with sibling paragraph content

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#4187]
On https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color the `<figure>` with `<figcaption>` content is kinda of "snug" next to the next `<p>` text in the document normal flow.

Since the `<p>` tags only have bottom margin from `_typography.scss` and the `figure` and `figcaption` have 0 margin, it makes the text underneath figcaption seem really close together. Adding a bit of bottom margin to the figcaption or figure would make this less crammed but not sure how that would affect other pages with `<figure>` + `<figcaption>`.

<img width="992" alt="Screen Shot 2021-07-10 at 3 02 12 PM" src="https://user-images.githubusercontent.com/48612525/125177454-b00b4180-e190-11eb-8e6b-b1e583f39c2c.png">

**Comment by peterbe** [comment]
Yep! I agree. A little `margin-bottom` on the `<figure>` would make a lot of sense.
