### ISSUE TITLE
CI didn't notice that the slug didn't match the folder

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#4188]
See https://github.com/mdn/content/pull/6734
If you look carefully, @Rumyra made the perfectly human error of accidentally forgetting to update the `slug` value. The folder was correctly named `.../firefox/releases/92` but a mismatch in folder and `slug` (from front-matter) should crash the CI build. In fact, I proved that with:

```
▶ yarn build files/en-us/mozilla/firefox/releases/92/index.html
yarn run v1.22.10
$ env-cmd --silent cross-env CONTENT_ROOT=files BUILD_OUT_ROOT=build node node_modules/@mdn/yari/build/cli.js files/en-us/mozilla/firefox/releases/92/index.html
CONTENT_ROOT:            /Users/peterbe/dev/MOZILLA/MDN/content/files
CONTENT_TRANSLATED_ROOT: not set
CONTENT_ARCHIVED_ROOT:   not set
Time to gather all translations: 4.210s
Error: The document's slug (Mozilla/Firefox/Releases/91) doesn't match its disk folder name (en-us/mozilla/firefox/releases/92)
    at buildDocument (/Users/peterbe/dev/MOZILLA/MDN/content/node_modules/@mdn/yari/build/index.js:288:11)
    at buildDocumentInteractive (/Users/peterbe/dev/MOZILLA/MDN/content/node_modules/@mdn/yari/build/cli.js:51:35)
    at buildDocuments (/Users/peterbe/dev/MOZILLA/MDN/content/node_modules/@mdn/yari/build/cli.js:130:15)
    at Se._action (/Users/peterbe/dev/MOZILLA/MDN/content/node_modules/@mdn/yari/build/cli.js:320:66)
    at Se.run (/Users/peterbe/dev/MOZILLA/MDN/content/node_modules/@caporal/core/dist/index.js:1:27590)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Te._run (/Users/peterbe/dev/MOZILLA/MDN/content/node_modules/@caporal/core/dist/index.js:1:32257)

error: The document's slug (Mozilla/Firefox/Releases/91) doesn't match its disk folder name (en-us/mozilla/firefox/releases/92)
```

So the Yari builder code is working at least.

**Comment by peterbe** [comment]
PS. https://github.com/mdn/content/pull/6769 corrects the actual problem so that Prod builds start to work again.

**Comment by peterbe** [comment]
The bug seems to be here: https://github.com/mdn/content/actions/runs/1015759281
It successfully built the changed changes. The reason the Yari builder was never given the chance to throw was because the `yarn build` command never ran. It would happen if the `git-diff-action` action decided that there were no files that changed!

As you can see https://github.com/mdn/content/actions/runs/1015759281 and https://github.com/mdn/content/runs/3030718839?check_suite_focus=true
 which mentions a bunch of warnings.

<img width="1203" alt="Screen Shot 2021-07-11 at 10 53 20 AM" src="https://user-images.githubusercontent.com/26739/125199882-45144600-e236-11eb-98c2-406f029c1104.png">

Are we using `git-diff-action` incorrectly? Are we using an ancient version? Is it a bug in `git-diff-action`??

**Comment by Rumyra** [comment]
omg I'm sooo sorry 🤦🏻‍♀️

**Comment by peterbe** [comment]
> omg I'm sooo sorry 🤦🏻‍♀️

no! This is *not* your fault. If anything, it's *my* fault. I wrote most of the automation around CI and git stuff. But it's actually nobody's fault because it's just a bug.

**Comment by peterbe** [comment]
Note-to-self; Perhaps we're using `get-diff-action` incorrectly. Either way, it should have failed early if the underlying `git diff ...` didn't work. I filed https://github.com/technote-space/get-diff-action/issues/164 and hoping for some help there.

**Comment by peterbe** [comment]
No update here other than I'm taking the P1 label off. I'm genuinely stumped and we might have either a bug in a lib or an extremely rare case of some race condition in the git storage. 
Let's keep it open till more clues, magically, appear.

**Comment by peterbe** [comment]
In the next release of `get-diff-action` it will exit non-zero if something goes wrong with the `git diff ...` it does internally. 
See https://github.com/technote-space/get-diff-action/issues/164#issuecomment-890529995

**Comment by escattone** [comment]
Thanks for tracking this in the `get-diff-action` repo @peterbe!
