### ISSUE TITLE
Markdown conversion error with nested `dl`

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#4205]
Looking at the Temporal docs, I found what looks like an error in the Markdown converter, when a `dd` contains a nested `dl` and then after the nested `dl` contains another element.

Given HTML like this:

```html
<dl>
  <dt>thing</dt>
  <dd>nested definition:
    <dl>
      <dt>thang</dt>
      <dd>stuff</dd>
    </dl>
  </dd>
</dl>
```

...I get the expected output:

```
- thing
  - : nested definition:
    - thang
      - : stuff
```

But given this:

```html
<dl>
  <dt>thing</dt>
  <dd>nested definition:
    <dl>
      <dt>thang</dt>
      <dd>stuff</dd>
    </dl>
    <p>I'm what breaks it</p>
  </dd>
</dl>
```

(i.e. an extra element after the nested `dl`), I get:

```
- thing
  - : nested definition:
    - thang \* : stuff I'm what breaks it
```

**Comment by fiji-flo** [comment]
@wbamberg It was harder than I wanted to, to get to the bottom of that.

It's an issue within https://github.com/remcohaszing/remark-prettier#readme

We can _just_ disable it for now and file an issue. Any opinion?

**Comment by wbamberg** [comment]
> We can just disable it for now and file an issue. Any opinion?

That means, completely disable Prettier formatting? That seems sad especially as some of the choices we've made have been guided by the desire to enable Prettier to work. Perhaps it is the best option though.

For the `<dl>` issue described above I wouldn't actually expect the error to happen very often because it seemed to require a nested `<dl>` with a block element after it. But since it's a Prettier issue, does that mean it's not specifically about `<dl>` conversion, but rather about how Prettier formats GFM lists? Since the underlying format we're using for `<dl>` is a list. That would make this a worse problem because it would potentially affect more pages.

**Comment by fiji-flo** [comment]
Paddling back. I dug more before filing a bug and it turns out it was our mistake.

I was expecting
```markdown
- thing
  - : nested definition:
    - thang
      - : stuff
    I'm what breaks it
```
- thing
  - : nested definition:
    - thang
      - : stuff
    I'm what breaks it
---

but it should be:
```markdown
- thing

  - : nested definition:

    - thang
      - : stuff

    I'm what breaks it
```
- thing

  - : nested definition:

    - thang
      - : stuff

    I'm what breaks it

---
Note the newline above _ I'm what breaks it_.

Creating a PR now.

**Comment by caugner** [comment]
Probably fixed by https://github.com/mdn/yari/pull/4221.
