### ISSUE TITLE
CLI to delete content without redirect is broken

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#4210]
I'm following the steps here: https://github.com/mdn/content#deleting-a-document and it doesn't seem to work anymore or the usage has changed and the docs need to be updated.  It feels a lot safer using the CLI to me anyway and the docs advice it, too.

_Originally posted by @Elchi3 in https://github.com/mdn/yari/pull/4166#discussion_r669666681_

**Comment by peterbe** [comment]
@Elchi3 I think you uncovered a bug that's unrelated to using dry-run mode or not. But it should be possible to delete a document, with the CLI, even if you don't intend to replace it with a redirect.

**Comment by vinyldarkscratch** [comment]
I can also confirm this regression while I was working on some new PRs for mdn/content.  While the pages I'm working on will require redirects (I didn't know that you could redirect during deletion as well), there are many times where I have submitted PRs that are simply removing deprecated, irrelevant interfaces and API features from BCD and MDN content.

Doing some debugging, it appears that this does have to do with the new dry-run changes presented in #4166, but luckily this will be a super easy fix!  All we need to do is perform a dry redirect addition only if we have defined a `redirect`.  I'll open a PR to resolve this!
