### ISSUE TITLE
Make popularities.json dynamic instead of checked into git

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#4217]
Today, the popularities are [checked into `mdn/content`](https://github.com/mdn/content/blob/09cd7c0431b3810d347a107bba81a6b156bfca77/files/popularities.json). As if it's the source of truth. 
In Yari, as of [this PR](https://github.com/mdn/yari/pull/3844) we now download the popularities from S3 right before building, every time we build. That's better. 
The best source of truth is the S3 file, which the `yarn tool popularities` CLI tool knows to download from, and that should be all we need. No need to check in the `popularities.json` file into git at all. 

But writers who use yari from the mdn/content repo, via the `@mdn/yari` NPM package, will still benefit from having the popularities for local writing. Then they can know instantly if the page their looking at is popular. E.g the "Flaws Dashboard" too. 

We should treat the fetching of the popularities like we're fetching the RSS feed, for our home page, from hacks.mozilla.org. It gets downloaded every time we build, and for local laptop dev, we can cache it in the tmp directory so that each `yarn dev` doesn't get so slow. We also need to make sure the `popularities.json` file gets shipped into the NPM package.

**Comment by foolip** [comment]
This was fixed by https://github.com/mdn/yari/pull/4286, right?

**Comment by caugner** [comment]
> This was fixed by #4286, right?

No, that PR only fixed it for mdn/yari, but in the context of mdn/content, `yarn tool popularities` is not run yet.

**Comment by LeoMcA** [comment]
> but in the context of mdn/content, yarn tool popularities is not run yet.

I don't think it needs to be, since `popularities.json` is already in the npm package. Closing as fixed, please reopen if you disagree.
