### ISSUE TITLE
A bug found: a particular paragraph is shown if language is changed from some languages to other languages

### ISSUE THREAD

**Issue by logic-finder** [mdn/yari#4227]
Hello I think I just found a bug at [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) article.

I think you can find this bug if you take the following steps:
1. go to one of the Web Audio API articles of the following list:
![image](https://user-images.githubusercontent.com/83723320/125932814-e3dbcd88-1a4a-4721-a6f5-474fee29c234.png)
2. then click 'View in English'.
![image](https://user-images.githubusercontent.com/83723320/125932893-da9d4dfa-42cc-46ad-95c3-630201d4e563.png)
3. now 'Obsolete interfaces' paragraph appears.
![image](https://user-images.githubusercontent.com/83723320/125934348-8a243587-25d5-4369-8b29-660992a56b95.png)

As far as I observe this bug, there are some features.
- In case of Spanish, French, and Chinese, 'Obsolete interfaces' paragraph seems to be translated into their respective language.
- In case of Korean, 'Obsolete interfaces' paragraph is not translated and it's written in English.
- In case of Russian, 'Obsolete interfaces' paragraph is not translated and it's written in English. Also, the paragraph is at the middle of the article, not at the top of the article like other cases. (Though the paragraph title comes first at 'table of contents' menu)
![image](https://user-images.githubusercontent.com/83723320/125936725-faca95d7-a115-4498-81cd-331621bc3ffd.png)
- You can collect the paragraph repeatedly like this:
![image](https://user-images.githubusercontent.com/83723320/125942697-85f232e9-f9ba-405f-b046-8d236203e880.png)
(order: en-US → french → view in english → spanish → view in english → spanish → view in english → french → view in english → french → view in english → french → view in english)

※ It seems there is some unrevealed rule or condition at making the paragraph appear. For example, changing language from Chinese to Korean doesn't work, but Chinese → View in English works. mysterious)

p.s. Sorry for messy description and I'm not sure this is a right place to submit this issue since I'm a newbie; please let me know if there are any mistakes. Thank you.

**Comment by peterbe** [comment]
Which URL were you on when you got "Obsolete interfaces" in the "Table of contents" menu?

**Comment by logic-finder** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API#example

**Comment by peterbe** [comment]
Wow! What's going on here?!

https://user-images.githubusercontent.com/26739/126000090-ae9a1bab-05c3-4f8c-84f5-039e111cd7ba.mov

I visit https://developer.mozilla.org/ko/docs/Web/API/Web_Audio_API then I click "View in English". Then, I hit the Back button and the Forward button and suddenly the English content changes. Yikes. 
I'll investigate.

**Comment by peterbe** [comment]
I wonder if this has something to do with it! 
There are two `id="example"` in the HTML. 
<img width="497" alt="Screen Shot 2021-07-16 at 3 39 42 PM" src="https://user-images.githubusercontent.com/26739/126000439-297b245d-0787-4426-aa6c-14484580ac57.png">

I still want to figure out what's going on.

**Comment by peterbe** [comment]
Hehe. I can reproduce this locally too. 
<img width="1616" alt="Screen Shot 2021-07-16 at 3 55 44 PM" src="https://user-images.githubusercontent.com/26739/126002008-38d31590-a7e7-440d-b775-f5ea0a2d2f33.png">

**Comment by peterbe** [comment]
Oh I see. It's a dangerous to mess with keys that repeat in React. 
<img width="1616" alt="Screen Shot 2021-07-16 at 3 57 11 PM" src="https://user-images.githubusercontent.com/26739/126002129-420d338f-53b1-4953-84ea-9850cf460f32.png">

**Comment by tannerdolby** [comment]
This is so interesting, I'm really curious on what is the root cause as well. 

@peterbe Yep, React is really strict on children having unique `key` attributes.
