### ISSUE TITLE
2b890eb broke CI (check_redirects) for mdn/content and mdn/translated-content

### ISSUE THREAD

**Issue by SphinxKnight** [mdn/yari#4228]
https://github.com/mdn/yari/commit/2b890eb3abc7b2a6ecad7548ccda20bc39639af4 / https://github.com/mdn/yari/pull/4218 had a side effect which broke CI for mdn/(translated-)?content

Failed run for mdn/content 
https://github.com/mdn/content/runs/3087463100?check_suite_focus=true
Failed run for mdn/translated-content
https://github.com/mdn/translated-content/pull/1566/checks?check_run_id=3088100822

Screenshot of git-bisect on the issue: 
![image](https://user-images.githubusercontent.com/2413436/125983567-be572558-a568-4525-9cf4-e85648085c58.png)

cc @peterbe / @escattone 
see also #3323

**Comment by SphinxKnight** [comment]
@peterbe I think this one should be reopened as it still fails for mdn/translated-content.

**Comment by peterbe** [comment]
> @peterbe I think this one should be reopened as it still fails for mdn/translated-content.
> 
> https://github.com/mdn/translated-content/actions/runs/1038454368

You're not wrong, but I'm sort of one step ahead of you :)
See https://github.com/mdn/translated-content/pull/1573 

Now, as of that, you can use this new Yari where archived redirect URLs are gone.
