### ISSUE TITLE
Broken Link in https://www.mozilla.org/en-US/contribute/

### ISSUE THREAD

**Issue by vighnesh192** [mdn/yari#4235]
Clicking on Contribute to Mozilla Codebase card in How to Contribute section takes us to a page that doesn't exist.

**Comment by tannerdolby** [comment]
Yes I see the same thing. Nice catch @vighnesh192 !

So this seems to be a deeper problem as the link is (or was) pointing to MDN archived content. There is a bug filed in bugzilla  www.mozilla.org https://bugzilla.mozilla.org/show_bug.cgi?id=1714434, it seems that someone has been assigned and is working on it.

cc @peterbe

**Comment by peterbe** [comment]
Let's hope someone follows up on https://github.com/mozilla/bedrock/issues/10340 instead.
