### ISSUE TITLE
"Loading chunk" error on some MDN pages

### ISSUE THREAD

**Issue by kg** [mdn/yari#4236]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry goes blank a couple hundred ms after loading, with these errors in devtools:

```
Content Security Policy: Couldn’t process unknown directive ‘script-src-elem’
Loading failed for the <script> with source “https://developer.mozilla.org/static/js/6.397539b0.chunk.js”. FinalizationRegistry:1:1
ChunkLoadError: Loading chunk 6 failed.
(error: https://developer.mozilla.org/static/js/6.397539b0.chunk.js)
    Webpack 57
react-dom.production.min.js:216:199
Uncaught ChunkLoadError: Loading chunk 6 failed.
(error: https://developer.mozilla.org/static/js/6.397539b0.chunk.js)
    Webpack 57
bootstrap:172:17
```

**Comment by peterbe** [comment]
What happens when you open https://developer.mozilla.org/static/js/6.397539b0.chunk.js in a new tab?
Does it load?

What it could be is that you were so unlucky that your network failed when it loaded this particular JS bundle.

**Comment by kg** [comment]
```Content Encoding Error

An error occurred during a connection to developer.mozilla.org.

    Please contact the website owners to inform them of this problem.```

I tried shift-refresh to fix the issue, and that didn't work. I haven't cleared my entire cache and history, though.

**Comment by peterbe** [comment]
And what if you try `curl`, like:

```
▶ curl -I https://developer.mozilla.org/static/js/6.397539b0.chunk.js
HTTP/2 200
content-type: application/javascript; charset=utf-8
content-length: 17111
date: Wed, 23 Jun 2021 17:35:38 GMT
cache-control: max-age=31536000, public
last-modified: Fri, 18 Jun 2021 02:02:47 GMT
etag: "44301a5f3c614386dda87ac11d1e8e4c"
server: AmazonS3
x-frame-options: DENY
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
strict-transport-security: max-age=63072000
vary: Accept-Encoding
x-cache: Hit from cloudfront
via: 1.1 dc88537beb5e26d4e490ca74560553cd.cloudfront.net (CloudFront)
x-amz-cf-pop: ATL52-C1
x-amz-cf-id: eKBUm7qgdhqNSbo2QPL3xWi7yRT-BwzH1eL2PaM7tpm8QDq-8AT_4w==
age: 2241583

```

**Comment by kg** [comment]
```
StatusCode        : 200
StatusDescription : OK
Content           : (this.webpackJsonpclient=this.webpackJsonpclient||[]).push([[6],{131:function(e,t,n){"use
                    strict";n.r(t),n.d(t,"default",(function(){return H}));var
                    r=n(6),a=n(3),s=n(0),c=n(1),o=n.n(c),i=n(2),l=o.a.c...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    X-Frame-Options: DENY
                    X-XSS-Protection: 1; mode=block
                    X-Content-Type-Options: nosniff
```

Seems like it was a transient failure that got cached. I think MDN's frontend might benefit from having a way to detect that a chunk load failed like this and either show an error message or re-try it somehow - I got a completely blank page and had to dig through the devtools logs to figure out which error messages were relevant + stuck across multiple loads.

**Comment by peterbe** [comment]
I totally agree. It's a shortcoming in how Webpack 4 works, which is what we have to rely on since we use `create-react-app` (via `react-scripts`). 
We do have a little bit of control over the lazy-loading but even if we use that to inject a "toast message" I wonder how we could ever make it appear if the whole page has gone all blank :)

**Comment by peterbe** [comment]
Another example of it happening: https://bugzilla.mozilla.org/show_bug.cgi?id=1721431

**Comment by craigdallimore** [comment]
I'm afraid I've encountered this recently. Initially I tried clearing the site data using devtools without success. Going into the firefox settings (`about:preferences#privacy`) and clearing _all_ site data worked. A bit unfortunate, but at least there is a way.

**Comment by schalkneethling** [comment]
> I'm afraid I've encountered this recently. Initially I tried clearing the site data using devtools without success. Going into the firefox settings (`about:preferences#privacy`) and clearing _all_ site data worked. A bit unfortunate, but at least there is a way.

@mdn/core-dev perhaps something to keep an eye on.

**Comment by caugner** [comment]
Maybe this happens when
1. an MDN page is loaded immediately before our CDN is invalidated, and
2. that outdated page loads a chunk that no longer exists.
