### ISSUE TITLE
Not excluding translations with localized slugs

### ISSUE THREAD

**Issue by escattone** [mdn/yari#426]
@peterbe surfaced an error in #420 (see https://github.com/mdn/stumptown-renderer/pull/420#issuecomment-606746286), which when I tracked it down, was due to the fact that although we're excluding all documents that start with a prefix like `Project:` (see [`DEFAULT_EXCLUDE_SLUG_PREFIXES`](https://github.com/mdn/stumptown-renderer/blob/5a15cd1912482b0fb189f360716f0bc1d23e1094/content/scripts/constants.js#L26)), we're **not excluding translations of those documents that have localized the slug**. For example, in the case that @peterbe surfaced, the issue was caused by `/fa/docs/پروژه:حقنشر`, which is a translation of `/en-US/docs/Project:Copyrights` (which actually redirects to `/en-US/docs/MDN/About#Copyrights_and_licenses`).

**Comment by peterbe** [comment]
[I'm pretty sure we had a solution for this](https://github.com/mdn/stumptown-renderer/pull/398)
It just needs some rethinking and refactoring. 
So now I'm confused about the overlap of https://github.com/mdn/stumptown-renderer/pull/420 vs. https://github.com/mdn/stumptown-renderer/pull/398

PS. If PR #420 does all of what PR #398 does, but better, then that's cool.

**Comment by escattone** [comment]
@peterbe My understanding of #420 vs #398 is that #420 is a superset of #398, it does all that #398 does and more (assuming of course that #427 is merged to address this issue).
