### ISSUE TITLE
Loaded content is lost and changes to error page when internet goes down

### ISSUE THREAD

**Issue by TwoFistedJustice** [mdn/yari#4260]
I live on a ranch with really terrible rural internet that frequently drops connections. Even my Verizon hotspot can't get a consistent signal here.

Whenever my connection drops while I am reading MDN docs, I lose my page. Some element tries to load or reload and when it inevitably fails, the whole page is replaced by an error page. This is actually quite disruptive to my work flow since I can no longer view the content that was already loaded, and that I was actually reading.

**What I expect to happen:**
Once page content loads, it remains viewable, even if some other content fails to load.

**What actually happens:**
All previously loaded content is lost when an element fails to load.

**Comment by peterbe** [comment]
You're now the third person to bring this up. 
https://github.com/mdn/yari/issues/4236 is the first one. 

I'm so disappointed in the way our framework wraps Webpack but perhaps it's time to bring out some hacks to cope better with it.
