### ISSUE TITLE
The search bar inside the MDN website is not working

### ISSUE THREAD

**Issue by nirkopler** [mdn/yari#4296]
**Search Bar Issue**: The search bar only displays related results while typing, when press "enter" / search, there is no data in the search result page.
For example: type "button" in search bar, hit "enter" => (redirect to search results page), the page has no content (results).

**Comment by peterbe** [comment]
Thanks! It's because our site-search appears to currently be broken. We're investigating it right now.

**Comment by peterbe** [comment]
This PR fixed it, locally, https://github.com/mdn/kuma/pull/7947 but I'm not going to close this issue until that's been pushed to production.

**Comment by peterbe** [comment]
Fixed! We're just waiting for the cache invalidation on the CDN.

**Comment by nirkopler** [comment]
Great! 👍
