### ISSUE TITLE
Fix sync-translated-content

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#4297]
See https://github.com/mdn/yari/pull/4295 and https://github.com/mdn/yari/issues/4288

- cope with the `index.md` vs `index.html` within the Node code
- revert https://github.com/mdn/yari/pull/4295
- [these lines](https://github.com/mdn/translated-content/blob/81f5106823ff9bdb65d8908573a14f03bbce2691/.github/workflows/sync-translated-content.yml#L61-L63) no longer work because the [`main` branch is protected](https://github.com/mdn/translated-content/settings/branch_protection_rules/21441301) such that it needs at least 1 reviewer. Perhaps lax that requirement or figure out some workaround
- [The GitHub Action itself](https://github.com/mdn/translated-content/actions/workflows/sync-translated-content.yml) is currently disabled.

**Comment by fiji-flo** [comment]
#4310 fixes the Node code.

Once the laded we can revert #4295 

How we deal with the protected main branch is another question. I vote for relaxing the restriction for now.

**Comment by peterbe** [comment]
All done now. @escattone started a Stage build to make sure it worked.

**Comment by peterbe** [comment]
You can't see the log lines from the `yarn tool sync-translated-content` while [it's going on](https://github.com/mdn/yari/runs/3163346768?check_suite_focus=true).
