### ISSUE TITLE
missing page by reference object

### ISSUE THREAD

**Issue by anrybalkin** [mdn/yari#4303]
when I try to see a reference to objects, I see that
Sorry, the page /en-US/docs/orphaned/Web/JavaScript/Reference/Global_Objects/Object could not be found.

**Comment by tannerdolby** [comment]
Could you elaborate a bit more? How exactly did you get to the page https://developer.mozilla.org/en-US/docs/orphaned/Web/JavaScript/Reference/Global_Objects/Object ?

The correct URL for viewing the `Object` reference is https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object

**Comment by tannerdolby** [comment]
The correct URL for viewing the `Object` reference is https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object 

This could be probably be closed unless OP can provide a link to how they arrived at that URL/MDN page.

**Comment by anrybalkin** [comment]
this link was given by google ,https://developer.mozilla.org/en-US/docs/orphaned/Web/JavaScript/Reference/Global_Objects/Object
is already working and google provides the correct link 
sorry to bother you

**Comment by tannerdolby** [comment]
> Thanks for the link and google now provides the correct link.. sorry to bother you

Your welcome! And oh your not a bother at all :) I really enjoy finding/fixing bugs so its all good fun. Feel free to start up the conversation here if you encounter any more issues in the next few days.

**Comment by peterbe** [comment]
It was an unfortunate bug in our deployment process. We stopped it late last week and then now we have a [fix](https://github.com/mdn/yari/pull/4310).
