### ISSUE TITLE
{{CSS_Ref}} misses some data entries

### ISSUE THREAD

**Issue by hinell** [mdn/yari#4305]
Somehow the [`{{CSS_Ref}}`][CSS_Ref] macros misses the [@document] at rule in the [CSS references]

[CSS_Ref]: https://github.com/mdn/yari/blob/main/kumascript/macros/CSS_Ref.ejs
[CSS references]: https://developer.mozilla.org/en-US/docs/Web/CSS/Reference
[@document]: https://developer.mozilla.org/en-US/docs/Web/CSS/@document

The brief investigation has revealed that the culprit isn't data source for sure:
https://github.com/mdn/data/blob/master/css/at-rules.json#L113-L124

**Comment by tannerdolby** [comment]
Since the the `@document` at-rule is now deprecated. The KS macros `CSS_Ref` could be intentionally missing that `@document` rule. Not entirely sure though.

**Comment by hinell** [comment]
@tannerdolby Sounds reasonable.

**Comment by tannerdolby** [comment]
Just to be sure, cc @schalkneethling

**Comment by wbamberg** [comment]
> Since the the `@document` at-rule is now deprecated. The KS macros `CSS_Ref` could be intentionally missing that `@document` rule since its been removed from relevant web standards. Not entirely sure though.

That seems to be more or less right:

https://github.com/mdn/yari/blob/main/kumascript/macros/CSS_Ref.ejs#L20
https://github.com/mdn/yari/blob/main/kumascript/macros/CSS_Ref.ejs#L175-L177

**Comment by tannerdolby** [comment]
Yeah I hadn't take a deep look but that's along the lines of what I imagined was happening. Thanks for verifying @wbamberg !
