### ISSUE TITLE
Suggestion: Remove a title in the `[]()` syntax in markdown. (h2m converter)

### ISSUE THREAD

**Issue by hochan222** [mdn/yari#4320]
- **Suggestion: Remove a title in the `[]()` syntax in markdown.**
  - **Final format:** `[모듈 패턴](http://www.google.com/search?q=javascript+module+pattern)`

I had a question while converting html to markdown in that [PR](https://github.com/mdn/translated-content/pull/1698).

```html
<a href="http://www.google.com/search?q=javascript+module+pattern" title="http://www.google.com/search?q=javascript+module+pattern">모듈 패턴</a>
```
I have seen the following code convert as follows.
```
[모듈 패턴](http://www.google.com/search?q=javascript+module+pattern "http://www.google.com/search?q=javascript+module+pattern")
```

[That grammar was an existing grammar in GFM.](https://github.github.com/gfm/#example-493)

However, I think there is a disadvantage that can be obtained by additionally specifying the title in markdown `[]()`.

- The amount of documents becomes long.
- Reduces readability.
- You have to think more about the format by increasing the complexity of the format.
- In the end, it directly leads to errors in maintenance and can reduce the quality of documents.
- This is not an attribute that exists in the a tag. https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a
  - (But `title` is an attribute of `HTMLElement`.)

This is contrary to the reasons for adopting the markdown approach. [OWD project: convert MDN content to Markdown ](https://github.com/openwebdocs/project/issues/25)

Why do we need a title?

**Comment by wbamberg** [comment]
I agree that we should remove `title` attributes from links.

**Comment by peterbe** [comment]
If you see 

```html
<a href="http://www.google.com/search?q=javascript+module+pattern" title="http://www.google.com/search?q=javascript+module+pattern">모듈 패턴</a>
```
I think you can safely replace it with
```html
<a href="http://www.google.com/search?q=javascript+module+pattern">모듈 패턴</a>
```
