### ISSUE TITLE
Fix fixable flaws in Markdown documents doesn't yet work

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#4333]
See https://github.com/mdn/yari/blob/186b3e1244391e828609646d891756938b4b3802/build/flaws/index.js#L85

**Comment by peterbe** [comment]
CC @wbamberg @Elchi3 Because you missed the conversion about this in Slack :)

**Comment by caugner** [comment]
https://github.com/mdn/yari/pull/6173 partly addressed this, adding a `yarn tool fix-flaws` command that allows fixing broken links.

**Comment by caugner** [comment]
Closing, as the `fix-flaws` command exists now and the issue is not actionable/specific otherwise.
