### ISSUE TITLE
Add browser release date to compatibility tables and a section where it is suggested or not to use said technology

### ISSUE THREAD

**Issue by Barbieroalex** [mdn/yari#4387]
- Browser release date (can be on hover)
- A section where it is suggested or not to use said technology
- How many users may be affected if we use said technology

The graph is pretty good, but it would be great to know what the experts recommendation is for using the different technologies.
it could be something like:

- You can use this technology with confidence 97% of the world's users have a compatible browser
- You can use Array.prototype.reduce() with confidence 99% of the world's users have a compatible browser

**Comment by caugner** [comment]
> Browser release date (can be on hover)

In the mean-time these are in fact shown on hover.

> A section where it is suggested or not to use said technology
> How many users may be affected if we use said technology

Caniuse answers these questions, and it has been suggested in https://github.com/mdn/yari/issues/4800 to add a link.

Beyond that, we don't have any plans in this regard, so I'm closing this as "won't fix" / "duplicate".
