### ISSUE TITLE
The .bc-icons inside the .bc-notes-wrapper aren't aligned consistently

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#4389]
The `.bc-icons` container is aligned with `vertical-align: text-top` and thats causing the text on the left of the icon to be "higher" up than the icon making the misalignment quite obvious. This could be intended in the design system but I wanted to bring it to light in case we were looking for "perfect" alignment. The "17-53" and the `.bc-icon` in the screenshot below highlight this misalignment.

<img width="977" alt="Screen Shot 2021-08-02 at 12 47 44 PM" src="https://user-images.githubusercontent.com/48612525/127915531-e9e2d31a-fae9-4d89-97f2-2e5f8e5e2871.png">

<img width="707" alt="Screen Shot 2021-08-02 at 10 28 36 PM" src="https://user-images.githubusercontent.com/48612525/127962738-670f48d2-656b-4b07-96ad-6a0a82a47cc7.png">

**Comment by tannerdolby** [comment]
The "star" svg icons are nearly as noticeably misaligned, which has to do with their computed sizes. It seems that because of the difference sizes that the "-x" and the "star" icons create, we are trying to find a "sweet spot" with the vertical alignment. 

I say this, because `vertical-align: baseline` works perfectly to keep the "-x" vertically aligned with its neighboring text, but the star looks "too high up" in the y-direction when using `baseline`. I want to find something to remedy the `17-53 -x-` alignment for .bc-icons that have a vendor prefix instead of the star svg.

<img width="1010" alt="Screen Shot 2021-08-02 at 1 25 28 PM" src="https://user-images.githubusercontent.com/48612525/127919503-511fe7af-69e5-45a8-900f-e9e0bc8ca6b4.png">

**Comment by peterbe** [comment]
You're already impressive @tannerdolby but if you can fix that ugly misalignment you'll be an even bigger star. I've also thought it was so annoying and buggy-looking.

**Comment by tannerdolby** [comment]
> You're already impressive @tannerdolby but if you can fix that ugly misalignment you'll be an even bigger star. I've also thought it was so annoying and buggy-looking.

Thank you lots @peterbe! I think I've got it, a combination of two vertical-aligns. Will submit a PR shortly.

**Comment by tannerdolby** [comment]
Voila! 🎉 After tinkering (for quite a bit) I ended up settling on a combination of `vertical-align: middle` for the `<abbr>` within `.bc-icons` and `vertical-align: sub` for the `<i>` within `.bc-icons`. I think it looks almost "perfectly" aligned now, for both the "-x" vendor prefix and the "star" svg.

<img width="1002" alt="Screen Shot 2021-08-02 at 1 36 56 PM" src="https://user-images.githubusercontent.com/48612525/127920669-da260a0e-43e6-49e7-87b4-5a2a9e723d4a.png">

<img width="1033" alt="Screen Shot 2021-08-02 at 1 37 13 PM" src="https://user-images.githubusercontent.com/48612525/127920694-f045e9f2-ddd3-4ac8-9c35-15a7528e89ee.png">

**Comment by tannerdolby** [comment]
Just checked a page to view alignment now that the updates have hit the main site, and it sure looks good! 🎉 

https://developer.mozilla.org/en-US/docs/Web/CSS/flex

<img width="996" alt="Screen Shot 2021-08-13 at 12 16 19 PM" src="https://user-images.githubusercontent.com/48612525/129408158-e10eb21d-1b2b-4eb2-9b52-69f61cb54e45.png">
