### ISSUE TITLE
Error 500 from local server when fixing fixable flaws

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#4392]
I've started to get this error when I try fix fixable flaws (Windows)

![image](https://user-images.githubusercontent.com/5368500/127936831-69c59de9-f8b1-4ce5-9796-19c630660a2e.png)

**Comment by peterbe** [comment]
If you can help to review https://github.com/mdn/yari/pull/4334 that would be great.

**Comment by hamishwillee** [comment]
Done
