### ISSUE TITLE
Avoid inserting section permalinks after DOM render, in DOM

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#44]
On https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video for example. The HTML sent from the server to the browser looks like this:

```html
<h2 id="Attributes">Attributes</h2>
```

Then, a piece of (jQuery??) code kicks in after the .js has been downloaded, parsed and executed (after `document.onload`) that turns that into this:

```html
<h2 id="Attributes">Attributes
   <a href="/en-US/docs/Web/HTML/Element/video$edit#Attributes" class="button section-edit only-icon" rel="nofollow, noindex">
    <svg class="icon icon-pencil" version="1.1" width="24" height="28" viewBox="0 0 24 28" aria-hidden="true" focusable="false"><path d="..."></path></svg>
    <span>Edit</span>
  </a>
  <a class="local-anchor" href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element/video#Attributes" data-heading-id="Attributes">
    <svg class="icon icon-link" version="1.1" width="24" height="28" viewBox="0 0 512 512" aria-hidden="true" focusable="false"><path d="..."></path></svg>
    <span>Section</span></a>
</h2>
```

Let's *not* do that in stumptown. 

Not only does it cause the page to "flicker" as the little section chain-icons suddenly appears. That makes the site feel "wobbly". It can also cause a re-paint (aka. recalculate style). 

Note: Using Chrome Performance dev tools, with 6x CPU slowdown, I found 4!! blocks of "Recalculate style" in the first 3.5 seconds! It's very hard to exactly see how large the repaint is due to the added extra `<a>` tags. 

Either way, it should be avoidable. I.e. let's not modify the DOM shipped from the HTML from the server. At least not just to add section links. 

I think (and hope) the permalink section can be done entirely with CSS.

**Comment by peterbe** [comment]
Whatever we do, the **stumptown-content shouldn't have to do anything to cater to this**. 
If it does turn out that we *need* to inject more HTML next to the `<h2>` tag, then let's do something like:
```javascript
  // PSEUDO CODE
  renderedHtml = renderedHtml.replace(/<\/h2>/g, '</h2> <a href="#anchor">Link</a>')
```

**Comment by joedarc** [comment]
Were you thinking maybe a utility type component for like `<AnchorTag>`? Could accept some props for what tag type it is an do the `React.createElement` to inject the extra goods?

**Comment by peterbe** [comment]
> Were you thinking

To be honest, now I'm losing confidence in this one. We're about to massively change how the main document components are going to work. At this very moment, we're hardcoding how rendering is supposed to work. There's a React component called [`RenderHTMLElementDocument`](https://github.com/mdn/stumptown-renderer/blob/815cb5652a4e5164453a6a0506806410b7161dfd/client/src/document.js#L77) which just tied us over till we have a better idea. 

Now, in https://github.com/mdn/stumptown-content/pull/107 we're changing all of this. Soon, the renderer just needs to loop over the JSON content from stumptown-content/packaged and use that `type` key to decide which "ingredient React component" to use. 

Either way, starting [here](https://github.com/mdn/stumptown-content/pull/107#issuecomment-522723897) there are some outstanding issues with regards to how we should make those `<h>` tags should be rendered with an ID attribute. 

All in all, perhaps this is not a good issue to tackle at the moment.

**Comment by joedarc** [comment]
No worries, i understand. I'll check out some other issues. If there are areas in the BCD table that need ID set that way i can adjust.

**Comment by peterbe** [comment]
Let's go here instead: https://github.com/mdn/yari/issues/1004
