### ISSUE TITLE
Content bug: "Problem with Responsiveness"

### ISSUE THREAD

**Issue by itssabhishek** [mdn/yari#4433]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/button

## Specific page section or heading?

HTML Button demo section
![Screenshot_20210808-074759](https://user-images.githubusercontent.com/68913813/128618695-ad75de69-5831-4a32-9041-d76e577bf130.png)

## What is the problem?

The content is not adaptive to Mobile screen.

## What did you expect to see?

Full view of button code and its preview

## Did you test this? If so, how?

By using smartphone.

**Comment by itssabhishek** [comment]
> Thanks for raising this. Alerting @mdn/core, who maintain the Yari code (including the frontend code)

If you don't mind then I wanted to solve this issue. I am a 2nd year computer science student and i have good knowledge about responsiveness. Also i have made several fully responsive websites. But again this is MDN's webpage and you guys have lots of very talented and experience persons than me. Sorry if i wasted your time. Thanks you and it would be an honor to contribute in MDN.

**Comment by peterbe** [comment]
@schalkneethling Should this be solved with `bob` instead?

**Comment by schalkneethling** [comment]
@itssabhishek @sideshowbarker @peterbe There is currently a discussion going on about this problem as part of the redesign. For right now, I will not recommend investing much, if any, energy into this until we have made a call. Thank you for reporting and offering to help @itssabhishek ❤️

**Comment by caugner** [comment]
This issue has been fixed as part of the redesign:

<img width="454" alt="image" src="https://user-images.githubusercontent.com/495429/202023800-c8aabe25-2e66-444e-9334-e3ec14542285.png">
