### ISSUE TITLE
{{InheritanceDiagram}} create the empty space, but no diagram in it anymore

### ISSUE THREAD

**Issue by AnilSeervi** [mdn/yari#4434]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent

#### What information was incorrect, unhelpful, or incomplete?
`{{InheritanceDiagram}}` missing from page - https://github.com/mdn/content/blob/main/files/en-us/web/api/touchevent/index.html#L19

#### Specific section or headline?
TouchEvent headline

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/touchevent`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/touchevent/index.html
* Last commit: https://github.com/mdn/content/commit/02978bafd8719a9554e5d0cc02f83385e9ac972d
* Document last modified: 2021-07-24T21:38:16.000Z

</details>

**Comment by sideshowbarker** [comment]
Fixed by https://github.com/mdn/yari/pull/4432 — so this can be closed

**Comment by AnilSeervi** [comment]
> Fixed by https://github.com/mdn/yari/pull/4432 — so this can be closed

Yes, the images are visible now.
