### ISSUE TITLE
EmbedLiveSample macro does not support translated slugs

### ISSUE THREAD

**Issue by shapkarin** [mdn/yari#4436]
it looks like `EmbedLiveSample` does not works well with slugs in other than `en` language. I guess it's the general problem with `EmbedLiveSample`. I got that at issue https://github.com/mdn/translated-content/issues/1985, found the same issues at other languages and there is a lot of the same can be found [at PRs](https://github.com/mdn/translated-content/pulls?q=is%3Apr+live+). And I that it's the problem with `macro EmbedLiveSample` because saw a lot of other pages with the same problems and also tried that:

Steps to reproduce:
1. Try to change live-sample ID argument at `EmbedLiveSample` call [`{{EmbedLiveSample('A_table_of_contents', 500, 300)}}`](https://github.com/mdn/translated-content/blob/ffaee541ee5d5cda6bcc3fddf100ee04eaf90852/files/ru/web/css/_colon_target/index.html#L74) to the value that title's `id` has [`Таблица_контента`](https://github.com/mdn/translated-content/blob/ffaee541ee5d5cda6bcc3fddf100ee04eaf90852/files/ru/web/css/_colon_target/index.html#L32)

like:
```vue
<div>{{EmbedLiveSample('Таблица_контента', 500, 300)}}</div>
```

But I got the error 
```
Error: No live-sample "%d0%a2%d0%b0%d0%b1%d0%bb%d0%b8%d1%86%d0%b0_%d0%ba%d0%be%d0%bd%d1%82%d0%b5%d0%bd%d1%82%d0%b0" found within /ru/docs/web/css/:target
```

As I can see macro [EmbedLiveSample](https://github.com/mdn/yari/blob/main/kumascript/macros/EmbedLiveSample.ejs) or [live-sample.js](https://github.com/mdn/yari/blob/main/kumascript/src/live-sample.js) does not works with translated ids and slugs.

**Comment by wbamberg** [comment]
Please see also https://github.com/mdn/yari/pull/3973 which (we hope) will make live samples work more easily with translated content.

**Comment by shapkarin** [comment]
@wbamberg thanks. Added review suggestion to the #3973 
Not sure that #4437 cover all languages, but will test a couple a bit later

**Comment by shapkarin** [comment]
@wbamberg thanks. they add it as part of PR #3973
