### ISSUE TITLE
h2m occasionally mangles `<dl>` conversion

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#4445]
This doesn't happen often. In fact I have only found one case so far in the CSS docs, but there may be more.

See the `<dl>` in https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape#shape_functions. Its markup is like:

```html
<dl>
 <dt><code>{{cssxref("basic-shape/inset()","inset()")}}</code></dt>
 <dd>
 <p>Defines an inset rectangle.</p>
 <pre class="brush: css">inset( &lt;shape-arg&gt;{1,4} [round &lt;border-radius&gt;]? )</pre>

 <p>When all of the first four arguments are supplied they represent the top, right, bottom and left offsets from the reference box inward that define the positions of the edges of the inset rectangle. These arguments follow the syntax of the margin shorthand, that let you set all four insets with one, two or four values.</p>

 <p>The optional <a href="/en-US/docs/Web/CSS/border-radius"><code>&lt;border-radius&gt;</code></a> argument(s) define rounded corners for the inset rectangle using the border-radius shorthand syntax.</p>

 <p>A pair of insets in either dimension that add up to more than the used dimension (such as left and right insets of 75% apiece) define a shape enclosing no area. For this specification, this results in an empty float area.</p>
 </dd>
...
</dl>
```

...which is rendered like:

<img width="788" alt="Screen Shot 2021-08-09 at 10 44 42 AM" src="https://user-images.githubusercontent.com/432915/128750205-1fcf7964-7bbd-4565-b662-72f7a1be00ba.png">

h2m converts this into:

```

- `{{cssxref("basic-shape/inset()","inset()")}}`

  - : Defines an inset rectangle.

    ```css
        inset( <shape-arg>{1,4} [round <border-radius>]? )
        ```

    When all of the first four arguments are supplied they represent the top, right, bottom and left offsets from the reference box inward that define the positions of the edges of the inset rectangle. These arguments follow the syntax of the margin shorthand, that let you set all four insets with one, two or four values.

    The optional [`<border-radius>`](/en-US/docs/Web/CSS/border-radius) argument(s) define rounded corners for the inset rectangle using the border-radius shorthand syntax.

    A pair of insets in either dimension that add up to more than the used dimension (such as left and right insets of 75% apiece) define a shape enclosing no area. For this specification, this results in an empty float area.
```

...which gets rendered like:

<img width="818" alt="Screen Shot 2021-08-09 at 10 44 30 AM" src="https://user-images.githubusercontent.com/432915/128750229-5bf280ce-57a8-4ab7-883b-60700c7521f0.png">

I think the issue is the extra indentation of the code block contents and especially the second code fence. If I change it like:

```
- `{{cssxref("basic-shape/inset()","inset()")}}`

  - : Defines an inset rectangle.

    ```css
    inset( <shape-arg>{1,4} [round <border-radius>]? )
    ```

    When all of the first four arguments are supplied they represent the top, right, bottom and left offsets from the reference box inward that define the positions of the edges of the inset rectangle. These arguments follow the syntax of the margin shorthand, that let you set all four insets with one, two or four values.

    The optional [`<border-radius>`](/en-US/docs/Web/CSS/border-radius) argument(s) define rounded corners for the inset rectangle using the border-radius shorthand syntax.

    A pair of insets in either dimension that add up to more than the used dimension (such as left and right insets of 75% apiece) define a shape enclosing no area. For this specification, this results in an empty float area.
```

...then it works fine.

**Comment by wbamberg** [comment]
Update! I've now found 3 cases in the CSS docs:

* https://developer.mozilla.org/en-US/docs/Web/CSS/basic-shape#shape_functions
* https://developer.mozilla.org/en-US/docs/Web/CSS/url()#values
* https://developer.mozilla.org/en-US/docs/Web/CSS/@counter-style#descriptors

**Comment by fiji-flo** [comment]
It's again a prettier issue 😔

I'll try to fix it.

**Comment by fiji-flo** [comment]
It's an us issue. We added `´ in front of any code block and that screwed things up.
