### ISSUE TITLE
Ready pages for next phase of market research

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#4480]
- [x] banner on https://developer.allizom.org/en-US/plus/deep-dives/planning-for-browser-support uses Arial but should use Inter
- [x] author Twitter handle should be `14px` on plus/deep-dives
- [x] about content should be `MDN Plus / Body / S` on `plus/deep-dives`
- [x] "in this series" needs letter spacing of `1.5px` on `plus/deep-dives`
- [x] copy for series items should be `MDN Plus / Title Card / Regular` on `plus/deep-dives`
- [x] "see contents" should be 14px Inter on `plus/deep-dives`
- [x] ensure all TOC list items is Inter and 14px
- [x] TOC should expand full container width when expanded on `plus/deep-dives`
- [x] "show more" should read "see more"
- [x] Other than the top-level heading in the survey, the other headings should be `18px`

**Comment by schalkneethling** [comment]
@dalexsy Can we reword:

"Find below the first article of the 'Modern CSS in the Real World' deep-dive. Use the one minute long survey to let us know what you think."

to:

"Find below one of the articles that form part of the 'Modern CSS in the Real World' deep-dive series. Use the one-minute-long survey to let us know what you think."

Because of the place in the code we add this, it is not simple to know whether we are on the first or the second. So, this simplifies it.

**Comment by dalexsy** [comment]
> 
> 
> @dalexsy Can we reword:
> 
> "Find below the first article of the 'Modern CSS in the Real World' deep-dive. Use the one minute long survey to let us know what you think."
> 
> to:
> 
> "Find below one of the articles that form part of the 'Modern CSS in the Real World' deep-dive series. Use the one-minute-long survey to let us know what you think."
> 
> Because of the place in the code we add this, it is not simple to know whether we are on the first or the second. So, this simplifies it.

How complicated would it be to make it unique to each one of the articles?

**Comment by dalexsy** [comment]
Could you change the background on the overview hero to `background: linear-gradient(0deg, #FFF 13%, rgba(255, 255, 255, 0.41) 25.05%, rgba(255, 255, 255, 0) 29.17%), transparent url(/static/media/deep-dive-hero.09268174.svg) 50% no-repeat;`
![image](https://user-images.githubusercontent.com/44966503/129577417-871472cf-dd6e-44ee-a830-bafa3b5bcb44.png) so we get a bit of a fade?

**Comment by dalexsy** [comment]
Do you have an idea why the text looks so jagged in Firefox? 
Chromium 
![image](https://user-images.githubusercontent.com/44966503/129595131-c9cefd74-132b-4a23-b3e1-b69dfce9b78c.png)

Firefox 
![image](https://user-images.githubusercontent.com/44966503/129595376-0ce75c00-d087-4e7b-90f6-3fc8f36bbb05.png)

Chromium 
![image](https://user-images.githubusercontent.com/44966503/129595890-5689e81a-5588-4334-8e18-d2dcb5239686.png)

Firefox
![image](https://user-images.githubusercontent.com/44966503/129595933-fc63ed30-5340-42d3-b38a-0796e8467fb8.png)

**Comment by schalkneethling** [comment]
> Do you have an idea why the text looks so jagged in Firefox?

No idea, unfortunately.
