### ISSUE TITLE
Launch market research v3

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#4494]
- [x] All page layout updates done
- [x] campaign origin being recorded via survey
- [x] launched

**Comment by bensternthal** [comment]
Reviewed everything I could, note I was not in the earlier conversations so I am basing this just on figma and what is in Trello. The only minor thing i found is below. Nice work on all the other changes. 

- [ ] Please change text "see more" to "Read more"

**Comment by schalkneethling** [comment]
\o/
