### ISSUE TITLE
Automatically add labels to issue when they are raised from MDN

### ISSUE THREAD

**Issue by Rumyra** [mdn/yari#4496]
When issues are raised via the 'Report a problem with this content' link on MDN, we have information about where the issue is coming from, plus it's a new issue.

Labels should be:
* Which area of content is applicable, such as `Content: CSS` - this can be derived from the URL, even if it's not a perfect science it's a good start for issue triagers
* `needs-triage` label - currently we are adding these manually so issue triagers can seach via this label, automatically adding this would save this work

**Comment by peterbe** [comment]
Doesn't it already do that? This is what I see after having clicked that "Report a problem with this content" link. 
<img width="1255" alt="Screen Shot 2021-08-17 at 2 45 15 PM" src="https://user-images.githubusercontent.com/26739/129783065-2ac6c527-a567-41d9-8705-d83ed77c4cc8.png">

**Comment by Rumyra** [comment]
So looking into this it would be good to check through what's being added, some issues are coming through with no labels - maybe this is 'check auto issue labelling'

**Comment by schalkneethling** [comment]
As we have `needs-triage` automatically added, we are good here for now.
