### ISSUE TITLE
Purge empty divs from main content?

### ISSUE THREAD

**Issue by tannerdolby** [mdn/yari#4527]
I noticed some empty `<div></div>` tags in the `<main id="content">`, should we write a bit of Cheerio to remove these from the `doc` at buildtime? Or do they serve a purpose somewhere down the line for interactivity (ie injecting content into the empty divs upon some event or something) ?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes 

<img width="557" alt="Screen Shot 2021-08-19 at 9 05 15 PM" src="https://user-images.githubusercontent.com/48612525/130177627-ce814d3d-f25c-4788-9b22-f9e1f7c522ed.png">

cc @schalkneethling

**Comment by schalkneethling** [comment]
@tannerdolby That is a good question. I wonder if perhaps we should live with these for now and see how this plays out as more and more of the content is moved to Markdown?

**Comment by peterbe** [comment]
There are no empty divs in the raw content. Open files/en-us/web/javascript/reference/classes/index.md and see. 
It looks like this:

```markdown
If you're experimenting with code in a web browser, such as the Firefox Web Console (**Tools** > **Web Developer** > **Web Console**) and you 'Run' a definition of a class with the same name twice, you'll get a `$

## Specifications

{{Specifications}}

## Browser compatibility

{{Compat}}

## See also

- {{jsxref("Functions", "Functions", "", "true")}}
- {{jsxref("Statements/class", "class declaration", "", "true")}}
- {{jsxref("Operators/class", "class expression", "", "true")}}
```

but if you look at the [HTML output](view-source:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) you'll find:

```html
<h2 id="specifications"><a href="#specifications" title="Permalink to Specifications">Specifications</a></h2>
<table class="standard-table"><thead><tr><th scope="col">Specification</th></tr></thead>
<tbody><tr><td><a href="https://tc39.es/ecma262/multipage/ecmascript-language-functions-and-classes.html#sec-class-definitions">ECMAScript Language Specification<!-- --> <!-- -->(ECMAScript)<br><small># <!-- -->sec-class-definitions</small></a></td></tr></tbody></table>

<div></div>

<h2 id="browser_compatibility"><a href="#browser_compatibility" title="Permalink to Browser compatibility">Browser compatibility</a></h2><p>BCD tables only load in the browser</p>

<div></div>

<h2 id="see_also"><a href="#see_also" title="Permalink to See also">See also</a></h2><div><ul>
  <li><a href="/en-US/docs/Web/JavaScript/Reference/Functions">Functions</a></li>
  <li><a href="/en-US/docs/Web/JavaScript/Reference/Statements/class">class declaration</a></li>
  <li><a href="/en-US/docs/Web/JavaScript/Reference/Operators/class">class expression</a></li>
```

**Comment by peterbe** [comment]
*Something* not nice is going on with the `document-extractor`. It's creating sections that of type `prose` with `""` content.
<img width="894" alt="Screen Shot 2021-08-20 at 7 47 30 AM" src="https://user-images.githubusercontent.com/26739/130228609-e7b516fb-bb13-4eee-8ced-3d4631b69369.png">
