### ISSUE TITLE
Subsequent searches ignore first term

### ISSUE THREAD

**Issue by Ryuno-Ki** [mdn/yari#4534]
Yesterday I noticed, that when I enter a search term into the form, then refine my term (because I had not the results I expected), the autosuggestion seemingly ignores the already entered term and only looks for the newly entered characters.

I can't recall the exact search terms (but will leave a comment here once I remember).

## Steps to reproduce

1. Enter request and hit enter
2. Enter animation after request

## Expected behaviour

Suggestions for requestAnimationFrame

## Actual behaviour

Suggestions for CSS animations.

## Additional information

I remember that when I cleared the search input and entered both terms the suggestion list was different (closer to what I was looking for).

**Comment by peterbe** [comment]
Unable to reproduce. 
https://user-images.githubusercontent.com/26739/130295279-26e85a0e-0c70-4442-ad96-22c3a1a9d828.mov

**Comment by Ryuno-Ki** [comment]
As I mentioned, that wasn't the exact term I used.

Let me dig into my [Nostalgia](https://github.com/nostalgia-dev/timeline) …

**Comment by Ryuno-Ki** [comment]
Got it!

`midnight` => `midnight blue` yields Bluetooth results instead of [`midnightblue` CSS color keyword](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#color_keywords)

**Comment by caugner** [comment]
Cannot reproduce.
