### ISSUE TITLE
Live Code not showing in "Test Your Skills" section for tutorials about Introduction to HTML

### ISSUE THREAD

**Issue by ghost** [mdn/yari#4539]
![Screen Shot 2021-08-22 at 10 52 40 PM](https://user-images.githubusercontent.com/88672980/130362548-8dde2587-9a12-47fd-941e-dbe2f41d7061.png)
In the screenshot you can see the Live Code section is just a blank.

**Comment by bensternthal** [comment]
Testing this morning I can not reproduce (see below). If this is still happening can you add a bit more information to help us track this down. A couple things that can help:

- What is the URL?
- What browser/version are you using?
- Plugins (anything that might block content or scripts)
- Any errors in your browser console?

Thanks!
<img width="935" alt="Screen Shot 2021-08-23 at 7 41 24 AM" src="https://user-images.githubusercontent.com/198507/130467268-73d327a4-f2bd-40b5-a3d3-4b9fbbc17486.png">

**Comment by schalkneethling** [comment]
I can confirm that this works now.
