### ISSUE TITLE
click `change language` always need scroll to page bottom

### ISSUE THREAD

**Issue by Zuckjet** [mdn/yari#4541]
![image](https://user-images.githubusercontent.com/17976139/130380011-9bafb44b-dfdf-4803-9c20-11b015e09610.png)

When I click the top right `change language`, the page always scrolls to the bottom, I think it is not a good user experience

**Comment by schalkneethling** [comment]
Thank you for reporting @Zuckjet! This has changed significantly with the redesign so, this is no longer a problem.
