### ISSUE TITLE
h2m tool sometimes mangles `code` conversions

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#4550]
See https://github.com/mdn/content/pull/8194 for details.

**Comment by escattone** [comment]
cc @fiji-flo

**Comment by fiji-flo** [comment]
```html
<code><strong>font</strong></code><strong><code>-src</code></strong>
```

That's the HTML version. Looks like that cannot be converted to markdown without intervention

```md
**`font`****`-src`**
```
is rendered like this:
**`font`****`-src`**

@wbamberg can we just fix this in HTML:

```sh
rg -F "</strong></code><strong><code>"
```
tells me there's many more.

**Comment by wbamberg** [comment]
Thanks Florian!

>     <code><strong>font</strong></code><strong><code>-src</code></strong>

wild.

> @wbamberg can we just fix this in HTML:

Yeah, I'd be happy to.

> tells me there's many more.

I count 122 in Web/API, a mere drop in the bucket :).

**Comment by teoli2003** [comment]
/me gets ready for reviewing the incoming PRs. 🤣
