### ISSUE TITLE
[documentation] Unlisted setup dependency for ubuntu users

### ISSUE THREAD

**Issue by binyamin** [mdn/yari#4566]
For the `yarn install` step, I had to install the "autoreconf"package with `sudo apt-get install autoconf`.

I tried running this in a docker image of Ubuntu 21.04. Here's the output.
```console
root@15ceeaf6e5b2:~/foo/yari# yarn install
yarn install v1.22.11
[1/5] Validating package.json...
[2/5] Resolving packages...

# skipping irrelevant lines...

error /root/foo/yari/node_modules/gifsicle: Command failed.
Exit code: 1
Command: node lib/install.js
Arguments: 
Directory: /root/foo/yari/node_modules/gifsicle
Output:
⚠ Response code 404 (Not Found)
  ⚠ gifsicle pre-build test failed
  ℹ compiling from source
  ✖ Error: Command failed: /bin/sh -c autoreconf -ivf
/bin/sh: 1: autoreconf: not found
```

**Comment by schalkneethling** [comment]
> @schalkneethling Not sure what the "idle" label means. It feels like a warning that the bot might auto-close the issue. If there was no reaction to an issue, should that really reflect back on the author?

It is in indication to us that the issue has been open for a long time and we need to make a call on how to proceed. It is definitely not a reflection on the author and will not be auto-closed. Thank you for bringing this up @binyamin

**Comment by saleh5yu** [comment]
123sal

في السبت، ٢٨ مايو ٢٠٢٢ ١٤:٥٢ github-actions[bot] ***@***.***>
كتب:

**Comment by binyamin** [comment]
@schalkneethling FYI, this is no longer an issue. Not sure if anything was done.

**Comment by schalkneethling** [comment]
> @schalkneethling FYI, this is no longer an issue. Not sure if anything was done.

Great! Thank you for letting us know.
