### ISSUE TITLE
Improved a11y for header permalinks

### ISSUE THREAD

**Issue by binyamin** [mdn/yari#4567]
After seeing #4554, I did some research on accessible header permalinks. https://github.com/w3c/respec/issues/425 dealt with a similar case, so I'm using their markup for comparison.

Basically, MDN's permalinks have the "title" attribute, which sounds repetitive when using a screen reader. So, it might be smart to remove it. That's really it.

---
Just for fun, I tested an h2 element from both site, and recorded the results below.

<details>
<summary>On MDN</summary>

([link to page](https://developer.mozilla.org/en-US/docs/Web/JavaScript#tutorials))

The screen reader (NVDA) reads "Tutorials  visited link    Permalink to Tutorials  heading    level 2". (Note: without the `title` attribute, NVDA reads "Tutorials visited link heading level 2")
```html
<h2 id="tutorials">
    <a href="#tutorials" title="Permalink to Tutorials">Tutorials</a>
</h2>
```
</details>
<details>
<summary>On w3.org</summary>

([link to page](https://www.w3.org/TR/css-syntax-3/#intro))

The screen reader (NVDA) reads "heading level 2 visited link"
```html
<h2 class="heading settled" data-level="1" id="intro">
    <span class="secno">1. </span>
    <span class="content"> Introduction</span>
    <a class="self-link" href="#intro">
        <!-- A section character (§) is displayed via css -->
    </a>
</h2>
```
</details>

**Comment by caugner** [comment]
After talking with a11y folks internally, we will ...

1. definitely remove that `title` attribute (PR welcome!), and
2. probably proceed with moving the "permalink" (also known as anchor link or deep-link) next to the heading (like GitHub already does it).
