### ISSUE TITLE
Can't add MDN search engine to Firefox search engine list

### ISSUE THREAD

**Issue by Neluji** [mdn/yari#4573]
Everything is in the title. The little + sign next to the magnifying glass (![image](https://user-images.githubusercontent.com/38362829/131099893-846dd1b3-6760-4704-a566-e7c63c98b770.png)) in the search bar is not present, nor the add option in the search menu (![image](https://user-images.githubusercontent.com/38362829/131100145-6f1cb9b4-232c-449d-b9a8-9f7ccd696aa1.png) for example), as it should be for search engines that have not yet been added.
<br>
![image](https://user-images.githubusercontent.com/38362829/131104422-baa73816-85ef-4e12-87c5-9355e5816760.png)
<br>
I am running Firefox Normal Edition version 91.0.2 (64 bits) on Windows 10, and have experienced the same issue on Ubuntu 20.04.

**Comment by loganrosen** [comment]
This looks to be a duplicate of #3991.

**Comment by Neluji** [comment]
Hmm yeah indeed

**Comment by Neluji** [comment]
Duplicate of #3991
