### ISSUE TITLE
border-image slicing differences between mobile/desktop

### ISSUE THREAD

**Issue by lschult2** [mdn/yari#4580]
I'm seeing some significant differences in how mobile and desktop Firefox are repeating sliced border images. It's easily demonstrated on https://developer.mozilla.org/en-US/docs/Web/CSS/border-image-slice

MacOS 10.14.6 Firefox 91.0.1 
![image](https://user-images.githubusercontent.com/52585096/131259691-fdc164b4-479a-4c2e-a485-d940f58ed7ce.png)

iOS 14.6 Firefox 
![image](https://user-images.githubusercontent.com/52585096/131259702-0a3546fe-2ec9-4197-8a81-b888f4283dbc.png)

Why do these behave differently? How can I get the un-stretched results in iOS that MacOS Firefox has?

**Comment by gumbol** [comment]
hi
navigate to that page then on the browser click the icon on the top right to display the tools list.
look for (desktop site) option and click that.

**Comment by escattone** [comment]
@lschult2 Yes, that's right. This repo is for MDN the website (https://developer.mozilla.org) but has nothing to do with Firefox the browser (either the desktop or mobile versions). If you'd like to report an issue with Firefox, [this page](https://support.mozilla.org/en-US/kb/file-bug-report-or-feature-request-mozilla) will help guide you.
