### ISSUE TITLE
Wrong value in Node.nodeType

### ISSUE THREAD

**Issue by KelvinPaul** [mdn/yari#4582]
https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType

*The following constants have been deprecated and are not in use anymore: code>Node.ENTITY_REFERENCE_NODE (5), Node.ENTITY_REFERENCE_NODE (6), and Node.NOTATION_NODE (12).*

this paragraph contain a wrong information, Node.ENTITY_REFERENCE_NODE is appeared twice, 

according to 
```for (let x in Node) console.log(x, Node[x])```
code execution, value 6 belongs to Node.ENTITY_NODE.

**Comment by teoli2003** [comment]
Thanks, I opened a PR to fix it.
