### ISSUE TITLE
many links have a strange symbols

### ISSUE THREAD

**Issue by Nortyboy1983** [mdn/yari#4602]
many buttons display a weird block in place to mention what that feature is for but often photos, especially on facebook are not displayed at all. I think it is a java problem but your tips on this are not working. For Facebook use the facebook extension. Furthermore I use Ublock. 
Can you see something wrong with my Firefox? I have already regularly reset everything but that is not the solution either
In the picture you see 2 smal blocks with the letters E5C4
![2021-09-01](https://user-images.githubusercontent.com/48383297/131715996-cf4e6a48-ae41-4574-8168-af000d9dd780.png)
and in the other E5D4. This on a googlesite but nearly all sites have this thing so i don't know what dat button means

Translated with www.DeepL.com/Translator (free version)
![2021-09-01](https://user-images.githubusercontent.com/48383297/131715613-622ef8a7-b798-4e74-ae75-6d8cca67ec54.png)

**Comment by bensternthal** [comment]
This is a repository for MDN (developer.mozilla.org), not a forum for general questions about Firefox. I would suggest support.mozilla.org as a better place for you to ask this type of question.
