### ISSUE TITLE
Demo Iframes 404ing 

### ISSUE THREAD

**Issue by MaxBittker** [mdn/yari#4606]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range

^ cannot view any of the demos on this page, for instance this url:
`https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range`

**Comment by escattone** [comment]
I just fixed this (see https://github.com/mdn/yari/pull/4613). Thanks for reporting this @MaxBittker!

**Comment by MaxBittker** [comment]
thank you so much! I am using this this page in a class this week and I'm super happy to see it fixed! <3 @escattone
