### ISSUE TITLE
Markdown converter - support pre brush types: python, sql

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#4608]
I get an error during markdown conversion pre blocks with Python: `<pre class="brush: python">` and with `"brush: sql"`
Can we convert this to three backticks and python (or sql, as the case may be)

**Comment by hamishwillee** [comment]
@escattone Any chance this could be looked at - I am assuming it might be an easy change, and it would save me a lot of time in conversion.

**Comment by escattone** [comment]
@hamishwillee For sure! I do believe `python` is supported as of 8 hours ago due to @wbamberg's #4599, but I just submitted https://github.com/mdn/yari/pull/4646 to support `sql` as well. I'll merge that tomorrow!

**Comment by escattone** [comment]
@hamishwillee I just merged #4646 so you're good to go!
