### ISSUE TITLE
Issue with "perspective": live sample iframe blocked

### ISSUE THREAD

**Issue by sinafath** [mdn/yari#4614]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/perspective

#### Specific section or headline?
Examples

#### What did you expect to see?

cant see the result I see an error "yari-demos.prod.mdn.mozit.cloud refused to connect."

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/perspective`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/perspective
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/perspective/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by escattone** [comment]
This has been fixed, thanks everyone.

**Comment by teoli2003** [comment]
Thanks a lot, @escattone.
