### ISSUE TITLE
Clicking search suggestion on 404 page yields another 404

### ISSUE THREAD

**Issue by loganrosen** [mdn/yari#4615]
STR:

1. Go to a page that 404s (e.g. https://developer.mozilla.org/en-US/Using_native_JSON).
2. Type in a search query in the top right.
3. Click on one of the suggested results that pops up.

Actual:
You get another 404 page for the article linked from the suggested result (but it works if you refresh).

Expected:
You see the article that was suggested.

**Comment by escattone** [comment]
Confirmed. Thanks for reporting @loganrosen!

**Comment by schalkneethling** [comment]
I can still reproduce this.

https://user-images.githubusercontent.com/10350960/163579960-f132f419-6fa2-43f7-86aa-d7276883708a.mov
