### ISSUE TITLE
Problemas com interface

### ISSUE THREAD

**Issue by gvlf147** [mdn/yari#4633]
Comecei a utilizar a SpeechSyntesis a pouco tempo, a ferramenta é incrível, funciona perfeitamente para a leitura de tela na versão do desktop, porem, no celular somente alguns conteúdos são lidos, outros não, com alguns testes que fiz em minha aplicação é como se ele não conseguisse ler determinadas palavras, palavras essas sem ligações nenhuma uma com a outra, erro esse também que não acontece na versão desktop.

**Comment by escattone** [comment]
@gvlf147 This repo is only for MDN Web Docs, and I think you're talking about Firefox?
