### ISSUE TITLE
Italic inside bold is not converted correctly from HTML to MD 

### ISSUE THREAD

**Issue by lex111** [mdn/yari#4648]
It seems that the HTML to MD converter does not correctly convert italic (`em`) text if it is inside bold (`strong`).

Put following paragraph in any page and try convert this:

```
<p>Note that <code>foo !== bar</code>. While they are similar objects, <em>they are not <strong>the same object</strong></em>.</p>
```

<p>Note that <code>foo !== bar</code>. While they are similar objects, <em>they are not <strong>the same object</strong></em>.</p>

* * *

Expected result:

```
Note that `foo !== bar`. While they are similar objects, *they are not **the same object***.
```

Note that `foo !== bar`. While they are similar objects, *they are not **the same object***.

* * *

Actual result (_`*` chars  is erroneously escaped_):

```
Note that `foo !== bar`. While they are similar objects, \*they are not **the same object\***.
```

Note that `foo !== bar`. While they are similar objects, \*they are not **the same object\***.

**Comment by teoli2003** [comment]
I think we can manually check pages with "\***" (or even with "***" when we convert. I did a rg on triple stars and found no other occurrence than the one you fixed.

**Comment by schalkneethling** [comment]
@lex111 @teoli2003 Seeing that there was only one instance, and that one was addressed, does it make sense to keep this open, or can we close?

**Comment by ddbeck** [comment]
Closing this, since it seems resolved and nearly all content has been converted already. Thanks for flagging this!
