### ISSUE TITLE
README.md and signed PRs

### ISSUE THREAD

**Issue by rebloor** [mdn/yari#4653]
The readme file doesn't mention that PR submitted to Yari need to be signed. Also, while this process is documented on GitHub (obtaining and using a GPG key) it might also be worth providing an overview and links.

**Comment by schalkneethling** [comment]
@fiji-flo What do you think, do we want to keep making this a requirement? I know Peter and myself have talked about this and thought that perhaps it is not worth enforcing this. If we want to, then I agree we should document it in the contribution docs.

**Comment by fiji-flo** [comment]
I personally do think signed commits are valuable and we should _just_ add it to the readme.
