### ISSUE TITLE
Make language switching easier

### ISSUE THREAD

**Issue by lex111** [mdn/yari#4657]
Currently, it takes four clicks to change language:
1. Click on link "Change language" at the top of page, which will take you to the end of this page where language select box is placed
2. Click on select box with languages list
3. Click by desired language
4. Finally, click on the button "Change language".

But this is complicated and inconvenient, why not relocate `<select>` element to the top of page as shown below?

![image](https://user-images.githubusercontent.com/4408379/132948381-11912c38-67f8-4383-82bd-88c3514fcdc9.png)

Then user need to make only two clicks to select language. Immediately after selecting language we will re-render page with  selected language. It's a more obvious, handy and UX-friendly way to select/switch language. For example PHP docs uses such design:

![image](https://user-images.githubusercontent.com/4408379/132948515-ae1f7c81-8481-48fc-9b0c-421f1572930c.png)

**Comment by schalkneethling** [comment]
Thank you for the feedback @lex111. We are exploring some options here as part of the redesign and will definitely take this feedback into account.

**Comment by lex111** [comment]
Is it possible to make this change in the current design? It doesn't seem that complicated, so I can help with the implementation of this.

**Comment by schalkneethling** [comment]
> Is it possible to make this change in the current design? It doesn't seem that complicated, so I can help with the implementation of this.

Thank you for the offer @lex111. We are already working on it so, I would not recommend spending additional effort of making changes in the current UI.

**Comment by schalkneethling** [comment]
As mentioned this is changing as part of the redesign so, I am going to close this one. Once the redesign launches, if there is still room for improvement, feel free to reopen or file a new issue. Thank you.
