### ISSUE TITLE
A new world for Chinese l18n

### ISSUE THREAD

**Issue by zhjustice** [mdn/yari#4658]
### Summary
There is no big gap between Traditional and Simplified Chinese. However, as we all know, Traditional Chinese is the real tradition and I agree that we shouldn't create a tool to convert either way. After analyzing, it might be the best to remove simplified Chinese.

### Why
There are now two different branches of MDN zh, zh-cn and zh-tw. The translation results for the same document are roughly the same for both. However, each and every character in zh-tw contains all the strokes in zh-cn. That is very obvious because Traditional Chinese characters is the tradition and the Simplified Chinese characters is simplified!

A Traditional Chinese user can read documents in Simplified Chinese almost without any problems. And vice versa.

The complete segregation of zh-cn and zh-tw translations results in unnecessary duplication of effort. We can avoid the waste of manpower by simply removing the one has less strokes in characters.  

### What needs to be done?

- [ ]  Remove settings files of separated zh languages
- [ ]  Redirect all Chinese to zh-tw pages
- [ ]  Focus more in zh-tw so the contents can match

**Comment by escattone** [comment]
@zhjustice This has been discussed before (see https://github.com/mdn/yari/issues/4530), and both communities have strong feelings for wanting to keep their own translation. We will continue to support both translations (`zh-CN` and `zh-TW`).
