### ISSUE TITLE
Broken macro links rendered as macro text on local Windows build

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#4670]
Any Xref or glossary link where the target does not exist is now showing up as the macro text on Windows local preview. For example, here is a link to a glossary entry that does not exists.
![image](https://user-images.githubusercontent.com/5368500/133176923-af7023f7-18f1-4869-8d8e-f73fb0b64563.png)

This has been happening for a couple of weeks. Prior to that the links rendered as broken links.

**Comment by schalkneethling** [comment]
> Any Xref or glossary link where the target does not exist is now showing up as the macro text on Windows local preview. For example, here is a link to a glossary entry that does not exists. ![image](https://user-images.githubusercontent.com/5368500/133176923-af7023f7-18f1-4869-8d8e-f73fb0b64563.png)
> 
> This has been happening for a couple of weeks. Prior to that the links rendered as broken links.

Hey @hamishwillee, just wanted to double-check that this is still a problem on Windows? Thank you.

**Comment by hamishwillee** [comment]
@schalkneethling Yes it is. Happy new year!

**Comment by schalkneethling** [comment]
Hey @hamishwillee, when you have a moment, could you perhaps add steps to reproduce this? Essentially the build commands you run and a page that shows this output. Thanks so much.

**Comment by hamishwillee** [comment]
@schalkneethling Of course. I do nothing special. I'm on Windows 10. Currently running node v12.22.0, yarn 1.22.5.
I have a github clone of mdn/content.
I do `yarn` in root to update dependencies and `yarn start` to run it:
```
D:\github\mozilla\mdn_content\content>yarn start
yarn run v1.22.5
$ yarn up-to-date-check && env-cmd --silent cross-env CONTENT_ROOT=files REACT_APP_DISABLE_AUTH=true BUILD_OUT_ROOT=build node node_modules/@mdn/yari/server
$ node scripts/up-to-date-check.js
[HPM] Proxy created: /  -> https://developer.mozilla.org
CONTENT_ROOT: D:\github\mozilla\mdn_content\content\files
Listening on port 5000
Your EDITOR is set to: code
buildDocumentFromURL(/en-us/docs/mdn/structures/macros/commonly-used_macros): 529.898ms
buildDocumentFromURL(/en-us/docs/mdn/structures/macros/commonly-used_macros): 157.907ms
...
```
Looking at http://localhost:5000/en-US/docs/Web/API/Window I see both linked and missing topics as shown

![image](https://user-images.githubusercontent.com/5368500/149026349-64754f0c-afcd-4b3b-adac-3877b075e60a.png)

**Comment by schalkneethling** [comment]
Thanks so much @hamishwillee, this will help a lot!

**Comment by caugner** [comment]
@hamishwillee Sorry to have to repeat Schalk's question. Is this still an issue?

Whenever a macro call is displayed as is, this means that an Error was thrown inside the macro call. In the case of the `DOMxRef` macro, really the only thing that can crash is the `web.smartLink()` call:

https://github.com/mdn/yari/blob/50b8148395b9bdf82f86ef1c4e5cd2044f5b096a/kumascript/macros/DOMxRef.ejs#L51

Looking at the `smartLink()` implementation, I'm not sure what might cause an error specifically on Windows.

But in general, we should be surfacing macro errors at least on the command line, if not (for writers and developers) also on the page directly. 🤔

**Comment by caugner** [comment]
(@hamishwillee Once https://github.com/mdn/yari/pull/7619 has landed in mdn/content, you'll get a proper error message in the console provided that the DOMxRef macro still fails on Windows.)

**Comment by hamishwillee** [comment]
@caugner Good news is that I'm no longer getting those errors on Windows. I couldn't tell you when it was fixed. Feel free to close - and thanks!

**Comment by caugner** [comment]
Great news, thanks for letting me know, @hamishwillee. 🙏
