### ISSUE TITLE
BCD multiple notes incorrectly formatted

### ISSUE THREAD

**Issue by rebloor** [mdn/yari#4757]
When a feature has multiple notes against a release they are wrapped rather than presented in a columns. e.g. for https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/read
 
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/7352080/135890291-18a0ee2e-2492-4f96-a97d-2a1003b92e66.png">

however the presentation should be more like
 
<img width="1294" alt="image" src="https://user-images.githubusercontent.com/7352080/135891325-04850b2c-46b4-4e78-8a12-0ebb694ba39b.png">

**Comment by schalkneethling** [comment]
It feels like if we remove the `flex` from the `dd` element it will be much better.

![Screenshot of bcd table with flex removed from dd elements showing the content all stacked as paragraphs](https://user-images.githubusercontent.com/10350960/147827757-325377aa-2211-4079-91f3-a180f80cd03c.png)

With that said, this might all change as part of the redesign so, I am going to close this one for now with this comment. Should the problem persist after the redesign, please feel free to reopen this issue. Thank you for filing @rebloor

**Comment by rebloor** [comment]
@schalkneethling As you seem uncertain whether this would be fixed by the redesign, wouldn't it make sense to leave this open and somehow flag it as part of the redesigned site testing?

**Comment by schalkneethling** [comment]
> @schalkneethling As you seem uncertain whether this would be fixed by the redesign, wouldn't it make sense to leave this open and somehow flag it as part of the redesigned site testing?

I did bring it to their attention and so, there is an issue raised in their repository.

**Comment by rebloor** [comment]
Thank you @schalkneethling
