### ISSUE TITLE
Improvement: Make links to pages that haven't been translated have a different style

### ISSUE THREAD

**Issue by pVesian** [mdn/yari#4784]
Hello.

It's my first issue here, I hope I wrote it well.
I was browsing through the FR version of the HTTP headers documentation when I found some pages that hadn't been translated. It doesn't bother me, but the process by which I found out does. I thought this could be improved on.

Example:
* Navigate to https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Accept-Charset
* Click on the link to "Accept-CH-Lifetime": https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Accept-CH-Lifetime
* Discover the page isn't translated

Improvement example:
* Navigate to https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Accept-Charset
* Discover the link to "Accept-CH-Lifetime" (and all the ones like it) have different style (an icon next to it, a different color, a title/tooltip, or maybe all 3 combined) to indicate translation to be unavailable.

Advantages
* Less requests from visitors on servers
* Less requests from crawlers if an attribute exists to indicate an inexistent page
* Happy non-english speaking visitors (i18n of semantics not just content)

Disadvantages
* Might require a little computing on the backend

What do you think?

**Comment by escattone** [comment]
@pVesian We have some PR's that I think address this issue you've identified (for example #3030, #3944, #3170, and #3946) -- although maybe not the links in the HTTP doc sidebars. Unfortunately I haven't had time to review them yet, but I'll try to start reviewing them soon.

**Comment by schalkneethling** [comment]
> @pVesian We have some PR's that I think address this issue you've identified (for example #3030, #3944, #3170, and #3946) -- although maybe not the links in the HTTP doc sidebars. Unfortunately I haven't had time to review them yet, but I'll try to start reviewing them soon.

All pull requests mentioned above have now been merged so, closing this issue.
