### ISSUE TITLE
"Page" and "IncludeSubnav" macros introduce render dependencies into builds

### ISSUE THREAD

**Issue by escattone** [mdn/yari#479]
### Summary
The [`page`](https://github.com/mdn/kumascript/blob/master/macros/page.ejs) and [`IncludeSubnav`](https://github.com/mdn/kumascript/blob/master/macros/IncludeSubnav.ejs) macros rely on [the `wiki.page` function](https://github.com/mdn/kumascript/blob/1f4b93faf68095f0b69b2d3d0e9e487793bdc18e/src/api/wiki.js#L29) which basically includes content from one rendered document into another. This introduces dependencies into the Kumascript-rendering process, where the Kumascript rendering of one document depends on the Kumascript-rendered output of another. For example, consider https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role which contains the macro call `{{Page("/en-US/docs/Web/Accessibility/ARIA/Roles", "Subnav")}}`, which when resolved extracts the sidebar from https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles into https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role. This means that in order to KS-render `/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role`, we first need to KS-render `/en-US/docs/Web/Accessibility/ARIA/Roles`. There are about 475 English documents that call the `Page` and/or `IncludeSubnav` macros.

**NOTE: This issue is actively being addressed as part of https://github.com/mdn/kuma/issues/6818.**

### Additional Context
@wbamberg makes the following comment about the `page` macro, which I think is important to consider (see https://github.com/mdn/sprints/issues/2520#issuecomment-564598806):

> >     * page
> 
> **Render**
> 
> This page is used to include content from one page in another page.
> 
> I would like us to render out this macro, in general. I think **ad hoc** transcluding of content is a kind of content antipattern (mostly because the original source of the doc doesn't know where it is included, so it's easy to edit it so it doesn't make sense in the transcluding context). But it is used quite extensively in the JS docs to include instance properties and methods from the corresponding `Foo/prototype` page.
> 
> For example, https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray uses it to include instance properties from https://wiki.developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/prototype.
> 
> I think we should consider whether the JS docs really want to be doing this. If they do, we should find a way to support it.

**Comment by wbamberg** [comment]
We did remove all calls to `{{page}}` from the JS docs (https://github.com/mdn/sprints/issues/2798). Note though that we're no longer working on triaging or de-macroing Wiki docs, since it's not seen as important enough ¯\_(ツ)_/¯.

**Comment by peterbe** [comment]
There are ~1,300 pages that use `{{page(`. 350 of which are en-us. 

Interdependencies are unfortunate, but **would it work at all** to just give in to this and do what it says. I.e. in `processFolder()`, you scan the text (with regex) for `/\{\{\s*page\(/gi` and then go and process those first. And then, inside the "page macro" you can train it to go an open the built `index.html` plus cheerio and stuff. 

Come to think of it, we don't need to do anything to `processFolder()`. It returns enums and the `file` which is the built file. Because the caching that's built into it, it's pretty darn fast if called repeatedly.

**Comment by escattone** [comment]
@peterbe After thinking about this over the weekend and yesterday, I've arrived at what I think is a really good solution to this. I'll have a PR ready for you to review later this week.

**Comment by peterbe** [comment]
So we have a solution for this now. It's working. I don't see a bright future in doing away with it entirely. It's too much responsibility to rewrite the content. For Yari in 2020 and 2021 we need to focus on just getting what we're committed to to work without rewriting the world.
