### ISSUE TITLE
Research: Let’s consider CSS Modules

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#4858]
See https://github.com/mdn/yari/pull/3954 for reference.

**Comment by tannerdolby** [comment]
I'm totally for this! I read through #3954 and it seems migrating to CSS Modules for an easier "CSS in JS" approach would be beneficial going forward.

**Comment by schalkneethling** [comment]
> I'm totally for this! I read through #3954 and it seems migrating to CSS Modules for an easier "CSS in JS" approach would be beneficial going forward.
> 
> Resources:
> 
> * https://github.com/css-modules/css-modules
> * https://css-tricks.com/css-modules-part-1-need/

I am also keen to explore this but, this is currently on the back burner while some other work is completed. Once that is done though, I am definitely going to explore this further.

**Comment by tannerdolby** [comment]
Ok, sounds like a plan @schalkneethling
