### ISSUE TITLE
Styling issue on developer.mozilla.org

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#4929]
Reported on Matrix: https://matrix.to/#/!cGYYDEJwjktUBMSTQT:mozilla.org/$oZfdZgi6_ZE6P1FigcCF0wht5FXmpxeFKsto8xg8Uks?via=mozilla.org&via=matrix.org&via=nordgedanken.dev

...a reader reports that (for example) the https://developer.mozilla.org/en-US/docs/Web/HTML/Element/canvas element looks like: https://matrix-client.matrix.org/_matrix/media/r0/download/mozilla.org/340d937d0fcfcd18ce91ee76b12f00fe6d33879b , and that many other pages look like this too.

**Comment by wbamberg** [comment]
I don't see this, but I am seeing more subtle style problems. For me on many pages it looks like the `margin-bottom` on paragraphs has gone missing:

<img width="1036" alt="Screen Shot 2021-11-10 at 11 14 06 AM" src="https://user-images.githubusercontent.com/432915/141178259-8a1ef5b7-898b-4605-a76e-c7063c4581a8.png">

**Comment by escattone** [comment]
@wbamberg Very strange! I'm not seeing any of this, but that may be because I'm hitting a different edge location of our CDN.

**Comment by Elchi3** [comment]
> For me on many pages it looks like the `margin-bottom` on paragraphs has gone missing:

I see this as well.

**Comment by schalkneethling** [comment]
Fixed in https://github.com/mdn/yari/pull/4930 I believe. Please let me know if that is not the case.
