### ISSUE TITLE
Search results dropdown obscured by footer

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#4949]
If you search on a page such as the `404` page, the title search results drop-down is hidden behind the footer.

![Screenshot showing drop-down menu obscured by the page footer](https://user-images.githubusercontent.com/10350960/141839407-42d71dc6-b29c-4063-85e4-e2ce3b3b3485.png)

This is an easy fix. We simply need to remove the `z-index` from the `footer` here:
https://github.com/mdn/yari/blob/91f9c61a58dce664d2c21bed262d7bea4a20de32/client/src/ui/organisms/footer/index.scss

```scss
.page-footer {
  background-color: $mdn-neutral900;
  color: $text-color-inverted;
  padding: ($base-spacing * 2) $base-spacing;
  position: relative;
  z-index: $bring-to-front; <--
```

**Comment by oneamanish** [comment]
see my pull req.
