### ISSUE TITLE
Label automation from mdn site for new issues not working correctly

### ISSUE THREAD

**Issue by Rumyra** [mdn/yari#4999]
When you 'Report an issue with this page' from MDN, labels are automatically added to the new issue dialogue. These labels are `needs-triage` and a `Content: ...` label based on the url of the reported page.

When the issue is saved however, if the user does not have write permissions for mdn/content, these labels are removed. So new issues appear with no labels.

This is not an urgent problem, but I'm making a note of it here so we understand it. Some notes:

- I created a workflow which adds `needs-triage` which will add after the issue is created, so it's not all bad
- We're reviewing the issue triage process with synced triage meetings which could conclude in a different approach to adding a content label

Suggest we review this problem after a few triage meetings to see if we want the labels to be automated when reporting from MDN's 'Report an issue' link

**Comment by schalkneethling** [comment]
@Rumyra I am kinda thinking we should move this to our content team projects repo. I reckon this is something we can resolve between us. Let me know.

**Comment by Rumyra** [comment]
This _is_ part of implementing an issue triage process - so we can include it in our project. It is however the sort of issue we should have engineering support for I think.

**Comment by schalkneethling** [comment]
@Rumyra I believe this is being addressed in https://github.com/mdn/content/pull/14212

**Comment by Rumyra** [comment]
Yes it is 👍
