### ISSUE TITLE
Low-hanging fruit fixes on bad redirects in dumper

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#500]
When reviewing https://github.com/mdn/stumptown-renderer/pull/499/files I noticed a bunch of things the `repairUri` has to do. Every time. Things that cause unnecessary trouble that could be solved once and for all in the dumper. 

For example, a lot of `_redirects.txt` files look like this:
```
# FROM-URL      TO-URL
/th/docs/en     /
...
```
and that can become:
```
# FROM-URL      TO-URL
/th/docs/en     /en-US/docs/
...
```

Another example is there's 27 uses of a `_` in the locale code in `content/files/zh-tw/_redirects.txt`. It uses `zh_tw` instead of `zh-TW` which is what what's in `VALID_LOCALES`. 

In `content/files/zh-cn/_redirects.txt` there are a lot of these:
```
/zh-CN/docs/AJAX:Getting_Started        /cn/docs/AJAX/Getting_Started
```

Just like we once used to called `en-US` just `en`, I guess at some point we used to call `zh-CN` just `cn`. There's also a lot of redirects to things like `/pt/docs/...` which needs to be replaced with `pt-BR` or `pt-PT` but which one?! Perhaps it can be deduced from the `locale` in the MySQL wiki_document row.

**Comment by peterbe** [comment]
By the way, Sheppy informs me that `pt` later became `pt-PT` when the distinction between the two Portuguese languages was introduced.

**Comment by peterbe** [comment]
Here's what I think we should do:

1. Wait for https://github.com/mdn/stumptown-renderer/pull/499 to land
2. Work on this issue and test it with the `repairUri` function to see how much less it had to do in the builder. 
3. Revisit how `repairUri` is used in the builder, in a new issue, to make it much much stricter so that faulty fatfingered PR builds where people edit the _redirects.txt files break the build before it makes things worse. 

Good plan?

**Comment by escattone** [comment]
@peterbe 👍 good plan!

**Comment by peterbe** [comment]
Actually `https://developer.mozilla.org/th/docs/en` redirects to `/`. Not to `/en-US/`. So how bad is it really to do a 301 to `/` followed by 302 to `/en-US/`. Probably not very bad. 

I'll make sure all those easier locale code redirects are fixed.

**Comment by peterbe** [comment]
Here are some rows in `_redirects.txt` that could be fixed rather easily:
```
/en-US/docs/-moz-locale-dir(rtl)        /En/docs/CSS/:-moz-locale-dir(rtl)
/en-US/docs//nsIPlacesView      /En/docs/NsIPlacesView
/en-US/docs/DOM/en/Window.scrollBy	/%(en/DOM/window.scrollBy)s
```

By the way:
```
▶ cat content/files/en-us/_redirects.txt| rg '/En/' | wc -l
     118
```

Also, what's this?
```
▶ cat content/files/en-us/_redirects.txt| rg '/Trash/' | wc -l
     100
```
Should we add `Trash` to `ARCHIVE_SLUG_ENGLISH_PREFIXES`?

**Comment by peterbe** [comment]
And for `content/files/zh-cn/_redirects.txt` for example:
```
/zh-CN/docs/AJAX:Getting_Started        /cn/docs/AJAX/Getting_Started
```

**Comment by peterbe** [comment]
But what about things like:
```
/zh-CN/docs/About_the_MDC       /Project:cn/docs/%E5%85%B3%E4%BA%8E
```
that shouldn't have been included in the `_redirects.txt` file, right?
