### ISSUE TITLE
(Auto)EmbedLiveSample: whitespace weirdness

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#5006]
See https://github.com/mdn/content/pull/10758. In one of the examples that I converted to use the (Auto)EmbedLiveSample algorithm, it looks like it somehow affected the handling of whitespace. Compare:

https://pr10758.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Global_attributes/itemscope#result
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemscope#html_2

**Comment by OnkarRuikar** [comment]
I am not able to reproduce this issue. I tried using the file contents in https://github.com/mdn/content/pull/10758.

**Comment by wbamberg** [comment]
Yes, this looks like a non-issue.
