### ISSUE TITLE
"Related topics" Navigation overlapping the content

### ISSUE THREAD

**Issue by d11r** [mdn/yari#5008]
![image](https://user-images.githubusercontent.com/17767170/143686226-9210448d-73a9-4e2a-8391-cd7541ce199c.png)

URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all
Browser width: 1240px

**Comment by wbamberg** [comment]
Duplicate of https://github.com/mdn/yari/issues/4973.
