### ISSUE TITLE
Content bug: User Interface of MDN Web Docs while scrolling in menu/search button in Firefox Mobile Browser

### ISSUE THREAD

**Issue by kirkynaj** [mdn/yari#5010]
## What page(s) did you find the problem on?

Opening MDN web docs website on mobile browsers.

## Specific page section or heading?

While accessing the menu/search button there's an UI/CSS unusual behavior 

## What is the problem?

UI or CSS problem that makes it weird or do unusual behavior of the website when scrolling

## What did you expect to see?

Not sure, either close the menu when scrolling or make the whole page gray

## Video 

https://user-images.githubusercontent.com/16712217/143683554-c35d6ddf-7a17-4dcd-931d-1133e7924c5e.mp4

**Comment by schalkneethling** [comment]
@kirkynaj Is this still a problem for you with the redesign?

**Comment by kirkynaj** [comment]
No Sir @schalkneethling, the problem has been resolve after the redesign. Thank you.
