### ISSUE TITLE
Content bug: aside.metadata width (right part) overlapping in desktop mode

### ISSUE THREAD

**Issue by joliveramu** [mdn/yari#5013]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/MDN/contribute

## Specific page section or heading?
aside element (To be specific, aside.metadata)

## What is the problem?
The width is overlapping when used in a desktop mode.

## What did you expect to see?
Same width as div.notecard.note

Make the width be responsive

## Did you test this? If so, how?
Using developer tools and changing the device type

**Comment by AnilSeervi** [comment]
I don't understand what's wrong here. @joliveramu can you explain it a bit.

**Comment by joliveramu** [comment]
Hello, apologies for the latest response.

When I am browsing the page in desktop mode, the aside.metadata's width is overlapping. It covered past the width we have from the div.notecard.note.

**Comment by schalkneethling** [comment]
@joliveramu Looks like this was resolved as part of the redesign. Please feel free to reopen this issue if you still encounter the problem.
