### ISSUE TITLE
Border not changing programmatically

### ISSUE THREAD

**Issue by nickolasnikolic** [mdn/yari#5046]
window.onload = () => {

const div = Array.from(document.getElementsByTagName('div'))[0];

let i = 0;
function changeBorder(element){
    element.style.border = i++ + "px dotted black";
    if(i < 30){
        i = 0;
    }
}

setInterval(changeBorder, 30, div);

};

The previous code doesn't change the border of a div in animated fashion.

Thank you for your work.

**Comment by schalkneethling** [comment]
Hey @nickolasnikolic! Is this related to a specific page on MDN? If not, you will get better support by asking this question on our [Learn forum](https://discourse.mozilla.org/c/mdn/learn/250).
