### ISSUE TITLE
Create a Slider for the left nav Items

### ISSUE THREAD

**Issue by ShivaSaiKanathala** [mdn/yari#5057]
![image](https://user-images.githubusercontent.com/30581953/145596303-5377cccd-d420-40ea-b3fa-5d8e1c0440ed.png)

Please have a slider for the Nav items, so that it becomes easy to switch from one to another.

**Comment by schalkneethling** [comment]
@ShivaSaiKanathala can you expand a bit more on this request? Did the redesign address this at all? Thank you.

**Comment by caugner** [comment]
Closing as idle.
