### ISSUE TITLE
Dark Mode on MDN DOCS 

### ISSUE THREAD

**Issue by HamzaAymen** [mdn/yari#5080]
Dear MDN team ,  programmers write code at day and night , and reading MDN documents at the night can be painful because of that white background , me and my eyes will be glad if you work on **dark mode feature** ..

**Comment by subz390** [comment]
try the Dark Reader brower plugin, works pretty well on MDN docs.

**Comment by davbrito** [comment]
This can be closed now because #5337 solves this.
