### ISSUE TITLE
Firefox sidebar contains links which are redundant

### ISSUE THREAD

**Issue by Rumyra** [mdn/yari#5096]
The Firefox sidebar contains links which have been removed from MDN and thus the links also need to be removed

**Comment by Rumyra** [comment]
Realising this is in kumascript... think we should remove all 'Firefox Internals' & 'Building and Contributing' links and replace with one 'Firefox Documentation' which is here https://firefox-source-docs.mozilla.org/

**Comment by dipikabh** [comment]
Update: Just discussed this issue with Schalk and he suggested he can guide me while I fix this issue. We plan to work on it on March 18.
