### ISSUE TITLE
Issue with "BigInt": Left sidebar blends with text

### ISSUE THREAD

**Issue by PythonCoderAS** [mdn/yari#5105]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

#### What information was incorrect, unhelpful, or incomplete?

The left sidebar clips with the actual text and makes it hard to read.

![image](https://user-images.githubusercontent.com/13932583/147357785-843faaf5-41bc-47cb-84cf-02b0978c06e4.png)

#### Specific section or headline?

Most noticeable near the Operators heading.

#### What did you expect to see?

Sidebar separated by whitespace

#### Did you test this? If so, how?

N/A

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/javascript/reference/global_objects/bigint`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/global_objects/bigint/index.md
* Last commit: https://github.com/mdn/content/commit/05a80e13f9824c8733ed293c5f22e322248096ef
* Document last modified: 2021-12-03T05:27:53.000Z

</details>

**Comment by schalkneethling** [comment]
Hey @PythonCoderAS, @Andrew-Cottrell, and @AnilSeervi. Thank you for raising this issue. It is indeed problematic. This is being addressed as part of the current redesign that is underway. As such, the work is tracked elsewhere. Closing this one to avoid duplication.
