### ISSUE TITLE
Add devtools interfaces to web extension side bar

### ISSUE THREAD

**Issue by rebloor** [mdn/yari#5158]
With reference to [Issue with "devtools": broken links in sidebar #1126](https://github.com/mdn/content/issues/1126) from mdn/content.

The macro for the web extensions API content in the menu side bar isn't including devtools.inspectedWindow, devtools.network, and devtools.panels.

**Comment by caugner** [comment]
The sidebar is generated by the `AddonSidebar`, which in turn includes the `WebExtAPISidebar` that has a `buildSidebarForAllAPIs()` function.

While `commands` has subpages `getAll`, `reset`, `update` etc. that correspond directly to a method, property, type or event, this is not the case for `devtools`, which has those three interfaces (?!) `inspectedWindow`, `network` and `panels` that each have their own methods/properties/types/events (e.g. [devtools.network.getHAR()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/devtools/network/getHAR)).

@rebloor Can you tell me why `devtools.inspectedWindow`, `devtools.network` and `devtools.panels` are "Interfaces" and not properties? If they were properties and tagged accordingly in mdn/content, they should automatically appear in the sidebar (although not with their children).

**Comment by Rob--W** [comment]
> Can you tell me why `devtools.inspectedWindow`, `devtools.network` and `devtools.panels` are "Interfaces" and not properties? If they were properties and tagged accordingly in mdn/content, they should automatically appear in the sidebar (although not with their children).

What do you mean by "interfaces and not properties"? I don't see a special annotation at https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/devtools/inspectedwindow/index.md nor https://github.com/mdn/browser-compat-data/blob/main/webextensions/api/devtools.json

**Comment by caugner** [comment]
@Rob--W If you look at [browserSettings/allowPopupsForUserEvents](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserSettings/allowPopupsForUserEvents), you will see that the page appears under "Properties" in the sidebar. This is because it is tagged as "Property", see [here](https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/browsersettings/allowpopupsforuserevents/index.md?plain=1#L8).

Adding the "Property" tag to `devtools.inspectedWindow`, `devtools.network` and `devtools.panels` would implicitly add them to the sidebar.

**Comment by rpl** [comment]
`devtools.inspectedWindow`, `devtools.network` and `devtools.panels` are API namespaces nested into the `devtools` API namespace, technically they are not that different from `storage.local` / `storage.sync` / `storage.managed` being API namespaces nested into the `storage` API namespace but they are defined in a sightly different way in the JSONSchema (in particular the `devtools` ones are defined each in their own separate JSONSchema file, while the all the `storage` ones are explicitly defined as properties in a single `storage` JSONSchema file), that is likely the only reason why they didn't got tagged as properties.

I don't see any harm in adding the `Property` tag to these `devtools` API references pages (similarly to [how the `storage.local` one are tagged here](https://github.com/mdn/content/blob/670c6c5b8d75ed18722a10aecf657b7f41ecd78e/files/en-us/mozilla/add-ons/webextensions/api/storage/local/index.md?plain=1#L9)).

+1 on my side on doing that to make sure they gets listed in the sidebar.

**Comment by rebloor** [comment]
I'll add the tag
