### ISSUE TITLE
Issue with "CSS building blocks": Assessments missing in the navigation

### ISSUE THREAD

**Issue by glmvc** [mdn/yari#5164]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks

#### What information was incorrect, unhelpful, or incomplete?
In the navigation (Related Topics) on the left, the assessments are not displayed for the ["CSS building blocks" module](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks).

#### Specific section or headline?
Related Topics navigation on the left.

#### What did you expect to see?
Until now, the assessments were always displayed in the navigation on the left. For [this module](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks), I assumed that there were no assessments and almost overlooked them.

#### Did you test this? If so, how?
Assessments just on the [overview section of the page](https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks#assessments), not in the navigation.
The ["CSS layout" module](https://developer.mozilla.org/en-US/docs/Learn/CSS/CSS_layout) navigation for the assessments is also missing - additionally, the heading "Assessments" is missing on the page in general.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/building_blocks`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/building_blocks/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by schalkneethling** [comment]
@glmvc Hi there! This seems to have been fixed. Can you confirm? Thank you.

**Comment by glmvc** [comment]
@schalkneethling Hi! No, the pr (#5828) with the fix is still open and needs to be approved and merged :)

**Comment by wbamberg** [comment]
@glmvc , I'll take a look, sorry I missed it. Please feel free to ping me if a PR is sitting for too long :).

**Comment by glmvc** [comment]
@wbamberg Hi, I made new commits to the pr (#5827) :) I have also left a few questions there.

Please note pr #6050 and pr #6053 which are very similar, just for the reference sidebars but with almost the same changes / improvements. This prs are somehow related / connected to #5827 and this issue. I have also left some questions there.
