### ISSUE TITLE
one mozilla.org page doesn't load in FF (documentation for css `skew`)

### ISSUE THREAD

**Issue by ashleedawg** [mdn/yari#5170]
Oddly, this _**one**_ mozilla.org page won't open in Firefox, _but it's fine in Chrome:_

**https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/skew()**

It actually loads and flashes the content for a split second before the page goes blank.  I use mozilla.org constantly but haven't experienced it with any other page (on any site).

I tried refreshing without cache (<kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>R</kbd>), restarted Firefox, tried private browsing, rebooted my machine, and tried modifying the URL (like, to remove brackets at the end, and to remove the language/country) but it just redirects back to the same URL, with the same result. I can still `View Page Source`; it just doesn't render.  🤔

I recently updated to Firefox 96.0.1 (64-bit) and I'm using Windows 10, build 19044 (fully updated).

**Comment by schalkneethling** [comment]
@ashleedawg I just tried this page and it works for me. Do you still experience the problem as described?

**Comment by schalkneethling** [comment]
Seems like this one is fine now, closing the issue. If there is indeed still a problem, please reopen and let us know. Thank you.
