### ISSUE TITLE
Page loading issues with certain language configurations

### ISSUE THREAD

**Issue by Alexthemediocre** [mdn/yari#5171]
On the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects page, it will be loaded briefly before blanking out the page when using certain configurations of languages in the browser's language list. This seems to be because the site returns a 404 for certain scripts with those configurations, specifically https://developer.mozilla.org/static/js/24.ebbdebe0.chunk.js and https://developer.mozilla.org/static/js/5.d8f248fb.chunk.js. When I was using Chrome, the "accept-language" header being sent was "en-US,en;q=0.9,el;q=0.8,la;q=0.7". When I changed it to "en-US,en;q=0.9,la;q=0.8" or "en-US,en;q=0.9", the scripts and the page loaded normally.

Using the "Copy -> Copy as fetch" option through the network tab of the Chrome DevTools page on one of these failed requests gives:
```js
fetch("https://developer.mozilla.org/static/js/24.ebbdebe0.chunk.js", {
  "headers": {
    "accept": "*/*",
    "accept-language": "en-US,en;q=0.9,el;q=0.8,la;q=0.7",
    "cache-control": "no-cache",
    "pragma": "no-cache",
    "sec-ch-ua": "\" Not;A Brand\";v=\"99\", \"Google Chrome\";v=\"97\", \"Chromium\";v=\"97\"",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "\"Windows\"",
    "sec-fetch-dest": "script",
    "sec-fetch-mode": "no-cors",
    "sec-fetch-site": "same-origin"
  },
  "referrer": "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});
```

Again, the only thing needed for the site to return a 200 instead of a 404 for those scripts is to delete at least one language from the "accept-language" header.

**Comment by schalkneethling** [comment]
> On the [developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects) page

@Alexthemediocre this page renders for me. Is there a specific locale for which this page fails to render?

**Comment by Alexthemediocre** [comment]
@schalkneethling Today, the page seems to load normally using the language configurations that I had when I first came across this issue, and the addresses of the scripts used on that page have updated. However, the scripts that I linked in my original message (which I assume were blanking out the page when they didn't load) still seem to not load with the accept-language header as "en-US,en;q=0.9,el;q=0.8,la;q=0.7" but succeed with the language header "en-US,en;q=0.9". I never changed the language of the page I was viewing (which was en-US), just the browser's language list and the accept-language header.

I did not change the first language in the language list, just adding and removing secondary ones. But, for whatever reason, the value of the accept-language header (i.e. the browser's language list) seemed to be determining whether or not the server would return a 404 for those scripts.

**Comment by schalkneethling** [comment]
Thank you for the additional information @Alexthemediocre. Seeing that the page(s) display correctly for you now and that we have no other reports of this being a problem, I am going to close this issue. If you run into this again in future, feel free to reopen.
