### ISSUE TITLE
Some pages have related topics in main content

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5180]
For some pages like https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze the related topic sidebar is missing, and instead, the list is added to the `main` content area.

**Comment by schalkneethling** [comment]
If you compare the `content`(in the content repo) of the following pages:

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Equality

The first has this as the first entry after the frontmatter:

```md
{{JSRef}}
```

The second of the two(which renders correctly), has this:

```md
{{jsSidebar("Operators")}}
```

**Comment by Elchi3** [comment]
Why did this 

`output  = '<section id="Quick_links"><ol>';`

changed to

`output = '<section class="Quick_links" id="Quick_Links"><ol>';`

in https://github.com/mdn/yari/pull/3944/files?diff=split&w=1 ?

Could that be the reason?

**Comment by schalkneethling** [comment]
The problem, in the end, was that the `id` attribute should be `id="Quick_links"` and not `id="Quick_Links"`
