### ISSUE TITLE
Port "Fundamental redirects" into Yari

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#519]
**UPDATE Aug 12 2020**

What we need to do is, on the surface, easy:

1. Port the kuma `redirects.py` into a JavaScript file/function 
2. Make this available so it can be used in the `Redirect.resolve` function as a fallback for that object lookup
3. Somehow get this JS function copied into the Lambda@Edge function that runs on "Origin response"

Perhaps the simplest would be to publish this as a standalone npm package and then both Yari and the Lambda@Edge zip can import it easily. 

----

When tinkering with the "flaws" prototype I noticed that on http://localhost:3000/en-US/docs/Web/HTML/Element/audio the very last link there is broken. It links to http://localhost:3000/en-US/Apps/Fundamentals/Audio_and_video_delivery/Cross-browser_audio_basics which the `server` can't map to either a folder or a redirect. But the `_redirects.txt` is so close:

```
▶ cat content/files/en-us/_redirects.txt | rg Fundamentals | rg Cross-browser_audio_basics
/en-US/docs/Web/Apps/Fundamentals/Audio_and_video_delivery/Cross-browser_audio_basics	/en-US/docs/Web/Guide/Audio_and_video_delivery/Cross-browser_audio_basics

```

What that redirect does is it changes `Apps` for `Guide`. **But** note that the URL still always starts with `/en-US/docs/Web/...` which we're missing. 

As a matter of fact on [the `<audio>` page](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/audio)
the link at the bottom there points to `https://developer.mozilla.org/en-US/Apps/Fundamentals/Audio_and_video_delivery/Cross-browser_audio_basics` which (302) redirects to `/en-US/docs/Web/Apps/Fundamentals/Audio_and_video_delivery/Cross-browser_audio_basics`

I believe the reason it works in prod (kuma) is because of this:
https://github.com/mdn/kuma/blob/3a64b3aad148f174882427957c28cb9a32891e7a/kuma/redirects/redirects.py#L925

I call those "fundamental redirects" because they're application-level redirects and not part of the content.

**Comment by peterbe** [comment]
I think we need to do two things, somewhat orthogonally since it'll be very hard to share this code:

1. We need to port the contents of [`redirects.py`](https://github.com/mdn/kuma/blob/master/kuma/redirects/redirects.py) to Lambda@Edge so that these redirects are correctly dealt with when we're 100% "jamstacked".  
2. We need to port the contents of `redirects.py` into the `server` (`localhost:5000`) so it can use that to help the local development environment. Otherwise, you'll get a bunch of broken links when clicking around locally and your dev environment won't match production nearly enough.

**Comment by escattone** [comment]
This is done. See:
- https://github.com/mdn/yari/pull/1359
- https://github.com/mdn/yari/pull/1425
