### ISSUE TITLE
Issue with "References": (the pages is loaded without the layout style)

### ISSUE THREAD

**Issue by tamminh2003** [mdn/yari#5197]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/

MDN Content page report details
  - Folder: content/files/en-us/web/  - GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/index.md
  - MDN URL: https://developer.mozilla.org/en-US/docs/Web/

There are other pages with the same issue.

![image](https://user-images.githubusercontent.com/8927582/150211261-aa3abaac-c615-4f44-bf6e-d3e9b1395387.png)

**Comment by schalkneethling** [comment]
Hey @tamminh2003, thank you for filing an issue. I just tested the page and all seems fine on my end. Are you still experiencing this problem?

If so, please also include the OS, browser and browser version you are using. Thank you.

**Comment by tamminh2003** [comment]
Hey @schalkneethling, thank you for following up on this. The website working fine now. No more issues with styling.

**Comment by schalkneethling** [comment]
> Hey @schalkneethling, thank you for following up on this. The website working fine now. No more issues with styling.

Thanks so much for confirming.
