### ISSUE TITLE
Add fallback redirects for NSS and NSPR documentation

### ISSUE THREAD

**Issue by ddbeck** [mdn/yari#5260]
## Summary

Redirect remaining Firefox NSS and NSPR documentation 404s with a catchall redirect to their respective documentation sets.

## Motivation and background

Firefox Source Docs previously lived on MDN. They've since moved to https://firefox-source-docs.mozilla.org/. Unfortunately, when many of those docs moved, no redirects were set up. This creates the appearance that the docs were deleted outright, provoking understandable confusion and anger from readers.

In many cases, we now have proper page-to-page redirects from MDN to the Firefox Source Docs (see https://github.com/mdn/content/pull/12731 as an example). However, it's possible that some pages weren't redirected or that in-bound links from the rest of the web have typos or other errors which will prevent useful redirects from taking place. To mitigate this, we should implement a fallback redirect from each tree to a URL, specified below.

Note that these redirects should be fallbacks. Redirects in [`_redirects.txt`](https://github.com/mdn/content/blob/main/files/en-us/_redirects.txt) should apply before the fallbacks below.

## Tasks

- [ ] Redirect `/en-US/Mozilla/Projects/NSS/*` to `https://firefox-source-docs.mozilla.org/security/nss/index.html`
- [ ] Redirect `/en-US/Mozilla/Projects/NSPR/*` to `https://firefox-source-docs.mozilla.org/nspr/listing.html`

**Comment by ddbeck** [comment]
We discussed this in the most-recent content + engineering call, and learned that wildcards like I've suggested aren't really possible at the moment. Instead, we'll use a slightly less sophisticated approach: use Cloudfront 404 logs to find recent (past 30 days? or whatever horizon looks reasonable) URLs containing NSS or NSPR and put in redirects for those URLs. That is likely to capture any straggling broken links to MDN.

@schalkneethling @Guyzeroth can one of you get into Cloudfront and report on this stuff? It's not terribly urgent, but I'd like to finally close the book on NSS and NSPR docs at some point.

**Comment by schalkneethling** [comment]
> @schalkneethling @Guyzeroth can one of you get into Cloudfront and report on this stuff? It's not terribly urgent, but I'd like to finally close the book on NSS and NSPR docs at some point.

I cannot, but I have also asked @fiji-flo

**Comment by ddbeck** [comment]
Got the list from @fiji-flo (sorry, I mistakenly forgot to tag you instead of Schalk). https://github.com/mdn/content/pull/13284 is open. This is more or less resolved now.
