### ISSUE TITLE
Fallback english url removes markdown styling

### ISSUE THREAD

**Issue by davbrito** [mdn/yari#5269]
When I write an URL that doesn't exist in Spanish, Yari replaces the link with the `en-US` version of the page as a fallback.

The problem comes when the text inside the Markdown link is styles with backticks, in which case the markup gets removed and left as plain text.

The source code:
  [![image](https://user-images.githubusercontent.com/39559632/153298058-127d279b-c6ae-4b52-ba2b-41c21e864d59.png)](https://github.com/mdn/translated-content/pull/4066/files#diff-2ced37d3e8c36019be77bcde1af28de2f3a0e26e4e1e25b924692fdfd7f14a4fR21)

The result:
[![image](https://user-images.githubusercontent.com/39559632/153298689-b0db4a3e-6346-4792-ad8a-cffd4b0b43e3.png)](https://pr4066.content.dev.mdn.mozit.cloud/es/docs/Web/API/Notification/icon)

> Note: I'm using this PR https://github.com/mdn/translated-content/pull/4066 to give the context for this issue.

**Comment by caugner** [comment]
It looks like this is the culprit:

https://github.com/mdn/yari/blob/13890752c2de8998357ff6fbe0dcde748d06f89e/build/flaws/broken-links.ts#L64-L66
