### ISSUE TITLE
mobile view responsive issue

### ISSUE THREAD

**Issue by blackSky1213** [mdn/yari#5273]
below given link there is one code tag overflow in x direction which create white space in right side.
link :- https://developer.mozilla.org/en-US/docs/Web/Guide/AJAX/Getting_Started
![Screenshot (112)](https://user-images.githubusercontent.com/42443511/153562237-c537b25f-a45a-4b3c-8b12-8aae9efb04a2.png)

![Screenshot (113)](https://user-images.githubusercontent.com/42443511/153562785-ed8f9b02-e864-40be-a586-0ae290d15f34.png)

solution : remove white-space property from code class.
![Screenshot (115)](https://user-images.githubusercontent.com/42443511/153563010-5d3b1188-14e9-4dca-a748-f78a460df132.png)

**Comment by schalkneethling** [comment]
@blackSky1213 We launched a complete redesign yesterday. It looks like this issue was fixed as part of the redesign. Can you please have a look and confirm? Thank you

**Comment by blackSky1213** [comment]
done! now issue is fix.

**Comment by schalkneethling** [comment]
> done! now issue is fix.

Thank you for confirming.
