### ISSUE TITLE
Issue with "Use the Inspector API": bad link in sidebar "Connecting the devtools" (with fix)

### ISSUE THREAD

**Issue by WebMechanic** [mdn/yari#5293]
MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Use_the_Inspector_API

#### What information was incorrect, unhelpful, or incomplete?
The sidebar section "Connecting the devtools" features a link [Connecting to other browsers](https://developer.mozilla.org/en-US/docs/Tools/Valence) but that page does not exist.

#### What did you expect to see?
Information on how to "Connecting to other browsers" -- which would indeed be  a nice feature to have.

### Related content / issue
There's another page about [Remotely debugging Chrome Desktop](https://developer.mozilla.org/en-US/docs/Tools/Remote_Debugging/Chrome_Desktop) that also features a link to the "Valence" page, but it's properly shown in red.

The actual issue appears to be: **sidebar links** (unlike content pages) do not realize if a wiki page does not exist.

### Probable fix
Replace to link to the non existing "Valence" page with the one for "Remotely debugging Chrome Desktop" given above.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/tools/page_inspector/how_to/use_the_inspector_api`
* MDN URL: https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Use_the_Inspector_API
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/tools/page_inspector/how_to/use_the_inspector_api/index.html
* Last commit: https://github.com/mdn/content/commit/6b813901a413f1ea27bc0c982e041f7c60c2604e
* Document last modified: 2021-04-05T17:56:05.000Z

</details>

**Comment by WebMechanic** [comment]
thanks for the transfer :)

---
slightly off topic: do you happen to know where such cross-browser debugging and esp. **better** IDE integration of FF is being developed and discussed? 

It's very annoying that virtually all editors and IDEs only support Chrome derivatives for (integrated) remote debugging and there are either issues w/ FF not functioning properly or the setup is tedious an unreliable.
Any hints appreciated.

have a nice time

**Comment by WebMechanic** [comment]
great, didn't know about the channel. I'll check that out!

**Comment by caugner** [comment]
The page in question has meanwhile been moved off MDN (namely [here](https://firefox-source-docs.mozilla.org/devtools-user/index.html#page-inspector)), so I will go ahead and close this issue.
