### ISSUE TITLE
Issue with build in linux server, links can't be recognize

### ISSUE THREAD

**Issue by ysrdear** [mdn/yari#5313]
I use yari build content，and move client/build to linux server , use http-server , but links look like  /en-US/docs/Web can't show because the files and folders  are lowercase

**Comment by caugner** [comment]
Hi @ysrdear, thank you for taking the time to report this issue, and sorry it took us so long to get back to you! 👋 

If you still experience this issue, please open a [new issue using our new issue template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml) to make sure we have all information to look into the problem. Thank you! 🙏
