### ISSUE TITLE
styling: hyperlink to licenses

### ISSUE THREAD

**Issue by frogtile** [mdn/yari#5336]
> © 2005-2022 Mozilla and individual contributors. Content is available under [these licenses](https://developer.mozilla.org/docs/MDN/About#Copyrights_and_licenses).

In https://developer.mozilla.org "these licenses" has no visual difference than a regular piece of text

**Comment by HerminaC** [comment]
Hi @frogtile can you please point me exactly where you're seeing this? I don't manage to find it. Thanks!

**Comment by frogtile** [comment]
> Hi @frogtile can you please point me exactly where you're seeing this? I don't manage to find it. Thanks!

This has been fixed the redesign. Thanks!
