### ISSUE TITLE
Dark mode interferes with js demo console

### ISSUE THREAD

**Issue by SanketRP** [mdn/yari#5354]
### Issues
In the light mode after pressing reset console. The whole js demo block turn back to dark mode.

![Image](https://i.ibb.co/n6kd88X/image.png)

**Comment by Pranav-yadav** [comment]
Vice-versa is also true. i.e., dark shows light & light shows dark on clicking reset. 👍 
btw, <3 the new look :)

**Comment by caugner** [comment]
Duplicate: #5381
