### ISSUE TITLE
Code blocks wrap on mobile

### ISSUE THREAD

**Issue by Den0702** [mdn/yari#5357]
Hello,

I have encountered several problematic things after the mozilla's site had swicthed to new design and I wander if there is a possibility to correct (at least what will be possible to) in the near future. 

1.  The _line height_ . On mobile screen there is less content **to fit on screen** now, so from now on there is a need to scroll the content more often which seems a little bit distractive while studying.
2.  _Font weight_.  If it were a little bit bolder it would be easier to see whats is on the screen (this is not too critical)
3.  _Margin_. It became bigger so it results to the same problem as described in the 1st point.
4.  _The `code` font size in relation to other text size_. The `code font` is a bit small at 100% screen's size The first thought is to zoom a page, but it increases a much the problem described in the 1st point.
5.  **The _code wrapping_.** . This is the biggest problem because now it is **definitely hard** to read the code when it's wrapped because of not fitting to the screen. As for me scrolling a bit is not a very big problem.
6. The _code font's lightness_. On such a readers is harder to see the text which has a light color. It's better if it would be a little bit darker (However, this point is not a critical one).

Below are the example screenshots attached of the present and previous versions (have no idea why github turns over the images, I tried to change orientation, but it behaves strange and only one image looks normal ):
![20220301_152107](https://user-images.githubusercontent.com/30319035/156194981-01824ba9-fe01-44bf-884b-c6c4969beee0.jpg)
![20220301_152201](https://user-images.githubusercontent.com/30319035/156194999-c8376a2e-54e6-4ed1-91a1-8bef6834f0f1.jpg)

Edit: I attached below another image

Kind regards

**Comment by Den0702** [comment]
![20220306_125533](https://user-images.githubusercontent.com/30319035/156922138-f6c2d476-3109-4635-a6fa-bbc345e0af3b.jpg)

**Comment by caugner** [comment]
I'm not sure what is the best way to target e-readers, but I will add the `accepting PR` label.

Any solution that improves the layout for e-readers without changing the layout for other devices (mobile + desktop) is appreciated!

**Comment by Den0702** [comment]
> I'm not sure what is the best way to target e-readers, but I will add the `accepting PR` label.
> 
> Any solution that improves the layout for e-readers without changing the layout for other devices (mobile + desktop) is appreciated!

@caugner Thank you, but it looks like the same situation on mobile phones? Here is for example horizontal screen view
![Capture+_2022-03-22-18-32-19 1](https://user-images.githubusercontent.com/30319035/159542807-c0a6786e-d92b-4c9c-b7b8-e45a9ea9581a.png)

**Comment by caugner** [comment]
The redesign added `white-space: pre-wrap;` to `pre`, which causes the code blocks to wrap, so they no longer overflow with a scrollbar, cf. [old design](http://web.archive.org/web/20220124135755/https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction#the_verbosity_of_dom_changes) vs. [new design](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction#the_verbosity_of_dom_changes).

**Comment by Den0702** [comment]
> The redesign added `white-space: pre-wrap;` to `pre`, which causes the code blocks to wrap, so they no longer overflow with a scrollbar, cf. [old design](http://web.archive.org/web/20220124135755/https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction#the_verbosity_of_dom_changes) vs. [new design](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Introduction#the_verbosity_of_dom_changes).
> 
> PS: This refers to point 5 of the issue description.

Thank you for the answering

**Comment by caugner** [comment]
We have discussed this issue, but decided to close it as won't fix, because a) the issue only received a single upvote since 2022, and b) user preferences regarding code wrapping vary (and we don't want to make this a setting).

Nevertheless, we thank you for taking the time to report this, and for your patience! 🙏
