### ISSUE TITLE
Firefox Reader Mode does not show tables

### ISSUE THREAD

**Issue by quentinvernot** [mdn/yari#5358]
### Issues

I found some pages where opening firefox's reader mode would display incomplete content:

[Doc for the WWW-Authenticate HTTP header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate)
![Screenshot 2022-03-01 at 16-07-23 WWW-Authenticate - HTTP MDN](https://user-images.githubusercontent.com/6038707/156194470-878e4c61-5f64-4f2d-b00a-1219f277bd50.png)

In this case, only the browser compatibility table seems to have made it in. Other pages for http headers seem to behave the same way, although some just don't have a reader mode, possibly due to very short content.

The obvious culprit seems to be the new theme, but I can't say for sure. It worked fine [2 months ago](https://web.archive.org/web/20211208225940/https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate)
![Screenshot 2022-03-01 at 16-52-48 WWW-Authenticate - HTTP MDN](https://user-images.githubusercontent.com/6038707/156202136-1a62d5c3-855e-4f36-a54a-ca5c4928be5d.png)

Other pages seem to handle reader-mode better than other, for example the [doc for Array.find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find) seems to work fine, only the compatibility table seems broken (and, again, it seemed better [a month ago](https://web.archive.org/web/20220203121650/https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)). I've been through most of the Array pages and they all seem to behave the same way.

**Comment by quentinvernot** [comment]
I just did a quick check just now, and it looks like it's almost fixed! The compatibility table is still missing in reader mode, but the rest looks exactly like it used to!

**Comment by schalkneethling** [comment]
That is great news @quentinvernot! Thank you for verifying. I believe the problem with the compatibility table is probably related to how it is loaded. @mdn/core-dev not sure how hard this would be, and perhaps the future plans for Yari will already address this, but I thought I would at least put it on your radar.

**Comment by caugner** [comment]
Firefox Reader mode seems to omit tables, because it isn't trivial how to render them in a readable way:

<img width="807" alt="image" src="https://user-images.githubusercontent.com/495429/190223703-5fcd6290-85f0-4f37-9e30-22f92ce3198b.png">

<img width="731" alt="image" src="https://user-images.githubusercontent.com/495429/190223769-3fc2cae4-47b3-4bc7-8baf-94ab830a9d4a.png">

I will discuss this with the rest of the MDN engineering team, but I don't think there is much that we can do.

**Comment by quentinvernot** [comment]
Hey! Thanks for the fix, I can confirm that tables are working now! Unfortunately, the compatibility table at the end of the page is still broken.

Looking into it, it looks like this table is generated from a request to `<page url>/bcd.json`, which was already the case with the old theme so that's probably not the issue. The table is wrapped in a double `<div>` however, to have horizontal scrolling in narrow viewports, and seeing how it affected the other tables, I'd bet this is the cause of the issue here too. The wrapping is probably here for a good reason though: it's a wide and dense table, it even has responsive styles for various viewport widths, so I'm not sure how it can be fixed, I don't know this codebase enough to know where the look.

I got screenshots though:

<details>
<summary>Before</summary>

![Screenshot 2022-11-16 at 20-57-41 WWW-Authenticate - HTTP MDN](https://user-images.githubusercontent.com/6038707/202285071-221ccdeb-73cc-4a4a-b431-c6b84fb4613b.png)


It was even scrollable and everything!
</details>

<details>
<summary>After</summary>

![Screenshot 2022-11-16 at 20-58-02 WWW-Authenticate - HTTP MDN](https://user-images.githubusercontent.com/6038707/202285103-fe467e9f-6653-4249-955f-9054677d55a0.png)

</details>

Would you like me to open a separate issue for this?

**Comment by caugner** [comment]
Glad to hear it's working now! 🙂 

> Would you like me to open a separate issue for this?

I think this should be covered by https://github.com/mdn/yari/issues/3653, i.e. resolving that issue should also resolve this. (And now this issue is referenced there.)

As long as we don't server-side render BCD tables, they won't appear in the Reader Mode. 😉

**Comment by quentinvernot** [comment]
Alright, I'll keep an eye on https://github.com/mdn/yari/issues/3653. If that still doesn't fix the issue, I'll re-open something then.

Thank you!
