### ISSUE TITLE
Suggestion: the search field on the home page should be automatically focused on load

### ISSUE THREAD

**Issue by globau** [mdn/yari#5360]
Automatically focusing the search field would be nice.

**Comment by schalkneethling** [comment]
Hey @globau, thank you for raising the issue. We explicitly decided not to do that for accessibility reasons. If you are either a blind/low-vision user or a keyboard-only user, being immediately thrown into this mode is not ideal.

You have to kinda figure out what context you are in, and then how it fits into the overall page. Hope that explains the decision.

**Comment by globau** [comment]
Thank you for the clear response!
