### ISSUE TITLE
Bring back the old design

### ISSUE THREAD

**Issue by PurpleVsGreen** [mdn/yari#5364]
Did you know Firefox supports alternative stylesheets? Would be cool to have the old design as an alternate stylesheet.

**Comment by runbing** [comment]
This is a good suggestion, I prefer old look.

**Comment by arcataroger** [comment]
The new version is really hard to read =/  The pinkish-red is terrible. Please revert to the old design and stop trying to "fix" what wasn't broken... these reference guides don't need to be an art project. Who ever asked for this?

**Comment by arcataroger** [comment]
Old version was crystal-clear: https://web.archive.org/web/20210302090607/https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

New version is completely unskimmable, too dense, and horrific color scheme:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

Yikes =/ This is really bad.

**Comment by navjotjsingh** [comment]
Agree. Please give us a choice to go back to the old site/design. This was totally unnecessary and has made the site totally useless.

**Comment by whathappenedman** [comment]
+1

**Comment by initdc** [comment]
I am building content with yari@0.6.69, Many JAMStack platform not working very well.

@Cloudflare Pages deploy log only support 5000 lines, and max 20K assets

@Netlify build time limit in 30 mins

Github pages also not very well

The MDN need runing on express server to support Uppercase URL

I am still trying on some other platform

Here is an runing instance with Netlify https://mdn2.netlify.app/en-us/docs/web/

I've working on this for half a day, I feeling tired right now.

I can't imaging the MDN people and community paying how much of time and attention to build the documents.

We need time to adapt to the change, we need the choice, some people choose stay, some choose forward, 

no matter what does MDN looking like, we all keep learning, that's the most important thing.

**Comment by initdc** [comment]
It's a really big problem that when @nodejs building project, it runing on single thread.

I miss the @gohugoio hugo,  will @denoland deno solve this problem?

**Comment by DeciderWill** [comment]
@initdc took 17 minutes to build on [Northflank ](https://northflank.com) example running at: [https://site--docs--mdn--nort-xjjq.code.run/en-US/](https://site--docs--mdn--nort-xjjq.code.run/en-US/) with `yari@0.6.69`

**Comment by initdc** [comment]
Try new a folder named `mdn`, put `yari content translated-content` in,
 setup .env,  
run command in yari

**Comment by initdc** [comment]
In new design, font is more tiny, contrast ratio will falldown.
The font-size more small, the font-weight should bolder.

font-weight using 100-900 is a bad idea, because some of them doesn't make sense.

**Comment by e3dio** [comment]
The good thing is it is very easy to add your own styles, a couple changes made the site nice for me, I am using the styles here https://github.com/mdn/yari/issues/5389 with before and after screenshots. Basically just adjust the Header/paragraph styling, remove extra whitespace, remove 3rd column and use full screen width, add code contrast, scrollbar styling. I will update styles if I make more changes

**Comment by hugohabicht01** [comment]
+1
The old design wasn't really beautiful but it was really well-arranged, finding what I was looking for was easy. In the new design the font is waaaay too small, the contrast sucks, the font sucks, it's not well arranged. Who even thought that this was a good idea? I mean new design, sure I wouldn't mind, but who approved this horrendous design? Everything is worse than it was before

**Comment by initdc** [comment]
I've edited the github action to enable auto building the `English-Only` MDN documents. 
check: https://github.com/initdc/yari/blob/style/old/.github/workflows/prod-build.yml
continuous deploy to @netlify. Very thankful to @netlify team member in community.
check: https://answers.netlify.com/t/deploy-6-8g-of-old-style-mdn-files-to-the-platform/52859


known issue: 
  1. English only, bigger output will reached build time limit.
  2. search not working, only suggestion items will send you right place.

I know node.js hosting maybe better, but I may have no time or fund to handle this, sorry for that.

**Comment by initdc** [comment]
I did it, check out http://mdn1.moz.one

Deploy on @vercel + Cloudflare

**Comment by jxu** [comment]
This is not just a design issue but an ACCESSIBILITY issue. My eyes are straining

**Comment by DCzajkowski** [comment]
@initdc What is your strategy for updating content on [mdn1.moz.one](http://mdn1.moz.one/)? Are you going to update it on a schedule automatically or are you planning to update content once every some time?

<details>
<summary><i>Custom bookmarket for easy design switching</i></summary>
<pre>javascript: ((() => { window.location.href = window.location.href.replace('https://developer.mozilla.org', 'https://[mdn](javascript: ((() => { window.location.href = window.location.href.replace('https://developer.mozilla.org', 'https://mdn1.moz.one') })());)1.moz.one') })());</pre> and assigned it an "mdn" keyword.
</details>

**Comment by jxu** [comment]
why have a mirror site when maintaining a custom CSS script enabled with ex. greasemonkey is all that is needed.

**Comment by DCzajkowski** [comment]
@jxu we are going off the topic here, but it's not just the css. There is quite a lot that changed, new bugs were introduced etc. For example my console is filled with JS errors, some shortcuts stopped working, there are weird behaviors around the new themes, some information is hidden with JS (like the browser support versions), some things are wrongly labeled, some things are missing labels — just look at the list of issues on this repo. The list goes on and on.

Until the new redesign becomes usable, having a mirror as a middle step does not seem like a bad idea imo

**Comment by jxu** [comment]
I see. Makes sense and we can also use archive.org archives if the mirror is unavailable

**Comment by initdc** [comment]
Contents auto build by github actions per 3 day, tell me if want it keep up-to-date per day.

I provide you better way to change theme
When you browsing https://mdn1.moz.one/en-US/docs/Web
you may thinking, ohmygod, this is a fucking mirror, I don't trust a fucking unknow source mirror.

You just need delete the `1`, it will be https://mdn.moz.one/en-US/docs/Web
You will be send to official website.

Tell me if you don't need this mirror, if does, I will make it private.

**Comment by DCzajkowski** [comment]
@init thank you for the answer. Every three days sounds reasonable. 

Please keep it up for now until the new website is brought to a better state 🙂

**Comment by bartenra** [comment]
> I did it, check out http://mdn1.moz.one
> 
> Deploy on @vercel + Cloudflare

Found a broken link

https://mdn1.moz.one/en-US/docs/Web/Reference

Otherwise really helpful!

**Comment by initdc** [comment]
> 
> Found a broken link
> 
> https://mdn1.moz.one/en-US/docs/Web/Reference
> 
> Otherwise really helpful!

It has redirect to /en-US/docs/Web, since 2021-06-13

https://web.archive.org/web/20210609000000*/https://developer.mozilla.org/en-US/docs/Web/Reference

source file doesn't exsit, https://github.com/mdn/content/blob/main/files/en-us/web/reference/index.html

**Comment by gatewaytofredom** [comment]
The new design feels very much like it's trying to be google docs. That's not a good thing. MDN has been the best documentation for years in terms of accessibility and clarity.  Now it is a low contrast spaced out mess that's harder to read. 

Information is much less clear. The browser compatibility no longer features the  icon of the browser. Instead we now have to rotate our heads or struggle to read text that's rotated 90 degrees. Headlines and titles are now smaller and not bold making it hard to easily find information. In example code of what not to do, the boxes containing incorrect examples are no longer red to easily denote that they are in fact, wrong examples. The list goes on and on.

Everything about the new design appears as if they wish to make MDN less accessible to users.

**Comment by Krelyshy** [comment]
> Contents auto build by github actions per 3 day, tell me if want it keep up-to-date per day.
> 
> I provide you better way to change theme When you browsing https://mdn1.moz.one/en-US/docs/Web you may thinking, ohmygod, this is a fucking mirror, I don't trust a fucking unknow source mirror.
> 
> You just need delete the `1`, it will be https://mdn.moz.one/en-US/docs/Web You will be send to official website.
> 
> Tell me if you don't need this mirror, if does, I will make it private.

Please, keep the mirror up. It's the only usable subserver on the MDN right now. I will make an extension that will automatically redirect you to this mirror if you click on a link pointing to the "public" MDN.

**Comment by initdc** [comment]
I will do my best to keep it working.
Stay grateful to the MDN developers and contributors, I just did a little bit of work.

**Comment by Krelyshy** [comment]
Here is the extension if it interests anyone:
https://addons.mozilla.org/cs/firefox/addon/modestly-denying-the-new/

It simply redirects all traffic to developers.mozilla.org to the aforementioned mirror.

**Comment by initdc** [comment]
Hey, I wanted to mention that mdn is having some problems with the deployment on @vercel, and I'm running into build time limits, like I did on @netlify. I was tired of this issue, the build process is done through github actions and I had no idea how to solve the changes in their platform's build workflow. So I tried the github pages instance and luckily it worked, but there were issues with URL case mixing. check the instance with latest content at:

https://mdn3.moz.one

I don't want to add to this number unnecessarily, it's a proof of how different platforms have helped open source, and I want to give my respects to that. and the existing problems are not enough to get it to the tier 1. But if you guys are more used to `mdn1`, please let me know.

**Comment by Krelyshy** [comment]
I'm currently using mdn1. Do the problems mean that mdn1 is not going to be updated?

**Comment by initdc** [comment]
> I'm currently using mdn1. Do the problems mean that mdn1 is not going to be updated?

Yes, I don't know how to fix it

**Comment by initdc** [comment]
I build a chrome extension, src on: https://github.com/initdc/MDN-Wayback/

install it
https://chrome.google.com/webstore/detail/gholkimjbjkdpibnfcocfdighkjbhbhd

**Comment by caugner** [comment]
We don't have any plans to bring back the old design, but we continue to welcome feedback and suggestions about how to make the new MDN design even better.

Thank you! 🙏
