### ISSUE TITLE
Regression: Errors + warnings less visible since redesign

### ISSUE THREAD

**Issue by mmis1000** [mdn/yari#5367]
## Step to reproduce

1. Open the HTML documents of some deprecated elements in new mdn docs

## What happen

The errors in HTML docs section is basically the same as normal contents.
Without read the Icon and text, you aren't even know this is a error section.

![圖片](https://user-images.githubusercontent.com/2993977/156192066-4a0c6fd0-2e92-4ad8-9a8f-298652e59ecf.png)
![圖片](https://user-images.githubusercontent.com/2993977/156192750-9c828a16-9690-4ef4-9965-399dedbe5f5d.png)

## What did you expect

Primary color of a page is something sane instead of the same as error color.
Error color should be used exclusively for error.

Either the main color should be changed to something else, or the error color should be even darker.

Take the css docs for example.
You know what is a error section or error icon even you blur it and don't read the text at all.

![圖片](https://user-images.githubusercontent.com/2993977/156193440-e17dcb44-b3cb-45c3-8f46-76b68758d483.png)
![圖片](https://user-images.githubusercontent.com/2993977/156193752-8dfc6b1b-ea6d-4cd6-ad9a-22287ea96aff.png)

**Comment by caugner** [comment]
This is how it looked before:

![image](https://user-images.githubusercontent.com/495429/156377374-41f2f629-87bb-4318-9abc-d46dae6f8949.png)

Source: https://web.archive.org/web/20211208085002/https://developer.mozilla.org/en-US/docs/Web/HTML/Element/acronym

**Comment by HerminaC** [comment]
@caugner Maybe you can take this? First of, let's address the alert/messaging/notifications and use as guideline Mozilla's protocol design system: https://protocol.mozilla.org/patterns/molecules/notification-bar.html. Color palette considered both light and dark more, so it should do fine.  
Once we have those established, we could go back to ensure the section colors are significantly different from those of notifications.

**Comment by pilchard** [comment]
The truth is the 'colorways' applied to all links on the page makes the reading experience highly inconsistent between categories, and one often has to read across categories when referencing related APIs. I think it would be better to keep link colors consistent across all categories, especially inline links, and demarcate by 'colorway' in some neutral way that doesn't affect content.

**Comment by spartanatreyu** [comment]
Related to: https://github.com/mdn/yari/issues/5396
