### ISSUE TITLE
UI suggestion: The search box expands by default for new website

### ISSUE THREAD

**Issue by initdc** [mdn/yari#5368]
## What is the new suggestion?

The search box expands by default

## Why is it important or useful?

I come for search something

## Other supporting information

I'm having trouble with the new website design. Even with the improvements, the search box is still too small.

**Comment by initdc** [comment]
When search opened, dark mode switcher will hide.

Put switcher after search could be a better way, switcher don't need hide

**Comment by schalkneethling** [comment]
Part of https://github.com/mdn/yari/pull/5507
