### ISSUE TITLE
UI suggestion: Make index list 'headings' easier to recognize

### ISSUE THREAD

**Issue by jonathantneal** [mdn/yari#5369]
Looking at this alphabetical list of all the APIs that are available, it is difficult for me to find the correct letter 'heading'.

**Example:**
https://developer.mozilla.org/en-US/docs/Web/API#specifications

**Possible enhancement:**
![Screenshot of the lengthy Web APIs index on MDN. The list is alphabetically organized, with headers for each letter ("A", "B", "C"). The screenshot includes a style modification to more strongly visually indicate  these headers.](https://pbs.twimg.com/media/FMxaRI1XIAElFMB?format=jpg&name=medium)

**Comment by HerminaC** [comment]
Thanks @jonathantneal - thanks for the feedback - we'll implement the background as per your suggestion and we'll also center the letter. Should make them more easily identifiable.
