### ISSUE TITLE
BCD tables double titles

### ISSUE THREAD

**Issue by Rumyra** [mdn/yari#5371]
If you hover over a tick icon in a bcd table it says either 'Released ...' or 'Full Support'. This is because the `td` and `span` both have titles - so you get released only if you're not hovering over the icon itself and just in the table cell - because the cell is so small it just appears that it's inconsistent.

**Comment by caugner** [comment]
Reproduced here, for instance: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter#browser_compatibility

**Comment by Zannick** [comment]
This makes the discovery of the support date unintuitive. I came here to report this and to suggest adding the date to the history/notes section so it is not **only** available on hover, especially as there's lots of space in that section.

![Screenshot 2022-03-05 111218](https://user-images.githubusercontent.com/518709/156896988-27ec4fab-e9d2-4a57-a19e-3a6178955f1d.jpg)
