### ISSUE TITLE
Font-size on the front page is too small

### ISSUE THREAD

**Issue by padenot** [mdn/yari#5372]
16px is generally recommended size, and it's what other MDN pages that I just looked at have.

It's 13px on the front page, and it's too small to be legible.

**Comment by HerminaC** [comment]
We could try a couple of options:
1. The Body LG style:
<img width="339" alt="Screen Shot 2022-03-02 at 9 40 01 AM" src="https://user-images.githubusercontent.com/7406447/156445101-2402dc6b-15d7-4f58-bbe2-77ddc4ea302c.png">
or:
2. The Body MD style:
<img width="330" alt="Screen Shot 2022-03-02 at 9 39 25 AM" src="https://user-images.githubusercontent.com/7406447/156445107-804d7527-cec0-4248-a724-06930ffe7aa7.png">

**Comment by schalkneethling** [comment]
Hey @padenot, we are trialing some improvements to the readability and accessibility of MDN Web Docs and we want your input. Please join in the discussion here: https://github.com/mdn/yari/discussions/5715
