### ISSUE TITLE
Dark mode toggle should be 3-state instead of 2-state

### ISSUE THREAD

**Issue by cheeaun** [mdn/yari#5373]
Current redesign looks like this:

<img width="148" alt="Screenshot 2022-03-02 at 12 54 17 AM" src="https://user-images.githubusercontent.com/2296/156214303-6199db21-a04c-43a2-a262-17184968dfdf.png">

It's a 2-state toggle. But it _should_ be **3-state**, one extra state for **"system/auto"**.

Here's an article for explanation: [Three-State Light/Dark Theme Switch](https://tpiros.dev/blog/three-state-light-dark-theme-switch/).

- On **MacOS**, there are 3 states:
  <img width="429" alt="Screenshot 2022-03-02 at 1 05 02 AM" src="https://user-images.githubusercontent.com/2296/156214827-6385bfd4-2ceb-478b-bc81-ab711cd176a8.png">
- On **StackOverflow**, there are 3 states:
  <img width="643" alt="Screenshot 2022-03-02 at 1 06 00 AM" src="https://user-images.githubusercontent.com/2296/156215080-654940b9-14e0-45e3-a9e3-baa42092413c.png">
- On **GitHub**, there's a "Sync with system" theme mode:
  <img width="810" alt="Screenshot 2022-03-02 at 1 06 32 AM" src="https://user-images.githubusercontent.com/2296/156215154-741ea8b6-2aad-4914-ac61-2cfed9ee6bab.png">

**Comment by schalkneethling** [comment]
> It's a 2-state toggle. But it _should_ be **3-state**, one extra state for **"system/auto"**.

We actually do fallback to @prefers-color-scheme if you did not make an explicit choice using the selector. Saying that though, we might want to consider adding a clear option or, as you suggested here, adding the option to choose the syncing with the system.
