### ISSUE TITLE
Bug: Paragraphs have too much line height

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [mdn/yari#5377]
# Summary

In the redesigned MDN docs, it's difficult to distinguish paragraphs from other surrounding text (and from each other).

## Where did you spot the bug?

A good content-heavy page: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images

![image](https://user-images.githubusercontent.com/19352442/156222436-b2e423ec-3487-4371-a09d-defa5773e8e9.png)

## What is the problem?

The paragraphs have too much line height compared to the spacing between them, making them visually blend into each other.

## What did you expect to happen?

The paragraphs should use a line height that improves readability and makes it easier for readers to distinguish paragraphs from each other. From testing, the following values seem to work well:

- Line height: `1.8`
- Paragraph spacing: `1.8rem 0`

Example:

![image](https://user-images.githubusercontent.com/19352442/156222708-b2432000-8a25-4f69-9a65-b656ca30cdc1.png)

## Steps to reproduce the issue

1. Visit any page in the new docs.
2. Observe that too much line height is being used for text.

## Environment

Any (N/A)

### Device

- [x] Desktop
- [x] Mobile
- [x] Tablet

### Browser

Any

### Operating system

Any

**Comment by jjspace** [comment]
I'll throw out that the previous design used 1.5 for most body text and applying that to the new design still looks pretty good.

```css
p, .notecard p {
  line-height: 1.5;
}
:root {
  --type-article-p: 400 1rem/1.5 var(--font-body);
}
```

**Comment by schalkneethling** [comment]
Hey @AleksandrHovhannisyan, how do you find the update as shown below?

![Screenshot of new paragraph typography style](https://user-images.githubusercontent.com/10350960/159331049-2e95402e-77c9-4292-ae2b-8e4181a56e96.png)

**Comment by AleksandrHovhannisyan** [comment]
@schalkneethling That line height is definitely looking better! I might bring the paragraphs just a little closer together and maybe also tighten the line height just a bit more (unless it gets too cramped).

**Comment by schalkneethling** [comment]
Thank you for the feedback @AleksandrHovhannisyan. I am following the WCAG guidelines here so, line-height is 1.5x the font size and the space between paragraphs is 2x the font size. I will let you know as soon as you can browse the site with these changes. Perhaps the experience will be different when it is not a static screenshot 😄

**Comment by AleksandrHovhannisyan** [comment]
@schalkneethling I haven't personally seen the `2x` requirement implemented strictly in practice, even on accessibility articles that discuss the requirement 😅 I think a better practice is to set your paragraph spacing to be your line height (give or take). For example, if you use a line height of `1.5`, you could set your paragraph spacing to be `1.5em`. This establishes a vertical rhythm that makes it easier to read the content.

Either way, it may be worth pinging a few a11y experts in this thread to get their opinions since I am not an expert myself.

**Comment by schalkneethling** [comment]
Hey @AleksandrHovhannisyan, we are trialing some improvements to the readability and accessibility of MDN Web Docs and we want your input. Please join in the discussion here: https://github.com/mdn/yari/discussions/5715

**Comment by schalkneethling** [comment]
@AleksandrHovhannisyan for sure. I do experiment some by bumping it up and down. It is such a tricky thing to get to a place where everyone is happy. A lot of it is also a matter of personal taste. This is essentially why I wanted to open this up to more people. That way it is not just what I find readable.

**Comment by AleksandrHovhannisyan** [comment]
@schalkneethling Yup, makes sense!
