### ISSUE TITLE
Code background color poor visibility in light mode

### ISSUE THREAD

**Issue by avidworks** [mdn/yari#5383]
The code-background-inline and code-background-block colors have extremely poor visibility in light mode. WCAG shows only a 1.05:1 contrast ratio. 

Suggesting all occurrences of color #f9f9fb be changed to provide more contrast between UI elements and/or add a 1px border around them. 

For reference, see attached example using Github's background-color #f6f8fa and border color #d0d7de. I think this is a significant improvement without taking away from the design of the site.
![sample](https://user-images.githubusercontent.com/68607953/156230356-235051ac-bc80-4faa-9e95-02d087f6ac70.png)

**Comment by fiji-flo** [comment]
Can you look at https://github.com/mdn/yari/issues/5370 maybe that's enough?

**Comment by avidworks** [comment]
> Can you look at #5370 maybe that's enough?

Honestly I think even just changing the border color on code blocks from transparent to var(--border-primary) is a big improvement.

![image](https://user-images.githubusercontent.com/68607953/156635366-80d3749d-b9d6-4c27-a0b8-eaff0f180a55.png)

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/issues/5370 - @avidworks we are still considering your suggestion as well.
