### ISSUE TITLE
New dark design is striking but dark blue is nearly invisible on black background

### ISSUE THREAD

**Issue by iDave2** [mdn/yari#5387]
MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback

#### What information was incorrect, unhelpful, or incomplete?

New dark design is striking but dark blue is nearly invisible on black background!

#### Specific section or headline?

This combination appears in multiple places, including this page.

#### What did you expect to see?

Text.

#### Did you test this? If so, how?

Just reporting state of my old eyeballs. Something for RFE list if others agree.

In case this bug report is not reporting page I was on, see (for example) top of this page,

https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings

thx.

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/mdn/contribute/feedback`
* MDN URL: https://developer.mozilla.org/en-US/docs/MDN/Contribute/Feedback
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mdn/contribute/feedback/index.md
* Last commit: https://github.com/mdn/content/commit/072ff0c2bdfa29c02861450b6a91ff93f46e2218
* Document last modified: 2022-02-18T09:11:14.000Z

</details>

**Comment by schalkneethling** [comment]
Hey @iDave2, how do you find the contrast in the screenshot below? I am working on making improvements to the readability of MDN. I would appreciate your feedback.

![Screenshot of new dark mode contrast](https://user-images.githubusercontent.com/10350960/159327875-26b6c6ed-0d40-4a10-ab71-bb0d07ca942f.png)

**Comment by iDave2** [comment]
@Shalk, i got an email where you asked how i found <one of my examples>. i do not see your email query here and cannot grok which page you refer to since you clipped page title from your big sample image above. i will guess that whatever i was reporting may already have been fixed. the site looked progressively prettier in the days following dark rollout. i happened to be working on javascript so it was fun to watch. -d

**Comment by schalkneethling** [comment]
@iDave2 it probably referred to this screenshot: https://github.com/mdn/yari/issues/5387#issuecomment-1074180374

So, this is not live, it is a screenshot from my local environment.

**Comment by iDave2** [comment]
Sorry, i see it now, the URL is in my original post,

  https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings

Reviewing, i still see dark blue text ("liga", "tnum", "smcp" in "CSS Demo" example) on nearly black background and will still rate it Quite Bad. it is so bad, you cannot see it! or our eyes are just different. you're the boss, choose wisely.  :)

**Comment by schalkneethling** [comment]
@iDave2, please join in the discussion here: https://github.com/mdn/yari/discussions/5715

**Comment by NiedziolkaMichal** [comment]
This issue was fixed by [#2042](https://github.com/mdn/interactive-examples/pull/2042). Also there is a fix for [overflow-wrap](https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap) mentioned in the second post, by PR [#2067](https://github.com/mdn/interactive-examples/pull/2067).
