### ISSUE TITLE
Poor UX on laptop

### ISSUE THREAD

**Issue by nhrones** [mdn/yari#5393]
# Summary
Fonts too small! text difficult to read!  
A short description of the overall issue.
Very poor User Experience on my laptop!  Font size too small! font color too light!  Very uncomfortable reading experience over all!
## Where did you spot the bug?
Your new Website!  I was a frequent user of the old MDN!  No longer! UX is too uncomfortable

All new MDN pages
## Steps to reproduce the issue

1. Open https://developer.mozilla.org/... in Chrome/Firefox/Safari
2. Click on "..."
3. Type in "..."
4. Press "..."
5. ...

### Device

- [ ] Desktop
- [ ] Mobile: ...
- [x ] Tablet: ...
- [ ] Other: ...

### Browser

- [x ] Chrome: (what version?)
- [ ] Firefox: (what version?)
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [ 10] Windows: (what version?)
- [ ] Mac OS: (what version?)
- [ ] Linux: (what distribution / version?)

**Comment by caugner** [comment]
Hi @nhrones, thanks for taking the time to report this. 👍 

Two questions:
1. Are you seeing the font-size issue anywhere else than on the front page (as reported in #5372)? If so, could you please provide one or two examples?
1. As for the font-color, can you share whether you are using light or dark mode?

**Comment by nhrones** [comment]
I'm sorry to report that the issue was with Chrome.  For some reason chrome had the Zoom level for your URL set to %75.
After correcting that, I'm pleased with  the UX on your site.  I very much enjoy learning from MDN.

**Comment by nhrones** [comment]
I should have informed you when I discovered the cause.  Sorry for any
inconvenience!
