### ISSUE TITLE
FR: Restore hyperlink underline to increase a11y

### ISSUE THREAD

**Issue by jtangelder** [mdn/yari#5394]
# Summary

Hyperlinks are becoming harder to discover in the redesign due to low contrast. Previously, they were underlined. Can this be restored?

## Where did you spot the bug?

Anywhere in the new design, for example at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function

## What is the problem?

Links are hard to discover, reducing the accessibility and discoverabillity of the content.

## What did you expect to happen?

Easy to scan content

**Comment by schalkneethling** [comment]
@jtangelder thank you for filing. This is at the top of my list.

**Comment by caugner** [comment]
Hi @jtangelder, thank you for taking the time to report this. 👋 

I will go ahead and close this in favor of #5445, which has some more context and a screenshot.
