### ISSUE TITLE
Colour contrast is so low, some colours are impossible to see

### ISSUE THREAD

**Issue by spartanatreyu** [mdn/yari#5396]
From the page: <https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog>:

<img width="631" alt="_dialog___The_Dialog_element_-_HTML__HyperText_Markup_Language___MDN" src="https://user-images.githubusercontent.com/3240456/156294985-95a9d086-8716-4cea-9d63-70bb45a5d66b.png">

**Comment by spartanatreyu** [comment]
Related to https://github.com/mdn/yari/issues/5367

**Comment by caugner** [comment]
@spartanatreyu Would you say this is an issue only with the new dark mode feature, or it also a problem with the "traditional" light mode?

**Comment by spartanatreyu** [comment]
I'd say it was definitely a problem with both, but it was much more prevalent in dark mode.

A nice trick when testing light and dark mode accessibility I learned is that you should still be able to read and discern the different colors with your display on its lowest brightness setting.

I can see the updated colours in https://github.com/mdn/yari/pull/5449 and the dark mode blue is the only colour that isn't too hard to see. I'd bring up the other dark mode color's brightnesses to at least the blue's brightness.

**Comment by schalkneethling** [comment]
@spartanatreyu Please see below the update to the background color for the active item in the table of contents.

> NOTE: This is not live yet.

![Screenshot of TOC in dark mode](https://user-images.githubusercontent.com/10350960/159330015-4135f5c2-2d31-4f3c-9bb1-fe97970a7d91.png)

![Screenshot of TOC in dark mode](https://user-images.githubusercontent.com/10350960/159330042-2434ef54-271f-4325-9c6d-ea4f2cf41459.png)

**Comment by schalkneethling** [comment]
And here is the red variant.

![Screenshot of TOC in dark mode with red variant](https://user-images.githubusercontent.com/10350960/159330435-0db14148-5ba7-4cb9-a174-eb8944edf83e.png)

![Screenshot of TOC in dark mode with red variant](https://user-images.githubusercontent.com/10350960/159330516-a38d9b4b-86d6-4277-b2b8-67922fdbadc4.png)

**Comment by spartanatreyu** [comment]
Ooh, those screenshots look much better

:D

**Comment by schalkneethling** [comment]
> Ooh, those screenshots look much better
> 
> :D

Please join in the discussion here: https://github.com/mdn/yari/discussions/5715
