### ISSUE TITLE
Bug: The new look "experimental" icon is broken.

### ISSUE THREAD

**Issue by toritree** [mdn/yari#5397]
# Summary

The new look "experimental" icon is broken.

## Where did you spot the bug?

https://developer.mozilla.org/ja/docs/Web/API/CanvasRenderingContext2D/arc
https://developer.mozilla.org/ja/docs/Web/API#specifications
## Steps to reproduce the issue

1. Open https://developer.mozilla.org/ja/docs/Web/API#specifications... in Chrome/Firefox

## Environment
Firefox 97.0.1
Chrome 98.0.4758.102

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [x] Chrome: (98.0.4758.102)
- [x] Firefox: (97.0.1)
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [x] Windows: (11)
- [ ] Mac OS: (what version?)
- [ ] Linux: (what distribution / version?)

## Screenshots
![Screenshots](https://user-images.githubusercontent.com/65443082/156319104-68509b7f-ff10-4abb-a8fa-a0a7796c793d.png)

**Comment by schalkneethling** [comment]
This one has been resolved. Thank you for reporting @toritree!

![Screenshot of new flask icon. The icon is a much clearer drawing of a flask commonly used in labs](https://user-images.githubusercontent.com/10350960/163876715-96a2b490-7561-49b4-9c09-fbb9f5594ffa.png)
