### ISSUE TITLE
[Design][improvement] Compatibility table to display supported versions without click

### ISSUE THREAD

**Issue by georapbox** [mdn/yari#5398]
One thing I used to find very useful in the compatibility table, was the fact that I could see all the browsers supported versions for a feature at the same time. That gave me a very quick overview of the feature's support across different browsers.

With the redesign, one needs to click on each cell one by one for the version to be revealed and it's not possible to check all at a glance.

Beyond that, the redesign looks beautiful and much cleaner. Kudos for the dark theme! 💪

**Comment by georapbox** [comment]
@caugner Yes, #5353 pretty much covers the same issue, so feel free to close this one as duplicate. Thanks.

**Comment by caugner** [comment]
Thanks, closing this in favor of #5353. :)
