### ISSUE TITLE
Bug: Erratic scroll behavior on left side nav bar. 

### ISSUE THREAD

**Issue by seeker-3** [mdn/yari#5401]
# Summary

If the nav bar on the left is scrollable and you scroll the main content all the way down to the bottom, the side bar starts to behave a bit erratically.

## Where did you spot the bug?

On the JavaScript reference, but it seemed to happen everywhere.

## What is the problem?

Wasn't really a big problem, just wanted to help you guys fix the bugs on the new site if you didn't already know about it. Love the new site!! Good luck!

## What did you expect to happen?

I guess I would expect the scroll bar on the side to stay well scrolling to the bottom of the page.

## Steps to reproduce the issue

1. Go to any docs page.
2. Expand out the content so a scroll bar exists.
3. Scroll the main content down to the footer of the page.
4. Scroll back up again.

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [ ] Chrome: (what version?)
- [ ] Firefox: (what version?)
- [ ] Safari: (what version?)
- [x] Other: (brave / 1.35.104 Chromium: 98.0.4758.109)

### Operating system

- [ ] Windows: (what version?)
- [x] Mac OS: (12.2.1)
- [ ] Linux: (what distribution / version?)

## Screenshots

https://user-images.githubusercontent.com/31900513/156321989-4786cf69-f0c1-4d10-a26e-d2fb41ade071.mov

**Comment by caugner** [comment]
Hi @seeker-3, thank you for taking the time to report this, and kudos for providing a screen cast. Awesome!

I believe this was resolved by #5413 on Wednesday. Could you please verify if the problem persists?

**Comment by seeker-3** [comment]
Seems to work now, awesome!
