### ISSUE TITLE
[Browser compatibility section]: version numbers not visible right away

### ISSUE THREAD

**Issue by carlosjeurissen** [mdn/yari#5403]
In the old design, we used to be able to see the versions which a certain feature is supported. For example:
https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()#browser_compatibility

However, in the new design we first have to click on each browser before the first version of a browser the feature is supported at. My request is to bring this back. Either as replacement for the "check" or display it below the check mark.

**Comment by jjspace** [comment]
Same as #5353 and #5366 (which seems to have the most traction)

**Comment by caugner** [comment]
Closing this in favor of #5366, thanks! 👍
