### ISSUE TITLE
Content bug: Resetting interactive JS applet reverts applet display style to light mode, Firefox Desktop

### ISSUE THREAD

**Issue by SandyClams** [mdn/yari#5405]
I've checked a few pages to confirm it's consistent behavior. Example page: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach. When clicking the "Reset" button in the "JavaScript Demo" applet in dark mode, the entire applet reverts to light mode style with no style changes outside the immediate applet. The change persists across page loads; i.e. the next loaded page will also have a light mode applet. Manually toggling the light/dark mode controls for the site fixes the applet state. I've only tested this on a recent desktop Firefox so I can't speak to how the site behaves outside that environment.

**Comment by schalkneethling** [comment]
@SandyClams this has been resolved. Can you please confirm? Thanks!

**Comment by SandyClams** [comment]
@schalkneethling it no longer reverts to light mode in any of my testing. The applet does, however, flash to light mode for a brief instant on some occasions when pressing the Reset button in dark mode. Not sure if that issue would even be addressable or not

**Comment by schalkneethling** [comment]
Thanks you for confirming. I will open a separate issue for the flash.
