### ISSUE TITLE
Bug: Copy to clipboard icon is barely visible in dark mode

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5414]
# Summary

From Twitter:
https://twitter.com/ivanitomasz/status/1498662267415678976/photo/1

## Where did you spot the bug?

All reference pages

## What is the problem?

![Screenshot showing barely visible clipboard icon](https://user-images.githubusercontent.com/10350960/156362676-33e8aaf3-797f-48ca-9763-07b79467676e.png)

## What did you expect to happen?

Clipboard icon is clearly visible in dark mode

**Comment by AnilSeervi** [comment]
Can I work on this?

**Comment by schalkneethling** [comment]
> Can I work on this?

Hey @AnilSeervi! Thanks so much for your interest. I already grabbed this one and neglected to assign it to myself. Perhaps there is another issue you are interested in working on?

**Comment by AnilSeervi** [comment]
I had an easier way of fixing this issue without changing the URL of the clipboard image.

**Comment by AnilSeervi** [comment]
I've created #5536 as a fix for this issue, @schalkneethling can you have a look at it?

**Comment by caugner** [comment]
Fixed via #5504.
