### ISSUE TITLE
BCD table shows "Full support" title for support with flags

### ISSUE THREAD

**Issue by rniemela77** [mdn/yari#5429]
## Where did you spot the bug?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu#browser_compatibility

## What is the problem?

When hovering over a table cell with both the flag and (x) icons, the icons and tooltips do not match.

## Screenshots
![image](https://user-images.githubusercontent.com/84466763/156455322-5e0ccee8-9340-4cee-906f-e2743ca21487.png)

**Comment by caugner** [comment]
Related: #5371

**Comment by caugner** [comment]
After changing the title of this issue and looking at the [pre-redesign version of this article](https://web.archive.org/web/20210301171223/https://developer.mozilla.org/en-US/docs/Web/HTML/Element/menu), I realized that the bug might actually be that we see the "No support" icon, when in fact the feature _is_ fully supported, just behind a feature flag.
