### ISSUE TITLE
Regression: Missing links are no longer highlighted properly

### ISSUE THREAD

**Issue by jjspace** [mdn/yari#5430]
# Summary

The theme color for links is currently overriding the error color for links that don't have a destination. This is doubly true for any links that also have a `code` block inside them.

## Where did you spot the bug?

https://developer.mozilla.org/en-US/docs/Web/API/FileReader#event_handlers

The last three should have red text, or at least text of a different color showing that the link deistinations don't exist. 

![2022-03-02_18-04](https://user-images.githubusercontent.com/8007967/156464895-a92bc068-3096-4f0b-baa5-6a4ebbf687c8.png)

"Fixed" version

![2022-03-02_18-08](https://user-images.githubusercontent.com/8007967/156464966-a3a3ffc9-f93d-4a4b-bcd9-3ddbfe50c02c.png)

## What is the problem?

There's no way to tell if a link exists or not until you hover and try to click it.

(this is even more of an issue on the HTML doc pages because the theme color is already red but that's been discussed in #5367)

## What did you expect to happen?

These links should be highlighted like they used to be. It seems like the CSS is still there to support it but the cascading/specificity of the CSS is overwriting it. Even if you fix the first issue I also noticed that `code` blocks inside `.page-not-created` links once again force the theme color.

I fixed this by adding:

```css
a.page-not-created {
  color: var(--icon-critical) !important;
}
a.page-not-created code {
  color: var(--icon-critical);
}
```

![2022-03-02_18-05](https://user-images.githubusercontent.com/8007967/156465102-c455b360-777e-4fb1-830d-082403a56012.png)

**Comment by danielhjacobs** [comment]
I tested the link to the accessibility project: https://5546.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/SVGElement. Dead links in the sidebar are still the same color as all other links until hovered over.

Perhaps the CSS rule should be:

```
a.page-not-created code {
	color: var(--icon-critical);
	text-decoration-style: wavy;
	text-decoration-line: underline;
}
```

**Comment by danielhjacobs** [comment]
The current rules, `.about-container a:link, .about-container a:visited, .main-page-content a:link, .main-page-content a:visited` and `a.page-not-created:focus, a.page-not-created:hover, a.page-not-created:link`, don't work because those a tags don't have hrefs, so they are not considered links.
