### ISSUE TITLE
Bug: Embedded iframe styling issues in dark mode

### ISSUE THREAD

**Issue by cherrol** [mdn/yari#5436]
It is recommended to set the iframe background color to white to keep access in dark mode.

**Comment by caugner** [comment]
Hi @cherrol, thank you for taking the time to report this. 👋 

Would you mind verifying if #5428 covers the issue you're having?

**Comment by cherrol** [comment]
> 嗨@cherrol，感谢您抽出宝贵时间报告此问题。👋
> 
> 您介意验证#5428是否涵盖您遇到的问题吗？

Looks like the same problem
