### ISSUE TITLE
Bug: the TOC is overlapping page content

### ISSUE THREAD

**Issue by B2D1** [mdn/yari#5457]
# Summary

UI Problem, the TOC is overlapping page content

## Where did you spot the bug?

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Meta_programming#handlers_and_traps

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [x] Chrome: (98)
- [ ] Firefox: (what version?)
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [ ] Windows: (what version?)
- [x] Mac OS: (11.6)
- [ ] Linux: (what distribution / version?)

## Screenshots

<img width="594" alt="image" src="https://user-images.githubusercontent.com/36991862/156695402-334c6e5c-d4ea-4c2b-bb96-c9a3c0d6fd82.png">

**Comment by caugner** [comment]
Hi @B2D1, thank you for taking the time to report this issue. 👋 

We're aware of it and are tracking it in #5349.
