### ISSUE TITLE
adjustable bug / React Developer Tools

### ISSUE THREAD

**Issue by zhaogongchengsi** [mdn/yari#5459]
Your site can use React Developer Tools may have security issues

**Comment by caugner** [comment]
Hi @zhaogongchengsi, thank you for taking the time to report this issue. 👋 

If I understand you correctly, you're saying that the "React Developer Tools can be used on https://developer.mozilla.org/ and that this poses a potential security issue. I just verified and couldn't reproduce this.

Could you please provide a URL and a screenshot to help us understand the problem? Thanks! 🙏

**Comment by zhaogongchengsi** [comment]
![mdn](https://user-images.githubusercontent.com/64842422/157150137-bf6d2baa-5529-4164-b68b-bfedf150dd9e.png)
This is it

**Comment by schalkneethling** [comment]
@zhaogongchengsi We will have a look at this but, the fact that you can edit something in the React developer tools does not affect anyone else but yourself so, this should not be a concern. I will do due diligence though just to be sure. Thank you for raising the issue with us.

**Comment by caugner** [comment]
I just looked into this again.

Chrome DevTools does in fact show the React Developer Tools' "Components" and "Profiler" tabs even for production sites. However, it doesn't allow editing any of the state, and even if this was possible, wouldn't be a security concern. As Schalk already pointed out correctly, the state is local to each individual user and doesn't persist between reloads.

Therefore I'm going ahead and closing this as "won't fix".
