### ISSUE TITLE
Suggestion: Add browser icons to compatibility table

### ISSUE THREAD

**Issue by eymeen** [mdn/yari#5460]
# Summary

As a UI/UX designer, I see it's better to put browser icon on browser compatibility, and colors, green and red  
because no one wants to read to see if the code works in the specific browser or not 
![image](https://user-images.githubusercontent.com/75482336/156736216-3c81481e-4724-46a2-8484-6128ab40993a.png)

**Comment by schalkneethling** [comment]
Hey at @eymeen. Thank you for your feedback, we addressed some of this in the pull request: https://github.com/mdn/yari/pull/5458

**Comment by Ugzuzg** [comment]
Vertical text is very hard to read. Icons helped with finding the right column before:
![image](https://user-images.githubusercontent.com/1078004/158429553-fcc7ba7e-c7d2-4ba2-a7d3-0e74777efcbd.png)

Now it's a lot harder to find the right column at a glance.
