### ISSUE TITLE
New BCD timeline view is possibly confusing to some users

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5462]
> <img alt="Screenshot_2022-03-03 15 45 17" width="345" src="https://user-images.githubusercontent.com/25517624/156649980-9dd8bf26-c25b-4d58-858f-3f87848bd267.png">

The old version looked like this:

![image](https://user-images.githubusercontent.com/1330321/156723692-8ad59274-b2e7-40a2-8c6d-836272f7f0ae.png)

They have same data, but the new view displays them in a confusing way.

"Removed in 15 and later", "Partial support", "Only supported the deprecated callback syntax." are notes of the old implementation in Safari 7~15, but now it's separated.

Secondly, I don't know how multiple entries in BCD are sorted, but I naturally expects top to bottom as time goes.

_Originally posted by @yume-chan in https://github.com/mdn/yari/issues/5366#issuecomment-1058930440_

**Comment by stof** [comment]
I totally agree with this. when looking at the timeline for the support of `<dialog>` in Firefox, it looks like the `full support` message relates to the range between versions 53 and 98, while this is the range where `Support behind a flag` applies: ![image](https://user-images.githubusercontent.com/439401/158360598-5795ee03-bab2-4655-82c1-07557e5287d6.png)

The timeline should be rendered in a logical order. Here is how it would look like by changing the order of items (through devtools): 
![image](https://user-images.githubusercontent.com/439401/158361450-dedec8f4-d041-4c41-9681-703729adabd2.png)
This is a lot easier to understand.

**Comment by caugner** [comment]
I agree with the proposed solution of showing the timeline in chronological order.

@stof Would you be interested in a submitting a PR for this change?
