### ISSUE TITLE
Bug: Syntax highlighting is too dark in dark mode

### ISSUE THREAD

**Issue by intrnl** [mdn/yari#5468]
# Summary

Syntax highlighting in dark mode is too dark

## Where did you spot the bug?

Any articles involving code.
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Fetching_data

### Device

- [x] Desktop
- [x] Mobile: Poco M3
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [x] Chrome: 101.0.4919.0 (Official Build) dev (64-bit) 
- [x] Firefox: 99.0a1 nightly
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [ ] Windows: (what version?)
- [ ] Mac OS: (what version?)
- [x] Linux: Arch Linux, Liquorix Kernel 5.16.12-lqx1-1-lqx

## Screenshots

![image](https://user-images.githubusercontent.com/20620901/156763558-711ec113-4b0a-4320-b485-fe80800d5780.png)

green `#39a038` 41.42%
red `#ed3966` 36.62%
gray `#8f8f9d` 43.06%
light blue `#74a9f6` 56.17%

green is too dark, red and gray can probably be a little lighter, light blue is fine

**Comment by caugner** [comment]
Good news, this has been fixed, probably as part of https://github.com/mdn/yari/pull/5710:

<img width="824" alt="image" src="https://user-images.githubusercontent.com/495429/201939814-b90672a8-e70e-4da3-834a-9db688261091.png">
