### ISSUE TITLE
Bug: Code box is set to light mode when clicking on "Reset" in dark mode 

### ISSUE THREAD

**Issue by nikitakhutorni** [mdn/yari#5470]
# Summary

When dark mode is active and "Reset" in a code box is clicked, the theme of the code box is set to white. 

## Where did you spot the bug?
Any page with a code box.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse

## What is the problem?
Box switches theme to light.

## What did you expect to happen?
Box theme has to stay in dark mode.

## Steps to reproduce the issue

1. Open https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/parse in Brave
2.  Activate dark mode.
3. Click on "Reset"

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [ ] Chrome: (what version?)
- [ ] Firefox: (what version?)
- [ ] Safari: (what version?)
- [x] Other: Brave 1:1.32.106-1

### Operating system

- [ ] Windows: (what version?)
- [ ] Mac OS: (what version?)
- [x] Linux: Arch, Kernel: 5.16.8-arch-1-1

## Screenshots

https://user-images.githubusercontent.com/55978518/156777113-bf078d86-9b10-4c23-ad3c-d724e3275cdf.mp4

**Comment by caugner** [comment]
Hi @nikitakhutorni, thank you for taking the time to report this! 👋 

We're aware of this issue and are already tracking this issue in #5428 (the "Reset" button is just reloading the example), so I will close this issue in favor of that one.
