### ISSUE TITLE
Bug: H2 "Overview" heading is not rendered

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#5476]
This is part of https://github.com/mdn/content/issues/13505.

The page at https://developer.mozilla.org/en-US/docs/Web/API/Navigator/Online_and_offline_events has an "Overview" listed in the ToC, but when we click it nothing happens.

The document source does contain an H2#Overview: https://github.com/mdn/content/blob/d3953594fd4328553ed3e27dbb73c0c71671b08c/files/en-us/web/api/navigator/online_and_offline_events/index.md?plain=1#L15 , but it's not appearing in the rendered page.

Testing it a bit: this only happens in the redesign, and only when the element is H2 or H3 with the text "Overview".

**Comment by caugner** [comment]
FWIW I can see the same issue with the old design: https://web.archive.org/web/20220215062310/https://developer.mozilla.org/en-US/docs/Web/API/Navigator/Online_and_offline_events#overview

**Comment by wbamberg** [comment]
Oh, thanks! I'm not seeing it when running `yarn start` from mdn/content, which made me think it was the redesign. But it's obviously not...

BTW now I see that code, I think this behavior is a hangover from the original conception of Yari, which was to render a structured-content version of MDN (in which among other things authors could signal sections of the content that didn't want rendered headings by calling them things like  "Overview") that never happened. So it should be removed.

**Comment by caugner** [comment]
Thanks for the context!

So it should like this:

![image](https://user-images.githubusercontent.com/495429/156830171-3269f618-ecbc-4ec7-987e-cc4dfc3fcd96.png)

I will see if I find an `short_description` as well.

**Comment by schalkneethling** [comment]
> It doesn't look like `short_description` was used anywhere

I wonder if there is a plan to use this in the future. For example, we also want to set a `short_title` in the frontmatter instead of "faking" some of them as we currently do.
