### ISSUE TITLE
Bug: Pocket doesn't accurately pick up MDN

### ISSUE THREAD

**Issue by ElijahPepe** [mdn/yari#5483]
# Summary

From Reddit: https://www.reddit.com/r/firefox/comments/t6f900/mdn_and_pocket_do_not_work_well_together/

When using Pocket with MDN, only `div`s with class names are displayed. `div`s that contain content should have a class name to combat this (i.e. ".content").

## Where did you spot the bug?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

## What is the problem?
The content when using Pocket with MDN is very wonky.

## What did you expect to happen?
The content should display as it appears on the normal site.

## Steps to reproduce the issue
1. Use Pocket with MDN.
2. Observe.

### Device

- [X] Desktop
- [ ] Mobile
- [ ] Tablet
- [ ] Other

### Browser

- [ ] Chrome
- [X] Firefox: 90.0.2/97.0.1
- [ ] Safari
- [ ] Other

### Operating system

- [X] Windows: 11
- [ ] Mac OS
- [X] Linux: Arch Linux

## Screenshots

![image](https://user-images.githubusercontent.com/29153977/156852583-52d552bd-5804-4158-aba0-6bc5f26fcaa3.png)

**Comment by caugner** [comment]
I got the feedback from the Pocket team that the parsing rules from MDN have recently been adjusted, and so the page is now parsed correctly, which I just verified:

<img width="736" alt="image" src="https://user-images.githubusercontent.com/495429/204578431-55115b4d-3872-431a-aa29-bfaf7c5f1ff4.png">
