### ISSUE TITLE
Bug: Missing Mozilla articles + tags without redirects to current content

### ISSUE THREAD

**Issue by Gitoffthelawn** [mdn/yari#5484]
# Summary

Quite a few of my bookmarks and blog links to MDN pages no longer work, and MDN isn't redirecting to current content on those topics.

## Where did you spot the bug?

https://developer.mozilla.org/docs/Mozilla/Command_Line_Options
https://developer.mozilla.org/docs/Mozilla/Developer_guide/Source_Code/Directory_structure
https://developer.mozilla.org/docs/Mozilla/Firefox/Performance_best_practices_for_Firefox_fe_engineers
https://developer.mozilla.org/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler
https://developer.mozilla.org/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences
https://developer.mozilla.org/docs/Mozilla/Preferences/Mozilla_networking_preferences
https://developer.mozilla.org/docs/Mozilla/Preferences/Preference_reference
https://developer.mozilla.org/docs/Mozilla/Tech/Places/Frecency_algorithm
https://developer.mozilla.org/docs/tag/Preferences

## What is the problem?

Content has been moved or removed without redirection to current content (or explanation of where to find current information on the specific topics).

## What did you expect to happen?

Be redirected to current content.

## Steps to reproduce the issue

Try to go to any of the above URLs.

## Environment

All

### Device

All

### Browser

- [x] Firefox: 97.0.1

### Operating system

All

**Comment by caugner** [comment]
As for the Mozilla documentation, this has been moved off MDN, see: https://github.com/mdn/content/issues/10928#issuecomment-985085551

As for the tags, I believe those have been removed as well, but I will check into that next week.

**Comment by Gitoffthelawn** [comment]
@caugner Thanks Claas.  Where did the Firefox team put all the documents that were removed from MDN?  Is there a time-efficient method to find all the previously bookmarked/linked references, such as the ones listed above?

**Comment by caugner** [comment]
@Gitoffthelawn I don't know, but I did a quick DuckDuckGo search and seem to have found the first document here: https://wiki.mozilla.org/Firefox/CommandLineOptions

Feel free to post a mapping of URLs you found that correspond to the old ones you posted. This would help others in your position (I'm sure I have some of those bookmarked myself in Pocket). 

Afaik we add redirects only if we see a significant number of 404s for a particular URL.

**Comment by Gitoffthelawn** [comment]
@caugnew Thank you Claas!  Much appreciated.

**Comment by ddbeck** [comment]
I've created [a PR to redirect, where possible, these URLs to places where these docs appear to be maintained](https://github.com/mdn/content/pull/14269), specifically:

source | dest
-- | --
https://developer.mozilla.org/docs/Mozilla/Command_Line_Options | https://wiki.mozilla.org/Firefox/CommandLineOptions
https://developer.mozilla.org/docs/Mozilla/Developer_guide/Source_Code/Directory_structure | https://firefox-source-docs.mozilla.org/contributing/directory_structure.html
https://developer.mozilla.org/docs/Mozilla/Firefox/Performance_best_practices_for_Firefox_fe_engineers | https://firefox-source-docs.mozilla.org/performance/bestpractices.html
https://developer.mozilla.org/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler | https://firefox-source-docs.mozilla.org/devtools-user/performance/index.html

The remaining MDN URLs don't appear to be maintained elsewhere. In those cases, I think 404-ing is the correct approach, unfortunately.

Once https://github.com/mdn/content/pull/14269 has landed, I think we ought to close this issue. Thank you!

**Comment by Gitoffthelawn** [comment]
@ddbeck Thank you Daniel!  That will be a big improvement and save people much time.

Regarding 404ing the other links... I'm rarely a big fan of issuing 404s when they can be prevented.  A few off-the-cuff possibilities:

1. Determine why some good reference materials are no longer available, and make them available again.  Another opportunity to use semicolons! :)  (a reference to your humorous profile that gave me a good chuckle... thanks for the smile!)
2. If the above is not possible, provide a link to https://github.com/mdn/archived-content
3. If neither of the above are possible, provide a link to the content via the Wayback Machine (archive.org).

**Comment by Gitoffthelawn** [comment]
@ddbeck Thank you Daniel. I wish you the best in your new endeavors.
