### ISSUE TITLE
Bug: Cannot copy code from JavaScript demo boxes

### ISSUE THREAD

**Issue by jamesWalker55** [mdn/yari#5489]
# Summary

When copying from a code demo box, the copied contents is mixed with line numbers.

[For this page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create), after copying from the JavaScript demo box, the clipboard content is replaced with this:

```
const person = {

2

  isHuman: false,

3

  printIntroduction: function() {

4

    console.log(`My name is ${this.name}. Am I human? ${this.isHuman}`);

5

  }

6

};

7

​

8

const me = Object.create(person);

9

​

10

me.name = 'Matthew'; // "name" is a property set on "me", but not on "person"

11

me.isHuman = true; // inherited properties can be overwritten

12

​

13

me.printIntroduction();

14

// expected output: "My name is Matthew. Am I human? true"

15

​
```

## Where did you spot the bug?

All pages that have a JavaScript demo box, like [this one](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create).

## Steps to reproduce the issue

1. Go to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create
2. Select text in the demo box with your mouse
3. Hit Ctrl+C
4. Paste the content anywhere else

### Device

- [X] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [ ] Chrome: (what version?)
- [X] Firefox: 97.0.1
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [X] Windows: Windows 10
- [ ] Mac OS: (what version?)
- [ ] Linux: (what distribution / version?)

**Comment by caugner** [comment]
I tried to reproduce the issue as follows:

1. Open https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create
2. Focus the interactive example code editor.
3. Press `CTRL` + `A` to select the code.
4. Press `CTRL` + `C` to copy the selection.
5. Paste the clipboard in an editor like Visual Studio Code or gedit.

For me, the code was copied and pasted as expected, i.e. *without* the line numbers and *without* the additional spacing that you are reporting.

@jamesWalker55 Could you please try it again with the same environment and, if possible, with another browser or another device? If you can reproduce it consistently, a screen cast would be very helpful.

**Comment by jamesWalker55** [comment]
It is consistently reproducable in my environment, here is a screen recording: https://streamable.com/ptf5o9

**Comment by jamesWalker55** [comment]
I discovered that this is caused by a conflict with an extension that enables "absolute right click & copy", essentially disabling JavaScript callbacks for text copying.

I've excluded the extension for this URL: `https://interactive-examples.mdn.mozilla.net/*`, after that copying works as expected.
