### ISSUE TITLE
Bug: Slash no longer opens the search

### ISSUE THREAD

**Issue by detj** [mdn/yari#5490]
Last year, MDN had introduced an autocomplete search on all of its pages. Peter had written a [delightful post](https://hacks.mozilla.org/2021/08/mdns-autocomplete-search/) on it. It allowed MDN users to quickly jump between several documentation pages really quickly. A rather cool thing about it was, throughout the website, users could focus the search input field by pressing the `/` key. This in my opinion improved the user experience for users like me. And I'm sure many other developers.

Since, [the launch of the redesign](https://hacks.mozilla.org/2022/03/a-new-year-a-new-mdn/), I noticed that this keyboard shortcut interaction is no longer working. **Any plans to re-introduce it in the newer website?**

Btw, the newly redesigned website looks amazing & is fast. ❤️  it!

**Comment by schalkneethling** [comment]
Part of https://github.com/mdn/yari/pull/5507

**Comment by caugner** [comment]
Good news!

@schalkneethling has resolved this issue via #5507, so the slash now opens the search again. 🎉
