### ISSUE TITLE
Bug: Live samples don't support dark mode

### ISSUE THREAD

**Issue by caugner** [mdn/yari#5491]
# Summary

Previously, some **live samples** (which are not the same as **interactive examples**) were displayed with *dark* color on *dark* background in dark mode, rendering the samples unreadable.

@NiedziolkaMichal partly fixed this in https://github.com/mdn/translated-content/pull/4401, so that these live samples look the same in light and dark mode, i.e. dark color light background.

Now, we "just" need to add dark-mode support for live samples in yari, which seemed to have been missed in the redesign:

https://github.com/mdn/yari/blob/0f206cee92975b9e73f1cb8518528e8857d2a5fd/kumascript/src/live-sample.js#L23-L32

## Where did you spot the bug?

- https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align
- https://developer.mozilla.org/de/docs/Web/CSS/vertical-align

## What is the problem?

Live samples have dark color on light background, even in dark mode.

## What did you expect to happen?

Live samples should have light color on dark background in dark mode.

## Steps to reproduce the issue

1. Go to https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align
2. Enable dark mode.
3. Go to the "[Vertical alignment in a line box](https://developer.mozilla.org/en-US/docs/Web/CSS/vertical-align#vertical_alignment_in_a_line_box)" section
4. Notice the live samples above/below with white background

### Device

- [x] Desktop

### Browser

- [x] Firefox: 97

### Operating system

- [x] Linux: NixOS

## Screenshots

![image](https://user-images.githubusercontent.com/495429/156901084-a86e8bcd-e9cf-4eae-92ce-7c3d2df214c3.png)

![image](https://user-images.githubusercontent.com/495429/156901086-2edc0c10-ae83-46b9-8e71-f9e32cfd8fa4.png)

**Comment by NiedziolkaMichal** [comment]
I believe it should be handled just like interactive examples, by switching background, text color & font. When this is done, examples with unreadable text should be individually resolved.
This can be done by switching background from #fff to var(--background-secondary) in iframe scss, then switching text in live-sample.js by including editor-css.css in iframe and setting body class to either theme-light or theme-dark.
That's expected result in [most cases](https://developer.mozilla.org/en-US/docs/Web/CSS/column-count#frame_splitting_a_paragraph_across_three_columns):
![image](https://user-images.githubusercontent.com/100634371/156902892-23ca9522-e185-4d4c-a61c-2d76d0737e27.png)

Then there are 16 cases where playable-code class is used, like [Audio and Video Manipulation](https://developer.mozilla.org/en-US/docs/Web/Guide/Audio_and_video_manipulation#frame_editable_example), background-color & text-color should be switched for it too.

![image](https://user-images.githubusercontent.com/100634371/156903047-62938499-af38-4f27-a5d6-0137724e4d6e.png)

After that there are individual cases like [Getting Started](https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Getting_started#frame_active_learning_creating_your_first_html_element), which override background-color or text-color settings.

**Comment by caugner** [comment]
I just noticed that this also prominently affects the [`<input>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#input_types) article.

Unfortunately, this is a known issue, but for which we don't have a trivial fix at hand:
https://github.com/mdn/yari/blob/c5c85597fd04f2ab1547b51d7f109c909269e151/client/src/document/index.scss#L312-L327

(Original discussion happened in an [internal issue](https://github.com/mdn/yari-private/issues/370#issuecomment-1015624144).)

@schalkneethling Do you happen to to know if we have a plan on how to address this?

**Comment by schalkneethling** [comment]
> @schalkneethling Do you happen to to know if we have a plan on how to address this?

Thanks for the ping, I will have a look at these. This is, as you mentioned, part of a larger problem that needs solving. Perhaps there is a way to at least improve this now while we resolve the larger problem.

**Comment by mirunacurtean** [comment]
@caugner This seems improved for live samples
![image](https://github.com/mdn/yari/assets/53306802/e26410fb-5c16-46fc-ba6f-07579db968fb)

Even if not for demos
![image](https://github.com/mdn/yari/assets/53306802/ba333d4f-8eb7-481b-b185-69bed234e42a)

**Comment by caugner** [comment]
> This seems improved for live samples

To me, it looks like a (positive?) side-effect of the migration to Playground. You could argue that the white background for the live samples (and the Playground preview) is a regression.

@fiji-flo Did we intentionally make the live samples and Playground preview background white in dark mode?

**Comment by fiji-flo** [comment]
Yes, we intentionally use a white background as some of them don't work on dark background. Ultimately a question if we want to support this, this would ad complexity for both, the system and the writers.

**Comment by caugner** [comment]
Thanks @fiji-flo, so I'm closing this as "won't fix". 👍
