### ISSUE TITLE
Bug: Formal Syntax link doesn't match identifier

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/yari#5492]
# Summary
Formal Syntax links don't match actual identifiers of operators that they are refering to.

## Where did you spot the bug?
[margin](https://developer.mozilla.org/en-US/docs/Web/CSS/Margin#formal_syntax)

## What is the problem?
When I click on curly bracket, it refers me to [value definition syntax page](https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#curly_braces), but with incorrect URL fragment. Link in margin redirects to "curly_braces", while id of that operator header is "curly_braces_". Because ids are different, I am redirected to top of the page rather than description of that particular element.

## Steps to reproduce the issue
1. Open https://developer.mozilla.org/en-US/docs/Web/CSS/Margin#formal_syntax
2. Click on curly bracket

## Cause of the problem
In yari CSSSyntax.ejs indentifier, is set in line 238: '"en-US": "Curly_braces"', together with title shown on link hover.
In content value_definition_syntax\index.md we have defined header '### Curly braces (`{ }`)'. It looks like this name creates indentifier 'curly_craces_' instead of 'curly braces'.

There are two obvious solutions to this problem. We can change '"en-US": "Curly_braces"' to '"en-US": "Curly_braces_"', in CSSSyntax.ejs or we can change header '### Curly braces (`{ }`)' to '### Curly braces(`{ }`)'. I can see that CSSSyntax.ejs has plenty of links aware of this problem, like "Geschweifte_Klammern_(_)", "Fragezeichen_()", "Rautensymbol_()". I think it would be better to make universal solution instead, by changing algorithm that creates those indentifiers, so problem can be fixed globally.

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [x] Chrome: (98)
- [ ] Firefox: (what version?)
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [x] Windows: (what version?)
- [ ] Mac OS: (what version?)
- [ ] Linux: (what distribution / version?)

**Comment by caugner** [comment]
The corresponding section in mdn/content is calling the `CSSSyntax` here:
https://github.com/mdn/content/blob/3443b2d1b3b50d56ec0b309586488a9059e3c4ee/files/en-us/web/css/margin/index.md?plain=1#L85-L87

So I believe this is an issue within that macro, which is defined here: https://github.com/mdn/yari/blob/main/kumascript/macros/CSSSyntax.ejs

**Comment by caugner** [comment]
The problem here is that we have link from the `CSSSyntax` macro to https://developer.mozilla.org/en-US/docs/Web/CSS/Value_definition_syntax#curly_braces, but the targeted heading has a trailing `_` in its id:

```html
<h3 id="curly_braces_"><a href="#curly_braces_" title="Permalink to Curly braces ({ })">Curly braces (<code>{ }</code>)</a></h3>
```

I agree with the OP's proposed solution to update the header id generation to remove trailing space. The new id of that header would then  be `curly_braces` instead of `curly_braces_`. This could break some links, but we can find those with a regular search, something like:`/id=(['"]).*?_\1/`

@ddbeck Any objections?

**Comment by ddbeck** [comment]
> @ddbeck Any objections?

@caugner No objections. That sounds reasonable to me.
