### ISSUE TITLE
UI/UX Issue: Search is now hidden behind a button

### ISSUE THREAD

**Issue by pmentropy** [mdn/yari#5493]
MDN URL: https://developer.mozilla.org/en-US/docs/Web

#### What information was incorrect, unhelpful, or incomplete?

Search usability has been reduced: Search input is now hidden behind a button where it used to be at the top of the page.

Part of the usefulness of MDN docs before the UI change was being able to easily search at any time, now that is harder to do. Hiding core functionality behind a button drastically reduces usability.

How to fix: Keep the search input available at all times, don't hide it behind a button. (ex: see github.com);

#### Specific section or headline?

Main Nav Search button

#### What did you expect to see?

A search bar at the top of the page.

#### Did you test this? If so, how?

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/index.md
* Last commit: https://github.com/mdn/content/commit/f33c6f2cc126e9fe2d2968c12291e8b6a8f322df
* Document last modified: 2022-03-02T06:46:41.000Z

</details>

**Comment by hamishwillee** [comment]
@schalkneethling FWIW I found this aspect of the design unintuitive too - I think because the light/dark mode button is so clearly a clickable element while search was not. 

Might be nice if this was at least open by default if there is space for it to be open.

![image](https://user-images.githubusercontent.com/5368500/156949898-ed543ba6-539b-4920-87e8-d461ef395110.png)

**Comment by e3dio** [comment]
My CSS fix here https://github.com/mdn/yari/issues/5389 includes always open search input, I agree no point hiding it behind a tiny button, there is plenty of space 

![image](https://user-images.githubusercontent.com/85405955/156950303-bca9d77e-ac15-449d-a7ad-8bfdd283ab6a.png)
