### ISSUE TITLE
Bug: Wide non-Markdown tables overlap with right sidebar/TOC

### ISSUE THREAD

**Issue by nichniq** [mdn/yari#5518]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values

<img width="1806" alt="Screen Shot 2022-03-07 at 1 51 25 PM" src="https://user-images.githubusercontent.com/8700924/157124200-844d6f88-2748-4aa6-b9bc-32a712d6c1b4.png">

#### What information was incorrect, unhelpful, or incomplete?

The "In this Article" side navigation is overlapping with several tables in the main content

#### Specific section or headline?

Any section with a wide table

#### What did you expect to see?

The table to scroll its overflowing content (or otherwise not overlap with the nav bar)

#### Did you test this? If so, how?

No

#### My computer

* MacBook Pro (16-in, 2019)
* macOS 12.2.1
* Firefox 97.0.2

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/keyboardevent/key/key_values`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/keyboardevent/key/key_values/index.md
* Last commit: https://github.com/mdn/content/commit/88b57678d8c4cf07f02a2853788027dff0b2f18e
* Document last modified: 2022-02-15T08:06:18.000Z

</details>

**Comment by caugner** [comment]
The tables in that articles are HTML tables, not Markdown tables, and therefore they don't get wrapped in a scrollable-div:
https://github.com/mdn/content/blob/2e7338207d991d842be028df950640a504dd9b1d/files/en-us/web/api/keyboardevent/key/key_values/index.md?plain=1#L35

@sideshowbarker Do you know why those HTML tables haven't been converted to Markdown?

We have two possible solutions here:
1. Wrap the tables directly in the mdn/content.
2. Wrap the tables ourselves in mdn/yari.

**Comment by wbamberg** [comment]
We talk about this in https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN#tables , which includes links to the places this was discussed.
