### ISSUE TITLE
Print preview in Chrome and Edge for Learn/CSS/Howto/Add_a_shadow claims printing this particular article will require 34240 pages

### ISSUE THREAD

**Issue by nicolesharp100** [mdn/yari#5519]
MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Howto/Add_a_shadow

#### What information was incorrect, unhelpful, or incomplete?

Unable to print to PDF with Google Chrome for 64-bit Microsoft Windows 10.  Print preview cannot be generated.

Unable to print to PDF with Microsoft Edge for 64-bit Microsoft Windows 10.  Print preview cannot be generated.

Print preview for Microsoft Edge claims that printing this particular webpage will require 34240 pages (should only be about 2 pages when printed).

#### Did you test this? If so, how?

All previous pages for "Learn CSS" will print to PDF from Google Chrome for 64-bit Microsoft Windows 10 without issue.

Print preview and print to PDF work correctly with Mozilla Firefox for 64-bit Microsoft Windows 10 (prints as 2 pages instead of 34240 pages).

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/learn/css/howto/add_a_shadow`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn/CSS/Howto/Add_a_shadow
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/css/howto/add_a_shadow/index.md
* Last commit: https://github.com/mdn/content/commit/07453ac2b659a397b0fee921fa71db5488e9ca62
* Document last modified: 2021-10-08T14:43:33.000Z

</details>

**Comment by sideshowbarker** [comment]
I can reproduce this behavior in Chrome Canary in my macOS environment — 32,000+ pages to print

This seems like a bug in Blink that probably should be reported at https://bugs.chromium.org/p/chromium/issues/entry — but I guess there’s a possibility the @mdn/core-yari-dev team may have seen this happen before with some other page

**Comment by schalkneethling** [comment]
I agree with @sideshowbarker that we should report this to Blink using the link provided. I have not seen this before but, that is clearly a bug in the browser and not something particular too MDN. Thank you for letting us know @nicolesharp100. Would you file the issue at https://bugs.chromium.org/p/chromium/issues/entry

**Comment by nicolesharp100** [comment]
A better solution would be to make all of the "learn" modules from "developer.mozilla.org/docs/learn" available on the Mozilla website as printable PDF ebooks (e.g. "Getting Started with the Web", "Learn HTML", "Learn CSS", "Learn JavaScript", "Learn Forms", etc.).  Making the entire site available as downloadable/printable PDF files ensures offline access for people with limited or unreliable internet access, as well as for people with disabilities who prefer to read printed pages offline instead of online text (this can be helpful for people with attention-deficit disorder for example).  The HTML Standard follows this dual-publication model for both online and offline access and is available as both a multi-page website and as a printable PDF ebook: https://html.spec.whatwg.org/print.pdf

**Comment by schalkneethling** [comment]
Thank you for your suggestion @nicolesharp100!
