### ISSUE TITLE
Bug: browser compatibility tables not displaying

### ISSUE THREAD

**Issue by rebloor** [mdn/yari#5520]
# Summary

Some browser compatibility tables aren't displaying, 

## Where did you spot the bug?

For example:
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea
- https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/sidebarAction 

## What is the problem?

Rather than displaying the table, there is the error "Unfortunately, this table has encountered unhandled error and the content cannot be shown."

## What did you expect to happen?

The browser compatibility table displays.

## Steps to reproduce the issue

Open one of the example pages and scroll to the browser compatibility section.

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [ ] Chrome: (what version?)
- [x] Firefox: (97)
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [ ] Windows: (what version?)
- [x] Mac OS: (12.2.1)
- [ ] Linux: (what distribution / version?)

## Screenshots

![image](https://user-images.githubusercontent.com/7352080/157155502-3be8cb16-eed7-458e-bda1-e7a9631a7c48.png)

**Comment by schalkneethling** [comment]
@rebloor The issue should be resolved. Can you please confirm? Thank you

**Comment by liyuhang1997** [comment]
@schalkneethling Hello. I found

```txt

**Comment by schalkneethling** [comment]
@liyuhang1997 Ouch, that is a nasty one. We will take a look, thanks! I know there is a problem with using Google translate with the website so, it might be related.

**Comment by rebloor** [comment]
@schalkneethling at least for the pages I know about the original issue is fixed. I'm happy to close the issue unless you want it to keep it open for this other problem, but that looks so it should have a new issue anyway.

**Comment by caugner** [comment]
We're tracking the Translate-related issue in #5538, so I will go ahead and close this issue.
