### ISSUE TITLE
UI suggestion: Make the font size of code in the notecard smaller

### ISSUE THREAD

**Issue by sharonytlau** [mdn/yari#5522]
# Summary

The `code` text in the notecard has the same font size as in the body. A smaller font size would make the notecard look better. 

## Where did you spot the bug?

Here's an example screenshot from the [Object.prototype.toString()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString#description) page:

![image](https://user-images.githubusercontent.com/62269974/157171207-f2aaf53f-eab1-427c-be53-6a350c94c370.png)

## What is the problem?

As we can see in the above screenshot, inside the notecard, a smaller font is applied to the normal text, and the `a code` text (underlined in green). However, the `code` text (underlined in red) has the same font size as in the body.

## What did you expect to happen?

I expect that the `code` text also gets a smaller font. Consider adding a new CSS variable for the font in `./client/src/app.scss` and declaring a style on `.notecard code` text in `./client/src/ui/molecules/notecards/index.scss`.

### Device

- [x] Desktop
- [ ] Mobile: ...
- [ ] Tablet: ...
- [ ] Other: ...

### Browser

- [x] Chrome: 99.0.4844.51
- [ ] Firefox: (what version?)
- [ ] Safari: (what version?)
- [ ] Other: (what browser / version?)

### Operating system

- [x] Windows: Windows 10 Home
- [ ] Mac OS: (what version?)
- [ ] Linux: (what distribution / version?)

**Comment by e3dio** [comment]
See issue https://github.com/mdn/yari/issues/5517

The note text should probably be made larger to match the other text

**Comment by caugner** [comment]
As @e3dio rightly mentioned, we have tracked this issue in #5517 and resolved it in #5530, which will be deployed soon.

The section above will then look like this:

![image](https://user-images.githubusercontent.com/495429/157434749-756d6ca9-937b-43ac-acbf-85754ae26238.png)

**Comment by sharonytlau** [comment]
Hi @caugner, I've just noticed that the `:before` pseudo-element appears to be no longer aligned with the first line of the text after changing the font size. 

I think the following rule in `./client/src/ui/molecules/notecards/index.scss` should be tweaked a little bit.
![image](https://user-images.githubusercontent.com/62269974/157474795-946c93fa-3708-4f1c-822d-23f36debc039.png)
Maybe `top: 1.3rem` to `top: 1.5rem`.
![image](https://user-images.githubusercontent.com/62269974/157475232-7ebddbef-923e-4b9c-a3c9-6f7109195f70.png)

What do you think?

**Comment by caugner** [comment]
@sharonytlau Would you like to open a PR with a before/after screenshot, referencing this issue and mentioning me? I will have a look then. 🙂
