### ISSUE TITLE
chore: remove hacks blog post banner

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5528]
Tomorrow, 9 March 2022, we should remove the current banner linking to the hacks blog post about the redesign.

**Comment by caugner** [comment]
Is this as simple as reverting 3e25747c01e9859c411de773ac45d7a03e842112?

**Comment by schalkneethling** [comment]
> Is this as simple as reverting [3e25747](https://github.com/mdn/yari/commit/3e25747c01e9859c411de773ac45d7a03e842112)?

Technically, but I wanted to document and improve the way we do this slightly as part of turning it off.
