### ISSUE TITLE
Suggestion: Option to pin site navigation while scrolling

### ISSUE THREAD

**Issue by scottdotjs** [mdn/yari#5535]
It would be nice to have the option to pin the site header so that it remains visible while you scroll down the page. That would allow for faster access to navigation and search. Something like this button in Microsoft Office apps:

![image](https://user-images.githubusercontent.com/32358661/157296185-2ed812ed-bbe8-4c61-8af4-873d8f69cd24.png)

**Comment by caugner** [comment]
Hi @scottdotjs, thanks for taking the time to create this issue. 👋 

We're already tracking this suggestion in #5521, and we will probably go by making the header sticky by default.

I will go ahead and close this issue in favor of the existing one.

**Comment by scottdotjs** [comment]
Ah cool, I had a scroll through the issues list but evidently missed that. Thanks @caugner!
