### ISSUE TITLE
Research: Readability and accessibility of main content

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5546]
This issue is to track the work we are doing to rethink the typography and colors used for the main content of our documents across technologies and the learning area. The issue will be fleshed out as the work progresses.

## Related remarks

- [x] On the HTML pages in dark mode, links containing <code> almost look like red underlines for grammatical errors
- [x] Would it be possible to add icons for the browsers in the Browser Compatibility tables?
- [x] Return background color to active TOC entries
- [x] Reduce weight of h1
- [x] Smaller font scale for mobile
- [x] Move notes and related icons to below version number 

## Related issues

- [x] #5378
- [x] #5387
- [x] #5396
- [x] #5389
- [x] #5377
- [x] #5415
- [x] #5430
- [x] #5445
- [ ] #5468
- [ ] #5469
- [x] #5485
- [x] #5372
- [x] #5569
- [x] #5596
- [x] #5632
- [x] #5666
- [x] #5755
- [x] #5521
- [ ] Feedback from the community: https://twitter.com/ferdnyc/status/1508384644475068420
- [ ] #5878
- [x] #5906
- [x] #5914
- [x] #5919
- [x] #5521
- [x] #5934
- [x] #5831
- [x] #5369

**Comment by Rumyra** [comment]
Overall I like the improvements - I'm not too keen on the different weight for the headers though - I like the consistency of just using size. Also I assume the line-height in the note at the top here https://5546.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/@layer hasn't been changed yet - it looks a little bigger than the text?

Also have we considered letter-spacing? I always like a `letter-spacing: 0.1px;` myself - it gives everything a bit more room to breath :)

**Comment by OnkarRuikar** [comment]
https://5546.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/Payment_Request_API/Using_the_Payment_Request_API#starting_the_payment_process

In dark mode, current code background-color `#4e4e4e` appears very strong. And the code section stands out way too much:
![strong](https://i.imgur.com/2vGeyNj.png)

We can change it to `#383838`. It blends nicely:
![mild](https://i.imgur.com/gzFnixb.png)

**Comment by schalkneethling** [comment]
> Also I assume the line-height in the note at the top here

Good catch!

**Comment by schalkneethling** [comment]
> Also have we considered letter-spacing? I always like a `letter-spacing: 0.1px;` myself - it gives everything a bit more room to breath :)

Yes, I am addressing the letter spacing as well. Thanks, Ruth.

**Comment by iDave2** [comment]
Hi all, thx for the invite @Schalk. I have one old suggestion (pondered but not shared) and two initial impressions of new mozit.cloud site.

1. I visit MDN every few years and go thru many tutorials to refresh skills. This year, I noticed myself getting lost after returning from a break to the middle of a long lesson -- now "Where was I?" I look to the right and it says I am IN THIS ARTICLE. After returning true to that one, I look left to see where I was in the Bigger Picture, the left navbar with its Table Of Contents (TOC) but, sadly, that TOC redraws itself whenever you touch something! My unshared (old) suggestions then were,

  a) Replace IN THIS ARTICLE with Page Title so one always immediately sees / recalls what they were reading, what they are doing. That right aside never moves, you can count on it!

  b) Add smarts to left navbar to maintain its position so that it better tracks user's context. For example, if user refreshes a page, why do we need to reposition Anything user was looking at before refreshing? Or when user clicks a specific page in navbar TOC -- remember, user is now Staring at the desired TOC entry -- why would we then Surprise the user by erasing what s/he is looking at? We could just repaint body with selected article instead.

OK, out with the old, in with the new?

2. Opening new 5546 site (I just noticed that "host" name, nicely done :) my initial impression was approximately "Wow, these fonts are larger." While my old eyes like bigger fonts, I'd hesitate shipping this without more votes. There's the "evolution rather than revolution" thought, I'd hesitate veering Too far from other development sites like google or microsoft. The left-side navigation does seem too large, too spacey. After all, left navbar represents a condensed, skimmable Table Of Contents (TOC) rather than the readable prose of a main article.

3. I think I'm preferring the almost-pitch-black background (#111 or #222) rather than the softer 5546 background (near #333). Strong black background helps me feel more like a secret agent, especially when coding late at night. The deep black may also permit more "dramatic" (but not revolutionary) flourishes since it is easier to create high contrast. For example, i find the new search box coloring on the Old dark site (the current public site) gorgeous. All is black (i.e., it was a dark and stormy night...) until you click the search button and that oval text box slides out with the prettiest splash of bright (but soft) orange border. i think this reaction would be harder to find with lower contrast everywhere. Also, trolls might complain "it is not dark yet, have you got a dark site i could use?" From another (design) angle, "light" and "dark" are the extremes -- one could have many intermediate "skins" -- and getting the extremes right might make it easier to do whatever comes next. In any case, keep the current public "darker than 5546" CSS on hand, @Schalk, as I think current public dark site is looking marvelous except for a few low-contrast edge cases. I noticed the letter coloring changing the other day as I referenced various pages and liked that a bunch -- whether you were doing it sitewide on purpose or randomly selecting slightly different CSS -- it was kinda refreshing in the context of reading Lots of text in one sitting.

OK, there you go, in case anyone was running out of thoughts to think.  ;)

2c,
-dave

**Comment by schalkneethling** [comment]
Thank you so much for the great feedback @iDave2!

**Comment by iDave2** [comment]
color is so subjective -- i reserve the right to change my preferences daily -- today, i'm with google marketing. (<- joke)

i opened Chrome preferences this morning. so smooth, so subtle, almost like no links are there, but you know something is there because it is google and they always have stuff.

i go back to MDN. all the links have a different background color, it almost looks like a page covered with sticky-notes. maybe too much (unsolicited) stuff in this case.

@Schalk, i see references added to my previous post that point to past merges. are there associated issues / discussions, people arguing we need more #111's, or are these just merge / build ID's that github automation added? sorry, discussion newbie here.

**Comment by schalkneethling** [comment]
> or are these just merge / build ID's that github automation added

It might be that it is automation by GitHub

**Comment by simevidas** [comment]
The browser compatibility table has a readability issue, IMO. The icons are not consistent. If the cross is in a red circle, and the question mark is in a gray circle, then the check-mark should be in a green circle.

Also, the asterisk should not be in a circle because the circle is already used for the icons that represent level of support.

Finally, the table cells should be top-aligned, so that the icons and version numbers are property aligned with each other.

<img width="681" alt="Screenshot 2022-03-24 at 16 02 51" src="https://user-images.githubusercontent.com/716405/159946447-81d84c6d-9b2b-4ee5-9ad1-9195ede9bf76.png">

**Comment by Andrew6rant** [comment]
I personally think that inconsistent icons can be good for accessibility, your example is super nice-looking but the circle icons can be a bit hard to tell apart at a quick glance if one has poor eyesight or red-green colorblindness.

Here is what yours looks like put through Chrome's deuteranopia color filter (the most common form of colorblindness):
![Šime_Vidas_MDN_AFTER](https://user-images.githubusercontent.com/57331134/160034046-fc0bd8b9-7744-46ac-8f3d-18ffbc92fbef.png)

I took a stab at making a mock-up, here is my attempt:

**Before:**

![Andrew_Grant_MDN_BEFORE](https://user-images.githubusercontent.com/57331134/160033278-fde5c31d-32a6-4459-a3b7-927ebb1b653e.png)

**After:**

![Andrew_Grant_MDN_AFTER](https://user-images.githubusercontent.com/57331134/160033294-d3da90aa-a698-4a61-b4e5-33c96d65c03a.png)

It's not as pretty as yours but the checkmark is visually distinguished from the X and question mark.

**Comment by simevidas** [comment]
Hey @Andrew6rant, I opened a separate issue for this a few moments ago. It’s here: https://github.com/mdn/yari/issues/5804. Could you please post your comment there, so that the discussion can happen in that issue?

**Comment by iDave2** [comment]
<img width="1276" alt="MDN EventTarget" src="https://user-images.githubusercontent.com/190651/160163774-22170dc0-c241-4f6d-b690-32c88eb80e33.png">

hi all,

if we must have gigantic header fonts, we might display it more like a formatter would, like a developer might expect, like

    EventTarget
      .addEventListener(),

that is, we let '<h1>' wrap on dots (, dashes, etc.).

also, the screenshot shows noticeable unused real estate on right side after 'In this article'.

also, and this overlaps my last comment comparing "sexy subtle google prefs" to MDN's "sticky-note" presentation:

<img width="1271" alt="MDN CSS" src="https://user-images.githubusercontent.com/190651/160163956-1e972652-7c0a-448f-82af-9059e4a5e55e.png">

sticky notes are prominent in EventTarget example above but absent in CSS example's left-side navigation. so the site is inconsistent and i still vote for subtle. 

it is interesting: technically, Google prefs violates MDN's strong suggestion to "Don't mess with anchor CSS, people are too familiar with the legacy behavior." on the other hand, MDN visitors may be more technically inclined, in general, so have no trouble with a fresh variation.

anyway, 2c for today. -d

**Comment by iDave2** [comment]
oops. that was "we let H1 wrap on dots and dashes" but i did not escape the HTML so the remainder of that post is bold indeed. ;)

**Comment by schalkneethling** [comment]
> a) Replace IN THIS ARTICLE with Page Title so one always immediately sees / recalls what they were reading, what they are doing.

On change we will make to address this is to make the header sticky. This means the breadcrumbs will always be visible. I believe that will resolve this problem. It has also been mentioned by other folks.

**Comment by schalkneethling** [comment]
> 2\. There's the "evolution rather than revolution" thought, I'd hesitate veering Too far from other development sites like google or microsoft.

I have dailed these down some. 👍

**Comment by schalkneethling** [comment]
> 2\. The left-side navigation does seem too large, too spacey.

Yup, agree. I updated this as well.

**Comment by Rumyra** [comment]
In regards to the wrapping of web api page titles - we've got a project in the works to redo the format of these, which will help to solve this problem https://github.com/mdn/content/discussions/5121

**Comment by iDave2** [comment]
hi all, a couple more thoughts for @Schalk and team. And thx for the wrapping update, Rumyra!

-----

i like the sticky breadcrumbs (not headers), a perfect solution to the "where am i?" problem. creative, the crumbs are there, just needed to share them.

-----

site is looking excellent overall. most lessons quite smooth, web api's (DOM) still a bit choppy with all their links still having both underline and background color (sticky-note syndrome).

-----

speaking of breadcrumbs, before i forget, there are still some peek-a-boo pages. if you go here for example,

  https://5546.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Guide/Introduction,

you will see in left navbar that you are at 

  JavaScript > JavaScript Guide > Introduction, 

and if you look at the breadcrumbs you see you are at

  References > JavaScript > JavaScript Guide > Introduction,

but there is no way to get to that peek-a-boo JavaScript Guide page without leaving the navbar and going up and clicking it in breadcrumbs directly or by modifying URL in address bar manually. while readers may feel satisfied at having found a back door into MDN, we could also update left navbar to make these "disclosure links" actually open their page in addition to disclosing their hidden subtree.

-----

other than that, i might strive for better consistency in presentation of links. go to Reference > HTML,

  https://5546.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML,

and look around:

  * left-side site navigation provides no hover feedback aside from an oddly flickering cursor as it alternates between Grasp and Pointer (slide mouse up and down over navigation to see). margin 0 and healthy padding might fix flickering. i might add a tad more hover feedback after removing flickering.

  * First paragraph on page has two hyperlinks with underlines and alternate text color;

  * Third paragraph on page has links with underlines and background color and text color change;

  * Right-side page navigation (In this Article) uses background color to say "you are here in this page," changes text color on hover, and almost no cursor flickering.

so there are four link styles. hmm... i don't know if there is a "right answer" here but, you know, those &lt;code&gt; links could be easy -- they would still be prominent without changing their background color. then there would only be three link styles on this page.

and so on.

2c,
-d

**Comment by schalkneethling** [comment]
Thank you for your consistent feedback @iDave2, much appreciated. That is a good point about perhaps making only the breadcrumbs sticky. I guess the main benefit to having the header also be sticky is quick access to search.

**Comment by schalkneethling** [comment]
@iDave2 I was also thinking, another reason having the header also be sticky is quick access to change you theme. Not sure how much folks do this, but when working on MDN it helps :)

**Comment by OnkarRuikar** [comment]
@iDave2 and @schalkneethling we can have both floating without occupying a lot of space!

https://user-images.githubusercontent.com/87750369/161049915-6a5a2528-4f81-41bc-b3a9-8deff74f7247.mov

For this I needed only two CSS rules:
```css
/* existing rule */
.main-document-header-container {
  position: -webkit-sticky;
  position: sticky;
  z-index: var(--z-index-top);
 
  top: -4rem;                  /* shift header up when not at page top */
  transition-duration: 0.5s;   /* smoothen the drop */
}

/* new rule */
.main-document-header-container:hover {
  top: 0;                      /* on hover bring it down */
}
```

With little bit of polish we can make it work.

**Comment by iDave2** [comment]
@Schalk, 5546 looks great as i see it today. the uppermost rectangle containing "mdn web docs, theme" and ending with "breadcrumbs ... English (US)" is sticky so readers always see their current location.

i think when you said "header" i thought of the ginormous "EventTarget.addEventListener()" and thought that that would not be so good to make sticky. (it would also be redundant with breadcrumbs.)

so i think we are on same page.

that's a pretty slick video, @Onkar. your solution is compelling too. guess you'd need to weigh pros and cons (with @Schalk who enjoys toggling themes :),

 *  pros: more real-estate for articles, compact & to-the-point, ...
 * cons: maybe more complex, can't search or change theme without extra work, ...

i guess if we swapped position of Theme-Search and Language (unless this breaks some standard), then @Schalk could change themes in @Onkar's solution. i like both, you all choose.

-d

**Comment by OnkarRuikar** [comment]
@iDave2 , @schalkneethling 

> that's a pretty slick video, @onkar. your solution is compelling too. guess you'd need to weigh pros and cons (with @schalk who enjoys toggling themes :),

Thanks! 
You've tagged wrong 'onkar'.  I am @OnkarRuikar 🙂


> * cons: maybe more complex, can't search or change theme without extra work, ...

When you are at the beginning of the page, all the options are visible without need to hover. If you are looking for menus or search that means you are leaving the page. This and theme change users don't do frequently, unless you are QA or Dev. For dev builds we can have entire header floating.

 
> i guess if we swapped position of Theme-Search and Language (unless this breaks some standard), then @schalk could change themes in @onkar's solution. i like both, you all choose.

Users don't change language and theme that often so grouping them together in header seems good idea. And we can bring search down like this:

![changed positions](https://i.imgur.com/RQ9Rwpv.png)

**Comment by schalkneethling** [comment]
> @iDave2 and @schalkneethling we can have both floating without occupying a lot of space!

Thank you for the suggestion! This was indeed a first iteration to get people’s feedback on the basic idea. I really like your idea.

**Comment by schalkneethling** [comment]
@Andrew6rant I created an issue(https://github.com/mdn/yari/issues/5878) for further discussion based on your suggestions. Thanks so much.

**Comment by rogix** [comment]
Is great to see all the improvements so far. Great work, people! 

One thing I think could be improved, based on my personal experience, is the  side menu. Right now it looks hard to read sometimes, the background color does not make easier, quite the opposite, it make it feel "full" and hard to distinguish.  

![image](https://user-images.githubusercontent.com/12768403/161265404-0351459f-f1ad-4147-aa40-9cc4febd6f4f.png)

Removing the background and adding some space look cleaner and easier to read for me.

![image](https://user-images.githubusercontent.com/12768403/161266270-3e13bcb7-5a2e-4c9f-8f0c-6ad56525f286.png)


Also, the "current item" is very hard to distinguish from the others.

![image](https://user-images.githubusercontent.com/12768403/161266704-d2b9fc67-3ec5-4755-b8e4-114a9d3385c2.png)

I'm not sure how to improve this, but maybe adding some bold and a stronger color could help.

I think it would be nice to keep the selected menu item on the middle of screen, so the user can see it while reading the content. It would help localize where it is. 

I hope this can help.

**Comment by schalkneethling** [comment]
> the background color does not make easier, quite the opposite, it make it feel "full" and hard to distinguish.

I 100% agree with you. This is part of the next batch of updates I am making today

**Comment by schalkneethling** [comment]
> Awesome!

This is what it will look like now in the sidebar:

## Dark mode

![Screenshot shows sidebar with improved styling for the active page entry.](https://user-images.githubusercontent.com/10350960/162070225-75342b7b-7b54-43dd-a46d-6bfc9a6674b5.png)

## Light mode

![Screenshot shows sidebar with improved styling for the active page entry.](https://user-images.githubusercontent.com/10350960/162070307-9336b213-a50a-4b87-97a3-824f503f84d6.png)

**Comment by rogix** [comment]
Looks nice. I would add a little more padding between the items, similar to "Is this article" section.

In this case just removing `line-height: 1.2` seems to solve it.

It would look like this:

**Comment by rogix** [comment]
![image](https://user-images.githubusercontent.com/12768403/162202015-2eae2ed9-3362-4880-9163-b80f9e4a11b9.png)

**Comment by wbamberg** [comment]
Overall I think this is *really* good. Things I especially like:

* the H2s are more distinct from the H3s, which really helps reveal the page structure.
* consistent link colours
* much clearer sidebar typography
* sticky breadcrumbs

1. The positioning of heading anchors  needs a tweak to account for the sticky breadcrumbs: as it is the breadcrumbs hide the title, so you wonder where you have ended up (for example, try clicking on "Examples" in the ToC).

2. The ToC applies a particular style to the "current" section of the page:

![Screen Shot 2022-04-07 at 11 31 09 AM](https://user-images.githubusercontent.com/432915/162272477-d40c2127-3211-4ce7-8743-1bf48f968540.png)

It would be really nice, for consistency, if the sidebar applied the same style to the current page:

![Screen Shot 2022-04-07 at 11 31 19 AM](https://user-images.githubusercontent.com/432915/162272539-33ad3416-9ea0-4090-83b1-1bf9162c07b0.png)

3. I am not a fan of the `_` after the page title.

4. There are some contrast issues still. Comments in code blocks especially in the light theme are hard to read:

![Screen Shot 2022-04-07 at 11 35 30 AM](https://user-images.githubusercontent.com/432915/162273146-a6cc3ea3-504e-4dbe-ab0c-837ddada6761.png)

...and sometimes the interactive examples have problems too - look at `element` here:

![Screen Shot 2022-04-07 at 11 36 26 AM](https://user-images.githubusercontent.com/432915/162273319-477362b6-9b77-46df-9475-dc573e3bec33.png)

But I guess these contrast issues can just be picked off :).

5. There are some places where vertical spacing makes things hard to read. For instance:

![Screen Shot 2022-04-07 at 11 37 51 AM](https://user-images.githubusercontent.com/432915/162273587-89aa6d4c-b77f-4b6e-8d04-56ac1d0de196.png)

Here there's less space before the H3 than between paragraphs and `dt` elements, so the sectioning is not visually apparent. Compare with the current design:

![Screen Shot 2022-04-07 at 11 38 48 AM](https://user-images.githubusercontent.com/432915/162273741-c8197d1a-7db7-4db1-9a3a-77dac2388d64.png)

...which is better in this case.

It might be worth making the `dt` spacing a bit tighter, and also possibly increasing `dd` indentation a bit. We use these things a lot and often nest them, and it's not always easy to see which items belong to which higher-level object.

6. Overall this is a bit less dense than the current design. I'm probably marginally in favour of a bit more density but I understand that people have different views on that, and it's fine really.

7. Although I love there being a link to the interactive example in the ToC, I much prefer the page without the actual heading:

![Screen Shot 2022-04-07 at 11 45 11 AM](https://user-images.githubusercontent.com/432915/162274783-8108f0ba-aeb9-4864-b46b-117eeeff818f.png)

versus:

![Screen Shot 2022-04-07 at 11 45 39 AM](https://user-images.githubusercontent.com/432915/162274809-4005bf34-fe70-430f-a161-ee9d5b5f0224.png)

...it just feels like there's a lot of empty space in the first version. When we built the interactive examples we wanted them fairly tight at the top of the page. But this isn't a hill I am prepared die on. 

8. This is more of a possible feature request, but now we have a scrolling sidebar should we scroll the sidebar so the current page is visible in it?

**Comment by schalkneethling** [comment]
Thanks so much for all your fantastic detailed feedback, @wbamberg. I have gone through a round of reviews internally and will be making some updates this week.

**Comment by OnkarRuikar** [comment]
> * Sticky header animation is a bit off-putting

If accidental slide down is being annoying, then we can provide a small pin button on breadcrumbs bar to keep it folded:
![pin button](https://i.imgur.com/6CTIF36.png) 

***
Or
Instead of hover we can use click button:
![button](https://i.imgur.com/lm3UveN.png)

**Comment by schalkneethling** [comment]
> Dead links in the sidebar and listed under properties on [5546.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/SVGElement](https://5546.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/SVGElement) are still the same color as all the other links.

Those are fixed locally, I just have not pushed an update to the dev server is a while.

**Comment by iDave2** [comment]
i think new sticky zone is hiding section headers whenever links are followed? plus, i wanted to try a movie:

https://user-images.githubusercontent.com/190651/163407554-e71facad-a81b-4fa1-94cc-603a6c939319.mov

**Comment by OnkarRuikar** [comment]
@iDave2 following CSS rule solves the issue:
```css
:target {
  scroll-margin-top: 30px;
}
```

https://user-images.githubusercontent.com/87750369/163410232-b055a5f0-c862-497a-9856-3e5ddfef8fc5.mov

**Comment by iDave2** [comment]
thanks for the quick solution, @OnkarRuikar. maybe @schalkneethling can implement for site when time permits.

**Comment by schalkneethling** [comment]
> thanks for the quick solution, @OnkarRuikar. maybe @schalkneethling can implement for site when time permits.

Yup, this has been addressed. Thank you.
