### ISSUE TITLE
[Design] Search input almost hidden

### ISSUE THREAD

**Issue by cadars** [mdn/yari#5548]
The search input is now collapsed as a thin icon on the right, next to the color mode toggle, making the whole thing visually confusing.

<img width="1396" alt="image" src="https://user-images.githubusercontent.com/467112/157195233-50a2409b-4807-4201-b22a-eb79c2005cb1.png">

A collapsed search input could be acceptable on smaller screens, but in this case it’s hidden behind a hamburger menu:
<img width="487" alt="image" src="https://user-images.githubusercontent.com/467112/157196385-11b57919-eff0-4e5e-8dca-67e3e853e4fa.png">

For a documentation website, the search input should be one of the most prominent elements, not an afterthought.

**Comment by schalkneethling** [comment]
@cadars I believe this has been resolved with some of the recent updates. Closing the issue as a result.
