### ISSUE TITLE
Add in document title to interactive examples

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5561]
@dipikabh started a [discussion thread here](https://github.com/mdn/yari/discussions/5453) after having talked through it internally. The idea has great support across the content team. I have also mentioned this to @HerminaC and the decision was made to go ahead with the plan.

This means we will add an `h2` heading to the output of the interactive example macro. This would then have the additional benefit of it showing up in the table of contents for all pages with an interactive example.

**Comment by schalkneethling** [comment]
## Try it

![Screenshot 2022-03-14 at 19 29 28](https://user-images.githubusercontent.com/10350960/158228012-44e420dc-ecdb-4f49-982f-bb7ff088b1b4.png)

## Interactive example

![Screenshot 2022-03-14 at 19 30 04](https://user-images.githubusercontent.com/10350960/158228078-7930b1d0-7ec7-4e6e-8c73-d9c1e5f93aaa.png)

## Interactive demo

![Screenshot 2022-03-14 at 19 30 24](https://user-images.githubusercontent.com/10350960/158228121-776fa5b2-1885-40e5-bb5f-92b51dc7e0a9.png)

**Comment by caugner** [comment]
Have we considered adding this header directly to all articles in mdn/content, to be consistent with the other headers?

Other macros like `CSSInfo` and `csssyntax` don't add a heading either:

https://github.com/mdn/content/blob/468263d78e51ed942e64b47b1bbef5dfbbc689bf/files/en-us/web/css/width/index.md?plain=1#L68-L74

**Comment by schalkneethling** [comment]
> Have we considered adding this header directly to all articles in mdn/content, to be consistent with the other headers?

That is indeed the plan once we have settled on a title to test with our readers.

**Comment by ddbeck** [comment]
I know it was my idea, but I'm loving the "Try it" header—it feels much more approachable.

@dipikabh 

> If we go with the option of "Try it", do we want to add an exclamation mark so that it says "Try it!"?

I'm inclined to go without the punctuation. I think the learning area has a breezier tone than the reference docs. I think people bounce from reference page to reference page pretty quickly—the exclamation loses its potency with repetition, I think.

I'm also favorable to trying this out with other macros, but I say we start with just one and see how it goes.

**Comment by dipikabh** [comment]
> @ddbeck @dipikabh Shall we go ahead and trial `Try it`?

We should 👍. Thanks!
