### ISSUE TITLE
Links within code are greyish and hard to read, different than normal links

### ISSUE THREAD

**Issue by e3dio** [mdn/yari#5568]
Links within code are colored differently than links outside code. These code links are hard to read, they are a greyish version of the normal links, and being inside an already grey code block hurts readability. Also it's not clear what the different color signifies, why it's a different color than normal link, if it's actually a link, etc. I propose to color those the same color as normal links as pictured below:

# Before

![chrome_40e1bqKa7K](https://user-images.githubusercontent.com/85405955/157692267-1f6e5fab-0341-46cd-a14c-06cf5e16e7f6.png)

# After

![5NnkOu5u60](https://user-images.githubusercontent.com/85405955/157692255-e9cd5487-d990-4a8d-b0ee-afa14c7105fb.png)

# Before

![image](https://user-images.githubusercontent.com/85405955/157698886-a8971315-86d1-4e63-b3b2-a8cf85cbc993.png)

# After

![image](https://user-images.githubusercontent.com/85405955/157699355-c85a34bb-a704-4995-bb8c-0850a73d4845.png)

**Comment by caugner** [comment]
Please use our [bug report issue template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml). Thanks!
