### ISSUE TITLE
Links within code are greyish and hard to read, different than normal links

### ISSUE THREAD

**Issue by e3dio** [mdn/yari#5569]
### Summary

Links inside code are colored different than other links. These are a little harder to read due to being greyish color inside an already grey code block, but mostly it just does not look like a link because the color is off. It would look better and make more sense to have those the same color text as other links

 Ref: https://github.com/mdn/yari/issues/5445

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects

### Reproduction steps

1. Look at page

### Expected behavior

Code Links same color as normal links

### Actual behavior

Code links different color, harder to read, confusing meaning

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

# Before

![chrome_40e1bqKa7K](https://user-images.githubusercontent.com/85405955/157692267-1f6e5fab-0341-46cd-a14c-06cf5e16e7f6.png)

# After

![5NnkOu5u60](https://user-images.githubusercontent.com/85405955/157692255-e9cd5487-d990-4a8d-b0ee-afa14c7105fb.png)

# Before

![image](https://user-images.githubusercontent.com/85405955/157700666-9e234cdd-ad02-4929-9e4d-3c51782c4f94.png)

# After

![image](https://user-images.githubusercontent.com/85405955/157700613-b76f2f27-12df-4203-a4ab-7cdb99b24183.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Thanks for reporting this, and I will check internally, whether this is intended.

FWIW The difference is even more noticeable in dark mode:
![image](https://user-images.githubusercontent.com/495429/157709110-c2c1d25f-aaec-4620-b2e2-81e7b3fa5ce5.png)

**Comment by caugner** [comment]
Hm, I think it doesn't affect all sections.

For example, in the [CSS basics](https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/CSS_basics), the links seem to have the same color.

However, the [HTTP section is affected](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies), for instance.

@schalkneethling Do you have this on the radar, by any chance?

**Comment by e3dio** [comment]
Also note: there is an inconsistency between inline code links and "pre" block code links. The block code links are normal color links, the inline are the different grey color. If you make the inline code links the same as normal links they would match with block links

**Comment by caugner** [comment]
> there is an inconsistency between inline code links and "pre" block code links.

@e3dio Would you have links + screenshots where we can see inline code links and "pre" blocks together? (I don't believe the screenshots above capture this.)

**Comment by schalkneethling** [comment]
> @schalkneethling Do you have this on the radar, by any chance?

It is now 😄  https://github.com/mdn/yari/issues/5546 - Thanks for the ping.
