### ISSUE TITLE
Non-standard/Deprecated icons are not consistent

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/yari#5571]
### Summary

The entire page and compatibility section uses different icons for the same 'Non-standard' badge. 
Same is the case with `Deprecated` badge. 
Same icon 👎🏻 has different meanings, in different sections on the same page.

### URL

https://developer.mozilla.org/en-US/docs/Web/API/Window#browser_compatibility
https://developer.mozilla.org/en-US/docs/Web/API/Window#methods

### Reproduction steps

1. Open the [URL](https://developer.mozilla.org/en-US/docs/Web/API/Window) and search `mozpaintCount` property.
2. In [properties section](https://developer.mozilla.org/en-US/docs/Web/API/Window#deprecated_properties) you'll see assigned badges like this:
![img1](https://i.imgur.com/4VsJoAd.png)
Note: 
👎🏻 => Non-standard
🗑 => Deprecated
3. Now go to browser compatibility section. You'll see:
![img2](https://i.imgur.com/zkIcXuW.png)
Note:
👎🏻  => Deprecated
⚠ => Non-standard
4. Now open page https://developer.mozilla.org/en-US/docs/Web/API/Window/mozPaintCount . There you'll see:
![img3](https://i.imgur.com/LMieaon.png[/img)
Note:
 ❌ => Deprecated
⚠ => Non-standard
6. Note, same icon 👎🏻 has different meanings, on the same page. The icons used are different for the same badges.

### Expected behavior

Icons should be consistent across the entire site. 

- [x] 1.  🗑 should mean `Deprecated` everywhere on the website. Compatibility section and notecards need to be corrected. 
- [x] 2.  ⚠ should mean  `Non-Standard` everywhere on the website.  CSS rule `icon-nonstandard` needs to be corrected on main page.  The icon 👎🏻doesn't fit well here, and has negative tone.

Less severe issues:

- [x] 3. Same icons should be used everywhere e.g. Experimental icon looks different everywhere: The flask is different for compatibility and main section.
- [ ] 4.  Quick links sidebar has colored badges. Looks odd. Can we have same black and white badges there too?
- [ ] 5.  Currently badge order is different at 3 places(mentioned in Steps to Reproduce section). For sake of consistency the badges should appear in same order every where e.g. deprecated -> experimental  -> non-standard.  Or the order can be decided based on the danger of using such APIs, i.e. deprecated are more harmful than experimental, cos they can creep into production easily, and so on.

### Actual behavior

- Icon 👎🏻 represents different badges in main content(non-standard) and in browser compatibility(deprecated).
- Deprecated badge uses different icons ( 🗑, 👎🏻 , and ❌) at different places: main content, browser compatibility, and notecards. 
- Icons have different flavors at different places. In quicklinks sidebar icons are colored.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
I have checked internally, and we would like to

- use the _trash_ symbol consistently for _deprecated_ features, and 
- restore the icons for the non-standard / deprecated headers (notecards).

@OnkarRuikar Would you be interested in submitting one or two PRs for this?

**Comment by danielhjacobs** [comment]
1-3 fixed by #5583

**Comment by caugner** [comment]
> 1-3 fixed by #5583

Unless I'm mistaken, 3 is not yet fixed, but will be fixed by #5611.

PS: I have inserted a task list for the 5 problems mentioned in the OP.

**Comment by caugner** [comment]
FWIW https://github.com/mdn/yari/pull/5644 is resolving point 4.

**Comment by danielhjacobs** [comment]
@caugner So is there internal consensus for removing the color of those icons? Last I heard it was still being discussed.

**Comment by caugner** [comment]
@danielhjacobs Sorry for the waiting time. I have added this to the agenda of an internal meeting on Wednesday.

**Comment by danielhjacobs** [comment]
#5644 is merged. That's fine, but it means I'll need to open a follow-up PR if the result of Wednesday's meeting is that the colors are to be removed.

**Comment by caugner** [comment]
We are consistent now, and we'll keep the colors for now.
