### ISSUE TITLE
Header and Nav links use "16px" instead of "1rem", look small with large browser font-size

### ISSUE THREAD

**Issue by e3dio** [mdn/yari#5596]
### Summary

Nav links use "16px" instead of "1rem", look small with large browser font-size

### URL

https://developer.mozilla.org/en-US/docs/Learn/CSS

### Reproduction steps

Increase the browser font-size

### Expected behavior

All font size on site increases 

### Actual behavior

All font size increase except the Header and Breadcrumb nav links

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

# Current:
![gsKMVMPUle](https://user-images.githubusercontent.com/85405955/158041497-765ccba7-9642-459f-a355-934281c7e804.png)

# Fixed:
![chrome_jH6mkGBoP8](https://user-images.githubusercontent.com/85405955/158041488-dc2652bd-f59f-4c1e-8e89-8784e15b2d23.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Thanks for reporting @e3dio. 👍 

If you already have a fix, feel free to open a PR.

**Comment by caugner** [comment]
@schalkneethling Before I add the `accepting PR` label, I wanted to quickly check whether you are already working on this?

**Comment by schalkneethling** [comment]
> @schalkneethling Before I add the `accepting PR` label, I wanted to quickly check whether you are already working on this?

Indeed, this will be part of https://github.com/mdn/yari/issues/5546 - Thank you for checking.

**Comment by schalkneethling** [comment]
I have addressed this. Now if you bump the zoom level to say 200%, everything scales up.

![Screenshot showing a page with the main menu expanded at a 200% zoom level](https://user-images.githubusercontent.com/10350960/159341999-1ae1f512-5592-4a45-8ee2-cbcf4e2e6a14.png)
