### ISSUE TITLE
Search appears inconsistent with case

### ISSUE THREAD

**Issue by growf** [mdn/yari#5600]
Searching for `measuretext` brings back a single result; searching for `measureText` brings back 3,071 results.

**Comment by growf** [comment]
![Screenshot 2022-03-13 at 23 01 12](https://user-images.githubusercontent.com/6474244/158082995-5525c631-8cf6-4bd6-86d6-8698a9ad17df.png)
![Uploading Screenshot 2022-03-13 at 23.01.16.png…]()

**Comment by caugner** [comment]
Hi @growf, thank you for taking the time to report this.

Please make sure to use the [Bug report template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml) so that we have all information at hand to properly triage the issue.

Thanks again!
