### ISSUE TITLE
New design hard to read. | high contrast suggestion.

### ISSUE THREAD

**Issue by ShawnCockburn** [mdn/yari#5631]
### Before I get started

I'm not sure if this is the correct place to post this.. let me know if there is a better place!

I mostly really like the new functionality the site brings including dark mode, great navigation and i'm not against change in general.

---

### New design hard to read

The new documentation page design is hard to read for me personally, the old design had a really clear ui with great visual information hierarchy.

**Here is the old design:**

<img width="1792" alt="Screenshot 2022-03-15 at 15 45 13" src="https://user-images.githubusercontent.com/60285801/158417938-76a7297c-cb32-4b9b-8eba-691059d48ca0.png">

**And here is the new deign:**

<img width="1792" alt="Screenshot 2022-03-15 at 15 48 03" src="https://user-images.githubusercontent.com/60285801/158418051-056a6c0d-42c2-4c33-833a-293d480eab74.png">

I think what would help would be a **high contrast tick box option**, next to the dark light mode?

**To make the design look like something like this:**

<img width="1792" alt="Screenshot 2022-03-15 at 16 23 26" src="https://user-images.githubusercontent.com/60285801/158424636-b6af4ab9-b0f6-49c5-908d-50d7fd5adb73.png">

Again I love pretty much all the new changes, its just infuriating to skim and maybe what ain't broke, don't need fixing :)

I think this is a good option to keep the community that finds the old design great for readability happy and to keep the new design at the same time.

**what I would like to see in the high contrast mode:**

1. black and white h3's (really clear to read and skim to)
2. larger bolder h1 && h2 
3. less whitespace
4. more contrast on the different type of section. eg: grey background on the code snippet / blue ribbon on the syntax... 

### lastly

I would like to thank the MDN team for providing this amazing resource that I use everyday!

**Comment by caugner** [comment]
Hi @ShawnCockburn, we're already tracking some of the points you're raising in #5454 and #5546.

If you don't find an issue for a problem you're experiencing, please open an issue using our [bug report template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml) to make sure we have all the information we need to triage and prioritize the problem.

Thank you for your understanding!
