### ISSUE TITLE
Pages like Web APIs with multiple columns look bad on mobile

### ISSUE THREAD

**Issue by mattwelke** [mdn/yari#5632]
### Summary

To clarify, "bad" is just a succinct word to use in the title. Hard work went into the docs and this is appreciated. I love front end devs. Please don't make me center a div. <3

On mobile, pages like https://developer.mozilla.org/en-US/docs/Web/API look bad because the three columns cause the content to get squished too much and cause text in one column to get cut off as you scroll down.

I think it would look better if it was just one column on mobile.

This may affect other pages on the site too. I haven't checked other areas yet.

### URL

https://developer.mozilla.org/en-US/docs/Web/API

### Reproduction steps

1. In a phone's mobile browser (I used Firefox on Android) go to https://developer.mozilla.org/en-US/docs/Web/API
2. Scroll down
3. Observe content

### Expected behavior

Content is in a form easy to read

### Actual behavior

Content is possibly hard to read

### Device

Smartphone

### Browser

Firefox

### Browser version

Stable

### Operating system

Android

### Screenshot

https://pbs.twimg.com/media/FN5GredWYAUI6mV?format=jpg&name=900x900

### Anything else?

from https://twitter.com/schalkneethling/status/1503779679811121153

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Hi @mattwelke, thanks for reporting this issue! 👋 

Reducing the `column-count` for ``.index` to 1 on smaller screens sounds like a reasonable solution for me.

Would you be interested in submitting a PR for this?

**Comment by mattwelke** [comment]
I'll let someone else submit the PR. I'm not really comfortable editing and testing CSS. Been a long time since I did that kind of coding. I'm a back end dev who browses MDN to understand what the browser is doing when it calls the server.

**Comment by caugner** [comment]
No worries, Matt, glad to have you browsing MDN! :)

**Comment by schalkneethling** [comment]
Hey @mattwelke,

Here is how it will look on mobile.

![Screenshot of 3-column lists on mobile](https://user-images.githubusercontent.com/10350960/159335551-626eca1f-8806-46ba-b61a-e32472130c97.png)

**Comment by mattwelke** [comment]
I'm seeing something different. Could it be an issue between different devices?

I'm using a Pixel 4a.

![Screenshot_20220321-140603.png](https://user-images.githubusercontent.com/7719209/159336498-7368a2da-e51c-4e98-97a0-7cd0035ae3df.png)

**Comment by schalkneethling** [comment]
> I'm seeing something different. Could it be an issue between different devices?

Oh, this is not in production yet. That was a screenshot from my local development environment. Sorry for not being more clear about that.

**Comment by mattwelke** [comment]
Ah that makes sense. I think that will be much easier to read on mobile once it's in production.

**Comment by schalkneethling** [comment]
Hey @mattwelke, we are trialing some improvements to the readability and accessibility of MDN Web Docs and we want your input. Please join in the discussion here: https://github.com/mdn/yari/discussions/5715
