### ISSUE TITLE
Change dark theme contrast

### ISSUE THREAD

**Issue by KarannKaul** [mdn/yari#5685]
The White and Black values in the website are very contrasting to the eyes- making it stress full on the eyes

**Comment by caugner** [comment]
Hi @KarannKaul, we have addressed several issues with the redesign in https://github.com/mdn/yari/pull/5710, so I invite you check if you're still experiencing the problem you have reported.

If so, please open a new issue using our [bug report issue template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml). Thanks! 🙏

**Comment by caugner** [comment]
We're following this issue up in https://github.com/mdn/yari/issues/7705.
