### ISSUE TITLE
Good/bad code example design feels like a regression

### ISSUE THREAD

**Issue by Rumyra** [mdn/yari#5686]
Sometimes code examples have the class `example-good` or `example-bad` to highlight good practises or bad practises. Originally these snippets had a green/red background colour, now they have tick/cross icons in the corner.

These icons are not only hard to miss, but seem a little mis-leading (the cross for instance looks like a user could 'close' the code example).

I don't have a clear idea as to what the design improvement should be here (possibly green/red borders on the left?) but I think what we currently have isn't particularly good.

https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#highlight_good_and_bad_practice_examples

**Comment by caugner** [comment]
Here is how it looked before ([source](https://web.archive.org/web/20220217030234mp_/https://developer.mozilla.org/en-US/docs/MDN/Guidelines/Code_guidelines/General#code_line_length)):

![image](https://user-images.githubusercontent.com/495429/159334438-f0c82227-a6bd-4e4f-9aaf-cab1df814c8b.png)

**Comment by victor0x16** [comment]
@caugner, that would be great from a learner perspective and I do feel icons a litte mismatching with the purpose. 

I guess the icons could be less thick because they do look like too thick.

**Comment by Rumyra** [comment]
> Apart from restoring the background-color, an alternative to ✔️ / ✖️ would be 👍 / 👎 .

I'm unsure about restoring the background colour tbh - with the varied colours for sections now... It's hard to envisage without seeing. I would be inclined to just try the border colour - I like the idea of thumbs up thumbs down - are there flat icons we can use instead of emoji?

**Comment by victor0x16** [comment]
@Rumyra and @caugner, I was reading reactjs beta website and it seems they have found the right solution, see bellow:

![bad_and_good_example](https://user-images.githubusercontent.com/100092662/160221265-8f74a7ec-1275-4759-9148-bb829bcd21f6.jpeg)

I don't know how you can implement that but would be a nice for sure to see something like that.

```js
// 🚩 Wrong: Lines of code should be a maximum of 80 characters long
let tommyCat = 'Said Tommy the Cat as he reeled back to clear whatever foreign matter may have nestled its way into his mighty throat. Many a fat alley rat had met its demise while staring point blank down the cavernous barrel of this awesome prowling machine.';
```
```js
// ✅  Correct: use template strings
let tommyCat = `Said Tommy the Cat as he reeled back to clear whatever foreign
  matter may have nestled its way into his mighty throat. Many a fat alley rat
  had met its demise while staring point blank down the cavernous barrel of
  this awesome prowling machine.`;
```

**Comment by caugner** [comment]
Resolved by https://github.com/mdn/yari/pull/6857.
