### ISSUE TITLE
Create script for updating/copying Kumascript macros

### ISSUE THREAD

**Issue by escattone** [mdn/yari#570]
We need to create a script (and associate documentation) that we can use to update the macros in the Yari `kumascript` workspace with the latest changes from a `kumascript` repo clone.

**Comment by peterbe** [comment]
We decided to not do this. We've completely taken over the `kumascript/macros/*.ejs` files in Yari. But the `*.json` files are still actively maintained in https://github.com/mdn/kumascript/
Copying those latest-and-greatest over into Yari is already part of our checklist. Or at least part of https://github.com/mdn/yari/issues/1069
