### ISSUE TITLE
Parsing errors should be reported as flaws in getPrerequisites

### ISSUE THREAD

**Issue by escattone** [mdn/yari#571]
We should report parsing errors in `getPrerequisites` instead of hiding them:

https://github.com/mdn/stumptown-renderer/blob/2bf242d3eea647390a3cce17597b0e604a219a82/kumascript/src/render.js#L63-L70

**Comment by peterbe** [comment]
My bet is that too much has changed and we failed up update this issue. What do you think @escattone ?
