### ISSUE TITLE
Search input UX on desktop: Mouse users may accidentally collapse the search after expanding it

### ISSUE THREAD

**Issue by AleksandrHovhannisyan** [mdn/yari#5717]
### Summary

When you click the search bar in the top-right corner of the site and it expands, your mouse hovers over the `X`/clear button. This could make it easier for desktop users to accidentally close the search by double-clicking. (This is not an issue on mobile.)

### URL

https://developer.mozilla.org/en-US/

### Reproduction steps

1. Visit https://developer.mozilla.org/en-US/ on a desktop device.
2. Hover your mouse anywhere in the center of the search bar.
3. Click the search bar in that location.
4. Observe that the search bar expands, and the `X` button to collapse the search bar is now resting below your cursor.

### Expected behavior

It should not be easy for users to accidentally collapse the search after expanding it.

### Actual behavior

Users may accidentally collapse the search after expanding it because their mouse hovers over the close button.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![demo](https://user-images.githubusercontent.com/19352442/159487274-77fe160c-bf25-47e9-914d-4aa8f62b8ae2.gif)

### Anything else?

Users have reported other issues related to the search bar's design/UX. Fixing those issues may require redesigning the input, which may in turn resolve this problem.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
I understand the point, but I wouldn't consider this a real UX issue, so I'm closing it as "won't fix".

After expanding the search field, the field has focus and matches appear immediately after typing, so there is no immediate need to click again. In the worst case, the user has to retype their search query.
