### ISSUE TITLE
Heading hierarchy seems a little odd on these pages

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5734]
Not something to solve now but just a general comment. The space between the page heading and the first FAQ seems very large. It feels like they are completely disconnected from each other. It also seems strange that the heading of the questions are so much larger that the page heading.

![Screenshot 2022-03-23 at 13 04 49](https://user-images.githubusercontent.com/10350960/159685707-336cd8e2-9bc1-42ed-898b-dde76faa20c8.png)

_Originally posted by @schalkneethling in https://github.com/mdn/yari/issues/5707#issuecomment-1076240910_

**Comment by caugner** [comment]
This has already been fixed, most likely by https://github.com/mdn/yari/pull/5710.
