### ISSUE TITLE
Some mentions of collections in notifications

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5741]
### Summary

There are a couple of places where the copy currently mentions collections when it should mention notifications.

- https://github.com/mdn/yari/blob/mdn-offline/client/src/plus/notifications/notifications-tab.tsx#L128
- https://github.com/mdn/yari/blob/mdn-offline/client/src/plus/notifications/watched-items-tab.tsx#L120
- https://github.com/mdn/yari/blob/mdn-offline/client/src/plus/notifications/notification-card.tsx#L87

### URL

Notifications related UI

### Reproduction steps

1. Go to notifications dashboard
2. Loading message states: "Fetching your collection..."

### Expected behavior

The loading message should say: "Fetching your notifications..."

### Actual behavior

The loading message states: "Fetching your collection..."

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Fixed via https://github.com/mdn/yari/pull/5742.
