### ISSUE TITLE
Font sizes are inconsistent in a table

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#5805]
In the table at https://developer.mozilla.org/en-US/docs/Web/Performance/Animation_performance_and_frame_rate#css_property_cost the font size for the first and third non-heading cells is smaller than the size for the second.

<img width="684" alt="Screen Shot 2022-03-24 at 8 51 54 PM" src="https://user-images.githubusercontent.com/432915/160050957-0b327dfc-d6b1-4031-a07c-123fb6c0b8fd.png">

**Comment by caugner** [comment]
The difference between the cells in row 2 vs rows 1/3 is that the cell in row 2 is wrapped in a `<p>`, whereas the cells in row 1/3 are not wrapped, and so this `font-size` property on line 249 applies:

https://github.com/mdn/yari/blob/5454d9281d4a3a9f45b8214356216c01a3f7b70b/client/src/document/index.scss#L243-L249
