### ISSUE TITLE
Big vertical margins, especially with "try it" heading

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#5831]
In pages with interactive examples, we now have a lot of whitespace at the top of the page:

<img width="1122" alt="Screen Shot 2022-03-27 at 11 12 24 AM" src="https://user-images.githubusercontent.com/432915/160294840-cbfb852a-2842-46f0-a545-080688329951.png">

...it would be better with less:

<img width="1123" alt="Screen Shot 2022-03-27 at 11 13 06 AM" src="https://user-images.githubusercontent.com/432915/160294854-7c97c47a-ddc1-4eaf-b13d-59231944c484.png">

**Comment by saleh5yu** [comment]
123sal

في الأحد، ٢٧ مارس ٢٠٢٢ ٢١:١٣ wbamberg ***@***.***> كتب:

**Comment by schalkneethling** [comment]
I believe this will be improved by #5546 

![Screenshot showing updating spacing between "Try it" heading and preceding text. There is now less vertical space between these.](https://user-images.githubusercontent.com/10350960/163687507-08288471-b820-4db5-9eaf-2005184433b9.png)
