### ISSUE TITLE
Broken page layout when page not found

### ISSUE THREAD

**Issue by okjungsoo** [mdn/yari#5853]
### Summary

The page's layout is broken.

### URL

https://developer.mozilla.org/en-US/docs/Web/API/ChromeWorker

### Reproduction steps

1. Go to https://developer.mozilla.org/en-US/docs/Web/API/ChromeWorker

### Expected behavior

The page layout should look good.

### Actual behavior

Broken layout

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

![Screen Shot 2022-03-30 at 2 33 07 PM](https://user-images.githubusercontent.com/851065/160758268-20d909d3-d8be-4f99-85b4-da05e26c6e32.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
The layout of [the page](https://developer.mozilla.org/en-US/docs/Web/API/ChromeWorker) already looks better, but it's missing the header now:

<img width="1123" alt="image" src="https://user-images.githubusercontent.com/495429/190139420-e589b3df-89e7-4bf4-a342-fa4105aa756d.png">

**Comment by caugner** [comment]
This will be fixed by https://github.com/mdn/yari/pull/7070.

PS: Here is the code location that returns the `LoadingError` without other elements like TopNavigation:

https://github.com/mdn/yari/blob/5c0fe01141754f17605929d63ef988489c1c43a8/client/src/document/index.tsx#L175-L177
