### ISSUE TITLE
Homepage access to web extensions and others

### ISSUE THREAD

**Issue by rebloor** [mdn/yari#5876]
The previous iteration of the homepage for MDN web docs included links to most (not all) of the technologies included in the docs:
![image](https://user-images.githubusercontent.com/7352080/157344456-5f02f1db-7d3d-4e87-a1b7-5fa2c51e84b1.png)
The current home page no longer includes all these links, and there's no obvious way to find the documents. Search is not an entirely appropriate substitute. For example, some developers may think of "browser extensions" as "web extensions." However, a search for "web extensions" doesn't find a direct link (the best is through a glossary item but the follow on link may be missed.)

**Comment by HerminaC** [comment]
@caugner please don't start working on this until we've discussed it. Thx!

**Comment by caugner** [comment]
As pointed out by @schalkneethling, a "Web extensions" link was recently added to the [Web technology](https://developer.mozilla.org/en-US/docs/Web) overview page as part of https://github.com/mdn/content/pull/13491 to make these pages easier to access.

Seeing other important technologies like "WebAssembly", "SVG" and "MathML" without a menu item also makes me wonder whether "Web extensions" are really that important that they warrant a dedicated menu item.

As for the problem that a search for "web extensions" doesn't yield the right page, it might make sense to simply rename the page title from "Browser extensions" to "Web Extensions".

**Comment by kewisch** [comment]
WebExtensions are not specific technologies similar to SVG/MathML, they are a framework for a number of Web APIs and Extension APIs. I'd prefer if we keep a top level item as before. Let's also keep it at "Browser Extensions" for now, someone from my team will get back in case this needs changing.

See [here for information on terminology](https://wiki.mozilla.org/Add-ons/Terminology), though this page hasn't been updated since legacy extensions. In practice, we've kept the use of WebExtensions instead of just going with extensions.

**Comment by Rumyra** [comment]
> WebExtensions are not specific technologies similar to SVG/MathML, they are a framework for a number of Web APIs and Extension APIs. I'd prefer if we keep a top level item as before. Let's also keep it at "Browser Extensions" for now, someone from my team will get back in case this needs changing.

Agreed from a content perspective - as you said @caugner let's create something actionable. This would be to add a link in the top menu for Web Extensions. The 'Web Technology' overview page that was updated is inclusive of lots of different sections - we should discuss 👍

**Comment by mixedpuppy** [comment]
@Rumyra is there any update on discussing this item?  Would be nice to reach a conclusion.

**Comment by Rumyra** [comment]
Thanks for the nudge @mixedpuppy - I'll flag it to the team now 👍
