### ISSUE TITLE
Nginx Deployment

### ISSUE THREAD

**Issue by ganapathichidambaram** [mdn/yari#5889]
Hi,
I would like to understand this code into production deployment using nginx or other web server. 

can anybody share nginx configuration file for the same.

**Comment by caugner** [comment]
We're currently using a combination of AWS CloudFront, AWS Lambda and AWS S3 to deploy yari, so we don't have any advice for deploying it with nginx.

PS: You would want to run `yarn build` and host the `client/build` folder with any static webserver, but we cannot provide any assistance.
