### ISSUE TITLE
A decent CSS grid

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#59]
We currently have a super basic CSS skeleton based on [water.css](https://watercss.netlify.com/) plus our own dumping groud [`mdn.scss`](https://github.com/mdn/stumptown-renderer/blob/master/client/src/mdn.scss) where we've ported some necessary CSS stuff to display the pages correctly. 

What would be nice is a ground-up solid CSS framework with a decent grid and a decent header and footer. 
It should be responsive at least.

**Comment by schalkneethling** [comment]
Happy to take this one.

**Comment by peterbe** [comment]
Perhaps this needs to be renamed to a task etc. Perhaps it should be called "Incorporate minimalist in Yari" or "Rewrite SCSS framework" :)

**Comment by schalkneethling** [comment]
> Perhaps this needs to be renamed to a task etc. Perhaps it should be called "Incorporate minimalist in Yari" or "Rewrite SCSS framework" :)

I notice that this one is assigned to me https://github.com/mdn/yari/issues/708 🤷‍♂️

**Comment by tobinmori** [comment]
Replaced by design system
