### ISSUE TITLE
Compat table doesn't display Firefox icon

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/yari#5904]
### Summary

Icon of Firefox is not displayed on Chromium based browsers(I tested on desktop chrome and edge) in Browser Compatibility Table.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/repeat#browser_compatibility

### Reproduction steps

1. Open Chrome
2. Go to [Compat Table](https://developer.mozilla.org/en-US/docs/Web/CSS/repeat#browser_compatibility)
3. Check Firefox icon

### Expected behavior

Icon is supposed to be shown on all browsers.

### Actual behavior

It is displayed on FIrefox & Safari, but not on Chromium, Edge, Opera

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://user-images.githubusercontent.com/100634371/161617577-170aa732-2da8-42eb-ad02-f2f75550b5c1.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by danielhjacobs** [comment]
Interesting. I didn't add that icon separately in https://github.com/mdn/yari/pull/5749 because I saw it existed already: https://github.com/mdn/yari/blob/main/client/src/assets/icons/firefox.svg. I guess it's not included in browsers other than Firefox. I wonder where in the code is responsible for adding/removing it.

**Comment by danielhjacobs** [comment]
`<svg class="icon" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg" aria-hidden="true"><path d="M14.389 3.133a7.96 7.96 0 0 0-.696-.795 6.28 6.28 0 0 0-.636-.584c.129.113.253.231.37.357a4.48 4.48 0 0 1 .976 1.625c.418 1.263.39 2.844-.407 4.085-.95 1.48-2.498 2.21-4.171 2.174a3.38 3.38 0 0 1-.218-.006c-3.003-.18-3.76-3.252-2.198-4.58-.421-.09-1.213.087-1.764.91-.494.737-.467 1.877-.161 2.685A4.316 4.316 0 0 1 5.09 7.74c-.395-2.663 1.398-4.935 3.042-5.497-.887-.773-3.11-.72-4.764.493-.964.708-1.654 1.714-2.017 2.913.053-.673.308-1.678.831-2.704C1.63 3.23.924 4.135.576 4.972.074 6.18-.103 7.624.056 8.998l.037.309A8.01 8.01 0 1 0 14.39 3.133Zm.014.603a4.48 4.48 0 0 0-.976-1.625c-.51-.55-1.146-.97-1.82-1.295A8.109 8.109 0 0 0 9.82.184a7.983 7.983 0 0 0-3.313-.02C5.37.404 4.37.894 3.739 1.508c.474-.288 1.135-.52 1.606-.64 2.186-.55 4.593.046 6.234 1.617.33.315.626.669.866 1.058.98 1.588.887 3.584.123 4.761-.567.875-1.781 1.696-2.914 1.687 1.738.09 3.359-.64 4.342-2.17.798-1.241.825-2.822.407-4.085Z" fill="currentColor"/></svg>`:

If this svg replaced https://github.com/mdn/yari/blob/main/client/src/assets/icons/firefox.svg, that would work, but it may have knock-on effects. It could be saved with a separate name, but that would necessitate a change to these areas: https://github.com/mdn/yari/blob/b0ae6599c5c0ab7328650ad1ea18f5c92f8b9855/client/src/document/ingredients/browser-compatibility-table/headers.tsx#L57 https://github.com/mdn/yari/blob/b0ae6599c5c0ab7328650ad1ea18f5c92f8b9855/client/src/ui/atoms/icon/index.scss#L4
