### ISSUE TITLE
Search results page touching the left side of the window  

### ISSUE THREAD

**Issue by sylbru** [mdn/yari#5918]
### Summary

There is no padding on the left side in the results page, causing the text to touch the left side of the window.
It happens from the breakpoint at 769px and until reaching 1440px (`var(--max-width)` when the content stops expanding.    

### URL

https://developer.mozilla.org/en-US/search?q=use

### Reproduction steps

1. Go to a search URL like https://developer.mozilla.org/en-US/search?q=use
2. Make sure your viewport width is between 769px and 1440px

### Expected behavior

Text should never touch the edge of the window/screen.

### Actual behavior

Text does touch the edge of the window.

### Device

Laptop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Screenshot

![image](https://user-images.githubusercontent.com/3757523/161945440-bc7232ec-fd0a-4d39-b33f-35162879e846.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by schalkneethling** [comment]
Thank you @sylbru! this page needs some love for sure.

**Comment by caugner** [comment]
This already been fixed in https://github.com/mdn/yari/pull/5987. 🎉
