### ISSUE TITLE
Move update state management to the service worker.

### ISSUE THREAD

**Issue by fiji-flo** [mdn/yari#5920]
Part of the is to simplify `setOfflineSettings`.

The plan is to manage state in indexedDB. The client will trigger update/clean via messaging but then poll for the state in the `MDNWorker` triggering a re-render on changes.

**Comment by mirunacurtean** [comment]
I went through the whole new profile> enable offline > download offline> refresh page> finish unpacking> clear data> download again> navigate away from offline page and return> finish unpacking for the second time  process.  With the note that it takes from in-between a few seconds to tens of seconds (Firefox) to return to the unpacking process after an interrupt, the status updates have been successful.
![image](https://user-images.githubusercontent.com/53306802/164229842-d295b074-4159-4216-b6e9-d18dd20b5b65.png)
