### ISSUE TITLE
Content bug: Black text on dark theme.

### ISSUE THREAD

**Issue by 7heMech** [mdn/yari#5924]
## What page(s) did you find the problem on?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise

## Specific page section or heading?

Browser compatibility

## What is the problem?

Using a phone(or using a display of that size) clicking on a browser name for more details opens up a menu where the text is black on dark mode, as you can see in this screenshot ![screenshot](https://user-images.githubusercontent.com/83923848/162174859-ebd0765a-1462-4bc2-b541-909354bdf8f9.jpg)

## What did you expect to see?

I expected to see readable text.

The solution:
Adding `color: var(--text-primary)` inside of `button {}` in CSS (I tried finding that, but I couldn't find any CSS in the repo...)

**Comment by sideshowbarker** [comment]
@7heMech If possible, can you please add a screenshot here which shows the problem described in the issue description?

**Comment by 7heMech** [comment]
> > I think this may have been caused by the user agent Stylesheet in Chrome.
> 
> I think it is, though it appears Firefox has something similar. The color for a button is set based on dark/light mode apparently, using some special property called -internal-light-dark. The text here is inside a button on mobile, but separate from the button on Desktop, which explains the difference.

Well... Yes, every browser has a user agent stylesheet and they shouldn't be much different, so I wouldn't be surprised.(the issue is caused by -internal-light-dark in Chrome as well)
