### ISSUE TITLE
Foldersearch backslash & empty result handling

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#593]
`node content build -l en-us -f web/api` blows up on windows with a non-descript error, ultimately due to no folder found containing forward slashes. Folder search should probably just work for both slashes and backslashes.

Also we should throw a descriptive error when nothing matching the query is found.

**Comment by peterbe** [comment]
Are you referring to this error:
<img width="724" alt="Screen Shot 2020-05-15 at 7 27 36 AM" src="https://user-images.githubusercontent.com/26739/82045753-9e5a0700-967d-11ea-9cc0-03e797d6220c.png">

That's a regression at some point. Most likely the big ks renderer thing that upended most of the `build` CLI.

**Comment by Gregoor** [comment]
Oh yes, good point, I should've added the log. That's exactly the one
