### ISSUE TITLE
Irregularities in Mandala SVG

### ISSUE THREAD

**Issue by PROxZIMA** [mdn/yari#5930]
### Summary

The header background (Mandala) on `MDN Web Docs` homepage caught my attention. But the SVG seems a bit irregular. Further lookup bought me to [`mandala/index.scss`](https://github.com/mdn/yari/blob/main/client/src/ui/molecules/mandala/index.scss) and [`mandala/index.tsx`](https://github.com/mdn/yari/blob/main/client/src/ui/molecules/mandala/index.tsx).

- `index.scss`
  - `.mandala-container` doesn't include `--mandala-accent-5`
  - `.mandala-accent-4 > textPath > tspan { }` doesn't exist
- `index.tsx`
  - Due to line-brakes in [`L120-L140`](https://github.com/mdn/yari/blob/021c8cdf9c55a10b961aab3e26f932a9589263d4/client/src/ui/molecules/mandala/index.tsx#L120-L140), the circles looks segmented in-between.
  - [`mandala-accent-4`](https://github.com/mdn/yari/blob/021c8cdf9c55a10b961aab3e26f932a9589263d4/client/src/ui/molecules/mandala/index.tsx#L170-L177) doesn't have any `<tspan></tspan>` so `animateColors` won't work on this circle
  - MDN Plus product page Mandala's 4th circle spin bug
    - https://github.com/mdn/yari/blob/e9bae54c292016d3f064c14aac6a5e253b6e9af6/client/src/ui/molecules/mandala/index.tsx#L95-L96

### URL

- https://developer.mozilla.org/en-US/
- https://github.com/mdn/yari/tree/main/client/src/ui/molecules/mandala

### Reproduction steps

1. Visit [`MDN Web Docs`](https://developer.mozilla.org/en-US/) and [`MDN Plus`](https://developer.mozilla.org/en-US/plus)
2. Inspect `mandala-container` via `Developer Tools`

### Expected behavior

Resultant Mandala SVG should not have above mentioned irregularities.

### Actual behavior

Resultant Mandala SVG has above mentioned irregularities.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Screenshot

![Screenshot from 2022-04-07 22-17-06](https://user-images.githubusercontent.com/43103163/162256057-19779bad-e740-4bd3-ac83-d7f40664aa4e.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by schalkneethling** [comment]
Hey @PROxZIMA! Thank you for reporting this. Before we dig deeper, are you seeing any specific problem with the SVG when viewed in the browser? There is a difference between the mandala on the landing page and the one on the Plus product page.

the homepage mandala rotates, but the colors are not meant to animate. On the [Plus page(https://developer.mozilla.org/en/plus], the colors animate _and_ the mandala rotates.

**Comment by PROxZIMA** [comment]
> are you seeing any specific problem with the SVG when viewed in the browser

No, There is no issue with the SVG itself. It just caught my attention and after detailed inspection I thought that it is missing some fine tuning which I mentioned above.

Also as the above image states, is it by design that the Mandala circles should be segmented?

**Comment by schalkneethling** [comment]
> Also as the above image states, is it by design that the Mandala's circles are segmented (have `&nbsp;` in the `<textPath>`)?

I reckon it is worth us running this through SVGOMG.

**Comment by schalkneethling** [comment]
@PROxZIMA looks like this was resolved by https://github.com/mdn/yari/pull/5941, correct?

**Comment by PROxZIMA** [comment]
Yep, we can close this issue. Thanks!!
