### ISSUE TITLE
Search keyboard shortcut

### ISSUE THREAD

**Issue by pickfire** [mdn/yari#5935]
### MDN URL

all

### What specific section or headline is this issue about?

Search keyboard shortcut

### What information was incorrect, unhelpful, or incomplete?

There are no keyboard shortcut to invoke search, have to manually go click on that small area at the top to search.

### What did you expect to see?

Something like <kbd>alt</kbd><kbd>shift</kbd><kbd>f</kbd> like those in media wiki pages or <kbd>s</kbd> or <kbd>/</kbd> like those in other documentation, when press it allows user to type in the text to start searching.

**Comment by danielhjacobs** [comment]
This already exists: use the / key:

https://github.com/mdn/yari/blob/e9bae54c292016d3f064c14aac6a5e253b6e9af6/client/src/search-utils.ts#L11-L34

I'm unsure if that's documented anywhere though.

**Comment by pickfire** [comment]
Thanks, I am not aware of that, maybe because vimium overrides `/` by default so I didn't notice that.

**Comment by caugner** [comment]
We would gladly accept a PR that adds <kbd>Ctrl</kbd> / <kbd>⌘</kbd> + <kbd>K</kbd>, in addition to the `/` shortcut.
