### ISSUE TITLE
Include the class constructor in the left navigation panel

### ISSUE THREAD

**Issue by ygoe** [mdn/yari#5942]
### Summary

The left panel includes the class description, its methods, properties, inheritance, and everything. But not the constructor. That was what I was looking for. I only got there by the panel on the right of the class overview page, and following another link to this page.

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/Promise

### Reproduction steps

Look for the current page on the left side, it's not there.

### Expected behavior

-

### Actual behavior

-

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by wbamberg** [comment]
I think this is a bug.

What I think happened here: in the old days, we didn't have separate constructor pages for the JS docs, we just had one page for the class overview and the constructor. Then @Elchi3 wrote constructor pages for them, but I guess we never updated the sidebars to show them.

Regardless, I think it would be good to have a link to the constructor in the sidebar. For consistency it feels like it would be nice to have a "Constructor" drop-down alongside "Methods", and have the link there, although it would be a bit weird as there is only one.

**Comment by ygoe** [comment]
Then why add a collapsible group if it only takes up unnecessary space? Just put the constructor entry directly in its place.

**Comment by wbamberg** [comment]
That could look something like:

<img width="324" alt="Screen Shot 2022-09-13 at 12 12 43 PM" src="https://user-images.githubusercontent.com/432915/189989603-18562904-f310-4b4f-9121-e61449ccae1b.png">

**Comment by wbamberg** [comment]
Actually a collapsible group would be consistent with the Web/API docs: https://developer.mozilla.org/en-US/docs/Web/API/XRRigidTransform/XRRigidTransform

<img width="318" alt="Screen Shot 2022-09-15 at 3 12 53 PM" src="https://user-images.githubusercontent.com/432915/190517929-8dd93623-5800-4cfd-8aa0-8ed0e0ff90a5.png">

**Comment by caugner** [comment]
A collapsible group saves horizontal space, and that's relevant for longer API names:

<img width="906" alt="image" src="https://user-images.githubusercontent.com/495429/197538942-a76b431c-8b31-41f9-8292-703bb802858a.png">

Let's go for the collapsible group for now.
