### ISSUE TITLE
BCD: The assumption about currentSupport being the most recent support item is faulty

### ISSUE THREAD

**Issue by danielhjacobs** [mdn/yari#5945]
### Summary

Current support is defined as the most recent support item:

https://github.com/mdn/yari/blob/e93d4a542aca26315da3b8a92573f9e2e78c92a8/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx#L139

However, look at innerHeight for Firefox on https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight#browser_compatibility. It's had full support since version 1, but a removed note in effect from version 4-24. Because that item is newer and was removed, it looks like it has no support.

### URL

https://developer.mozilla.org/en-US/docs/Web/API/Window/innerHeight#browser_compatibility

https://developer.mozilla.org/en-US/docs/Web/API/Window/innerWidth#browser_compatibility

### Reproduction steps

1. Go to above pages
2. Go to BCD
3. Click Firefox BCD cell

### Expected behavior

Full support should be shown, since at least one un-removed item has full support.

### Actual behavior

No support is shown, since the most recent support item has been removed.

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![support_none_full](https://user-images.githubusercontent.com/29206584/162641264-bbbc547d-2a54-4679-9dea-9c34200e2762.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
FWIW Here is the corresponding BCD data:

https://github.com/mdn/browser-compat-data/blob/78319d5881bd91d8b1a63b69de9da38182cf9a43/api/Window.json#L3152-L3161

I guess we could also _automatically_ rewrite cases like this (as part of the build process) from:

 ```json
[
              {
                "version_added": "1"
              },
              {
                "version_added": "4",
                "version_removed": "24",
                "notes": "..."
              }
            ]
```

to

```json
[
              {
                "version_added": "1"
                "version_removed": "4",
              },
              {
                "version_added": "4",
                "version_removed": "24",
                "notes": "..."
              },
              {
                "version_added": "24"
              }
            ]
```

Because this is essentially what the above means (and how it should probably be displayed).

**Comment by ddbeck** [comment]
Generally, I agree with the overall thrust. I suspect the logic about which statement to use the primary one is going to be a bit complex, prioritizing non-prefixed, non-flagged, non-preview values, non-`version_removed` statements ahead of others. That said, in this particular case, the data was a bit poor. I've opened https://github.com/mdn/browser-compat-data/pull/15798 to fix it in BCD.
