### ISSUE TITLE
Make the 404 page useful

### ISSUE THREAD

**Issue by ddbeck** [mdn/yari#5973]
## Summary

Some pages 404 for good, but unexplained reasons. The 404 page should help MDN readers find the content they're looking for with a prominent search box, links to mdn/archived-content, Firefox Source Docs, the Wayback Machine, or to raise an issue on mdn/content.

## Making the 404 page useful

Over the years, lots of content has been removed from MDN, for many reasons including:

- It moved elsewhere (e.g., https://firefox-source-docs.mozilla.org/)
- It was archived (i.e., put in https://github.com/mdn/archived-content)
- It was deleted (e.g., irrelevant content)

Some of these removals have been supported by useful redirects. However, in many cases, there's no sensible redirect because there's no plausible replacement content on or off MDN, or the removal was simply mismanaged. In those cases, we should provide a 404 page that actually helps readers find the content they're looking for.

The 404 page could help by linking mdn/archived-content, Firefox Source Docs, the Wayback Machine, or to the form to create a new issue on mdn/content. Ideally, the last option would only apply when the document referrer is on MDN itself.

## Related issues

Inspired by this comment from @Gitoffthelawn: https://github.com/mdn/yari/issues/5484#issuecomment-1078669637

**Comment by OnkarRuikar** [comment]
For starters we can at least give directions where to find these pages.
For example like the google search:
> ![google](https://i.imgur.com/lhY80In.png)

we can have the suggestion list like:
- try searching the term in search box, the page may have moved to new location on the same site
- try on Wayback Machine: https://web.archive.org/web/*/https://developer.mozilla.org/en-US/docs/Learn (here we show preconstructed url.
- try something something
- ....

And some cool Mozilla dinosaur art would be nice.

**Comment by Gitoffthelawn** [comment]
@OnkarRuikar

Those are all great ideas!

For your first point, I think also directing the user to use terms that may yield good results.  Or, even better, add search keywords to specific pages that may benefit from such additions.

BTW, your Wayback Machine trick of using an asterisk is quite clever and useful.  Is that trick (and perhaps similar ones) documented somewhere?

**Comment by schalkneethling** [comment]
Closing in favor of the following discussion: https://github.com/mdn/mdn-community/discussions/125 - Please continue sharing your ideas, everyone. Thanks!
