### ISSUE TITLE
404 Page layout incorrect

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#5986]
### Summary

The 404 page seems to be using an incorrect content wrapper causing the layout be incorrect.

### URL

https://developer.mozilla.org/en-US/Using_native_JSON

### Reproduction steps

1. Open https://developer.mozilla.org/en-US/Using_native_JSON
2. Notice that there are large gaps between each line of text

### Expected behavior

Something closer to the following screenshot

![Screenshot showing a layout where the spacing between the three lines of text is not widely spaced apart](https://user-images.githubusercontent.com/10350960/163579550-ba59defd-62dc-448f-933b-8b0d9fea69d7.png)

### Actual behavior

See screenshot

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

![Screenshot 2022-04-15 at 15 51 31](https://user-images.githubusercontent.com/10350960/163579009-9bf35f4f-61fb-4cd2-9ba1-1cd2a965215b.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by schalkneethling** [comment]
The search results page has the same problem: https://developer.mozilla.org/es/search?q=midnight
A larger issue is that this page needs some love.

**Comment by caugner** [comment]
If we add the `article-wrapper` class to the `div.page-not-found`, the 404 Page already looks like this:

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/495429/163627346-54928e53-fcdb-4ffa-881f-d616ec4ef7b1.png">

We could rename `article-wrapper` to `main-wrapper` to fix the semantics.
