### ISSUE TITLE
Sidebar: French translations out of date or missing

### ISSUE THREAD

**Issue by glmvc** [mdn/yari#5994]
As discussed in pr #5164, @cw118 noticed that the French translations in LearnSidebar.ejs are almost all missing or incomplete.
We thought it would be a good idea to make an issue so it wouldn't be forgotten.
_If this is already on todo somewhere, then please ignore this issue - sorry._

Example URL: https://developer.mozilla.org/fr/docs/Learn/HTML/Multimedia_and_embedding/Other_embedding_technologies

Expected behavior: To see the French translations in the sidebar

Actual behavior: Seeing the Englisch version of it (because this is default?)

**Comment by schalkneethling** [comment]
@SphinxKnight 🔔

**Comment by SphinxKnight** [comment]
Thanks a lot @glmvc @schalkneethling, let's fix this 🙏

**Comment by SphinxKnight** [comment]
"Meta" issue over https://github.com/mdn/translated-content/issues/5135

**Comment by caugner** [comment]
Closing this issue in favor of https://github.com/mdn/translated-content/issues/5135.
