### ISSUE TITLE
Heading elements are not in a sequentially-descending order

### ISSUE THREAD

**Issue by Mohammad-Nikkhah** [mdn/yari#6000]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web

### What specific section or headline is this issue about?

Lighthouse heading levels audit fails

### What information was incorrect, unhelpful, or incomplete?

**Lighthouse**  flags pages whose headings skip one or more level

### What did you expect to see?

Observe the rules of the Lighthouse

### Do you have any supporting links, references, or citations?

https://web.dev/heading-order/?utm_source=lighthouse&utm_medium=devtools

### Do you have anything more you want to share?

![Screenshot (9)](https://user-images.githubusercontent.com/78091800/163874455-0d62f38b-0241-4148-a577-fc6b74813311.jpg)

**Comment by danielhjacobs** [comment]
This had been fixed by https://github.com/mdn/yari/pull/4107, but the redesign reverted that change (see https://github.com/mdn/yari/commit/dbaddf2c7578cde358dd974b35587d22b63d94dd#diff-ab2fc38f339970a01b3deed0ecd9c0109dda310982ab640a9ed2975a45312381)

**Comment by Mohammad-Nikkhah** [comment]
nice
