### ISSUE TITLE
BCD support history has wrong notes symbol behind version range

### ISSUE THREAD

**Issue by caugner** [mdn/yari#6009]
### Summary

In the BCD support history, icons are now shown behind the version numbers, but the notes symbol displays as a circle instead of an asterisk.

### URL

- http://localhost:3000/en-US/docs/Web/API/Window#browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/API/Window#browser_compatibility

### Reproduction steps

1. Go to _Window#browser_compatibility_.
2. Open the support history for Window.alert in Opera.
3. See a grey circle behind the (version) 3.

### Expected behavior

An asterisk symbol should be shown.

### Actual behavior

A circle symbol is shown.

### Device

Desktop

### Browser

Firefox

### Browser version

Pre-release (e.g. Beta, Nightly or Canary)

### Operating system

Mac OS

### Screenshot

# Before

<img width="780" alt="image" src="https://user-images.githubusercontent.com/495429/164114566-315af98a-2fe8-4f73-9f24-6338c5b2efa2.png">

# After

<img width="780" alt="image" src="https://user-images.githubusercontent.com/495429/164114590-573514fb-2843-42c3-b349-fd26962c877d.png">

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by danielhjacobs** [comment]
Worth noting this isn't actually regression since that symbol within the timeline has always shown blank.  It just wasn't a real issue before since the only place it appeared it didn't look bad.

**Comment by danielhjacobs** [comment]
The fix would probably be to move this rule under `bc-supports-dd`, instead of just `bc-notes-list`:

https://github.com/mdn/yari/blob/8c3a7bcaa06f4e833c6a686664e1f55d0efe85dc/client/src/document/ingredients/browser-compatibility-table/index.scss#L209-L214
