### ISSUE TITLE
Add 'Latest news' section to MDN homepage

### ISSUE THREAD

**Issue by HerminaC** [mdn/yari#6020]
Section needs to include the  titles of the three latest blog posts from Hacks. Titles need to be links and behave similarly to the ones in the 'Recent contributions' section. If blog post is newer than 1 week, a 'New' label will be displayed next to the post title. 
Ideally, results to be shown need to be imported from Hacks.

**Comment by caugner** [comment]
We may be able to use the category feed: https://hacks.mozilla.org/category/mdn/feed/
