### ISSUE TITLE
DOMException: IntersectionObserver constructor with Firefox ESR

### ISSUE THREAD

**Issue by darim92** [mdn/yari#6021]
### Summary

mdn docs throws error on firefox esr 91 resulting in blank pages.

Error: DOMException: IntersectionObserver constructor: rootMargin must be specified in pixels or percent
File: hooks.ts:324

Occurs when you pass rootMargin as empty string before firefox 96.

### URL

https://developer.mozilla.org/en-US/docs/Web/API/Streams_API

### Reproduction steps

1. Open URL with Firefox ESR 91

### Expected behavior

docs page

### Actual behavior

blank page

### Device

Desktop

### Browser

Firefox

### Browser version

Extended Support Release

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by schalkneethling** [comment]
Fixed in https://github.com/mdn/yari/pull/6030. Thank you for letting us know @darim92!
