### ISSUE TITLE
disappearing web pages

### ISSUE THREAD

**Issue by ovideplouffe** [mdn/yari#6035]
I am using Firefox 91 ESR 32-bit.

I never had problem everytime I tried to access MDN's website to look at anything pertaining to HTML, SVG, MathML, CSS, you name it.

Today I tried to access MDN's website but only the page at the following address 

https://developer.mozilla.org/en-US/

is displayed by the browser. Any other page linked from this main page is shown as a blank page even if clicking the link on the main page opens a tab with the appropriate title (e.g., clicking in Featured Articles the link for the HTML Dialog Element will open a tab with <dialog>: The Dialog element ... but only a blank page is shown). The page content is loaded for sure because I can see the HTML code behind it if I press CTRL+U to look at the page source in another tab. I can even save the page if I press CTRL+S. 

More important to you perhaps, if I press CTRL+SHIFT+I to open the console in the Web Developer Tools, I see a lot of errors. I also see a lot of errors for the only page that shows something (the abovementioned main page) but on the blank pages, 3 more errors stand out:

- DOMException: IntersectionObserver constructor: rootMargin must be specified in pixels or percent     react-dom.production.min.js:216:199
- DOMException: IntersectionObserver constructor: rootMargin must be specified in pixels or percent     react-dom.production.min.js:216:199
- Uncaught DOMException: IntersectionObserver constructor: rootMargin must be specified in pixels or percent     main.d5b17c14.chunk.js:1

This happens whether addons (NoScript and uBlock Origin) are enabled or disabled.

This never happened to me before. I am more than puzzled. Thanks in advance for your help.

**Comment by amc1804** [comment]
I am experiencing the same symptoms and the same error messages, starting today, running firefox 91.5.0esr (64-bit) on Linux.

**Comment by danielhjacobs** [comment]
This should have been fixed by #6030. It was caused by https://bugzilla.mozilla.org/show_bug.cgi?id=1738791

**Comment by ovideplouffe** [comment]
I just tested MDN's website to see if a solution to the problem I described yesterday had been found. Obviously, yes, because I am now able to browse MDN's website without problem.

Being a newbie to GitHub, I don't know what to do now that everything is OK except by answering my own message. Is there another way to do it?

Thanks in advance for your help.

**Comment by ovideplouffe** [comment]
Looks like clicking on "Close with comment" just did it!
