### ISSUE TITLE
Creative Commons License link does not work with MDN Offline

### ISSUE THREAD

**Issue by ExploreLearnMake** [mdn/yari#6036]
### MDN URL

https://developer.mozilla.org/en-US/

### What specific section or headline is this issue about?

Page footer

### What information was incorrect, unhelpful, or incomplete?

The "a Creative Commons License" link within the footer of all pages leads to a 404 error page. It is pointing to https://developer.mozilla.org/docs/MDN/About#Copyrights_and_licenses

### What did you expect to see?

The About page with the licensing information. 

### Do you have any supporting links, references, or citations?

I believe the correct URL is missing the "en-us" folder and should be pointing to the following URL based upon the folder structure in GitHub: https://developer.mozilla.org/en-US/docs/MDN/About#copyrights_and_licenses

### Do you have anything more you want to share?

However, the "About" link in the footer under the MDN heading points to https://developer.mozilla.org/en-US/about, which is a different "About" page that does not include the licensing information. So, I'm not sure if it should be pointing to the one above or if the "About" page also in the footer needs to be modified to include the licensing information and the Creative Commons link points to that instead of the one found within the "en-us" folder.

**Comment by Rumyra** [comment]
@schalkneethling should we add this to the yari project board?

**Comment by schalkneethling** [comment]
> @schalkneethling should we add this to the yari project board?

Done.

**Comment by caugner** [comment]
MDN Offline only offers a limited functionality, and redirecting from URLs without a locale is not supported.

However, we can add the locale to the footer link here:
https://github.com/mdn/yari/blob/52e41038cce87d2a35768d7c428727d819763315/client/src/ui/organisms/footer/index.tsx#L228-L230

@ExploreLearnMake Would you like to open a PR for this?

**Comment by rohini-ranjanR** [comment]
Can I contribute to this, I also got a problem the link is linked to the wrong page. The link should be linked to https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Attrib_copyright_license here we can have creative common license not to https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines.

**Comment by ExploreLearnMake** [comment]
@rohini-ranjanR If you wish to create a PR to fix this issue, I am OK with that.
