### ISSUE TITLE
Right side menu section highlighting is wrong

### ISSUE THREAD

**Issue by pmario** [mdn/yari#6041]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn

### What specific section or headline is this issue about?

right side menu section highlighting doesn't work as expected

### What information was incorrect, unhelpful, or incomplete?

To reproduce: 

I'm using FF 99.0.1 on Windows 11

- open: https://developer.mozilla.org/en-US/docs/Learn
- Click: "Where to start" in the right side menu -> OK -> Screenshot 1
- Click: "Topics covered" -> The content scrolls to the right anchor link. BUT 
  - The highlighting in the right menu is set to "Where to Start"
  - See screenshot 2
- **It's also wrong if the body element is scrolled. It seems the body anchors and the highlighting are not in sync.** ... There are probably more pages, but that's the one it happens to me

Screenshot 1) 
![image](https://user-images.githubusercontent.com/374655/164715326-430c41ba-a893-48af-ab0b-fb2cdbab6be7.png)

Screenshot 2) 
![image](https://user-images.githubusercontent.com/374655/164715702-0773b621-dc83-42de-ad1b-96e160cc953e.png)

### What did you expect to see?

The highlighting in the menu should correspond to the text in the content body. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/learn`
* MDN URL: https://developer.mozilla.org/en-US/docs/Learn
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/learn/index.md
* Last commit: https://github.com/mdn/content/commit/ac89e5279f00f7c656262ff451a5962bfe34f296
* Document last modified: 2022-04-10T04:48:50.000Z

</details>

**Comment by schalkneethling** [comment]
Also see: https://github.com/mdn/yari/issues/6061

**Comment by schalkneethling** [comment]
Also see: https://github.com/mdn/yari/issues/6064

**Comment by schalkneethling** [comment]
Also see: https://github.com/mdn/yari/issues/6078
