### ISSUE TITLE
Next/previous button style is broken

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#6042]
See for example https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Selectors

This has "previous/up/next" nav buttons at the start end end of the page. The ones at the top are OK:

********

<img width="845" alt="Screen Shot 2022-04-22 at 2 30 35 PM" src="https://user-images.githubusercontent.com/432915/164798499-ab86ae3e-e851-41e1-a398-1488369a27a2.png">

********

...the ones at the bottom aren't:

********

<img width="843" alt="Screen Shot 2022-04-22 at 2 31 46 PM" src="https://user-images.githubusercontent.com/432915/164798605-77095241-c881-4fab-ab01-a50fbb220eae.png">

**Comment by caugner** [comment]
I think this is a side-effect of #5908.
