### ISSUE TITLE
#show-flaws anchor link broke

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#605]
### Steps to reproduce:

1. You need to visit at least one page (with flaws) first or run `node content build -l en-us -f web/html`
2. Go to http://localhost:3000/en-US/_flaws
3. Click on any of the listed documents

### Expected result:
That it scrolls you to the bottom where the flaws are listed

### Actual result:
No scrolling happens

I think it broke in
https://github.com/mdn/yari/pull/586/commits/5a2fb413b815d1b4315c4b46a790745daa2f8f7b
which I merged into the big Flaws PR but failed to notice.

**Comment by peterbe** [comment]
Wanna take a stab at this one @Gregoor ?

**Comment by Gregoor** [comment]
Yes, I shall unbreak my breakings
