### ISSUE TITLE
Feedback on new sticky header

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#6051]
Funnily enough, I spent the time tracking down these feedback pages to ask that the header stickiness be removed on desktop for accessibility reasons. I'll just post a comment here instead of creating a new issue. 

@[galich](https://github.com/galich), you correctly point out the advantages of a sticky header, but there are some major downsides. Namely: 

1. It reduces the space available for content, which is especially problematic on horizontally oriented displays and when the page is zoomed in for eyesight reasons.
2. As currently implemented, it breaks the table of contents in the sidebar.  

### Example of problem number 2:

Take a look at the following screenshot. This was taken immediately after clicking the "Specifications" navigation link in the table of contents on the right. There are three problems here:
- The page has been scrolled to the wrong position. The navigation button must sometimes be clicked twice to properly scroll to the correct position (This behavior occurs inconsistently, but on both Windows and Mac OS.)
- The "Example" section is highlighted as the current position in navigation, despite no portion of that section being visible. 
- Despite not moving my cursor, it is now hovering over the "Browser Compatibility" link. (This wouldn't be such an issue if not for the need to double click the navigation.) 

![image](https://user-images.githubusercontent.com/42920487/164959414-f7fcd028-7845-4b84-a157-6fe27bc12296.png)

The first two problems are caused by the sticky header. The third is in some sense caused by the navigation bar not being sticky enough.

### Suggestions

My general feeling is that sticky headers are sensible design on mobile, because the screen is vertically large, there is no room for sidebars, and scrolling to the top of the page is difficult. But on desktop, a sticky header is poor design because there is less vertical space available and more horizontal space, because returning to the top of the page requires only a single keystroke, and because the always-visible url renders breadcrumbs largely redundant.

Ideally, what I would like to see is to:

- Keep the sticky header on mobile.
- Completely remove header stickiness on desktop. 
- On desktop, move the search bar from the header to one of the sidebars.
- Give the table of contents a more fixed position, instead of having it scroll but only a tiny amount.

_Originally posted by @bacontime in https://github.com/mdn/yari/issues/5521#issuecomment-1107775508_

**Comment by schalkneethling** [comment]
Hey there @bacontime! I believe this deserves its own issue and so I created this from you very detailed comment. I terms of completely removing this from desktop, not sure this will be the correct approach. What if we gave readers the option to disable the sticky header?

Thank you again for your feedback.

**Comment by caugner** [comment]
We have already addressed the reported problems in #6148 and #6170. 🎉
