### ISSUE TITLE
Extra underscore at end of page titles.

### ISSUE THREAD

**Issue by jpmedley** [mdn/yari#6066]
### Summary

See the screenshot.

### URL

https://developer.mozilla.org/en-US/docs/Web/Manifest

### Reproduction steps

NA

### Expected behavior

Title's should not appear to have characters that aren't part of the title.

### Actual behavior

Title's have an extra underscore.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

https://developer.mozilla.org/en-US/docs/Web/Manifest

### Anything else?

Chrome stable = Chrome 100

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by schalkneethling** [comment]
Thank you for filing @jpmedley. As @danielhjacobs there is already an issue for this(#6044). Therefore, we have referenced this issue in the original and will close this as a duplicate.
