### ISSUE TITLE
Prettier's Markdown prose wrap shouldn't apply to h2m results

### ISSUE THREAD

**Issue by alattalatta** [mdn/yari#6075]
#6032 introduced Markdown prose wrap within this repo. As an unfortunate side effect, it's also affecting the results of `h2m` CLI command because `remark-prettier` respects `.prettierrc`.

**Background: Prettier's print width is 80 in default. [CJK characters are fullwidth whereas English, numbers and such are halfwidth](https://en.wikipedia.org/wiki/Halfwidth_and_Fullwidth_Forms_(Unicode_block)).**

The following image is h2m-converted `Document` interface for `l10n-ko`. Please note the first line I highlighted:

<img width="543" alt="image" src="https://user-images.githubusercontent.com/9212605/165332250-077cbcdd-c43e-4de7-b8a9-feb9b898905a.png">

It's only 49 characters, which is too short to be meaningful. It's because Prettier counts fullwidth characters as 2 for calculating print width.

<img width="132" alt="image" src="https://user-images.githubusercontent.com/9212605/165332284-2c8d6382-993e-4ab1-aeea-ae39939e8f6b.png">

It's also inserting line breaks within words. Even though Korean words are more tolerable to breaks than English, this isn't good for reading.

Conclusion: Contents of https://github.com/mdn/translated-content should be wrapped by editor soft wraps, not hard breaks in files.

Please refer to discussions around wrapping in https://github.com/mdn/content/pull/6936, and https://github.com/mdn/translated-content/discussions/1236#discussioncomment-1051874. There's also #4259.

**Comment by LeoMcA** [comment]
Oops! Apologies for that, I've reverted the change as an interim fix.
