### ISSUE TITLE
code snippets are not showing 'copy' shortcut 'icon' in 'Table Basics' article

### ISSUE THREAD

**Issue by bappyasif** [mdn/yari#6077]
### MDN URL

https://developer.mozilla.org/en-US/docs/Learn/HTML/Tables/Basics#when_should_you_not_use_html_tables

### What specific section or headline is this issue about?

code snippets are not showing 'copy shortcut' icon

### What information was incorrect, unhelpful, or incomplete?

![image](https://user-images.githubusercontent.com/19854521/165365642-82f21ccc-fa1d-485e-9630-d6e5fc72d8fd.png)
as you can see no 'copy shortcut' icon is visible

### What did you expect to see?

a 'copy' shortcut icon like this 
![image](https://user-images.githubusercontent.com/19854521/165365816-e1460f1c-91c5-4901-9dd0-782351a8182b.png)

### Do you have any supporting links, references, or citations?

pretty much all articles code snippets has this on mdn, somehow this article left out!

**Comment by schalkneethling** [comment]
@caugner I had a look at this and this is possibly a tricky one. The icons are there when the page loads but, as soon as you click on a link in the TOC, they all disappear.

**Comment by caugner** [comment]
Reproduced locally, and git bisect found b3d9b031bc2cbd3a10a720984db10c3269e41c4c to be the culprit:

```
b3d9b031bc2cbd3a10a720984db10c3269e41c4c is the first bad commit
commit b3d9b031bc2cbd3a10a720984db10c3269e41c4c
Author: Claas Augner <caugner@mozilla.com>
Date:   Thu Apr 21 11:25:04 2022 +0200

    fix(document): use <section>s with aria-labelledby (#5908)
    
    * fix(document): use <section>s with aria-describedby
    
    * fix(prose): use aria-labelledby
    
    * chore(document): merge Prose + ProseWithHeading

 client/src/document/index.tsx                      | 21 ++----------
 client/src/document/ingredients/prose.tsx          | 40 +++++++++++-----------
 .../files/en-us/web/externallinks/index.html       |  2 ++
 testing/tests/index.test.js                        |  4 +--
 4 files changed, 26 insertions(+), 41 deletions(-)
```
