### ISSUE TITLE
ctrl + click on search result opens it in same tab

### ISSUE THREAD

**Issue by schockocraft** [mdn/yari#6107]
### Summary

Clicking on a search result while holding ctrl will open the page in the same tab, instead of in a new tab, as it should be for a link that is ctrl-clicked. Middle click and right click are acting like they should for links, opening the page in a new tab or showing the context menu.

### URL

https://developer.mozilla.org/en-US/

### Reproduction steps

1. click on the search bar to expand and focus
2. enter a keyword
3. hold down ctrl
4. click on a result

### Expected behavior

The page of the ctrl-clicked result opens in a new tab

### Actual behavior

The page of the ctrl-clicked result opens in the current tab

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Anything else?

Left clicking on the whole highlighted-on-hover div-element switches to the referenced page, while the a-element is actually smaller then the div. unsure what that means.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by schalkneethling** [comment]
Hey @schockocraft, thank you for opening the issue. I see there was a pull request on 13 March to fix this. https://github.com/mdn/yari/pull/5599

I also tried it myself with `cmd+click` (this is on a mac) and it works for me. Because you mentioned `ctrl+click` I assume you are on either Windows or Linux?

**Comment by danielhjacobs** [comment]
@schalkneethling I can't always emulate this, but the behavior of Ctrl+click is incredibly inconsistent for me on Linux as well. Do a seacrh, Ctrl+click a result, and if it opens on a new tab, Ctrl+click other results of the same search.

See screen recording. Every click is a Ctrl+click:

[Screencast from 04-28-2022 11:24:04 AM.zip](https://github.com/mdn/yari/files/8584098/Screencast.from.04-28-2022.11.24.04.AM.zip)

**Comment by schalkneethling** [comment]
Thank you for the additional information @danielhjacobs.

**Comment by caugner** [comment]
Here is the corresponding code, and it should not prevent the browser from executing the default Ctrl + Click behavior:

https://github.com/mdn/yari/blob/8bfe7e307307ba49cba7068e662f26d806e5821c/client/src/search.tsx#L380-L394

@danielhjacobs Does Ctrl+Click open in new tab everywhere else on MDN?

**Comment by caugner** [comment]
Does this additional CSS rule resolve the issue for you?

```scss
.search-results a {
  display: block;
}
```

**Comment by danielhjacobs** [comment]
Yes, for the most part. I see now. The issue was clicking on the non-link part of the search result. The one that rule doesn't fully fix is clicking "Not seeing what you're searching for?", since that's not part of the link.

**Comment by caugner** [comment]
> What that rule doesn't fully fix is clicking "Not seeing what you're searching for?" or "No document titles found.", since those messages are not part of the link, so those lines will need to move inside the links:

I think we could change those two links as follows:

1. Use `<a>` instead of `<Link>` to reduce one common cause of issues.
2. Move the text before the link inside the anchor.

@danielhjacobs Would you be interested in drafting a PR for this?

PS: Have a nice weekend! 🌤️

**Comment by danielhjacobs** [comment]
Done. Have a nice weekend.

**Comment by danielhjacobs** [comment]
@schockocraft Is this issue still occurring for you now? I fixed the issue based on what I reported, but I was unsure if that matched the issue you were having.

**Comment by schockocraft** [comment]
>  I assume you are on either Windows or Linux?
Yes, i am on Windows

@danielhjacobs i checked and it is fixed now, thank you :3
