### ISSUE TITLE
Blank page due to old browser

### ISSUE THREAD

**Issue by undefined-bob** [mdn/yari#6113]
### Summary

Can't access developer.mozilla.org because my browser is too old. All I see is a completely blank page. (im using Firefox ESR 52.9.0 32-bit) 

### URL

developer.mozilla.org

### Reproduction steps

1. install/run Firefox ESR 52.9.0 32-bit
2. open link developer.mozilla.org
3. see blank page 

### Expected behavior

I expected to see the pages content.

### Actual behavior

I only see a completely blank page. 

### Device

Desktop

### Browser

Firefox

### Browser version

Extended Support Release

### Operating system

Windows

### Anything else?

I asked on Mozilla matrix server on the MDM web docs  room and was then asked to fill out this issue here. There was said it was tracked down to the use of IntersectionObserver.
(just for your information why im using such an old browser: I can't update/install a newer browser because it's already the latest one for the OS on my work computer. It's the PC in the office from the company I work for.)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by schalkneethling** [comment]
Tested using BrowserStack which shows an error because `IntersectionObserver` is undefined.

**Comment by undefined-bob** [comment]
I'm happy to report back that the issue is fixed and that I can now access the MDN pages again. Thank you all very much for the quick fix

**Comment by schalkneethling** [comment]
> I'm happy to report back that the issue is fixed and that I can now access the MDN pages again. Thank you all very much for the quick fix

Awesome! Thank you for letting us know.
