### ISSUE TITLE
SectionOnPage leaving newlines and escaping leading space in HREFs

### ISSUE THREAD

**Issue by nschonni** [mdn/yari#6117]
### Summary

Runnig VNU validator I noticed a few complaints for newlines in the generated HREFs. EX:
```
"file:/mnt/z/mdn-content/build/en-us/docs/web/api/htmlimageelement/loading/index.html":116.7-117.29: error: Bad value “/en-US/docs/Learn/HTML/Howto/Author_fast-loading_HTML_pages#use↩____lazy_loading_for_images” for attribute “href” on element “a”: Tab, new line or carriage return found.
```
Think the newlines should be stripped when generating the ID values.

### URL

https://github.com/mdn/content/blame/217dbcd5126ecdd61ebf0e6993cf37c58f52fa1f/files/en-us/web/api/htmlimageelement/loading/index.md#L124-L125

### Reproduction steps

1.
2.
3.

### Expected behavior

Should generate:
```html
  <li><a href="/en-US/docs/Learn/HTML/Howto/Author_fast-loading_HTML_pages#use____lazy_loading_for_images">Use
    lazy loading for images</a> in <a href="/en-US/docs/Learn/HTML/Howto/Author_fast-loading_HTML_pages">Tips for authoring fast-loading HTML pages</a></li>
```

### Actual behavior

Generates:
```html
  <li><a href="/en-US/docs/Learn/HTML/Howto/Author_fast-loading_HTML_pages#use
____lazy_loading_for_images">Use
    lazy loading for images</a> in <a href="/en-US/docs/Learn/HTML/Howto/Author_fast-loading_HTML_pages">Tips for authoring fast-loading HTML pages</a></li>
```

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Anything else?

The browser ultimately "fixes" this, so it doesn't fail to render the link

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Note that the correct link is https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Author_fast-loading_HTML_pages#use_lazy_loading_for_images, so normalizing whitespace to a single character should work fine, probably around here:

https://github.com/mdn/yari/blob/b20862667294b9b9378f624befad16e5dd33c88f/kumascript/macros/SectionOnPage.ejs#L36-L39

Something like `elem = elem.replace(/\s+/, ' ');` should do the job.

**Comment by nschonni** [comment]
I think stripping all the whitespace might be better, or maybe explicitly just doing `elem = elem.replace(/\n+/, '');`
https://www.rfc-editor.org/rfc/rfc3986#appendix-C

**Comment by caugner** [comment]
It's actually the `section`, and merging whitespace to a single space is what we want, because those spaces get replaced by underscores:

https://github.com/mdn/yari/blob/b20862667294b9b9378f624befad16e5dd33c88f/kumascript/macros/SectionOnPage.ejs#L46-L48

**Comment by nschonni** [comment]
but these aren't additional whitespaces that need to be escaped. Replacing the newline with another one that would later be replaced, would generate an extra `_` and break the URL

**Comment by nschonni** [comment]
Actually, I think I'm wrong, because there is also the leading space on the next line

**Comment by yin1999** [comment]
This macro seems to be [deprecated](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Macros/Other#deprecated). Maybe it's a better idea to remove it from content/translated-content.

![image](https://user-images.githubusercontent.com/15844309/206603849-6e15f81e-6d4f-4db6-98d6-f4f9c531759a.png)

**Comment by bsmth** [comment]
Let me check with the team, but it looks like it's deprecated in favor of links with anchors on first glance. It looks like we have 141 occurrences of it on `en-us`:

```bash
grep -r "SectionOnPage" files | wc -l
141
```

**Comment by bsmth** [comment]
After checking with the team, the macro is deprecated (as is correctly listed) and usage of it should be removed from content. I'll look into the places it's used to see how easily it can be replaced with regular markdown links with anchors.

**Comment by nschonni** [comment]
If this is just being tracked under the regular depreciation, I guess this could just be closed

**Comment by caugner** [comment]
👍 

Closing as "won't fix".
