### ISSUE TITLE
Header obscures article actions header on mobile

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#6125]
### Summary

When you open the article actions menu on mobile, the header obscures the article actions menu heading. The makes it hard or impossible to close the menu other than changing your language, for example. See videos below.

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach

### Reproduction steps

1. Open a page on a mobile device or in responsive mode
2. Open the article actions menu (from the three dots)
3. See actions menu header obscured

### Expected behavior

Should be able to easily close the article actions menu

### Actual behavior

See reproduction steps above

### Device

Smartphone

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Video one

https://user-images.githubusercontent.com/10350960/165954386-2e03ddd7-b2f6-4462-a9b6-552123c66f9a.mov

### Video two

https://user-images.githubusercontent.com/10350960/165954427-93c9f898-978a-4509-9d2f-1038974da4e6.mov

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by zhouhaoyiu** [comment]
I think the top value can be adjusted to 64px so that users can click the close button.
![show actions](https://user-images.githubusercontent.com/67226385/166179090-d0c12b7f-d2fd-4051-8bc1-088e9ad9aacd.png)

**Comment by zhouhaoyiu** [comment]
> 
### This class controls this area
![area](https://user-images.githubusercontent.com/67226385/166181095-b51b8d64-c28d-4f0a-934a-2015d02e48f5.png)

**Comment by caugner** [comment]
> I think the top value can be adjusted to 64px so that users can click the close button.

@zhouhaoyiu That should indeed fix it for now, but let's use `--var(--top-navigation-height)` instead. Would you like to open a PR for this?

**Comment by zhouhaoyiu** [comment]
@schalkneethling 

> > I think the top value can be adjusted to 64px so that users can click the close button.
> 
> @zhouhaoyiu That should indeed fix it for now, but let's use `--var(--top-navigation-height)` instead. Would you like to open a PR for this?

I'm very glad to do it.

**Comment by zhouhaoyiu** [comment]
> 
![image](https://user-images.githubusercontent.com/67226385/166309359-ee5c9462-1108-4d03-8d87-169276e4ae12.png)
Should I remove this border?

**Comment by caugner** [comment]
> Should I remove this border?

Please keep the focus border (this is an accessibility feature), but we could add `margin-top: 1px` to make sure the top-edge of the border is shown.

**Comment by schalkneethling** [comment]
> @schalkneethling
> 
> > > I think the top value can be adjusted to 64px so that users can click the close button.
> > 
> > 
> > @zhouhaoyiu That should indeed fix it for now, but let's use `--var(--top-navigation-height)` instead. Would you like to open a PR for this?
> 
> I'm very glad to do it but I don't know where I should add it. May be app.scss?

Thank you do much for contributing! I am sure @caugner will be happy to guide you through the process. 🎉

**Comment by zhouhaoyiu** [comment]
> > Should I remove this border?
> 
> Please keep the focus border (this is an accessibility feature), but we could add `margin-top: 1px` to make sure the top-edge of the border is shown.



> > @schalkneethling
> > > > I think the top value can be adjusted to 64px so that users can click the close button.
> > > 
> > > 
> > > @zhouhaoyiu That should indeed fix it for now, but let's use `--var(--top-navigation-height)` instead. Would you like to open a PR for this?
> > 
> > 
> > I'm very glad to do it but I don't know where I should add it. May be app.scss?
> 
> Thank you do much for contributing! I am sure @caugner will be happy to guide you through the process. 🎉

I'm sorry to at you by mistake.  😳

**Comment by schalkneethling** [comment]
> I'm sorry to at you by mistake. 😳

No, no need. You are more than welcome to mention me if you need assistance. Since you and Claas have been having a conversation already, I thought it best that the two off you keep the conversation going. 👍

**Comment by zhouhaoyiu** [comment]
I have submitted PR and request your review

**Comment by zhouhaoyiu** [comment]
> > I think the top value can be adjusted to 64px so that users can click the close button.
> 
> @zhouhaoyiu That should indeed fix it for now, but let's use `--var(--top-navigation-height)` instead. Would you like to open a PR for this?

I have submitted PR and request your review.
