### ISSUE TITLE
Browser back button sometimes fails to render page after previous 404

### ISSUE THREAD

**Issue by midgleyc** [mdn/yari#6161]
### Summary

Pressing "back" (or, sometimes, "forward") in the browser sometimes leads to an error, e.g. 

> Sorry, the page `/en-US/docs/Web/CSS/font-weight` could not be found.

instead of rendering the page.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-weight

### Reproduction steps

1. Go to a page that 404s, e.g. https://developer.mozilla.org/en-US/docs/404
2. In the search bar, type "font", and click on the first option (for me it is font-weight). The page loads successfully.
3. Click "Get MDN Plus" in the top right, and wait for the page to load.
4. In your browser, click the back button. The page gives a "Page not found" error.
5. Clicking back again gives the first 404ing page, but with a different error: "Loading Error 

    Error: 404 on /en-US/docs/404/index.json: Page not found"
6. Clicking forwards renders the page correctly again.

### Expected behavior

Pages render consistently no matter whether navigated to using links or browser buttons.

### Actual behavior

"Back" sometimes shows an error instead of showing the page.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Screenshot

![backbug](https://user-images.githubusercontent.com/25565697/166567437-3f558e78-94d8-41b7-9d31-ecc813155bec.gif)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
There's a small chance that #5952 (which will land tonight) fixed this.

**Comment by danielhjacobs** [comment]
This seems to have been mostly fixed by #6437, though number 5 still applies.
