### ISSUE TITLE
"Browser support for Javascript APIs" righ side bar is locked in place and footer is not on the bottom in firefox

### ISSUE THREAD

**Issue by miloshadzic86** [mdn/yari#6169]
### Summary

- Div with the class "toc" doesn't scroll to the bottom with the highlighted list items, it is locked in place.
- Footer in firefox is not all the way to the bottom but at a certain position near the bottom and it covers the "toc" div, while in chrome it is at the bottom.

### URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Browser_support_for_JavaScript_APIs

### Reproduction steps

- Visit the link
- Try scrolling to the bottom
- Try it in firefox and chrome

### Expected behavior

- List to scroll
- Footer to be on the bottom on firefox

### Actual behavior

- Locked in place

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Screenshot

![2022-05-05 01_31_18-Window](https://user-images.githubusercontent.com/33502682/166842400-b3464be5-110c-4a61-a880-35360913ef26.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by zhouhaoyiu** [comment]
Wow. A very long TOC ! And I think this area doesn't seem to scroll with the focused toc-link.
PS: this page makes my browser running really slow😰

**Comment by caugner** [comment]
Fixed by @zhouhaoyiu via #6170.
