### ISSUE TITLE
"Specifications" magic does not work from mdn/content

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#6187]
When I'm working on MDN I use mdn/content and `yarn start` to run a local MDN.

In various ways though, this isn't the same as the "real" MDN. One thing in particular is this: if I include a `spec-urls` front matter key, and then in the document I include the `{{Specifications}}` macro, then I should see a spec table rendered there, populated with the value of `spec-urls`.

This works if I run `yarn dev` from mdn/yari, but does not work if I run `yarn start` out of mdn/content.

That makes it much harder for me to check that my changes are correct.

**Comment by caugner** [comment]
@wbamberg Just checking if this is still an issue, and if you could provide steps to reproduce, giving a concrete page example, and what to look for?

**Comment by wbamberg** [comment]
This seems to work now! Thanks for checkout @caugner !
