### ISSUE TITLE
Double-escape inside search widget should blur input

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#621]
You can start to search by pressing <kbd>?</kbd> which is nice. But if you change your mind, you can't escape. One regular <kbd>Esc</kbd> is used to hide any ongoing search results, but a double-escape could be used to really blur out.

**Comment by Gregoor** [comment]
What does one gain from blurring out? (honest question about usage, not trying to be snide or anything)

**Comment by peterbe** [comment]
> What does one gain from blurring out? (honest question about usage, not trying to be snide or anything)

You lose the ability to keyboard navigate. For example scrolling up and down with the arrow keys.
