### ISSUE TITLE
U - Dealing with recoverable (x)ref macros as a new flaw

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#623]
There are 3 types of xrefs challenges. 3 multiplied by the *type* of xref. 
```
▶ ls -l kumascript/macros | rg -i xref
-rw-r--r--  1 peterbe  staff    1499 May 18 06:42 DOMxRef.ejs
-rw-r--r--  1 peterbe  staff    2757 May 18 06:42 cssxref.ejs
-rw-r--r--  1 peterbe  staff     929 May 18 06:42 htmlattrxref.ejs
-rw-r--r--  1 peterbe  staff    1226 May 18 06:42 jsapixref.ejs
-rw-r--r--  1 peterbe  staff    1440 May 18 06:42 jsxref.ejs
-rw-r--r--  1 peterbe  staff     949 May 15 11:39 xref.ejs
-rw-r--r--  1 peterbe  staff    1833 May 15 11:39 xref2.ejs
-rw-r--r--  1 peterbe  staff     741 May 15 11:39 xref_csscomputed.ejs
-rw-r--r--  1 peterbe  staff     767 May 15 11:39 xref_cssinherited.ejs
-rw-r--r--  1 peterbe  staff     850 May 15 11:39 xref_cssinitial.ejs
-rw-r--r--  1 peterbe  staff     884 May 15 11:39 xref_cssvisual.ejs
```

The 3 challenges are, using `cssxref` as an example:

1. Perfect: `{{cssxref('doesexist')}` => `<a href="/en-US/docs/DoesExist">Does Exist</a>`
2. Redirects: `{{cssxref('oldname')}` => `<a href="/en-US/docs/NewName">New Name</a>`
3. Broken: `{{cssxref('oldjunk')}` => `<a class="new" title="This page does not exist">oldjunk</a>`

What we want is that all but (1) "Perfect", above, should be treated as a flaw and go into the existing flaw detection system. But we'll need to put something into the flaw/error object that is structured so we can do something about it later. 

In `master` as of right now, it doesn't deal with 2 and 3 "gracefully". It just turns it into the verbatim original (i.e. leaving it as `{{cssxref('oldname')}}`).
Basically, we need to do a bit of both. Recover a little but still flag it as a flaw. 

**Note! It might not just be a matter of xrefs. Perhaps this whole solution-space is related to macros like `APIRef()` too.** Let's not discriminate. But also, let's make it small incremental steps.

Even though we can use our redirects to correct, so that users never have links to things that redirect, it's still worth calling them flaws. As a content writer you shouldn't be seeing the old reference name E.g. `{{cssxref('-webkit-placeholder')}}` but the new, more correct name, like `{{cssxref('::placeholder')}}`. 

It's important that the flaws are structured enough to contain information available to the point where some script can fix things. Suppose the flaw error object (that gets included in the `index.json`) looks something like this:
```json
{
  "type": "MacroRefRedirectError",
  "source": "{{cssxref('oldname')}",
  "line": 15,
  "column": 7,
  "redirect":  {
    "old": "oldname",
    "final_destination": "newname",
  }
}
```
Equipped with that we can write a script that mass-edits a bunch of these. (or at least, all within a page) But the script would be reusable forever. Since we don't treat KS as an AST I think it's very plausible that we automate fixes with regular expressions. As long as they feel safe and predictable, I think we can really do a nice job with automation.

**Comment by escattone** [comment]
### Acceptance Criteria
- [ ] New functionality, as described above, implemented and tested within the Yari `kumascript` workspace

**Comment by peterbe** [comment]
In terms of names of flaws, I think it should all be part of the `macros` flaws. (e.g. `--flaw-levels="macros:error"`) but I think we should be more specific about the error instance used. At the moment, you get something like "`MacroExecutionError` from `jsxref` in line 209:349"
It's not terrible but it would be nice to give a more fine-tuned error like `MacroLookupError` or `MacroExhaustedLookupError`.

The point I'm trying to make is that they're all `macros` flaws but it'll be extremely helpful to be able to go to the Flaws dashboard and focus on those that aren't saved by a redirect. (i.e. the ones can end up as `<a class="new" title="This page does not exist yada yada">foo-bar</a>` because they're a lot more severe. 

Also, when a macro can be saved by following the redirects you might not need the Flaws dashboard (and a cup of tea) to go through them, but you might want to run a script that tides them all up E.g. turning `{{cssxref('-webkit-placeholder')}}` into `{{cssxref('::placeholder')}}` in the `index.html` file.

**Comment by peterbe** [comment]
Perhaps it's a separate issue but it definitely feels related from a quick skim.
On http://localhost:3000/en-US/docs/Web/HTTP/CORS#_flaws you get a `MacroExecutionError` on `{{HTTPHeader("Downlink")}}` because, I guess, that page simply doesn't exist. So perhaps it's the same as `CSSxRef` (deep down) but the macro isn't called `/xref$/i` so I just don't want us to miss it.

**Comment by escattone** [comment]
This is done.
