### ISSUE TITLE
Some pages' Github links are dead

### ISSUE THREAD

**Issue by schockocraft** [mdn/yari#6245]
### Summary

The "Edit on GitHub" and "Source on GitHub" links to Gihub in the "Found a problem with this page?" box link to a page that just show me Github's 404 warning on *some* pages.

### URL

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values
https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code/code_values

### Reproduction steps

1. go to one of the pages
2. scroll down to the "Found a problem with this page?" box
3. click on one of either "Edit on GitHub" or "Source on GitHub"

### Expected behavior

I see the Markdown code for the Page

### Actual behavior

I see GitHub's 404 warning page

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://user-images.githubusercontent.com/44204747/167902964-8a7cfb7d-af1c-4119-a717-ed2d0e5b7c75.png)

### Anything else?

I only found this isssue to exist for pages with 5 entries in the breadcrumb navigation, not for pages with 4 or less.

Also if you could give me working links to both page's source that would be appreciated :D

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by wbamberg** [comment]
It's because [these pages were moved yesterday](https://github.com/mdn/content/pull/15884), but the site isn't deployed yet. So the page served is from the new location but the GitHub file is at the new one. Once MDN deploys this will go away.

**Comment by schockocraft** [comment]
ahhh i see, i guess this is not actually an issue then?

**Comment by wbamberg** [comment]
I would say not.
