### ISSUE TITLE
Lots of outdated dependencies?

### ISSUE THREAD

**Issue by queengooborg** [mdn/yari#6272]
I happened to notice that a sizable chunk of our dependencies are out of date by running `yarn outdated`.  It seems that Dependabot may not actually be functioning properly?

Out of date dependencies:
```
Package                          Current Wanted  Latest Package Type    URL                                                                           
@types/react-dom                 18.0.3  18.0.4  18.0.4 devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom
chalk                            4.1.2   4.1.2   5.0.1  dependencies    https://github.com/chalk/chalk#readme                                         
eslint-plugin-jest               26.1.5  26.2.0  26.2.0 devDependencies https://github.com/jest-community/eslint-plugin-jest#readme                   
file-type                        16.5.3  16.5.3  17.1.1 dependencies    https://github.com/sindresorhus/file-type#readme                              
got                              11.8.3  11.8.3  12.0.4 dependencies    https://github.com/sindresorhus/got#readme                                    
hast-util-is-element             1.1.0   1.1.0   2.1.2  dependencies    https://github.com/syntax-tree/hast-util-is-element#readme                    
hast-util-to-html                7.1.3   7.1.3   8.0.3  dependencies    https://github.com/syntax-tree/hast-util-to-html#readme                       
hast-util-to-text                2.0.1   2.0.1   3.1.1  dependencies    https://github.com/syntax-tree/hast-util-to-text#readme                       
history                          5.2.0   5.3.0   5.3.0  devDependencies https://github.com/remix-run/history#readme                                   
imagemin                         7.0.1   7.0.1   8.0.1  dependencies    https://github.com/imagemin/imagemin#readme                                   
imagemin-mozjpeg                 9.0.0   9.0.0   10.0.0 dependencies    https://github.com/imagemin/imagemin-mozjpeg#readme                           
imagemin-svgo                    9.0.0   9.0.0   10.0.1 dependencies    https://github.com/imagemin/imagemin-svgo#readme                              
mdast-util-from-markdown         0.8.5   0.8.5   1.2.0  dependencies    https://github.com/syntax-tree/mdast-util-from-markdown#readme                
mdast-util-phrasing              2.0.0   2.0.0   3.0.0  dependencies    https://github.com/syntax-tree/mdast-util-phrasing#readme                     
open-editor                      3.0.0   3.0.0   4.0.0  dependencies    https://github.com/sindresorhus/open-editor#readme                            
read-chunk                       3.2.0   3.2.0   4.0.2  dependencies    https://github.com/sindresorhus/read-chunk#readme                             
rehype-format                    3.1.0   3.1.0   4.0.1  dependencies    https://github.com/rehypejs/rehype-format#readme                              
rehype-minify-whitespace         4.0.5   4.0.5   5.0.1  devDependencies https://github.com/rehypejs/rehype-minify/tree/main#readme                    
rehype-parse                     7.0.1   7.0.1   8.0.4  dependencies    https://github.com/rehypejs/rehype                                            
rehype-raw                       5.1.0   5.1.0   6.1.1  dependencies    https://github.com/rehypejs/rehype-raw#readme                                 
rehype-remark                    8.1.1   8.1.1   9.1.2  dependencies    https://github.com/rehypejs/rehype-remark#readme                              
rehype-stringify                 8.0.0   8.0.0   9.0.3  dependencies    https://github.com/rehypejs/rehype                                            
remark-gfm                       1.0.0   1.0.0   3.0.1  dependencies    https://github.com/remarkjs/remark-gfm#readme                                 
remark-parse                     9.0.0   9.0.0   10.0.1 dependencies    https://remark.js.org                                                         
remark-rehype                    8.1.0   8.1.0   10.1.0 dependencies    https://github.com/remarkjs/remark-rehype#readme                              
remark-stringify                 9.0.1   9.0.1   10.0.2 dependencies    https://remark.js.org                                                         
stylelint                        13.13.1 13.13.1 14.8.2 devDependencies https://stylelint.io                                                          
stylelint-config-recommended     5.0.0   5.0.0   7.0.0  devDependencies https://github.com/stylelint/stylelint-config-recommended#readme              
stylelint-config-sass-guidelines 8.0.0   8.0.0   9.0.1  devDependencies https://github.com/bjankord/stylelint-config-sass-guidelines#readme           
stylelint-prettier               1.2.0   1.2.0   2.0.0  devDependencies https://github.com/prettier/stylelint-prettier#readme                         
stylelint-scss                   3.21.0  3.21.0  4.2.0  devDependencies https://github.com/stylelint-scss/stylelint-scss#readme                       
tempy                            1.0.1   1.0.1   3.0.0  dependencies    https://github.com/sindresorhus/tempy#readme                                  
unified                          9.2.1   9.2.2   10.1.2 dependencies    https://unifiedjs.com                                                         
unist-builder                    2.0.3   2.0.3   3.0.0  dependencies    https://github.com/syntax-tree/unist-builder#readme                           
unist-util-visit                 2.0.3   2.0.3   4.1.0  dependencies    https://github.com/syntax-tree/unist-util-visit#readme
```

**Comment by caugner** [comment]
Most of those dependencies are now pure ESM packages, which prevents us from updating:

- chalk [v5](https://github.com/chalk/chalk/releases/tag/v5.0.0)
- file-type [v17](https://github.com/sindresorhus/file-type/releases/tag/v17.0.0)
- got [v12](https://github.com/sindresorhus/got/releases/tag/v12.0.0)
- hast-util-is-element [v2](https://github.com/syntax-tree/hast-util-is-element/releases/tag/2.0.0)
- hast-util-to-html [v8](https://github.com/syntax-tree/hast-util-to-html/releases/tag/8.0.0)
- hast-util-to-text [v3](https://github.com/syntax-tree/hast-util-to-text/releases/tag/3.0.0)
- imagemin [v8](https://github.com/imagemin/imagemin/releases/tag/v8.0.0)
- imagemin-mozjpeg [v10](https://github.com/imagemin/imagemin-mozjpeg/releases/tag/v10.0.0)
- imagemin-svgo [v10](https://github.com/imagemin/imagemin-svgo/releases/tag/v10.0.0)
- mdast-util-from-markdown [v1](https://github.com/syntax-tree/mdast-util-from-markdown/releases/tag/1.0.0)
- mdast-util-phrases [v3](https://github.com/syntax-tree/mdast-util-phrasing/releases/tag/3.0.0)
- open-editor [v4](https://github.com/sindresorhus/open-editor/releases/tag/v4.0.0)
- read-chunk [v4](https://github.com/sindresorhus/read-chunk/releases/tag/v4.0.0)
- rehype-format [v4](https://github.com/rehypejs/rehype-format/releases/tag/4.0.0)
- rehype-minify-whitespace v5, see rehype-minify [v6](https://github.com/rehypejs/rehype-minify/releases/tag/6.0.0)
- rehype-parse v8, _see_ rehype [v12](https://github.com/rehypejs/rehype/releases/tag/12.0.0)
- rehype-raw [v6](https://github.com/rehypejs/rehype-raw/releases/tag/6.0.0)
- rehype-remark [v9](https://github.com/rehypejs/rehype-remark/releases/tag/9.0.0)
- rehype-stringify v9, _see_ rehype [v12](https://github.com/rehypejs/rehype/releases/tag/12.0.0)
- remark-gfm [v2](https://github.com/remarkjs/remark-gfm/releases/tag/2.0.0)
- remark-parse v9, _see_ remark [v14](https://github.com/remarkjs/remark/releases/tag/14.0.0)
- remark-rehype [v9](https://github.com/remarkjs/remark-rehype/releases/tag/9.0.0)
- remark-stringify v10, _see_ remark [v14](https://github.com/remarkjs/remark/releases/tag/14.0.0)
- tempy [v2](https://github.com/sindresorhus/tempy/releases/tag/v2.0.0)
- unified [v10](https://github.com/unifiedjs/unified/releases/tag/10.0.0)
- unist-builder [v3](https://github.com/syntax-tree/unist-builder/releases/tag/3.0.0)
- unist-util-visit [v4](https://github.com/syntax-tree/unist-util-visit/releases/tag/3.0.0)

I don't know what's preventing us from updating to stylelint [v14](https://github.com/stylelint/stylelint/releases/tag/14.0.0) and the other dependencies though.

**Comment by queengooborg** [comment]
Gotcha, I just noticed #3673 which talks about ESM migration.  It seems that KumaScript is still the main thing holding us back on migrating to ESM, correct?

**Comment by caugner** [comment]
Most of those dependencies are now updated (see the checklist in my [previous comment](https://github.com/mdn/yari/issues/6272#issuecomment-1129871977)), so I'm going ahead and close this issue as resolved.
