### ISSUE TITLE
`yarn build:client` or `yarn dev` command are failure caused by `Module not found: Error:`

### ISSUE THREAD

**Issue by yoshinorin** [mdn/yari#6276]
### Summary

`Module not found: Error` occurs when exec `yarn build:client` or  `yarn dev`.

```sh
$ yarn build:client
Module not found: Error: Can't resolve 'C:/Users/username/mdn/yari/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/toConsumableArray' in 'C:\Users\username\mdn\yari\node_modules\dexie\dist\modern'
Did you mean 'toConsumableArray.js'?
BREAKING CHANGE: The request 'C:/Users/username/mdn/yari/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/toConsumableArray' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

Not sure but I assume this error caused by webpack 5 or react-scripts `5.x`

### URL

N/A

### Reproduction steps

1. `git checkout 8f248fb0eae46f0d49c4bb1423dd668a1388408b`
2. delete `node_modules`
3. `yarn install`
4. `yarn build:client` or `yarn dev`

### Expected behavior

Success a build without error

### Actual behavior

`Module not found: Error` occurs

### Device

Desktop

### Browser

Other (specify below)

### Browser version

Other version (specify below)

### Operating system

Windows 11

### Screenshot

N/A

### Anything else?

Node version is `v16.15.0`

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by danielhjacobs** [comment]
I've been getting the same error: https://github.com/mdn/yari/pull/6260#issuecomment-1126407066

**Comment by caugner** [comment]
Do you have a `package-lock.json` in your checkout by any chance? (I noticed this [here](https://github.com/mdn/yari/pull/6260#issuecomment-1126407066).)

**Comment by caugner** [comment]
@danielh

> * `git checkout 8f248fb0eae46f0d49c4bb1423dd668a1388408b`
> 
> * delete `node_modules`
> 
> * `yarn install`
> 
> * `yarn build:clie`

I just followed these steps with node v16.15.0 and couldn't reproduce the issue. 😕

**Comment by caugner** [comment]
@yoshinorin Were you able to resolve the problem?

@sideshowbarker If you still have this problem, another measure could be to clear the yarn cache (usually in `~/.yarn/berry/cache`)?

**Comment by yoshinorin** [comment]
@caugner 
Thank you for your reply :)

Sorry I'm very busy on this weekdays. I'll try it on this weekend.

**Comment by caugner** [comment]
After testing out npm in this repo, I'm getting the same error now consistently, so I'm able to investigate.

I ran `git bisect`:

> 8e72a1f7bb31dc459a3ded0bdce0a951068bef22 is the first bad commit

FWIW, I also got the following similiar error with a916557e41857a567f1f9b69cb895004dadd6cb4.

```
Module not found: Error: Can't resolve '/Users/username/github/mdn/yari/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/createForOfIteratorHelper' in '/Users/username/github/mdn/yari/node_modules/dexie/dist/modern'
Did you mean 'createForOfIteratorHelper.js'?
BREAKING CHANGE: The request '/Users/username/github/mdn/yari/node_modules/babel-preset-react-app/node_modules/@babel/runtime/helpers/esm/createForOfIteratorHelper' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Comment by caugner** [comment]
I think I found a (temporary) solution by recreating the `yarn.lock` file(s). However, the same error appears after switching to npm (#6322), which suggests that we're just lucky that `yarn` accidentally fixes this somehow. :thinking:

https://github.com/mdn/yari/runs/6520871772?check_suite_focus=true#step:9:32

**Comment by yoshinorin** [comment]
@caugner 
Sorry, the late reply.

I execute `yarn dev` just now with the latest main branch and confirmed the issue was solved.
Thank you :)

**Comment by caugner** [comment]
Glad to hear @yoshinorin! 🎉
