### ISSUE TITLE
Problem with the header (mobile site)

### ISSUE THREAD

**Issue by Den0702** [mdn/yari#6277]
Hello!

### Problem: The sticky _header's content_ on mobile page version _blends_ with the _cite's content_
Also, if I'm trying to open left-side menu bar it also messes up with the cite's content. Moreover, the search field, changing language and other buttons are invisible, but at least, clickable (they can be found in a blind way)

#### Browsers: 
- DuckDuckGo Browser 5.88.0 (58800)
- Brave 1.0.76, Chromium 71.0.3578.99

I have no option to switch to newer browser on my e-book reader, because it's impossible to update it's Android OC
Could you help me please with this problem if there is anything possible to do.

Kind regards

![brave](https://user-images.githubusercontent.com/30319035/168420992-14951c5d-01f2-461a-83a9-e0dafaee1ac3.jpg)
![duckduckgo](https://user-images.githubusercontent.com/30319035/168420995-87e2ad4e-c0c7-407d-b001-63b935a265ee.png)
![20220515_210233](https://user-images.githubusercontent.com/30319035/168490180-bccbb2ea-a153-44b6-a6ce-8c10b82dc829.jpg)
![20220515_210730](https://user-images.githubusercontent.com/30319035/168490183-3571b7bd-c90d-416f-be99-3abeb9d8d3c3.jpg)

**Comment by zhouhaoyiu** [comment]
I think this bug is because chrome 71 does not support preferences-color-scheme when using OS default theme.
![image](https://user-images.githubusercontent.com/67226385/169011447-d39446c2-4282-410d-9f62-268045a4ad8a.png)
![image](https://user-images.githubusercontent.com/67226385/169011518-1cccec72-d0e8-4062-8340-51870c11a841.png)

**Comment by Den0702** [comment]
@zhouhaoyiu 
Thank you very much for the reply, do you think is there a way out from this situation?

**Comment by caugner** [comment]
Hi @Den0702, are you still experiencing this issue?

**Comment by Den0702** [comment]
Hello, 
thank you for asking
If you are asking to know whether to close this issue you can

Regards
