### ISSUE TITLE
Client source isn't reloaded on change

### ISSUE THREAD

**Issue by queengooborg** [mdn/yari#6281]
I'm running `yarn dev` and working on source code for Yari.  When source code in `client/src/` changes, `ssr/dist/main.js` is recompiled, but the page doesn't seem to change.  I'm reloading and hard reloading, but only when I re-run the command does the page change.

**Comment by caugner** [comment]
Cannot reproduce:

1. Run `yarn dev`.
2. Open http://localhost:3000/ in browser.
3. Open `client/src/writers-homepage/index.tsx` in editor.
4. Change "Writer's web page" to "Writer's office".
5. (The text changes automatically in the browser, without reload.)

@queengooborg What was the change that didn't get hot-reloaded?

**Comment by queengooborg** [comment]
Ahh, I see what the problem is: I was still visiting port 5042, rather than port 3000.  Now that I'm going to port 3000, I'm not running into the same issues!
