### ISSUE TITLE
Redirect error reported by Google search console

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#6288]
### Summary

Google search console reported the following three pages as having a redirect error:

- https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/dataset
- https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/tabIndex
- https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/focus

In Chrome, I can see that [https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/dataset](https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/dataset) redirects to `https://developer.mozilla.org/fr/docs/orphaned/Web/API/HTMLOrForeignElement/dataset` which fails and it then tries to redirect back to `https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/dataset` which causes an infinite redirect loop

### URL

- https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/dataset
- https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/tabIndex
- https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/focus

### Reproduction steps

1. Open https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/dataset
2. It will redirect to https://developer.mozilla.org/fr/docs/orphaned/Web/API/HTMLOrForeignElement/dataset 
3. Which will, in turn, redirect back to https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/dataset

### Expected behavior

Either https://developer.mozilla.org/fr/docs/Web/API/HTMLElement/dataset load correctly or successfully redirects to the appropriate page.

### Actual behavior

See reproduction steps.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
The reason is that https://github.com/mdn/translated-content/pull/5707 removed some redirects, and the corresponding lambda is already up-to-date on staging, but not yet on prod.

@fiji-flo It looks like this would be a good moment to enable automatic lambda deployment to prod.

**Comment by caugner** [comment]
Just verified that the redirects are now properly working again, thanks to #6330.
