### ISSUE TITLE
Hydration errors on every page

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/yari#6294]
### Summary

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/55398995/168587626-17d59d95-0149-44a4-95df-7fdbf9334c79.png">

The errors are:

> Hydration failed because the initial UI does not match what was rendered on the server.
>
> There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.

Perhaps something is using the naive `typeof window !== "undefined"` type of check, instead of `useEffect`?

### URL

https://developer.mozilla.org/en-US/docs/Web/API/Navigator

And every other page that I visited

### Reproduction steps

Go to that URL; open browser console.

### Expected behavior

No errors

### Actual behavior

Hydration errors

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by schalkneethling** [comment]
Here is the full log output:

```
react-dom.production.min.js:147 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Ro (react-dom.production.min.js:147:159)
    at Iu (react-dom.production.min.js:224:229)
    at xl (react-dom.production.min.js:293:187)
    at ys (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at ms (react-dom.production.min.js:279:180)
    at rs (react-dom.production.min.js:267:209)
    at D (scheduler.production.min.js:13:203)
    at MessagePort.N (scheduler.production.min.js:14:128)
Ro @ react-dom.production.min.js:147
Iu @ react-dom.production.min.js:224
xl @ react-dom.production.min.js:293
ys @ react-dom.production.min.js:279
vs @ react-dom.production.min.js:279
ms @ react-dom.production.min.js:279
rs @ react-dom.production.min.js:267
D @ scheduler.production.min.js:13
N @ scheduler.production.min.js:14
react-dom.production.min.js:292 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at xl (react-dom.production.min.js:292:155)
    at ys (react-dom.production.min.js:279:389)
    at vs (react-dom.production.min.js:279:320)
    at ms (react-dom.production.min.js:279:180)
    at as (react-dom.production.min.js:270:88)
    at rs (react-dom.production.min.js:267:429)
    at D (scheduler.production.min.js:13:203)
    at MessagePort.N (scheduler.production.min.js:14:128)
xl @ react-dom.production.min.js:292
ys @ react-dom.production.min.js:279
vs @ react-dom.production.min.js:279
ms @ react-dom.production.min.js:279
as @ react-dom.production.min.js:270
rs @ react-dom.production.min.js:267
D @ scheduler.production.min.js:13
N @ scheduler.production.min.js:14
```

**Comment by Josh-Cena** [comment]
I'd like to take a shot at this, just trying to start a local development server first 😄

**Comment by schalkneethling** [comment]
So 423 is `There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.` and 418 is `Hydration failed because the initial UI does not match what was rendered on the server.`

**Comment by caugner** [comment]
Reopening, because #6295 (albeit being an improvement) didn't resolve these errors.

@fiji-flo has also investigated, but couldn't locate the culprit yet.

**Comment by Josh-Cena** [comment]
Ah, this is more complicated than I thought... I've unassigned myself but I'll still be interested in investigation.
