### ISSUE TITLE
Wrong browser order in BCD

### ISSUE THREAD

**Issue by dawidpotocki** [mdn/yari#6314]
### Summary

Mobile browsers are included in the desktop column and vice versa.
This bug got introduced in 4978102cc5065da0d2a093a88a8ff25c6dfa7305.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-last-child#browser_compatibility

### Reproduction steps

1. Just open a link with a BCD table

### Expected behavior

![image](https://user-images.githubusercontent.com/38681822/169192365-c9a98596-ad71-42d1-855c-5df11c5b423a.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/38681822/169192390-4a6ceaf5-6794-4c3c-89e2-cd6b3fbef235.png)

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by danielhjacobs** [comment]
I believe this is technically a browser-compat-data issue: https://github.com/mdn/browser-compat-data/blob/main/types.d.ts#L7-L22

**Comment by dawidpotocki** [comment]
Is it though? Blame shows that this order is there for at least 3 years.

**Comment by danielhjacobs** [comment]
Yes but the commit you referenced attempted to "simplify some of the code and simplify the addition of new browsers" by pulling the browsers, including the ordering of them, directly from browser-compat-data, whereas they had been explicitly defined in yari:

https://github.com/mdn/yari/pull/6308/files#diff-0463450c02d1f503f37fdc07c54624b8a6faa467bc228f65b667fd5c9671cb92L1-L18

**Comment by queengooborg** [comment]
This happens to be a Yari issue, you're right @dawidpotocki -- and my apologies, this one was on me.  What's odd though is that this behavior is not seen on the local development version, and only affects the production version.  Hmm...
