### ISSUE TITLE
Add oculus.svg for BCD

### ISSUE THREAD

**Issue by danielhjacobs** [mdn/yari#6316]
### Summary

Per https://github.com/mdn/browser-compat-data/pull/15923, Oculus will be added to the BCD. Oculus's icon will appear blank until an icon is added to https://github.com/mdn/yari/tree/main/client/src/assets/icons and "oculus" is added to https://github.com/mdn/yari/blob/main/client/src/ui/atoms/icon/index.scss. The other icons were copied from https://github.com/mdn/mdn-dinocons, but that doesn't have oculus.

### URL

None yet

### Reproduction steps

1. None yet

### Expected behavior

When oculus is added to the BCD, it should have an icon.

### Actual behavior

It will not currently.

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by queengooborg** [comment]
FYI, Oculus won't actually show up in the rendered tables yet as the MDN platform renders select categories of browsers (XR isn't one of them yet).

**Comment by caugner** [comment]
I will close this, because (as @queengooborg correctly said) Oculus won't show up until https://github.com/mdn/yari/pull/6718 is merged (which includes an icon).
