### ISSUE TITLE
URL fragments don't work any more

### ISSUE THREAD

**Issue by Getfree** [mdn/yari#6408]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures

### What specific section or headline is this issue about?

All headlines

### What information was incorrect, unhelpful, or incomplete?

URLs with a fragment don't take you to the corresponding section of the webpage.
For example, the following URL will load at the top of the page instead of the "String type" section:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#string_type

### What did you expect to see?

Opening a URL with a fragment should load the page at the corresponding section of that page, not at the top.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/data_structures`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/data_structures/index.md
* Last commit: https://github.com/mdn/content/commit/6862dac854f15e947c25b9b186845ff663ea8c8e
* Document last modified: 2022-05-19T23:21:33.000Z

</details>

**Comment by mustaphaturhan** [comment]
hey, i am able to reproduce it on these browser:
`chrome 102.0.5005.62 (official build) (64-bit)`
`chrome 102.0.5005.63 (official build) (64-bit).`
`microsoft edge 101.0.1210.53 (official build) (64-bit)`

my windows version is `21h2 (os build 22000.675)`. 

however, i didn't see any problem on firefox browser. this might be an issue that related with chromium browsers.

**Comment by caugner** [comment]
On Mac OS, I could **not** reproduce the issue with:

- Firefox Nightly 103.0a1 (2022-06-06) (64-bit)
- Google Chrome 102.0.5005.61 (Official Build) (x86_64)
- Microsoft Edge 102.0.1245.33 (Official build) (x86_64)
