### ISSUE TITLE
T - use front-matter in the index.html instead of a index.yaml file

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#643]
At the moment, the dumper creates two files:

* `index.html` - just the HTML
* `index.yaml` - just the metadata in YAML

Instead, we should just have 1:

* `index.html` - metadata in YAML, as front-matter, above the HTML

This affects...

* `processFolder`
* `processFolderTitle`
* the `index.hash` caching
* and those various things like "Edit this page in your editor"
* the macros flaws links need to point to a different line number

**Comment by peterbe** [comment]
@Gregoor I'm going to work on this one ASAP but I think it'll have a big effect on how you wrote those tools for creating/deleting/moving documents. 
Perhaps if you can work on that CMS tool first, just to stall a little since *this* issue is resolved.

**Comment by Gregoor** [comment]
I am indeed currently working on moving document creation out of the importer. Can I maybe push that up as an isolated change in a minute and then we both work based on that?

**Comment by peterbe** [comment]
> I am indeed currently working on moving document creation out of the importer. Can I maybe push that up as an isolated change in a minute and then we both work based on that?

Sure! I guess we can also just accept the merge conflicts as a fact of life :)

**Comment by Gregoor** [comment]
True, I don't shy away from merge conflicts! But now i've also created a PR. Your call :)

**Comment by Gregoor** [comment]
Oh I just realized that I'm actually deeper in your territory than I thought. I'll definitely have to create (or resolve) some conflicts in server.js wrt doc meta
