### ISSUE TITLE
Left side navigation tree should be focused on current page

### ISSUE THREAD

**Issue by mwisnicki** [mdn/yari#6492]
### Summary

Go to https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context and try to locate it on the left and other items related to it. It's too hard.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context

### Reproduction steps

1. Go to https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context
2. Try to locate related classes

### Expected behavior

Navigation element corresponding to current page is highlighted and scrolled into view with ancestor nodes expanded.

### Actual behavior

Current element is hidden.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://user-images.githubusercontent.com/96032/172453511-a069b97f-4598-4eaa-88c7-97df34aed65b.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by abhisharkjangir** [comment]
I would like to fix this issue, can I take it?

**Comment by caugner** [comment]
@mwisnicki This problem has now been addressed in https://github.com/mdn/yari/pull/7085. 🎉
