### ISSUE TITLE
`yarn content move` change the order of YAML entries

### ISSUE THREAD

**Issue by teoli2003** [mdn/yari#6493]
### Summary

The `page-type` YAML entry is moved after the `tags` when moving the page using `yarn content move`.

### URL

You can test this with any page under Web/API as they have a `page-type` YAML entry.

### Reproduction steps

I did:
```
yarn content move Web/API/msSetMediaProtectionManager Web/API/HTMLMediaElement/msSetMediaProtectionManager
```

### Expected behavior

The `page-type` entry should either stay where it is or be moved between `slug` and `tags`, where we want it to be.

### Actual behavior

The `page-type` entry is moved _after_ the `Tags` YAML entry

### Device

Desktop

### Browser

Firefox

### Browser version

Pre-release (e.g. Beta, Nightly or Canary)

### Operating system

Mac OS

### Screenshot

![Capture d’écran 2022-06-08 à 07 00 12](https://user-images.githubusercontent.com/1466293/172535348-519f5bc0-d9f9-40d6-96ae-5ed63e044174.png)

### Anything else?

cc/ @wbamberg 

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by yin1999** [comment]
I've created #6873 to fix it :)
