### ISSUE TITLE
[Feature Request] The primary directory of the sidebar should be able to jump to its own page

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/yari#6499]
### Summary

Now, The primary directory of the sidebar can only be expanded to the secondary title. But it has its own page. We can not jump to the page by the sidebar. only through the address.

### URL
An example:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes

it can't be jumped by the sidebar.

### Reproduction steps

click any the primary directory of the sidebar.

### Expected behavior

The primary directory of the sidebar should be able to jump to its own page.

### Actual behavior

We can not jump to the page by the sidebar. only through the address.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by teoli2003** [comment]
I confirm this is an annoyance of our current sidebar system. (Not only for the JavaScript sidebar, but in general)

**Comment by awxiaoxian2020** [comment]
Are there some plans to fix it?

**Comment by awxiaoxian2020** [comment]
@teoli2003 I found that we handle this by adding a secondary title "overview" to reference the primary directory.
e.g.: https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding is link to secondary title "Multimedia and embedding overview"

So our problem is to find all missing overview links and add it.

If you don't mind, I will close this issue and open a new one.
