### ISSUE TITLE
"Get MDN Plus" button too eye-catching

### ISSUE THREAD

**Issue by hergetr** [mdn/yari#6500]
Dear all,
thank you for providing MDN!

Now, in dark-mode, the "Get MDN Plus" button is very eye-catching.
That's because it's the only element with white filled background, "shining" much more than the other content.

You may have a look here:
[https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData/FormData)

Perhaps this only applies to dark-mode, i.e. black background with white text.
Would you mind to reduce this advertising to not disturb reading the MDN content? 

Thank you very much in advance,
Rainer

**Comment by awxiaoxian2020** [comment]
It doesn't appear in the text, so I think it doesn't matter.

**Comment by y-liang** [comment]
Looks like this has been resolved as the Get MDN Plus button now appears on the far right of the navigation menu.
<img width="1179" alt="Screenshot 2022-06-14 at 2 29 39 pm" src="https://user-images.githubusercontent.com/45440333/173692392-d2e93b25-9b1a-43e9-b1b8-59aabfbbbe5a.png">
u

**Comment by caugner** [comment]
Hi @hergetr, thank for your reporting this issue, but the button is intended to be eye-catching. 😉

**Comment by caugner** [comment]
PS: You can sign-up for free for an MDN Plus Core account, then you will see your avatar instead.
