### ISSUE TITLE
Table missing headings on mobile

### ISSUE THREAD

**Issue by sybereal** [mdn/yari#6514]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control

### What specific section or headline is this issue about?

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#cache_directives

### What information was incorrect, unhelpful, or incomplete?

The table juxtaposing request and response directives is missing its headings on mobile:
![Screenshot_20220611-130937_Chrome](https://user-images.githubusercontent.com/103007302/173185535-65c77e0a-2e69-4fe8-9b84-4f1e6bac64c3.png)

In desktop view for comparison:
![Screenshot_20220611-131420_Chrome](https://user-images.githubusercontent.com/103007302/173185569-1a78791a-a276-4149-a389-ac940db293b7.png)

### What did you expect to see?

Table headings should be displayed on all platforms.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/http/headers/cache-control`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/http/headers/cache-control/index.md
* Last commit: https://github.com/mdn/content/commit/88ad012e4e0f72ef22ffc4c97f2bef4734a35167
* Document last modified: 2022-05-01T05:16:41.000Z

</details>

**Comment by rushikeshadhav** [comment]
May I work on this?

**Comment by schalkneethling** [comment]
> May I work on this?

Sure thing! Thank you for offering.

**Comment by rushikeshadhav** [comment]
> I had a look at the source. The rule causing this is:
> 
> ```
> @media screen and (max-width: 425px) {
>   thead {
>     display: none;
>   }
> }
> ```
> 
> in `index-mobile.scss`.
> 
> This seems intentional, but I'm unsure about the reasoning behind it.
> 
> This should be moved to https://github.com/mdn/yari

Hey, can you state the path?
I am unable to locate the file path of index-mobile.scss

**Comment by mikoMK** [comment]
It's here: https://github.com/mdn/yari/blob/main/client/src/document/ingredients/browser-compatibility-table/index-mobile.scss

It was introduce with PR #5648. So it would probably make sense to change the selector to `.bc-table thead` to keep the code for the browser compatibility table.

**Comment by rushikeshadhav** [comment]
I am getting this error after following all the steps of Verifying commit signatures
Can anyone help me fix this?
after running this
$ git commit -S -m "test"
could not find identity matching specified user-id: 28D6008F5CF39071
error: gpg failed to sign the data
fatal: failed to write commit object

**Comment by mikoMK** [comment]
I haven't got experience with signing commits, but probably @schalkneethling can help.
