### ISSUE TITLE
The map and foreach pages switch back and forth to display duplicate content

### ISSUE THREAD

**Issue by Anansxo** [mdn/yari#6517]
### Summary

Syntax introduction repeated

### URL

https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach
https://developer.mozilla.org/zh-CN/docs/Web/JavaScript/Reference/Global_Objects/Array/map

### Reproduction steps

1. get into https://developer.mozilla.org/zh-CN/
2. Search Array.prototype.forEach()
3. ![image](https://user-images.githubusercontent.com/95646493/173228231-b3820507-1682-4485-860a-57c49cae6665.png)
4. top-nav-search-input seach Array.prototype.map()
5. ![image](https://user-images.githubusercontent.com/95646493/173228314-001c6628-244e-42e4-b0a6-de5097bfb858.png)
6. Forward or backward browser history

### Expected behavior

Page content does not conflict

### Actual behavior

The content of foreach syntax introduction is repeated
Each time you go back and forward, the web page record will make the introduction content +1
![image](https://user-images.githubusercontent.com/95646493/173228686-c5254c32-ebdc-46d5-a874-2fc77c434121.png)
![image](https://user-images.githubusercontent.com/95646493/173228647-0d325476-9a83-49f8-a132-290de20e8a8a.png)
![image](https://user-images.githubusercontent.com/95646493/173228651-ab2a3895-1955-44d6-bf7f-df82d130efce.png)

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://user-images.githubusercontent.com/95646493/173228785-acced9aa-ff54-4905-8439-e35da7c5fc6c.png)
![image](https://user-images.githubusercontent.com/95646493/173228791-e4e1b977-9808-4b2d-95ed-d80064af8d8f.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Hi @Anansxo, thank you for reporting this issue! 👋 

I wasn't able to reproduce the issue, neither on Chrome nor on Firefox.

Could you please check whether you still experience the problem? 🙏

**Comment by caugner** [comment]
Closing as "can't repo".
