### ISSUE TITLE
`Markdown in MDN` page isn't indexed

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/yari#6525]
### Summary

https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN
I didn't find it at the navigation.
![issue0614](https://user-images.githubusercontent.com/69554233/173477527-c748754b-2de5-4bf1-98d4-d3fd22176ca5.png)

### URL

https://developer.mozilla.org/en-US/docs/MDN/Contribute/Markdown_in_MDN

### Reproduction steps

None.

### Expected behavior

`Markdown in MDN` page is indexed

### Actual behavior

`Markdown in MDN` page isn't indexed

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by teoli2003** [comment]
The sidebar is hardcoded there: https://github.com/mdn/yari/blob/main/kumascript/macros/MDNSidebar.ejs

@Rumyra and @dipikabh are currently rewriting/reorganizing all these guides (we call them the meta-documentation), so I'm not sure it is worth fixing it, even if it is relatively simple.

Thanks for telling us, and for your interest!

**Comment by awxiaoxian2020** [comment]
> The sidebar is hardcoded there: https://github.com/mdn/yari/blob/main/kumascript/macros/MDNSidebar.ejs
> 
> @Rumyra and @dipikabh are currently rewriting/reorganizing all these guides (we call them the meta-documentation), so I'm not sure it is worth fixing it, even if it is relatively simple.
> 
> Thanks for telling us, and for your interest!

It's so good there have been a progress! Thanks for your reply!

**Comment by Rumyra** [comment]
Thanks both! Yes one of the many issues that will hopefully be fixed soon 👍
