### ISSUE TITLE
(Dev mode) Effects in notifications/watching tab are firing twice.

### ISSUE THREAD

**Issue by Guyzeroth** [mdn/yari#6552]
## Problem 

Since the migration to react 18 the useEffect()'s are being mounted and re-mounted in development mode. The reasons for this are described in [this discussion](https://github.com/reactwg/react-18/discussions/19). Owing to assumptions made about effect's and how they are triggered in the component lifecycle this causes items to be duplicated in the notifications, collections and watching tabs ( multiple fetches are made to the API).  While not a production problem right now this may become an issue in later versions of React.

## Solution

Implementing the solution defined [here](https://beta.reactjs.org/learn/synchronizing-with-effects#fetching-data)  should fix the issue. The affected code is [here](https://github.com/mdn/yari/blob/main/client/src/plus/common/api.tsx#L70) [here](https://github.com/mdn/yari/blob/main/client/src/plus/common/api.tsx#L122) , [and here](https://github.com/mdn/yari/blob/main/client/src/plus/common/api.tsx#206)

**Comment by caugner** [comment]
@Guyzeroth Could using useSWR be a solution for those places? 

PS: The last link references a file, not lines in that file.

**Comment by caugner** [comment]
We have removed the Notifications feature, so this is no longer an issue.
