### ISSUE TITLE
No search box on mdn.dev

### ISSUE THREAD

**Issue by SteveALee** [mdn/yari#6583]
### MDN URL

https://mdn.dev/

### What specific section or headline is this issue about?

There is no search box.

### What information was incorrect, unhelpful, or incomplete?

Expect to land on home page and search. I can only choose from predefined topic links

### What did you expect to see?

A search box near top of page

**Comment by caugner** [comment]
We have now decommissioned the website and replaced it with a link to https://developer.mozilla.org/.
