### ISSUE TITLE
No indication on search bar

### ISSUE THREAD

**Issue by premshetty** [mdn/yari#6584]
### MDN URL

https://developer.mozilla.org/en-US/

### What specific section or headline is this issue about?
# slack of visual feedback on search bar

### What information was incorrect, unhelpful, or incomplete?

on clicking on the search bar it does'nt gives any visual feedback wether it's working or not please add some blinking or flickering things on tyhe search bar 

### What did you expect to see?

please add some visual feedback

**Comment by caugner** [comment]
Hi @premshetty, 👋 

Unless you have [`prefers-reduced-motion`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) enabled, you should have a visual feedback in the form of a blinking cursor:

https://user-images.githubusercontent.com/495429/189724938-8f193830-9c1f-45d8-ace0-afccdef11958.mov

The same applies for the central search field on the home page.

Please provide a screen recording and details about your environment (operating system, browser vendor, browser version), if you're still experiencing this issue. 🙏 

Thank you.
