### ISSUE TITLE
CSS Visibility: Link target doesn't exist

### ISSUE THREAD

**Issue by estelle** [mdn/yari#6641]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/visibility

### What specific section or headline is this issue about?

animation type

### What information was incorrect, unhelpful, or incomplete?

In the formal definition, the animation type value is a link to a target not addressed in the document: https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#Interpolation

### What did you expect to see?

a definition of the animation type somewhere

### Do you have any supporting links, references, or citations?

https://www.w3.org/TR/css-display-3/#visibility

animation type is `discrete`. 

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/visibility`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/visibility
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/visibility/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by wbamberg** [comment]
I guess actually it's coming from https://github.com/mdn/data/blob/ba61af61baf4f1ed4c41b4cf9654b7b381f0a4ae/l10n/css.json#L1677.

**Comment by teoli2003** [comment]
Oh yes, you nailed it.

**Comment by teoli2003** [comment]
I think we can close this.
