### ISSUE TITLE
The h2 title changes the number of lines from 1 to 2 when hovering over the title - by making the hash appear

### ISSUE THREAD

**Issue by lukaszpolowczyk** [mdn/yari#6647]
### Summary

The h2 title changes the number of lines from 1 to 2 when hovering over the title - by making the hash appear.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries

### Reproduction steps

1. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries
2. set the viewport width to 1289px
3. hover your mouse over the title "[What problem do container queries solve?](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Container_Queries#what_problem_do_container_queries_solve)"

### Expected behavior

Then the hash `#` appears in the second line of the title, but the title should always include the hash.
The hash should disappear (visibility: hidden), not be completely removed.
The hash should always take its place.

### Actual behavior

Then the hash `#` appears in the second line of the title.
Normally this title on one line.

### Device

Desktop

### Browser

Firefox

### Browser version

Extended Support Release

### Operating system

Linux

### Screenshot

![mdn hover bug](https://user-images.githubusercontent.com/16800535/177022355-ffae54db-eb51-4ea0-8a2c-accdfe6309bd.gif)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
I guess this is the reason why GitHub shows the indicator on the left-side of the heading:
<img width="930" alt="image" src="https://user-images.githubusercontent.com/495429/185916419-6a238247-d29e-47a1-b3ad-1d9d6bbd7b5d.png">

I agree that the proposed solution of always having space attributed to the `#` symbol is probably better than the current behavior, but it would also cause additional space below the heading if it's not hovered and the `#` is not currently shown.

Therefore we might want to consider moving the `#` symbol to the left of the heading. 🤔

**Comment by lukaszpolowczyk** [comment]
@caugner It is enough for the indicator to be with `visibility: hidden;` when it should be hidden for it to work properly.
The pseudo element `::after` should never be `display: none;`. And there would be a problem solved.

**Comment by caugner** [comment]
I talked to our designer and we would accept a PR that moves the `#` in front of the heading.

**Comment by Dhanrajtamang** [comment]
The link to the issue is not working.
