### ISSUE TITLE
BCD tables include the `version_removed` in the version range

### ISSUE THREAD

**Issue by foolip** [mdn/yari#6667]
This is https://bugzilla.mozilla.org/show_bug.cgi?id=1417902 filed again for the new MDN setup.

The problem is clearly illustrated by things that were in EdgeHTML (Edge 12-18) but are not in new Chromium-based Edge 79+:
https://developer.mozilla.org/en-US/docs/Web/API/DocumentType#browser_compatibility

It looks as though support was in Edge 12-79, but it was in Edge 12-18.

---

From duplicate https://github.com/mdn/yari/issues/3971:

> Take a look at this table:
> https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/replacesClientId#browser_compatibility
> 
> The data for Edge being rendered here is:
> ```
> "edge": {
>   "version_added": "18",
>   "version_removed": "79"
> },
> ```
> 
> This is rendered as "18 — 79" on a red background. I think the natural interpretation of this that the feature was in versions 18-79, but the correct interpretation is that it was in Edge 18 only.
> 
> I think the logic here should be:
> - The displayed end range is the version *before* `version_removed` in BCD.
> - If that is the same as the start range, show just a single number on red, "18" in this case.

**Comment by caugner** [comment]
> It looks as though support was in Edge 12-79, but it was in Edge 12-18.

According to [browser-compat-data](https://github.com/mdn/browser-compat-data/blob/a9f4d4851b61ec7d41415fc679f7595af8e7023d/api/DocumentType.json#L122-L135), `DocumentType` was added in Edge 12 and removed in Edge 79.

@foolip Is this issue about showing `12-78` instead of `12-79`, as Edge 78 is the last version that supported the feature? In the issue description, you mention Edge 12-18, which sounds like this is also a data issue? Or is 18 just a typo?

**Comment by caugner** [comment]
💡 Just realized: Edge 79 followed after Edge 12!

**Comment by caugner** [comment]
@danielhjacobs Would you be interested in looking into this?

Essentially, when support was removed in version N (e.g. Edge 79), we should show version N-1 (e.g. Edge 12) in the version range instead.

**Comment by danielhjacobs** [comment]
Opened #7589

**Comment by foolip** [comment]
> 💡 Just realized: Edge 79 followed after Edge 12!

Almost. Edge 18 was followed by Edge 79.
