### ISSUE TITLE
Free Core plan "Current plan" text has not been added 

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#6695]
### Summary

In the MDN Choose a plan flow, the MDN Free Core card should have a "Current plan" line, that is instead, not visible. 

### URL

https://developer.allizom.org/en-US/plus#subscribe

### Reproduction steps

1. Use the Get MDn Plus or Already a subscriber flows to create a new  free account. 
2. Return to https://developer.allizom.org/en-US/plus#subscribe
3. Notice the Free Core card. 

### Expected behavior

When logged in with a paid account and navigating to the Choose a plan section, the plan that applies to the subscription is denoted as the "Current plan". This should apply to the Free core card as well. 
![image](https://user-images.githubusercontent.com/53306802/178284738-6b41b365-aacf-4c9b-a5ed-9ee3daf518cf.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/53306802/178284825-f5939588-7c60-45d6-8cc4-a52126a07de5.png)

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
@mirunacurtean I cannot reproduce this issue:

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/495429/185950505-4dbed5a4-672f-4551-9eb8-e868d989bae3.png">

Does this happen for you only directly after sign-up, or whenever you visit the page with a Free account?

**Comment by mirunacurtean** [comment]
Thanks for verifying this @caugner . Indeed it cannot be reproduced anymore, so I'll close it.
