### ISSUE TITLE
XML Sitemap files are invalid

### ISSUE THREAD

**Issue by a-kyne** [mdn/yari#6708]
### Summary

Although the Sitemap index file is valid ( https://developer.mozilla.org/sitemap.xml), none of the three XML files it links to are valid. 

### URL

    https://developer.mozilla.org/sitemaps/fr/sitemap.xml.gz
    https://developer.mozilla.org/sitemaps/en-us/sitemap.xml.gz
    https://developer.mozilla.org/sitemaps/ja/sitemap.xml.gz

### Reproduction steps

1. Try to open the file, or use an XML validator.
2.
3.

### Expected behavior

XML file should open

### Actual behavior

Encoding error

### Device

Laptop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://user-images.githubusercontent.com/104653010/178807691-6f80aafa-caaa-412b-b22f-5560a80853f7.png)

### Anything else?

Google Search Console records that they visited the XML files earlier today and were able to read them, so this probably happened recently?

Also, I opened an [issue ](https://github.com/mdn/kuma/issues/8092)for this Kuma, I assume that was incorrect?

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by yin1999** [comment]
This is a gzipped file, please download this URL and unzip it.

**Comment by yin1999** [comment]
if you are using linux, try `gzip -d <filename>`, or if you are using windows, try 7-Zip or other software. I can decompress those file

**Comment by a-kyne** [comment]
@yin1999 Son of a gun. Today it works. Just FYI, yesterday three members of the Websites team also tried to open the files and also got errors. I don't know why yesterday the file had encoding errors and today it doesn't. Thanks for responding so quickly, though.

**Comment by caugner** [comment]
I just verified that the sitemap is working as expected:

1. Opened https://developer.mozilla.org/sitemap.xml
2. Downloaded sub-sitemap https://developer.mozilla.org/sitemaps/en-us/sitemap.xml.gz
3. Ran `gunzip sitemap.xml.gz`.
4. Opened the resulting `sitemap.xml` in Firefox.
5. Didn't see any validation errors.
