### ISSUE TITLE
Sidebar badges look inconsistent for current/linked page

### ISSUE THREAD

**Issue by L1Q** [mdn/yari#6719]
### Summary

When an item in the sidebar is a link, the badges are displayed inline, but when the item is for the current page, ``<em>`` tag makes the badges take their own line.

### URL

https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contextMenu
https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/nonce

### Reproduction steps

1. Visit a docs page with the sidebar containing badges (experimental, deprecated, etc.)
2. Observe the badge being in the same line as the rest of the list item 
3. Navigate to the item
4. Observe the badge now showing up in their own line

### Expected behavior

![image](https://user-images.githubusercontent.com/6942070/179196593-9aa2c802-18f5-45c3-9889-e7153f5bcbda.png)

### Actual behavior

![image](https://user-images.githubusercontent.com/6942070/179196997-31bae050-7d65-4c96-90d2-d0eb1806dcd2.png)

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Linux

### Anything else?

[Relevant code](https://github.com/mdn/yari/blob/7839698817fd9e5df569d95db1e28a6ff61eec05/kumascript/macros/WebExtAPISidebar.ejs#L55-L95)
I believe the badges should accumulate in their own variable, then be inserted inside the ``<em>`` tag or outside the ``<a>`` tag like so:
```javascript
    result += '<li>';

    var pageBadges = '';
    if (!ignoreBadges) {

        if (hasTag(aPage, 'Experimental')) {
            pageBadges += badges.ExperimentalBadge;
        }

        if (hasTag(aPage, 'Non-standard') || hasTag(aPage, 'Non Standard')) {
            pageBadges += badges.NonStandardBadge;
        }

        if (hasTag(aPage, 'Deprecated')) {
            pageBadges += badges.DeprecatedBadge;
        }

        if (hasTag(aPage, 'Obsolete')) {
            pageBadges += badges.ObsoleteBadge;
            pageBadges += '<s class="obsoleteElement">';
        }
    }

    if (rtlLocales.indexOf(locale) != -1) {
        result += '<bdi>';
    }

    if (slug == aPage.slug) {
        result += '<em>' + pageBadges + '<code>' + apiComponentName + '</code></em>'
    } else {
        result += pageBadges + '<a href="' + url + '"><code>' + apiComponentName + '</code></a>';
    }

    if (rtlLocales.indexOf(locale) != -1) {
        result += '</bdi>';
    }

    if (hasTag(aPage, 'Obsolete')) {
        result += '</s>';
    }

    result += '</li>';
```

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by mirunacurtean** [comment]
Hello @L1Q and thank you for your contribution. Regarding the sidebar inconsistencies there is a bigger ticket that also encompasses this case as well. Please see https://github.com/mdn/yari/discussions/4033.
