### ISSUE TITLE
Macros are missing some Overview items

### ISSUE THREAD

**Issue by awxiaoxian2020** [mdn/yari#6724]
### Summary

originally in #6499 .
Now we have some chapters whose directory miss the overview page index, This causes we can't jump to some pages.

### URL

confirmed by @teoli2003 , It exists in our system. only an example URL:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes
it can't be jumped by the sidebar for there is no overview link for it.

### Reproduction steps

click any the primary directory, which has no overview page index of the sidebar but it has it's own contents.

### Expected behavior

The primary directory of the sidebar should be able to jump to its own page.

### Actual behavior

We can not jump to some pages by the sidebar. only through the address.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Anything else?

I can make PRs for this issue if it is welcomed, but how we find all missing indexs. I think we should have a plan.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
@awxiaoxian2020 To add the missing "Overview" pages, you would probably need to update the JsSidebar macro, e.g. here:

https://github.com/mdn/yari/blob/251b5cc18bc2067b709f60459a758b3e2a5ca7ed/kumascript/macros/JsSidebar.ejs#L489-L494

**Comment by awxiaoxian2020** [comment]
@caugner As you said here, the `Classes` has added it

but there is still no overview page.

**Comment by caugner** [comment]
@awxiaoxian2020 The `ListSubpagesForSidebar` macro takes a third parameter, which determines whether the parent page should be listed as well:

https://github.com/mdn/yari/blob/1e077dd51ea429bf0b378425197e5a8366632688/kumascript/macros/ListSubpagesForSidebar.ejs#L7-L9

So to add the missing overview pages, you would need to set that parameter to 1, for example here:

https://github.com/mdn/yari/blob/1e077dd51ea429bf0b378425197e5a8366632688/kumascript/macros/JsSidebar.ejs#L413

```patch
-<%-await template("ListSubpagesForSidebar", ['/en-US/docs/Web/JavaScript/Reference/Global_Objects', 1])%> 
+<%-await template("ListSubpagesForSidebar", ['/en-US/docs/Web/JavaScript/Reference/Global_Objects', 1, 1])%>
```
