### ISSUE TITLE
Dark mode does not properly apply to Demos when signed in (sometimes)

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#6727]
### Summary

Noticed this on a logged in account/ older browser profile, tat the dark teme did not sucessfully apply to Demos. 

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/calc#try_it

### Reproduction steps

1. Open older browser profile
2.Go to https://developer.mozilla.org/en-US/docs/Web/CSS/calc#try_it
3. SIgn in
4. Switch between themes and apply dark mode. 

### Expected behavior

Dark color scheme is applied to Demo. 
![image](https://user-images.githubusercontent.com/53306802/179490206-4a8f1867-0d67-4124-9906-391937e07ff8.png)

### Actual behavior

Regardless of switch between themes, or sign out sign in. and browser profile restart, the dark theme was not applied. 

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Screenshot

![Dark theme is not applied sometimes to Demos](https://user-images.githubusercontent.com/53306802/179490259-e6966ab1-8cc8-4fe0-8d6a-24464c6ed3a4.gif)

### Anything else?

Inconsistency with reproducing at times. 

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
It looks like our `postToIEx()` mechanism is not reliable enough.
