### ISSUE TITLE
U - Check MDN (en-US) content into Github / Automate content builds in Github

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#673]
We'll only check in `content/files/en-us` and gitignore the other locales. 

*Acceptance Criteria*
- [x] MDN en-US content exists in Yari Github repo
- [ ] Content built on a GitHub Action cron job 

# Sprint Ready Checklist 
1. - [x] Acceptance criteria defined 
2. - [x] Team understands acceptance criteria 
3. - [x] Team has defined solution / steps to satisfy acceptance criteria 
4. - [x] Acceptance criteria is verifiable / testable 
5. - [x] External / 3rd Party dependencies identified

**Comment by chinikes** [comment]
@peterbe , @atopal - With #674 done, can we verify this Story as done?

**Comment by peterbe** [comment]
> @peterbe , @atopal - With #674 done, can we verify this Story as done?

No. 

https://github.com/mdn/yari/issues/710 is not done because its PR hasn't been merged (or reviewed) yet. 

https://github.com/mdn/yari/issues/711 I haven't started on yet. And I'm trying to figure out if I'm blocked on or not.

**Comment by peterbe** [comment]
https://github.com/mdn/yari/issues/711 is still not done.

**Comment by tobinmori** [comment]
Changed to epic to a more appropriate one.

**Comment by peterbe** [comment]
All sub-items completed/closed now.
