### ISSUE TITLE
Issue with "Document": some symbols aren't explained in a legend or key

### ISSUE THREAD

**Issue by skcodes** [mdn/yari#6744]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document

Throughout the page, various list items are marked with small icons. One is a trashcan, but a trashcan icon is not in the key near the bottom of the page (just below the compatibility chart). Also, some list items are red, and red vs. black is not documented in the key. (And further, using only color to convey information is an accessibility violation.)

Specific section or headline? The icons and red are used throughout the page. The key that is missing the definition of them is at the bottom of https://developer.mozilla.org/en-US/docs/Web/API/Document#browser_compatibility

#### Did you test this? no

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/api/document`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/API/Document
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/api/document/index.md
* Last commit: https://github.com/mdn/content/commit/8e65ef1ae04e60b828482fa18bdeac04bcf379f8
* Document last modified: 2021-09-15T07:56:41.000Z

</details>

**Comment by caugner** [comment]
The icons now have titles (also conveyed to screen-readers), and are no longer colored in the content:

<img width="781" alt="image" src="https://github.com/mdn/yari/assets/495429/d0d72a85-4f77-4e2e-b357-15ade188901d">

(Thank you @mirunacurtean.)
