### ISSUE TITLE
Broken syntax macro in font-style

### ISSUE THREAD

**Issue by alattalatta** [mdn/yari#6779]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/font-style

### What specific section or headline is this issue about?

Formal syntax

### What information was incorrect, unhelpful, or incomplete?

<img width="120" alt="image" src="https://user-images.githubusercontent.com/9212605/181023704-f95ecd3b-8930-4eef-b11f-263e94fb18e8.png">

I can see the raw macro.

### What did you expect to see?

CSS syntax definition.

### Do you have anything more you want to share?

From my search, this is blocked by csstree: https://github.com/csstree/csstree/issues/192

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/font-style`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/font-style
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/font-style/index.md
* Last commit: https://github.com/mdn/content/commit/abcebf471d56ef12239e2565f26d952e8a8cab2e
* Document last modified: 2022-05-17T13:23:31.000Z

</details>

**Comment by teoli2003** [comment]
Strangely, I see this:
```
        // also remove the range in square brackets, as in "<number [0,∞]>"
        slug = slug.replace(/\[.*\]/, '')
```

in our macro code.

Either this is not called, or we should add it to the code path leading to CSSTree.

**Comment by sideshowbarker** [comment]
Fixed upstream now https://github.com/csstree/csstree/commit/746d8601831e30b86cd0bf4de634877373ac6528. So I guess we need to merge to the new version of the package.

**Comment by teoli2003** [comment]
This is really cool! cc/ @wbamberg as he will be interested in this new syntax.
@schalkneethling Do you know if CSSTree will be updated by Dependabot, or is there something we should do to "accelerate" the update?

**Comment by wbamberg** [comment]
Fixed now.
