### ISSUE TITLE
APIRef macro does not work for local rendering

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#6802]
### Summary

The APIRef macro is applied to interfaces, properties, methods, etc to render all the related elements.

This works on the live version - e.g. in [SVGStyleElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGStyleElement) you can see a sidebar. However when I build locally on windows I do not see the sidebar.

The `{{DefaultAPISidebar}}` macro does work locally.

### URL

https://developer.mozilla.org/en-US/docs/Web/API/SVGStyleElement

But any page that uses APIRef

### Reproduction steps

Open any page locally that uses this - e.g. http://localhost:5042/en-US/docs/Web/API/SVGStyleElement

Note the macro is shown unrendered, and the sidebar does not appear:
![image](https://user-images.githubusercontent.com/5368500/182268632-492f2974-bd11-45ad-825e-321f3839d9a0.png)

### Expected behavior

Local view should work as does live view. As it is now my assumption as an editor is that the groupdata is not defined.

### Actual behavior

See summary

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by hamishwillee** [comment]
FYI @teoli2003 - THIS is why the devices thing happened.

**Comment by teoli2003** [comment]
This is weird: it does work locally on MacOS for me. Is this a Window-specific problem?

**Comment by hamishwillee** [comment]
Looks like it.

**Comment by caugner** [comment]
@hamishwillee Just checking:

1. Does it also not render on http://localhost:3000/en-US/docs/Web/API/SVGStyleElement?
2. If you replace the content of `APIRef.ejs` with "Test", does that render?

**Comment by hamishwillee** [comment]
Hi @caugner 

Good to have you back! 

1. Well, I use http://localhost:5042/en-US/docs/Web/API/SVGStyleElement . Nothing renders on localhost:3000 . I tried `yarn dev` on the mdn repo and it gave me command not supported. 
2. On the MDN version of APIRef.ejs it still doesn't render.

I guess you are asking me to test on yari independently? I'll try that, but it's a pain to set up.

**Comment by hamishwillee** [comment]
@caugner OK, when running on http://localhost:3000/en-US/docs/Web/API/SVGStyleElement (i.e. `yarn dev`)
- sidebar is not displayed
- but TEST is, so APIRef is being executed

  ![image](https://user-images.githubusercontent.com/5368500/185518893-ea7344fd-d791-4a19-9fa0-76b4ccde8e6b.png)

**Comment by caugner** [comment]
@hamishwillee I will see if I can reproduce the issue on Windows, just need a couple of information:

1. What Windows version are you using, Windows 10 or Windows 11?
2. What shell are you using (e.g. Git Bash, WSL, WSL2)?
3. What Node version are you running?

**Comment by caugner** [comment]
Never mind, I was able to reproduce it on a private machine running Windows 10, and the following line appears to be the culprit (if you comment it out, the sidebar works fine):

https://github.com/mdn/yari/blob/251b5cc18bc2067b709f60459a758b3e2a5ca7ed/kumascript/macros/APIRef.ejs#L232

**Comment by caugner** [comment]
And here we go:

https://github.com/mdn/yari/blob/251b5cc18bc2067b709f60459a758b3e2a5ca7ed/kumascript/src/api/web.js#L165

**Comment by hamishwillee** [comment]
Thanks very much!
