### ISSUE TITLE
[h2m] Add support to notes, callouts, and warnings on pt-br

### ISSUE THREAD

**Issue by bpires** [mdn/yari#6803]
This issue was discussed over [issue #7291 at mdn/translated content](https://github.com/mdn/translated-content/issues/7291).

It was pointed out by @cw118 the need for creating a file named `pt-BR.json` in the folder `markdown/localizations` to allow notes, callouts, and warnings to use translated keywords in Brazilian Portuguese.

**Comment by fiji-flo** [comment]
@mdn/yari-content-pt-br could any of you confirm this?
