### ISSUE TITLE
U - Create foundational test framework for the Yari PVP

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#681]
# User Story 
The main point of this story is that for the PVP we want a foundational test framework in place so that:
1) once the PVP is live any new changes are easier to handle
2) we need tests for CI

Test coverage may be low, and that is fine. (because this work is _not_ about coverage)

# Acceptance criteria
- [ ] foundational test frameworks in place

# Sprint Ready Checklist 
1. - [ ] Acceptance criteria defined 
2. - [ ] Team understands acceptance criteria 
3. - [ ] Team has defined solution / steps to satisfy acceptance criteria 
4. - [ ] Acceptance criteria is verifiable / testable 
5. - [ ] External / 3rd Party dependencies identified

**Comment by peterbe** [comment]
The only thing remaining is https://github.com/mdn/yari/issues/641 and that's a fine issue on its own.
