### ISSUE TITLE
Show release dates in BCD table

### ISSUE THREAD

**Issue by newclaus** [mdn/yari#6812]
## What is the new suggestion?
Show constantly a feature release date in Browser Compatibility table instead of/along with browser version

## Why is it important or useful?
Browser versions are often increased these days, so we decide to use a feature based on its release date, not the browser version. In this case, seeing the actual release date would be more usefull and more commonly used than uninformative number of some browser version. We can currently see the release date in the tooltip by hovering over the browser version, but we have to do this for every cell in the grid.

**Comment by queengooborg** [comment]
I had an idea a while back about adding a sparkle pattern to the cells of newer features to represent they were just introduced, and have that pattern slowly fade over time.  I think that having the date shown somewhere other than tooltips would be helpful, especially for mobile users.  Perhaps we could put it in the details pane?

(Also, just a note, we won't be able to always show dates in the case of future or beta/nightly releases.)

**Comment by newclaus** [comment]
What if you allow user to select a date on UI from which all implemented features considered as not implemented? A feature can be implemented but it will be displayed as not supported because it was implemented after the selected date

**Comment by caugner** [comment]
> I had an idea a while back about adding a sparkle pattern to the cells of newer features to represent they were just introduced, and have that pattern slowly fade over time.

@queengooborg I like that idea, and maybe we could use the same dot that we use for notifications in MDN Plus:

<img width="230" alt="image" src="https://user-images.githubusercontent.com/495429/197820911-2ade8692-9a00-4f77-921a-f19a2a861c3f.png">


https://github.com/mdn/yari/blob/13890752c2de8998357ff6fbe0dcde748d06f89e/client/src/ui/molecules/user-menu/index.scss#L10-L20

**Comment by caugner** [comment]
Our designer took a look at this today, and to make a long story short: The current design of the BCD table doesn't really allow us to highlight recent releases directly, but as a compromise we can show release dates for recent releases in the expanded row:

<img width="793" alt="image" src="https://user-images.githubusercontent.com/495429/198111948-2c7bc47d-1edb-4ffc-947e-58c64ffa3649.png">
