### ISSUE TITLE
Date.prototype.toLocaleString()- Unusual Time format when forcing hour12 in regions with 24 hour standards

### ISSUE THREAD

**Issue by danaburger** [mdn/yari#6822]
### **Summary:** 
If you use https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toLocaleString to output a localized date string and force 12 hour format, the output is not accurate for regions that default to 24hours. 

For example, when running the following for es-mx: 

```
const event = new Date(Date.UTC(2012, 11, 20, 12, 3, 0));
console.log(event.toLocaleString('es-mx', { timeZone: 'UTC', hour: 'numeric', minute: 'numeric', hour12: true }));

```

Will output `0:03 p. m.`which for en-mx is not considered the region standard, and can be easily mistaken for midnight (00:00). 12 hour time should be reflected as `12:03 p. m.` in that case. 

Our current solution is to remove the hour12:true parameter to default back to 24 hour time, but ideally the formatter should not be outputting values that users would find unfamiliar/incorrect for a particular region.

**Comment by caugner** [comment]
Hi @danaburger! 👋 

Please note that this is the issue tracker for yari, the platform that powers MDN. Unfortunately, we aren't in a position to answer content questions like the one you have, and would recommend to ask your question on another platform like StackOverflow.

Besides, your code example gives the expected result for me on Firefox Nightly (preview version): 😉 

<img width="778" alt="image" src="https://user-images.githubusercontent.com/495429/185473905-5972fd51-90ff-46f5-aa2d-9744fabab464.png">
