### ISSUE TITLE
Sidebar positioning issue

### ISSUE THREAD

**Issue by AdusGaming** [mdn/yari#6824]
### Summary

The sidebar has a reduced height by the size of the header as if originally intended to not cover it, however it lacks a margin and has the same z-index as the header so when you add the margin it still covers the headers boarder.

### URL

https://developer.mozilla.org/en-US/docs/Learn/CSS/Building_blocks/Creating_fancy_letterheaded_paper
or basically any other link from the "Learn Web Development" guide

### Reproduction steps

1. Narrow the width of the browser untill the sidebar hides
2. Open the sidebar

### Expected behavior

The sidebar should only cover the content not the header.

### Actual behavior

The sidebar has a reduced height on the bottom without any purpose and covers the header.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![image](https://user-images.githubusercontent.com/63808441/182820138-a0c532b7-e9f5-4ec5-9e32-0ed671ca354b.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
I couldn't reproduce the issue with Chrome 105 on Mac OS.

@AdusGaming Are you still having this issue?

**Comment by AdusGaming** [comment]
No, I believe it has been fixed
