### ISSUE TITLE
Extending the developer tools page not on web extensions sidebar menu

### ISSUE THREAD

**Issue by rebloor** [mdn/yari#6850]
### Summary

The Extending the developer tools page not on web extensions sidebar menu. Needs adding to the AddonSidebar.ejs macro as one of the "how to" options.

### URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Extending_the_developer_tools

### Reproduction steps

1. Visit https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions
2. Look for "Extending the developer tools"

### Expected behavior

"Extending the developer tools" is listed in the menu

### Actual behavior

"Extending the developer tools" isn't listed in the menu

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Resolved via https://github.com/mdn/yari/pull/6851.
