### ISSUE TITLE
Autogenerate id attributes from dt elements?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#6853]
### Discussed in https://github.com/mdn/yari/discussions/4990

<div type='discussions-op-text'>

<sup>Originally posted by **wbamberg** November 24, 2021</sup>
This came out of https://github.com/mdn/content/pull/10730, and it had occurred to me before. It used to be possible to add `id` attributes to random bits of markup so we could link to them, and that's no longer possible in Markdown. In fact one of the main areas this is annoying is in `<dl>` elements, which we use pretty extensively in MDN. For instance, it would be nice to be able to link to the values of CSS properties.

So I wondered if we might generate `id` attributes for `<dt>` elements in the Markdown-to-HTML step, ad we currently do for headings.
</div>

**Comment by iSatVeerSingh** [comment]
Also check this issue [mdn/content#19625](https://github.com/mdn/content/issues/19625). I think that issue is also linked with this.

**Comment by caugner** [comment]
It appears that auto-generating ids for `<dt>` elements has already been implemented in #5190.

/cc @wbamberg
