### ISSUE TITLE
build is taking a long time, isn't it ?

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#6854]
### Discussed in https://github.com/mdn/yari/discussions/5510

<div type='discussions-op-text'>

<sup>Originally posted by **setop** March  7, 2022</sup>
Hi MDN folks,

I see the last [build](https://drop.zoocoop.com/d/egTMKgyP/L3PQhCA8dFZsjUjkUuadcVFFfKuM5czz) took 48 minutes to build the site at a speed of :

> Built 23,517 pages in 46.9 minutes, at a rate of 8.4 documents per second.

Compare to other static site generators - like for example hugo which can build 1'000 pages per second on a commodity laptop ; roughly 23 seconds for MDN content - it seems pretty slow.

Do you know what is causing this slowness ? Is it an issue for the contributors as the feedback loop must be very very long ?

Cheers</div>

**Comment by caugner** [comment]
Answer: Yari is not a static site generator, but an interactive React web application, so we're essentially rendering 20,000s instances of a React app. We have optimized build time somewhat in the last few months, and we continue to work on it, but it's not our top priority. 😕 

That being said, we're are very open to any tips and contributions that make our build faster without increasing complexity. 🙏 

/cc @setop

PS: While GitHub actions are limited to 2 rather slow cores, a state-of-the-art laptop can build MDN in less than 5 minutes.
