### ISSUE TITLE
Styling suggestion: using padding instead of margin for anchor headings

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#6855]
### Discussed in https://github.com/mdn/yari/discussions/5635

<div type='discussions-op-text'>

<sup>Originally posted by **P233** March 16, 2022</sup>
The targeted anchor heading can be cutted by the fixed top breadcrumb on mobile devices. For example:
![](https://discourse-prod-uploads-81679984178418.s3.dualstack.us-west-2.amazonaws.com/original/3X/7/3/73852bb3a70b0bedb9ca5d9fd770ea8eb7cbc58e.png)

This is not helpful if I directly come to the site with anchor links. Using `padding` instead of `margin` can make sure there is enough space between the target heading and the viewport edge.
https://github.com/mdn/yari/blob/78916367491ca92a6c206c65031163b83908c8d7/client/src/document/index.scss#L336-L340</div>

**Comment by caugner** [comment]
This has already been fixed by #5627.
