### ISSUE TITLE
Remove quick edit

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#6856]
### Discussed in https://github.com/mdn/yari/discussions/4866

<div type='discussions-op-text'>

<sup>Originally posted by **schalkneethling** November  3, 2021</sup>
I did a quick unscientific poll on Slack, and it seems that basically nobody uses this feature. If you want this feature to stay add a 👎 and if you do not use it and would not mind if it is removed, vote it up - Thanks!</div>

**Comment by caugner** [comment]
@schalkneethling Quick-edit has been replaced by "Edit on GitHub" in #6065, so I don't think we need to act here.
