### ISSUE TITLE
"translation" ticker stays visible in main navigation area

### ISSUE THREAD

**Issue by bappyasif** [mdn/yari#6869]
### Summary

i was reading through this, and found out that "translate" ticker is staying visible in main header navigation area, where it should not(at least that's how im expecting it!!)

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#routes_needed_for_the_locallibrary

### URL

https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#routes_needed_for_the_locallibrary

### Reproduction steps

1. [Genre Controller section](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#routes_needed_for_the_locallibrary)
2. [Update app.js section](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#update_app.js)
3. [testing routes section](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Express_Nodejs/routes#testing_the_routes)

if you select any text from those 'code blocks' you will see that 'ticker' shows up and when you scroll down, you will see that ticker stays "visible" in header navigation area until it goes beyond screen view!!

### Expected behavior

im assuming it should go invisible when it reaches "header main navigation" area

### Actual behavior

perhaps same as expected behavior!!

### Device

Laptop

### Browser

Other (specify below)

### Browser version

Stable

### Operating system

Linux

### Screenshot

![image](https://user-images.githubusercontent.com/19854521/184401185-b528a970-0570-4ce9-8272-7becf2e5a468.png)

### Anything else?

please let me know if there is anything else that i can provide to make this issue even better for understanding

and after an initial look around, i could not find any open issue about this....

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Hi @bappyasif, thank you for taking the time to report this issue.

I'm not sure what you mean by "translation ticker". Is this being added by a browser extension?

On your screenshot, I can see the white square artifact (a checkbox?) near the "Guides" menu, but I cannot reproduce it.

Could you please:
1. Share what browser and exact version you're using?
1. Try if you can reproduce the issue in another browser (Firefox, Chromium)?
1. Right-click on the artifact and "Inspect" to see what HTML element it is (and share a screenshot of it)?

**Comment by bappyasif** [comment]
> Hi @bappyasif, thank you for taking the time to report this issue.
> 
> I'm not sure what you mean by "translation ticker". Is this being added by a browser extension?
> 
> On your screenshot, I can see the white square artifact (a checkbox?) near the "Guides" menu, but I cannot reproduce it.
> 
> Could you please:
> 
> 1. Share what browser and exact version you're using?
> 2. Try if you can reproduce the issue in another browser (Firefox, Chromium)?
> 3. Right-click on the artifact and "Inspect" to see what HTML element it is (and share a screenshot of it)?

im afraid that is not reproducible any longer!! seems like its 'solved' somehow!!

btw, issue was: when i was "selecting" that snippet of code, it was showing me this "translation" suggestive ticker!! and upon scrolling further down "while snippet still selected and active ticker", it was still "staying visible" in places such as "top navigation" area"

hope this makes sense.... if you need any more information, please ask away, i'll try my best to comply :)

and, please feel free to close this, as this is no longer as such i reported, thanks and happy open sourcing :)

**Comment by bappyasif** [comment]
> Hi @bappyasif, thank you for taking the time to report this issue.
> 
> I'm not sure what you mean by "translation ticker". Is this being added by a browser extension?
> 
> On your screenshot, I can see the white square artifact (a checkbox?) near the "Guides" menu, but I cannot reproduce it.
> 
> Could you please:
> 
> 1. Share what browser and exact version you're using?
> 2. Try if you can reproduce the issue in another browser (Firefox, Chromium)?
> 3. Right-click on the artifact and "Inspect" to see what HTML element it is (and share a screenshot of it)?

btw, i could now only see this for this snippet only somehow!! here is a screenshot of it
![image](https://user-images.githubusercontent.com/19854521/185650964-c2e72ed6-7992-4c8e-80b1-7a4df3288392.png)

"Genre controller" ==> "exports.genre_list"

it's not showing up in "firefox", and im using "Brave" browser which is a chromium if im not mistaken

on inspection its showing: id of "gtx-trans" and it contains element with this class "gtx-trans-icon"

hope this was helpful, please let me know if there is anything more you need to know about this, happy coding :)

**Comment by caugner** [comment]
@bappyasif Thank you for taking the time to respond, and for providing the screenshot. 👍 

That checkbox you're seeing is definitely not coming from us (see: https://github.com/mdn/yari/search?q=gtx-trans-icon), but most likely from an extension, "gtx" sounds like Google Translate. 😕
