### ISSUE TITLE
mdn plus pwa

### ISSUE THREAD

**Issue by Covenantels** [mdn/yari#6896]
### Summary

I purchased the mdn plus to use off line. I was told to use a chrome browser and install it from the browser bar. I was told after I clicked install onscreen instructions would guide me but no instructions poped up. I am not a tech so can someone help me?

### URL

https://developer.mozilla.org/en-US/plus

### Reproduction steps

1.purchase mdn plus
2.enable downloads off line
3.wait for download to complete
4.go to website I want to use the pwa (https://developer.mozilla.org/en-US/plus
5.click install from browser box

### Expected behavior

instruction about the install where it installed or choose a location, how to add it to my desktop.

### Actual behavior

instead after clicking the install button nothing happened no instructions and the install button went away

### Device

Desktop

### Browser

Chrome

### Browser version

Other version (specify below)

### Operating system

Mac OS

### Screenshot

there is no screen shot because nothing happened no error code

### Anything else?

chrome Version 104.0.5112.79 (Official Build) (x86_64)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Hi @Covenantels, thank you for taking the time to open this issue. 👋 

First of all, please make sure you follow [these instructions](https://developer.mozilla.org/en-US/plus/docs/features/offline#getting-started) to enable MDN Offline. Once you have done that, you should be able to open MDN and navigate even when in flight mode ✈️. 

When you talk about "Install", that sounds like a separate feature **of your browser** that adds a shortcut to the website on your desktop or home screen. This is not a feature provided by MDN, and you don't need it to use MDN Offline. Just keep visiting MDN in your browser like you would usually do. 🙂 

If you continue to have issues setting up MDN Offline, please contact support by opening MDN in your browser, clicking on your avatar (top-right) and open the "Help" item. 😉
