### ISSUE TITLE
Cannot scroll after switching locale

### ISSUE THREAD

**Issue by yin1999** [mdn/yari#6908]
### Summary

When trying to switch a locale, the web page got stuck and cannot scroll up and down.

### URL

Any page with l10n translation. Such as <https://developer.mozilla.org/en-US/docs/Web/CSS>.

### Reproduction steps

1. open <https://developer.mozilla.org/en-US/docs/Web/CSS>
2. switch locale to `zh-CN` or others
3. try to scroll up and down but the web page just not move

### Expected behavior

The web page will not stuck when switch locale.

### Actual behavior

See above

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

Without scrollbar

![image](https://user-images.githubusercontent.com/15844309/185302001-49a51b7d-18cc-4ac4-a45b-4a8d18cae9c3.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Reproduced on prod, stage and local dev environments.

**Comment by caugner** [comment]
Looks like this regression is caused by https://github.com/mdn/yari/pull/6904.
