### ISSUE TITLE
Difference in Firefox/Chrome in behavior concerning the favicon in the new open window

### ISSUE THREAD

**Issue by Ccccccccccccccccccccccccc** [mdn/yari#6914]
### Summary

When testing the example from the "https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus" page,
I just noticed a different behavior in the favicon appearing in the title bar according to the browser I was using.
I clicked on the **"Open a new window" button of _the example_**.

![image](https://user-images.githubusercontent.com/40864712/185635384-b031b419-b5b9-40a0-8a57-d7db1ffacdb5.png)

In the new window from Firefox, the favicon is the Mozilla Firefox default favicon.
In the new window from Chrome, the favicon is the same as the MDN website.

**Under Chrome :**

![image](https://user-images.githubusercontent.com/40864712/185634759-1ed8aa43-b282-498b-b12f-3deb37e513d6.png)

**Under Firefox :** 

![image](https://user-images.githubusercontent.com/40864712/185634671-05b62060-ec2d-461a-994c-488a77062708.png)

### URL

The main page URL: https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus
The new open window URL from the Result section of the example: https://developer.mozilla.org/fr/

### Reproduction steps

1. Open the URL "https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus". One can notice see the MDN favicon.
2. Scroll down to the example's Result.
3. In the Result frame, one can see an "Open a new window" button. Click on this button.
4. The result is a new window with a Mozilla Firefox favicon.

### Expected behavior

I intended to see the same favicon icon whatever the browser I used.
As far as I'm concerned, I would think that the right behavior would be to see the favicon from the MDN website as in Chrome.

### Actual behavior

I saw the Mozilla Firefox favicon instead of the MDN favicon.

### Device

Laptop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Screenshot

https://user-images.githubusercontent.com/40864712/185633718-03cf954b-27f5-4c9e-8b20-7b192df93d06.mp4

### Anything else?

I create this ticket as a successor of this one "https://github.com/mdn/yari/issues/6872" as requested by the last interaction with your teammate.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Thank you again for taking the time to thoroughly report this issue.

Unfortunately, this turned out to be a low-priority Firefox bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1657278), so there's nothing that we can do about it at this moment.

**Comment by Ccccccccccccccccccccccccc** [comment]
Ok, I understood. I will close this issue too and keep watching the bugzilla you indicate. Thanks for your time too.
