### ISSUE TITLE
Absolute links to https://developer.mozilla.org/...

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#695]
```
▶ pwd
/Users/peterbe/yari/content/files/en-us

▶ rg '<a href="https://developer.mozilla.org/' --files-with-matches | wc -l
     712

▶ rg '<a href="https://developer.mozilla.org/' | wc -l
    1332
```

In other words, there are lots and lots of content like this:
```html
 <dt class="landingPageList"><a href="https://developer.mozilla.org/en-US/docs/Web/Guide/API">Guide to web APIs</a></dt>
 <dd class="landingPageList">A list of all web APIs and what they do.</dd>
```

See "Source" on https://wiki.developer.mozilla.org/en-US/docs/Web/Guide$edit for example

**Comment by peterbe** [comment]
They're annoyingly misleading because you might be clicking around in your environment that is NOT `https://developer.mozilla.org` and not notice that you've suddenly hopped from a local or stage build into the real deal.

**Comment by peterbe** [comment]
We should make an exception for this prefix and root them out but still call them flaws. 
And a tool that can auto-fix all of them.

**Comment by peterbe** [comment]
@escattone @tobinmori  What do you think about this idea? 
We currently have a flaw called `broken_links`. Perhaps we should explode that a bit so that there's a new one called `imperfect_links`. Basically, we loop through all the `<a href>` tags and see if the URL can be saved/fixed by a redirect. If so, *mutate* it and add it to the flaw. Then, once the `broken_links` flaw thing runs, it'll not use `this.allRedirects` but only `this.allTitles`. 

So today, a give page might have 10 "broken links". Perhaps of them 8 are redirects and 2 are genuinely broken. So you'd get 8 flaws of `imperfect_links` and 2 flaws of `broken_links`. 

**The only thing I *don't* like about this plan is the name. Got any good suggestions?**

The other interesting thing is that `*xref`s that can be salved would adhere to the same rough plan. If it can be corrected, thanks to a redirect, just correct it but log it as a flaw. However, KS macro stuff is a deeper process that happens earlier, whereas the the broken links is happening to the *rendered* html. So perhaps we can keep these two things separate. E.g. `imperfect_xref` flaw? :)

**Comment by peterbe** [comment]
The reason I'm bringing this up here in *this* issue is because I'm going to treat HTML like
```html
<a href="https://developer.mozilla.org/en-US/docs/Web/Guide/API">Guide to web APIs</a>
```
as an imperfect link that ought to be corrected to 
```html
<a href="/en-US/docs/Web/Guide/API">Guide to web APIs</a>
```

Other name ideas?

* Fixable links (sounds ok)
* Incorrect links (sounds hopeless)
* Bad links (sounds hopeless)

Any other ideas?

**Comment by peterbe** [comment]
I don't want to be too specific because the name of the flaw (e.g. `imperfect_links` like my gut first attempt) should umbrella multiple things. 

Yeah, "imperfect" is vague and subjective and might put it in someone's mind that they shouldn't even be there. As in, the solution would be to remove it. 

And to complicate things, if they're "fixable" then why even wake up a human?!

**Comment by tobinmori** [comment]
dubious_links, flawed_links? :)

What is under the umbrella of imperfect_links aside from redirects?

**Comment by peterbe** [comment]
> What is under the umbrella of imperfect_links aside from redirects?

1. Redirects
2. Links that start with `https://developer.mozilla.org`
3. Links that are spelled with the correct case (e.g. `/en-Us/Docs/wEb/HtMl`)

**Comment by peterbe** [comment]
Both dubious_links and flawed_links are both better than imperfect_links or fixable_links. 
In particular, I think I like `flawed_links` best. So much so that if I find the time and inclination to work on this, that's what I'll call it. So catch me before it's too late!

**Comment by tobinmori** [comment]
flawed_links is good with me. having seen the umbrella of flaws you have to cover, this is not an easy thing to name, like you said! 

but i do like 'flawed' better than 'imperfect' - despite it being a bit vague, at least it's monosyllabic! :)

my only dislike of our naming is that it cover redirects (implying that redirects are something we don't ever want). are we considering redirects an absolute no-no? or, are they ok and acceptable some of the time?

**Comment by peterbe** [comment]
> are we considering redirects an absolute no-no? or, are they ok and acceptable some of the time?

With anything, you'll have this happening. There's nothing really wrong with redirects. 

```
<!-- document A -->
<a href="/b.html">
```
and then you realize that `b.html` was a bad  name so you rename to `bee.html` and add an entry to the `_redirects.txt`:
```
/b.html     /bee.html
```
Now, clicking the link in document A will work but your user had to encounter a 301 redirect before she ended up on `/bee.html`. And besides, for editors of document A, they'll be noticing that `b.html` and thinking "What the heck! I thought we removed or moved that pages? WHat's up with that?! Ghaaa!!!"
So, we can use some powerful automation and stuff, we can semi-automatically re-write document A so the hyperlink HTML gets edited to:
```html
<a href="/bee.html">
```

**Comment by peterbe** [comment]
The exact same thing is going on with, for example `cssxref`.
Perhaps there was a page called `/en-US/docs/Web/CSS/background-color` and some document has in it:
```html
<p>Check out {{cssxref("background-color")}}</p>
```
Now, if the gods of content deside to rename that CSS background-color page to `/en-US/docs/Web/CSS/background/color` what we can do is the same as with regular flawed links.

We help, using our Yari tools, to edit the original HTML so it becomes:
```html
<p>Check out {{cssxref("background/color")}}</p>
```

If we had the concept of primary keys that never change we could have asked people to type:

```html
<p>Check out {{cssxref("3195714")}}</p>
```
and we would never need to do these kinds of loops.
