### ISSUE TITLE
Website "focus search field" keyboard shortcut conflicts with Firefox "open web console" shortcut

### ISSUE THREAD

**Issue by ingria** [mdn/yari#6964]
**Summary**
It's impossible to open firefox web console using the [Ctrl+Shift+K shortcut](https://firefox-source-docs.mozilla.org/devtools-user/keyboard_shortcuts/index.html), because the website uses this shortcut to focus the search field.

**Steps To Reproduce (STR)**
Open any page (like [this one](https://developer.mozilla.org/en-US/)) and press ctrl+shift+k

**Actual behavior**
Search field becomes focused

**Expected behavior**
Web Console should've opened

**Comment by caugner** [comment]
Thank you for reporting this issue. 👋 

Two questions:
1. What operating system are you using?
2. Does the shortcut open the console here on GitHub?

**Comment by ingria** [comment]
1. Ubuntu 20.04
2. Console shortcut works fine on GitHub
