### ISSUE TITLE
Math doesn't display on Chrome

### ISSUE THREAD

**Issue by foobarbecue** [mdn/yari#6967]
**Summary**
The MathML or whatever it is displays as text on Google Chrome. FireFox on left, Chrome on right

![image](https://user-images.githubusercontent.com/854789/140665101-1a2096c2-0e52-4baa-837d-3e1856763d89.png)

**Steps To Reproduce (STR)**
_How can we reproduce the problem?_

1. Open Google Chrome and go to a page that uses math symbols, like 
- https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API/Cameras#Positioning_the_camera
- https://developer.mozilla.org/en-US/docs/Web/API/XRRigidTransform/matrix
- https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/getTransform
- https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidateStats/priority
- https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Audio_concepts
- https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/translateZ (in the table under "Values")

**Actual behavior**
Saw text instead of math symbols

**Expected behavior**
Math symbols

**Additional context**
Previous issue https://github.com/mdn/kuma/issues/6391

**Comment by caugner** [comment]
I checked the first page and the MathML seems to be rendered properly in all browsers.

- Firefox:
  <img width="1082" alt="image" src="https://user-images.githubusercontent.com/495429/201388582-2502065e-a435-424a-89c1-1d0e2f528e86.png">
- Chrome
  <img width="1082" alt="image" src="https://user-images.githubusercontent.com/495429/201388528-bf44656e-34ef-4d61-93d1-7b1aab3440ec.png">
- Safari
  <img width="1082" alt="image" src="https://user-images.githubusercontent.com/495429/201388646-42f4f9b1-c5fb-4945-8f84-f6486bb04080.png">

**Comment by foobarbecue** [comment]
I also get @caugner 's results now, in Chrome 107. I guess it started working after a recent Chome upgrade.

As shown in @caugner 's screenshots, there's clearly still an issue with the brackets around the matrix not extending the full vertical height. I'm confused though, because I see that issue on Chrome and @caugner has labelled that screenshot "Firefox." Is it possible they got mixed up?

**Comment by caugner** [comment]
> Is it possible that the screenshots are mislabeled?

@foobarbecue Good catch, they were indeed mislabeled. Fixed now.

As for the brackets in Chrome, this is not an issue on our side, but you could open an issue in the Chromium bug tracker for the [MathML component](https://bugs.chromium.org/p/chromium/issues/list?q=component%3ABlink%3EMathML&can=2).
