### ISSUE TITLE
Kuma should stop setting heading id attributes to match name attributes

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#6969]
In Kuma, headings automatically get `id` attributes that are taken from the heading's text content:

```
<h2 id="Examples">Examples</h2>
```

Unless the heading also has a `name` attribute, in which case the value of the `name` is used as the `id`:

```
<h2 id="Example" name="Example">Examples</h2>
```

This is a problem for writers, because the linter relies on heading IDs to, well, identify headings. And one of the things we are doing as part of the linting work is to fix up our headings to make them consistent, so we're (manually) making hundreds of changes like:

```
"Example" -> "Examples"
"Browser Compatibility" -> "Browser compatibility" 
"Specification" -> "Specifications"
```

Because of Kuma's treatment of the `name` attribute, making these changes sometimes doesn't update the `id`, so the linter still reports an error, and we have to go into the source view and remove the `name` attribute manually.

I don't know of any good reason for Kuma's behaviour here, so I'd like to suggest that it is changed so `id` is set only from the text content, and the `name` attribute is ignored.

**Comment by caugner** [comment]
@wbamberg Wondering if this is still in issue?

**Comment by wbamberg** [comment]
nope.
