### ISSUE TITLE
"View on MDN" link should be in the Toolbar, not the footer

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#697]
In the footer, there should only be "Edit on GitHub". What that links to is a different story for another day but for now we can continue with just linking straight to the `index.html` based on the current branch or something. It's probably going to need a lot of thought and smarts. 

Either way, that link is going to be there in all production builds that we upload to S3. Some day, when Yari *is* MDN, we'll still keep that link. Similar to how readthedocs has the "Edit on GitHub" link when reading docs. 

The "View on MDN" link however only makes sense in the Toolbar. E.g. you're in content-writing hat-wearing mood and you're spinning up a branch to rewrite some docs and suddenly you feel the urge to see and compare this to the current production build.

**Comment by peterbe** [comment]
I suggest we take whatever code we have that makes the `View on MDN` and put it somewhere in the Toolbar and remove it from the footer.

**Comment by Gregoor** [comment]
@peterbe I don't think it's too disruptive. Feel free to go ahead. Though I also hope we're close to getting CRUD in (which would benefit from your codebase proficiency rn)
