### ISSUE TITLE
BCD table arrow is is mispositioned 

### ISSUE THREAD

**Issue by mindy** [mdn/yari#6971]
**Summary**
This was originally reported in mdn/kuma#6845. It's a different but related issue, so I wanted to create a separate ticket for it. 

From @WebMechanic: 
On EdgeHTML (Edge/18), the position of the twirly triangle is misaligned and appears inside the table cell:

![](https://user-images.githubusercontent.com/638340/78993662-80f5c280-7b3e-11ea-8059-0df733453170.png)

**Steps To Reproduce (STR)**
1. Using Windows 10/Edge 18, visit https://developer.mozilla.org/en-US/docs/Web/CSS/@media#Browser_compatibility

**Actual behavior**
The arrow button is in the middle of the table cell.

**Expected behavior**
The arrow button should be aligned towards the bottom of the table cell.

**Comment by caugner** [comment]
MDN has undergone a [redesign](https://hacks.mozilla.org/2022/03/a-new-year-a-new-mdn/) and those arrows are no longer present, so the issue should be resolved.
