### ISSUE TITLE
please have the dark mode already .......

### ISSUE THREAD

**Issue by PankajDeshmukh93** [mdn/yari#6973]
**Summary**
_What should be changed? (Please provide a URL if applicable)_

The code that is being read to understand should be availabel in dark mode
**Rationale**
_What problems would this solve?_
bcoz mostly coding is done at night and we want the dark mode

**Audience**
_Who would use this changed feature?_

each soul that is programmer or want to be a programmer
![dark mode](https://user-images.githubusercontent.com/66534825/83987188-10f89280-a95d-11ea-8848-b8d67b6f5e5e.png)

**Proposal**
_What would users see and do? What would happen as a result?_

**Additional context**
_Is there anything else we should know?_

**Comment by caugner** [comment]
As part of the [MDN Redesign](https://hacks.mozilla.org/2022/03/a-new-year-a-new-mdn/) in March 2022, dark mode is now available on MDN.
