### ISSUE TITLE
"Browser compatibility"-colors unclear for colorblind people (bug 1548316)

### ISSUE THREAD

**Issue by RednaelT** [mdn/yari#6979]
# Request type
- [x] Correction or update

# Details
Hi, I'm colorblind and I have some difficulties reading the browser campatibility table at the end of each docs page. The issue I have is with distinguishing between "Full Support" and "Compatibility Unknown". To me, the two colors look the same. Also when I look at the legend at the bottom, I see no difference between the two colors picked for this. I see some difference between "No Support" and the others, but there the cross helps me best.

I would suggest to pick colors that are more widely apart from eachother in the color spectrum and to perhaps also introduce an icon of some sort (like the cross for No Support) for all statuses. This would help me out a lot.

Thanks and regards,
Martijn

**Comment by caugner** [comment]
The [MDN Redesign](https://hacks.mozilla.org/2022/03/a-new-year-a-new-mdn/) in March 2022 should have resolved this issue by updating the colors and adding icons.
