### ISSUE TITLE
Accesskey on search box missing

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#6983]
Over on the sprints repo the following issue was raised by @whyalwayscreateaccounts

https://github.com/mdn/sprints/issues/2188

> See subject. The search box should be accessible via keyboard.
> I would suggest to use accesskey="f"
>
> Have a nice day

**Comment by caugner** [comment]
@schalkneethling Do you think the search box still needs an access key now that we can access it using Cmd + K?

**Comment by mirunacurtean** [comment]
@caugner I propose we close this as the request as it were, for "The search box should be accessible via keyboard." is applied and it has gotten no further feedback in a long while.
