### ISSUE TITLE
CSS Interactive examples have got a scrollbar

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#7038]
## Summary

CSS interactive examples have now got a vertical scrollbar in the section listing the choices, cutting off the bottom of the last example choice:

<img width="806" alt="Screen Shot 2022-09-01 at 11 55 54 AM" src="https://user-images.githubusercontent.com/432915/187991357-c164bf55-a627-4b40-ae55-85fd2d1de7bc.png">

The content of this example has not changed recently so I think this must be a platform change, although I don't know where.

## URL

https://developer.mozilla.org/en-US/docs/Web/CSS/background
https://developer.mozilla.org/en-US/docs/Web/CSS/filter
https://developer.mozilla.org/en-US/docs/Web/CSS/transform

...and many many more.

##  Reproduction steps 

Visit one of the above pages and look at the interactive example.

##  Expected behavior 

The set of code choices on the left fits in the pane of the editor without a scrollbar.

When we write examples we are very careful to avoid a scrollbar in the editors, because it looks bad, it cuts off part of the example, and it potentially hides examples.

##  Actual behavior 

The set of code choices gets a scrollbar.

##  Device

Laptop

## Browser

Chrome and Firefox

## Browser version

All

## OS

MacOS

## Screenshot

<img width="806" alt="Screen Shot 2022-09-01 at 11 55 54 AM" src="https://user-images.githubusercontent.com/432915/187991357-c164bf55-a627-4b40-ae55-85fd2d1de7bc.png">

**Comment by caugner** [comment]
Please make sure to always use the [issue template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml) so that we have all information to reproduce the issue.

> CSS interactive examples have now got a scrollbar

Unfortunatey, I cannot reproduce the issue on https://developer.mozilla.org/en-US/docs/Web/CSS/background-image with Chrome, Edge or Firefox on Mac OS.

> (also just noticed: in dark mode the function name is completely unreadable)

This is a known issue: https://github.com/mdn/bob/issues/858

**Comment by wbamberg** [comment]
This is Chrome:

<img width="822" alt="Screen Shot 2022-09-02 at 8 18 34 AM" src="https://user-images.githubusercontent.com/432915/188181511-aa0c1cac-0017-4808-b6f1-f7135b06ca79.png">

Please confirm that you don't see the scrollbar I've highllighted.

**Comment by schalkneethling** [comment]
> Please confirm that you don't see the scrollbar I've highllighted.

I can confirm that I am also seeing it in Chromium-based browsers, Safari, and Firefox on desktop.

**Comment by caugner** [comment]
> Please confirm that you don't see the scrollbar I've highllighted.

I tested again both locally and on BrowserStack (tested different resolutions), and I don't get those scrollbars in Chrome, Safari or Firefox.

@wbamberg @schalkneethling Can you find out what's causing the scrollbar?

FWIW Here's a screenshot of the `section#example-choice-list`'s Box Model in Firefox that appears to have a scrollbar in your screenshots: 
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/495429/198573943-19678f07-fd32-4908-90fa-235224253556.png">
