### ISSUE TITLE
Search should suggest exact matches first

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/yari#7047]
### Summary

When I search for `with`, I expect https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with, not a bunch of random articles with "with" in them. Same goes for `for`, `break`, etc.

### URL

Every page; this is about the search.

### Reproduction steps

1. Type in `with`
2. Get:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/55398995/188183125-b2cf2e81-92d8-434e-b078-903c5da40929.png">

3. Have to do "site search" to get to the real "with" page

### Expected behavior

Exact matches of the text should always be presented first. (Letter-by-letter; I can live with "wit" not showing that page since it's quite ambiguous)

### Actual behavior

The page doesn't appear at all

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
@Josh-Cena Feel free to review [my PR](https://github.com/mdn/yari/pull/7867) that should fix this.
