### ISSUE TITLE
U - Make documents look like MDN

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#708]
This is about making the pages built in Yari to look almost identical to documents in MDN. So stuff like notices, syntaxboxes, code snippets (`<pre>` tags), etc. But excluding things like sidebar, header, footer, Toolbar, home page. 

Timebox to a couple days. Not required for PVP launch, but would be nice! 

**Acceptance Criteria**
- [ ] Majority of the document looks like MDN

**Tasks**
- [ ] Copy SCSS from Kuma into Yari?

**Comment by tobinmori** [comment]
Note: We can add minimalist-specific tasks to this story @schalkneethling, if you manage to complete your current sprint workload.

**Comment by atopal** [comment]
Apparently this was too much work to do it quickly, and the decision was to cancel the plan.
