### ISSUE TITLE
ListSubpagesForSidebar should sort by title

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#7097]
### Summary

[ListSubpagesForSidebar](https://github.com/mdn/yari/blob/main/kumascript/macros/ListSubpagesForSidebar.ejs) sorts by page slug, not title. This means entries in the sidebar are not sorted in a way that's visible to users:

<img width="325" alt="Screen Shot 2022-09-08 at 9 37 57 AM" src="https://user-images.githubusercontent.com/432915/189177803-7117ccd0-74e4-443b-9179-0d333306109e.png">

Note that [ListSubpages](https://github.com/mdn/yari/blob/main/kumascript/macros/ListSubpages.ejs) does sort by title:

<img width="814" alt="Screen Shot 2022-09-08 at 9 38 55 AM" src="https://user-images.githubusercontent.com/432915/189177980-0bc8c5c1-2562-481d-8a32-cefee1bd7bf0.png">

### URL

These screenshots came from https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors.

### Reproduction steps

Visit https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors and look at the entries in the sidebar.

### Expected behavior

Entries should be sorted by title.

### Actual behavior

Entries are sorted by slug.

### Device

Laptop

### Browser

Firefox

### Browser version

Pre-release (e.g. Beta, Nightly or Canary)

### Operating system

Mac OS

### Anything else?

See also https://github.com/mdn/yari/issues/7097

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by yin1999** [comment]
Hi @wbamberg. I've created #7186 to fix this. Could you review on this (for the sorting rule, trim title rule, etc.)

**Comment by wbamberg** [comment]
Thanks for your PR, @yin1999 ! But it looks like it is doing a lot more than sorting titles. I get a lot of PRs to review, and you're much more likely to get a quick review from me if you make a PR that's focused on the specific issue.

I'm into code improvements like using `const`/`let`, but would prefer them to be in separate PRs.
