### ISSUE TITLE
Images doesn't load on page with Russian language

### ISSUE THREAD

**Issue by beken0w** [mdn/yari#7111]
Images doesn't load on page with Russian language. English page had checked and it has images.

**Comment by yin1999** [comment]
Hi @beken0w, could you please provide the URL to the page which has the problem?

**Comment by caugner** [comment]
Hi @beken0w! 👋 

Please use our [issue template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml) to report the problem you're experiencing. 🙏

Thank you!

**Comment by caugner** [comment]
PS: Maybe this is the same issue as https://github.com/mdn/yari/issues/5652.

**Comment by beken0w** [comment]
https://developer.mozilla.org/ru/docs/Learn/Server-side/Django/Forms
@yin1999

**Comment by yin1999** [comment]
hi @caugner, this should be an issue related to mdn/translated-content. Could you transfer this?
