### ISSUE TITLE
Support for more syntax highlight languages

### ISSUE THREAD

**Issue by rubiesonthesky** [mdn/yari#7154]
I'm opening discussion for some new languages that could be added. 

It would be beneficial to mark code blocks with actual language they are using so the highlight would work correctly. This will also help with linters and formatters to understand the code better.

Here are some that I think would be good fit for adding and they are used in multiple pages. I have added some examples were they are currently used and how does it look.

- Handlebars:  Ember pages, [Ember conditional footer - todos plural problem](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Ember_conditional_footer#the_todotodos_plural_problem)
- EJS: Kumascript pages, [Kumascript - basics](https://developer.mozilla.org/en-US/docs/MDN/Tools/KumaScript#basics)
- Django/Ninja2: [Django Tutorial Part 6: Generic list and detail views - template](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views#creating_the_list_view_template)

It would be also nice to have syntax highlighting for Svelte and Vue but it seems that Prism does not support those.

**Comment by caugner** [comment]
@teoli2003 @queengooborg What do you think, should these languages be added?

**Comment by queengooborg** [comment]
I think these are reasonable languages to include syntax highlighting for, yeah!

**Comment by Mrsan825** [comment]
> I'm opening discussion for some new languages that could be added. 
> 
> It would be beneficial to mark code blocks with actual language they are using so the highlight would work correctly. This will also help with linters and formatters to understand the code better.
> 
> Here are some that I think would be good fit for adding and they are used in multiple pages. I have added some examples were they are currently used and how does it look.
> 
> - Handlebars:  Ember pages, [Ember conditional footer - todos plural problem](https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Ember_conditional_footer#the_todotodos_plural_problem)
> - EJS: Kumascript pages, [Kumascript - basics](https://developer.mozilla.org/en-US/docs/MDN/Tools/KumaScript#basics)
> - Django/Ninja2: [Django Tutorial Part 6: Generic list and detail views - template](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Generic_views#creating_the_list_view_template)
> 
> It would be also nice to have syntax highlighting for Svelte and Vue but it seems that Prism does not support those.

[]()

**Comment by caugner** [comment]
Alright, we would now be accepting any PR that adds syntax highlighting for those languages.

**Comment by caugner** [comment]
Django and Handlebars have been added in https://github.com/mdn/yari/pull/8108 and https://github.com/mdn/yari/pull/8113, and there has been no further request for EJS, so I'm going ahead and close this as done.
