### ISSUE TITLE
Importer might need to line-ending trim all HTML

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#717]
One thing I noticed when I ran the importer the last time was the the `index.html` files look like this:

```
<p>Bla bla</p> \n
```
Basically, lines that aren't trimmed. 

Why's that a problem? Because, I opened one of them to edit in my IDE and added a new line at the bottom. When I pressed Save (cmd-s) it did save my file but it also cleaned up all the trailing spaces of individual lines. You know, because VSCode is sensible. 

It might be a worthwhile feature to keep. In the in-browser editor we're actually using the same `Document.create` function as we use in the importer. The one that turns the metadata into YAML, as front-matter and combines it with the Kuma-HTML. So if someone uses the in-browser editor it might be a good ideal to do something like this:
```javascript
content = content.split('\n').map(x => x.trimEnd()).join('\n');
```

**Comment by peterbe** [comment]
@Gregoor We also want to make sure that anyone and anybody doing edits on Windows or on UNIX'y don't mess up each others line-endings too. Perhaps a little JavaScript code to back up the in-browser editor can make sure the edits are sane. We know what the goal is:

1. No `\r\n` linebreaks
2. Using the in-browser editor to add a new line of text shouldn't cause edits to the other lines you didn't change ...on Windows.

**Comment by peterbe** [comment]
See https://gist.github.com/peterbe/3010e6317b878ccd7840808d0c2a7cab
This is what I got from `git diff master -- content/files/en-us/web/html/element/video/index.html`
All I did was add the new `<p>peterbe sample change</p>` line and saved. 
It shouldn't be causing the reviewers to have to worry about those 2 other changes elsewhere in the file.

**Comment by peterbe** [comment]
This is partially fixed by https://github.com/mdn/yari/commit/4457daa91062aaa9bf2975b4c71dad0250fe79b1 but we still need to make sure it doesn't happen again on in-browser edits and we need to make sure it works for Windows too.

**Comment by Gregoor** [comment]
How about adding an [.editorconfig](https://editorconfig.org/) file to the content directory? It can be used to tell code editors to respect existing line-endings, trailing white spaces, etc.
A lot of code editors support it out-of-the-box and there's plugins for the rest:https://editorconfig.org/#download

**Comment by Gregoor** [comment]
We could also throw this into CI, to not duplicate what'd be checked by .editorconfig: https://github.com/editorconfig-checker/editorconfig-checker

Drawback being that problems violating .editorconfig would be reported differently.

**Comment by peterbe** [comment]
The importer is fine for now. We might get some corruption in the future with PRs that are made using Windows CRLF but that's a CI problem.
