### ISSUE TITLE
CSS spec references show as "Unknown specification"

### ISSUE THREAD

**Issue by andreubotella** [mdn/yari#7173]
### Summary

It used to be that CSS spec references pointed to the consistently-down official drafts.csswg.org website. Recently (see w3c/csswg-drafts#7712), a new mirror for the CSS Editor's Drafts was set up in https://w3c.github.io/csswg-drafts, which builds the specs automatically using Github Actions and Github Pages, and the links to CSS specs in browser-compat-data were updated to use it in mdn/browser-compat-data#17747 and mdn/browser-compat-data#17802.

However, currently all references to CSS specs, which use this new mirror, show up as "Unknown specification", apparently because this new mirror isn't in the `browser-specs` NPM package, and there seems to be resistance to adding it (w3c/browser-specs#704). So maybe this should be worked around in yari instead.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/overflow for example

### Reproduction steps

Scroll down to the "Specifications" heading.

### Expected behavior

"CSS Overflow Module Level 3 / #propdef-overflow"

### Actual behavior

"Unknown specification / #propdef-overflow"

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Linux

### Anything else?

cc @sideshowbarker @queengooborg 

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by sideshowbarker** [comment]
It looks like we now have an upstream solution, per https://github.com/w3c/browser-specs/issues/704#issuecomment-1255147490:

> Browser-specs now lists `https://w3c.github.io/csswg-drafts/` URLs for CSS specs under the [nightly.alternateUrls](https://github.com/w3c/browser-specs/#nightlyalternateurls).

So it looks like we can fix this by updating our browser-specs client/consumer code to check the `nightly.alternateUrls` value in addition to the `nightly` and `nightly.url` values.

**Comment by meyerweb** [comment]
Sorry if I’ve overlooked something obvious but do we have a fix for this ready to go?  It’s kind of a bad look, even if all the links do still seem to work.

**Comment by sideshowbarker** [comment]
Hi @meyerweb
> Sorry if I’ve overlooked something obvious but do we have a fix for this ready to go? It’s kind of a bad look, even if all the links do still seem to work.

Yes, there’s a fix at https://github.com/mdn/yari/pull/7262 that’s ready to go. Hopefully we can get it merged very soon
