### ISSUE TITLE
Yari delete CLI incorrectly throws about non-existing document

### ISSUE THREAD

**Issue by Elchi3** [mdn/yari#7196]
### Summary

On latest main, the following command:
`yarn content delete Web/API/ShadowRoot/onslotchange --redirect=Web/API/HTMLSlotElement/slotchange_event
`
throws with:

```
yarn content delete Web/API/ShadowRoot/onslotchange --redirect=Web/API/HTMLSlotElement/slotchange_event 
yarn run v1.22.19
$ env-cmd --silent cross-env CONTENT_ROOT=files yari-tool delete Web/API/ShadowRoot/onslotchange --redirect=Web/API/HTMLSlotElement/slotchange_event

error: document does not exists: /en-US/docs/Web/API/ShadowRoot/onslotchange

error Command failed with exit code 1.
```

Same command before https://github.com/mdn/content/pull/20770 (probably https://github.com/mdn/yari/pull/7008)

```
yarn run v1.22.19
$ env-cmd --silent cross-env CONTENT_ROOT=files yari-tool delete Web/API/ShadowRoot/onslotchange --redirect=Web/API/HTMLSlotElement/slotchange_event
Will remove 1 documents:
Web/API/ShadowRoot/onslotchange
Redirecting document to: Web/API/HTMLSlotElement/slotchange_event
? Proceed? Yes
Moved 1 documents.
✨  Done in 3.10s.
```

### URL

no url

### Reproduction steps

Run yari content cli for page deletion. `yarn content delete <slug>`

### Expected behavior

Document to delete is found and deleted.

### Actual behavior

Document isn't found, can't be deleted.

### Device

Desktop

### Browser

Other (specify below)

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by SphinxKnight** [comment]
reproduced with `yarn tool delete conflicting/Glossary/Firefox_OS fr --redirect Glossary/Boot2Gecko`

Checked out 79f3eb93bfa4a3c1a6c9138fe5c350af4538d3f5 and it works.
Looks like a unwanted side effect of https://github.com/mdn/yari/commit/d1d02fb55525b758781105e1e00bb9b65bed8bc3 / https://github.com/mdn/yari/pull/7008
