### ISSUE TITLE
Italic not showing on Safari

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/yari#7203]
### Summary

On Safari, _italic_ font is exactly the same as the normal upright version.

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Memory_Management#weakmaps_and_weaksets

### Reproduction steps

Read the sentence:

> `WeakMap` and `WeakSet` got the name from the concept of _weakly held_ values. 

### Expected behavior

Chrome/Firefox rendering:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/55398995/191337908-059ab5b2-509d-4fba-99ec-f464a90437d5.png">

### Actual behavior

Safari rendering:

<img width="782" alt="image" src="https://user-images.githubusercontent.com/55398995/191337958-e78e6b9c-ff4e-4717-999b-16839d944e2b.png">

(Reproducible on iPad/iPhone as well)

### Device

Laptop

### Browser

Safari

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by Elchi3** [comment]
I can reproduce this issue, fwiw.

**Comment by caugner** [comment]
This doesn't seem to be a general issue in Safari, see: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em#result

So it looks like an issue with the font (Inter) we're using.

**Comment by ironnysh** [comment]
Hi,
seems like it's missing a `font-variation-settings: "slnt" -10;` on `em` elements (see also [this reference](https://fonts.google.com/knowledge/using_type/styling_type_on_the_web_with_variable_fonts#registered-axes-italic-and-slant)).

Here's a screenshot from Safari 17.2.1:

<img width="1108" alt="image" src="https://github.com/mdn/yari/assets/63248335/9b693bac-69dc-4681-93e3-fb3cde0b9221">

**Comment by ironnysh** [comment]
@caugner --I'm happy to open a PR, but I'm not sure in which stylesheet it belongs :-)

**Comment by ironnysh** [comment]
@caugner, done now :-)
