### ISSUE TITLE
H3 and H4 section headings are hard to tell apart

### ISSUE THREAD

**Issue by bsmth** [mdn/yari#7204]
### Summary

The font sizes of `<h3>` and `<h4>` elements are quite similar. It's hard to tell if a section is a subsection or not based on styling. 

There is a difference in font size, but if both titles are capitalized, it's tough to tell them apart.

### URL

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/105#apis

### Reproduction steps

1. Go to https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/105#apis
2. See `APIs` (h3) and `DOM` (h4)

### Expected behavior

I can tell that "DOM" is a subsection of "APIs".

### Actual behavior

The font sizes look very similar:

* APIs - 27.648px (1.17em)
* DOM - 23.04px (1em)

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

![image](https://user-images.githubusercontent.com/43580235/191454933-5f3ab2f9-1bf4-4ca1-9990-0d37b76f22bf.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
FWIW The heading fonts are defined here:

https://github.com/mdn/yari/blob/05851d9f35e81c92d0400585cd62e0843f684499/client/src/app.scss#L35-L68

**Comment by caugner** [comment]
Our designer made some suggestions to update the heading font sizes and weights, but this turned out to be more tricky than expected, as we use `<h4>` in our sidebars ("Related Topics" + "In this article"), so we'll need at least one other iteration. Unfortunately this may take some time due to PTOs and other priorities.

**Comment by bsmth** [comment]
I think this one is quite subjective so I'm going to close for now unless there's some other people who also see this as an issue.
