### ISSUE TITLE
Issue with "::first-letter (:first-letter)": (Google search result header does not show properly for pseudo-classes)

### ISSUE THREAD

**Issue by deekeh** [mdn/yari#7212]
MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter

#### What information was incorrect, unhelpful, or incomplete?
When we search for any pseudo-class on Google, It ignores some of the first keywords while showing MDN in the results list.

#### Specific section or headline?
![image](https://user-images.githubusercontent.com/43519784/140538564-3ce8ea77-e976-4dd1-8701-a86aa70425eb.png)
For instance, the result should show something like `::before (:before) - CSS: Cascading Style Sheets - MDN Web Docs`. But instead, it ignores "::before (:" part in the results.

#### What did you expect to see?
Some result header like `::before (:before) - CSS: Cascading Style Sheets - MDN Web Docs` should show in the results. It seems to be some issue in SEO.

#### Did you test this? If so, how?
Checked on different search Engines by searching the same text "css before".
Search engines tested on:
1. [Google](https://www.google.com/search?q=css+before): failed
1. [Duckduckgo](https://duckduckgo.com/?q=css+before): passed
1. [Dogpile](https://www.dogpile.com/serp?q=css+before): passed
1. [Yandex](https://yandex.com/search/?text=css+before): passed (shows `before` instead of `::before`)

<details>
<summary>MDN Content page report details</summary>

* Folder: `en-us/web/css/_doublecolon_first-letter`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/::first-letter
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/_doublecolon_first-letter/index.md
* Last commit: https://github.com/mdn/content/commit/26f50bdaeb1228f458d21dbdf7dc110387b20daa
* Document last modified: 2021-08-12T23:59:09.000Z

</details>

**Comment by caugner** [comment]
It may still take some days until the search index is updated, but it should indeed have been fixed by #7166.
