### ISSUE TITLE
Ux: left sidebar with links could persist scroll height

### ISSUE THREAD

**Issue by Gynko** [mdn/yari#7278]
**Culprit:** the left sidebar with links, that appears at breakpoint 769px on desktop.

**Problem**: I am now reading through the long list of CSS properties. Each time I click on the link of a property to read the article, the sidebar gets refreshed and I am taken to the top of the list of properties. To get to the next property I need to scroll back again through the list. 

**Idea**: we could persist the scroll height when we have clicked on a link, instead of reloading the sidebar.

**Comment by caugner** [comment]
Hi @Gynko, thank you for taking the time to report this issue. 👋 

Please use our [issue template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml) to make sure we have all the information to properly triage it. Thanks! 🙏
