### ISSUE TITLE
Centralize all wikihistory.json files, maybe?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#729]
### Pros:

* We might be able to read it all in in one sweep instead of having to open the local `./wikihistory.json` file each time we're in `processFolder` in the builder. 
* Fewer files for the watcher to watch. 
* Just generally lest files when navigating around in the tree.
* Putting it all in one big file means less disk usage since individual files weigh more on disk than their size in bytes (due to all the metadata (access time, modification time, creation time, permissions))

### Cons:

* When you move a tree (or a folder for that matter) you need to mutate this one massive file each time rather than just letting it be moved. 
* Our git history won't ever forget so now we're going to have that in our history *and* as centralized files. 
* It might be hard/cumbersome when it's so large but it's never meant for humans to mess with anyway. 
* Just like `this.allRedirects` this will mean more in-memory head usage. 

### Notes/Ideas:

* It might be worth checking in to git in .gz (e.g. `content/files/en-us/_wikihistory.json.gz`) since it'll compress really well and it means less weight in the git repo. Also, it "sends a message" that you're never supposed to manually edit it.

**Comment by peterbe** [comment]
After a quick hack on the importer.js you get, for example:
```
▶ ls -lh content/files/en-us/_wikihistory.json
-rw-r--r--  1 peterbe  staff   5.4M Jun  9 14:14 content/files/en-us/_wikihistory.json

```
It's pretty big. But check this out! I took a copy of the whole `content/files/en-us` directory to `/tmp` and can now compare their disk usage:

```
▶ du -sh content/files/en-us
 76M	content/files/en-us

▶ du -sh /tmp/en-us
110M	/tmp/en-us
```

And when I use `ncdu` I get:
```
Total disk usage:  75.6 MiB  Apparent size:  58.1 MiB  Items: 20294
```
vs 
```
Total disk usage: 109.8 MiB  Apparent size:  55.4 MiB  Items: 30432
```
Pretty attractive!

**Comment by peterbe** [comment]
And to prove that it compresses well, see:
```
▶ ls -lh content/files/en-us/_wikihistory.json*
-rw-r--r--  1 peterbe  staff   5.4M Jun  9 14:14 content/files/en-us/_wikihistory.json
-rw-r--r--  1 peterbe  staff   887K Jun  9 14:14 content/files/en-us/_wikihistory.json.gz

```

**Comment by peterbe** [comment]
Oops! I didn't respect the `isArchive` thing. Now, the centralized `content/files/en-us/_wikihistory.json` is much smaller:
```
▶ ls -lh content/files/en-us/_wikihistory.json*
-rw-r--r--  1 peterbe  staff   3.1M Jun  9 14:38 content/files/en-us/_wikihistory.json
-rw-r--r--  1 peterbe  staff   494K Jun  9 14:38 content/files/en-us/_wikihistory.json.gz

```
So, instead you get:
```
▶ du -sh content/files/en-us
 74M	content/files/en-us
```

**Comment by peterbe** [comment]
Wow! If we gzip the file and read it in at the beginning of the builder, it's virtually no slower:
```javascript
const zlib = require("zlib");
const { performance } = require("perf_hooks");

function f1() {
  const parsed = JSON.parse(
    fs.readFileSync("content/files/en-us/_wikihistory.json")
  );
  return parsed["API/File_API"];
}

function f2() {
  const parsed = JSON.parse(
    zlib.gunzipSync(fs.readFileSync("content/files/en-us/_wikihistory.json.gz"))
  );
  return parsed["API/File_API"];
}

function test(func) {
  const t0 = performance.now();
  const r = func();
  const t1 = performance.now();
  console.log(func.name, "TOOK", t1 - t0);
  console.log(r);
}

test(f1);
test(f2);
```

This outputs:
```
f1 TOOK 31.045610904693604
{
  modified: '2020-04-07T19:13:59.210Z',
  contributors: [ 'escattone', 'mdnwebdocs-bot', 'huangdarwin', 'grendel' ]
}
f2 TOOK 32.68551301956177
{
  modified: '2020-04-07T19:13:59.210Z',
  contributors: [ 'escattone', 'mdnwebdocs-bot', 'huangdarwin', 'grendel' ]
}
```

So I definitely think we should check these into git in .gz format.

**Comment by peterbe** [comment]
[I now have a fully working draft of this.](https://github.com/mdn/yari/pull/730) 
The harsh reality is that I can't detect any improvement to the builder speed. 
I ran it a couple of times before and a couple of times after and there was no distinct difference in the number of docs per second. I think it's because the opening of each `wikihistory.json` (and parsing it) is dwarfed by the slowness of other bigger things like kumascript and syntax highlighting. 

So I think the reasoning goes back to evaluating the DX and the other aspects such as file size stuff on disk.

**Comment by peterbe** [comment]
@Gregoor Can you please have a think about this. You'd have to scream to stop the moving train because I think both @escattone and myself are pretty confident it's a good idea.

**Comment by Gregoor** [comment]
Oh sorry I thought my affirmation in our last 1:1 was enough. I'm on-board!

**Comment by peterbe** [comment]
The new importer is in place and I checked in all the new content in: https://github.com/mdn/yari/commit/165c30967e58a40cf578edf282c80f840a9b685b

So now you can see: [No `wikihistory.json`](https://github.com/mdn/yari/tree/master/content/files/en-us/web/html/element/audio)
Instead, it's all in [this beast](https://github.com/mdn/yari/blob/master/content/files/en-us/_wikihistory.json)

We can close this issue once I've updated the code that needs to rewrite that file after you rename something from the Toolbar.

**Comment by peterbe** [comment]
Done.
