### ISSUE TITLE
Browsers survey is blank on iOS

### ISSUE THREAD

**Issue by nickmccurdy** [mdn/yari#7348]
### Summary

I got a survey alert on my iPhone, but it's blank when I expand it.

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

### Reproduction steps

1. Open an article on iOS
2. Be selected to complete the browsers survey
3. Expand the browsers survey

### Expected behavior

Form is visible

### Actual behavior

Form is blank (with just the purple alert background)

### Device

Smartphone

### Browser

Safari

### Browser version

Pre-release (e.g. Beta, Nightly or Canary)

### Operating system

iOS

### Screenshot

![Screenshot](https://user-images.githubusercontent.com/927220/196010483-7c8fad40-2831-4c87-bd71-dee4d39143db.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by bershanskiy** [comment]
[Yari contains CSP `frame-src` directive](https://github.com/mdn/yari/blob/1850cecade16ebb1105ef31075d8867eac1ac031/libs/constants/index.js#L107) which blocks the survey frame.

This is the apperance of survey on Chromium on Linux:
![Screenshot from 2022-10-16 02-10-19](https://user-images.githubusercontent.com/45960703/196010971-99c3230a-b30d-449c-8f80-4869b4e7fc53.png)

**Comment by schalkneethling** [comment]
This has been resolved. Thanks you everyone.
