### ISSUE TITLE
Links to global attributes contain wrong uri fragment

### ISSUE THREAD

**Issue by irrelevation** [mdn/yari#7349]
### Summary

When clicking on a link to a global attribute, I land on the correct page but always at the top and not at the correct scroll position.
The reason is due to the htmlattrxref macro prefixing the uri fragment with `attr-` wich  does not exist on ids on the global attributes page.

### URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes#attr-part

### Reproduction steps

1. Visit https://developer.mozilla.org/en-US/docs/Web/CSS/::part
2. Click on the link labeled 'part'
3. You will get redirected to the global attributes page without scrolling to the correct position

### Expected behavior

I would expect the page to be scrolled to the correct position.

### Actual behavior

The page does not scroll.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Good catch, thank you for reporting.

This regression was introduced by https://github.com/mdn/content/pull/14870, which replaced occurrences of the `HTMLAttrDef` macro (that explicitly defined the `#attr-` anchors).

Explicit links were updated, but the `htmlattrxref` macro was not updated accordingly.
