### ISSUE TITLE
No Combinators navigation in CSS navigator

### ISSUE THREAD

**Issue by wangshuihua** [mdn/yari#7437]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors

### What specific section or headline is this issue about?

Combinators

### What information was incorrect, unhelpful, or incomplete?

Each time I want to check **Combinators**, I need to go to **CSS selectors** page. There is no Combinators navigator on the left side, which is not helpful and incomplete in structure.

### What did you expect to see?

I can follow the Combinators navigator on the left side, no need to go to Combinators section from CSS selectors page.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/attribute_selectors`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/attribute_selectors/index.md
* Last commit: https://github.com/mdn/content/commit/aec3ea04d6fcc42227960edaa2e8b90d4c16704f
* Document last modified: 2022-09-29T16:04:11.000Z

</details>

**Comment by wbamberg** [comment]
Thanks for filing, @wangshuihua !This would need to be addressed in the MDN macro code, so I'm transferring it to the MDN platform repo.
