### ISSUE TITLE
Failed to load browser compatibility table

### ISSUE THREAD

**Issue by Selflocking** [mdn/yari#7466]
### Summary

maybe because https://github.com/mdn/yari/commit/05851d9f35e81c92d0400585cd62e0843f684499#diff-992e84d53a490b687d006958a87fdcebee197e7a5317bec8337a69e617cafde3R40

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object#browser_compatibility

### Reproduction steps

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object#browser_compatibility

### Expected behavior

browser compatibility table

### Actual behavior

error

### Device

Desktop

### Browser

Edge

### Browser version

Stable

### Operating system

Linux

### Screenshot

![image](https://user-images.githubusercontent.com/53544726/199030413-b520b0a0-a4b9-4d67-b72e-0c1ef36bbc68.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by danielhjacobs** [comment]
Opened #7469. Hoping for a quick merge, since it's a simple change.
