### ISSUE TITLE
buildDocumentFromURL: no Prism grammar for 'js-nolint' found

### ISSUE THREAD

**Issue by hinell** [mdn/yari#7477]
### Summary

```
...
Unable to find a Prism grammar for 'js-nolint' found in /en-US/docs/Web/API/Document/execCommand
buildDocumentFromURL(/en-us/docs/web/api/document/execcommand):
...
Unable to find a Prism grammar for 'js-nolint' found in /en-US/docs/Web/API/HTMLInputElement/setSelectionRange

```
When Yari is run (`npm run start` ) in the MDN content repo clone I get the above error. It stalls the build process for a few minutes and makes locally hosted instance unresponsive. When resumes it works as usual. I think after npm update this issue is gone. Anyone?it's

### URL

Locally run server

### Reproduction steps

```bash
git clone --no-tags --depth 1 git@github.com:mdn/content.git mdn-content
cd mdn-content
npm run start
```

The following command DOESN'T show the error:

```bash
CONTENT_ROOT="$(pwd)/files" $(npm bin)/yari-build '/en-us/web/api/document/execcommand/index.md'
```

### Expected behavior

Fast bulid, no stalls

### Actual behavior

Temporarili stalling buld

### Device

Desktop

### Browser

Other (specify below)

### Browser version

Stable

### Operating system

Linux

### Diagnostics
```
GNU/Linux Kubuntu 22.04.1 LTS
Nodejs v16.15.1
npm ls --depth 0
    content@1.0.0 /media/../../MDN/content
    ├── @mdn/yari@1.22.0
    ├── cross-env@7.0.3
    ├── env-cmd@10.1.0
    ├── husky@8.0.1
    ├── lint-staged@13.0.3
    ├── markdownlint-cli2@0.5.1
    ├── markdownlint-rule-search-replace@1.0.5
    └── prettier@2.7.1
```

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Fixing https://github.com/mdn/yari/issues/7379 would probably solve this.

**Comment by caugner** [comment]
Hi @hinell, thank you for taking the time to report this issue! 👋 

> ```shell
> git clone --no-tags --depth 1 git@github.com:mdn/content.git mdn-content
> cd mdn-content
> npm run start
> ```

You appear to be missing a step between cloning and running the `start` script, namely installing the **yarn** dependencies. According to the [README](https://github.com/mdn/content/#build-the-site), you'll want to run `yarn` and `yarn start` (not `npm`), and that works for me.

Closing as "can't repro", but please let us know if the issue persists with yarn. 🙏

**Comment by hinell** [comment]
@caugner Well deps were nstalled before that.
I've later reinstalled everything and it seems like that the issue has disappeared. For now at least. :roll_eyes:

**Comment by caugner** [comment]
Glad to hear!
