### ISSUE TITLE
ts-loader in ssr?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#749]
You get this in `yarn install`:
```
warning "workspace-aggregator-c122f266-4e1b-4d30-a55b-9884de96e226 > ssr > ts-loader@7.0.5" has unmet peer dependency "typescript@*".
```

I have yet to understand exactly where we are with TS and the `ssr` workspace. 
[Is this related?](https://github.com/mdn/yari/blob/992acbd02cd9c203a363a880a72be8ac43f5eb66/ssr/package.json#L24)

**Comment by peterbe** [comment]
@Gregoor might know?

**Comment by Gregoor** [comment]
Oh I forgot to take care of it, thanks. I played the risky game and pushed it straight to master (since it should be trivial)
