### ISSUE TITLE
Rough notation graphics jump when the toolbar changes height

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#751]
Before expanded one of the macro flaws:
<img width="1119" alt="Screen Shot 2020-06-15 at 4 17 45 PM" src="https://user-images.githubusercontent.com/26739/84701953-e04bc680-af23-11ea-8b61-56841eca4a6a.png">

After:
<img width="1083" alt="Screen Shot 2020-06-15 at 4 17 55 PM" src="https://user-images.githubusercontent.com/26739/84701965-e477e400-af23-11ea-8cfe-d02500ef3d82.png">

**Comment by peterbe** [comment]
The solution must be to re-run the code that applies the rough-notation when you expand macro flaws.

**Comment by pshihn** [comment]
If the annotated element is inside a positioned parent, e.g. `position:relative;` then expanding the section above should not affect the annotation layout, it will move with the annotated content. I think this is the cleaner solution here. 

Or, as you suggest, you could update the annotation by calling `annotation.show()` again which will update the position - but if you add several dynamic sections on the page, you may not want to add logic in every section.

**Comment by peterbe** [comment]
> If the annotated element is inside a positioned parent, e.g. `position:relative;` then expanding the section above should not affect the annotation layout, it will move with the annotated content. I think this is the cleaner solution here.
> 

We're about to replace all the CSS so I'll keep that in mind when that lands. CC @schalkneethling 

> Or, as you suggest, you could update the annotation by calling `annotation.show()` again which will update the position - but if you add several dynamic sections on the page, you may not want to add logic in every section.

That turns out to be a pain because `RoughNotation` is used from a completely different React component. So the two independent components would need to chat across to each other. 
One simple solution would to not use expansion things in the first place.

**Comment by pshihn** [comment]
btw the positioned element doesn't need to be the immediate parent but up the tree anywhere before the collapsible section.

**Comment by peterbe** [comment]
Now blocked by https://github.com/mdn/yari/issues/1541

@schalkneethling When you're done with that one, do you wanna take a look at this one?
