### ISSUE TITLE
Duplicate `toc-entries` id

### ISSUE THREAD

**Issue by MrBrain295** [mdn/yari#7537]
### Summary

The `toc-entries` id is applied to some elements twice. 

### URL

Pretty much all URLs.

### Reproduction steps

1. Open the [Nu HTML checker](https://validator.w3.org/nu/).
2. Check any MDN URL.
3. See the error.

### Expected behavior

No duplicate ids.

### Actual behavior

Duplicated ids.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Screenshot

![Screenshot of the error](https://user-images.githubusercontent.com/66077254/200956712-4aebabe7-5672-4d14-8d9c-3de2d7e5c15a.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
@MrBrain295 Good catch, thanks! Could you open a PR that removes the `toc-entries` ID from the element? It doesn't appear to be used anywhere. 🙂
