### ISSUE TITLE
Should whitespace be allowed in content folders?

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#758]
As of right now, you can actually create a content folder with a space in it. It works. 
(note the slug in the front-matter in the `index.html` didn't have a space). 
I created a folder called `jpeg 2000` and it just worked. 

If this is "dangerously problematic", we should include it in our builder that if it finds a `index.html` in a folder whose name contains a whitespace, it should break. 

So, what's the problem with content folder with a space in it? I definitely find it annoying when you use tab completion sometimes on the command line and that's why I prefer using `_` or `-` so that it's easier for me in ther terminal. 

What do you think?

**Comment by escattone** [comment]
I really dislike folders and files with spaces in their names, if only because I find them confusing and difficult to work with. I would vote for disallowing spaces.

**Comment by wbamberg** [comment]
I would prefer us to disallow spaces. I'm not sure whether "-" or "_" is better. I think we tend towards "-" in filenames.

**Comment by peterbe** [comment]
Seems we all agree. Let's build it into the builder since we don't have a linting stage that checks everything before it starts. The `ensureAllTitles` function is the first thing that starts looping over folders. What it could simply do is something like:

```diff
function getContent(source, folder, appendWikiHistory = false) {
+ if (folder.includes(' ')) {
+    throw new Error(`Folders not allowed to contain a space (${folder} in ${source}`)
+} 
  const rawHtmlFilepath = path.join(folder, "index.html");
  const rawContent = fs.readFileSync(rawHtmlFilepath, "utf8");
```

**Comment by peterbe** [comment]
Note, it should probably also do this check when it validates the slug. At the moment, if you create a folder and set the slug to something that is *not* the same as the folder (minus and transformations) it will break, but the error is always a bit cryptic.

**Comment by peterbe** [comment]
@escattone Does the contribution guide (your Markdown doc in mdn/content) or the contribution guides inside the actual content spell this out?

For the record, I'm going to tackle this in a way that you should notice it right away when you create a new doc using the yari previewer. But it should also get caught in the CI if you create or edit a folder and introduce whitespace without ever running Yari locally.

**Comment by peterbe** [comment]
Thankfully, in our production MySQL there are slugs today, that aren't redirects, that contain a whitespace:
```
>>> Document.objects.filter(slug__contains=' ').count()
25
>>> Document.objects.filter(slug__contains=' ', is_redirect=True).count()
25
```
(from prod, Oct 8)

**Comment by escattone** [comment]
> @escattone Does the contribution guide (your Markdown doc in mdn/content) or the contribution guides inside the actual content spell this out?

👍 No, not yet, but I'll add a comment about it.

**Comment by peterbe** [comment]
Wonderful! I upgraded mdn/content so it uses this new builder. And I merged in `main` into [this PR](https://github.com/mdn/content/pull/40) and clearly it now fails. As expected!
