### ISSUE TITLE
Code size has got disproportionately large

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/yari#7586]
I don't know if it's intended because I couldn't find an issue/PR for it, but I noticed that starting a few days ago the size of monospace font has grown larger.

Before (from a [deploy preview](https://pr21831.content.dev.mdn.mozit.cloud/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)):

![image](https://user-images.githubusercontent.com/55398995/201993591-7fd94f22-2656-4a17-819d-e711ca644076.jpeg)

After (on [production](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment)):

![image](https://user-images.githubusercontent.com/55398995/201993642-a55fb6cf-a934-4fae-85d3-f146453adb42.jpeg)

This makes the code wrapping problem even more serious, and it just looks out of the place because the code is even bigger than h4 headings. This can be reproduced on my Mac's Safari and Chrome as well as iPad Safari. I wonder if we can revert to the previous typography where code is the same size as (or preferably slightly smaller than) the main text.

**Comment by caugner** [comment]
@Josh-Cena Please make sure to always use the [Bug report template](https://github.com/mdn/yari/issues/new?assignees=&labels=bug&template=bug-report.yml) when reporting issues.

As for the issue, I cannot reproduce it [on this page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#examples) using Firefox:

<img width="795" alt="image" src="https://user-images.githubusercontent.com/495429/202022843-c665245b-ad0d-4ec9-807e-52d434877867.png">

**Comment by Josh-Cena** [comment]
I could not reproduce it on Firefox either, but you should be able to in both Chrome and Safari. Looking closer, it looks like the fontface used has changed. Are there CSS changes recently that might affect this?

Apologies for skipping the template—I did not have access to a computer when I submitted this so I went for something quick and dirty. Should I resubmit with my system/browser info, or is this a wontfix?

**Comment by caugner** [comment]
> edit my OP

Yes, editing the OP is always welcome.

**Comment by caugner** [comment]
Never mind, this is actually the effect of https://github.com/mdn/yari/pull/7131, even though that was mainly intended to target the Japanese locale, it looks like code blocks were previously not consistent between Chrome/Safari and Firefox. Now they are!
