### ISSUE TITLE
Browser compatibility should show release date and current stable version

### ISSUE THREAD

**Issue by oojacoboo** [mdn/yari#7603]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

### What specific section or headline is this issue about?

Browser compatibility

### What information was incorrect, unhelpful, or incomplete?

This section is very helpful.  However, it's extremely frustrating that there isn't any context provided with the versions supported.  Maybe some people have every version memorized in their head.  But, I surely don't, never will and don't care to.

### What did you expect to see?

I'd really like to see 2 additional data points.

- The release date of the supported version
- The current latest stable version

With this information, I'd now be able to determine if the browser compatibility for the current "feature" is acceptable or not.  As it presently stands, it requires additional research.

### Do you have any supporting links, references, or citations?

List of latest versions:
https://browser-update.org/browsers.html

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/javascript/reference/functions/default_parameters`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/javascript/reference/functions/default_parameters/index.md
* Last commit: https://github.com/mdn/content/commit/87a9f73c410c9b9e91300695c8aa4931367243fb
* Document last modified: 2022-09-13T07:01:32.000Z

</details>

**Comment by caugner** [comment]
> The timeout on triggering it for hover seems way too long. Additionally, some extra styling on it might be nice.

We use the `title` attribute, so the tooltip timeout and styling is determined by your browser.

> As for the latest version, it's not irrelevant. I concur that the time since the first supported version is the most important.

Could it be that you want to see if a feature got support **only recently**? If so, https://github.com/mdn/yari/pull/7546 would cater for your use case.

Other than that, showing the release date (not only as a tooltip) has been requested in https://github.com/mdn/yari/issues/6812.

**Comment by oojacoboo** [comment]
@caugner thanks for the details on these other issues.

>Could it be that you want to see if a feature got support only recently? If so, https://github.com/mdn/yari/pull/7546 would cater for your use case.

Kinda.  It's more that... if support came in version 50, released on 2018/01/01 and we're now on version 112, while I don't know for certain that they followed a normal versioning pattern, I can assume it's probably likely and by the sheer number of releases since that date, I can tell that it's likely it's well supported and tested within the browser.

#6812 would be great.  The title attribute has never worked well in browsers.  It's nice to have... I guess.  But it's always been poorly done from a UX perspective IMO.

**Comment by caugner** [comment]
> At the end of the day, I just want to know if I can use the feature or not.

Understood.

> Obviously caniuse.com is excellent for this. But that's another searching process. Maybe you guys can just partner with them and include a "module" with their data.

FWIW Linking to caniuse has been suggested in https://github.com/mdn/yari/issues/4800.

PS: It has also been suggested in https://github.com/mdn/yari/issues/1400 to add a row for the current version number. 😉

**Comment by danielhjacobs** [comment]
Perhaps a better alternative to title for release date may be this:

```html
<span class="bc-version-label" title="">
  (Number)
  <span class="released">Released (date)</span>
</span>
```

```css
.bc-version-label:hover .released {
  display: block;
}

.released {
  display: none;
  background: black;
  opacity: 0.8;
  margin-left: 9px;
  padding: 8px 10px;
  position: absolute;
  z-index: 1000;
  height: 40px;
  margin-top: 16px;
  border-radius: 6px;
  color: white;
}
```

Note that the CSS there is meant to be fairly close to the styling provided by the title tag for demonstration. There may be better styling alternatives.
