### ISSUE TITLE
Constant refresh of interactive examples

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/yari#7630]
### Summary

Iframe of interactive examples is now constantly being refreshed every few seconds. It makes writing code in the editor impossible and flash of white background is really annoying. I noticed it today and I check interactive examples very often, so it must be caused by one of the recent updates.

I have checked it on Chrome, Firefox and Safari. Result is the same on all 3 browser within 2 devices.

This issue must have been caused by yari, because devtools shows that it's triggered by react and if you open same example in [https://interactive-examples.mdn.mozilla.net/pages/js/array-foreach.html](https://interactive-examples.mdn.mozilla.net/pages/js/array-foreach.html), problem doesn't occur.

### URL

I think it happens on all interactive examples, but you can check it here: [https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach)

### Reproduction steps

Simply open page, try to write something in interactive example and see how your input is gone after few seconds.

### Screenshot

https://user-images.githubusercontent.com/100634371/202913834-7e3c9b8d-42cd-4218-8394-5187ef0ff709.mp4

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/mdn/yari/discussions).

**Comment by caugner** [comment]
Most likely a side-effect of https://github.com/mdn/yari/pull/7444.

On mobile, the examples refresh only if the sidebar is toggled to be visible.
