### ISSUE TITLE
T - Cleanup CLI output more relevant (less noisy) to content team. 

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#765]

**Comment by tobinmori** [comment]
@chinikes we're going to pull this out of the sprint, because it's not relevant right now, but maybe later.

**Comment by chinikes** [comment]
> @chinikes we're going to pull this out of the sprint, because it's not relevant right now, but maybe later.

Got it Tobin. Thanks for the heads up

**Comment by Gregoor** [comment]
Originally I was only thinking about the initial startup, but watching Daniel test it became clear there's more opportunities. Like atm when a file is changed, it outputs three logs about changed files, some of them intermediary files, which are barely interesting to content folk. Instead it should probably only be a log with clickable links like:
```zsh
Document changed
edit: content/en-us/web/api/document/query_selector/index.html
view: localhost:3000/en-US/docs/Web/API/Document/querySelector
```

**Comment by peterbe** [comment]
They probably also don't need to know that it took 198.8601669273 milliseconds :)
