### ISSUE TITLE
WebExtExamples macro displays empty section on WebExtensions `commands` API page

### ISSUE THREAD

**Issue by abhn** [mdn/yari#7703]
### MDN URL

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands

### What specific section or headline is this issue about?

Example extensions

### What information was incorrect, unhelpful, or incomplete?

The headline "Example extensions" doesn't make sense after the headline "Browser compatibility" and before the table of browser compatibility data. Especially also as there are no examples listed.

<img width="729" alt="image" src="https://user-images.githubusercontent.com/6270406/204260740-89782487-314c-4344-b1cf-8d0b9459bcbf.png">

### What did you expect to see?

No "Extension examples" headline

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/mozilla/add-ons/webextensions/api/commands`
* MDN URL: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/mozilla/add-ons/webextensions/api/commands/index.md
* Last commit: https://github.com/mdn/content/commit/1ee49b729dc4cd02b862d910f279861f4b30e704
* Document last modified: 2022-09-09T05:03:45.000Z

</details>

**Comment by bsmth** [comment]
I've transferred this issue to Yari as it looks like the following is happening, but needs further investigation:

The [WebExtExamples macro](https://github.com/mdn/yari/blob/main/kumascript/macros/WebExtExamples.ejs) should be picking up [existing commands examples](https://github.com/mdn/webextensions-examples/blob/master/examples.json#L87).

**Comment by caugner** [comment]
The reason this happens is that the `WebExtExamples` macro is called inside the "Browser compatibility" section, so it gets removed somehow, possibly as part of lazy-loading the BCD table.

Essentially https://github.com/mdn/content/pull/22632 will fix this, and we don't need to update yari.
