### ISSUE TITLE
Macro flaws included for recursively sub-renders in other pages

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#772]
If you open http://localhost:3000/en-US/docs/Web/HTML/Element/img#_flaws you'll see that it complains about a `MacroRedirectedLinkError` on line 1212. 
But that flaw is actually not in this page. This page (`en-us/web/html/element/img/index.html`) only has 417 lines!
So, this flaw shouldn't even be mentioned when you press the "Show flaws" button.

The actual macro flaw is actually in http://localhost:3000/en-US/docs/Web/Media/Formats/Image_types#_flaws
There, it *should* appear when you press the "Show flaws" button.

**Comment by peterbe** [comment]
I don't know how to implement it but the solution would be something like passing in an argument to the kumascript render method so that it knows if it's gone deeper recursively or on the "top level" and use this fact to add or not to add the non-fatal flaw error objects. 

Thankfully, the above two URLs describe enough how the acceptance criteria should work to test a PR on this issue.

**Comment by escattone** [comment]
I don't think this is a bug with the way flaws are being returned in the code, but I think it means that we need to change with the way we're presenting the flaws in the toolbar.

Considering http://localhost:3000/en-US/docs/Web/HTML/Element/img#_flaws, the `MacroRedirectedLinkError` flaw's `filepath` is `content/files/en-us/web/media/formats/image_types/index.html`, not `content/files/en-us/web/html/element/img/index.html`, so from that we can tell it's a flaw that originates from a prerequisite document and not this document itself. This document (`Web/HTML/Element/img`) depends on the document `Web/Media/Formats/Image_types` because it makes this `page` macro call:
```
<p>{{page("/en-US/docs/Web/Media/Formats/Image_types", "table-of-image-file-types")}}</p>
```
and the `MacroRedirectedLinkError` flaw occurs when rendering that prerequisite.

Thinking out loud, here's one possible approach for handling these flaws that come from the recursive chain of prerequisites.
1. We always check the flaw's`filepath` (or some new attribute that we add to the flaw, like it's document URI or slug) as the first step in determining whether to display the flaw or not.
1. If it matches the current page, we of course always show it.
1. If it doesn't match the current page,  we do some more checking.
1. If it's a fatal flaw (for now, **not** a `MacroRedirectedLinkError` or `MacroBrokenLinkError`), do NOT show it. This means it's a fatal flaw in one of the prerequisite documents, but that flaw will never show up on the current page because its macro call will remain unresolved.
1. If it **is** a non-fatal flaw (for now, a `MacroRedirectedLinkError` or `MacroBrokenLinkError`), **and** the current page contains an element with a `data-flaw-id` attribute whose value matches the value of the flaw's `id` attribute (this of course depends on https://github.com/mdn/yari/issues/756), then display the flaw since although it's origin is another page, it has been included into the current page.

What do you think? Let's think about that more.

**Comment by peterbe** [comment]
It's a bit weird to have to make a distinction specifically for `MacroRedirectedLinkError` and `MacroBrokenLinkError`. These just happen to be non-fatal ones. 

But I definitely think it'd be useful to know, when you're on http://localhost:3000/en-US/docs/Web/HTML/Element/img#_flaws that the page you're actively worrying about is depending on a busted page. "You're fool for depending on /en-US/docs/Web/Media/Formats/Image_types because that page is full of all sorts of wrongs".
Hiding or abstracting that away feels fragile and just strange. 

Python does a good job of this in that stacktraces are pushed to a list. If you get an exception, oftentimes the first traceback in the list is the root cause and where you should go and put your energy. 

Before we make a distinction between specific names (e.g. `MacroRedirectedLinkError` and `MacroBrokenLinkError`) I think we need to turn these macro errors into something so you can find out the flaw "starts" with `<p>{{page("/en-US/docs/Web/Media/Formats/Image_types", ...` in the document you're currently working on. 
I.e. instead of:
```javascript
[{
    name: "MacroRedirectedLinkError",
    line: 1212, column: 123,
    filepath: "content/files/en-us/web/media/formats/image_types/index.html"
}]
```

it should be something like this:

```javascript
[{
    name: "MacroRedirectedLinkError",
    line: 1212, column: 123,
    filepath: "content/files/en-us/web/media/formats/image_types/index.html"
},
{
    name: "MacroRedirectedLinkError",
    line: 417, column: 9,
    filepath: "content/files/en-us/web/html/element/img/index.html"
},
]
```

I'm not sure about the details but it would be a big step forward because now you can make the clickable link open `content/files/en-us/web/html/element/img/index.html:417:9` even though there's not a lot you can do there. But with a bit of work on the UI we can actually display:

1. "This is flaw in a prequisite"
2. "To see the flaw in *this* page, go to line 417:9 (content/files/en-us/web/html/element/img/index.html)"
3. "To see the flaw in the dependent page, go to line 1212:123 (content/files/en-us/web/media/formats/image_types/index.html)"

@escattone Do you want to take a stab and see if you can flesh up the flaw a bit when it's a flaw in a pre-requisite? If it helps, we can pause worrying about how to do the UI (ie. Toolbar) for it for now. 
After all, in my work on automatically fixing fixable flaws, I'm not blocked on this because it uses the `filepath` to its advantage and it just doesn't care where the problem started.

**Comment by peterbe** [comment]
Here's a great page to test things with: http://localhost:3000/en-US/docs/Web/HTML/Element/input/number#_flaws
It breaks the toolbar UI because the same things repeat. You can see it on the command line with:

```
▶ cat client/build/en-us/docs/web/html/element/input/number/index.json| jq ".doc.flaws"
{
  "macros": [
    {
      "name": "MacroBrokenLinkError",
      "error": {},
      "errorMessage": "/en-US/docs/Web/API/HTMLInputElement/value does not exist",
      "line": 432,
      "column": 188,
      "macroName": "domxref",
      "sourceContext": "   34 | <h2 id=\"Value\">Value</h2>\n   35 | \n   36 | <p>The {{htmlattrxref(\"value\", \"input\")}} attribute is a {{domxref(\"DOMString\")}} that contains the current value of the text entered into the text field. You can retrieve this using the {{domxref(\"HTMLInputElement.value\", \"value\")}} property in JavaScript.</p>\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n   37 | \n   38 | <pre class=\"brush: js\">let theText = myTextInput.value;",
      "macroSource": "{{domxref(\"HTMLInputElement.value\", \"value\")}}",
      "filepath": "/Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/web/html/element/input/text/index.html"
    },
    {
      "name": "MacroBrokenLinkError",
      "error": {},
      "errorMessage": "/en-US/docs/Web/API/HTMLInputElement/value does not exist",
      "line": 528,
      "column": 184,
      "macroName": "domxref",
      "sourceContext": "  130 | <h3 id=\"htmlattrdefreadonly\">{{htmlattrdef(\"readonly\")}}</h3>\n  131 | \n  132 | <p>A Boolean attribute which, if present, means this field cannot be edited by the user. Its <code>value</code> can, however, still be changed by JavaScript code directly setting the {{domxref(\"HTMLInputElement.value\")}} property.</p>\n-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n  133 | \n  134 | <div class=\"note\">",
      "macroSource": "{{domxref(\"HTMLInputElement.value\")}}",
      "filepath": "/Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/web/html/element/input/text/index.html"
    },
    {
      "name": "MacroBrokenLinkError",
      "error": {},
      "errorMessage": "/en-US/docs/Web/API/HTMLInputElement/value does not exist",
      "line": 432,
      "column": 188,
      "macroName": "domxref",
      "sourceContext": "   34 | <h2 id=\"Value\">Value</h2>\n   35 | \n   36 | <p>The {{htmlattrxref(\"value\", \"input\")}} attribute is a {{domxref(\"DOMString\")}} that contains the current value of the text entered into the text field. You can retrieve this using the {{domxref(\"HTMLInputElement.value\", \"value\")}} property in JavaScript.</p>\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n   37 | \n   38 | <pre class=\"brush: js\">let theText = myTextInput.value;",
      "macroSource": "{{domxref(\"HTMLInputElement.value\", \"value\")}}",
      "filepath": "/Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/web/html/element/input/text/index.html"
    },
    {
      "name": "MacroBrokenLinkError",
      "error": {},
      "errorMessage": "/en-US/docs/Web/API/HTMLInputElement/value does not exist",
      "line": 528,
      "column": 184,
      "macroName": "domxref",
      "sourceContext": "  130 | <h3 id=\"htmlattrdefreadonly\">{{htmlattrdef(\"readonly\")}}</h3>\n  131 | \n  132 | <p>A Boolean attribute which, if present, means this field cannot be edited by the user. Its <code>value</code> can, however, still be changed by JavaScript code directly setting the {{domxref(\"HTMLInputElement.value\")}} property.</p>\n-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n  133 | \n  134 | <div class=\"note\">",
      "macroSource": "{{domxref(\"HTMLInputElement.value\")}}",
      "filepath": "/Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/web/html/element/input/text/index.html"
    },
    {
      "name": "MacroBrokenLinkError",
      "error": {},
      "errorMessage": "/en-US/docs/Web/API/HTMLInputElement/value does not exist",
      "line": 432,
      "column": 188,
      "macroName": "domxref",
      "sourceContext": "   34 | <h2 id=\"Value\">Value</h2>\n   35 | \n   36 | <p>The {{htmlattrxref(\"value\", \"input\")}} attribute is a {{domxref(\"DOMString\")}} that contains the current value of the text entered into the text field. You can retrieve this using the {{domxref(\"HTMLInputElement.value\", \"value\")}} property in JavaScript.</p>\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n   37 | \n   38 | <pre class=\"brush: js\">let theText = myTextInput.value;",
      "macroSource": "{{domxref(\"HTMLInputElement.value\", \"value\")}}",
      "filepath": "/Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/web/html/element/input/text/index.html"
    },
    {
      "name": "MacroBrokenLinkError",
      "error": {},
      "errorMessage": "/en-US/docs/Web/API/HTMLInputElement/value does not exist",
      "line": 528,
      "column": 184,
      "macroName": "domxref",
      "sourceContext": "  130 | <h3 id=\"htmlattrdefreadonly\">{{htmlattrdef(\"readonly\")}}</h3>\n  131 | \n  132 | <p>A Boolean attribute which, if present, means this field cannot be edited by the user. Its <code>value</code> can, however, still be changed by JavaScript code directly setting the {{domxref(\"HTMLInputElement.value\")}} property.</p>\n-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n  133 | \n  134 | <div class=\"note\">",
      "macroSource": "{{domxref(\"HTMLInputElement.value\")}}",
      "filepath": "/Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/web/html/element/input/text/index.html"
    },
    {
      "name": "MacroBrokenLinkError",
      "error": {},
      "errorMessage": "/en-US/docs/Web/API/HTMLInputElement/value does not exist",
      "line": 432,
      "column": 188,
      "macroName": "domxref",
      "sourceContext": "   34 | <h2 id=\"Value\">Value</h2>\n   35 | \n   36 | <p>The {{htmlattrxref(\"value\", \"input\")}} attribute is a {{domxref(\"DOMString\")}} that contains the current value of the text entered into the text field. You can retrieve this using the {{domxref(\"HTMLInputElement.value\", \"value\")}} property in JavaScript.</p>\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n   37 | \n   38 | <pre class=\"brush: js\">let theText = myTextInput.value;",
      "macroSource": "{{domxref(\"HTMLInputElement.value\", \"value\")}}",
      "filepath": "/Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/web/html/element/input/text/index.html"
    },
    {
      "name": "MacroBrokenLinkError",
      "error": {},
      "errorMessage": "/en-US/docs/Web/API/HTMLInputElement/value does not exist",
      "line": 528,
      "column": 184,
      "macroName": "domxref",
      "sourceContext": "  130 | <h3 id=\"htmlattrdefreadonly\">{{htmlattrdef(\"readonly\")}}</h3>\n  131 | \n  132 | <p>A Boolean attribute which, if present, means this field cannot be edited by the user. Its <code>value</code> can, however, still be changed by JavaScript code directly setting the {{domxref(\"HTMLInputElement.value\")}} property.</p>\n-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n  133 | \n  134 | <div class=\"note\">",
      "macroSource": "{{domxref(\"HTMLInputElement.value\")}}",
      "filepath": "/Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/web/html/element/input/text/index.html"
    },
    {
      "name": "MacroBrokenLinkError",
      "error": {},
      "errorMessage": "/en-US/docs/Web/API/HTMLInputElement/value does not exist",
      "line": 432,
      "column": 188,
      "macroName": "domxref",
      "sourceContext": "   34 | <h2 id=\"Value\">Value</h2>\n   35 | \n   36 | <p>The {{htmlattrxref(\"value\", \"input\")}} attribute is a {{domxref(\"DOMString\")}} that contains the current value of the text entered into the text field. You can retrieve this using the {{domxref(\"HTMLInputElement.value\", \"value\")}} property in JavaScript.</p>\n---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n   37 | \n   38 | <pre class=\"brush: js\">let theText = myTextInput.value;",
      "macroSource": "{{domxref(\"HTMLInputElement.value\", \"value\")}}",
      "filepath": "/Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/web/html/element/input/text/index.html"
    },
    {
      "name": "MacroBrokenLinkError",
      "error": {},
      "errorMessage": "/en-US/docs/Web/API/HTMLInputElement/value does not exist",
      "line": 528,
      "column": 184,
      "macroName": "domxref",
      "sourceContext": "  130 | <h3 id=\"htmlattrdefreadonly\">{{htmlattrdef(\"readonly\")}}</h3>\n  131 | \n  132 | <p>A Boolean attribute which, if present, means this field cannot be edited by the user. Its <code>value</code> can, however, still be changed by JavaScript code directly setting the {{domxref(\"HTMLInputElement.value\")}} property.</p>\n-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------^\n  133 | \n  134 | <div class=\"note\">",
      "macroSource": "{{domxref(\"HTMLInputElement.value\")}}",
      "filepath": "/Users/peterbe/dev/MOZILLA/MDN/yari/content/files/en-us/web/html/element/input/text/index.html"
    }
  ],
  "broken_links": [
    {
      "href": "/en-US/docs/Web/HTML/Element/input/date#Validation",
      "suggestion": null,
      "line": 288,
      "column": 221
    },
    {
      "href": "/en-US/docs/Learn/HTML/Forms",
      "suggestion": "/en-US/docs/Learn/Forms",
      "line": 444,
      "column": 14
    },
    {
      "href": "/en-US/docs/Learn/HTML/Forms/Property_compatibility_table_for_form_widgets",
      "suggestion": "/en-US/docs/Learn/Forms/Property_compatibility_table_for_form_controls",
      "line": 447,
      "column": 14
    }
  ]
}
```

**Comment by peterbe** [comment]
(CC @Gregoor )

what is the status on this? 
I know we got off-track with the bug on repeated flaws. And you've [taken care of that](https://github.com/mdn/yari/issues/810). 
But it's still a slight problem that on http://localhost:3000/en-us/docs/web/html/element/input/number#_flaws it says I have a bad macro call on line 53 but you have to be very observant to notice that it's in a different file. 
If I press the line `MacroBrokenLinkError from domxref in line 53:188` it will open line 53 in a *different* file. 
What I would like to know **where in `content/files/en-us/web/html/element/input/number/index.html` it all started**. I.e. which macro triggers a flaw in a different file. 

The quickfix right now would be to be **"louder"** here in the UI to say that "This macro is in a different file". 

But it would still be neat to be able to use the 👀 in the "Show flaws" so you can scroll to where the flaw relates to the rendered DOM.

**Comment by escattone** [comment]
@peterbe Here are my initial thoughts. What you're describing, knowing which macro in the original document's raw HTML forced the rendering of other documents which then had errors, would be a nice thing to have. The problem is that it gets very complicated depending on how detailed we want to get. For instance, in the example you cited (http://localhost:3000/en-us/docs/web/html/element/input/number), there are 3 places in the raw HTML that call the `page` macro asking for various sections of http://localhost:3000/en-us/docs/web/html/element/input/text:
```
line 100 --> {{page("/en-US/docs/Web/HTML/Element/input/text", "list", 0, 1, 2)}}
line 114 --> {{page("/en-US/docs/Web/HTML/Element/input/text", "placeholder", 0, 1, 2)}}
line 116 --> {{page("/en-US/docs/Web/HTML/Element/input/text", "readonly", 0, 1, 2)}}
```
so it's impossible to point to a single line in the raw HTML of `/en-us/docs/web/html/element/input/number` that introduces the rendering of `/en-us/docs/web/html/element/input/text` and its associated `MacroBrokenLinkError`'s. Any one of those 3 lines, those `page` macro calls, would introduce the prerequisite. Also, since with the `page` macro we're typically extracting only sections of a prerequisite document, it's difficult to know if the extracted section actually includes any of the non-fatal errors (like `MacroBrokenLinkError`) that may have occurred while rendering that prerequisite.

Because of this complexity and all of the other work we have to do, I suspect it's not worth getting bogged down in these details to determine an elegant approach at the moment, and maybe for now we should go with some kind of quickfix?

**Comment by peterbe** [comment]
The --fix-flaws already takes the filepath into account which is nice. The only remaining thing is that we'll make it loud and clear if the filepath is different from the one you're viewing and we can call this done for now. ... once we've done the quick fix that is :)

**Comment by peterbe** [comment]
Ok. So we'll work with the `.fileinfo` in the UI. 
We also now have a chance to insert those 👀 clicks so you can highlight the `<a>` tag based on a macro flaw. I just can't remember if we have a separate and dedicated issue for that :)

**Comment by peterbe** [comment]
Pretty sure it's no longer a problem. We don't get crazy recursion any more and we have a solution to the "Show flaws" UI to alert when you're seeing a macro flaw coming from a prerequisite.
