### ISSUE TITLE
Sidebar is no longer hidden when printing MDN pages

### ISSUE THREAD

**Issue by DomOBU** [mdn/yari#7767]
### MDN URL

https://developer.mozilla.org/fr/docs/Learn/HTML/Introduction_to_HTML/Getting_started

### What information was incorrect, unhelpful, or incomplete?

Hello,

I used to print MDN pages and work on them.

Until now, only the central text was printed as on most sites (e.g. Wikipedia or the uBO wiki); not the left column.
Since a few days the left column is printed in addition to the central text which is very annoying. I suppose that there has been a modification of the site.
The problem is the same with Firefox and Edge.

Is it possible to go back to the previous situation where the left column was not printed?
Sincerely

### What did you expect to see?

That only the central text is printed not the left column

**Comment by caugner** [comment]
@DomOBU Thank you for reporting this issue. 👋 

Do you remember when this last worked as expected for you? A few days/weeks/months ago?

**Comment by DomOBU** [comment]
Hello Claas,

Thank you for your answer.

I have taken a break from MDN for a few weeks.
The last pages I have that were printed as expected were dated 2 November 2022.
I hope this will help.

Sincerely

**Comment by DomOBU** [comment]
It works as expected.
Thanks.
