### ISSUE TITLE
Add macro helper page.hasStatus()

### ISSUE THREAD

**Issue by hamishwillee** [mdn/yari#7799]
MDN docs are hoping to remove all tags front metadata - deleting what is not used, and replacing the "useful tags" with dedicated front matter keys. The idea is that the tags Experimental, Non-standard, Deprecated would be replaced by this front matter key and possible values. They would be all default "false" and optional.

```
status:
  - experimental
  - deprecated
  - non-standard
  ```

To do this we need accessors like `page.hasTag` and `env.tags` that can read the metadata. With those I could do the remainder of the work.

On removal of all tags, the hasTags would no longer be needed.

The MDN project is here: https://github.com/mdn/mdn/issues/262

**Comment by hamishwillee** [comment]
I might be able to do this by copying Will's approach https://github.com/mdn/yari/pull/7223/files#diff-f44886b0a1451a3b86209511fce6abb3d1f761d75a672295715268e606a74616

**Comment by caugner** [comment]
I would expect the `status` from the frontmatter to already be available via `env.status`, but introducing a helper function `page.hasStatus` should not be a problem:

https://github.com/mdn/yari/blob/13a2ed097562581273dec123f00e4ba156f823fc/kumascript/src/api/page.ts#L4-L31

**Comment by hamishwillee** [comment]
Thanks so much @caugner !!!
