### ISSUE TITLE
Browser Text Search always searches sidebar first

### ISSUE THREAD

**Issue by schockocraft** [mdn/yari#7882]
### Summary

When using ctrl+f to search the site for what i am looking for it always gives me the search results in the sidebar first which is pretty annoying. 

Now while testing i actually found out, that when i click on the content area first, it will show me the first search result in the content part, but i think it is still worth a change to make this the default behaviour, because when woul you ever want to search the - admittedly often way too long and convoluted - sidebar?

I see two possible fixes for this problem:
1. move the sidebar below the content in the DOM
2. set focus to the content area on page load 

The first one is probably too much work though for such a small usability gain, but for the second idea i don't know if that could interfere with any screenreader functionality and that kinda stuff.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units

### Reproduction steps

1. load any page
2. do not click anywhere
3. press ctrl+f
4. enter a keyword that's both in sidebar and content areas

### Expected behavior

the content scrolls to the first occurence of the keyword in the content area

### Actual behavior

the sidebar scrolls to the first occurence of the keyword in the sidebaar area

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot
all results up to this one are in the sidebar, only the next one is finally in the content area
![image](https://user-images.githubusercontent.com/44204747/209844730-abf7e9dd-ddc3-4835-9401-a2f0a631336d.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by fiji-flo** [comment]
Thanks for the input. This behavior is intended, the sidebar comes first in the DOM and we don't want to change this unless there's a clear signal from our users. If you want to stray with keys only you can press [TAB] -> [ENTER] -> [CTRL+F].
