### ISSUE TITLE
Updating the Android WebView icon?

### ISSUE THREAD

**Issue by mahozad** [mdn/yari#7914]
Do you think it would be better to use the Android new (updated) logo as the icon for Android WebView instead of the (I think) Android outdated mascot?

  - [Android brand guidelines](https://developer.android.com/distribute/marketing-tools/brand-guidelines)
  - [Another link for Android brand guidelines](https://source.android.com/docs/setup/about/brands)

I can create a pull request if you'd like:

| Before | After |
| ------- | ------ |
| ![3](https://user-images.githubusercontent.com/29678011/210731675-54e372d9-241e-4fd8-90e4-c39d77c8d5c2.svg) | ![4](https://user-images.githubusercontent.com/29678011/210731842-c93e06e5-e837-43fb-8021-fa54add079c6.svg) |
| ![1](https://user-images.githubusercontent.com/29678011/210730999-7a715b96-0cef-4c7b-98ea-64f915fb28cb.png) | ![2](https://user-images.githubusercontent.com/29678011/210731026-bff7cfa0-ad84-4687-8e6d-a9120b4fca90.png) |

**Comment by mahozad** [comment]
@Guyzeroth @bsmth @mirunacurtean 
I think the pull request is ready.

**Comment by bsmth** [comment]
Hi @mahozad - thanks a lot for raising the issue and proposing a fix. I would tag @caugner on this one for a pair of eyes 👀

**Comment by mahozad** [comment]
Thanks.
