### ISSUE TITLE
STIX Two Math not used for MathML content

### ISSUE THREAD

**Issue by fred-wang** [mdn/yari#7967]
### Summary

See https://mobile.twitter.com/KenHatesSoftwar/status/1613779950909403138

(@caugner @mrego  @dginev @bkardell)

### URL

https://developer.mozilla.org/en-US/docs/Web/MathML/Examples/Deriving_the_Quadratic_Formula

### Reproduction steps

1. Go to the page
2. Inspect one MathML element
3. In Firefox/Linux with STIX Two Math and Latin Modern Math installed, I'm seeing:

- The style "Inherited from math" is
  `math { font-family: STIXTwoMath-Regular; } from mathml-font.scss:9`

- In the "Fonts" tab:
  Fonts Used are `Liberation Serif` and/or `Latin Modern Math`.

- In the style editor, `mathml-font.scss` is properly inserted. If I copy its
  content into a new stylesheet, and add the missing comma in the `src` my
  local `STIX Two Math` font is properly used.

4. If I uninstall STIX Two Math and try again, I'm getting
  `GET https://developer.mozilla.org/en-US/docs/Web/MathML/Examples/font/STIXTwoMath-Regular.woff2 HTTP/2 404 Not Found`
  `downloadable font: download failed (font-family: "STIXTwoMath-Regular" style:normal weight:400 stretch:100 src index:1): status=2147746065 source: https://developer.mozilla.org/en-US/docs/Web/MathML/Examples/font/STIXTwoMath-Regular.woff2`

### Expected behavior

Either the local or woff2 font should be used.

### Actual behavior

STIX Two Math is not used.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Anything else?

This was supposed to be implemented by https://github.com/mdn/yari/pull/7620 but it does not seem to work (and I guess it was difficult to test on macOS where STIX Two is pre-installed).

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by fred-wang** [comment]
The URL of the web font is https://developer.mozilla.org/static/media/STIXTwoMath-Regular.a6dd783b1df04c61b10a.woff2

I tried adding the missing comma in a local copy of yari and the web font properly loads after that change, so maybe that's the only issue.

**Comment by caugner** [comment]
Resolved via https://github.com/mdn/yari/pull/7968.
