### ISSUE TITLE
yari, dev server error when cloned into file hierarchies containing spaces

### ISSUE THREAD

**Issue by ninevra** [mdn/yari#7986]
### Summary

If `yari` (or `mdn/content`) is cloned into a folder which contains whitespace anywhere in its path, `yarn dev` etc produce "Error: Folder contains whitespace which is not allowed" for every page."

This feature was intended to prevent whitespace from appearing in the names of content folders (see #758, #2171), but also poses a(n admittedly very minor) barrier to contributing to the docs.

### URL

n/a

### Reproduction steps

1. `mkdir "Contains Space"`
2. `cd "Contains Space"`
3. `git clone https://github.com/mdn/yari.git`
4. `yarn install`
5. `yarn dev`
6. navigate to any page in the dev server.

### Expected behavior

Page should render.

### Actual behavior

An error message is displayed.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Maybe we could check against `folder` instead of `filePath` here:

https://github.com/mdn/yari/blob/5ed7cc2877fc373239138a524e520497e7c72e13/content/document.ts#L245-L251

**Comment by caugner** [comment]
Oh, I hadn't seen the PR: https://github.com/mdn/yari/pull/7987 🎉
