### ISSUE TITLE
Dark Theme font colour is not readable in Try It CSS Demo: grid-template-areas

### ISSUE THREAD

**Issue by devonhughes** [mdn/yari#8008]
### Summary

The text in the example choice boxes to the left does not change to a light colour when dark mode is enabled, rendering it unreadable. 

### URL

[https://interactive-examples.mdn.mozilla.net/pages/css/grid-template-areas.html](url)

### Reproduction steps

1.The Try It feature that displays this problem was found here: [https://developer.mozilla.org/en-US/docs/Web/CSS/grid-template-areas](url) and exhibits the same behaviour on Firefox and Chrome.

### Expected behavior

A lighter, readable font colour should be implemented when dark mode is enabled. 

### Actual behavior

The text is not changed from the default light mode colour. 

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Screenshot

![css-font-colour](https://user-images.githubusercontent.com/14238044/213846256-653d1eba-279a-46d5-b820-ad85235f7186.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by NiedziolkaMichal** [comment]
This has been already fixed by [#888](https://github.com/mdn/bob/pull/888), but it's waiting to be deployed.

**Comment by mirunacurtean** [comment]
Closing this as it appears to be fixed. 
![image](https://user-images.githubusercontent.com/53306802/228477744-7388ec9a-8c10-4ba0-833c-de1e62c94222.png)
![image](https://user-images.githubusercontent.com/53306802/228478336-371caf28-42cc-4c36-ae6a-57dd2b557487.png)
