### ISSUE TITLE
The "Try It" result block isn't displaying in Firefox (works in Chrome)

### ISSUE THREAD

**Issue by blindspeed90** [mdn/yari#8042]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior

### What specific section or headline is this issue about?

Try It

### What information was incorrect, unhelpful, or incomplete?

The result block below the block you pick the "overflow-behavior" isn't displayed in Firefox.

### What did you expect to see?

The result block.

### Do you have anything more you want to share?

It looks like an exception is being thrown from React.

### MDN metadata

<details>
<summary>Page report details</summary>

* Folder: `en-us/web/css/overscroll-behavior`
* MDN URL: https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior
* GitHub URL: https://github.com/mdn/content/blob/main/files/en-us/web/css/overscroll-behavior/index.md
* Last commit: https://github.com/mdn/content/commit/44439c7254c9da1797e4438bade0f8e8984cbc35
* Document last modified: 2022-09-27T22:38:41.000Z

</details>

**Comment by tlylt** [comment]
Sharing my console output here:
![image](https://user-images.githubusercontent.com/41845017/214463880-ab551cae-f3c3-419e-b42d-e698c10508ab.png)
> Uncaught Error: Minified React error #425; visit https://reactjs.org/docs/error-decoder.html?invariant=425 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Qr (react-dom.production.min.js:118:466)
    at $s (react-dom.production.min.js:227:369)
    at xc (react-dom.production.min.js:281:85)
    at yc (react-dom.production.min.js:280:450)
    at gc (react-dom.production.min.js:280:320)
    at vc (react-dom.production.min.js:280:180)
    at ac (react-dom.production.min.js:268:209)
    at _ (scheduler.production.min.js:13:203)
    at MessagePort.N (scheduler.production.min.js:14:128)
react-dom.production.min.js:131 Uncaught Error: Minified React error #418; visit https://reactjs.org/docs/error-decoder.html?invariant=418 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at ci (react-dom.production.min.js:131:278)
    at Su (react-dom.production.min.js:293:379)
    at yc (react-dom.production.min.js:280:389)
    at gc (react-dom.production.min.js:280:320)
    at vc (react-dom.production.min.js:280:180)
    at ac (react-dom.production.min.js:268:209)
    at _ (scheduler.production.min.js:13:203)
    at MessagePort.N (scheduler.production.min.js:14:128)
react-dom.production.min.js:293 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at Su (react-dom.production.min.js:293:39)
    at yc (react-dom.production.min.js:280:389)
    at gc (react-dom.production.min.js:280:320)
    at vc (react-dom.production.min.js:280:180)
    at ic (react-dom.production.min.js:271:88)
    at ac (react-dom.production.min.js:268:429)
    at _ (scheduler.production.min.js:13:203)
    at MessagePort.N (scheduler.production.min.js:14:128)

**Comment by blindspeed90** [comment]
Took me a while to reproduce it, but first I had to shrink the window which caused the result block to appear under, then I saw this:

![Untitled](https://user-images.githubusercontent.com/26564540/214478877-e61ad15b-2bec-4551-8772-b602f0b20d3a.png)

**Comment by tlylt** [comment]
Hi @blindspeed90, while I get the error in the console, I actually don't understand what you mean by
> The result block below the block you pick the "overflow-behavior" isn't displayed in Firefox.

In your screenshot above, if you scroll down vertically, won't you see the result block?
Like so:
> ![image](https://user-images.githubusercontent.com/41845017/214544995-f8769592-01e3-45e3-9e3d-b026de87e4e8.png)
![image](https://user-images.githubusercontent.com/41845017/214545032-9b465f7c-77ac-4843-a5f3-84d0a37a2ff5.png)
![image](https://user-images.githubusercontent.com/41845017/214545087-18a7f148-32ba-4121-b38c-b644efa13a76.png)

The other thing that I observe is that sometimes when reducing the width of the page, the result block gets rendered outside:
> ![image](https://user-images.githubusercontent.com/41845017/214544959-d5db2a78-11ae-4377-8dfc-9414ba70a0ea.png)

So despite the errors in the console, it seems like the page is still readable.

**Comment by NiedziolkaMichal** [comment]
I also have a hydration error on this page, on Firefox & chrome:
![image](https://user-images.githubusercontent.com/100634371/214963447-93178084-4dcc-47c2-9a10-108db4a3a8fd.png)

**Comment by LeoMcA** [comment]
Can't repro result block being hidden, nor the React errors on the page.

**Comment by NiedziolkaMichal** [comment]
@LeoMcA I get this error on Firefox 110, Edge 110, Chrome 110. @tlylt reported it too, so I am not the only one.

**Comment by LeoMcA** [comment]
@NiedziolkaMichal The React error? Since it's unrelated to the "try it" problem in this issue, could you open a new issue please, and give as much detail as possible so I can attempt to reproduce it: URLs, browsers/versions (as you already have), OS, installed extensions (or lack thereof), whether you're logged in or not, etc. Thanks!

**Comment by NiedziolkaMichal** [comment]
@LeoMcA Sure
