### ISSUE TITLE
_wikihistory.json is not being updated in the translated-content repo.

### ISSUE THREAD

**Issue by hochan222** [mdn/yari#8043]
### Summary

It seems that all pages are not fully updated in local pages. In the case of globalThis, the date at the bottom of the page has been updated, but it is not updated on the "MDN contributors" page.

maybe related: https://github.com/mdn/mdn-community/discussions/181

### URL

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/globalThis

### Reproduction steps

1. Go to a specific(globalThis) MDN page.
2. Compare the "This page was last modified" and "MDN contributors" page at the bottom and the _wikihistory.json file.

### Expected behavior

- The modified date of the MDN page should be the same as the modified date of the _wikihistory.json file. 
- The IDs of the contributors who committed the file should be displayed in "MDN contributors" page.

### Actual behavior

The MDN page itself is being updated, but neither the _wikihistory.json file nor the "MDN contributors" page is being updated.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### MDN page

![image](https://user-images.githubusercontent.com/22424891/214507831-42bfdc08-544a-4e14-9e2d-3bfc1301d06e.png)

### "MDN contributors" page

![image](https://user-images.githubusercontent.com/22424891/214507986-05335473-411b-4cda-8c43-dd8599a12871.png)

### _wikihistory.json

![image](https://user-images.githubusercontent.com/22424891/214508096-1ac4d183-f8c0-4ae7-a19e-adbe7ea3bd57.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by yin1999** [comment]
I think the `modified` property indicates the last modified time on [old kuma](https://wiki.mozilla.org/MDN/Archives/Kuma) (not really sure), and this will not be updated when the corresponding document is modified.

And the last modified time in `https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/globalThis` would be related to the git logs (history).

**Comment by caugner** [comment]
Sorry for taking the long to triage this. 🙏 

As @yin1999 correctly explained, the `_wikihistory.json` only contains contributions from when the MDN content was managed as a wiki via [kuma](https://github.com/mdn/kuma/), so the `contributors.txt` only lists the original wiki contributors, while referring to the git history for GitHub contributions.

Note that the same applies to the [_wikihistory.json](https://github.com/mdn/content/blob/main/files/en-us/_wikihistory.json) in content.

So I will go ahead and close this as "won't fix".
