### ISSUE TITLE
Consider changes to the content/files/en-us/mdn/contribute tree given the new world of Yari

### ISSUE THREAD

**Issue by escattone** [mdn/yari#805]
We should consider if all or portions of the [`/en-us/mdn/contribute`](https://developer.mozilla.org/en-US/docs/MDN/Contribute) document tree need to be re-written. archived, or simply deleted given the new world of Yari.

For example, much of [`/en-US/docs/MDN/Contribute/Editor`](https://developer.mozilla.org/en-US/docs/MDN/Contribute/Editor) will have to either change or simply be removed.

**Comment by peterbe** [comment]
It's a couple of months old now but according to https://peterbe.github.io/mdn-sitetree/ `en-us/mdn/contribute` is about 1.3% of the content. Or, 128 pages. 

Mayhaps we keep them but boldly rewrite them all.

**Comment by peterbe** [comment]
If the contribution guide is going to be [a Google doc](https://github.com/mdn/yari/issues/1113) can we just link to the Google doc in these (128) pages?

**Comment by escattone** [comment]
@chrisdavidmills has already addressed this.
