### ISSUE TITLE
Remove "Related Topics" as sidebar heading

### ISSUE THREAD

**Issue by Elchi3** [mdn/yari#8050]
### Summary

Sidebars have the headline "Related Topics". As discussed in the London work week, we should remove it as it seems unnecessary.

### URL

Any reference page with a sidebar. For example, https://developer.mozilla.org/en-US/docs/Web/API/Performance_API

### Reproduction steps

1. Go to a reference page
2. See "Related Topics" at the top of the sidebar

### Expected behavior

No "Related Topics" heading.

### Actual behavior

"Related topics" heading that doesn't seem to have any value. The sidebar content is often an organized list of members of an interface or the like. 

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Anything else?

Meeting minutes from the discussion: https://github.com/openwebdocs/project/blob/main/steering-committee/meetups/london-2023/session-content.md

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Resolved via https://github.com/mdn/yari/pull/8126.
