### ISSUE TITLE
Define metrics instrumenting how users are using the sidebar

### ISSUE THREAD

**Issue by Elchi3** [mdn/yari#8053]
### Summary

As discussed in our London work week, we want to understand how MDN users are using the sidebar in order to improve it. In order to do that we should define metrics for sidebar instrumentation.

### URL

MDN pages with sidebars.

### Reproduction steps

None. New metrics needed.

### Expected behavior

Metrics that show how users interact with the links in the sidebar.

### Actual behavior

No metrics :(

### Device

Desktop

### Browser

Safari

### Browser version

Stable

### Operating system

Mac OS

### Anything else?

Meeting minutes where this was discussed: https://github.com/openwebdocs/project/blob/main/steering-committee/meetups/london-2023/session-content.md

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Resolved in February 2023 via https://github.com/mdn/yari/pull/8293.
