### ISSUE TITLE
Search box is still not keyboard friendly

### ISSUE THREAD

**Issue by ThreeSevenths** [mdn/yari#8054]
## Summary

You cannot use the `Home` and `End` keys to move to the beginning and end of the search text field on Windows. This includes the header search box and the search box on the homepage.

## URL

https://developer.mozilla.org/en-US/

## Expected Behaviour

You should be able to enter a search term, then use `Home` to navigate to the beginning of the text, and `End` to move to the end. 

## Device

Desktop

## Browser

Chrome, Edge

## Browser Version

109

## Operating System

Windows

**Comment by danielhjacobs** [comment]
Duplicate of https://github.com/mdn/yari/issues/6466. You can use `Ctrl+LeftArrow` and `Ctrl+RightArrow` to go to the start / end of the input value.
