### ISSUE TITLE
BCD table is not available in PR test for mdn/content and mdn/translated-content

### ISSUE THREAD

**Issue by yin1999** [mdn/yari#8056]
### Summary

The recent changes have made BCD table not available in PR test for mdn/content and mdn/translated-content

See:

- https://pr11247.content.dev.mdn.mozit.cloud/zh-CN/docs/Web/HTML/Attributes/crossorigin (translated-content)
- https://pr23899.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/MediaDevices/getUserMedia (content)

### URL

- https://pr11247.content.dev.mdn.mozit.cloud/zh-CN/docs/Web/HTML/Attributes/crossorigin (translated-content)
- https://pr23899.content.dev.mdn.mozit.cloud/en-US/docs/Web/API/MediaDevices/getUserMedia (content)

### Reproduction steps

Open the URLs, and move to BCD section

### Expected behavior

We could see the BCD table in PR test (this is still work on Prod build)

### Actual behavior

The BCD table is not available.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Linux

### Screenshot

![image](https://user-images.githubusercontent.com/15844309/214768799-2e4e08ba-0f9f-433e-b532-b32c80cdf41b.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by yin1999** [comment]
Maybe relate to #7957

**Comment by LeoMcA** [comment]
@yin1999 thanks for reporting, this should now be fixed!
