### ISSUE TITLE
T - BUG? localeHistory can be undefined

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#807]
Haven't understood it enough yet to check whether this might just be some random Windows folder, but `yarn start` failed for me, unless I added this check:

```diff
Index: content/scripts/document.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- content/scripts/document.js	(revision c15d6696a11ffafe9a82ba2d6d8bbf48ae9d6878)
+++ content/scripts/document.js	(date 1593167905976)
@@ -117,7 +117,7 @@
     }
     const localeHistory = allWikiHistory.get(metadata.locale.toLowerCase());
     const slugLC = metadata.slug.toLowerCase();
-    if (localeHistory.has(slugLC)) {
+    if (localeHistory && localeHistory.has(slugLC)) {
       metadata.modified = localeHistory.get(slugLC).modified;
     }
   }

```

**Comment by peterbe** [comment]
If `ensureAllWikiHistory` wasn't run, you'd get this error. But the line above your suggested diff implies there's at least something in that `Map` instance. 
Can you do some console.log of `allWikiHistory` to find out what keys are in the map? 
And, can `metadata.locale.toLowerCase()` become an empty string by chance?

**Comment by Gregoor** [comment]
ah oh, my content folder was full of non english content from an older import which I forgot about (and which naturally didn't have the new wiki history). Don't mind me 🙊
