### ISSUE TITLE
chore: run "Help prioritise cross-browser web platform features" survey

### ISSUE THREAD

**Issue by schalkneethling** [mdn/yari#8087]
The Firefox team wants to run a short survey to determine what the most important web compat issue is to work on.

> Ensuring the web is open and accessible to all is central to Mozilla’s mission. The Firefox product team is interested in learning which features are most important to support across all major browsers.

Sampling rate: 5% of JavaScript pages
Run for 7 days

**Comment by schalkneethling** [comment]
@caugner, when I add this one, should I go ahead and cleanup the interop survey that is currently still present? Thanks

**Comment by caugner** [comment]
> @caugner, when I add this one, should I go ahead and cleanup the interop survey that is currently still present? Thanks

@schalkneethling Yes, you can remove the interop survey at the same time, except maybe for its enum value.

**Comment by schalkneethling** [comment]
> > @caugner, when I add this one, should I go ahead and cleanup the interop survey that is currently still present? Thanks
> 
> @schalkneethling Yes, you can remove the interop survey at the same time, except maybe for its enum value.

Cleaned up.
