### ISSUE TITLE
T - Search redirects break after create document

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#809]
Steps to reproduce:

1. Open up http://localhost:3000
2. Find a document: e.g. http://localhost:3000/en-US/docs/Web/HTML/Element/audio
3. Create a document with slug: Web/HTML/Element/audiox
4. Save document
5. Search may work once or twice, search for audiox (which i found)
6. Soonafter - auto-complete displays results BUT, the page does not redirect

Reproducible on osx: chrome & ff

NOTE: this bug persists even after restarting the app and I was able to make it go away by doing a fresh install, but it reappears after you do a save and then persists

**Comment by tobinmori** [comment]
Later discovery:

This feature works if you use the arrows/return key to select a doc.

Breaks if you select a doc, using your cursor.

**Comment by Gregoor** [comment]
Btw this is breaking for me without creating a document, so I'm currently assuming this is an issue somewhere in the UI interactivity, not in the search index.

**Comment by tobinmori** [comment]
Thanks @Gregoor I won't try out this branch then. :)

**Comment by Gregoor** [comment]
Oh no that's not what I was trying to say. I still assume that my branch fixes it, but the reproduction being so flaky, I'm not 100% sure yet. I just can reproduce it without creating a new document which makes for a simpler (yet still flaky) repro.
