### ISSUE TITLE
"Learn more" button from MDN Plus page open empty page

### ISSUE THREAD

**Issue by loremipsum-20** [mdn/yari#8106]
### Summary

When I navigate from MDN Homepage to MDN Plus, scroll down to Notifications, Collections, or Offline and click on "Learn more -->" the next page is empty and only after reloading the page I can see the content

### URL

https://developer.mozilla.org/en-US/plus/docs/features/notifications
https://developer.mozilla.org/en-US/plus/docs/features/collections
https://developer.mozilla.org/en-US/plus/docs/features/offline

### Reproduction steps

1. start here: https://developer.mozilla.org/en-US/
2. click on MDN Plus 
3. scroll down to section Notifications, Collections, or Offline and click on "Learn more -->" 
4. refresh the page

### Expected behavior

I expect to see the content of the page

### Actual behavior

I see a blank page

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

https://user-images.githubusercontent.com/74014542/216028130-cade6fee-1f81-4844-afb1-af6d6d264361.mov

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Thank you, Janine, I was able to reproduce the issue.

Here's the error message I'm seeing in the browser console:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/495429/216067870-dd4039c3-8520-4f46-8680-65daf3616029.png">

And it looks like an error with hydration:

https://github.com/mdn/yari/blob/f823b54dcd757a8860f95dc398e6f4b42256ce82/client/src/homepage/static-page/index.tsx#L82-L89

**Comment by caugner** [comment]
The SSR hydration data does contain the sections, which explains why reloading works fine:
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/495429/216068941-d7c1a613-5930-4d7b-acd4-6a69d3accef0.png">

**Comment by LeoMcA** [comment]
I imagine this issue has the same underlying cause: https://github.com/mdn/yari/issues/8107
