### ISSUE TITLE
Impossible to commit on windows

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/yari#8119]
### Summary

It looks like currently, it's not possible to commit anything to YARI on windows, without performing manual modifications to project files.

Script `check:tsc` contains commands that are required to be used in the shell. Those commands can be executed on Git Bash, in which everything works fine. Yarn uses the default OS shell to execute scripts, so in order for it to work, the following command needs to be used first: `npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"`.
However in my case, the command `yarn lint-staged` which runs script `node_modules/.bin/lint-staged` stops working correctly. It tries to run the following path, omitting path separators: `C:repoopen-sourcemdnyarinode_modules.binlint-staged`.

I think it's a problem with yarn. MDN repositories use yarn 1 which is not maintained for years. When I upgrade to yarn 3(which requires modifications to files), everything works fine. Also replacing `yarn lint-staged` with `npx lint-staged` in `pre-commit` works fine.

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Resolved via https://github.com/mdn/yari/pull/8118: We no longer run `check:tsc` via lint-staged. 😌

**Comment by NiedziolkaMichal** [comment]
@caugner Alright. Thanks a lot
