### ISSUE TITLE
The font color of the search bar on the MDN home page is not set correctly

### ISSUE THREAD

**Issue by yarusome** [mdn/yari#8176]
### Summary

The font color of the search bar in the center of the MDN home page uses the initial value of `color`, which makes the input characters almost invisible against the background.

### URL

https://developer.mozilla.org/en-US/

### Reproduction steps

1. Go to the home page.
2. Input a few characters in the search bar.

### Expected behavior

The input characters can be clearly seen.

### Actual behavior

The input characters are almost invisible.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Screenshot

![Screenshot](https://user-images.githubusercontent.com/97945148/217689863-381784b4-16af-47ef-a67e-61b1bb8683c4.png)

### Anything else?

The `<input>` element does have inherited `--text-primary` from the `.dark` class, but this custom property is not applied to the element.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
I cannot reproduce the issue, are you using an extension like DarkReader by any chance?

**Comment by yarusome** [comment]
@caugner I made sure to disable all the extensions before taking the screenshot. In the DevTool, the relevant CSS rules are:
````
.homepage-hero .homepage-hero-search .search-input-field {
  background-color:rgba(1,1,1,.5);
  border-radius:10rem;
  padding:2rem;
  width:100%
}
button, input, select, textarea {
  font:inherit
}
.dark {
  --text-primary:#fff;
  /* Some other custom properties */
}
````
This problem is reproduced on Firefox 75.0 and Android System WebView 62.0, and the problem starts to show a few weeks ago.

**Comment by caugner** [comment]
We don't actively support retired browser versions like Firefox 75.0 (from 2020) and WebView 62.0 (from 2017).

Can you reproduce the issue on the latest Firefox/WebView versions?

**Comment by yarusome** [comment]
I'll try to test once I'm able to get another device. The interesting thing is that on Firefox 75.0, the computed style for this `input` element is:
![computed](https://user-images.githubusercontent.com/97945148/218364278-51fdf73d-fd3e-4636-9100-e9b3e12ceea6.png)
So its parent element does correctly inherit the `color` value.

Closing this issue since it's about outdated browsers.
