### ISSUE TITLE
"svelte" Prism language is not loading with `loadLanguages()`

### ISSUE THREAD

**Issue by queengooborg** [mdn/yari#8187]
The `loadLanguages()` command is not loading the `svelte` language with the Prism plugin.  It's possible that the language is already being loaded ahead of time and we don't need to load the language ourselves.

**Comment by caugner** [comment]
[This example](https://github.com/pngwn/prism-svelte#usage) suggests importing `prism-svelte` would be enough, [as it adds itself to `Prism.languages`](https://github.com/pngwn/prism-svelte/blob/51cacf0ef0189ca6e575dc27c9124676711bd57d/index.js#L3), and that is more or less exactly what the [`loadLanguages()`](https://github.com/PrismJS/prism/blob/59e5a3471377057de1f401ba38337aca27b80e03/components/index.js#L45) function does (e.g. [prism-rust](https://github.com/PrismJS/prism/blob/59e5a3471377057de1f401ba38337aca27b80e03/components/prism-rust.js#L11)).

**Comment by caugner** [comment]
1. Remove the following line:
  https://github.com/mdn/yari/blob/e547ca35cc8535d7020b1f2883e67e622a2ca665/build/syntax-highlight.ts#L47
2. Test that `svelte` code blocks are still rendered correctly.

**Comment by caugner** [comment]
Looking at https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Svelte_stores#creating_the_actual_component, it seems that Svelte syntax highlighting is working fine on MDN.
