### ISSUE TITLE
[object promise] text is generated in the sidebar across Standard built-in objects pages

### ISSUE THREAD

**Issue by mirunacurtean** [mdn/yari#8191]
### Summary

Global Object pages show a [object promise] text under the sidebar list headings. 

### URL

https://developer.mozilla.org/en-US/docs/web/javascript/reference/global_objects/array/filter
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AggregateError

### Reproduction steps

1. Go to link.
2. Look at the sidebar.
3.Notice the additional text.

### Expected behavior

Only headings and page links should be listed in the sidebar.

### Actual behavior

Text that is not a heading or a link is displayed. 

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Android

### Screenshot

![image](https://user-images.githubusercontent.com/53306802/218083072-4bc3be31-64f8-47b4-a4e1-7d742fe761d2.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by yin1999** [comment]
Could be fixed by: #8134

**Comment by wbamberg** [comment]
Ugh, @yin1999 , since that PR is in draft, and it is a large PR that does a lot of other things, do you think you could split out the fix for this particular issue into a separate PR?

**Comment by yin1999** [comment]
> Ugh, @yin1999 , since that PR is in draft, and it is a large PR that does a lot of other things, do you think you could split out the fix for this particular issue into a separate PR?

Oh yes. I'm waiting for resolving mdn/translated-content#11430 as I've removed webassemly in #8134.

Split the fix into #8197
