### ISSUE TITLE
U - Yari Architecture documentation

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#824]
## Acceptance Criteria

- [ ] A high-resolution document, detailing the different architectures, toolchains, running processes, working modes (local versus building for production), various watching/caching layers and the user/writer needs they serve completed

**Comment by peterbe** [comment]
Another option is to write it from the perspective of an edit or a new doc. It might be worth doing that approach too. Or, as an alternative. 
I.e. Like [those "How it's done" videos](https://www.youtube.com/watch?v=QstxI4NJl_E) but not a video. And a little deep-linked details about various components as the edit goes through.

**Comment by tobinmori** [comment]
Updated AC: Write ADR for reductio.
