### ISSUE TITLE
Hydration error on `overscroll-behavior` page

### ISSUE THREAD

**Issue by NiedziolkaMichal** [mdn/yari#8272]
### Summary

I get a hydration error on [overscroll-behavior](https://developer.mozilla.org/en-US/docs/Web/CSS/overscroll-behavior).

![image](https://user-images.githubusercontent.com/100634371/220174808-df7af0ba-4c79-4471-913f-4b9326c788a0.png)

- This issue doesn't occur on other `overscroll-behavior-*` pages.
- Error happens every time.
- I get it on desktop Firefox 110, Edge 110, Chrome 110, while not being logged in, with or without browser extensions.
- I use Windows 11 x64.
- I don't get the error while running YARI in dev mode.

Related to #8042

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by OnkarRuikar** [comment]
I am not able to reproduce it on Fedora 37, Firefox 110.0 (64bit). This may be related to advertisements, cos ads are not shown for my region yet.
![bug](https://user-images.githubusercontent.com/87750369/222611849-daaf4c2c-e870-448f-822d-1fe61d19da36.png)
