### ISSUE TITLE
Rename Markdown links when an internal page is moved using `yarn content move`

### ISSUE THREAD

**Issue by teoli2003** [mdn/yari#8292]
### The problem
Moving pages with `yarn content move` adds an entry in the _redirect_ files. There is some magic ongoing in Yari to transform this redirect into the correct link when building a page.

**_Nevertheless_**, Markdown links inside MDN stay the same. This leads to a few problems:

- Writers manually edit these links, while this could be automated
- it is challenging to navigate to the right page in GitHub or in our code editors as the link no longer exists. Usually, we need to open MDN and paste the link to discover the natural slug. That's cumbersome.
- A flaw is generated when the build process discovers such redirection. This clutters the flaw dashboard and induce manual actions.
- Reuse of `mdn/content` is made next to impossible as links are broken (this is not the only offender, but a major one)

### Potential solution:

When doing `yarn content move` (and not `yarn content delete`), make an extra pass and edit all Markdown links in `mdn/content` linking to this slug to the new one (preserving the fragment, if any).

This will not solve links created by macros, but we are mostly moving around non-reference pages nowadays, and macros deal with these kinds of links so that it would cover 90% of the cases.

**Comment by caugner** [comment]
This was meanwhile implemented in the content repo: https://github.com/mdn/content/pull/31091
