### ISSUE TITLE
ListSubPages macro doesn't pick up changes

### ISSUE THREAD

**Issue by escattone** [mdn/yari#832]
`ListSubPages` macro doesn't pick up changes (e.g., when @Elchi3 added the new “Firefox 79” page).

Steps to reproduce:

1. Go to http://localhost:3000/en-US/docs/Mozilla/Firefox/Releases/78 (or whatever is latest)
2. Use the Toolbar to create the `79` page. 
3. Visit http://localhost:3000/en-US/docs/Mozilla/Firefox/Releases/

**Comment by Elchi3** [comment]
In kuma, macros also don't pick up changes automatically, but when logged in, I can do a force-refresh to trigger a re-rendering. I don't know what the re-rendering strategy looks like in yari. Re-render everything nightly? Compat data would benefit from that, too, as it currently only gets re-rendering once a month, which is problematic.
