### ISSUE TITLE
Missing space in the text in BCD table

### ISSUE THREAD

**Issue by dipikabh** [mdn/yari#8328]
### Summary

This text appears in the cells with a flag:

(example page: https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility#browser_compatibility)

> From version 109: this feature is behind thelayout.css.content-visibility.enabled preferences (needs to be set to true). To change preferences in Firefox, visit about:config.

- The text is missing a space between "the" and the preference name
- "preferences" should be singular when only one flag needs to be enabled

### URL

Another example: https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline-name#browser_compatibility

### Reproduction steps

1. Navigate to any BCD table where a feature is supported behind a preference
2. Click the flag in the cell to display the text

### Expected behavior

Text of the form:

"From version 109: this feature is behind the `layout.css.content-visibility.enabled` preference (needs to be set to `true`). To change preferences in Firefox, visit about:config."

### Actual behavior

The text appears with a missing space before the preference name and mentions it as "preferences" even though there is only one preference to be enabled.

### Device

Laptop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

This is from https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-timeline-name#browser_compatibility:

<kbd>![Screen Shot 2023-02-28 at 6 47 17 PM](https://user-images.githubusercontent.com/23019147/222010075-c6250292-787d-4fb5-8b11-e008e547b63e.png)</kbd>

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Probably this should fix it:

```diff
diff --git a/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx b/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
index 3058a0f6e..93d477057 100644
--- a/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
+++ b/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx
@@ -299,7 +299,7 @@ function FlagsNote({
         const valueToSet = flag.value_to_set && (
           <>
             {" "}
-            (needs to be set to <code>{flag.value_to_set}</code>)
+            (needs to be set to{" "}<code>{flag.value_to_set}</code>)
           </>
         );
         return (
```

**Comment by caugner** [comment]
> `{" "}` would need to be added to after "the"

You're right.
