### ISSUE TITLE
"Create new document" should be positioned close to the Edit and Delete actions

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#834]
...in the Toolbar. 
Currently, the "Create new document" is all the way to the left. Whereas edit and delete is centered.

**Comment by peterbe** [comment]
CC @schalkneethling and @Gregoor 

Let's not make the toolbar too perfect until it's gotten a proper do-over with styling but just moving it might be a quick win and positioning of the button is probably done with the DOM, at first, rather that we SCSS.

**Comment by schalkneethling** [comment]
@Gregoor If you are ok with it, I am happy to make this tiny update as my first contribution 😄

**Comment by Gregoor** [comment]
@schalkneethling Delighted is what I am 🙂
