### ISSUE TITLE
Watcher is failing, by default, on Linux

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#835]
When @Elchi3 tested `yarn start` it crashes the `watcher` (with an unhandled error too!) because his system couldn't cope with that many open files. By default. 

He fixed his system by (blindly) following the tips here: https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details

Somehow we need to cope with this better for our Linux users.

**Comment by peterbe** [comment]
Ideas?

* Make it possible to configure/override which trees to watch (all of `content/files/` is default)
* We shouldn't have unhandled exceptions but the only good UI for displaying that the watcher isn't working is the `yarn start` terminal output. 
* The document spy should let the user know that the watcher isn't working and (hint)
* Perhaps wrap the `try/catch` in a way that it can post a link to https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers#the-technical-details

**Comment by peterbe** [comment]
Testing this is going to be hard since everyone on the core dev team is using macOS or Windows.

It might be possible to reproduce this with the Ubuntu you get in GitHub Actions which we'd hit if we do: https://github.com/mdn/yari/issues/641

**Comment by Gregoor** [comment]
I can (and will) run it in my WSL, which should behave like Ubuntu

**Comment by peterbe** [comment]
Perhaps we can mention the error by copying from this: https://github.com/mdn/yari/blob/1849eb7b0a866ab2fd71994b6eb313b1168a18ce/.github/workflows/developing.yml#L38-L44

**Comment by escattone** [comment]
We should add a note to the `mdn/content` repo's `README.md` for how Linux users can address this issue if they experience it.

**Comment by Ryuno-Ki** [comment]
Hit by this today.
Modifying a system config sounds like a bad idea. Even when [recommended by Chokidar](https://github.com/paulmillr/chokidar#install-troubleshooting).

Would defining a local config be an option?
https://unix.stackexchange.com/a/445011

There were [some reports against chokidar](https://github.com/paulmillr/chokidar/issues?q=is%3Aissue+enospc+is%3Aclosed).

**Comment by fiji-flo** [comment]
I suggest we support running the server without the watcher. Modifying system settings should be a last resort.

It would also be okay to just document this for now as it's a common issue. But I would prefer making it optional.

**Comment by peterbe** [comment]
Yes, it would be cool if you can switch off the watcher. It's actually not a critical feature to have. And the UI for the DocumentSpy should become aware that it's disabled so it can shout out: "Document Spy is disabled."

**Comment by peterbe** [comment]
But I think a lot of Linux people would be OK with increasing their default file descriptor limit if the Yari previewer is important to them. So I think we should at least do what Chokadir does in that we *mention* the error in a Troubleshooting section. 

Another option would be if we could do it within the Node code, like:

```diff
-const watcher = chokidar.watch(
-  // For now, brutally hardcode it to only the 'en-us' folders
-  // until we have a resolution on L10n.
-  [path.join(CONTENT_ROOT, "en-us", "**", "*.html")]
-);
+try {
+  const watcher = chokidar.watch(
+    // For now, brutally hardcode it to only the 'en-us' folders
+    // until we have a resolution on L10n.
+    [path.join(CONTENT_ROOT, "en-us", "**", "*.html")]
+  );
+} catch(err) {
+   if (err.message.includes("System limit for number of file watchers reached")) {
+    console.warn("Unable to start file watcher due to:", err.message);
+    console.log("See https://github.com/mdn/yari#troubleshooting-file-watcher");
+   }
+};
```
... or something, if that's possible.

**Comment by fiji-flo** [comment]
Catching that exception and exiting clean is tricky as it happens in a thread and must first be handled in the `watcher.on("error" …)`. Would have been nice. I agree.

**Comment by peterbe** [comment]
It's been a while since I looked at that, but what's wrong with adding a `watcher.on("error" …)`?
As long as we can "inject" a `console.log()` before it re-throws, I think we can make life easier for people.
