### ISSUE TITLE
Remove Markdown links in content when a page is deleted using command `yarn content delete`

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/yari#8372]
Related to:
- https://github.com/mdn/content/pull/25131#issuecomment-1459617323
- https://github.com/mdn/yari/issues/8292

## Problem

After using the deletion script links pointing the deleted document remain in content. And info around the links become invalid and go unaddressed. Over time content accumulates a lot of broken links and each link requires manual edit. It would be great if the deletion script automatically deletes the links or at least report them so that contributor will clean them.

## Solution

a. Automatically delete all `en-US/docs/${deletedDocPath}` from content. And log `10 documents were referring to the deleted doc. Check and update info around it before commit.`
b. Simply log doc paths and location referring the deleted doc.

With approach b. the contributor will have to manually search the documents and location to update which could be lengthy. With approach a. they simply will have to look at the diff and do additional edits around the deleted link which is more time saving.

**Comment by teoli2003** [comment]
I would prefer that it reports them. Deleting them, or making them inactive, will not fix the text around them.
