### ISSUE TITLE
BCD not rendered for `html.global_attributes.virtualkeyboardpolicy`

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/yari#8390]
### Summary

Yari is not finding BCD data for  `html.global_attributes.virtualkeyboardpolicy` query.
It is [being reported as flaw](https://github.com/mdn/content/pull/25242#issuecomment-1464736168).
But there is BCD available: https://github.com/mdn/browser-compat-data/blob/bb3f3341e45ac3d5975bf52af630b167eec05b9e/html/global_attributes.json#L1499

### URL

https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/virtualkeyboardpolicy

Archived version on March 11, 2023:
https://web.archive.org/web/20230310001824/https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/virtualkeyboardpolicy#browser_compatibility

### Expected behavior

Page to render BCD table.

### Actual behavior

Yari throws error 
> No BCD data for query: html.global_attributes.virtualkeyboardpolicy

**Comment by teoli2003** [comment]
cc/ing @queengooborg 

This is weird.

**Comment by caugner** [comment]
The BCD data has just been added and will only be available on MDN after the next BCD release: https://github.com/mdn/browser-compat-data/pull/18762

**Comment by teoli2003** [comment]
Sorry! I read the date of the creation of the PRs and didn't notice it was merged yesterday only! Thank you!
