### ISSUE TITLE
[Regression?] Generate clickable tags for description terms

### ISSUE THREAD

**Issue by KartikSoneji** [mdn/yari#8394]
PR #3428 made linking to specific attributes easier by generating clickable links.
But it seems to have been lost in the new UI refresh.

The current UI uses a description table with description terms for attributes, and each of them has a unique id but no easy way to link to them directly.
Related: #3148

**Comment by teoli2003** [comment]
We are removing these macros.

**Comment by KartikSoneji** [comment]
Ah ok, I was just opening an issue since it's listed as a step in the contribution guidelines.
https://github.com/mdn/yari/blob/20672d3bd1981387b39c78cd5d6396ce0d7cbf72/.github/PULL_REQUEST_TEMPLATE.md?plain=1#L10

I'm working on a way to inject the `<a>` tags without the macros.
I'll open a PR shortly: https://github.com/KartikSoneji/yari/tree/feature/hyperlink-dt-table-entries

**Comment by teoli2003** [comment]
Definition list in mdn/content automatically get a `#xyz` link. We had two macros, one to generate `#attr-xyz and he other to link to it. We are removing both of these.

So to link to a defintion term named `xyz`  you can use a Markdown link with the anchor `#xyz`.

Or maybe I have misunderstood you?

**Comment by KartikSoneji** [comment]
Right now, to link to the id I have top right click > inspect element > find the id of the element I want to link to > copy-paste the id in the hashfragment of the url.
Turning the text into a hyperlink allows users to just click the link to get the url, similar to how headings work.
Perhaps the original issue has a better explaination: 3148

**Comment by teoli2003** [comment]
Or you put the name of the attribute you want to link to.

**Comment by KartikSoneji** [comment]
Hmm that is usually the case, but there might be instances where the id is not equal to the name since the name is already taken.
Also, I feel a link is much better for UX.
