### ISSUE TITLE
This fixes a compiler performance issue in `validation-test/stdlib/UnsafeBufferPointerSlices.swift`. Using `reduce` expressions in `expectEqual()` causes very slow expression resolution. Changed the tests to something simpler, and re-enabled the test.

### ISSUE THREAD

**Issue by iampaulnorman1010** [mdn/yari#8428]
This fixes a compiler performance issue in `validation-test/stdlib/UnsafeBufferPointerSlices.swift`. Using `reduce` expressions in `expectEqual()` causes very slow expression resolution. Changed the tests to something simpler, and re-enabled the test.

Resolves rdar://106656555, and undoes https://github.com/apple/swift/pull/64352.

_Originally posted by @glessard in https://github.com/apple/swift/pull/64393_

**Comment by schalkneethling** [comment]
@iampaulnorman1010, please note that we have dozens of people watching this repository. For every comment posted, these people may receive a notification.

Please be respectful of other people’s time and attention, and avoid taking actions that might cause excessive notifications. Issues should describe a problem or propose an actionable solution. Please use the [MDN Web Docs feedback repository](https://github.com/mdn/feedback/discussions) if a discussion is needed.

Also, please remember that the [Mozilla Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/) govern all participation in these open spaces. We enforce these to maintain a healthy and inviting community experience for everyone.
