### ISSUE TITLE
Consider new ways to create a document

### ISSUE THREAD

**Issue by escattone** [mdn/yari#843]
We should consider new ways for users to create new documents via the Yari local preview server:
- `Create Document` button on the 404 page? (@Elchi3 frequently uses this approach)
- Some way to create documents from the links that have the `new` class? (@a2sheppy frequently uses this approach)

**Comment by peterbe** [comment]
Those are so good suggestions that maybe they should be split up so it makes sense to "vote" for which feature request the team needs the most.

**Comment by peterbe** [comment]
Yeah, this came up quite a bit. 
Perhaps an interesting implementation is to add something like `--template=SLUG` to the `yarn tool create` command. 
What do you think @fiji-flo ?
