### ISSUE TITLE
Delete all branches on the upstream git repo

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#848]
Every time someone forks `yari`, and we hope and expect this to happen a lot, they all get every single branch in their fork. E.g. this is what happens when I fetch `schalkneethling`'s remote:
```
Fetching the latest from schalkneethling
schalkneethling/834-reposition-create-document updated
schalkneethling/autocomplete-search-with-flexsearch updated
schalkneethling/build-tree updated
schalkneethling/debug-travis updated
schalkneethling/dependabot/npm_and_yarn/jest-26.0.1 updated
schalkneethling/dependabot/npm_and_yarn/react-router-6.0.0-alpha.5 updated
schalkneethling/dependabot/npm_and_yarn/react-router-dom-6.0.0-alpha.5 updated
schalkneethling/dependabot/npm_and_yarn/types/node-14.0.1 updated
schalkneethling/deployment updated
schalkneethling/is-yarn-cached updated
schalkneethling/js-sidebar updated
schalkneethling/ks-renderer updated
schalkneethling/ks-renderer-sync updated
schalkneethling/master updated
schalkneethling/new-cli updated
schalkneethling/prettier updated
```

**Comment by peterbe** [comment]
You can manually delete inactive branches here: https://github.com/mdn/yari/branches
Don't delete the Dependabot ones. 

@Gregoor @escattone If you see your branches in there, and they don't belong in the upstream remote any more, delete them please.

**Comment by peterbe** [comment]
According to https://github.com/mdn/yari/branches/all it's all that handsome fella from Germany who has branches in there. So I'll assign this issue to him and then we can be done with this.

**Comment by Gregoor** [comment]
Whoopsie, me and my bad defaults! Cleared out all of my branches. Compliments are always a great incentive 💐
