### ISSUE TITLE
Left Navigation Bar  not Works Properly

### ISSUE THREAD

**Issue by akonitx** [mdn/yari#8494]
### Summary

Left nav scroll bar not works. As i cheked it doesn’t work nor in Chrome and nor in Firefox.
[Youtube link for screen recorder.](https://youtu.be/Yj0ECGYcC1Y)

### URL

Is appear anywhere in your site where is left scroll nav bar.

### Reproduction steps

1.
2.
3.

### Expected behavior

Nav scroll bar should scroll

### Actual behavior

not scrolling

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by jasonren0403** [comment]
nor in Edge also :(

![image](https://user-images.githubusercontent.com/40999116/227709444-ed7417e5-eeaa-44b8-9dea-faaf6977b460.png)

**Comment by deepug9787** [comment]
The `display: contents` set on the `.sidebar-container` appears to be the culprit.

**Comment by Disney-Banje** [comment]
Yes the left aside guide section is unresponsive
![developer mozilla org_en-US_docs_Learn (1)](https://user-images.githubusercontent.com/91415009/227732569-06664e2e-58be-4a26-aa92-b074b8c1ebd0.png)

**Comment by gekasam** [comment]
For some unknown reason, sidebar scrolling disappears. If you reduce the width of the view - appears.
Disabling extensions doesn't help.
Chrome  111.0.5563.111 x64 / Mozilla
Win 10

![Screenshot_1](https://user-images.githubusercontent.com/98611096/227739127-1b5fa12b-c5e1-4487-b383-565b12a307b0.png)
![Screenshot_2](https://user-images.githubusercontent.com/98611096/227739130-90f06a21-8264-4272-856f-491eae913f3e.png)

**Comment by caugner** [comment]
@akonitx @jasonren0403 @gekasam @yashwithgm We have not been able to reproduce the issue yet.

1. Can you please try and run Chrome/Edge/Firefox with extensions disabled (e.g. `chrome --disable-extensions`) and verify if the issue persists?
2. What are the exact versions of Chrome/Edge you're using?
3. What are your screen resolutions?

**Comment by jasonren0403** [comment]
> @akonitx @jasonren0403 @gekasam @yashwithgm We have not been able to reproduce the issue yet.
> 
> 1. Can you please try and run Chrome/Edge/Firefox with extensions disabled (e.g. `chrome --disable-extensions`) and verify if the issue persists?
> 2. What are the exact versions of Chrome/Edge/Firefox you're using, an on what operating system?
> 3. What are your screen resolutions?

I am running windows 11 on 1920x1080 screen, and my Edge version is 111.0.1661.54.
Disabling extensions did not resolve the issue.

**Comment by akonitx** [comment]
> 1. Can you please try and run Chrome/Edge/Firefox with extensions disabled (e.g. `chrome --disable-extensions`) and verify if the issue persists? 
Yes, it persists.
> 2. What are the exact versions of Chrome/Edge/Firefox you're using, an on what operating system?
Chrome: Version 111.0.5563.110 (Official Build) (x86_64)
FireFox: Version 111.0.5563.110 (Official Build) (x86_64)
> 3. What are your screen resolutions?
3072‑by‑1920
My device: MacBook Pro (16-inch, late 2019)
[link with same issue but without any extensions(using Chrome Inkognito tab and Firefox Private Mode)](https://www.youtube.com/watch?v=JYzFEaGk_XM)

**Comment by yashwithgm** [comment]
1. Tested on Both Google Chrome and Mozilla Firefox with extensions disabled, still the issue persists.
2. Chrome version - 111.0.5563.111, Firefox version - 110.0.1 on Windows 11
3. Resolution - 1366 x 768

**Comment by fiji-flo** [comment]
Fix should be fully rolled out now.

**Comment by deepug9787** [comment]
@fiji-flo It's working now! Thank you very much.
