### ISSUE TITLE
Incorrect browser compatibility tooltips

### ISSUE THREAD

**Issue by FozzieHi** [mdn/yari#8587]
### Summary

Split from #8586

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer#browser_compatibility

If you go to Edge under the `messageerror event` row you will see the tooltip "User must explicitly enable this feature." for "Removed in 79 and later":
![image](https://user-images.githubusercontent.com/23139726/230484886-d4f904e8-b12a-4be8-8aac-19a27fd24c81.png)

### URL

https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerContainer#browser_compatibility

### Reproduction steps

N/A

### Expected behavior

N/A

### Actual behavior

N/A

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Linux

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by danielhjacobs** [comment]
It used to be that the "Removed in..." note used the footnote icon:

https://github.com/mdn/yari/blob/9a9cc5e04589f42ec63623bbad15418ae893a761/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx#L308-L314

After the redesign back in 2022, the icon was changed to the disabled icon, which if you didn't know the codebase would make perfect sense:

https://github.com/mdn/yari/blob/dbaddf2c7578cde358dd974b35587d22b63d94dd/client/src/document/ingredients/browser-compatibility-table/feature-row.tsx#L316-L322

The disabled icon has the mentioned tooltip:

https://github.com/mdn/yari/blob/1f6ba5d040189efcdf1bdca0fdeac96773f8b79f/client/src/document/ingredients/browser-compatibility-table/legend.tsx#L25

The footnote icon's tooltip is this:

https://github.com/mdn/yari/blob/1f6ba5d040189efcdf1bdca0fdeac96773f8b79f/client/src/document/ingredients/browser-compatibility-table/legend.tsx#L24
