### ISSUE TITLE
Incorrect og:locale language code ("en-US" instead of "en_US")?

### ISSUE THREAD

**Issue by glmvc** [mdn/yari#8594]
### Summary

I was working on meta tags on my personal site when I noticed something that was divergent.
**The Open Graph language codes seem to require an underscore (instead of a hyphen) as a separator.**
I couldn't find anything about this in the MDN docs, so I looked directly in the source code of the MDN website; that's how I noticed it.

The [official Open Graph protocol](https://ogp.me/#optional) specifies that the format is `format language_TERRITORY` and provides an example of the default value `en_US`.
I tried to research it further but couldn't find much. The following links are from the Facebook dev docs which might confirm this:
- https://developers.facebook.com/docs/javascript/internationalization#locales
- https://developers.facebook.com/docs/messenger-platform/messenger-profile/supported-locales/

Maybe someone can test this again with the [sharing debugger tool](https://developers.facebook.com/tools/debug/), but I _assume_ that if the locale is not correct, it is just ignored and falls back to the lang of the document. But this is just my speculation, I haven't had a chance to test this with the debugger.

As `en_US` is the default value of `og:locale`, it can actually be omitted or?

I found this [pr](https://github.com/mdn/yari/pull/3623/files) where these Open Graph tags have been added.

### URL

https://developer.mozilla.org/en-US/
https://developer.mozilla.org/en-US/docs/Learn
https://developer.mozilla.org/en-US/docs/Web/JavaScript

(I think on all sites?)

### Reproduction steps

The _incorrect_ `og:locale` meta tag is in the `head` element of the documents

### Expected behavior

The _correct_ lang code for this specific Open Graph meta tag as specified in the official protocol/docs:
`<meta property="og:locale" content="en_US">` (underscore instead of a hyphen)

### Actual behavior

The _incorrect_ lang code for this specific Open Graph meta tag:
`<meta property="og:locale" content="en-US">`

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

<img width="439" alt="Screenshot 2023-04-10 at 11 31 05" src="https://user-images.githubusercontent.com/95487764/230875292-04ddcbbb-4a52-46e7-8087-3d7049139807.png">

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by glmvc** [comment]
Coming back to this issue, I re-evaluated this topic and checked it with [Facebook Sharing Debugger](https://developers.facebook.com/tools/debug/).

My guess from back then seems to be correct:
The _incorrect_ value of `og:locale` is ignored (at least according to the sharing debugger).
For sites that use the _correct_ language format, for example `en_US`, the debugger recognizes the specified language and outputs it.

**Comment by glmvc** [comment]
@caugner No problem! As much as my time and knowledge will allow, I will have a closer look and try to correct it.

**Comment by glmvc** [comment]
@caugner I noticed that you were one step ahead in https://github.com/mdn/yari/pull/9795; thank you for the fix you made! :)
I guess it's fine to close this issue, as it addresses the same issue as https://github.com/mdn/yari/issues/9429

**Comment by caugner** [comment]
Thank you for the ping @glmvc, indeed it looks like https://github.com/mdn/yari/pull/9795 also resolved this issuse. 🎉
