### ISSUE TITLE
"See also" is almost invisible in ToC

### ISSUE THREAD

**Issue by wbamberg** [mdn/yari#8610]
...on https://developer.mozilla.org/en-US/docs/Web/API/WebGPU_API, the "See also" link in the ToC is almost invisible:

<img width="271" alt="Screen Shot 2023-04-10 at 10 21 34 AM" src="https://user-images.githubusercontent.com/432915/230955725-61440982-d458-48c2-9084-f0e78c0f539c.png">

**Comment by mirunacurtean** [comment]
@wbamberg Thank you for bringing up this matter. 
I've also reproduced this when testing a page with a [long TOC](https://developer.mozilla.org/en-US/docs/web/api/fetch_api/using_fetch), on a [popular viewport ](https://screensizemap.com/)size. 
In fact, even using the TOC scrollbar, the last items in the list cannot be reached. 

![Long TOC is not scrollable](https://user-images.githubusercontent.com/53306802/231154504-4828d478-165e-44e7-8d2e-1ed52ce780e4.gif)

This occurs in the following situations: 

- on laptop sized viewports
- when the browser is resized vertically
- when using docked to the bottom developer tools on a laptop viewport
- when ads banners are enabled 

![image](https://user-images.githubusercontent.com/53306802/231155086-a886cd7f-ca94-46ea-9e19-f2657daf64e0.png)

@LeoMcA When you have the time, could you take a look at this?
