### ISSUE TITLE
Mobile sidebar obstructed by main page code blocks

### ISSUE THREAD

**Issue by Josh-Cena** [mdn/yari#8646]
### Summary

There seems to be a z-index issue with code blocks and the mobile sidebar overlay. This issue has persisted for a few weeks but I'm surprised no one seems to have reported it yet.

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator

(And every other page)

### Reproduction steps

1. Scroll so that there's a code block in view.
2. Open the sidebar.

### Expected behavior

The sidebar to completely cover the main content.

### Actual behavior

The sidebar is obstructed by the code block and other SVG icons.

### Device

Smartphone

### Browser

Safari

### Browser version

Stable

### Operating system

iOS

### Screenshot

<img width="418" alt="image" src="https://user-images.githubusercontent.com/55398995/232251210-6ca259a7-ab5e-461c-83d3-5944ed6cfac8.png">

### Anything else?

I can reproduce this on all browsers (Safari, FF, Chrome) on mobile.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by dostonnabotov** [comment]
Hey, there! 👋
If it hasn't been assigned yet, I would be happy to pick it up and fix this issue.

**Comment by yarusome** [comment]
The `display: flex` on `.main-wrapper` seems culpable.

**Comment by ruihildt** [comment]
I guess this is the same issue: 
![Screenshot_20230511-204353](https://github.com/mdn/yari/assets/13787166/0fec22f7-e86d-4aca-aaba-5a33e9872385)

**Comment by Cooldogyum** [comment]
There also appears to be a gap at the top of the sidebar when advertisements load.

![developer mozilla org_en-US_docs_Web_JavaScript_Guide_Indexed_collections](https://github.com/mdn/yari/assets/21272906/af0c9ec9-ae5f-487b-8414-8b7df42f15ab)
