### ISSUE TITLE
Add redirect option to document deletion

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#865]
When Will tested Yari we learned that a common workflow is to delete old/outdated/low-quality documents and add a redirect to an existing document. We could have UI that supports that workflow, similar to how we already add redirects when moving documents.

**Comment by peterbe** [comment]
https://github.com/mdn/yari/pull/1358 isn't complete but it does present a good avenue to make a CLI tool to create new redirects. It'd be something like:
```
yarn redirects add [--locale en-us] /en-US/docs/Foo /en-US/docs/Bar
```

**Comment by schalkneethling** [comment]
@escattone Looks like we got this covered?

**Comment by escattone** [comment]
Yes! Thanks @schalkneethling
