### ISSUE TITLE
could not load Live sample

### ISSUE THREAD

**Issue by yin1999** [mdn/yari#8662]
### Summary

The live sample is failed to load from `live-samples.mdn.mozilla.net`, got `404` error code.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/:hover
https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid

### Reproduction steps

open those pages and see the live samples.

### Expected behavior

could see those live samples.

### Actual behavior

Got 404 error code

Some response headers:

`GET https://live-samples.mdn.mozilla.net/en-US/docs/Web/CSS/:invalid/_sample_.showing_sections_in_stages.html`

```http
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
alt-svc: clear
cache-control: no-store, must-revalidate
content-length: 21007
content-type: text/html
date: Tue, 18 Apr 2023 07:26:54 GMT
expires: Tue, 18 Apr 2023 07:26:54 GMT
server: Google Frontend
strict-transport-security: max-age=63072000
via: 1.1 google
x-cache: miss
x-cloud-trace-context: 67361bc07f2b40e60f3c32ec1c4c4526
x-content-type-options: nosniff
x-guploader-uploadid: ADPycduejKBs1GQUdevRdqmo0LOPK4reQcZ42Rd1yi22L0q7gJDi0y35WXK2auGYBO-FZ12IXvwOSTbzoAuUE0e5Va_n0T2rfkU7
x-xss-protection: 1; mode=block
```

`GET https://live-samples.mdn.mozilla.net/en-US/docs/Web/CSS/:invalid/_sample_.coloring_elements_to_show_validation.html`

```http
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
alt-svc: clear
cache-control: no-store, must-revalidate
content-length: 21007
content-type: text/html
date: Tue, 18 Apr 2023 07:26:54 GMT
expires: Tue, 18 Apr 2023 07:26:54 GMT
server: Google Frontend
strict-transport-security: max-age=63072000
via: 1.1 google
x-cache: miss
x-cloud-trace-context: fea226671d46f605f237b1bbfc43fcea
x-content-type-options: nosniff
x-guploader-uploadid: ADPycdsVQAPOfdlvL-0MlPerSUUxsx9FWe5x7nFV6KHVFfahFEQvCJcoAA8f4RFqNLDf2oiB_UdDSJbqLAFM9vtZO00spj-MDycE
x-xss-protection: 1; mode=block
```

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Linux

### Screenshot

https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid

![image](https://user-images.githubusercontent.com/15844309/232704509-d2ce3427-13b4-4030-ae30-3f866ccb45aa.png)

![image](https://user-images.githubusercontent.com/15844309/232704582-ea57e5af-b869-4375-86a0-6ae5196c4690.png)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
@yin1999 Good catch, thank you for the bug report.

https://github.com/mdn/yari/commit/4cad3cc318327310f46a5b3760112cac67612d57 should fix this (verified on stage) and the deployment is in progress.

**Comment by caugner** [comment]
Just realised it's probably just a partial fix, and images in those live samples are also affected. Will investigate and report back shortly.

**Comment by caugner** [comment]
Fixed via https://github.com/mdn/yari/commit/c77996ba236878b7fc4d8a4976f570aff27541b5, deployment to prod is [in progress](https://github.com/mdn/yari/actions/runs/4731555505).

**Comment by caugner** [comment]
I just verified it's fixed now. 🎉 

Thanks again for reporting this.
