### ISSUE TITLE
Look into why newly-added add-on pages with tags don't seem to be detected by the AddonSidebar macro

### ISSUE THREAD

**Issue by escattone** [mdn/yari#870]
### Summary
When a new page is added under `/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs`, like `/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/warmup`, and given the same tags as `/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/captureTab`, any call to the `AddonSidebar` (by the new page or any other page that calls that macro) should include a link to the new page in its sidebar, but that doesn't seem to be working when the page rebuild is automatically triggered by the file watcher.

This is probably not a problem with the `AddonSidebar` macro, but more likely some larger cause within the Yari builder. One possibility, is that `allTitles` and/or its reflection in the Kumascript renderer instance are not being updated after a new document is added. This may indicate a fundamental problem with the invalidation of our cached build information like `allTitles`.

**Comment by peterbe** [comment]
Is this still an issue?

**Comment by peterbe** [comment]
@escattone I really suspect we killed that bug when we made the `kumascript` use absolutely not caching when in dev mode. Also, the `allTitles` functionality is too long gone :)
