### ISSUE TITLE
Proposal: Make the "Animation type" key link to "Animatable CSS properties" (CSSInfo macro)

### ISSUE THREAD

**Issue by yarusome** [mdn/yari#8721]
### Summary

This issue proposes to make the "Animation type" key in the "Formal definition" table for every CSS property link to [Animatable CSS proprties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties), where standard animation types are now explained.

A follow-up to https://github.com/mdn/content/pull/26364.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/height#formal_definition

### Reproduction steps

1.

### Expected behavior

The "Animation type" key link to "[Animatable CSS properties](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties)".

### Actual behavior

No link.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by teoli2003** [comment]
Sounds like a good idea to me.

**Comment by roy9495** [comment]
can I work on this issue?
