### ISSUE TITLE
Static JS/CSS temporarily not found (HTTP 404) during deployment

### ISSUE THREAD

**Issue by hong539** [mdn/yari#8752]
### Summary

These URL show me the code 404.

### URL

https://developer.mozilla.org/en-US/docs/MDN/Community/Issues
https://developer.mozilla.org/en-US/docs/Web/Performance/dns-prefetch

### Reproduction steps

1.Just click these URL via your browser.
2.And open dev tools>network 
3.some *.css/*.js files show the code 404

### Expected behavior

https://developer.mozilla.org/static/css/main.XXXXXX.css
https://developer.mozilla.org/static/js/main.XXXXXX.js

I think these files should be load as status code:200

### Actual behavior

https://developer.mozilla.org/static/css/main.XXXXXX.css
https://developer.mozilla.org/static/js/main.XXXXXX.js

But they response as status code:404

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![螢幕擷取畫面 2023-05-04 012129](https://user-images.githubusercontent.com/52050772/235993598-5f7bcb30-f84c-4a43-8260-61b85353dce2.png)
![螢幕擷取畫面 2023-05-04 012216](https://user-images.githubusercontent.com/52050772/235993614-8a932fe8-ca88-4bbf-a63c-43b0c5625c86.png)

### Anything else?

Maybe there are some URLs have same problems.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
@hong539 Thanks for reporting this. Do you still experience this problem or was this just temporary? It looks like a deployment artifact, i.e. you're seeing an old version of the page, but we already invalidated the cache and the old JS/CSS is no longer available.

**Comment by hong539** [comment]
> 

No, thanks you!
