### ISSUE TITLE
`{{CSSXref}}` handles CSS functions incorrectly

### ISSUE THREAD

**Issue by yarusome** [mdn/yari#8755]
### Summary

Since https://github.com/mdn/content/pull/14006:

  1. using this macro for CSS functions with parentheses in its parameter, e.g. `{{CSSXref("abs()")}}`, results in flaws, as parentheses are still kept in the URLs;
  2. `:host()` and `fit-content()` needs special-casing to append `_function` in the URLs.

Also:

  1. https://github.com/mdn/content/pull/26395 added `<overflow>`, which needs special-casing, too.
  2. The examples in `cssxref.ejs` need correction.

### Proposed solution

On [Line 53](https://github.com/mdn/yari/blob/main/kumascript/macros/cssxref.ejs#L53):

```diff
- // Deal with CSS functions by removing ()
- var slug = $0.replace(/&lt;(.*)&gt;/g, '$1');
+ // Deal with CSS data types and functions by removing <> and ()
+ var slug = $0.replace(/&lt;(.*)&gt;/g, "$1")
+     .replace(/\(\)/g, "");
  
- // Special case <color>, <flex>, and <position>
- switch ($0) {
-     case '&lt;color&gt;':
-         slug = 'color_value';
-         break;
- 
-     case '&lt;flex&gt;':
-         slug = 'flex_value';
-         break;
- 
-     case '&lt;position&gt;':
-         slug = 'position_value';
-         break;
- }
+ // Special case <color>, <flex>, <overflow>, and <position>
+ if (/^&lt;(color|flex|overflow|position)&gt;$/.test($0)) {
+     slug += "_value";
+ }
+ 
+ // Special case :host() and fit-content()
+ if (/^(:host|fit-content)\(\)$/.test($0)) {
+     slug += "_function";
+ }
```

### URL

https://github.com/mdn/content/pull/26575

### Reproduction steps

1.

### Expected behavior

No flaw for {{CSSXref("url()")}}.

### Actual behavior

A redirection flaw.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Anything else?

Relates to #8578.
Related discussion: https://github.com/orgs/mdn/discussions/369

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by yarusome** [comment]
@teoli2003 I hope the proposed solution here works for your case.

**Comment by teoli2003** [comment]
Can you create a PR? (and avoid the `var`) Use `let` instead. [I really dislike these macros.]
