### ISSUE TITLE
The "Formal syntax" section for `rgb()` is incorrect

### ISSUE THREAD

**Issue by yarusome** [mdn/yari#8777]
### Summary

The "Formal syntax" section only shows the legacy syntax of `rgb()`, and even the shown syntax is incorrect (i.e. lacks `#`).

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb#formal_syntax

### Reproduction steps

1. Navigate to the link above.
2. Compare the syntax shown there and that in the [spec](https://w3c.github.io/csswg-drafts/css-color/#rgb-functions).

### Expected behavior

```
<rgb()> =
  rgb( [ <number> | <percentage> | none ]{3} [ / [<alpha-value> | none ] ]? )
```

### Actual behavior

```
<rgb()> = 
  rgb( [ <percentage> | none ]{3} [ / [ <alpha-value> | none ] ]? )  |
  rgb( [ <number> | none ]{3} [ / [ <alpha-value> | none ] ]? )
```

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Anything else?

  1. webref/css does contain the correct syntax on [Line 826-854](https://github.com/w3c/webref/blob/curated/ed/css/css-color.json#L826-L854) in `css-color.json`.
  2. [`hsl()`](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/hsl#formal_syntax), which also has a legacy syntax, shows correctly.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by bsmth** [comment]
This is defined here: https://github.com/mdn/data/blob/main/css/functions.json#L355

But I thought we were pulling this in from webref and no longer updating `mdn/data`, maybe I'm mistaken.

**Comment by bsmth** [comment]
Actually I believe we're waiting to migrate [webref](https://github.com/w3c/webref) to >=v6.0.0

**Comment by yarusome** [comment]
@bsmth I refrained from opening a PR for `css-syntax.ts` due to the complexity of its structure. Besides, I see that this script should probably be covered/superseded by openwebdocs/project#174.

**Comment by caugner** [comment]
@yarusome We have meanwhile updated to `@webref/css` v6 (although not yet to the latest version). Can you please check if the formal syntax is now "correct"?

**Comment by caugner** [comment]
[It looks good](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb#formal_syntax) to me now:

![Image](https://github.com/mdn/yari/assets/495429/a358df35-fd72-4ef1-98b3-53e853022d35)

So I'm going ahead and close this issue as resolved.
