### ISSUE TITLE
Handle default internationalization

### ISSUE THREAD

**Issue by harrisi** [mdn/yari#8823]
### Summary

Currently, the MDN URL structure is `https://developer.mozilla.org/${language-tag}/...rest`. e.g., `https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode`. However, if a path doesn't include the `language-tag`, it just goes to the "page not found" page. I propose injecting the language tag to the user agent's default locale if possible by injecting the `language-tag` into the base of the path if `Accept-Language` header exists.

### URL

https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

### Reproduction steps

1. Open a page that is in quirks mode (or Almost Standards mode) in Firefox (e.g., https://www.quirksmode.org/)
2. View console output
3. Click on [Learn More] in console

### Expected behavior

Navigate to https://developer.mozilla.org/en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

### Actual behavior

Navigates to https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Mac OS

### Anything else?

This issue has been discussed before in #3771. I'm not sure if the desired behavior should be to change the url in Firefox (https://searchfox.org/mozilla-central/source/parser/html/nsHtml5DocumentBuilder.cpp#109-111, with the link in question being defined [here](https://searchfox.org/mozilla-central/source/devtools/server/actors/errordocs.js#139-140)), or going with this proposal. I personally think using the user agent's `Accept-Language` header is ideal, but changing the url in Firefox is definitely an easier solution.

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by harrisi** [comment]
This is related to #8822, which I just [opened a PR for](https://github.com/mdn/yari/pull/8824). The solution proposed here is still different, however, and would inject the locale into the path before even getting to that page, making the change in that PR obsolete. I can also open a PR for this solution instead.

**Comment by caugner** [comment]
Thanks for taking the time to raise this issue, and sorry for the long triage time.

In fact we already do what you're suggesting.

When you access an MDN url without a locale, you do get redirected to the best locale:
1. If there is a `preferredlocale` cookie with a locale that we support, then we redirect to this locale.
2. Else if the `Accept-Language` header has a locale that we support, then we redirect to this locale.
3. Else we redirect to `en-US`.

This work is done by the [redirect-locale](https://github.com/mdn/yari/blob/0bd5489ea8556b07b79e66aecc2fe3b7ffed022b/cloud-function/src/middlewares/redirect-locale.ts) middleware, and the code to determine the locale is in `libs/locale-utils`:

https://github.com/mdn/yari/blob/0bd5489ea8556b07b79e66aecc2fe3b7ffed022b/libs/locale-utils/index.js#L57-L73

I just double-checked that this is still working as expected:

```console
$ curl https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
Found. Redirecting to /en-US/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

$ curl --header "Accept-Language:fr" https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
Found. Redirecting to /fr/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

$ curl --cookie "preferredlocale=es" https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
Found. Redirecting to /es/docs/Web/HTML/Quirks_Mode_and_Standards_Mode

$ curl --header "Accept-Language:ko" --cookie "preferredlocale=ja" https://developer.mozilla.org/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
Found. Redirecting to /ja/docs/Web/HTML/Quirks_Mode_and_Standards_Mode
```

I'm closing this issue as "can't repro", but please let me know if you're still experiencing this issue (if so, are you using MDN Offline?).
