### ISSUE TITLE
Blog links marked as broken

### ISSUE THREAD

**Issue by yarusome** [mdn/yari#8954]
### Summary

On preview pages and real pages, links to MDN blogs are marked as broken.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/color_value#see_also
https://pr26775.content.dev.mdn.mozit.cloud/en-US/docs/Web/CSS/color_value#see_also

### Reproduction steps

1. Navigate to either page above.
2. Look at the last link in the "See also" section.

### Expected behavior

![expected](https://github.com/mdn/yari/assets/97945148/0c666e6e-416a-4a75-aa2a-7a794e316c7d)

### Actual behavior

![actual](https://github.com/mdn/yari/assets/97945148/43d4fc80-7bb9-47c0-89c7-2198f5c1ba1b)

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by schalkneethling** [comment]
Thank you for filing the issue, @yarusome 🎉 @caugner, could it be that the flaw checker expects `/docs` always to be part of the slug?

**Comment by caugner** [comment]
Good catch @yarusame! 🎉

There are two parts to the issue:

1. As @schalkneethling said, the flaw checker uses `Document.findByUrl()` [here](https://github.com/mdn/yari/blob/a9d737026ac159458a18ed261321e14751aff382/build/flaws/broken-links.ts#L278) to resolve internal links, and this doesn't take into consideration blog articles.
2. The link will always be flagged as a flaw for contributors as the (private) `mdn/mdn-studio` repository with the blog articles won't be checked out locally.

We could fix 1., but 2. would remain, so I'm going ahead and close this issue as "won't fix".

/cc @LeoMcA

**Comment by bsmth** [comment]
Two thoughts on this:
* Could the flaw checker ignore `/en-US/blog/` links? If not:
* What if we [allow absolute URLs for the blog](https://github.com/mdn/content/blob/6068006d89ef74e682685d4e6070d1bf9ed0f247/.markdownlint-cli2.jsonc#L185-L191)? We could then check if they're 200/404 like any external link.
