### ISSUE TITLE
Markup top-navigation problem.

### ISSUE THREAD

**Issue by gekasam** [mdn/yari#9015]
### Summary

The navigation bar has a distance to the top of the page in the Chrome browser. Disabling extensions doesn't help. Changing the viewing height doesn't help.

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript

### Reproduction steps

1.  Open mdn website.

### Expected behavior

The top navigation bar is fixed at the top without indentation.

### Actual behavior

The top navigation bar is fixed at the top with an indentation.

### Device

Desktop, screen-size 1680/1050

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Screenshot

![Screenshot_5](https://github.com/mdn/yari/assets/98611096/4a7a9189-7caf-407b-af33-e726265ffa51)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by danizier** [comment]
I found out that this gap is triggered through windows scaling settings. At 125% and 175% scaling this problem occurs. Read more on my Issue [Pixel Gap between browser top bar and mdn top bar #9140](https://github.com/mdn/yari/issues/9140).

**Comment by caugner** [comment]
We believe this issue has been fixed in the mean-time, and we cannot reproduce it nor have we had any new reports, so we're going ahead and close this issue as resolved.

Please let us know if you're still experiencing this issue with a full screenshot of your screen and details about your OS, browser and screen. 🙏
