### ISSUE TITLE
Keywords are located at the bottom of the search box instead of the middle

### ISSUE THREAD

**Issue by fenghan34** [mdn/yari#9016]
### Summary

Hi team, I noticed that the keywords are located at the bottom of the search box instead of in the middle. Is this intentional?

### URL

https://developer.mozilla.org/en-US/

### Reproduction steps

Just focus on the search box and type some keywords.

### Expected behavior

Keywords are located in the middle of the search box.

### Actual behavior

Keywords are located at the bottom of the search box.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

<img width="1091" alt="image" src="https://github.com/mdn/yari/assets/59411875/191234fb-3d76-4dff-ab93-b3f7777eaf47">

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by fenghan34** [comment]
After checking on my mobile phone, it seems more like a bug.

![image](https://github.com/mdn/yari/assets/59411875/bd94f33e-975c-4c3f-8a74-f94dd7c50816)

**Comment by mirunacurtean** [comment]
@fenghan34 Thank you for the contribution. I just tested on Chrome 114.0.5735.106 and on Safari 15.6 on a MacOS Monterey 12.6.6 and I cannot reproduce. 
<img width="1500" alt="Screenshot 2023-06-13 at 14 35 25" src="https://github.com/mdn/yari/assets/53306802/d86b5d54-b9ef-415b-8cd0-844f5e33fa95"> 

Could you please check again after clearing the browser cache?

**Comment by fenghan34** [comment]
> Could you please check again after clearing the browser cache?

Just checked again, and seems like it has been fixed. Thank you for replying.
