### ISSUE TITLE
U - Determine path forward for doc 'summary' field

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#902]
## Description

This is a research issue to determine what to do with the doc 'summary' field. 

## Acceptance Criteria
- [x] Determine if they should allow for KS macros
- [x] Determine whether we need to support them at all
- [ ] New issues created once the answers have been determined

**Comment by peterbe** [comment]
We haven't heard from Janet, Will, or Florian. Only Kadir, Daniel, and Chris. But combined with the dev teams preferences, we've established that **we should NOT have the summary as the `title` attribute in the sidebars and xref macros. And not even bother with the document title as a fallback.**

The killer argument is the accessibility concern combined with the fact that not having summaries makes a serious engineering task moot.

**Comment by peterbe** [comment]
https://github.com/mdn/yari/issues/980 sums it up nicely. Let's just do that one.
