### ISSUE TITLE
Don't rely on interactive examples and remote URLs in headless tests

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#905]
Relying https://interactive-examples.mdn.mozilla.net/pages/tabbed/video.html can cause the headless tests to fail with timeouts.

**Comment by peterbe** [comment]
For the record, it happens every now and then that CI fails. The solution is to just press the "Re-run jobs" in GitHub Actions and it works. But that's not sustainable.

**Comment by peterbe** [comment]
And it happened again  https://github.com/mdn/yari/pull/914/checks?check_run_id=875142154 :(

**Comment by peterbe** [comment]
Before we just give up and remove the Interactive Example from the `Foo` page, we should perhaps look into how we're using puppeteer so it's either a bit more patient or that we're simply OK with the iframe not loading.

**Comment by peterbe** [comment]
Thing is, I quite like that our end-to-end tests do run the interactive examples at *some point*. So if we can re-jig our tests to not break just because the iframe times out we can and should at least assert that the right `<iframe>` code runs as expected but not freak out just because the content inside it failed to load.

**Comment by caugner** [comment]
Closing in favor of https://github.com/mdn/yari/issues/6990, which has more details about the failing test (and actual extracts from the log).
