### ISSUE TITLE
U - Refactor Yari PVP

### ISSUE THREAD

**Issue by tobinmori** [mdn/yari#908]
## Acceptance Criteria

Feature parity is the goal, that means not losing these features
- [x] passes existing end2end test suite
- [x] builds all documents 
- [x] allows searching through all the documents
- [x] builds a sitemap
- [x] build & development speed parity with a ~30% margin
- [x] translations?
- [x] fixable flaws
- [x] configurable builds

while fulfilling these goals of the refactoring:
- [x] eliminate most explicit caches (/indexes), to cut down on cache-invalidation issues and simplify the codebase
- [x] more explicit module boundaries between the content, build & KS workspaces

**Comment by tobinmori** [comment]
@Gregoor do you think you can flesh out what you had in mind for the acceptance criteria? I think @peterbe may have found these a little unclear/vague.

**Comment by peterbe** [comment]
Let's make https://github.com/Gregoor/yari/pull/5 a task of this user story. It doesn't have an issue, just a PR.

**Comment by peterbe** [comment]
https://github.com/mdn/yari/pull/881 became where we hung out to do all the ACs of this user story. 

I can't think of any reason not to close this user story as done. We did it!
