### ISSUE TITLE
Even though the Korean locale page exists, it is coming out that all of them do not exist.

### ISSUE THREAD

**Issue by hochan222** [mdn/yari#9154]
### Summary

Even though the Korean locale page exists, it is coming out that all of them do not exist.

### URL

https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Int32Array

or for all documents

### Reproduction steps

1. go to https://developer.mozilla.org/ko/docs/Web/JavaScript/Reference/Global_Objects/Int32Array
2. https://github.com/mdn/translated-content/blob/86dc45260e0afa9ac3eb78099f050d436b6b2f6f/files/ko/web/javascript/reference/global_objects/int32array/index.md

### Expected behavior

Korean documents in translated-content are exposed.

### Actual behavior

no page

### Device

Laptop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

<img width="869" alt="image" src="https://github.com/mdn/yari/assets/22424891/d49ecd7f-8b5d-48cf-a8de-678b7e6c6afa">

### Anything else?

https://github.com/mdn/content/issues/27516

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by hochan222** [comment]
@mdn/core @mdn/localization-team-leads  The entire Korean page was not appearing, so I mentioned it before checking. Do you have any expectations?

**Comment by hochan222** [comment]
It works fine on the local server.

<img width="1378" alt="image" src="https://github.com/mdn/yari/assets/22424891/46bdf80a-b071-4b9e-a4a2-ec46af6a11f5">

**Comment by LeoMcA** [comment]
Thanks for reporting, I'm investigating, I've got a good theory as to what's happening - just need to debug it now.

**Comment by LeoMcA** [comment]
My hotfix worked on staging, I've triggered a prod deployment: https://github.com/mdn/yari/actions/runs/5364347654

**Comment by LeoMcA** [comment]
Looks like the missing pages are back. Thanks for reporting!

**Comment by hochan222** [comment]
@LeoMcA Thanks for the quick fix on the weekend. I don't think the build is over yet, but I've confirmed that most of the pages come out well. Have a good weekend :)

**Comment by LeoMcA** [comment]
Thanks, you too!
