### ISSUE TITLE
Most time consuming macros

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#917]
I injected a little logging into the `kumascript/src/render.js` code:
```diff
+       var t0 = performance.now();
        currentResult.output = await templates.render(
          macroName,
          environment.getExecutionContext(token.args)
        );
+       var t1 = performance.now();
+       fs.appendFileSync("macros.log", `${t1 - t0}\t${macroName}\n`, "utf8");
```

Then I ran `node content build -l en-us -f web --no-progressbar --quiet` and wrote a script that sums the times. 
I.e. where is the most time spent.
Results:

```
TOTAL MACRO TIME:
1  cssref                                  37.8 s ~= 39.45ms x 959
2  apiref                                  6.7  s ~= 1.49ms x 4,476
3  spec2                                   4.9  s ~= 0.56ms x 8,663
4  specname                                4.2  s ~= 0.42ms x 9,992
5  page                                    3.8  s ~= 9.62ms x 400
6  compat                                  3.5  s ~= 0.42ms x 8,197
7  domxref                                 2.0  s ~= 0.06ms x 32,575
8  svgref                                  1.9  s ~= 5.95ms x 327
9  httpsidebar                             1.6  s ~= 5.63ms x 284
10 htmlref                                 1.6  s ~= 9.38ms x 167
11 jssidebar                               1.3  s ~= 4.89ms x 259
12 jsxref                                  1.0  s ~= 0.15ms x 7,155
13 addonsidebar                            0.7  s ~= 1.12ms x 663
14 jsref                                   0.7  s ~= 1.09ms x 644
15 cssxref                                 0.6  s ~= 0.08ms x 7,793
16 htmlelement                             0.4  s ~= 0.11ms x 3,590
17 embedlivesample                         0.2  s ~= 0.10ms x 2,301
18 csssyntax                               0.2  s ~= 0.33ms x 617
19 svgelement                              0.2  s ~= 0.08ms x 2,150
20 cssinfo                                 0.2  s ~= 0.34ms x 500
21 inheritancediagram                      0.2  s ~= 0.64ms x 248
22 htmlsidebar                             0.1  s ~= 3.90ms x 36
23 webextapiref                            0.1  s ~= 0.10ms x 1,409
24 defaultapisidebar                       0.1  s ~= 0.63ms x 185
25 index                                   0.1  s ~= 6.95ms x 16
```

I.e. the `cssref` macro (I'm guess it's [this one](https://github.com/mdn/yari/blob/master/kumascript/macros/CSSRef.ejs)) is used 959 times and if you sum up each execution time it comes to 37.8 seconds.

Obviously, I didn't log the arguments so I can't tell if some simple memoization caching could help. 
But if we want to fix the build performance speed, we should roughly go by this list.

**Comment by peterbe** [comment]
Most possibly I don't know what I'm talking about but for the ~1k Web/CSS pages 950 times it just does: `{{CSSRef}}` with no arguments. Obviously, thanks to the `environment.getExecutionContext(token.args)` it means that when CSSRef.ejs renders it gets a different `slug` each time. But I analyzed the sidebar HTML difference between `client/build/en-us/docs/web/css/width/index.html` vs. `client/build/en-us/docs/web/css/height/index.html` and the only difference is that when you're on [width](https://developer.mozilla.org/en-US/docs/Web/CSS/width) vs. [height](https://developer.mozilla.org/en-US/docs/Web/CSS/height) the only difference is that the page you're on changes from 
```html
               <a
                 href="/en-US/docs/Web/CSS/height"
                 title="The height CSS property specifies the height of an element. By default, the property defines the height of the content area. If box-sizing is set to border-box, however, it instead determines the height of the border area."
                 ><code>height</code></a
               >
```
to 
```html
               <em><code>height</code></em>
```

If that's the only effective difference we could easily hack around this. 
First, we rewrite `CSSRef.js` so that it doesn't remove the `<a>` if it's the page you're on. 
Now, to achieve the same effect you can use `cheerio` in the builder or you write a piece of front-end DOM code that looks up the link in the sidebar whose `href` matches the `window.location.pathname`.

**Comment by peterbe** [comment]
The CSSRef is a lot more complex that my wishful thinking of a quick hack. See https://discourse.mozilla.org/t/css-sidebar-proposal/49500

**Comment by Gregoor** [comment]
Another idea from looking at the macro's code:

Move all the mdn-data access into the KS runtime and index it by these group values being used in the macro. Thereby turning all these O(n^2) loops into something closer to O(1).

**Comment by peterbe** [comment]
> Another idea from looking at the macro's code:
> 
> Move all the mdn-data access into the KS runtime and index it by these group values being used in the macro. Thereby turning all these O(n^2) loops into something closer to O(1).

Oh do please tell me more. 
I've never actually looked at the code yet. Where are these O(n^2) loops?

PS. I did notice (after 10 sec of opening the .ejs files) that there's a lot of `var data = require('mdn-data')` happening inside the macros.

**Comment by Gregoor** [comment]
These were the lines I was thinking of:

https://github.com/mdn/yari/blob/8ebf034fdbc394558a8b1d172aee582e9637e45e/kumascript/macros/CSSRef.ejs#L95-L123

Though it's more of a shot in the dark, I've only skimmed it and haven't run it to be certain that this is really where most of the time is being spent.

**Comment by peterbe** [comment]
Heck, that one and the runtime `require()` are both great places to start!

**Comment by peterbe** [comment]
If you build all the `web/css` docs it does so at a rate of **8.9 documents per second**. 
If you comment out all of `kumascript/macros/CSSRef.ejs` and have it just return an empty string the rate goes up to **24 documents per second**.

**Comment by peterbe** [comment]
It's probably not important enough to be actionable. It's just sad that the `CSSInfo` macro is so complicated and that it can't be cached (because it depends on the caller). 

Somewhere in some distant future, we should do what Stumptown started which was the simple concept of "Related links". A simple array (or array of arrays) of links. Some of these arrays could be generated outside Kumascript simply by looping over all the sibling folders and displaying them either alphabetically or by some algorithm based on tags. 
The big challenge with any such solution is; how can the writer carefully control the specific order when it's something like the learning pathway where it only makes sense to show "Getting started" before the "Appendix".
