### ISSUE TITLE
Live sample in PR preview is broken

### ISSUE THREAD

**Issue by yin1999** [mdn/yari#9193]
### Summary

The live sample is broken in PR preview (got 404), see:

- mdn/content#27637 - https://pr27637.content.dev.mdn.mozit.cloud/en-US/docs/Web/HTML/Element/input/datetime-local
- mdn/translated-content#13957 - https://pr13957.content.dev.mdn.mozit.cloud/zh-CN/docs/Web/API/EyeDropper

![image](https://github.com/mdn/yari/assets/15844309/73fdade9-5a7b-402a-ad5e-48f72f3d3751)

### URL

see above

### Reproduction steps

open preview page and scroll to the live sample.

### Expected behavior

could see the live samples in PR preview

### Actual behavior

got 404

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by jasonren0403** [comment]
Another instance: https://pr14012.content.dev.mdn.mozit.cloud/zh-CN/docs/Learn/CSS/Styling_text/Styling_lists
