### ISSUE TITLE
The layout of the new paragraph

### ISSUE THREAD

**Issue by lonelyplant** [mdn/yari#9282]
### Summary

Hello, I have a typography problem. In the red box in the following two pictures, there is new paragraph in Github preview, but it is different in MDN. Is there any way to handle styles for Github？

![微信截图_20230711135012](https://github.com/mdn/yari/assets/34595699/ac3f1321-08ea-4509-ab77-5116da9670ac)

![微信截图_20230711134938](https://github.com/mdn/yari/assets/34595699/88c47878-5ae9-401a-bebc-cfbf1f0c8a9b)

### URL

- Github(line 278)：
https://github.com/mdn/translated-content/edit/main/files/zh-cn/learn/tools_and_testing/client-side_javascript_frameworks/vue_methods_events_models/index.md

- MDN(In the words "像这样更新你的 onSubmit() 方法")：
https://developer.mozilla.org/zh-CN/docs/Learn/Tools_and_testing/Client-side_JavaScript_frameworks/Vue_methods_events_models

### Reproduction steps

1. Open the link above MDN Web Docs in github, preview it.
2. Open the link above MDN Web Docs, search "像这样更新你的 onSubmit() 方法".
3. Compare them.

### Expected behavior

"像这样更新你的 onSubmit() 方法" is a new paragraph in this MDN chapter.

### Actual behavior

"像这样更新你的 onSubmit() 方法" is not a new chapter

### Device

Desktop

### Browser

Edge

### Browser version

Stable

### Operating system

Windows10

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by Josh-Cena** [comment]
There is code specifically removing descendant paragraphs:

https://github.com/mdn/yari/blob/adbe6b38786301cf70b66b4046c63629e0580b4f/markdown/m2h/handlers/index.ts#L114-L120

It seems very much intentional, but I don't know why.

**Comment by caugner** [comment]
Thank you for reporting this @lonelyplant, and thanks for looking into this @Josh-Cena. 👍 

The issue has already been reported in https://github.com/mdn/yari/issues/5042, so I'm closing this as duplicate.

PS: I don't know either why we remove paragraphs in lists (since https://github.com/mdn/yari/pull/3843).
