### ISSUE TITLE
line numbers incorrect on flaws from prerequisites

### ISSUE THREAD

**Issue by escattone** [mdn/yari#930]
### Summary
<img width="755" alt="image" src="https://user-images.githubusercontent.com/3743693/87724446-58e6b280-c770-11ea-846a-4605c8ccce1f.png">

When rendering http://localhost:3000/en-US/docs/Web/HTML/Element/input/range, the prerequisite `/en-US/docs/Web/HTML/Element/input/text` is also rendered and generates the `MacroBrokenLinkError from domxref in line 78:188` macro error shown in the image. The line number should be `52` but is incorrectly shown as `78`.

One problem with the current code, is that it doesn't take into account the `filepath` of the flaw when adjusting the flaw's line number with the front-matter offset. It's always using the offset of the original document, which doesn't apply to flaws originating from prerequisites of the original document.

**Comment by peterbe** [comment]
I think [the PR](https://github.com/mdn/yari/pull/936) didn't close it because you wrote:
```
Fixes #915 and #930
```
It needs to be:
```
Fixes #915
Fixes #930
```
...I think.
