### ISSUE TITLE
Open playground in a new tab on CTRL+click and Middle-click

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/yari#9323]
The playground always opens in the same tab. This forces user to use browser back and forward buttons to switch between playground and the content. Though the button has external link icon next to it, there is no way to open it in a new tab.

## Expected

When the "Play" button is clicked with CTRL held, open the playground in a new tab. Also allow mouse middle-click to do the same.

**Comment by caugner** [comment]
Created internal ticket: https://mozilla-hub.atlassian.net/browse/MP-606

**Comment by caugner** [comment]
Good news, this issue was meanwhile fixed as part of https://github.com/mdn/yari/issues/10155! 🎉
