### ISSUE TITLE
"Border-radius generator" is missing from the sidebar

### ISSUE THREAD

**Issue by yarusome** [mdn/yari#9351]
### MDN URL

https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Backgrounds_and_Borders/Border-radius_generator

### What information was incorrect, unhelpful, or incomplete?

There's no entry for the "Border-radius generator" page in the sidebar:

![screenshot](https://user-images.githubusercontent.com/97945148/236717234-8078e599-e021-43c1-853a-d4fcb8e93117.png)

Side note: The entries for "Border-image generator" and "Box-shadow generator" also lack the dashes.

### What did you expect to see?

An entry in the sidebar for this page.

**Comment by Himanshuch8055** [comment]
can you explain more about the issue?
