### ISSUE TITLE
BCD Signalling in React 

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#947]
Unlike Kuma, we don't have the BCD Signalling flap on our BCD tables. Let's fix that.

**Comment by peterbe** [comment]
Let's build this on top of the `kumastyles` branch.

**Comment by peterbe** [comment]
@escattone  @chrisdavidmills @HerminaC 

Is the BCD Signalling still important enough to make it a blocker for Yari1?
I think it won't be too horrible to code up a React version of the monster we have in Kuma. After all, whoever builds it doesn't need to worry about what it should say or how it should work. However, it's not without challenges because you probably can't really work on it till @schalkneethling 's Fiori branch lands in `master`. 

An option is to just say Sorry. After all, without Florian S around, who's even looking at the submissions? 
Perhaps, post-Yari1, we could revive it but do it differently. For example, we can make it auto-create GitHub issues in the BCD project, rather than just storing them in MySQL.

**Comment by escattone** [comment]
@peterbe Yes, I think it should be a blocker for Yari1. Currently we're throwing away the Kumascript-generated BCD table and replacing it with our own React-based Yari version, and that's why we have work to do here, right? If push comes to shove, couldn't we just use the Kumascript-generated BCD table (and its associated JS), and then we get the existing BCD signalling code along with it?

**Comment by peterbe** [comment]
> If push comes to shove, couldn't we just use the Kumascript-generated BCD table

Nope. Won't help. The BCD Signalling is its own JS bundle that [latches onto the DOM](https://github.com/mdn/kuma/blob/4ccb9b50c0090b3b19389d5571ece8a026692452/kuma/javascript/src/bcd-signal.jsx#L858) after document load. It won't care how the BCD table got created. 

One thing that might be an option, although it hurts, is to copy [the bad code](https://github.com/mdn/kuma/blob/4ccb9b50c0090b3b19389d5571ece8a026692452/kuma/javascript/src/bcd-signal.jsx) and bang on it till it works. It's currently written with Flow but needs to be transformed into TypeScript. 
My fear is that hacking that to work in Yari + Fiori is more work than just writing it from scratch as a proper React component. 

It actually won't be that hard (to rewrite it in React + TypeScript). It's just a matter of excellent timing related to Fiori. 
I could attempt something today, using `kumastyles` but `kumastyles` is dying and if I do it as part of the Fiori branch, that'll make Fiori even more complicated to land into `master`.

**Comment by peterbe** [comment]
After chatting to @ddbeck and @chrisdavidmills we decide to opt for a much simpler solution: https://github.com/mdn/yari/pull/1360

The new solution is just a hyperlink with a fairly large query-string on it. 
* HTML - 965 bytes
* JS - 926 bytes
* CSS - 0 bytes

The old solution had a dedicated JS but its SCSS gets interspersed into the main CSS bundle. But roughly...
* HTML - 7,650 bytes
* JS - 23.6 KB (8.1KB gzipped)
* CSS - 9,421 bytes
* Images - ~3KB 

It's hard to compare because gzip is prevalent and it reduces the absolute difference. But the 8.1KB JS bundle adds a CPU load that is not insignificant. And the almost 10KB of CSS definitely adds to the render-blocking which we know is our biggest web perf fault. 

So, YAY!! for a much more performant solution.

**Comment by peterbe** [comment]
Oh, and let's not forget that this is a feature actually has a very attractive end-function solution. Instead of the overheard of the Django Admin and having to port these. Now, the GitHub issues, that get filed, are vetted (needs a GitHub account), always have a link to the page and BCD Query ID, and it finally becomes possible to actually have a discussion with the person who filed it.

**Comment by peterbe** [comment]
In my celebration-blather, I forgot why I came here in the first place.
