### ISSUE TITLE
{{LiveSampleLink}} macro did not work properly

### ISSUE THREAD

**Issue by yin1999** [mdn/yari#9485]
### Summary

The `{{LiveSampleLink}}`macro did not work any more.

Check the link generated by LiveSampleLink macro in [this section](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples#result): https://live.mdnplay.dev/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples/runner.html?id=Live_sample_demo

It would be an empty page.

### URL

Section: https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples#result
Live sample URL: https://live.mdnplay.dev/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples/runner.html?id=Live_sample_demo

### Reproduction steps

1. navigate to https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Page_structures/Live_samples#result
2. click the "Live sample demo link" link
3. Got an empty web page.

### Expected behavior

We could see the correct document.

### Actual behavior

Got an empty web page.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Android

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by wbamberg** [comment]
I asked about this broken macro a week or so ago and there was some support from the writing team for removing this macro. I'll probably file some PRs for that next week, we'll see if it can be removed!

**Comment by yin1999** [comment]
Thanks for the clarification @wbamberg. I'm trying to rewrite the example [here](https://developer.mozilla.org/en-US/docs/Web/Guide/Printing#open_and_automatically_close_a_popup_window_when_finished) with `{{LiveSampleLink}}` macro. Do you think it's also a good idea to use `{{EmbedLiveSample}}` instead?

**Comment by wbamberg** [comment]
> Thanks for the clarification @wbamberg. I'm trying to rewrite the example [here](https://developer.mozilla.org/en-US/docs/Web/Guide/Printing#open_and_automatically_close_a_popup_window_when_finished) with `{{LiveSampleLink}}` macro. Do you think it's also a good idea to use `{{EmbedLiveSample}}` instead?

I think if you can use just `{{EmbedLiveSample}}` it's almost always better to do that. If you can't, maybe use `{{EmbedGHLiveSample}}`? Or honestly it could be made a non-live example - the example already shows some terrible practices, so having a non-live good practice example would IMO be a net improvement.

**Comment by mirunacurtean** [comment]
@yin1999 There has been work done affecting the macros and from checking I noticed the link now works across several browsers: F, Chrome, Safari. Could you double check and let us know if you can still reproduce this?
![image](https://github.com/user-attachments/assets/c10f10c9-c5db-4e66-8ff3-35b5ec607881)

**Comment by yin1999** [comment]
> @yin1999 There has been work done affecting the macros and from checking I noticed the link now works across several browsers: F, Chrome, Safari. Could you double check and let us know if you can still reproduce this?

I could open the page that displays correctly, thanks for the feedback on this issue :pray:
