### ISSUE TITLE
Make BCD table not look too bad

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#949]
Yari has its own BCD table implementation. So using the `wiki-compat-tables.scss` file from `kumastyles` doesn't work very well. 
In fact, the SCSS all sits in [`search.scss`](https://github.com/mdn/yari/blob/master/client/src/document/ingredients/browser-compatibility-table/bcd.scss) which is a "component level" SCSS file. 

I don't think the Yari BCD tables need to be perfect. Especially not pixel perfect compared to Kuma. If we go to prod with Yari1, this BCD table implementation will be the only implementation so there's no need to compare with Kuma any more. This is unlike the header which needs to be visually identical. 

<img width="1084" alt="Screen Shot 2020-07-21 at 4 45 31 PM" src="https://user-images.githubusercontent.com/26739/88105250-9f258280-cb71-11ea-946a-ef59433da223.png">

I think it's fairly self-explanatory what the problems are:

- icons in row 1 and 2 and inner cells aren't centered. 
- missing borders
- missing outer border
- The "Update compatibility on GitHub" is missing the external svg icon

Another thing that would be nice to fix is that the `bcd.scss` file isn't really proper SCSS. It was actually, originally, created by pretty-printing the BCD stuff from Kuma's rendered CSS bundle. 
So, instead of indenting, it repeats the `.bc-table` prefix on every selector on a new line.

**Comment by peterbe** [comment]
Let's build this on top of the `kumastyles` branch.

**Comment by schalkneethling** [comment]
This work will happen as part of https://github.com/mdn/mdn-fiori/issues/258

**Comment by peterbe** [comment]
> This work will happen as part of [mdn/mdn-fiori#258](https://github.com/mdn/mdn-fiori/issues/258)

CC @tobinmori 

If we can resolve it in the `kumastyles` branch first, we should be able to have a working Yari 1 platform which we could ship. We probably don't want to ship it to `developer.mozilla.org` but I think it'd be a good idea to ship it to something like `yari.developer.allizom.org` or something like that. Then we can start a second round of "PVP testing" (but not user interviews on Zoom) where we ask the content folks to make some PRs, and see their work appear on a site on the internet. In that round it would be nice if it doesn't look too horrible. 

It all depends on how long we reasonably think you (Schalk, Mustafa, Gregor?) can fully implement Fiori, technically, into the code. Considering that no matter where we are with the `master` branch, `kumastyles` or `water.css`, we probably will start from scratch and slowly build it up. No?

So, can we consider NOT waiting for this to be solved in Fiori? I guess it all boils down to wasted cycles of time vs. Fiori not being ready to fully use in Yari in time. What do you think?

**Comment by schalkneethling** [comment]
@peterbe Oh, I meant that the CSS portion will make it into kumastyles. What I am trying to find are opportunities where we can have something in a sprint regarding the design system that has a clear and tangible impact on Yari, Kuma, or both. This feels like one of those opportunities where I can move all the pieces into Fiori, resolve any CSS and possibly HTML issues, and immediately contribute those back to Yari.

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/pull/1536
