### ISSUE TITLE
Make the auto-complete search widget look OK in responsive mode

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#950]
In `kumastyles` we married our auto-complete search widget with the search input field we have in the "kuma header". It looks like this:
<img width="734" alt="Screen Shot 2020-07-21 at 4 58 54 PM" src="https://user-images.githubusercontent.com/26739/88106487-8e760c00-cb73-11ea-8074-1f16d28b6080.png">
It's not perfect, but it's a buncha' better what nothing and it can be iteratively improved. 

However, in responsive mode is look pretty bad. Let's fix that. 
<img width="764" alt="Screen Shot 2020-07-21 at 5 00 29 PM" src="https://user-images.githubusercontent.com/26739/88106596-bf564100-cb73-11ea-9a72-bb50648a62c4.png">

**Comment by schalkneethling** [comment]
Resolved by https://github.com/mdn/yari/issues/1369
