### ISSUE TITLE
WebExtExamples macro missing

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#951]
Example use: http://localhost.org:3000/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs#_flaws

<img width="1092" alt="Screen Shot 2020-07-22 at 7 36 37 AM" src="https://user-images.githubusercontent.com/26739/88173534-bd7e9300-cbf0-11ea-9801-444a0b8dc407.png">

Because there is [no such macro](https://github.com/mdn/yari/tree/674e331d2f79f3c340339f31cf80b387b2bf7e60/kumascript/macros)

**Comment by peterbe** [comment]
Most possibly, we dropped it because it relies on an unreliable [network fetch](https://github.com/mdn/kumascript/blob/4cd552126dd3eefe8e2981d857bf8638c2ca147f/macros/WebExtExamples.ejs#L23)
So it's not a matter of just copying the `WebExtExamples.ejs` file.

**Comment by escattone** [comment]
I removed that macro in https://github.com/mdn/yari/pull/804 not only because it uses the network, but also because I didn't think it was used any longer at that time.

**Comment by escattone** [comment]
Yes, I just checked and at the time of #804, the `content/files/en-us/mozilla/add-ons/webextensions/api/*` files didn't exist at that time (they arrived in #808).

**Comment by peterbe** [comment]
So, back to the drawing board on this one a bit?

**Comment by escattone** [comment]
> So, back to the drawing board on this one a bit?

Unfortunately, yes. I'll need to look into what we can do here. Thanks for noting this as an issue @peterbe.

**Comment by escattone** [comment]
Some additional information:
- The `WebExtAllExamples.ejs` macro is also missing.
- Both the `WebExtExamples.ejs` and `WebExtAllExamples.ejs` macros reference examples maintained at https://github.com/mdn/webextensions-examples, and perform a fetch of https://raw.githubusercontent.com/mdn/webextensions-examples/master/examples.json to get a list of all of the examples.
- The https://raw.githubusercontent.com/mdn/webextensions-examples/master/examples.json file changes infrequently, on the order of 10 times or less per year (see https://github.com/mdn/webextensions-examples/commits/master/examples.json).

**Comment by peterbe** [comment]
We could have a little bash/node script that just makes sure these files are cached on disk. 
For most humans, who download and work with yari locally, they can run these things once and I very much doubt they mind it being too old.
For production (aka CI), where we don't really have a persisting disk, we can just download it every time. Something like this:

```python
p = Path('kumascript/macros/webextensions-examples.json')
if not p.exists() or p.stat().ctime < time.time() - 3600 * 24 * 100:
    with open(p, 'w') as f:
        f.write(requests.get("https://raw.githubusercontent.com/mdn/webextensions-examples/master/examples.json").text)
```

Now, add `/kumascript/macros/webextensions-examples.json` to `.gitignore`. 
And this script would be executed from the `Procfile` or the `.github/workflows/prbuilds.yml`. 

PS. I mean, the script should probably be Node, but I still find it easier to express pseudo-code in Python.
