### ISSUE TITLE
U - As the PM I want a contribution guide for Yari, so we can identify missing parts

### ISSUE THREAD

**Issue by atopal** [mdn/yari#953]
# Acceptance Criteria
- [ ] Draft contribution guide with placeholders created
- [ ] Missing items listed
- [ ] For each missing item: decision made on whether to support
- [ ] Issues filed for missing features we want to support
- [ ] Missing features triaged and assigned to milestones

# Sprint Ready Checklist 
- [x] - Team understands ACs
- [x] - No per-requisities 

# Solution Steps: 
- [ ] - Take Kuma contribution guide and copy headings into a new Google doc 
- [ ] - Review and decide how to do it in Yari instead of Kuma. Make note of items that can't be done in Yari
- [ ] - For each missing item, make a decision to keep / not and file issue for it 
- [ ] - Review list in Triage meeting 
- [ ] - Estimate cost of effort with Team

**Comment by atopal** [comment]
https://docs.google.com/document/d/1p7omstmMRW0WxT_uS6m8qS-B-kMl9nRCC9NW6ctTwSo/edit#

**Comment by peterbe** [comment]
Let's just stick to https://github.com/mdn/yari/issues/1113 for now.
