### ISSUE TITLE
U -  Decision whether we should have just a CLI and no GUI

### ISSUE THREAD

**Issue by chinikes** [mdn/yari#954]
# User Story 
U - Decision whether we should have just a CLI and no GUI to provide so that when we have a better idea of the **scope for the Yari MVP** 

# Acceptance Criteria:
- [ ] CLI option explored as a one pager (pro/con/mitigations)
- [ ] GUI option explored as a one pager (pro/con/mitigations)
- [ ] Proposal shared for input
- [ ] Decision made and communicated

# Sprint Ready Checklist 
- [x] - Team understands ACs
- [x] - No per-requisities

**Comment by peterbe** [comment]
Or, changed GUI.
