### ISSUE TITLE
T - Fully integrate KS rendering and related flaws into the refactoring branch

### ISSUE THREAD

**Issue by Gregoor** [mdn/yari#957]
**Acceptance criteria:**
- [x] Renders all the KS macros
- [x] Builds live-sample pages
- [x] KS related flaws are shown when viewing a page
- [x] KS related fixable flaws work
- [x] KS tests pass

**Comment by escattone** [comment]
This is really close but not yet done. The building of live-samples on-the-fly within the local server is broken (the sample ID's are always lower-cased which breaks the case-sensitive ID's).

**Comment by escattone** [comment]
We should be able to close this once https://github.com/Gregoor/yari/pull/13 lands.
