### ISSUE TITLE
Broken redirect rules in `fundamental-redirects`

### ISSUE THREAD

**Issue by yin1999** [mdn/yari#9664]
The redirect rules list [here](https://github.com/mdn/yari/blob/1d1a9b4bb30b8b1405c841d398e4779d98fd8576/libs/fundamental-redirects/index.js#L324-L388C5) are leading to nonexistent files. Should we remove them?

**Comment by caugner** [comment]
@yin1999 Yes, good idea, let's remove those! 👍
