### ISSUE TITLE
Make the colors of the visited and not visited links different

### ISSUE THREAD

**Issue by izh1979** [mdn/yari#9672]
### Summary

Currently visited and not visited links are having the same blue color. This is very inconvenient when, e.g., trying to learn JS, because you can't easily see, what pages you have already read.

### URL

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Synchronous_and_Asynchronous_Requests

### Reproduction steps

1. Open any page.
2. Visit any link.
3. See no difference in color of the visited and not visited links.

### Expected behavior

Visited links should have different color.

### Actual behavior

Visited links have the same color as not visited.

### Device

Desktop

### Browser

Firefox

### Browser version

Stable

### Operating system

Windows

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Re-opening, as #9907 was reverted in https://github.com/mdn/yari/pull/9922 due to a regression it caused.
