### ISSUE TITLE
Blank page if CSS is disabled

### ISSUE THREAD

**Issue by crystalcrag** [mdn/yari#9695]
### MDN URL

https://developer.mozilla.org/en-US/docs

### What information was incorrect, unhelpful, or incomplete?

Disabling CSS via View ► Page Style ► No style cause a .... javascript error ... causing the page to be blank.

Accessibility these days ... it is not was it used to :-/

All URLs below the one mentioned above seems to have this "problem".

### What did you expect to see?

Not a blank page, I guess ?

**Comment by fiji-flo** [comment]
fixed via #9707
