### ISSUE TITLE
AI Help button should only be visible when logged in.

### ISSUE THREAD

**Issue by estelle** [mdn/yari#9768]
### Summary

The AI help in the navigation bar should only be present if logged in.

<img width="1000" alt="Screenshot of MDN ai help page when logged out" src="thttps://github.com/mdn/yari/assets/69888/03eca46a-0ef8-46ed-9029-f48dece05dd3">

This it not the same bug saying "this button should not exist". This is a bug saying "this button should only be visible when it is usable"

### URL

All https://developer.mozilla.org page

 https://developer.mozilla.org/en-US/plus/ai-help is not useful when not logged in. There should not be a link to it in the nav bar unless logged in.

### Reproduction steps

1. Go to https://developer.mozilla.org
2. log out
3. Look at the top navigation bar and click on AI help link
4. Ask yourself why important real estate on the home page was dedicated to a link to this page.

### Expected behavior

When the user is logged out,  button to features only available when logged in should not be visible

### Actual behavior

When the user is logged out, a  button to a feature that is not available is visible. Clicking on the link takes you to a page that is not usable. The page has three components: the top makes it look like it's available. The second is a warning. The third has some duplication of the top nav bars with a sentence that can be made useful by making it more prominent, but it isn't well hilighted/promoted.

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

<img width="1000" alt="Screenshot 2023-09-15 at 3 02 20 PM" src="https://github.com/mdn/yari/assets/69888/5c6393ab-dd49-4cf2-b131-9d967c01292a">

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by s-sood** [comment]
Hi @estelle Thank you for submitting this issue and your idea. Currently, We expose AI Help to non-logged in users as part of discoverability strategy with the intent of letting them know that this feature exists. We won't be able to address this issue right away but we are working on making sure that we have a consistent and clear way to expose MDN Plus features to the users. This work is in progress in Q4.

**Comment by mirunacurtean** [comment]
Hello @estelle. I was looking for a different ticket but noticed we still have his AI Help button issue open. The AI Help page has had a new design since the end of last year, with only **Log in** and **Sign up for free** buttons visible. I think this issue can be closed now, do you agree? 

![image](https://github.com/user-attachments/assets/d34f67ac-4c47-4c08-9dd1-53aabbdc0b0b)
![image](https://github.com/user-attachments/assets/be485ccd-11d5-44a2-aebd-744a3007fec8)

**Comment by estelle** [comment]
Much better. The original had accessibility issues (cognitive). This works so much better! yup, this can be closed. thanks.
