### ISSUE TITLE
LIVE_SAMPLES_BASE_URL is clunky for most people

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#977]
First of all, https://github.com/Gregoor/yari/pull/14 fixes a problem of *naming* consistency. 

The problem is this: **By default**, you get this:
<img width="1289" alt="Screen Shot 2020-07-29 at 9 12 18 AM" src="https://user-images.githubusercontent.com/26739/88804268-a81ee100-d17b-11ea-97cd-189e8dc2e594.png">

The only way to not get that is to read the docs to find out you need to...
```
echo "BUILD_KS_LIVE_SAMPLES_BASE_URL=http://localhost:5000" >> .env
```
and kill the `yarn start` and start it up again. 

I know I know. Defaults should be secure by default. But this might be a matter of exception. What do you think? @escattone @Gregoor 

What I envisioned is that there'll be a dedicated GitHub Action that runs `yarn build` (no filtering!) and it's prepping everything in its power to make the resulting `client/build/` ready to go into production (ie. S3).
There has to be a place anyway where we put things like enabling SpeedCurve, Google Analytics, Stripe Public Key, etc. 
Can we make a compromise and make `LIVE_SAMPLES_BASE_URL` default for local "development" (aka. content writers firing up Yari to preview their content edits).

**Comment by peterbe** [comment]
@escattone I'm still torn on this one. Suppose that we have 100 contributors to the content, all 100 of them (who spin up `yarn start` and browse `http://localhost:3000`) should/need to override the samples base URL. 
But I'm still a security-paranoido and I think it's dangerous to make the default dangerous because I will never accept that live samples run in the same domain as the content because although we're not the Wiki any more, we're still not there to audit every code example. 

But how about this as a nice compromise. We change the hardcoded default to `http://localhost:5000` and in the prod `yarn build` (before we send it to the Yari deployer) we override it there. That way there's only exactly 1 place were it needs to be set. And god forbid we screw that up and accidentally typo the env var or something (which is the reason settings should be secure by default because this does happen) the worst that can happen is that we publish, to `developer.mozilla.org` HTML pages that look like this:
```html
<iframe src="http://localhost:5000/en-US/docs/Foo/_samples_/index.html">
```
That's not going to be a security risk. Just plain wrong and obviously needs to be fixed asap but does have the advantage that it's A) practical for ALL contributors to the content, B) not dangerous in terms of security.

**Comment by peterbe** [comment]
I.e. what I'm proposing is that we change the default value [here](https://github.com/mdn/yari/blob/7c04c06d91bc1d11ed24dacc76874242b446d62b/kumascript/src/constants.js#L2) to `"http://localhost:5000"` and we also add `export BUILD_LIVE_SAMPLES_BASE_URL=https://mdn.mozillademos.org` inside the `.github/workflows/production-build.yml`.

**Comment by escattone** [comment]
@peterbe 👍 That sounds good to me.
