### ISSUE TITLE
Should we have a breadcrumb on "root" pages

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#978]
[In prod](https://developer.mozilla.org/en-US/docs/Web) you get this:
<img width="803" alt="Screen Shot 2020-07-29 at 10 44 18 AM" src="https://user-images.githubusercontent.com/26739/88814946-bd4e3c80-d188-11ea-8754-f86507342229.png">

For the record, in Yari you get this:
<img width="617" alt="Screen Shot 2020-07-29 at 10 46 34 AM" src="https://user-images.githubusercontent.com/26739/88814995-cc34ef00-d188-11ea-818f-dfa6daf0a985.png">
(yes, I know the bottom border is present even though there's nothing in there but that's not important)

How Yari does it doesn't actually matter. We have a choice. We can either make a rule that there should ALWAYS be a breadcrumb since when you include "itself" you always have at least one item. Or, we can do it like Yari happens to do it which is: "If there are no parents, don't even bother with self"

- **Are the breadcrumbs of any value when there are no parents?**
- Should we consider linking to the home page (aka. `/en-US/`) when you're at some of these core landing pages?
- What is the "defacto HCI best practice" on breadcrumbs independent of SEO, past, or what's possible?

**Comment by malqinneh** [comment]
Re: SEO; there is no difference whether we show or hide the current page/item in the breadcrumbs.

Re: UX; it's better to avoid redundancy (adopt Yari UX)

**Comment by peterbe** [comment]
Perhaps all we need to do is that if there are no parent docs, drop the whole thing including that bottom-border. But that area is also reserved for a language switch drop-down which we still need to make a decision about.

**Comment by peterbe** [comment]
@schalkneethling Let's just make an executive decision here that **if you're on a level-1 document** (ie. when there is no parent document) **we simply don't do the breadcrumb at all**. 

In Kuma, we used to have that rectangular area for "[breadcrumbs] ........................... [language drop-down]" and we need to keep that in mind. 
What we need to do is something like this:

```javascript
if (hasBreadcrumbs() || hasLanguages()) {
  return <div className="lower-nav-bar">
    {hasBreadCrumbs() && <ShowBreadcrumbs/>}
    {hasLanguages() && <ShowLanguageDropdown/>}
  </div>
}
```
