### ISSUE TITLE
"yarn build" should fail, if it fails

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#981]
As of today, if anything unexpected goes wrong deep inside `yarn build` it actually exits with a 0. 

We'll be using `yarn build` in CI for both testing and for PR builds and fully production builds. If we have a bug, that's causing an unexpected error, it should break the build. For example, the [PR builds](https://github.com/mdn/yari/blob/dde924cd058e2c8a0b3ef72f0a9ef6c86c5cd956/.github/workflows/pr-build.yml#L87) will always be green. 
And [the functional test](https://github.com/mdn/yari/blob/dde924cd058e2c8a0b3ef72f0a9ef6c86c5cd956/testing/scripts/functional-test.sh#L8) suite shouldn't start if the `yarn build` command didn't work because we use `set -e`.

**Comment by Gregoor** [comment]
[It does](https://github.com/mdn/yari/blob/master/build/cli.js#L124), I added that line after your suggestion yesterday 🙂

**Comment by peterbe** [comment]
That was quick :)
