### ISSUE TITLE
Unable to recognize definition term hyperlinks in definition lists

### ISSUE THREAD

**Issue by OnkarRuikar** [mdn/yari#9810]
### Summary

After https://github.com/mdn/yari/pull/8413 landed all the definition terms got same formatting. Now it is not possible to recognize hyperlinks for these terms.

### URL

https://developer.mozilla.org/en-US/docs/Web/CSS/border

### Expected behavior

The definition term hyperlinks be recognizable.
This is how it looked prior to the changes:
https://web.archive.org/web/20231011150428/https://developer.mozilla.org/en-US/docs/Web/CSS/border#values
> ![_1](https://github.com/mdn/yari/assets/87750369/f1e819c3-794d-463c-908e-f5a34d9a4992)

Not asking to completely revert the changes but to fix/improve the implementation.

### Actual behavior

> ![_3](https://github.com/mdn/yari/assets/87750369/fd465047-3d9b-45bb-bbd6-64f955d5ec59)

cc/ @estelle

**Comment by estelle** [comment]
Thank you!!!!!!
