### ISSUE TITLE
Modified date and wikihistory

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#984]
In the Reductio work we lost something and that's that it used to open & parse the `en-us/_wikihistory.json` file and have it all in memory during the build. In Reductio (which is now `master`) we only use the `$locale/_wikihistory.json` when we serialize the sitemap XML files. I think we should reinstate it. We can do it lazily or load it into memory when the `cli.js` file is loaded.

**Comment by peterbe** [comment]
What do you think @Gregoor ?
We could just move [these lines](https://github.com/mdn/yari/blob/2ecbebffe1f4d28e53b5e788056c5c25d100234f/build/cli.js#L15-L20) to sit outside the `makeSitemapXML` function and now you can do something like

```diff
-    const [builtDocument, liveSamples] = await buildDocument(document);
+   const [builtDocument, liveSamples] = await buildDocument(document, wikiHistory);
```
or
```diff
-    const [builtDocument, liveSamples] = await buildDocument(document);
+   const [builtDocument, liveSamples] = await buildDocument(document, {modified: wikiHistory[document.url] || null});
```

**Comment by peterbe** [comment]
The context of this is that in `kumastyles`, which will soon be merged into `master`, we're now finally displaying each document's `modified` date near the bottom of the document.

**Comment by Gregoor** [comment]
Another option would be to extract the wikiHistory read&parse lines you mentioned into its own memoized function a la
```javascript
const readWikiHistory = memoize(() => JSON.parse(fs.readFileSync(WIKI_HISTORY_PATH)));
```
and then call that directly inside `buildDocument` a la:
```javascript
doc.modified = readWikiHistory()[document.url] || null;
```

Both options work for me though :)

**Comment by peterbe** [comment]
I'm not exactly sure how or which work fixed it, but it's fixed now.
