### ISSUE TITLE
Update Twitter logo on the MDN website to X.

### ISSUE THREAD

**Issue by adityadeshpande09** [mdn/yari#9864]
### MDN URL

https://developer.mozilla.org/en-US/

### What specific section or headline is this issue about?

The twitter (X)  logo in the footer must be updated.

### What information was incorrect, unhelpful, or incomplete?

The twitter logo in the footer is incorrect.
![image](https://github.com/mdn/content/assets/98452243/5e04d1a2-06cf-46d5-bcdf-ef6d976a2eac)

### What did you expect to see?

The new twitter (X) logo must be placed there.

**Comment by caugner** [comment]
We discussed this issue internally and are accepting PRs to replace the Twitter logo with the X logo.

@adityadeshpande09 Feel free to open a PR referencing this issue! 🙌

**Comment by adityadeshpande09** [comment]
I am having the following error while trying to run the project on codespaces:
![image](https://github.com/mdn/yari/assets/98452243/fd698661-c65c-4b8c-9714-f5eed5553e01)
Any suggestions ?

**Comment by roy9495** [comment]
Hi, can I work on this issue?
