### ISSUE TITLE
Sentry integration on client-side

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#99]
It needs to work in a way that if you don't put a `SENTRY_DSN_PUBLIC` (or whatever it's called) in your `.env` it should still work.

**Comment by tobinmori** [comment]
Use events instead of crashes?

**Comment by peterbe** [comment]
Let's not treat JS crashes as Sentry crashes. It'll be too noisy. However, we should someday consider sending errors as events to either Google Analytics or to Sentry. But it's not a high priority.
