### ISSUE TITLE
The headings have been styled as normal links

### ISSUE THREAD

**Issue by yin1999** [mdn/yari#9921]
### Summary

The headings have a color added, which look like regular links. It does confuse readers to figure the links which are navigating to other documents.

### URL

https://developer.mozilla.org/en-US/docs/Web/API/Crypto

### Reproduction steps

1. Open the above URL
2. Check the style of "h2~" headings

### Expected behavior

Check screenshot below

### Actual behavior

Check screenshot below

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Android

### Screenshot

**Now** (Actual)

![image](https://github.com/mdn/yari/assets/15844309/22195ded-a551-4116-a3ed-f58057e5af9f)

**Before** (Expected)

![image](https://github.com/mdn/yari/assets/15844309/803921e2-f19b-4c45-8669-e19b69e68ddc)

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by OnkarRuikar** [comment]
- Looks like it has been fixed: https://github.com/mdn/yari/pull/9922

**Comment by yin1999** [comment]
Thanks for the note @OnkarRuikar! I'm going to close this issue.
