### ISSUE TITLE
TS type definitions for docData

### ISSUE THREAD

**Issue by peterbe** [mdn/yari#993]
In `<Document/>` you might get an optional prop `doc` but we don't have type definitions for it. We should. It makes TS life happier.

**Comment by peterbe** [comment]
Also, see https://github.com/mdn/yari/pull/994 which would benefit from this.

**Comment by peterbe** [comment]
For the record, [this](https://github.com/mdn/yari/blob/a51b9a51f231fd76dd13a3860e16c366399cd0d6/client/src/document/index.tsx#L27) is what we hope to fix.

**Comment by caugner** [comment]
Meanwhile we have extensive types for `Doc`:

https://github.com/mdn/yari/blob/bfd20d4457f4f5df0ce246a8e35d59ab25c28fe1/libs/types/document.ts#L129-L160
