### ISSUE TITLE
Error in the CSS Styles Page

### ISSUE THREAD

**Issue by LautaroMRA02** [mdn/yari#9942]
### Summary

I have identified an error on the MDN Web Docs CSS Styles page. It's located in the 'sticky-header-container' class. This issue affects the display of the documentation.

### URL

https://developer.mozilla.org (all page)

### Reproduction steps

1. Upon entering the page, the header overlays all the page content.

### Expected behavior

1. El header shouldn't cover the entire main element of the page.

### Actual behavior

The page content is not visible because the navigation bar covers it. 

### Device

Desktop

### Browser

Chrome

### Browser version

Stable

### Operating system

Linux

### Screenshot

![Screenshot from 2023-11-05 17-15-31](https://github.com/mdn/yari/assets/79938359/7f4d48fd-c115-4cb2-bec7-8a6d400413ad)

### Anything else?

In the 'sticky-header-container' class and its children, the CSS error is located.
https://github.com/mdn/yari/blob/423c86e44221192daf8a000d8a8152ceca2625b7/client/src/app.tsx#L58C40-L58C40

https://github.com/mdn/yari/blob/423c86e44221192daf8a000d8a8152ceca2625b7/client/src/ui/organisms/top-navigation-main/index.scss#L3

Sorry if I'm not being clear, it's my first issue. 🥲 

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
Hi @LautaroMRA02, thanks for taking the time to raise this issue. 👍 

I'm unable to reproduce the issue on Chrome 119. Could you please double-check that you still experience the issue when you disable all your Chrome extensions (e.g. by running it with `--disable-extensions`)?

**Comment by LautaroMRA02** [comment]
I found the issue. The problem was caused by a certain X extension that was conflicting with similar CSS classes on the MDN web page. I've removed the extension now.

**Comment by caugner** [comment]
Thanks @LautaroMRA02, glad to hear you were able to resolve the issue! 👍
