### ISSUE TITLE
Visited links are unreadable in dark mode

### ISSUE THREAD

**Issue by Elchi3** [mdn/yari#9958]
### Summary

I think the color of the visited links in dark mode is unreadable. 

### URL

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some

### Reproduction steps

See screenshot or go to the provided URL and visit some links in dark mode.

### Expected behavior

Readable visited links in dark mode

### Actual behavior

Unreadable visited links in dark mode

### Device

Desktop

### Browser

Safari

### Browser version

Stable

### Operating system

Mac OS

### Screenshot

<img width="410" alt="Bildschirmfoto 2023-11-07 um 15 14 28" src="https://github.com/mdn/yari/assets/349114/e7e839f3-6fc8-4d98-a42f-ec66bd34ad89">

### Validations

- [X] I have read the [Community Participation Guidelines](https://www.mozilla.org/en-US/about/governance/policies/participation/).
- [X] I have verified that there isn't [already an issue](https://github.com/mdn/yari/issues) that reports the same bug to avoid creating a duplicate.
- [X] I have checked that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/orgs/mdn/discussions/categories/platform).

**Comment by caugner** [comment]
This is interesting. They are readable in Chrome and Firefox, but indeed not readable in Safari:

| Chrome | Firefox | Safari |
|--------|--------|--------|
| <img width="386" alt="image" src="https://github.com/mdn/yari/assets/495429/f6e5504d-6dff-4c83-8f93-a96cf5dface5"> | <img width="386" alt="image" src="https://github.com/mdn/yari/assets/495429/d13fde57-9f28-4e82-a3ca-9fce23f6ce68"> | 
<img width="386" alt="image" src="https://github.com/mdn/yari/assets/495429/7110f181-a256-4d11-a59f-e85139d491a2"> |

**Comment by caugner** [comment]
We discussed this issue internally and believe that this is a Safari issue (not providing a better visited link color for the dark theme), but we will address this by adopting the visited link colors (dark/light theme) from Firefox.

**Comment by caugner** [comment]
The fix is now being deployed to stage.

@Elchi3 Would you mind verifying the fix in about 30 minutes (or tomorrow/Wednesday) on https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some#see_also? 🙏

**Comment by Elchi3** [comment]
> The fix is now being deployed to stage.
> 
> @Elchi3 Would you mind verifying the fix in about 30 minutes (or tomorrow/Wednesday) on https://developer.allizom.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some#see_also? 🙏

LGTM 👍  Thanks for the very quick fix 🎉 

![Bildschirmfoto 2023-11-08 um 09 43 27](https://github.com/mdn/yari/assets/349114/5656852d-54a7-4a71-8d20-50ab66676bf4)

**Comment by caugner** [comment]
Thanks @Elchi3, the fix is now being deployed to production.
